### ISSUE TITLE
problem when using conditional constraints on portfolio optimization

### ISSUE THREAD

**Issue by lijuanLin** [cvxgrp/cvxpy#1007]
hi! I am using cvxpy to do portfolio optimization and I got some problem.

```Python
n = len(factor_data) #the number of stock is nearly 3300
weight = cvx.Variable(n)  
exposure = alpha.T * (weight - w_bench) #factor exposure

objective = exposure
turnover = cvx.abs(weight - w_last)
f_style = X_style.T * (weight - w_bench)  #style exposure
f_ind = X_ind.T * (weight - w_bench) #industry exposure

###tracking error
cov_matrix = np.dot(np.dot(exposure_matrix,factor_covariance_matrix),exposure_matrix.T) + spec_ret
error = cvx.quad_form(weight-w_bench, cov_matrix)
contraints = [cvx.sum(turnover) <= 1, cvx.sum(weight) == 1, weight >= 0, weight <= 0.05, f_style >= -0.01,f_ind >= -0.01, f_style <= 0.01, f_ind <= 0.01, error <= 0.07 * 0.07 / 250]
prob = cvx.Problem(cvx.Maximize(objective), constraints=contraints)
prob.solve(solver=cvx.MOSEK)
print(prob.status)
```

when i run this code, it can get the optimal result, but the number of none zero weight is nearly 1600, it means we need to hold half of the stock in the market, which is hard to achieve. So I want to add constraints of the stock number we hold.

```python
stock_number = cvx.sum([0 if weight[i] <= 0 else 1 for i in range(n)])
contraints = [stock_number <= 100,....]
```

and I got the error

Exception: Cannot evaluate the truth value of a constraint or chain constraints, e.g., 1 >= x >= 0.

I have no idea how to add this constraints and make it work.

Hope you can help me solve this problem.

Thank you in advance.

**Comment by aszekMosek** [comment]
This is a modeling question rather than a cvxpy issue. Since you are using Mosek you can look at https://docs.mosek.com/modeling-cookbook/mio.html#avoiding-small-trades or https://docs.mosek.com/9.2/pythonfusion/case-studies-portfolio.html#doc-card-constraints, they both contain examples of how to use binary variables to achieve your cardinality bounds and similar other penalties.
