### ISSUE TITLE
Feasiblitity/Optimality Cuts: CVXPY access value of constraints

### ISSUE THREAD

**Issue by rtolsma** [cvxgrp/cvxpy#1008]
I'm trying to write up an implementation for the Nested Benders Algorithm in cvxpy, but I'm running into some difficulties capturing the values of the constraints for generating cuts.

Are there ways to inspect the value of the LHS or RHS of a constraint? Alternatively, are there methods for symbolically interchanging parameters and variables?

For example, I have an MIP subproblem with constraints Wx <= h - Ty, where y is the fixed value of a solution of the parent problem, and I want to add a feasibility cut of the form v^T (h - Ty) < = 0 in the parent problem with y now being a variable to be optimized over. Is there a good way to approach this?

**Comment by rileyjmurray** [comment]
CVXPY ``Inequality`` constraint objects have an attribute called ``expr``. If you have a constraint ``constr = x1 <= x2`` then ``constr.expr.value == x1.value - x2.value``. If you have a constraint ``constr = x1 >= x2`` then it's the opposite: ``constr.expr.value == x2.value - x1.value``.

As for symbolically interchanging parameters and variables, I'm actually not so sure. This isn't possible with CVXPY ``Parameter`` objects, but you might have success with the [partial_optimize transform](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/transforms/partial_optimize.py).

I'm closing this issue for now. If you have more questions on this topic feel free to comment on this thread.
