### ISSUE TITLE
Multiplying constraints by a Cvxpy variable

### ISSUE THREAD

**Issue by robertmartin8** [cvxgrp/cvxpy#1009]
**Is your feature request related to a problem? Please describe.**

I have asked this on [StackOverflow,](https://stackoverflow.com/questions/61338298/cvxpy-converting-a-nonlinear-constraint-to-an-equivalent-linear-constraint) but a summary is below.

I am building a library which uses `cvxpy` on the backend. Users can pass their constraints as a lambda function, for example to make weights greater than 0.01, they pass `lambda w: w >= 0.01`. On the backend, I pass a `cp.Variable(n)` into this lambda function, which results in a valid cvxpy constraint (which I then give to a `cp.Problem` and solve).

**Describe the solution you'd like**

However, in some cases I need to transform the problem, e.g to turn the constraint into `w >= k * 0.01` where `k` is some scalar `cp.Variable`. In essence, I am trying to find some way of converting the _already existing_ cvxpy constraint `w >= 0.01` to `w >= k * 0.01`. Perhaps there is some API for decomposing an _already instantiated_ constraint so that I can put in a variable?

**Describe alternatives you've considered**
Alternatively, I have tried to construct the transformed version directly from the user's lambda function. So I tried passing `w/k` into the lambda function to give `w/k >= 0.01`, which I hoped would be equivalent to `w >= k * 0.01`, but this is not DCP. 

I also tried multiplying the entire constraint `w/k >= 0.01` by `k`, but you can't multiply constraints in `cvxpy`. Is it possible to break down a constraint into the two expressions on either side?

**Comment by akshayka** [comment]
> Perhaps there is some API for decomposing an already instantiated constraint so that I can put in a variable?

Constraints are immutable by design. Immutability simplifies much of CVXPY’s logic.

Why not construct a new constraint? You can certainly inspect the left and right hand sides of the constraint. Right now, that can be done by inspecting the args attribute (see https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/constraints/nonpos.py#L97).

**Comment by robertmartin8** [comment]
Hi Akshay,

My fault for terrible wording! I've made great use of cvxpy's immutability, so wasn't suggesting that I mutate the constraint in place – rather, I was trying to emphasise that my starting point is an already-instantiated cvxpy constraint, so I don't have explicit access to the initial LHS and RHS of the constraint.

In any case, the `args` thing was exactly what I've been looking for! I'll have a stab at implementing that. Feel free to copy-paste that into my SO question and I'll mark it as accepted :)

Cheers,
Robert
