### ISSUE TITLE
Example Addition

### ISSUE THREAD

**Issue by okpoti2** [cvxgrp/cvxpy#1015]
I would like to add an example based on the Multi-commodity network flow problem by [Cappanera & Frangioni](https://pubsonline.informs.org/doi/10.1287/ijoc.15.4.369.24887). This example would help other users overcome the two-dimensional limitation of CVXPY and be able to port models built in CPLEX with minimal code changes.
Please check the example code [here](https://github.com/okpoti2/CVXPYContributions)
Thank you.

**Comment by SteveDiamond** [comment]
That's great! Our format is to make Jupyter notebooks, where first you describe the problem mathematically, then you have code to solve an example. Out of curiosity, why does the problem benefit from more than 2D matrices? I've set up multi-commodity flow problems before with just normal linear algebra.

**Comment by okpoti2** [comment]
Thanks for the response. I will work on the notebook and send the link later. The benefit of the X-D (where X= 1,2, 3 ...) structure is to offer that flexibility as given in for instance IBM CPLEX which makes it easier to ead any model code. It makes use of the same complex indexing shown in the written math model. The model to be used in my example is the arc-flow type based on MNETGEN instances.

**Comment by okpoti2** [comment]
> That's great! Our format is to make Jupyter notebooks, where first you describe the problem mathematically, then you have code to solve an example. Out of curiosity, why does the problem benefit from more than 2D matrices? I've set up multi-commodity flow problems before with just normal linear algebra.

Here is the link to the notebook that contains the example in the format you suggested.
[link](https://github.com/okpoti2/CVXPYContributions/blob/master/MMCF.ipynb).
Please let me know if there are any issues. Thanks

**Comment by keithbriggs** [comment]
This is quite unpythonic in some places.

Instead of all those repeated int() conversions, wouldn't it be better to do:

data = map(int,eachLine.split(" "))

? Also, the python lists should be numpy arrays, and are all those temp variables really needed?

K

________________________________

**Comment by okpoti2** [comment]
Thanks for your comments. I have updated the file based on your suggestions. However, the use of the lists (and also the tem variables) is to build a kind of data structure that would allow ease modeling since the original input file as information scattered over with some lines made of int and float.

**Comment by keithbriggs** [comment]
for eachLine in mcpFileData:
    data = tuple(map(int, eachLine.split("      ")))
    mutualCapacityPointer[data[0]] = data[1]

However, all this could probably be done much better with np.loadtxt().

________________________________

**Comment by okpoti2** [comment]
That was great info.

**Comment by keithbriggs** [comment]
# Read mutual capacity pointer file
mutualCapacityPointer = np.loadtxt(mutFile)

You don't need to open and close it.
________________________________

**Comment by okpoti2** [comment]
Ok

**Comment by SteveDiamond** [comment]
@okpoti2 this looks pretty good! Could you start a pull request, and we'll help integrate it into the cvxpy examples?
