### ISSUE TITLE
Problems installing scs in Catalina

### ISSUE THREAD

**Issue by chase-dwelle** [cvxgrp/cvxpy#1024]
Trying to install `cvxpy` in a project and having issues installing the `scs` dependency on OS X 10.15.4 (Catalina). I can install `scs` from source but not `scs-python`. I've confirmed that I can install on Ubuntu 18.04.4.

I'm aware this isn't strictly an issue with `cvxpython` but hoping the maintainers may have come upon the issue at some point.

The issue is something related to the compilers in OS X. I've tried the suggestions in #947 to no avail, and both `gcc-8` and `gcc-9`.

Error log is too long to copy here, but ends in the following.

```bash
    error: Command "gcc-8 -Wno-unused-result -Wsign-compare -Wunreachable-code \
-DNDEBUG -g -fwrapv -O3 -Wall -I/Library/Developer/CommandLineTools \
/SDKs/MacOSX10.14.sdk/usr/include -I/Library/Developer/CommandLineTools \
/SDKs/MacOSX10.14.sdk/usr/include -isysroot -isysroot -DPYTHON -DCTRLC=1 -DDLONG=1 \
-DCOPYAMATRIX -DUSE_LAPACK -DHAVE_CBLAS -DNO_ATLAS_INFO=3 -DHAVE_CBLAS \
-Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external \
/dqlql -I/Users/chasedwelle/Repos/.../.venv/lib/python3.7/site-packages/numpy/core/include \ 
-I/usr/local/include -I/Users/chasedwelle/Repos/.../.venv/include -I/Users/chasedwelle/Repos \
/.../.venv/include -I/Users/chasedwelle/.pyenv/versions/3.7.6/include/python3.7m -c scs/src/util.c \
 -o build/temp.macosx-10.14-x86_64-3.7/scs/src/util.o -O3 -msse3 -I/System/Library \
/Frameworks/vecLib.framework/Headers" failed with exit status 1

    ----------------------------------------

ERROR: Command errored out with exit status 1: /Users/chasedwelle/Repos/.../.venv \
/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders \
/08/7jz761_958gcj49h8zrrcpsm0000gp/T/pip-install-1uec5yxe/scs/setup.py'"'"'; \
__file__='"'"'/private/var/folders/08/7jz761_958gcj49h8zrrcpsm0000gp/T/pip-install-1uec5yxe \
/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r \
\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private \
/var/folders/08/7jz761_958gcj49h8zrrcpsm0000gp/T/pip-record-hm7hr7fm/install-record.txt \
--single-version-externally-managed --compile --install-headers /Users/chasedwelle/Repos \
/.../.venv/include/site/python3.7/scs Check the logs for full command output.
```

**Comment by akshayka** [comment]
This issue belongs in the SCS repository (https://github.com/cvxgrp/scs), though I do understand it's also a CVXPY issue, since SCS is a hard requirement.

@chase-dwelle , do you mind creating this issue in the SCS repository? That way, the SCS developers can also chime in. When you do so, please do include the entire output from installation. You can do so by pasting it into a github gist, for example. (https://gist.github.com/)

**Comment by chase-dwelle** [comment]
Issue was very simple. in the end, needed to delete the OS 10.14 command line tools SDK. Something to do with how the compiler looked for the header files.
```bash
sudo rm -rf /Library/Developer/CommandLineTools/MacOSX10.14.sdk
```
Not quite sure why this is an issue, `scs` is the only time I've encountered this problem, but glad it's been resolved.
