### ISSUE TITLE
what does SOC constraint do 

### ISSUE THREAD

**Issue by xiaoweing** [cvxgrp/cvxpy#1025]
i want to use SCS so that i can write code in C++, but i don't know how to write the standard form. therefore, i use get_problem_data(cvxpy.SCS) to know what's the standard form. i really don't know the SOC constraint. i think cvxpy.SOC(t, x) means that ||x||_2 <= t. but data['A'] don't look so. 
Could anyone give some more specific examples or explanation, thank you very much!

**Comment by SteveDiamond** [comment]
Here is more information about the SCS standard form: https://github.com/cvxgrp/scs
