### ISSUE TITLE
Gurobi solver not found

### ISSUE THREAD

**Issue by dereklau33** [cvxgrp/cvxpy#1028]
Hi I am new to Python(3.7) and cvxpy(1.0). I recently installed Gurobi(9.0) but I get this solver error:

`prob.solve(solver = cvxpy.GUROBI, verbose=True)`

> SolverError: The solver GUROBI is not installed.

I found `import gurobipy` works properly and when I run `print(cvxpy.installed_solvers())` I see Gurobi listed as an installed solver:

> ['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', **'GUROBI',** 'OSQP', 'SCS']

The error comes from problem.py line 433 where `slv_def.INSTALLED_SOLVERS` does not contain Gurobi:

> ['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCS']

I am not sure why Gurobi is not recognized as a solver when it is already installed. Any advice is much appreciated!

**Comment by SteveDiamond** [comment]
Is this still a problem in 1.1? Try installing from source.
