### ISSUE TITLE
Parametric QPs slower on 1.1.0a4 compared to 1.0.31

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/cvxpy#1030]
**Describe the bug**
CVXPY 1.1.0a4 takes longer to solve a sequence of QPs  compared to 1.0.

**To Reproduce**

```python
import cvxpy as cp
import numpy as np
from time import time
from tqdm import tqdm

print("CVXPY version: ", cp.__version__)

# Problem data.
m = 300
n = 200
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)
gamma = cp.Parameter(nonneg=True, name="gammix")
x = cp.Variable(n)
N = 100
solver = cp.OSQP  
# solver = cp.GUROBI


def solve_sequence(solver):

    print("Solver", solver)

    objective = cp.Minimize(cp.sum_squares(A @ x - b) + gamma * cp.norm(x, 1))
    constraints = [0 <= x, x <= 1]

    t_solve_full = 0
    t_start = time()
    for n in tqdm(range(N)):
        prob = cp.Problem(objective, constraints)
        gamma.value = 1
        prob.solve(solver=solver)
        t_solve_full += prob.solver_stats.solve_time/N
    t_full = time() - t_start


    t_solve_param = 0
    t_start = time()
    prob = cp.Problem(objective, constraints)
    for n in tqdm(range(N)):
        gamma.value = 1
        prob.solve(solver=solver)
        t_solve_param += prob.solver_stats.solve_time/N
    t_param = time() - t_start

    print("Time full: %.2e" % t_full)
    print("Avg solve time full: %2e" % t_solve_full)
    print("Time param: %.2e" % t_param)
    print("Avg solve time param: %2e" % t_solve_param)

solve_sequence(solver)
```

**Expected behavior**
1.1.0a4 should be faster than 1.0.31 given the new parametric infrastructure.

**Output**

This is the output with *OSQP* (new version is slower):
```
CVXPY version:  1.1.0a4
Solver OSQP
100%|███████████████████████████████████████████████████████████████| 100/100 [00:16<00:00,  6.05it/s]
100%|███████████████████████████████████████████████████████████████| 100/100 [00:13<00:00,  7.19it/s]
Time full: 1.65e+01
Avg solve time full: 1.168879e-01
Time param: 1.39e+01
Avg solve time param: 1.157574e-01
```

```
CVXPY version:  1.0.31
Solver OSQP
100%|█████████████████████████████████████████| 100/100 [00:14<00:00,  6.68it/s]
100%|█████████████████████████████████████████| 100/100 [00:03<00:00, 28.02it/s]
Time full: 1.50e+01
Avg solve time full: 1.214789e-01
Time param: 3.57e+00
Avg solve time param: 7.173415e-03
```

This is the output with *GUROBI* (no noticeable improvement):
```
CVXPY version:  1.1.0a4
Solver GUROBI
100%|███████████████████████████████████████████████████████████████| 100/100 [00:23<00:00,  4.34it/s]
100%|███████████████████████████████████████████████████████████████| 100/100 [00:20<00:00,  4.81it/s]
Time full: 2.30e+01
Avg solve time full: 1.301685e-01
Time param: 2.08e+01
Avg solve time param: 1.350439e-01
```

```
CVXPY version:  1.0.31
Solver GUROBI
100%|█████████████████████████████████████████| 100/100 [00:20<00:00,  4.93it/s]
100%|█████████████████████████████████████████| 100/100 [00:21<00:00,  4.72it/s]
Time full: 2.03e+01
Avg solve time full: 1.305531e-01
Time param: 2.12e+01
Avg solve time param: 1.440245e-01
```

**Version**
 - OS: Mac OSX Catalina
 - CVXPY Version: 1.0.31 vs 1.1.0a4

**Observations**
- OSQP is way faster to solve the parametric program in 1.0.31. It looks like it is not warm-started nor cached.

- Gurobi takes similar time in both cases. However, the time improvement seems really minor given the fact that in the `full` case we are always recreating the cvxpy problem.

Do you guys have any idea why this is happening?

**Comment by SteveDiamond** [comment]
Yeah, @akshayka figured this out. Basically the mapping from parameter to problem data needs to be optimized. @akshayka how hard would it be to replicate what you did for cone programs for quadratic programs?

**Comment by akshayka** [comment]
I don’t think this is related to canonicalization (or at least i think my optimization wouldn’t make much of a difference here). As Bartolomeo mentioned,

> OSQP is way faster to solve the parametric program in 1.0.31. It looks like it is not warm-started nor cached.

my guess would be that OSQP is not getting warm-started.

**Comment by bstellato** [comment]
I think there are two separate fixes:

1. Make DPP QPs canonicalize faster. The canonicalization of repeated solves seem to have no time improvement. 

    I know the example is not the same, but from [(cvxpylayers paper Table 1)](https://web.stanford.edu/~boyd/papers/pdf/diff_cvxpy.pdf) I thought the canonicalization speedups would have been significant compared to the first output I reported (OSQP with CVXPY 1.1.0a4). However, I am not sure what the bottleneck is.
1. Make sure OSQP is warm-started. This should be quite easy I think.

**Comment by akshayka** [comment]
@bstellato , I ran your script on my workstation. On my machine (32 GB RAM, Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz), neither (1) or (2) applies, i.e., 1.1.0a4 is faster when re-canonicalizing  a parametrized problem, and the parametrized OSQP solves aren't any slower in the pre-release than in the alpha. Output below.

```
CVXPY version:  1.1.0a4
Solver OSQP
100/100 [00:01<00:00, 58.31it/s]
Time full: 1.21e+01
Avg solve time full: 9.924226e-02
Time param: 1.72e+00
Avg solve time param: 5.713834e-03
```

```
Time full: 1.21e+01
Avg solve time full: 1.012523e-01
Time param: 2.31e+00
Avg solve time param: 5.761518e-03
```

**Comment by akshayka** [comment]
The same is true for my 2012 MacBook Pro (Mojave, not Catalina). So, strangely, I can't reproduce your issue.

```
CVXPY version:  1.1.0a4
Solver OSQP
Time full: 1.64e+01
Avg solve time full: 1.134502e-01
Time param: 2.19e+00
Avg solve time param: 6.184388e-03
```

```
CVXPY version:  1.0.31
Time full: 1.45e+01
Avg solve time full: 1.141111e-01
Time param: 3.47e+00
Avg solve time param: 6.279030e-03
```

**Comment by SteveDiamond** [comment]
I get similar results to @bstellato  
```
CVXPY version:  1.1.0a4
Solver OSQP
Time full: 1.05e+01
Avg solve time full: 8.097630e-02
Time param: 9.11e+00
Avg solve time param: 8.055269e-02
```
I looked into the warm starting, and I'm seeing really strange stuff. The matrix A is changing, which makes no sense. Maybe some memory is getting overwritten? Would that happen in OSQP?

**Comment by bstellato** [comment]
This is really strange. @akshayka @SteveDiamond which version of Python are you using? I have Python 3.8 installed with pyenv. 

I am pretty sure OSQP does not modify the data. We made sure everything is copied so that the user provided variables do not change during the internal problem scaling. 

@SteveDiamond do the `A` elements change their values or only their order? Could it be related to this [issue we had in the past](https://github.com/cvxgrp/cvxpy/pull/664#issuecomment-461581429) ? I remember there was a bug in `QpMatrixStuffing` @akshayka discovered.

**Comment by akshayka** [comment]
@SteveDiamond , your results indicate that parameter canonicalization is faster than recreating the problem. What do you get for 1.0.31?

I’m using Python 3.7.

**Comment by SteveDiamond** [comment]
```
CVXPY version:  1.0.31
Solver OSQP
Time full: 9.56e+00
Avg solve time full: 8.152365e-02
Time param: 1.86e+00
Avg solve time param: 5.029398e-03
```
So you can see parameterization was more helpful in the previous version, and warm start seems to work better in the previous version.

**Comment by akshayka** [comment]
Hmmm. In that case I’d recommend that someone profile the code (using cProfile) and share your findings in this thread. I guess it wouldn’t be helpful for me to profile, since for some reason I don’t see the slowness that you guys see.

It’d also be useful to report the same timings but for SCS, across both versions.

In the benchmarks, I’d recommend doing a warm-up solve before starting the loop, so that you don’t measure the time it takes to compute the ASA maps the first time the parametrized problem is solved. Otherwise the profiles will be hard to interpret. (Call prob.solve once, immediately before the second for loop. I didn’t do this when reporting my results, I ran the script as given)

**Comment by bstellato** [comment]
@akshayka I have edited the script and ran the timings as you suggested.

I have also added the solver outputs in every case. I now only keep the average computation times and I estimate the average cvxpy canonicalization time. Note that I increased the problem dimension to increase the computation times and improve the profiling quality.

With 1.1.0a and SCS, the canonicalization time goes down significantly (44x) by reusing the same problem across solves. It does not seem to happen with OSQP (only around 2x). In addition, OSQP is not warm-started.

I have attached the new script, outputs and profile data with both `cProfile` (.prof) and `pyinstrument` (.html) for OSQP and SCS with options `master` (1.1.0a4) or `stable` (1.0.31): [test_param_prog.zip](https://github.com/cvxgrp/cvxpy/files/4668872/test_param_prog.zip)

**Comment by akshayka** [comment]
Thanks @bstellato !

I've pushed a branch (https://github.com/cvxgrp/cvxpy/tree/qp_reduce_asa_map) that optimizes the construction of the problem data on re-solves (analogous changes helped significantly for some parametrized cone programs). I'm not sure if it'll help much with this benchmark, maybe it will. Do you mind running the benchmark on that branch?

The profiles included in the zip archive are a bit difficult to interpret, because (if I understand correctly) they profile the entire benchmarking script. They'd be easier to read if they only profiled the second for loop. Something like

```python
prob.solve(solver=solver)  # don't profile the first call

pr = cProfile.Profile()
pr.enable()
for n in tqdm(range(N)):
        gamma.value = 1
        prob.solve(solver=solver)
        t_solve_param += prob.solver_stats.solve_time/N
pr.disable()
pr.dump_stats(cvxpy.__version__ + '_param.prof')
```

(https://docs.python.org/3/library/profile.html#profile.Profile)

In the meantime, @SteveDiamond or Bartolomeo, if either of you wants to submit a PR fixing the lack of warm-starting, that'd be great!

**Comment by SteveDiamond** [comment]
@akshayka  @bstellato I fixed the warm start. Was a very simple bug, so I pushed directly to master.

**Comment by bstellato** [comment]
Thank you guys!  Since I do not have write access to the `qp_reduce_asa_map` branch, I created one on my fork and made PR #1032 . I have attached the benchmarks in PR #1032.
