### ISSUE TITLE
Docs on website not up to date

### ISSUE THREAD

**Issue by kevkevinpal** [cvxgrp/cvxpy#1036]
**Describe the bug**
Documentation on the website is not up to date with what is on the master branch (ex. https://www.cvxpy.org/api_reference/cvxpy.atoms.affine.html#bmat) does not have any documentation but if you build the docs from master branch they are all filled in and readily available.

**To Reproduce**
go into the master branch travel to ```/doc``` then run ```make html``` you may need to update ```source/conf.py``` to have the correct system path

**Expected behavior**
It will build a local doc html which will look more updated that the current one. Travel to ```/doc/build/html/index.html``` to view the resulting documentation file

**Additional context**
I'm not sure if this is something I can fix with a pull request or if something needs to be done to the website directly by an admin but here is an issue so it has some visibility

**Comment by SteveDiamond** [comment]
Thanks for pointing this issue out! It's fixed now.
