### ISSUE TITLE
Control example

### ISSUE THREAD

**Issue by sjcapferrat** [cvxgrp/cvxpy#1039]
I am a very new user of cvxpy and now learning codes in your "Control" example. Would you kindly advise how I can capture the miminized stream of stage cost(x, u) for each T=t, once the solver is complete? 
At first glance It seems each stage cost at T=t can be just coded as "sum_squares(x[:, t+1]) + sum_squares(u[:, t]) after the solver line, but this did not work. In the end I am hoping to plot the development of stage costs along with t, in addition to the "u" and "x" plots in your example. Thank you.

**Comment by SteveDiamond** [comment]
You need to call the ``.value`` field to get the numerical value, unlike in CVX (e.g., ``(sum_squares(x[:, t+1]) + sum_squares(u[:, t]) ).value``.

**Comment by sjcapferrat** [comment]
I tried that but calling the .value as you suggested somehow gave me only a single number (see "captured cost" below in my result section), not a whole stream of interim sum_squares costs at each  t=0 and T. 
In contrast, printing both u.value and x.value (which are defined as cp.Valiable) do return every value for T-0 to 50 in arrays format, so I wonder there should be some other way to deal with retrieving costs in this control example.

Here's the code what I tried so far, followed by the results.  Thanks for your time.

# Generate data for control problem.
import numpy as np

np.random.seed(1)
n = 4   #state size
m = 2   #input size
T = 50  #number of horizon periods 
alpha = 0.2
beta = 5

A = np.eye(n) + alpha*np.random.randn(n,n)
B = np.random.randn(n,m)
x_0 = beta*np.random.randn(n)

# Form and solve control problem.
import cvxpy as cp

x = cp.Variable((n, T+1))
u = cp.Variable((m, T))

cost = 0
constr = []
for t in range(T):
    cost += cp.sum_squares(x[:,t+1]) + cp.sum_squares(u[:,t])
    constr += [x[:,t+1] == A@x[:,t] + B@u[:,t],
               cp.norm(u[:,t], 'inf') <= 1]
               
# sums problem objectives and concatenates constraints.
constr += [x[:,T] == 0, x[:,0] == x_0]
problem = cp.Problem(cp.Minimize(cost), constr)
problem.solve(solver=cp.ECOS)

print("Solved Cost --------------")
print(problem.value)

#Capture costs
print("Captured Interim Cost ------------")
print((cp.sum_squares(x[:,t+1]) + cp.sum_squares(u[:,t])).value)
print("--------------------------")

print(u.value) 
print(x.value)

(End of code)
---------------------
(Result)

Solved Cost --------------
1680.6536082581847
Captured Interim Cost ------------
9.007166189455884e-14
--------------------------
[[ 1.00000001e+00  1.00000001e+00  1.00000001e+00  1.00000001e+00
   1.00000001e+00  1.00000001e+00  1.00000000e+00  1.00000000e+00
   9.99999998e-01  9.99999973e-01  3.23020421e-01 -7.92985456e-01
  -6.83105283e-01 -4.32019845e-01 -2.48953860e-01 -1.39113551e-01
  -7.72278042e-02 -4.30177667e-02 -2.41377265e-02 -1.36633130e-02
  -7.80677886e-03 -4.50362402e-03 -2.62359736e-03 -1.54349973e-03
  -9.16993479e-04 -5.50032165e-04 -3.32979397e-04 -2.03347449e-04
  -1.25195311e-04 -7.76546394e-05 -4.84909272e-05 -3.04611912e-05
  -1.92359512e-05 -1.22029247e-05 -7.77180447e-06 -4.96631263e-06
  -3.18248058e-06 -2.04403674e-06 -1.31507637e-06 -8.46849157e-07
  -5.45058863e-07 -3.49605123e-07 -2.21936437e-07 -1.37107857e-07
  -7.88297764e-08 -3.66584226e-08 -5.38978369e-09  1.20254150e-08
  -3.65176268e-09 -9.08927066e-08]
 [ 1.00000001e+00  1.00000001e+00  1.00000001e+00  1.00000001e+00
   1.00000001e+00  1.00000000e+00  9.99999998e-01  6.34087515e-02
  -9.99999931e-01 -9.99999161e-01 -5.90422226e-02  3.41577882e-01
   3.37514414e-01  2.33828594e-01  1.41713327e-01  8.07996086e-02
   4.47888938e-02  2.45403465e-02  1.34045685e-02  7.33171314e-03
   4.02486307e-03  2.22062216e-03  1.23247757e-03  6.88650113e-04
   3.87651799e-04  2.19987130e-04  1.25928574e-04  7.27506752e-05
   4.24315542e-05  2.49896647e-05  1.48611351e-05  8.92244060e-06
   5.40630954e-06  3.30434706e-06  2.03596938e-06  1.26374465e-06
   7.89655780e-07  4.96364086e-07  3.13669409e-07  1.99185140e-07
   1.27099445e-07  8.15771456e-08  5.28478861e-08  3.48570860e-08
   2.38221517e-08  1.73494664e-08  1.43390972e-08  1.83635519e-08
   5.83288607e-08  2.86024785e-07]]
[[ 4.50427975e+00  6.40452759e+00  7.77280267e+00  8.65366264e+00
   9.04751514e+00  8.91734419e+00  8.19189169e+00  6.76668739e+00
   5.32613840e+00  4.35820725e+00  3.55008597e+00  2.44361108e+00
   1.47735658e+00  8.43304798e-01  4.69358863e-01  2.58820734e-01
   1.42568513e-01  7.87785800e-02  4.37644838e-02  2.44753564e-02
   1.37915848e-02  7.83571520e-03  4.49129806e-03  2.59831679e-03
   1.51766590e-03  8.95135568e-04  5.33109061e-04  3.20527345e-04
   1.94477917e-04  1.19015838e-04  7.34167321e-05  4.56181293e-05
   2.85307985e-05  1.79475867e-05  1.13476826e-05  7.20663046e-06
   4.59438728e-06  2.93889470e-06  1.88565256e-06  1.21351398e-06
   7.83729213e-07  5.08845020e-07  3.33576616e-07  2.22972198e-07
   1.55081022e-07  1.16487293e-07  9.97912846e-08  1.02306851e-07
   1.23148902e-07  1.42288541e-07 -5.62871608e-19]
 [-3.41863930e+00  5.75172460e-02  2.70268830e+00  4.75042336e+00
   6.34169024e+00  7.55269920e+00  8.41116207e+00  8.90505426e+00
   8.44057530e+00  6.95154482e+00  5.10260011e+00  3.42267067e+00
   1.92383123e+00  1.02007349e+00  5.30243120e-01  2.73829888e-01
   1.40937643e-01  7.22191851e-02  3.67377592e-02  1.84795668e-02
   9.14315714e-03  4.41565171e-03  2.05585616e-03  9.01886612e-04
   3.54404881e-04  1.06638826e-04  3.27848829e-06 -3.31171518e-05
  -4.03413386e-05 -3.62658729e-05 -2.89349629e-05 -2.16706751e-05
  -1.56147227e-05 -1.09660772e-05 -7.56417092e-06 -5.14989967e-06
  -3.47225571e-06 -2.32400743e-06 -1.54694290e-06 -1.02570260e-06
  -6.78665406e-07 -4.49309207e-07 -2.99161444e-07 -2.02478222e-07
  -1.42436448e-07 -1.08540456e-07 -9.49115710e-08 -9.87718257e-08
  -1.16376502e-07 -1.24514607e-07  1.93606451e-18]
 [-6.14451128e-01  1.63570108e+00  3.55801443e+00  5.21979130e+00
   6.65516246e+00  7.86916403e+00  8.83840964e+00  9.50919147e+00
   8.72136828e+00  6.16180799e+00  2.90794359e+00  7.64254376e-01
   1.29532905e-01 -1.40428940e-02 -2.81863207e-02 -1.84207468e-02
  -9.27122350e-03 -3.89947288e-03 -1.24803406e-03 -9.64816548e-05
   3.22141240e-04  4.14496847e-04  3.78497324e-04  3.04063145e-04
   2.28561057e-04  1.65053898e-04  1.16085079e-04  8.01542077e-05
   5.46102541e-05  3.68378789e-05  2.46615017e-05  1.64132409e-05
   1.08735160e-05  7.17726235e-06  4.72353956e-06  3.10106886e-06
   2.03144291e-06  1.32772633e-06  8.65141095e-07  5.60712596e-07
   3.59322469e-07  2.24224013e-07  1.30597757e-07  6.11288797e-08
   2.89284298e-09 -5.48851794e-08 -1.22122242e-07 -2.06483006e-07
  -3.01569945e-07 -3.36769001e-07 -6.38834562e-19]
 [-4.67884717e+00 -2.41270945e+00 -5.24383117e-01  1.09303554e+00
   2.51738243e+00  3.80625642e+00  5.00226095e+00  6.13579109e+00
   6.75540563e+00  6.65428821e+00  6.17181380e+00  5.11424341e+00
   3.19874059e+00  1.83514082e+00  1.02352600e+00  5.67742524e-01
   3.16129634e-01  1.77345146e-01  1.00368683e-01  5.73361849e-02
   3.30693349e-02  1.92601759e-02  1.13283253e-02  6.72854137e-03
   4.03497074e-03  2.44214559e-03  1.49107923e-03  9.17835698e-04
   5.69202763e-04  3.55378355e-04  2.23211502e-04  1.40938940e-04
   8.94000823e-05  5.69329216e-05  3.63797529e-05  2.33134286e-05
   1.49764638e-05  9.64055274e-06  6.21644247e-06  4.01431953e-06
   2.59551191e-06  1.68007156e-06  1.08882710e-06  7.06850976e-07
   4.60295175e-07  3.01535021e-07  1.99251146e-07  1.30929825e-07
   7.63665219e-08  1.82008325e-08 -1.07697564e-18]]

**Comment by SteveDiamond** [comment]
The fundamental idea is to get the value of an expression, you do ``expr.value`` the sum of ``sum_squares`` is a single scalar, but you could also get the value of any individual term by forming that particular term.

**Comment by sjcapferrat** [comment]
Yes, I have taken a "muscle" route for now by using x and u to recalculate each term cost, making sure all the sum matches the solved result. This at least helps chasing how the costs change over time in the optimization process. I hope to find some more elegant solutions later.
