### ISSUE TITLE
Improve support for alternative kktsolver functions in cvxopt

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#1042]
CVXOPT lets users provide a function handle that implements an algorithm to solve linearized KKT systems. Right now CVXPY partially exposes that functionality, by allowing users to select one of two pre-made KKT solvers ("chol" is the default, "robust" uses an LDL factorization designed to handle linearly dependent constraints). It would be nice if this functionally was fully-exposed.

From what I can tell, it looks like CVXPY behaves correctly if a user provides a CVXOPT-compliant function handle for the KKT solver. (See [here](https://github.com/cvxgrp/cvxpy/blob/387c48e08b230664e4bb092bf4e32a5d3573347e/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py#L323) for how we parse this setting.) The only clear limitation is at [line 161](https://github.com/cvxgrp/cvxpy/blob/387c48e08b230664e4bb092bf4e32a5d3573347e/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py#L161), where we assume the KKT solver is one of the two pre-defined options. The computational expense ``remove_redundant_rows`` is potentially huge, so it would be good to avoid if a user provided their own KKT solver.

My current plan is to personally make the necessary changes here; I'm creating this GitHub issue largely so I don't lose track of this task.

**Comment by bstellato** [comment]
@rileyjmurray, in case you are interested, we wrapped the LDL solver in OSQP and SCS in its own python package [qdldl-python](https://github.com/oxfordcontrol/qdldl-python). It works for quasi-definite linear systems and redundant rows.

**Comment by rileyjmurray** [comment]
I've actually played with QDLDL in another project of mine. My current goal is to try a non-standard approach to solving KKT systems, though.
