### ISSUE TITLE
Default eps for the SCS solver

### ISSUE THREAD

**Issue by adshieh** [cvxgrp/cvxpy#1046]
The default `eps` for the SCS solver is `1e-5` in the [C library constants](https://github.com/cvxgrp/scs/blob/master/include/glbopts.h#L32) and the [initialization](https://github.com/cvxgrp/scs/blob/master/src/util.c#L183) used by the [Python library](https://github.com/bodono/scs-python/blob/master/src/scsmodule.c#L329). However, cvxpy [sets](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/scs_conif.py#L304) the default `eps` to `1e-4`, based on the [comment](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/scs_conif.py#L303) that the default would otherwise be `1e-3`, presumably for higher accuracy. Should the default be left alone at `1e-5` for even higher accuracy and consistency with the C and Python libraries?

**Comment by rileyjmurray** [comment]
If the C library default is ``1e-5``, I think changing the CVXPY default to ``1e-5`` is a good idea.

**Comment by SteveDiamond** [comment]
It's been set at ``1e-4`` for a long time. Can we have some analysis of the change? Does it make problems much slower to solve?

**Comment by akshayka** [comment]
+1 for some analysis, this single-character change could lead to very different behavior.

**Comment by SteveDiamond** [comment]
Closed due to inactivity.
