### ISSUE TITLE
Error installing CVXPY in MAC

### ISSUE THREAD

**Issue by 4rtur0** [cvxgrp/cvxpy#1048]
**Describe the bug**

**To Reproduce**
(base) Xxxs-iMac:~ xxx$ pip install cvxpy
Collecting cvxpy
  Using cached cvxpy-1.1.1-cp37-cp37m-macosx_10_9_x86_64.whl (815 kB)
Requirement already satisfied: numpy>=1.15 in ./opt/anaconda3/lib/python3.7/site-packages (from cvxpy) (1.18.1)
Requirement already satisfied: ecos>=2 in ./opt/anaconda3/lib/python3.7/site-packages (from cvxpy) (2.0.7.post1)
Collecting scs>=1.1.3
  Using cached scs-2.1.2.tar.gz (3.5 MB)
Requirement already satisfied: scipy>=1.1.0 in ./opt/anaconda3/lib/python3.7/site-packages (from cvxpy) (1.4.1)
Requirement already satisfied: osqp>=0.4.1 in ./opt/anaconda3/lib/python3.7/site-packages (from cvxpy) (0.6.1)
Requirement already satisfied: future in ./opt/anaconda3/lib/python3.7/site-packages (from osqp>=0.4.1->cvxpy) (0.18.2)
Building wheels for collected packages: scs
  Building wheel for scs (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/xxx/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/setup.py'"'"'; __file__='"'"'/private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-wheel-r2od4yrm
       cwd: /private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/
  Complete output (46 lines):
  Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.7
  creating build/lib.macosx-10.9-x86_64-3.7/scs
  copying src/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/scs
  running build_ext
  blas_mkl_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xxx/opt/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xxx/opt/anaconda3/include']
  blas_opt_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xxx/opt/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xxx/opt/anaconda3/include']
  lapack_mkl_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xxx/opt/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xxx/opt/anaconda3/include']
  lapack_opt_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xxx/opt/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xxx/opt/anaconda3/include']
  {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/xxx/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/xxx/opt/anaconda3/include']}
  {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/xxx/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/xxx/opt/anaconda3/include']}
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/xxx/opt/anaconda3/include -arch x86_64 -I/Users/xxx/opt/anaconda3/include -arch x86_64 -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/xxx/opt/anaconda3/include -I/Users/xxx/opt/anaconda3/include -I/Users/xxx/opt/anaconda3/include/python3.7m -c src/scsmodule.c -o build/temp.macosx-10.9-x86_64-3.7/src/scsmodule.o -O3" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scs
  Running setup.py clean for scs
Failed to build scs
Installing collected packages: scs, cvxpy
    Running setup.py install for scs ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/xxx/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/setup.py'"'"'; __file__='"'"'/private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-record-4ffoqftf/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xxx/opt/anaconda3/include/python3.7m/scs
         cwd: /private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/
    Complete output (46 lines):
    Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/scs
    copying src/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/scs
    running build_ext
    blas_mkl_info:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/Users/xxx/opt/anaconda3/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/Users/xxx/opt/anaconda3/include']
    blas_opt_info:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/Users/xxx/opt/anaconda3/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/Users/xxx/opt/anaconda3/include']
    lapack_mkl_info:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/Users/xxx/opt/anaconda3/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/Users/xxx/opt/anaconda3/include']
    lapack_opt_info:
        libraries = ['mkl_rt', 'pthread']
        library_dirs = ['/Users/xxx/opt/anaconda3/lib']
        define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
        include_dirs = ['/Users/xxx/opt/anaconda3/include']
    {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/xxx/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/xxx/opt/anaconda3/include']}
    {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/xxx/opt/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/xxx/opt/anaconda3/include']}
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/xxx/opt/anaconda3/include -arch x86_64 -I/Users/xxx/opt/anaconda3/include -arch x86_64 -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/Users/xxx/opt/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/xxx/opt/anaconda3/include -I/Users/xxx/opt/anaconda3/include -I/Users/xxx/opt/anaconda3/include/python3.7m -c scs/src/linalg.c -o build/temp.macosx-10.9-x86_64-3.7/scs/src/linalg.o -O3" failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/xxx/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/setup.py'"'"'; __file__='"'"'/private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-install-vzye8gzw/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/p7/ymdl2w354k51dp1_xgbdc36w0000gn/T/pip-record-4ffoqftf/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xxx/opt/anaconda3/include/python3.7m/scs Check the logs for full command output.
(base) Xxxs-iMac:~ xxx$ 

**Expected behavior**
The package CVXPY should be installed

**Output**
Error (see above)

**Version**
 - OS: 10.14.6 (MAC)
 - CVXPY Version: v1.1.1

**Additional context**
Same error as when trying to install the SCS package separately

**Comment by SteveDiamond** [comment]
You need to install the Xcode command line tools.

**Comment by 4rtur0** [comment]
> You need to install the Xcode command line tools.

Steve: Thank you very much! I worked perfectly.
If you happen to visit Zurich, happy to sponsor you a beer :)

**Comment by SteveDiamond** [comment]
Thanks! Glad to hear it!
