### ISSUE TITLE
DCPError: Problem does not follow DCP rules. Specifically: The objective is not DCP

### ISSUE THREAD

**Issue by LuigiSimeone** [cvxgrp/cvxpy#1051]
**Describe the bug**
Hi, I am trying to optimise a portfolio with cvxpy.
The function I want to optimise has to maximise return and minimise volatility so it is a standard well known cost function. However, I get the following error

_Problem does not follow DCP rules. Specifically:
The objective is not DCP._ 

because it is not convex. 
However I must use that function. 
The problem happen exactly with the sign in front of the term PENALTY. If i put + it works with - not.

**To Reproduce**
def minVarOptC(self, lmbd, r_target):

        numAssets = np.shape(self.rets)[0]
        W = cp.Variable(numAssets)
        penalty=lmbd*cp.pnorm((self.rets @ W - r_target),1)

        risk = cp.quad_form(W, self.covs) - penalty
        prob = cp.Problem(Minimize(risk), [sum(W)==1.,
                                        sum(W[:2])>=min_fi,
                                        sum(W[:2])<=max_fi,
                                        sum(W[2:4])>=min_az,
                                        sum(W[2:4])<=max_az,
                                        sum(W[4:])>=min_cr,
                                        sum(W[4:])<=max_cr,
                                        sum(W[0])>=min_wgb,
                                        sum(W[0])<=max_wgb,
                                        sum(W[1])>=min_emd,
                                        sum(W[1])<=max_emd,
                                        sum(W[2])>=min_we,
                                        sum(W[2])<=max_we,
                                        sum(W[3])>=min_eme,
                                        sum(W[3])<=max_eme,
                                        sum(W[4])>=min_gc,
                                        sum(W[4])<=max_gc,
                                        sum(W[5])>=min_ghy,
                                        sum(W[5])<=max_ghy,
                                        W >= 0.])
        prob.solve()

**Version**
 - OS: W10
 - CVXPY Version: 1.1.1

Can anybody help me to correct the code in order to be able to use such a function?
Thanks
Luigi

**Comment by SteveDiamond** [comment]
This doesn't look standard to me. What is the pnorm from? Return is normally a linear function.

**Comment by LuigiSimeone** [comment]
Hi Steve,
the point is that I am trying to optimise the minimum regret because I have a scenario-based situation, so yes probably the way I wrote is wrong. Do you have any suggestion on how to correct it? 

Thanks
BR
Luigi

**Comment by SteveDiamond** [comment]
Are you sure the formulation is convex? ``cp.pnorm((self.rets @ W - r_target),1)`` is convex, and ``cp.quad_form(W, self.covs) - penalty`` is non-DCP assuming lmbd is positive.

**Comment by LuigiSimeone** [comment]
yes it was not and indeed I had to modify it, now seems to work. 
The norm was an error.
Thanks for putting that in evidence

BR
Luigi
