### ISSUE TITLE
Unexpected broadcasting errors

### ISSUE THREAD

**Issue by spenrich** [cvxgrp/cvxpy#1054]
From what I understand, the first type of broadcasting below is not supported by CVXPY, so this correctly raises a broadcasting error. 

Are either of the other two supposed to be supported (specifically, using `multiply`)?
```
import numpy as np
import cvxpy as cvx

np.random.seed(0)
m, n = 3, 4
A = np.random.rand(m, n)

col_scale = cvx.Variable(n)
C = cvx.multiply(A, col_scale)    # raises "ValueError: Cannot broadcast dimensions  (3, 4) (4,)"

col_scale = cvx.Variable([1, n])
C = cvx.multiply(A, col_scale)    # raises "ValueError: Cannot broadcast dimensions  (3, 4) (1, 4)"

row_scale = cvx.Variable([m, 1])
R = cvx.multiply(A, row_scale)    # raises "ValueError: Cannot broadcast dimensions  (3, 4) (3, 1)"
```

**Version**
Using a fresh conda environment with
 - OS: macOS Catalina (10.15.4)
 - CVXPY Version: 1.1.1

**Comment by SteveDiamond** [comment]
These are not supported in cvxpy. You need to multiply by a ones vector.

**Comment by SteveDiamond** [comment]
Thinking a bit more about what you posted, this might be a good place to add in some broadcasting.

**Comment by Karltlbm** [comment]
Is this related ?
```
vx = cvx.Variable(nx * ny)
objective = cvx.Minimize(cvx.norm(vx, 1))
constraints = [A*vx == b]
```

Error :
```
constraints = [A*vx == b]
ValueError: Cannot broadcast dimensions  (600,) (600, 1)
```

**Comment by SteveDiamond** [comment]
@Karltlbm you need to flatten ``b``. @spenrich the latter two broadcasting operations are now implemented for multiply in master.

**Comment by spenrich** [comment]
@SteveDiamond thank you!
