### ISSUE TITLE
Python script freezes when trying to solve LMI with high memory usage

### ISSUE THREAD

**Issue by pratikbajaria** [cvxgrp/cvxpy#1055]
Dear Team,

I am trying to solve an LMI problem using cvxpy. The matrix that I am using is a huge one with **65536x65536 float16** entries. My code works fine for smaller less complex systems and to my assumption it keeps working in the background for long hours too. Although, after sometime (approx 3hours), my linux instance freezes either disconnecting or killing the kernel producing no outputs. At the end, I have to re-run the whole code again right from scratch. I have tried everything with all kinds of systems right from 16GB MAC to 64GB Debian, without any luck.

Could anyone please help me with the issue? Or if redirected to previous similar issues that have been closed would be really helpful.

Also, I would have preferred putting my code snippet here but the matrices are huge as I mentioned  and takes up more than 8GB to be uploaded here.

Request you to kindly help me here, because I have been stuck with it from a very long time and have no idea how to proceed. 

Regards,
Pratik

**Comment by rileyjmurray** [comment]
To my knowledge, there are no SDP solvers that can handle dense matrix variables of that size. Certainly, none of the solvers accessible from CVXPY can handle problems of that scale.

You can look into SDP solvers not supported by CVXPY (e.g. SDPNAL+ in Matlab, Hypatia in Julia). However I seriously doubt you will be able to solve a problem that large unless you have an entire compute cluster at your disposal, and you write custom code (e.g. a solver which uses OpenMP for distributed memory parallelism).

Sorry I don't have better news!
