### ISSUE TITLE
Errors while running geometry examples

### ISSUE THREAD

**Issue by madkaikar-ashish** [cvxgrp/cvxpy#1060]
I have been trying to use the Polyhedron class but unfortunately none of the examples in cvxpy/examples/geometry/ work, not sure if i'm looking at the right branch(master) for recent updates.
example- 
`from convex_sets import ConvexHull, Polyhedron, intersect, is_empty, dist, proj, contains
import numpy as np

n = 2
m = 2*n
A1 = np.matrix("1 1; 1 -1; -1 1; -1 -1")
A2 = np.matrix("1 0; -1 0; 0 1; 0 -1")
b1 = 2*np.ones((m,1))
b2 = np.matrix("5; -3; 4; -2")

poly1 = Polyhedron(A1, b1)
poly2 = Polyhedron(A2, b2)

assert contains(poly1, [-1,-1,1])`

**Comment by madkaikar-ashish** [comment]
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
  File "\cvxpy\examples\geometry\convex_sets.py", line 48, in sep_hyp

**Comment by SteveDiamond** [comment]
The geometry example is 5 years old and uses outdated features of cvxpy. I'm not sure it can be recreated, at least in any easy way, with the current cvxpy. I have removed the example. If you're able to fix it, that would be a major contribution!
