### ISSUE TITLE
C-order flag for reshape function

### ISSUE THREAD

**Issue by ralphsb** [cvxgrp/cvxpy#1061]
**Is your feature request related to a problem? Please describe.**
The reshape function currently only supports Fortran ordering.

**Describe the solution you'd like**
In an ideal world, reshape would take a flag, similar to the numpy reshape function to specify C or Fortran ordering.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SteveDiamond** [comment]
This is fixed on master.
