### ISSUE TITLE
I can run my code with cvxpy but when I pass the code to other people he gets cvxpy.error.DCPerror

### ISSUE THREAD

**Issue by LuigiSimeone** [cvxgrp/cvxpy#1063]
**Describe the bug**
Hi,
I have encoutered a strange issue.
I'm able to run optimisation with cvxpy.
However I passed the code to a colleague to run it.
I have python 3.7.6 he has 3.6.x.

I ask him to install the cvxpy as conda install -c conda-forge cvxpy
he did it all was going well, but when he runs the code it gets
cvxpy.error.DCPerror: problem does not follow DCP rules- Specifically the DCP is not DCP: Its following subexpressions are not:
[......] and here a list of vectors/arrays

Now how is that possible that with same code, same package cvxpy he gets the error and I do not get it?
many thanks for helping

**To Reproduce**

**Expected behavior**
same behaviour as mine

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: WIndows 10 for  both
 - CVXPY Version:  1.1.1 for both

**Additional context**

**Comment by SteveDiamond** [comment]
We can only comment on specific code snippets. Maybe it's a random number generation issue? A non-PSD matrix?

**Comment by LuigiSimeone** [comment]
I could manage to fix this by creating new anaconda environment and install again coda forge and cvxpy. Thanks
