### ISSUE TITLE
cp.sign updates underlying variable in place

### ISSUE THREAD

**Issue by traubms** [cvxgrp/cvxpy#1066]
**Describe the bug**
Calling `cp.sign(variable).value` changes `variable.value`.

**To Reproduce**

```python
import numpy as np
import cvxpy as cp

vector = np.array([.1, -.3, .5])
variable = cp.Variable(len(vector))
problem = cp.Problem(cp.Maximize(vector @ variable), [cp.norm2(variable) <= 1.])
problem.solve()

print(variable.value)  # [ 0.16903085 -0.50709255  0.84515425]
print(cp.sign(variable).value)  # [ 1., -1.,  1.]
print(variable.value)  # [ 1., -1.,  1.]
```

**Expected behavior**
`variable.value` should not change.

**Version**
 - OS: linux
 - CVXPY Version: 1.1.1

**Additional context**
I think this just requires adding `.copy()` [on this line](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/atoms/sign.py#L29).

**Comment by SteveDiamond** [comment]
Fixed on master.
