### ISSUE TITLE
Error using DCCP for L-1 norm 

### ISSUE THREAD

**Issue by exw410** [cvxgrp/cvxpy#1070]
I am trying to solve the L-1 norm equality problem -- ||x||_1 == 1 -- using DCCP (https://github.com/cvxgrp/dccp), i.e., 
 
||x||_1 >=  0.95    &    ||x||_1 <= 1

However, I am getting an error that the >= is not DCP, which is indeed the case, but, was hoping that  this procedure would help with this? I had done a `pip install dccp` and do notice that dccp.objective, dccp.constraint, dccp.problem come up and I have defined  
prob = Problem(objective, constraints)
and specify method = 'dccp' in the prob.solve, but, get an attribute error. (I have cvxpy ver 1.0.25)

Also, since the following inequality is true:
||x||_2 <= ||x||_1 
then, could I impose a lower bound on ||x||_2 to help get close to the ||x||_1? Would appreciate any advice on this. Thank you.

**Comment by SteveDiamond** [comment]
Why don't you create an issue under dccp? DCCP in theory can handle all these constraints you're describing.
