### ISSUE TITLE
Cannot slice with Variables

### ISSUE THREAD

**Issue by Obs01ete** [cvxgrp/cvxpy#1076]
I try to solve a clustering problem with cvxpy. For it I need something like fancy indexing of numpy. Unfortunately numpy is not able to accept cvxpy.Variable's value as an index.

num_clusters = 3
num_nodes = 10
cluster_sizes = cp.Variable(num_clusters, integer=True)
node_weights = np.random.rand(num_nodes)
cluster_offsets = cp.cumsum(cluster_sizes)

slices = node_weights[cluster_offsets:cluster_offsets+cluster_sizes]
cluster_totals = cp.sum(slices)
objective = cp.max(cluster_totals)

Is there any way to perform this action in cvxpy?

Maybe there is something like an atom to create a 0-1-valued array with ones spanning between Variable a to Variable b like the following:
a = 3 # cp.Variable
b = 5 # cp.Variable
mask = cp.create_mask(a, b, num_nodes)
# [0 0 0 1 1 1 0 0 0 0 0]

The backend is GLPK_MI.

Thanks!

**Comment by SteveDiamond** [comment]
You can fancy index using numpy arrays. I.e., create the mask using numpy, not variables.

**Comment by vnscnap** [comment]
> You can fancy index using numpy arrays. I.e., create the mask using numpy, not variables.

Can you please give an example for the thing you mentioned? Thank you

**Comment by arthur-e** [comment]
I would also like to see an example of this.
