### ISSUE TITLE
scs solver report incorrect prob value

### ISSUE THREAD

**Issue by zcyang** [cvxgrp/cvxpy#1085]
**Describe the bug**
When SCS solver is finished, the problem value is inconsistent with the actual value evaluated through expression.

**To Reproduce**
```
import numpy as np
import cvxpy as cp

N = 3000
M = 100
NORM_BOUND = 10

def main():
  np.random.seed(0)

  x = np.random.randn(N, 2)
  weight = np.array([[0.5], [0.5]])
  y = np.random.randn(N)
  L = np.random.randn(N, M)
  L_diag = np.random.rand(N)
  L_diag[:N//2] *= 0.1
  L_diag[N//2:] *= 10
  L_diag = np.diag(L_diag)

  p = x.dot(weight)
  _v = cp.Variable((N))
  _q = np.random.randn(N)
  obj = cp.Minimize(0.5*cp.sum_squares(L.T@_v)
                    + 0.5*cp.sum_squares(L_diag@_v)
                    + 0.5*cp.sum_squares(_v-_q)
                    - _v@p)
  cons = [_v <= 1, -_v <= 1, cp.norm(_v, 1) <= NORM_BOUND]
  prob = cp.Problem(obj, cons)
  prob.solve(solver=cp.SCS, eps=1e-9)
  soln_scs = prob.value
  print(soln_scs)


  obj = (0.5*cp.sum_squares(L.T@_v)
                    + 0.5*cp.sum_squares(L_diag@_v)
                    + 0.5*cp.sum_squares(_v-_q)
                    - _v@p).value
  print(obj)



```

**Expected behavior**
The two value should be qual?

**Output**

1430.2273385810845

1464.7506027
**Version**
 - OS: 
 - CVXPY Version: '1.1.1'

**Additional context**
The problem disappears with other solves.

**Comment by SteveDiamond** [comment]
The status is "Status: Solved/Inaccurate". So it's not solving the problem exactly.

**Comment by SteveDiamond** [comment]
Actually there should be a warning when you get the Optimal/Inaccurate status. I'm not sure what happened to that feature.

**Comment by zcyang** [comment]
Thanks for the reply! Besides the warning, I though the prob.value should always reflect the true objective value? I was using prob.value to compare the optimization algorithms, which could be misleading.

**Comment by SteveDiamond** [comment]
The issue is that the problem is not being solved well in this case, so really you might not want to use the solution at all.

**Comment by SteveDiamond** [comment]
I added a warning for optimal/inaccurate.
