### ISSUE TITLE
Coding Block Matrix type LMI constraint using cvxpy variables in SDPs

### ISSUE THREAD

**Issue by venkatramanrenganathan** [cvxgrp/cvxpy#1095]
Hi All,

I am pretty new to cxvpy. I had been using cvx in matlab so far. I have a problem where I have to code a LMI constraint in cvxpy as follows

I have the following code

import cvxpy as cp

Z = cp.Variable((n,n), symmetric=True)
z = cp.Variable(n)
a = cp.Variable()

Lets suppose A is some matrix of size(n+1,n+1) - a numpy array in python which I have in hand already. I need to add a LMI constraint as follows

constraints = [B << A]

where the matrix B should be composed as a block matrix using above defined cvxpy variables as follows
B = [Z      z
       z.T    a] 

This was very easy to do in cvx in matlab. 

But in cvxpython, it is not allowing me to stack it. My np.vstack / np.hstack is not working. I found one approach using cp.mat. Since I know what is the dimension n (n = 3 in my case) I have hard coded my B matrix as follows which works fine,
B     = cp.bmat([[Z[0,0], Z[0,1], Z[0,2], z[0]], 
                          [Z[1,0], Z[1,1], Z[1,2], z[1]], 
                          [Z[2,0], Z[2,1], Z[2,2], z[2]], 
                          [z[0], z[1], z[2], a]])

In general, is there a way to do this easy for any dimension n ? That is, can we stack up cvxpy variables to form a block matrix type LMI constraint just like in MATLAB. 

Pardon me if the question looks stupid, I am new to cvxpy.

Warm Regards,
Venkatraman Renganathan.

**Comment by SteveDiamond** [comment]
``bmat`` works the same as matlab block matrix construction, e.g.,
```
B = [Z z
z.T a]
```
so if you can do it in matlab you can do it with bmat.

**Comment by SteveDiamond** [comment]
@alberttxu print all the dimensions of Z, z, and a. They should all be 2D.

**Comment by alberttxu** [comment]
Ah I see. Z is 2D, but z is a 1D vector and a is a scalar. So how should I convert z and a into 2D arrays?

n = 3
Z = cp.Variable((n,n), symmetric=True)
z = cp.Variable(n)
a = cp.Variable()
print(Z.shape)
print(z.shape)
print(a.shape)

----output----
(3, 3)
(3,)
()

**Comment by SteveDiamond** [comment]
Yeah, try
```
n = 3
Z = cp.Variable((n,n), symmetric=True)
z = cp.Variable((n,1))
a = cp.Variable((1,1))
```

**Comment by alberttxu** [comment]
Thanks for the help! That did it. Although I have a question about if I needed to create multiple LMI constraints.
E.g.

n = 3
Z = cp.Variable((n,n), symmetric=True)
z = cp.Variable((n,1))
a = cp.Variable(n)
for i in range(n):
    LMI = cp.bmat([
        [Z, z],
        [z.T, a[i]],
    ]) >> 0

It fails since a[i] is not 2D. I'm not sure how to form this problem where the components of a are separate for each LMI.

**Comment by SteveDiamond** [comment]
I'm pretty sure you can do ``cp.reshape(a[i], (1,1))``.
