### ISSUE TITLE
Potential bug in the dual variable retrieval of CVXPY

### ISSUE THREAD

**Issue by yifu0529** [cvxgrp/cvxpy#1096]
**Describe the bug**

If I change the solver of CVXPY (for example, from the default one to MOSEK), the dual value of constraints becomes incorrect and varies for different solvers. Even for some very simple questions, the dual value obtained from one solver could be negative while the other is positive number, and the absolute values are completely different.

**To Reproduce**
import cvxpy as cp

# Create two scalar optimization variables.
x = cp.Variable()
y = cp.Variable()

# Create two constraints.
constraints = [2 * x + y == 1,
               x - 2 * y >= 1]

# Form objective.
obj = cp.Minimize(x**2)

# Form and solve problem (MOSEK).
prob = cp.Problem(obj, constraints)
prob.solve(cp.MOSEK)

# The optimal dual variable (Lagrange multiplier) for
# a constraint is stored in constraint.dual_value.
print("optimal (2x + y == 1) dual variable", constraints[0].dual_value)
print("optimal (x - 2y >= 1) dual variable", constraints[1].dual_value)

# Form and solve problem (Default).
prob = cp.Problem(obj, constraints)
prob.solve()

# The optimal dual variable (Lagrange multiplier) for
# a constraint is stored in constraint.dual_value.
print("optimal (2x + y == 1) dual variable", constraints[0].dual_value)
print("optimal (x - 2y >= 1) dual variable", constraints[1].dual_value)

**Expected behavior**
The same dual variable value for two solvers.

**Output**
Different dual variable value for two solvers.

**Version**
 - OS: Version 10.14.6
 - CVXPY Version: CVXPY 1.1.2

**Additional context**
No

**Comment by rileyjmurray** [comment]
Here is my output. It shows essentially the same dual variables (up to possible rounding errors) for SCS, ECOS, OSQP, and MOSEK. Did you notice discrepancies much larger than the ones below?
```
>>> import cvxpy as cp
>>> x = cp.Variable()
>>> y = cp.Variable()
>>> constraints = [2 * x + y == 1,
... x - 2 * y >= 1]
>>> obj = cp.Minimize(x**2)
>>> prob = cp.Problem(obj, constraints)
>>> prob.solve(solver='SCS')
0.3599999999830787
>>> print("optimal (2x + y == 1) dual variable", constraints[0].dual_value)
optimal (2x + y == 1) dual variable -0.47999999998922466
>>> print("optimal (x - 2y >= 1) dual variable", constraints[1].dual_value)
optimal (x - 2y >= 1) dual variable 0.2399999999913317
>>> prob.solve(solver='MOSEK')
0.3600000087437285
>>> print("optimal (2x + y == 1) dual variable", constraints[0].dual_value)
optimal (2x + y == 1) dual variable -0.4800049055196274
>>> print("optimal (x - 2y >= 1) dual variable", constraints[1].dual_value)
optimal (x - 2y >= 1) dual variable 0.2400024527598137
>>> prob.solve(solver='ECOS')
0.3599999965629523
>>> print("optimal (2x + y == 1) dual variable", constraints[0].dual_value)
optimal (2x + y == 1) dual variable -0.4800113431896633
>>> print("optimal (x - 2y >= 1) dual variable", constraints[1].dual_value)
optimal (x - 2y >= 1) dual variable 0.2400056725034999
>>> prob.solve(solver='OSQP')
0.36
>>> print("optimal (2x + y == 1) dual variable", constraints[0].dual_value)
optimal (2x + y == 1) dual variable -0.4799999999999999
>>> print("optimal (x - 2y >= 1) dual variable", constraints[1].dual_value)
optimal (x - 2y >= 1) dual variable 0.24
```

**Comment by yifu0529** [comment]
That is very odd. I wish I could attach my screenshot.

My results are:

optimal (2x + y == 1) dual variable 0.4800049055196274
optimal (x - 2y >= 1) dual variable 0.2400024527598137
optimal (2x + y == 1) dual variable -0.4800113431896633
optimal (x - 2y >= 1) dual variable 0.2400056725034999

Maybe it is something to do with the MOSEK installation?

**Comment by yifu0529** [comment]
Thanks for the prompt reply. I re-checked my CVXPY version.

I updated the version from CVXPY 1.0,31 to CVXPY 1.1.3, and the problem gets solved.

**Comment by rileyjmurray** [comment]
We added far more thorough dual variable recovery tests when moving to CVXPY 1.1. It looks like in that process we fixed a bug in the old MOSEK interface.

Dual variables are not always unique. For example, if your problem has redundant constraints, then you cannot assume consistent values of dual variables across solvers. One thing you can do is remove the constraint which has zero dual variable, and then re-solve the problem with multiple solvers. If those solvers all give the same primal solution as before, then you probably are running into a non-unique dual solution issue.

Please let us know if that solves your problem. If we don't hear from you in a couple of days then we'll close this issue as resolved.
