### ISSUE TITLE
Expose Expression in top-level module

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#1098]
It's sometimes useful to pass around CVXPY expressions. Importing the `Expression` class in the top-level `cvxpy` module would let users write informative/correct type annotations for functions that accept or return `Expression` objects.

For example, a user could then write a function with the signature

```
def construct_problem(...) -> Tuple[Dict[str, cp.Expression], cp.Problem]:
```

where the dictionary's values hold CVXPY expressions of interest.

**Describe the solution you'd like**
Import `Expression` in the top-level `__init__.py`.

**Describe alternatives you've considered**
An alternative is to write `cp.expressions.expression.Expression`, but this feels clumsy.

**Comment by SteveDiamond** [comment]
Sounds good to me!
