### ISSUE TITLE
quad_form with complex variables

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#1102]
I'm not absolutely sure, but I think line 112 of quad_form.py should be

`D = (P+P.H)@x # not D = 2 * np.dot(P, x.T)`

to correctly handle complex variables.  The quad_form is real-valued and the gradient should be too.

It would also be convenient if quad_form(x) was allowed, with the matrix defaulting to the identity, and the function representing x.H@x.

**Comment by keithbriggs** [comment]
More precisely, if f(z)=z.H@A@z and z=x+iy, then ∂f/∂x+i∂f/∂y=(A+A.H)@z.

**Comment by SteveDiamond** [comment]
I changed the gradient on master. You can use ``sum_squares(x)`` if you want ``quad_form(x)``.
