### ISSUE TITLE
problem.derivative() example fails

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#1110]
The source code at https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/problem.py has this example:

```
import cvxpy as cp
import numpy as np
p = cp.Parameter()
x = cp.Variable()
quadratic = cp.square(x - 2 * p)
problem = cp.Problem(cp.Minimize(quadratic), [x >= 0])
p.value = 3.0
problem.solve(requires_grad=True, eps=1e-10)
# derivative() populates the delta attribute of the variables
problem.derivative()
p.delta = 1e-3
# Because x* = 2 * p, dx*/dp = 2, so (dx*/dp)(p.delta) == 2e-3
np.testing.assert_allclose(x.delta, 2e-3)
```

Is the last step meant to succeed?  I get this output:

> 
> Traceback (most recent call last):
>   File "try_cvxpy_init_00.py", line 13, in <module>
>     np.testing.assert_allclose(x.delta, 2e-3)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 1533, in assert_allclose
>     verbose=verbose, header=header, equal_nan=equal_nan)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 846, in assert_array_compare
>     raise AssertionError(msg)
> AssertionError: 
> Not equal to tolerance rtol=1e-07, atol=0
> 
> Mismatched elements: 1 / 1 (100%)
> Max absolute difference: 0.002
> Max relative difference: 1.
>  x: array(-0.)
>  y: array(0.002)

**Comment by akshayka** [comment]
Thanks for reporting! I believe the issue is that p.delta should be set before problem.derivative() is called, not after. We’ll update the docstring.

**Comment by keithbriggs** [comment]
Yes, that does fix it.
