### ISSUE TITLE
cvx.quad_form bug

### ISSUE THREAD

**Issue by xianglu96** [cvxgrp/cvxpy#1116]
**Describe the bug**
I used cvx.quad_form and its equivalent formulation cvx.sum_square for a diagonal matrix, but the former one can't get to the solution (unbounded or bad direction).

Moreover, when I added some inequality constraints, the former one gave unbounded judgement while the latter gave me an optimal point.

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.
```
import cvxpy as cvx
import numpy as np
# decision variables
h = cvx.Variable(4)
# my inputs
alpha = np.array([0.05] * 4)
sigma_i = np.array([9.91610173e-07, 2.61384914e-06, 9.31156500e-07, 8.46514100e-07])
B = np.array([[ 0.00791268,  0.01458194, -0.00633014,  0.04532835],
       [-0.02926666, -0.02489674, -0.01093661,  0.02437707],
       [-0.00791268, -0.01458194,  0.00633014, -0.04532835],
       [ 0.02926666,  0.02489674,  0.01093661, -0.02437707]])
MB = np.array([0.01 , 0.001, 0.01 , 0.001])
# problem 1
ret = alpha @ h
r_quad = cvx.quad_form(h, np.diag(sigma_i))
prob = cvx.Problem(cvx.Minimize(r_quad - ret))
prob.solve(solver=cvx.ECOS, verbose=True)

r_ss = cvx.sum_squares(cvx.multiply(np.sqrt(sigma_i), h))
prob = cvx.Problem(cvx.Minimize(r_ss - ret))
prob.solve(solver=cvx.ECOS, verbose=True)

# problem 2
prob = cvx.Problem(cvx.Minimize(r_quad - ret), [B @ h <= MB])
prob.solve(solver=cvx.ECOS, verbose=True)

prob = cvx.Problem(cvx.Minimize(r_ss - ret), [B @ h <= MB])
prob.solve(solver=cvx.ECOS, verbose=True)
```

**Expected behavior**
Both problem 1&2 from different forms of formulation give the same solution point

**Output**
ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +0.000e+00  -2.263e-01  +2e+00  5e-01  2e-01  1e+00  1e+00    ---    ---    1  1  - |  -  - 
 1  -1.862e-01  -1.764e-01  +2e-01  4e-02  5e-02  2e-01  2e-01  0.8454  3e-03   1  1  1 |  0  0
 2  -3.154e+00  -9.082e-01  +9e-02  7e-02  3e-01  3e+00  5e-02  0.9395  2e-01   1  1  1 |  0  0
 3  -1.035e+00  -1.203e+00  +6e-02  2e-02  5e-02  1e-02  3e-02  0.6115  2e-01   1  1  1 |  0  0
 4  -1.524e+00  -1.537e+00  +4e-03  3e-03  7e-03  1e-02  2e-03  0.9282  1e-03   1  1  1 |  0  0
 5  -3.743e+00  -3.453e+00  +5e-04  2e-03  8e-03  3e-01  3e-04  0.9890  1e-01   1  1  1 |  0  0
 6  -7.191e+00  -6.679e+00  +4e-05  5e-04  2e-03  5e-01  2e-05  0.9155  3e-03   2  1  1 |  0  0
 7  -2.043e+01  -1.562e+01  +4e-06  5e-04  2e-03  5e+00  2e-06  0.9890  9e-02   2  1  2 |  0  0
 8  -4.119e+01  -3.375e+01  +2e-07  1e-04  5e-04  7e+00  2e-07  0.9318  8e-04   2  1  1 |  0  0
 9  -9.930e+01  -6.756e+01  +2e-08  6e-05  3e-04  3e+01  2e-08  0.9890  1e-01   2  2  2 |  0  0
10  -1.511e+02  -1.140e+02  +2e-09  2e-05  1e-04  4e+01  3e-09  0.8399  2e-02   2  2  2 |  0  0
11  -4.178e+02  -1.330e+02  +1e-09  2e-03  5e-04  3e+02  1e-09  0.9593  3e-01   1  2  2 |  0  0
12  -2.844e+02  -2.824e+02  +8e-10  6e-04  2e-04  2e+00  4e-10  0.7694  2e-01   2  2  2 |  0  0
13  -5.216e+02  -5.175e+02  +7e-11  5e-04  1e-04  4e+00  4e-11  0.9153  3e-03   2  2  2 |  0  0
14  -6.399e+02  -6.309e+02  +7e-12  5e-02  2e-04  9e+00  4e-12  0.9890  3e-02   2  3  2 |  0  0
15  -7.280e+02  -7.259e+02  +6e-13  1e-02  7e-05  2e+00  3e-13  0.9020  5e-04   2  3  2 |  0  0

UNBOUNDED (within feastol=3.5e-09).
Runtime: 0.000256 seconds.

ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +0.000e+00  -4.765e+01  +2e+02  4e-01  3e-01  1e+00  8e+01    ---    ---    1  1  - |  -  - 
 1  -1.436e+03  -1.173e+03  +5e+01  6e+00  3e+01  2e+03  2e+01  0.9026  2e-01   2  1  1 |  0  0
 2  -1.238e+03  -1.223e+03  +5e-01  6e-02  4e-01  3e+01  3e-01  0.9890  1e-04   2  2  2 |  0  0
 3  -1.552e+03  -1.544e+03  +1e-02  3e-03  2e-02  9e+00  8e-03  0.9708  1e-04   2  2  2 |  0  0
 4  -1.892e+03  -1.873e+03  +2e-03  9e-04  8e-03  2e+01  1e-03  0.8633  3e-02   1  1  1 |  0  0
 5  -2.166e+03  -2.065e+03  +7e-04  8e-04  9e-03  1e+02  4e-04  0.8577  2e-01   2  2  1 |  0  0
 6  -2.230e+03  -2.227e+03  +1e-04  9e-05  1e-03  3e+00  5e-05  0.8736  6e-03   1  1  1 |  0  0
 7  -2.277e+03  -2.276e+03  +2e-05  2e-05  1e-04  1e+00  1e-05  0.8576  5e-02   3  1  1 |  0  0
 8  -2.278e+03  -2.278e+03  +2e-06  2e-06  2e-05  1e-01  1e-06  0.8878  3e-03   2  1  1 |  0  0
 9  -2.279e+03  -2.279e+03  +3e-07  4e-07  4e-06  8e-02  2e-07  0.9122  2e-01   2  2  2 |  0  0
10  -2.279e+03  -2.279e+03  +4e-08  3e-08  4e-07  9e-03  3e-08  0.8899  3e-03   3  2  2 |  0  0
11  -2.279e+03  -2.279e+03  +5e-09  5e-08  5e-08  2e-03  5e-09  0.9394  1e-01   3  2  2 |  0  0
12  -2.279e+03  -2.279e+03  +6e-10  7e-09  7e-09  2e-04  5e-10  0.8846  3e-03   2  2  2 |  0  0

OPTIMAL (within feastol=7.2e-09, reltol=2.6e-13, abstol=6.0e-10).
Runtime: 0.000177 seconds.

ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -7.670e-19  -5.497e-01  +7e+00  7e-01  1e-01  1e+00  1e+00    ---    ---    1  1  - |  -  - 
 1  -6.735e-02  -2.425e-01  +2e+00  7e-02  2e-02  2e-02  3e-01  0.8190  2e-02   1  1  1 |  0  0
 2  -9.443e-01  -1.366e+00  +9e-01  9e-02  7e-02  3e-01  2e-01  0.7025  4e-01   1  1  1 |  0  0
 3  -3.526e-01  -2.758e-01  +2e-01  7e-03  9e-03  1e-01  5e-02  0.8484  2e-01   1  1  1 |  0  0
 4  -8.049e-01  -5.192e-01  +7e-02  6e-03  9e-03  4e-01  2e-02  0.7760  1e-01   1  1  1 |  0  0
 5  -6.095e-01  -6.354e-01  +5e-02  2e-03  4e-03  3e-03  9e-03  0.7707  4e-01   1  1  1 |  0  0
 6  -1.512e+00  -1.488e+00  +6e-03  1e-03  3e-03  4e-02  1e-03  0.9890  1e-01   2  1  1 |  0  0
 7  -2.487e+00  -2.424e+00  +1e-03  5e-04  2e-03  7e-02  2e-04  0.8491  5e-02   1  1  1 |  0  0
 8  -6.336e+00  -5.773e+00  +4e-04  8e-04  3e-03  6e-01  6e-05  0.9560  3e-01   2  1  1 |  0  0
 9  -4.327e+00  -4.108e+00  +1e-04  2e-04  9e-04  2e-01  3e-05  0.9890  4e-01   2  1  1 |  0  0
10  -8.370e+00  -7.467e+00  +2e-05  2e-04  9e-04  9e-01  4e-06  0.8907  7e-02   2  1  1 |  0  0
11  -2.024e+01  -1.777e+01  +1e-06  5e-05  3e-04  2e+00  3e-07  0.9326  3e-03   2  1  1 |  0  0
12  -5.974e+01  -4.724e+01  +1e-07  3e-05  2e-04  1e+01  3e-08  0.9737  6e-02   1  1  2 |  0  0
13  -7.061e+01  -6.259e+01  +3e-08  1e-05  8e-05  8e+00  8e-09  0.7508  9e-02   2  2  2 |  0  0
14  -1.757e+02  -1.279e+02  +2e-08  7e-04  3e-04  5e+01  3e-09  0.9636  4e-01   1  2  3 |  0  0
15  -1.025e+02  -1.023e+02  +2e-08  3e-04  2e-04  3e-01  3e-09  0.3487  6e-01   1  2  2 |  0  0
16  -1.899e+02  -1.895e+02  +1e-09  9e-05  1e-04  4e-01  2e-10  0.9237  2e-03   2  3  2 |  0  0
17  -4.092e+02  -4.015e+02  +1e-10  2e-02  5e-04  8e+00  2e-11  0.9890  1e-01   1  3  3 |  0  0
18  -4.700e+02  -4.659e+02  +2e-11  4e-03  2e-04  4e+00  3e-12  0.8623  1e-02   2  2  3 |  0  0

UNBOUNDED (within feastol=6.2e-09).
Runtime: 0.000305 seconds.

ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -6.473e-15  -2.930e+01  +3e+02  6e-01  3e-01  1e+00  5e+01    ---    ---    1  1  - |  -  - 
 1  -1.423e+03  -1.452e+03  +9e+01  2e+00  1e+01  1e+03  2e+01  0.8545  2e-01   2  1  1 |  0  0
 2  -2.730e+02  -2.952e+02  +1e+01  5e-02  3e-01  2e+00  2e+00  0.9049  2e-02   2  2  2 |  0  0
 3  -3.655e+02  -3.667e+02  +7e-01  4e-03  2e-02  8e-01  1e-01  0.9362  4e-04   2  2  2 |  0  0
 4  -4.921e+02  -4.747e+02  +2e-01  2e-03  1e-02  2e+01  3e-02  0.8746  2e-01   2  1  1 |  0  0
 5  -5.536e+02  -5.221e+02  +7e-02  7e-04  9e-03  3e+01  1e-02  0.9890  4e-01   2  1  1 |  0  0
 6  -5.692e+02  -5.607e+02  +2e-02  2e-04  4e-03  9e+00  3e-03  0.7939  6e-02   2  1  1 |  0  0
 7  -5.826e+02  -5.733e+02  +1e-02  2e-04  4e-03  9e+00  2e-03  0.5417  4e-01   1  1  1 |  0  0
 8  -5.809e+02  -5.808e+02  +7e-04  5e-06  3e-04  2e-01  1e-04  0.9879  4e-02   1  1  1 |  0  0
 9  -5.815e+02  -5.815e+02  +7e-05  5e-07  3e-05  2e-02  1e-05  0.8981  2e-03   2  1  1 |  0  0
10  -5.816e+02  -5.815e+02  +4e-06  4e-08  2e-06  2e-03  9e-07  0.9890  6e-02   1  2  2 |  0  0
11  -5.816e+02  -5.816e+02  +7e-07  6e-09  3e-07  3e-04  1e-07  0.8557  1e-02   2  2  2 |  0  0
12  -5.816e+02  -5.816e+02  +2e-08  3e-10  7e-09  9e-06  3e-09  0.9890  1e-02   2  2  2 |  0  0

OPTIMAL (within feastol=6.7e-09, reltol=2.8e-11, abstol=1.7e-08).
Runtime: 0.000263 seconds.

**Version**
 - OS: CentOS Linux
 - CVXPY Version: 1.0.31

**Additional context**

**Comment by SteveDiamond** [comment]
The ``sigma_i`` values are absurdly small. Clearly ECOS is not handling this super well, but it's important to scale your problem appropriately.

**Comment by SteveDiamond** [comment]
If you want you can raise an issue for ECOS: https://github.com/embotech/ecos
