### ISSUE TITLE
Strange behaviour in "Control.ipynb" basic example

### ISSUE THREAD

**Issue by Olimoyo** [cvxgrp/cvxpy#1118]
Hi,

My question is about the basic control example notebook:
https://colab.research.google.com/github/cvxgrp/cvx_short_course/blob/master/intro/control.ipynb#scrollTo=lMZdHbyaU3F8

When I add the constraint below and nothing else, it causes the solver to crash. Unless I'm misunderstanding something, shouldn't this constraint not affect the solution?

```
# Form and solve control problem.
import cvxpy as cp


x = cp.Variable((n, T+1))
u = cp.Variable((m, T))

cost = 0
constr = []
for t in range(T):
    cost += cp.sum_squares(x[:,t+1]) + cp.sum_squares(u[:,t])
    constr += [x[:,t+1] == A@x[:,t] + B@u[:,t],
               cp.norm(u[:,t], 'inf') <= 1]
    constr += [-np.inf <= x[:, t], x[:, t] <= np.inf] # ************ EXTRA LINE HERE ********
# sums problem objectives and concatenates constraints.
constr += [x[:,T] == 0, x[:,0] == x_0]
problem = cp.Problem(cp.Minimize(cost), constr)
problem.solve(solver=cp.ECOS)
```

Thanks!

**Comment by SteveDiamond** [comment]
cvxpy doesn't permit ``np.inf``.

**Comment by Olimoyo** [comment]
Thanks for the info! 

I was a bit confused because I have seen np.inf get used in examples like https://osqp.org/docs/examples/mpc.html#cvxpy.

Is this a recent change?

**Comment by SteveDiamond** [comment]
That's an example for using OSQP, one of the solvers in cvxpy, directly, rather than through cvxpy.

**Comment by Olimoyo** [comment]
Sorry, the link is misleading but they have an example using cvxpy directly.

After doing a bit more testing, it seems like using cvxpy with the OSQP solver allows the use of `np.inf` but not with the other solvers. I see what you mean now though, thanks!

**Comment by SteveDiamond** [comment]
That's news to me actually! I assumed that the np.inf was breaking code in cvxpy. I had no idea you could propagate those constraints to OSQP.
