### ISSUE TITLE
Update docs / warnings prior to next release

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#1122]
We need to make changes on the following points:
1. The docs on contributing solver interfaces incorrectly describes the default conic form for the vectorized PSD cone. Our SDP solvers (CVXOPT, SCS, MOSEK) all use different formats. CVXOPT uses the format built-in to conic_solver.py, while SCS and MOSEK have their own formatting functions.
2. The error message for lack of a mixed-integer solver needs to be updated. Right now it doesn't tell users that ECOS_BB is once again an option. Users should be presented with a message that refers them to web documentation for detailed discussion. The discussion should mention that ECOS_BB is an option out of the box, but due to possible correctness issues, the solver will never be called automatically.
3. In discussion on mixed-integer solvers, NAG is mentioned as an option. Our NAG interface doesn't actually have mixed-integer support. The file ``cvxpy/reductions/solvers/defines.py`` should be checked to make sure NAG isn't miscategorized. (Misclassifications here are my fault.)
4. The release notes should mention changes to the MOSEK interface. It might actually be worth having some longer discussion on the solver page about the changes.

**Comment by SteveDiamond** [comment]
The NAG interface at least has no mixed integer support.

**Comment by rileyjmurray** [comment]
This should be linked to #1138
