### ISSUE TITLE
ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by sarimmehdi** [cvxgrp/cvxpy#1126]
**Describe the bug**
Unable to install cvxpy for Python 3.8 via pip

**To Reproduce**
`pip install cvxpy`

**Expected behavior**
cvxpy should install for python 3.8 on Ubuntu 18.04 inside venv

**Output**
message stating that cvxpy was installed successfully

**Version**
 - OS: Ubuntu 18.04
 - CVXPY Version: 1.1.5

**Additional context**
Full error log can be found here: https://github.com/cvxgrp/cvxpy/issues/1017#issuecomment-694591511

**Comment by gmjohns** [comment]
`sudo apt-get install python3-dev`
