### ISSUE TITLE
CPLEX Solver Use Issues

### ISSUE THREAD

**Issue by smm2311** [cvxgrp/cvxpy#1127]
**Describe the bug**
Despite having the CPLEX Community Edition installed and working (I can import and use it in Python scripts), CVXPY is having difficulty detecting it. I'm trying to run it on the very simple Linear Program example but continue to get an error claiming CPLEX is not installed.

**To Reproduce**
Implement the Linear program example ([https://www.cvxpy.org/examples/basic/linear_program.html](https://www.cvxpy.org/examples/basic/linear_program.html)) but simply change `prob.solve()` to `prob.solve(solver='CPLEX')`.

**Expected behavior**
I was simply hoping the solver would run without error. I am currently able to run both SCIP and GUROBI as solvers without error.

**Output**
```
Traceback (most recent call last):
  File "cvxpy_cplex.py", line 18, in <module>
    sol = prob.solve(solver='CPLEX')
  File "/home/smorgan/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)
  File "/home/smorgan/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 744, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(
  File "/home/smorgan/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 499, in get_problem_data
    solving_chain = self._construct_chain(
  File "/home/smorgan/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 651, in _construct_chain
    candidate_solvers = self._find_candidate_solvers(solver=solver, gp=gp)
  File "/home/smorgan/.local/lib/python3.8/site-packages/cvxpy/problems/problem.py", line 576, in _find_candidate_solvers
    raise error.SolverError("The solver %s is not installed." % solver)
cvxpy.error.SolverError: The solver CPLEX is not installed.
```

**Version**
 - OS: Ubuntu 20.04
 - CVXPY Version: 1.1.5

**Additional context**
I have played around with going into `.../cvxpy/reductions/solvers/` and altering the import name of CPLEX. CVXPY wants to import CPLEX as `import cplex as cpx` but CPLEX is now imported as `import docplex`. When I do this, it tells me that docplex has no attribute infinity (due to `.../cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py` which calls `cpx.infinity` multiple times.

**Comment by sschnug** [comment]
Some remarks from the top of my head (not checked):

- docplex is the high-lvl modelling-tool and *only one of the potential usages* within python
  - i think it's safe to say that no backend will use docplex as wrapper -> your experiments won't achieve anything in this regard (as docplex is not used; educated guess)
- `import cplex` is related to the low-lvl wrapper
  - i'm at most 1-2 minor behind current state-of-the-art, but i think it's safe to say, that this is still the way of importing the low-lvl wrapper (don't have access to installed docs right now)

Important:

- What happens when starting the interpreter (exactly the one which will be used with cvxpy) and doing `import cplex`
  - **If it fails**, your install of cplex is broken / incomplete
    - **important:** `pip install X` is not your typical install (and cannot work without any env-path management)
    - look into the docs for installation, but usually there is a python-directory within your cplex-install which offers some `setup.py` which needs to be installed`
  - **If it works**, there might be something wrong with cvxpy, but i don't think chances are high as the solver-setup is (imho) noch much more than trying the import

**Comment by kevkevinpal** [comment]
What version of python are you using? I think if you are using python3.8 cplex won't work, try downgrading to an older python version. 

I'm thinking this because of this StackOverflow but haven't verified myself
https://stackoverflow.com/questions/62437055/no-matching-distribution-found-for-cplex

**Comment by AndrewAwesomo** [comment]
I had the same problem.

I'm on Windows using cvxpy 1.1.7 on Python 3.7 with CPLEX Studio 12.9.0 (has support for Python 3.7).  I'm also using the professional version of CPLEX Studio, but I'm guessing this should work on the Community edition as well.

In your .../cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py file, you need to adjust the import of cplex: 

In the following functions, do this replacement:
constrain_cplex_infty(v):
solve_via_data(self, data, warm_start, verbose, solver_opts, solver_cache=None) :

replace:  import cplex as cpx
with:       import cplex.lib.python.cplex as cpx

You may need to do this elsewhere.  But after doing this in these two places, I was able to run models that I was previously using other open source solvers to solve, and it solves without error now.

**Comment by mvernacc** [comment]
Here is a workaround I used to get the CPLEX python API in python 3.8: https://stackoverflow.com/a/65117982/13216523

**Comment by smm2311** [comment]
Fixed by @mvernacc. After downgrading to 3.7, like @kevkevinpal recommended, was able to upgrade back to 3.8.
