### ISSUE TITLE
Unable to use integer=True

### ISSUE THREAD

**Issue by virsto** [cvxgrp/cvxpy#1129]
I have tried many of the cvxpy examples and ALL that use integer=true fail. Please provide information on why I am unable to use this option and how to fix it!

**Comment by virsto** [comment]
Here is the complete message I tried to post earlier.

Here is a simple python snippet that produces the error:

```
import cvxpy as cp
import numpy as np

n = 3
x = cp.Variable(n, integer=True)
#x = cp.Variable(n)
A = np.array([3,4,8]).reshape((1,3))
b = np.array([14]).reshape((1,1))
c = np.array([1,1,1]).reshape((1,3))
cons = [A @ x <= b, x >= 0]
obj  = cp.Maximize(c @ x)

# Construct a CVXPY problem
prob = cp.Problem(obj,cons)
prob.solve()
print("Status: ", prob.status)
print("The optimal value is", prob.value)
print("A solution x is")
print(x.value)
```

Here, is the complete error message in the popup window:
>python.exe - Ordinal Not found
>The ordinal 242 could not be located in the dynamic link library
>C:\Python36\Library\bin\mkl_intel_thread.dll

and this error message is shown after I close the popup:
>Long-step dual simplex will be used
>Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

I have tried many suggestions posted on the web; e.g. reinstall numpy and cvxpy, removal of suggested dll's, etc. I also tried some changes of my own; but none worked.

Note:

1.  The error occurs when prob.solve() is executed
    - I do not have Anaconda installed
    - Windows 10 platform
    - Python vers. 3.6.5
    - cvxpy  vers. 1.1.5
    -, numpy  vers. 1.19.2     
    -.. mkl_intel_thread.dll is located in C:\Python36\Library\bin\  
    -. No error occurs if I replace x = cp.Variable(n,integer=True) with x = cp.Variable(n)

**Comment by virsto** [comment]
Here is the complete message I tried to post earlier.

Here is a simple python snippet that produces the error:

import cvxpy as cp
import numpy as np

n = 3
x = cp.Variable(n, integer=True)
#x = cp.Variable(n)
A = np.array([3,4,8]).reshape((1,3))
b = np.array([14]).reshape((1,1))
c = np.array([1,1,1]).reshape((1,3))
cons = [A @ x <= b, x >= 0]
obj  = cp.Maximize(c @ x)

# Construct a CVXPY problem
prob = cp.Problem(obj,cons)
prob.solve()
print("Status: ", prob.status)
print("The optimal value is", prob.value)
print("A solution x is")
print(x.value)

Here, is the complete error message in the popup window:

    python.exe - Ordinal Not found
    The ordinal 242 could not be located in the dynamic link library
    C:\Python36\Library\bin\mkl_intel_thread.dll

and this error message is shown after I close the popup:

    Long-step dual simplex will be used
    Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

I have tried many suggestions posted on the web; e.g. reinstall numpy and cvxpy, removal of suggested dll's, etc. I also tried some changes of my own; but none worked.

Note:

    The error occurs when prob.solve() is executed
    I do not have Anaconda installed
    Windows 10 platform
    Python vers. 3.6.5
    cvxpy vers. 1.1.5
    numpy vers. 1.19.2
    mkl_intel_thread.dll is located in C:\Python36\Library\bin\
    No error occurs if I replace x = cp.Variable(n,integer=True) with x = cp.Variable(n)

**Comment by SteveDiamond** [comment]
Install Anaconda and try it that way.
