### ISSUE TITLE
DPP bug

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/cvxpy#1131]
**Describe the bug**
An expression that should be DPP is not recognized as DPP.

**To Reproduce**
```
import cvxpy as cp

x = cp.Variable()
p1 = cp.Parameter(nonneg=True)
p2 = cp.Parameter()
expr = p1 * cp.power(x * p2, -2)
print(expr.is_dpp())
```

**Expected behavior**
Should print True.

**Version**
 - OS: mac 10.14
 - CVXPY Version: 1.1.5

**Comment by akshayka** [comment]
Are you sure this is a bug?

From the [documentation](https://www.cvxpy.org/tutorial/advanced/index.html#disciplined-parametrized-programming):

```
For example, DPP forbids taking the product of two parametrized expressions
```

Reading the ruleset in the [paper](https://web.stanford.edu/~boyd/papers/pdf/diff_cvxpy.pdf) leads to the same conclusion.

**Comment by SteveDiamond** [comment]
But why would this be banned? Under the hood canonicalization introduces a new variable for power. Then it's not a product of two parameterized expressions.

**Comment by SteveDiamond** [comment]
Now that I understand the issue more, I guess this is similar to transforming ``p1 * p2 * var`` into ``p1 * t``, ``t = p2 * var`` where ``t`` is a new variable. That transformation is not part of DPP, so this transformation wouldn't be either. It's for free in some sense in the context of conic canonicalization, since the transformation will happen later anyway, but DPP is also for QPs and so it makes sense to keep things simple and not make too many assumptions.
