### ISSUE TITLE
cvxpy diff not returning expected shape

### ISSUE THREAD

**Issue by seanwoodworth** [cvxgrp/cvxpy#1134]

**Comment by SteveDiamond** [comment]
Please fill out the form.

**Comment by seanwoodworth** [comment]
Hi there,

I'm seeing the following unexpected output from the CVXPY diff() function.

Tests are based on Python / CVXPY versions:
Python 3.7.8
CVXPY 1.1.5

This simple example shows the observed differences between CVXPY and Numpy output shape for the same input dimensions to the diff function.  

>>> import cvxpy as cp
>>> import numpy as np
>>> A = cp.Variable((20,10))
>>> B = np.zeros((20,10))
>>> A.shape
(20, 10)
>>> B.shape
(20, 10)
>>> cp.diff(A,axis=1).shape
(10, 19)
>>> np.diff(B,axis=1).shape
(20, 9)

The result from CVXPY appears to be the transpose of numpy's output.   Nothing in the CVXPY documentation appears to mentions this.

Thanks 

Sean

Sean

**Comment by SteveDiamond** [comment]
This is totally a bug! Thanks for pointing it out. It's fixed now on master.

**Comment by seanwoodworth** [comment]
Thank you for the quick response on this.
