### ISSUE TITLE
block diagonal function

### ISSUE THREAD

**Issue by trevoravant** [cvxgrp/cvxpy#1137]
As far as I know, there is no "block diagonal" function in cvxpy, although there is one in CVX. So to create a block diagonal matrix, I wrote a function that uses a for-loop to iterate over each block, and uses the `bmat()` function to append each block to the matrix. To create all of the zero blocks around the diagonal blocks, my function uses the `numpy.zeros()` function.

My function works and runs quickly, but I have some questions:
* Although my function creates the matrix quickly, will the resulting matrix cause any slowness when it comes to running the solver?
* Is there a more preferred method to create a block diagonal matrix than my function?
* Is there a reason why cvxpy doesn't natively have a "block diagonal" function?

Thanks in advance

**Comment by SteveDiamond** [comment]
Your probably better off just calling bmat once with zero blocks off the diagonals.

**Comment by SteveDiamond** [comment]
In terms of why cvxpy doesn't have such a function, we could add it as a wrapper doing what I described above, but a more efficient implementation would be a major project.

**Comment by trevoravant** [comment]
Thanks for the reply. In my case, I don't know beforehand how many (or what size) the blocks will be, as they are specified by the user. The blocks will come in the form of a list (length unknown beforehand) of numpy matrices (dimensions unknown beforehand). In that case, would there any way to implement what you've described?

**Comment by SteveDiamond** [comment]
You mean it's an iterable or something? You would need to process the input and determine all the dimensions.

**Comment by trevoravant** [comment]
Ok thanks, I think I figured out how to do it with only one call to `bmat()`. I posted my code below in case it might help someone in the future.

```python
import numpy as np
import cvxpy as cp

def block_diag(arr_list):
    '''create a block diagonal matrix from a list of cvxpy matrices'''

    # rows and cols of block diagonal matrix
    m = np.sum([arr.shape[0] for arr in arr_list])
    n = np.sum([arr.shape[1] for arr in arr_list])

    # loop to create the list for the bmat function
    block_list = []  # list for bmat function
    ind = np.array([0,0])
    for arr in arr_list:
        # index of the end of arr in the block diagonal matrix
        ind += arr.shape

        # list of one row of blocks
        horz_list = [arr]

        # block of zeros to the left of arr
        zblock_l = np.zeros((arr.shape[0], ind[1]-arr.shape[1]))
        if zblock_l.shape[1] > 0:
            horz_list.insert(0, zblock_l)

        # block of zeros to the right of arr
        zblock_r = np.zeros((arr.shape[0], n-ind[1]))
        if zblock_r.shape[1] > 0:
            horz_list.append(zblock_r)

        block_list.append(horz_list)

    B = cp.bmat(block_list)

    return B
```
