### ISSUE TITLE
Diagonal matrix not reported as positive semi-definite

### ISSUE THREAD

**Issue by jasondark** [cvxgrp/cvxpy#1139]
There seems to be an issue with expressing diagonal matrices via `cp.diag(constant_vector)` -- namely it does not implement its own `is_psd()` / `is_nsd()` methods (https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/atoms/affine/diag.py#L45), so it inherits from `AffAtom` (https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/atoms/affine/affine_atom.py#L83), whose implementation, as far as I can tell, is asking if the underlying `constant_vector` is psd, which doesn't make sense.

I believe the fix would be to implement those methods on the `diag_vec` class. Here is a complete piece of code illustrating the behavior.

```python
import cvxpy as cp
import numpy as np

# Here is a super simple problem:
# Minimize x0^2 + 2x1^2

x = cp.Variable(2)
w = np.array([1.0, 2.0])

# Two equivalent ways of expressing the objective:

# Using quad_form
objective1 = cp.Minimize(cp.quad_form(x, cp.diag(w)))

# Using sum_squares
objective2 = cp.Minimize(cp.sum_squares(cp.multiply(x, np.sqrt(w))))

# Here is the issue:
objective1.is_dcp()  # == False (?!)
objective2.is_dcp()  # == True  (as it should be)

# objective1 fails to be dcp because quad_form asks if its matrix is psd
# (https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/atoms/quad_form.py#L64)
# and the following is observed:
cp.diag(w).is_psd() # == False, should be True
```

**Comment by SteveDiamond** [comment]
This is fixed on master.
