### ISSUE TITLE
sum_squares is memory inefficient

### ISSUE THREAD

**Issue by lukemarris** [cvxgrp/cvxpy#1140]
**Describe the bug**

The atom cp.sum_squares([SIZE]) seems to be using memory footprint on the order of [SIZE]^2, where I would have expected it to be closer to linear. Of note is that using cp.quad_form directly (with a sparse identity matrix) does not seem to be running into the same issues.

**To Reproduce**

```
x = cp.Variable(num_dists, nonneg=True)
con = cp.sum(x) == 1

cost = 1 - cp.sum_squares(x)  # Memory hungry.
cost = 1 - cp.quad_form(x, sp.sparse.eye(num_dists))  # Less hungry.
obj = cp.Maximize(cost)
prob = cp.Problem(obj, [con])
val = prob.solve(solver="OSQP")
```

**Version**
 - OS: Debian
 - CVXPY Version: 1.15

**Comment by SteveDiamond** [comment]
Could you try again with master? I believe I fixed this. Very good catch!
