### ISSUE TITLE
"negative row index found" for relatively simple problems

### ISSUE THREAD

**Issue by lukemarris** [cvxgrp/cvxpy#1141]
**Describe the bug**
When solving relatively small quadratic programs the indices used to populate sparse matrices can overflow. This is due to int32s being using for the indices. Also note that the size of the indices seems to be NUM_VARS^2 - which means that relatively simple sum_squares with ~> 50000 variables seem to choke.

**To Reproduce**
```
    x = cp.Variable(num_dists, nonneg=True)  # Where num_dists > sqrt(2^31)

    con = cp.sum(x) == 1

    cost = 1 - cp.sum_squares(x)
    obj = cp.Maximize(cost)
    prob = cp.Problem(obj, [con])
    val = prob.solve(solver="OSQP")
```

**Fix**
I was able to hack a fix together by using small modifications to `utilities/coeff_extractor.py`:

1. `P_tup = (data, (np.int64(P.row), np.int64(P.col)), P.shape)`.
2. Replace `ints` with `np.int64`.

I can verify that this fixed the case I have above, however someone more knowledgeable with the codebase should propagate the the usage of ints to int64s. I am also wary about potential compatibility issues with scipy.sparse.

**Version**
 - OS: Debian
 - CVXPY Version: 1.15

**Comment by SteveDiamond** [comment]
Are you using master? There are fixes in master related to this already.

**Comment by lukemarris** [comment]
Oh great. No, I wasn't using master, was on 1.15. Apologies for the noise!

I believe that recent commit fixes the issue. Thanks.

**Comment by SteveDiamond** [comment]
No worries! We just released a new version on pypi and that should have the fix as well.
