### ISSUE TITLE
CVXPY not respecting the constraints

### ISSUE THREAD

**Issue by mbronzo** [cvxgrp/cvxpy#1146]
**Describe the bug**
Good evening, first of all I would like to thank you for your time. My issue is that as one of the constraints of the problem I set x >=0 but the 4th value of the solution is negative. I have no idea how to solve this issue, also because I am not familiar with this library.

**To Reproduce**
import pandas as pd
import numpy as np
import cvxpy as cvx

df1 = pd.read_excel('...')
F = np.array(df1['A'])
obs = len(F) 
df = df1.iloc[:, 2:10]
I = np.array(df)
n = 8
x = cvx.Variable(n)
objective = cvx.Minimize(cvx.quad_over_lin(F - I @ x, obs))
constraints = [sum(x) == 1, x >= 0, x <= 1]
prob = cvx.Problem(objective, constraints)
print(obs)
print("Optimal value", prob.solve())
print("Indexes weights: ")
print(x.value)
print(sum(x.value))

**Expected behavior**
to have only positive values 

**Output**
Optimal value 0.0006967060759367921
Indexes weights: 
[ 2.32268747e-20  2.00133479e-01  4.62442145e-01 -3.21990719e-20
  1.12467205e-01  2.35557232e-02  3.42202086e-02  1.67181239e-01]

**Version**
 - OS: 10.15.7
 - CVXPY Version: 

**Additional context**

**Comment by rileyjmurray** [comment]
Hi @mbronzo. Can you please post the output of running ``prob.solve(verbose=True)``? This will tell us what solver is running and display information about the quality of the solution.

**Comment by aszekMosek** [comment]
There is no issue because the negative value of order -3e-20 is well within tolerance for being zero. See for instance https://docs.mosek.com/9.2/faq/faq.html#why-does-the-solution-slightly-violate-constraints In the same fashion the first value in your solution is zero as well.

**Comment by rileyjmurray** [comment]
@aszekMosek thanks for catching that. I was reading too fast and thought the issue was something else.

Closing this issue, because @aszekMosek's advice is definitive for this issue.

**Comment by mbronzo** [comment]
iter   objective    pri res    dua res    rho        time
   1   6.8509e-04   8.91e-16   1.27e-15   3.11e-03   2.29e-05s
  25   6.8509e-04   1.33e-15   1.28e-15   3.11e-03   3.72e-04s

status:               solved
number of iterations: 25
optimal objective:    0.0007
run time:             3.85e-04s
optimal rho estimate: 1.13e-05

0.000685094308004512

This was the output of the prob.solve(verbose=True). So the issue is that the negative solution is pithing tolerance level? 
I would also like to ask you why if I run the same analysis with the solver in Excel it manages to get a lower Variance and gets slightly different weights for the portfolio.

Thank you a lot for your time,
Marco.
