### ISSUE TITLE
Defining the shape of a Variable or Parameter as a variable

### ISSUE THREAD

**Issue by alisaab** [cvxgrp/cvxpy#1149]
I was looking into solving a problem sequentially but with the cvxpy Variables and Parameters changing shape between iterations. Is it possible to define the shape as a variable that can be set prior to solving? similar to how a Parameter can be set before solving.

**Comment by SteveDiamond** [comment]
This is not possible. I would suggest setting the dimensions to be those of the largest problem you'll solve, and filling in zeros in the unneeded entries.
