### ISSUE TITLE
cvxpy - reuse some vector constraints

### ISSUE THREAD

**Issue by andrea83ny** [cvxgrp/cvxpy#1155]
Hi there, please, could anybody take a look at this issue?
https://stackoverflow.com/questions/64488443/python-cvxpy-reuse-some-constraints
I can't seem to find anything related in the documentation and I don't understand how to face such issue. Thank you

**Comment by SteveDiamond** [comment]
You need to use parameters as described in the [linked post](https://stackoverflow.com/questions/44263875/cvxpy-how-to-efficiently-solve-a-series-of-similar-problems). Suppose you have the constraint ``rhs >= lhs`` which is sometimes used and other times not, where ``rhs`` and ``lhs`` have dimensions ``m x n``. Write the following code:
```
param = cp.Parameter((m, n))
slack = cp.Variable((m, n))
param_constraint = [rhs >= lhs + cp.multiply(param, slack)]
```
Now to turn off the constraint, set ``param.values = np.ones((m, n))``. To turn the constraint on, set ``param.values = np.zeros((m, n))``. You can turn some entries of the constraint off/on by setting some entries of ``param`` to be 1 and others to be 0.

**Comment by andrea83ny** [comment]
Thank you Steven, the issue of the link above is that it refers to changing values of some constants. 
In my case I don't a have any constant changing value at all.

**Comment by SteveDiamond** [comment]
I understand. Maybe I shouldn't have mentioned the post. The rest of my comment describes how to handle what I believe to be your situation, where you have a constraint you want to turn on and off.

**Comment by andrea83ny** [comment]
Hi Steve,  the thing is, if you look at the code I posted on stackoverflow, one of the constraints is always on. The problem is that it seems to link its solution to the first run and the it gives completely wrong values on the second run.  Please, would it be possible show how you would edit the sample code I posted on stackoverflow? Otherwise, I'm completely lost. Thank you

**Comment by akshayka** [comment]
Closing, since I saw this is solved on StackOverflow, and the issue wasn't due to CVXPY.
