### ISSUE TITLE
Product of 2 variable vectors.

### ISSUE THREAD

**Issue by surya-narayanan** [cvxgrp/cvxpy#1156]
**Is your feature request related to a problem? Please describe.**
Product of two vectors

**Describe the solution you'd like**
I am trying to add a constraint x^T y <= c where x and y are vectors of variables. I just asked Gurobi support and they say they can handle this. As far as I know, cvxpy does not handle products of variables in any form. Can you see if you can support this as well? If you currently already do, please let me know. This is how gurobi supports it. 

m = gp.Model()
n = 3
x = m.addMVar(n, name='x')
y = m.addMVar(n, name='y')
c = 2

m.addConstr(x @ np.eye(3) @ y <= 1)

**Describe alternatives you've considered**
I have tried transforming it to DCP such as exponentiation. I have also tried what Gurobi suggested to do in CVXpy and it does not work.

**Additional context**
Using colab

**Comment by rileyjmurray** [comment]
That constraint does not define a convex set. You can plot this for yourself by considering ``n=1``. GUROBI support says they allow such constraints because GUROBI allows for nonconvex quadratic constraints. Since CVXPY does not allow (and will not allow) nonconvex quadratic constraints, there is not much we can do to help you. Sorry I don't have better news!

**Comment by surya-narayanan** [comment]
No worries! Why won't cvxpy allow non convex quadratic constraints?

**Comment by rileyjmurray** [comment]
CVXPY is not intended to be the end-all-be-all of optimization modeling in python. It is designed very specifically for convex problems, and for problems that can be reduced to convex problems by suitable transformations (e.g. as in "log-log convex programming). The only exception to this rule, for the time being, is support for mixed-integer convex programming.
