### ISSUE TITLE
Use pytest instead of nose?

### ISSUE THREAD

**Issue by tommyod** [cvxgrp/cvxpy#1157]
I see that `nose` is used to run the tests, but [the docs state](https://nose.readthedocs.io/en/latest/) "Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership." It has not been updated for several years on [github.com/nose-devs/nose](https://github.com/nose-devs/nose).

Want me to create a PR to swap out nose as the test runner in favor of [pytest](https://github.com/pytest-dev/pytest)?

**Comment by SteveDiamond** [comment]
I've started using pytest on other projects and like it a lot. It seems to mostly work on ``cvxpy/tests``, with the exception of ``test_constant_atoms.py``. In short, I would be open to a PR that converts to pytest. @akshayka @rileyjmurray what do you think?

**Comment by tommyod** [comment]
I noticed the same about `test_constant_atoms.py`, but the re-write is not too bad - I can switch out nose yield-tests for pytest parametrization decorators.

**Comment by akshayka** [comment]
I'm all for it! A PR would be welcome.
