### ISSUE TITLE
Mistake in the content on page "https://www.cvxpy.org/examples/basic/quadratic_program.html"

### ISSUE THREAD

**Issue by RanjaniNiranjan** [cvxgrp/cvxpy#1173]
**Describe the bug**
In the paragraph below:
**Here P∈Sn+, q∈Rn, G∈Rm×n, h∈Rm, A∈Rp×n, and b∈Rn are problem data and x∈Rn is the optimization variable. The inequality constraint Gx≤h is elementwise.**
vector b should be in p dimension space and not Rn. Ax results in p*1 vector. Hence, b should also be p*1, and hence in Rp.
**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

**Expected behavior**

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: 
 - CVXPY Version:

**Additional context**

**Comment by SteveDiamond** [comment]
Thanks for finding this typo! We've fixed the docs.
