### ISSUE TITLE
How to increment the resolution of the results?

### ISSUE THREAD

**Issue by Antonio-Nappi** [cvxgrp/cvxpy#1175]
Hi everybody, I used cvxpy to emulate the lsqlin function of MATLAB. This library works perfectly, giving the same results but in MATLAB there is a very small value (2.6e-16) that cvxpy outputs as 0. Could I "increase the resolution" of cvxpy in order to compute even these small values or I have to work with this kind of approximation?

**Comment by rileyjmurray** [comment]
In numerical optimization, it is expected to see differences (in solution or objective value) as large as 1e-8 even for very high-accuracy solvers. CVXPY supports many solvers. You can ask a given solver to return a more accurate solution by providing appropriate keyword arguments to CVXPY's ``.solve`` function. However, you will not be able to achieve accuracy much better than 1e-10. Even for very simple problems such as least-squares, you can see differences greater than 1e-14 running the exact same algorithm on two different computers (the order of arithmetic operations on different CPUs will produce different rounding behavior in floating point).
