### ISSUE TITLE
cvxpy integer constraint to skip specific values

### ISSUE THREAD

**Issue by andrea83ny** [cvxgrp/cvxpy#1178]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Hi, I optimize portfolios at work and spend 99% of my time working with cvxpy.
When buying bonds and optimize the quantity a portfolio needs to buy, usually it's possible to buy such bond only in multiples of 1,000 units.
However, the minimum piece required to be bought is most of the time 10,000.
This means we either dont buy a bond at all or if we buy it, the quantity bought has to be either 10,000,  11,000,   12,000 and so on.
Is there a way (it seems it doesn't) to restrict certain values from the possible solutions an integer variable can have.
So let's assume we have an integer variable x that is non negative.
We basically want to buy 1000x but we know that x can be x = {0, 10, 11, 12, ...}
Is it possible to skip values 1.. 9 without adding other variables.
This would be extremely useful.
Thanks

**Describe the solution you'd like**
A clear and concise description of what you want to happen, and how your solution would solve the problem.

**Describe alternatives you've considered**

**Additional context**
Add any other context.

**Comment by SteveDiamond** [comment]
> Hi, I optimize portfolios at work and spend 99% of my time working with cvxpy.

That's very cool to hear! Unfortunately there's no way right now to pass an integer set constraint directly to a solver. I guess you could impose it by adding a binary variable b and writing ``x >= 10*b``. Hopefully adding that variable won't affect the solve time too much.

**Comment by SteveDiamond** [comment]
> Hi, I optimize portfolios at work and spend 99% of my time working with cvxpy.

That's very cool to hear! There's no way right now to pass down an integer set constraint to the solver. The only way I can think to impose the constraint is by creating a binary variable ``b`` and adding the constraint ``10*b <= x <= M*b``, where ``M`` is a maximal trade size.

**Comment by andrea83ny** [comment]
Thank you Steve. The problem is that I already have thousand of integer variables and I'm getting to a point where I don't know if I should consider a commercial solution or not. Adding the binary variable as you're suggesting makes totally sense but it drastically impact the solving time. Thanks for looking into this though, appreciated.

**Comment by SteveDiamond** [comment]
Have you tried SCIP? It's open source and quite good.
