### ISSUE TITLE
Remote execution? (Feature or doc request?)

### ISSUE THREAD

**Issue by noamgat** [cvxgrp/cvxpy#1183]
**Is your feature request related to a problem? Please describe.**
CVXPY problems are often computationally expensive. Sometimes a person's / organization's compute power is not distributed evenly. It would make sense to be able to harness the organization's power to solve the hard problems.

**Describe the solution you'd like**
A way to run the CVXPY solver remotely and to distribute the result to the caller's Variable objects.

**Describe alternatives you've considered**
I have looked into the source code and thought of some ways in, but wondered if anyone else has done this, and perhaps this is a documentation / example / help request rather than a feature request.

**Additional context**
If assistance would be provided, I would be happy to implement the rest and share it with the community.

**Comment by SteveDiamond** [comment]
I thought a lot at one point about how to have the problem data distributed. We didn't end up implementing any of that. I can't think of any solution that would be different than remote execution.

**Comment by noamgat** [comment]
@SteveDiamond this is what I was aiming to do. What do you think would be the correct way to elegantly implement this in cvxpy? Inherit from Solver class? A standalone class / module? What would be the correct information to pass to the other machine? A pickled "Problem" object? Is there any standardized "problem definition" file that can be generated? etc.

**Comment by rileyjmurray** [comment]
Chiming in here. @noamgat, I'm not sure if I understand your question, but at the moment we don't have a standardized "problem definition" file. Pickling a problem should work for transmitting model information though.

**Comment by noamgat** [comment]
So the ideal way to do this would be to create a standalone function that:
1) Receives the problem object
2) Pickles it, transports it to the other machine, solve there, return the object and unpickle it.
3) Redistribute the solution's values to the original problem's variable.value fields?

**Comment by noamgat** [comment]
OK, after experimenting, its impossible to pickle Problem objects after they have been solved, but pickling the variables is possible.
So the following code looks to be the correct structure for building such a solution:


```from cvxpy import Problem
from pickle import dumps, loads
import base64

from utils import solver_utils


def solve_problem(problem: Problem):
    pickled_problem = dumps(problem)

    # Transfer pickled_problem to the server...

    loaded_problem: Problem = loads(pickled_problem)
    opt_value = loaded_problem.solve(solver=solver_utils.get_solver_str())
    pickled_solved_variables = base64.b64encode(dumps(loaded_problem.variables()))

    # Transfer opt_value and pickled_solved_variables to the client...

    loaded_solved_variables = loads(base64.b64decode(pickled_solved_variables))
    for local_variable, loaded_variable in zip(problem.variables(), loaded_solved_variables):
        assert local_variable.name() == loaded_variable.name()
        local_variable.value = loaded_variable.value
    return opt_value```
