### ISSUE TITLE
Quadratic Programming in CVXPY using the CVXOPT solver

### ISSUE THREAD

**Issue by Michael-git96** [cvxgrp/cvxpy#1186]
**Description**
I am trying to run a simple QP problem using the cvxopt solver via cvxpy. If I run the QP problem using cvxopt directly, I get the right solution however if I run it using cvxpy it returns a certificate of dual infeasibility. I did some debugging and I could see that cvxpy was trying to use conelp rather than coneqp to solve the problem. 

**To Reproduce**
import cvxpy as cp
x_qp = cp.Variable((G[0].shape[1], 1))
prob = cp.Problem(cp.Minimize((1/2)*cp.quad_form(x, P) + q.T @ x),
                 [G @ x <= h])
prob.solve(solver="CVXOPT")

**Expected behavior**
The solve() method above would run through the cvxopt_conif.py python script which only attempts to use the conelp() solver of cvxopt. I would expect the code to recognise that it is a simple QP problem and run the coneqp(P, q, G, h) function instead of conelp().

**Output**
N/A

**Version**
 - CVXPY Version: 1.1.7

**Comment by rileyjmurray** [comment]
Hi, @Michael-git96. CVXPY performs transformations of the problem data so that our call to ``conelp`` is mathematically equivalent to ``coneqp`` (with some extremely minor exceptions). The only benefit to using ``coneqp`` is that solve times can improve when the quadratic form is sparse.

Your provided code does not allow us to reproduce the issue. Please post a complete example and we will take a look.

**Comment by Michael-git96** [comment]
Hi @rileyjmurray, thank you for your reply, do you have any documentation around the transformations performed by CVXPY so that the problems are mathematically equivalent in conelp as they are in coneqp? 

The G constraint matrix I am using is a scipy.sparse.csr_matrix() and the rest are numpy arrays and matrices. I can try and replicate the issue and send over the exact inputs P, q, G and h.

**Comment by Michael-git96** [comment]
Here are the files to replicate the issue. 
[G-npz.zip](https://github.com/cvxgrp/cvxpy/files/5683119/G-npz.zip)
[h-npz.zip](https://github.com/cvxgrp/cvxpy/files/5683120/h-npz.zip)
[q-npz.zip](https://github.com/cvxgrp/cvxpy/files/5683121/q-npz.zip)
[A-npz.zip](https://github.com/cvxgrp/cvxpy/files/5683122/A-npz.zip)

Once the files are unzipped and you have the .npz files, you can load them and run the optimisations using this code:

### Start of python code

import cvxpy as cp
import numpy as np
from scipy import sparse
import cvxopt

A = np.load('A.npz')["arr_0"]
P = A.T.dot(A).astype(np.double)
q = np.load('q.npz')["arr_0"]
G = sparse.load_npz('G.npz')
h = np.load('h.npz')["arr_0"]

# CVXPY QP using CVXOPT
x = cp.Variable((G.shape[1], 1))
qp_objective = (cp.Minimize(0.5*cp.quad_form(x, P) + q.T@x))
qp_problem = cp.Problem(qp_objective, [G@x <= h] )
qp_problem.solve(solver='CVXOPT', verbose=True)

# Using CVXOPT directly
solution = cvxopt.solvers.qp(cvxopt.matrix(P), cvxopt.matrix(q), scipy_sparse_to_cvxopt_sparse(G), cvxopt.matrix(h))

# Function to convert scipy sparse matrix to cvxopt sparse matrix
def scipy_sparse_to_cvxopt_sparse(M):
    coo = M.tocoo()
    cvx_sparse = cvxopt.spmatrix(coo.data.tolist(), coo.row.tolist(), coo.col.tolist(), size=M.shape)
    return cvx_sparse

### End of python code

When I run qp_problem.solve() function I get the output:
pcost       dcost       gap    pres   dres   k/t
 0: -4.5022e+16 -5.3768e+19  1e+21  5e+00  4e+00  1e+00
Certificate of dual infeasibility found.

When I run CVXOPT directly, the solver finds the Optimal solution.


If there is any other information you require, please do let me know.

**Comment by rileyjmurray** [comment]
The issue here is that your problem is very badly scaled. Some basic metrics:
```
np.linalg.norm(q)
643502187.8218355
np.linalg.norm(h)
388133723070.0196
np.linalg.norm(P)
1080.4211770932247
```
Here is the difference between primal and dual objectives in CVXOPT's solution:
```
'gap' = {float} 32783202.67793159
'relative gap' = {float} 5.218996937431626e-08
```
Having ``gap`` be that large basically means you can't trust the solution. If your problem was scaled in a more reasonable way, then CVXOPT would have a much larger relative gap, and probably would have returned an ``unknown`` status code.

I don't know whether or not your problem is bounded in exact arithmetic. Generally, SOCP formulations of QPs are numerically better-behaved, so if ``conelp`` says your problem is dual-infeasble, then that is probably correct. Your problem can be unbounded since ``P`` is low-rank; all that would need to happen is that the projection of ``q`` into the kernel of ``P`` points in a direction where ``{ x: G @ x <= h }`` is unbounded.

For information on the geometry of QP solutions and how to reformulate QP's into SOCP's, see https://docs.mosek.com/modeling-cookbook/qcqo.html.

**Comment by Michael-git96** [comment]
I can confirm that the problem is bounded in exact arithmetic due to the construction of the constraints so I still do not see how it could return a certificate of dual infeasibility since the variable x is in fact constrained to a closed set. 

I am aware that it is quite badly scaled, do you have any suggestions for scaling? I could not find a lot of literature on scaling convex problems, just that problems occur if matrices have a high condition number (are ill-conditioned).

**Comment by rileyjmurray** [comment]
Numerical optimization returns "approximate certificates" of infeasibility or unboundedness. If a dual variable ``mu`` nominally needs to satisfy ``A.T @ mu <= c``, then the solver might consider "small" violations of these constraints to be acceptable. The measure of constraint violation is usually normalized against problem data. In particular a common measure of constraint violation for something like ``A @ x = b`` might be ``np.linalg.norm( A @ x - b ) / (1 + np.linalg.norm(b))``. This sort of scaling is necessary to ensure a solver behaves similarly when data is scaled uniformly (e.g., ``A,b,c`` scaled to ``1e5*A,1e5*b,1e5*c``).

Unfortunately, I don't have suggestions for problem scaling. Commercial solvers often have parameters you can set so they can try various scaling heuristics, but for CVXOPT you'd have to explore those heuristics manually. Your first bet should be to adjust solver termination tolerances (e.g., for CVXOPT to require ``relative gap`` to be on the order of ``1e-14``), but this will only get you so far.

**Comment by Michael-git96** [comment]
I rescaled the optimisation problem so that:
np.linalg.norm(q)
643.5021878218356
np.linalg.norm(h)
388133536.19111514 (still not great but better)
np.linalg.norm(P)
1080.4211770932247 (same as before)

This time I get the same answer when using CVXOPT through CVXPY and CVXOPT coneqp directly. I can see in the CVXOPT documentation that the coneqp() solver does not return approximate certificates of infeasibility yet conelp() does. There is however no mention of scaling an optimisation problem in order to avoid "infeasible" outputs even though the problem is known to be feasible through construction. 

I would still be interested in finding out how CVXPY converts a quadratic programming problem to a linear programming problem, so if you have any mathematical documentation regarding that, please could you share it? 

Thank you for your help and time @rileyjmurray.

**Comment by rileyjmurray** [comment]
Glad you were able to get things to work out.

To clarify: CVXPY doesn't convert quadratic programs into linear programs. The confusion arises from CVXOPT's naming convention for "conelp" and "coneqp". Conelp is just for "cone programs" with linear objective functions. Cone programs can include nonlinear constraints such as ``||x || <= t`` or ``y*exp(x/y) <= z``. The typical convention in the literature is that a "quadratic cone program" refers to a cone program with a linear objective and conic constraints like ``||x|| <= t`` and ``||x||^2 <= y*z``.  CVXOPT's naming convention for "coneqp" refers to problems with quadratic objectives and general cone constraints.

You can find information on quadratic cone programming here: https://docs.mosek.com/modeling-cookbook/cqo.html#chap-cquadro, and you can see the standard reformulation from a "quadratic program" (solved with CVXOPT's coneqp) to a "quadratic cone program" (solved with CVXOPT's conelp) here: https://docs.mosek.com/modeling-cookbook/qcqo.html#conic-reformulation.

**Comment by Michael-git96** [comment]
Ok, that makes more sense, thank you for the clarification!
