### ISSUE TITLE
Error in recognizing convexity for power(max(difference,0),n)

### ISSUE THREAD

**Issue by dberkens** [cvxgrp/cvxpy#1187]
**Describe the bug**
Expressions of the type cvx.power(cvx.max(x-y,0),n) are not always recognized as convex for n>=1.

**To Reproduce**
import cvxpy as cvx
x = cvx.Variable()
y = cvx.Variable()
cvx.power(cvx.max(x-y,0),2)
cvx.power(cvx.max(x-y,0),3)
cvx.power(cvx.max(x-y,0),4)
cvx.power(cvx.max(x-y,0),5)
cvx.power(cvx.max(x-y,0),6)

**Expected behavior**
The DCP analyzer at https://dcp.stanford.edu/analyzer returns each of these expressions being positive and convex. 

**Output**
However, CVXPY is telling me that only a subset of these expressions are dcp. 

>>> cp.power(cp.max(x-y,0),2)
Expression(UNKNOWN, NONNEGATIVE, ())
>>> cp.power(cp.max(x-y,0),3)
Expression(CONVEX, NONNEGATIVE, ())
>>> cp.power(cp.max(x-y,0),4)
Expression(UNKNOWN, NONNEGATIVE, ())
>>> cp.power(cp.max(x-y,0),5)
Expression(CONVEX, NONNEGATIVE, ())
>>> cp.power(cp.max(x-y,0),6)
Expression(CONVEX, NONNEGATIVE, ())

**Version**
 - OS: Mac OS 10.15.6
 - CVXPY Version: 1.1.1 (with Python 3.6.0)

**Additional context**
Thanks in advance for any help on this!

Oh also - in cvxpy I am getting that cvx.max(x-y,0) is convex/unknown whereas in the dcp analyzer it is saying convex/positive.

**Comment by dberkens** [comment]
So I realize now that I should have been using cvx.maximum instead of max, so maybe that is intended behavior, but it does seem confusing to the user as it is likely an easy mistake to make...

**Comment by SteveDiamond** [comment]
It definitely is confusing, but this is the numpy convention. The behavior is correct for ``max(...,0)``.

**Comment by dberkens** [comment]
Ok - thanks for the reply I'll close it out!
