### ISSUE TITLE
cvxpy is interpreting element-wise multiplication as matrix multiplication

### ISSUE THREAD

**Issue by blenderben2** [cvxgrp/cvxpy#1188]
**Describe the bug**
cvxpy is interpreting `cp.multiply(x, (Q @ x))` as `x @ Q @ x`

**To Reproduce**
```
import cvxpy as cp
import numpy as np

N = 5

Q = cp.Parameter((N, N))
x = cp.Variable(N)

t = cp.min(cp.multiply(x, (Q @ x)))
objective = cp.Minimize(t)

matrix = np.random.random((N, N))
a_matrix = matrix.T @ matrix
Q.value = a_matrix

prob = cp.Problem(objective)

prob.solve()
print("status:", prob.status)
print("optimal value", prob.value)
```

**Expected behavior**
The objective function is based on 
![Screenshot from 2020-12-10 18-32-40](https://user-images.githubusercontent.com/31092148/101760721-32a62280-3b16-11eb-9b24-5771a23e4785.png)

hence, I am trying to make it an element-wise multiplication between `x` and `(Q @ x)`.

**Output**
However, when I run the program it gives me this error:

> DCPError: Problem does not follow DCP rules. Specifically:
The objective is not DCP. Its following subexpressions are not:
var11 @ param10 @ var11

and seems to be interpreting it as **two** matrix multiplication.

**Version**
 - OS: Ubuntu 18.04
 - CVXPY Version: 1.1.7

**Additional context**

**Comment by aszekMosek** [comment]
In any case the expression you actually want to model is very non-DCP.

**Comment by blenderben2** [comment]
Hi @SteveDiamond Im not sure what you mean by setting `x.value`. I've tried this and the results are as expected (element-wise multiplication), just that when combined into `cp.Problem` it prints out the subexpression as `x @ Q @ x`
```
import cvxpy as cp
import numpy as np

np.random.seed(0)
n_assets = 5
Q = np.random.random((n_assets, n_assets))
x = np.random.random(5)

cp.multiply(x, (Q@x)).value
>>> array([0.94910127, 0.28389189, 1.54127586, 0.841243  , 0.67718749])
```

Hi @aszekMosek can you briefly explain why it is non-DCP, sorry I am new to this.

**Comment by aszekMosek** [comment]
The expression you want to model is not convex, even when Q is the identity matrix, and in general each term appearing in your minimum will have the form ``x_i * (q_i^T * x)`` and such a bilinear expression is even more nonconvex itself. 

In fact I would guess this is what cvxpy is telling you: I would interpret the error message not as referring to ``x @ Q @ x``, but as referring to an individual ``x_i * Q_ij * x_j`` appearing inside one term that you later take minimum of.

**Comment by blenderben2** [comment]
thank you @aszekMosek @SteveDiamond
