### ISSUE TITLE
Missing implementation of some status return values of cvxopt.glpk.ilp()

### ISSUE THREAD

**Issue by lumbric** [cvxgrp/cvxpy#1191]
**Describe the bug**

The function `cvxopt.glpk.ilp()` may return following values as `status`: `'optimal'`, `'feasible'`, `'undefined'`, `'invalid formulation'`, `'infeasible problem'`, `'LP relaxation is primal infeasible'`, `'LP relaxation is dual infeasible'`, `'unknown'`. AFAICS the following values are not handled correctly by CVXPY and cause a KeyError:

* `'invalid formulation'`
* `'infeasible problem'`

Help text of `ilp()` mentions possible return values::

```
>>> from cvxopt.glpk import ilp
>>> help(ilp)
ilp(...)
    Solves a mixed integer linear program using GLPK.
    
    (status, x) = ilp(c, G, h, A, b, I, B)
...
    status       if status is 'optimal', 'feasible', or 'undefined',
                 a value of x is returned and the status string 
                 gives the status of x.  Other possible values of              status are:  'invalid formulation', 
                 'infeasible problem', 'LP relaxation is primal 
                 infeasible', 'LP relaxation is dual infeasible', 
                 'unknown'.
    
    x            a (sub-)optimal solution if status is 'optimal', 
                 'feasible', or 'undefined'.  None otherwise

```

These are the values which can are handled atm AFAICS:

https://github.com/cvxgrp/cvxpy/blob/b5b0f8b15b1f10106301d2b921ccfc6cbbbaf044/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py#L53-L63

There seem to be some unnecessary values too, they might be used by other subclasses. I haven't checked other versions of CVXOPT, this might have changed over time of course.

**To Reproduce**
I have a huge a example which can reproduce the problem. Unfortunately I haven't figured out yet how to reproduce it with a minimal problem. I'll add it to the ticket as soon as I get this done.

If one simply uses a problem with contradicting constraints, cvxopt will return `'LP relaxation is primal infeasible'`. I'm not sure what `'infeasible problem'` means exactly and how to construct one.

**Expected behavior**

The problem should be actually infeasible, so I expected `cp.Problem.solve()` to return without raising a `KeyError` exception and with the status field set to `infeasible` or something similar.

**Output**

That's what PyCharm says when I run my unit tests on my project:

```
...
/opt/miniconda3/envs/myenv/lib/python3.7/site-packages/cvxpy/problems/problem.py:395: in solve
    return solve_func(self, *args, **kwargs)
/opt/miniconda3/envs/myenv/lib/python3.7/site-packages/cvxpy/problems/problem.py:746: in _solve
    self, data, warm_start, verbose, kwargs)
/opt/miniconda3/envs/myenv/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py:326: in solve_via_data
    solver_opts, problem._solver_cache)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <cvxpy.reductions.solvers.conic_solvers.glpk_mi_conif.GLPK_MI object at 0x7fc0ec038510>
data = {'A': None, 'G': <16x12 sparse matrix, tc='d', nnz=44>, 'b': None, 'bool_vars_idx': [0, 4, 1, 5, 2, 6, ...], ...}
warm_start = True, verbose = False, solver_opts = {}, solver_cache = {}

    def solve_via_data(self, data, warm_start, verbose, solver_opts, solver_cache=None):
        import cvxopt
        import cvxopt.solvers
        # Save original cvxopt solver options.
        old_options = cvxopt.glpk.options.copy()
        # Silence cvxopt if verbose is False.
        if verbose:
            cvxopt.glpk.options["msg_lev"] = "GLP_MSG_ON"
        else:
            cvxopt.glpk.options["msg_lev"] = "GLP_MSG_OFF"
    
        # Apply any user-specific options.
        # Rename max_iters to maxiters.
        if "max_iters" in solver_opts:
            solver_opts["maxiters"] = solver_opts["max_iters"]
        for key, value in solver_opts.items():
            cvxopt.glpk.options[key] = value
    
        try:
            results_tup = cvxopt.glpk.ilp(data[s.C],
                                          data[s.G],
                                          data[s.H],
                                          data[s.A],
                                          data[s.B],
                                          set(int(i) for i in data[s.INT_IDX]),
                                          set(int(i) for i in data[s.BOOL_IDX]))
            results_dict = {}
            results_dict["status"] = results_tup[0]
            results_dict["x"] = results_tup[1]
        # Catch exceptions in CVXOPT and convert them to solver errors.
        #except ValueError as e:
        except RuntimeError as e:
            results_dict = {"status": "unknown"}
    
        # Restore original cvxopt solver options.
        self._restore_solver_options(old_options)
    
        # Convert CVXOPT results to solution format.
        solution = {}
>       status = self.STATUS_MAP[results_dict['status']]
E       KeyError: 'infeasible problem'

/opt/miniconda3/envs/myenv/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/glpk_mi_conif.py:90: KeyError
```

**Version**
 - OS: Ubuntu
 - CVXPY Version: 

``` >>> cp.__version__                                                                                                                  
'1.1.3'
>>> cvxopt.__version__                                                                                                              
'1.2.5'
```

**Additional context**

This seems to be very similar to  #812, but since I use CVXPY 1.1.3 the fix from #910 should be included already. So I guess this is still open.

**Comment by b1a0** [comment]
It seems like you have a problem that triggers both the status codes GLP_ETMLIM and GLP_NOFEAS in [glpk.c](https://github.com/cvxopt/cvxopt/blob/master/src/C/glpk.c). As far as I can see that is the only way to get to an "infeasible problem" as opposed to "infeasible" and might also help you in finding a minimal example or solving your original problem. 

The [GLPK reference manual](http://ftp.gnu.org/gnu/glpk/) (Version 4.35) tells me that that means that the search was prematurely terminated, because the time limit has been exceeded (GLP_ETMLIM) and that the problem has no feasible solution (GLP_NOFEAS). 

Therefore the correct status this code should be mapped to should probably be "infeasible" (since feasible timed out cases are handled differently).
