### ISSUE TITLE
cvxpy solving not reliable/consistent

### ISSUE THREAD

**Issue by blenderben2** [cvxgrp/cvxpy#1192]
**Describe the bug**
Solving problem not reliable/consistent. Certain runs will return `optimal`:
```
status: optimal
optimal value 1.1876279053948848
```
While others will return `infeasible`:
```
status: infeasible
optimal value inf
```

**To Reproduce**
```
import cvxpy as cp
import numpy as np

N = 5

Q_sqrt = cp.Parameter((N, N))
Q = cp.Parameter((N, N))
rets = cp.Parameter(n_assets)
R = cp.Parameter(n_assets, nonneg=True)

x = cp.Variable(N)
z = cp.Variable(N)
p = cp.Variable()
t = cp.Variable()

objective = cp.Minimize(p - t)

constraint_soc = [z == Q @ x, x.value * z >= t ** 2, z >= 0, x >= 0]
constraint_other = [cp.quad_over_lin(Q_sqrt @ x, p) <= N * p, 
                    rets.T @ x >= R,
                    cp.sum(x) == 1, p >= 0, t >= 0]
constraint_all = constraint_other + constraint_soc

matrix = np.random.random((N, N))
a_matrix = matrix.T @ matrix
Q.value = a_matrix
Q_sqrt.value = np.sqrt(a_matrix)

rets.value = np.random.random(n_assets)
R.value = np.random.random(n_assets)

prob = cp.Problem(objective, constraint_all)

assert prob.is_dcp()
assert prob.is_dpp()

prob.solve(solver='XPRESS', verbose=True)
print("status:", prob.status)
print("optimal value", prob.value)
```

**Expected behavior**
Consistently get `status: optimal`

**Output**
The verbose result when solve is `infeasible`:
```
Reading Problem CVX_xpress_conic
Problem Statistics
          29 (      0 spare) rows
          14 (      0 spare) structural columns
          79 (      5 spare) non-zero elements
Global Statistics
           0 entities        0 sets        0 set members
FICO Xpress v8.11.0, Community, solve started 10:40:10, Dec 14, 2020
Heap usage: 359KB (peak 359KB, 690KB system)
Minimizing SOCP CVX_xpress_conic with these control settings:
LPLOG = 1
MIPLOG = 2
OUTPUTLOG = 1
FEASTOL = 1.e-9
BARGAPTARGET = 1.e-30

Original problem has:
        41 rows           24 cols          121 elements
         2 cones          10 celems
Presolved problem has:
        12 rows           16 cols           47 elements
         2 cones          10 celems
Presolve finished in 0 seconds
Heap usage: 358KB (peak 404KB, 692KB system)

Coefficient range                    original                 solved        
  Coefficients   [min,max] : [ 6.95e-02,  5.00e+00] / [ 6.95e-02,  1.67e+00]
  RHS and bounds [min,max] : [ 5.95e-01,  1.00e+00] / [ 9.72e-01,  2.00e+00]
  Objective      [min,max] : [ 1.00e+00,  1.00e+00] / [ 5.00e-01,  1.00e+00]
  Quadratic      [min,max] : [ 2.00e+00,  2.00e+00] / [ 2.00e+00,  2.00e+00]
Autoscaling applied standard scaling

Barrier cache sizes : L1=32K L2=12288K
Using AVX support
Cores per CPU (CORESPERCPU): 12
Barrier starts after 0 seconds, using up to 12 threads, 6 cores
Barrier method finished in 0 seconds
Problem is infeasible after      0 iterations
Uncrunching matrix
 
   Its         Obj Value      S   Ninf  Nneg        Sum Inf  Time
     0           .000000      B      6     0       5.405385     0
Problem is infeasible
General IIS
 
 lc_00000      row     LE      1.000000
 lc_00008      row     LE      -.913214
 lc_00025      row     LE       .000000
 lc_00026      row     LE       .000000
 lc_00027      row     LE       .000000
 lc_00028      row     LE       .000000
Multiple IISs are supported for LPs only

status: infeasible
optimal value inf
```

**Version**
 - OS:  Ubuntu 18.04
 - CVXPY Version: 1.1.7

**Comment by aszekMosek** [comment]
It is surprising to me that the solver even accepted the problem. Since initially ``x.value==None``, whatever comes out of ``constraint_soc`` will have a lot of NaNs. For instance MOSEK will refuse to accept the input, while the ECOS and SCS log outputs will be full screens of NaNs. 

It is unfortunately not clear to me what constraint you actually meant with ``constraint_soc``, since both ``x`` and ``z`` are vectors.

**Comment by blenderben2** [comment]
Sorry for the confusion, below is the correct code to reproduce the error and I have added `x.value = np.random.random(N)` as an initialization (not sure if this is the proper way to initialize).

```
import cvxpy as cp
import numpy as np

N = 5

Q_sqrt = cp.Parameter((N, N))
Q = cp.Parameter((N, N))
rets = cp.Parameter(N)
R = cp.Parameter(N, nonneg=True)

x = cp.Variable(N)
z = cp.Variable(N)
p = cp.Variable()
t = cp.Variable()

objective = cp.Minimize(p - t)

constraint_soc = [z == Q @ x, x.value * z >= t ** 2, z >= 0, x >= 0]
constraint_other = [cp.quad_over_lin(Q_sqrt @ x, p) <= N * p, 
                    rets.T @ x >= R,
                    cp.sum(x) == 1, p >= 0, t >= 0]
constraint_all = constraint_other + constraint_soc

matrix = np.random.random((N, N))
a_matrix = matrix.T @ matrix
Q.value = a_matrix
Q_sqrt.value = np.sqrt(a_matrix)

rets.value = np.random.random(N)
R.value = np.random.random(N)

x.value = np.random.random(N) # <---- proper way to initialize?

prob = cp.Problem(objective, constraint_all)

assert prob.is_dcp()
assert prob.is_dpp()

prob.solve(solver='XPRESS')
print("status:", prob.status)
print("optimal value", prob.value)
```

As for the `constraint_soc`, this problem is modeled as a SOCP and is related to [#1185](https://github.com/cvxgrp/cvxpy/issues/1185), the only difference is that I have added `rets.T @ x >= R`.

As for `x` and `z` I originally thought it should follow [this](https://www.cvxpy.org/examples/basic/socp.html) SOCP example, in particular the `soc_constraints` list format with loops. However, after the discussion it was deemed not necessary (although I still have doubts).

Please let me know if a clearer explanation of the minimization problem is required! Thanks for your time :)

**Comment by rileyjmurray** [comment]
Please refer to https://www.cvxpy.org/tutorial/dcp/index.html and https://www.cvxpy.org/tutorial/functions/index.html. Your formulation is not correct as-stated. You need to replace ``x.value * z >= t ** 2`` by ``cp.quad_over_lin(t,x) <= z``.

**Comment by akshayka** [comment]
That said ... as @aszekMosek mentioned, CVXPY should refuse to compile this problem. The problem data has NaNs. Here's the SCS verbose output

![image](https://user-images.githubusercontent.com/1994308/102154576-8a060480-3e2e-11eb-9ddc-70eb58f34519.png)

**Comment by blenderben2** [comment]
Based on both of your feedback, I have update the code as below:

```
import cvxpy as cp
import numpy as np

N = 5

Q_sqrt = cp.Parameter((N, N))
Q = cp.Parameter((N, N))
rets = cp.Parameter(N)
R = cp.Parameter(N, nonneg=True)

x = cp.Variable(N)
z = cp.Variable(N)
p = cp.Variable()
t = cp.Variable()

objective = cp.Minimize(p - t)

constraint_soc1 = [z[i] == (Q @ x)[i] for i in range(N)] # z == Q @ x
constraint_soc2 = [cp.quad_over_lin(t, x[i]) <= z[i] for i in range(N)] # x.value * z >= t ** 2
constraint_soc3 = [z[i] >= 0 for i in range(N)] # z >= 0
constraint_soc4 = [x[i] >= 0 for i in range(N)] # x >= 0
constraint_soc = constraint_soc1 + constraint_soc2 + constraint_soc3 + constraint_soc4

constraint_other = [cp.quad_over_lin(Q_sqrt @ x, p) <= N * p, 
                    rets.T @ x >= R,
                    cp.sum(x) == 1, p >= 0, t >= 0]
constraint_all = constraint_other + constraint_soc

matrix = np.random.random((N, N))
a_matrix = matrix.T @ matrix
Q.value = a_matrix
Q_sqrt.value = np.sqrt(a_matrix)

rets.value = np.random.random(N)
R.value = np.random.random(N)

prob = cp.Problem(objective, constraint_all)

assert prob.is_dcp()
assert prob.is_dpp()

prob.solve(solver='SCS', verbose=True)

print("status:", prob.status)
print("optimal value", prob.value)
```

The code no longer has `.value` and I changed from `XPRESS` to `SCS`.

What I have noticed is when we comment out `rets.T @ x >= R` constraint, the problem is solved with `optimal` every time. When we include `rets.T @ x >= R` constraint, the problem gives `infeasible` solution sometimes.

However, I would like to solve it with `rets.T @ x >= R` included.

**Comment by aszekMosek** [comment]
@blenderben2 You use random data so it is not surprising you get various answers incl. infeasibility. I get the same with MOSEK. The  expected return constraint may be too demanding compared to the risk constraint for some inputs.

BTW the constraints soc3, soc4 and ``p>=0`` are redundant since they follow from the definitions of cones used in other constraints.

**Comment by blenderben2** [comment]
> the constraints soc3, soc4 and p>=0 are redundant 

just to be clear by redundant do you mean change to `z >= 0` and `x >= 0` (without loop) or **not** writing them out at all? 

I will try with non-random data as well. What are the suggested steps if non-random data fails to converge as well?

**Comment by aszekMosek** [comment]
@blenderben2 I meant removing them completely. If you get infeasible then it is infeasible and it is up to you which constraints to relax.
