### ISSUE TITLE
How to deal with the error when using Gurobi with cvxpy ：Unable to retrieve attribute 'BarIterCount'

### ISSUE THREAD

**Issue by wilixx** [cvxgrp/cvxpy#1194]
How to deal with the error when using Gurobi with cvxpy ：AttributeError: Unable to retrieve attribute 'BarIterCount'.

I have an Integer programming problem, using cvxpy and set gurobi as solver. When the number of variables is small, the result is ok. After the number of variables reach a level of like 43x13x6, then this error occured. I suppose it may be caused by the scale of the problem, in which the gurobi solver can not estimate the BarIterCount, which is the max Iterations needed.

Thus, I wonder, is there any way to manually set the BarItercount attribute of gurobi through the interface of the cvx? Or whether there exists other way to solve this problem?

Thanks for any suggestions you may provide for me.

The error is as follows:

  s.NUM_ITERS: model.BarIterCount,
  File "src\gurobipy\model.pxi", line 343, in gurobipy.gurobipy.Model.__getattr__
  File "src\gurobipy\model.pxi", line 1842, in gurobipy.gurobipy.Model.getAttr
  File "src\gurobipy\attrutil.pxi", line 100, in gurobipy.gurobipy.__getattr
AttributeError: Unable to retrieve attribute 'BarIterCount'

**Comment by neubig** [comment]
I'm experiencing the same problem with cvxpy 1.1.10 and Gurobi 9.1.1, any solution would be appreciated!

**Comment by Endorim** [comment]
Same issues over here (CVXPY 1.0.31 up untill 1.1.10 with Gurobi 9.1.1). Did not have issues with Gurobi 9.0; so the last version has broken something.  Highly appreciated, otherwise I will  (/need to) rewrite my code/constraints based on the Gurobi API.
