### ISSUE TITLE
Is it possible to obtain an approximated solution if the problem status is infisible?

### ISSUE THREAD

**Issue by Antonio-Nappi** [cvxgrp/cvxpy#1196]
Hi everybody, I'm trying to reproducing lsqlin matlab's function. I'm able to write the problem with the constraints, and it works, but sometimes the problem status is infisible, while on matlab works. How can I change the behavior in order to obtain maybe not the perfect solution but an approximation? I don't specify the solver of my problem, could be a problem?

**Comment by SteveDiamond** [comment]
See the discussion of a similar situation here: https://groups.google.com/g/cvxpy/c/RlWp_7N1RcI
