### ISSUE TITLE
Erraneous answer in cvxpy: optimal variable (as per cvxpy) does not follow the constraints. 

### ISSUE THREAD

**Issue by baekg** [cvxgrp/cvxpy#1201]
**Describe the bug**
I am solving an LP using cvxpy and one of the constraints was ">=0". But the solution that I was given back had one of the values negative.

**To Reproduce**
```
import cvxpy as cp
from  cvxpylayers.torch import CvxpyLayer
a=5
b=5
e=[(0,1),(1,2),(1,3),(2,3),(3,4)]
e_dict={}
count=0
n_e={i:[] for i in range(a)}
ine={i:[] for i in range(a)}
one={i:[] for i in range(a)}
for i in range(b):
    u,v=e[i]
    ine[u].append(i)
    ine[v].append(i)
    one[v].append(i+len(e))
    one[u].append(i+len(e))
q = cp.Parameter(2*b)
q.value=2*[0.5,0.5,0.5,0.5,0.5]
x = cp.Variable(2*b)
obj = cp.Minimize( x@q )
cons=[x>=0,x<=1]
s=0
t=4
for i in range(a):
    if i==s:
        cons.append(cp.sum(x[ine[i]])==0)
        cons.append(cp.sum(x[one[i]]) == 1)
    elif i==t:
        cons.append(cp.sum(x[ine[i]])==1)
        cons.append(cp.sum(x[one[i]]) == 0)
    else:
        cons.append(cp.sum(x[ine[i]])-cp.sum(x[one[i]])==0)
prob = cp.Problem(obj, cons)
print(prob.solve())
print(x.value)

```
**Expected behaviour**
All values in x.value should have been non-negative, which is not the case as seen in the following output.

**Output**
[ 4.30788558e-13  1.00000000e+00  1.43106021e-10 -1.20515176e-13
  1.00000000e+00  1.00000000e+00 -1.20530896e-13  1.43106014e-10
  1.00000000e+00  4.30786741e-13]

**Versions**
 - OS: Ubuntu/Linux
 - CVXPY Version:1.1.7

**Comment by rileyjmurray** [comment]
In numerical optimization, you only get solutions that are feasible up to a given precision. The constraint violation here (``1e-13``) is very modest. In general, you can only reasonably expect solutions to be feasible/optimal up to a tolerance of ``1e-8``. If you use the SCS solver, then your solutions may only be feasible/optimal up to tolerance ``1e-4``.
