### ISSUE TITLE
Is there a way to check if an `Expression` is integral?

### ISSUE THREAD

**Issue by adishavit** [cvxgrp/cvxpy#1209]
Obviously, a `cp.Variable` with `integer=True` is integral.  
But a `sum` of such variables is also integral, as is any affine expression with integral constants too.  
Similarly, things like minimum and maximum of integrals are also integral.

Is there such a recursive way to determine if a general, or at least a simple affine expression is integral?

**Comment by SteveDiamond** [comment]
This is not supported. You would have to write such a function yourself. If you do, it might be a good contribution!
