### ISSUE TITLE
The solver GUROBI is not installed.

### ISSUE THREAD

**Issue by geeeekDing** [cvxgrp/cvxpy#1216]
Hi I am new to Python (3.8)  and cvxpy (1.1.7) . I recently installed Gurobi(9.1) but I get this solver error:

prob.solve(solver = cvxpy.GUROBI, verbose=True)

SolverError: The solver GUROBI is not installed.

I found import gurobipy works properly and when I run    print(cvxpy.installed_solvers())     I see Gurobi listed as an installed solver:

print(cvx.installed_solvers())
['ECOS', 'ECOS_BB', 'GUROBI', 'OSQP', 'SCS']

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.1.7

**Comment by SteveDiamond** [comment]
Are you using Spyder? This issue has come up before when people had multiple python distributions and were using a different one than they expected.

**Comment by geeeekDing** [comment]
> Are you using Spyder? This issue has come up before when people had multiple python distributions and were using a different one than they expected.

Yes，I use Spyder as my python editor. And my question has been solved when I reboot Spyder. Thanks a lot to you.
