### ISSUE TITLE
log_normcdf atom

### ISSUE THREAD

**Issue by ali-tny** [cvxgrp/cvxpy#1219]
I've just finishing working through the edX convex optimisation course using python rather than Matlab, so this library has been a godsend - so first of all, thanks a lot!

In the last assignment a question relies on the CVX `log_normcdf` atom, which is missing in the python implementation.

In [the CVX version, a piecewise quadratic approximation is used](https://github.com/cvxr/CVX/blob/master/functions/%40cvx/log_normcdf.m), which is easy to implement in python (and which I used for the assignment), but I thought I might contribute the atom to the library to make it easier for python users in the future.

I wasn't sure of the best place to put the approximation though. I considered adding the atom as usual, then using the approximation at the DCP to cone canonicalization step, but I'm not sure its the best place - I was just going to calculate the approximate expression and canonicalize the tree, but that relies on the Dcp2Cone class so leads to a circular import, and generally feels like a bit of a hack.

Have you got any tips on what the best way to include the approximation is?

(I noticed there's already [a closed issue about this topic](https://github.com/cvxgrp/cvxpy/issues/63), but since there's a more specific question here I thought it'd be okay to open a new issue)

**Comment by SteveDiamond** [comment]
Does the canonicalization involve constraints? If not, you should implement it as a simple function like this:
```
def log_norm_cdf(x):
    return f(x)
```
where ``f`` is some composition of cvxpy functions. That way the function is just a wrapper, and you don't have to worry about canonicalization.

**Comment by rileyjmurray** [comment]
Chiming in. @ali-tny, circular imports are not uncommon in the cvxpy codebase. The way we get around this is with https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/expressions/cvxtypes.py. We also sometimes have import statements within a function call, rather than at the top level of a module.

**Comment by ali-tny** [comment]
Thanks both! 

@SteveDiamond the reason I considered using the canonicalisation to do the approximation rather than just writing it as a wrapper around a composwas because the absolute error on the approximation often makes the second decimal point a little different than `numpy.log(scipy.stats.norm.cdf(x))`:
![image](https://user-images.githubusercontent.com/26010073/105626592-a01ed000-5e84-11eb-83fd-05b4e60a7583.png)
(the jump to relative error of 1 is where `x` is high enough that the approximation is just 0)
i thought it might be nice for `problem.objective.value` to match up with numpy + scipy - but maybe its a lot of effort for not a lot of pay-off. What dya reckon?

@rileyjmurray ok cheers, good to know there's some precedent - it worked fine just importing the Dcp2Cone reduction in the canonicalisation but I wondered if I was being a bit of a cowboy.

**Comment by akshayka** [comment]
Another benefit of implementing `log_norm_cdf` as an atom (not a function) is that we'd be able to implement canonicalizations for multiple code paths. For example we could implement a canonicalizer in `Dgp2Dcp`, to support `log_norm_cdf` in LLCPs.

**Comment by SteveDiamond** [comment]
Ok I can see advantages of doing it as an atom, but that may be a bit too complicated for a PR from a new contributor. I still think the right path is to first do a simple PR with a wrapper function (like [pos](https://github.com/cvxgrp/cvxpy/blob/c88f09215252c932c101c842dd684a60c16ea4cf/cvxpy/atoms/elementwise/pos.py)). Later that can be elaborated into its own atom.

**Comment by ali-tny** [comment]
Ok cool, I'll get cracking then. Thanks for the guidance!
