### ISSUE TITLE
Solving time and initial LP bound about CBC

### ISSUE THREAD

**Issue by Xu-WJ** [cvxgrp/cvxpy#1220]
I just solve an MILP model using the solver CBC in cvxpy at my workstation.  Here are two issues, one is about the solving time, and the other one is about the relaxed LP model.
1) Solving time. We found the solver(CBC) reports solution information when the search completed, but we noticed that the Search completed time is much longer than the total time, for example(see the details below),  the search completed time is 221 seconds while the total time is 2031.81. Seconds.
2) Relaxed LP problem. After solving an MILP model, how can we print out the corresponding initial LP solution. 

Part of the processing information of an MILP model about the first issue is attached below.
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Cbc0010I After 100 nodes, 6 on tree, 2780494.7 best solution, best possible 2757924.3 (210.34 seconds)
**Cbc0001I Search completed - best objective 2780494.716351562, took 55093 iterations and 111 nodes (211.22 seconds)**
Cbc0032I Strong branching done 258 times (41103 iterations), fathomed 5 nodes and fixed 4 variables
Cbc0035I Maximum depth 13, 5 variables fixed on reduced cost
Cuts at root node changed objective from 2.75565e+06 to 2.75792e+06
Probing was tried 85 times and created 67 cuts of which 0 were active after adding rounds of cuts (0.768 seconds)
Gomory was tried 84 times and created 94 cuts of which 0 were active after adding rounds of cuts (0.703 seconds)
Knapsack was tried 49 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.659 seconds)
Clique was tried 49 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.009 seconds)
MixedIntegerRounding2 was tried 49 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.527 seconds)
FlowCover was tried 49 times and created 0 cuts of which 0 were active after adding rounds of cuts (183.764 seconds)
TwoMirCuts was tried 49 times and created 58 cuts of which 0 were active after adding rounds of cuts (0.458 seconds)
ZeroHalf was tried 1 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.009 seconds)

Result - Optimal solution found

Objective value:                2780494.71635156
Enumerated nodes:               111
Total iterations:               55093
Time (CPU seconds):             2031.80
Time (Wallclock seconds):       2031.80

**Total time (CPU seconds):       2031.81   (Wallclock seconds):       2031.81**

**Comment by SteveDiamond** [comment]
This sounds like a Cbc issue, not a cvxpy issue. You should post on the Cbc repo: https://github.com/coin-or/Cbc
I'm going to close the thread.
