### ISSUE TITLE
Numpy Minimum Version Mismatch in 1.1.8?

### ISSUE THREAD

**Issue by ndharasz** [cvxgrp/cvxpy#1236]
**Describe the bug**
I suspect a numpy version mismatch in cvxpy==1.1.8 caused by this commit:
https://github.com/cvxgrp/cvxpy/commit/71fa8221d5903f78f8273eaa7a222e571c493117
Would this cause a mismatch with the setup.py min version of 1.15?

**To Reproduce**
Build the following Dockerfile:
```
# syntax=docker/dockerfile:experimental
FROM python:3.7-slim-buster
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        build-essential \
        python3-dev
RUN pip install numpy==1.14.5
RUN pip install cvxpy==1.1.8
```

**Output**
```
Some build dependencies for cvxpy==1.1.8 from https://files.pythonhosted.org/packages/e6/3b/6a6650ed48503c4e4b2f497ce40517fe427f3cfacfc8fb43ff52f89bc4c8/cvxpy-1.1.8.tar.gz#sha256=444068d4eda9ffcd43578895174489d4cef36b28ba7ae8a96ab9ef9571d2b4ff conflict with the backend dependencies: numpy==1.14.5 is incompatible with numpy>=1.15.
```

**Expected behavior**
It should install just fine like cvxpy==1.1.7 does:
```
# syntax=docker/dockerfile:experimental
FROM python:3.7-slim-buster
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        build-essential \
        python3-dev
RUN pip install numpy==1.14.5
RUN pip install cvxpy==1.1.7
```

**Version**
 - OS: Docker python:3.7-slim-buster
 - CVXPY Version: 1.1.8 vs 1.1.7

**Additional Context**
Both 1.1.7 and 1.1.8 require numpy>=1.15 but only 1.1.8 throws an error. This is an issue for projects with many moving dependencies each that require numpy in some way and numpy 1.14.5 could get installed, but we want to have the min version that works for all dependencies. Is this error new in 1.1.8 and by design?

**Comment by edjeffery** [comment]
I've also noticed this issue. Downgrading pip to 18.1 fixed it, but that's not ideal in the long-term as that's very out-of-date now.

**Comment by akshayka** [comment]
Thanks for the detailed report! This is a known issue. We're working on it. (https://github.com/cvxgrp/cvxpy/pull/1234#issuecomment-772887993, #1229)

**Comment by rileyjmurray** [comment]
@edjeffery this should be fixed with cvxpy 1.1.9 and higher.

If anyone continues to have this problem with cvxpy >= 1.1.9, please leave a comment here. If no one has problems for a week then I'll close the issue.

**Comment by edjeffery** [comment]
Can confirm this now works in cvxpy 1.1.9. Thanks!

**Comment by ndharasz** [comment]
Looks like 1.1.9 installs just fine on our project now, thank you for the quick fix!
