### ISSUE TITLE
SCS returns wrong result

### ISSUE THREAD

**Issue by astghikhakobyan** [cvxgrp/cvxpy#1244]
Hello,

I am using SCS for solving an SDP problem in cvxpy. However, the result I get is incorrect when I compare it to other solvers such as MOSEK, SEDUMI, and SDPT3. All three solvers return somewhat similar results, while the SCS one is completely different. Similarly, when I solve the dual version of my problem, in the case of MOSEK the optimal values are very close, while in the case of SCS completely different.
Please see below my python code.

import cvxpy as cp
import numpy as np

ny = 2
p = 3
theta = 0.0001
alpha = 0.95
r = 0.2

Z = cp.Variable((ny,ny), PSD=True)
z = cp.Variable((1,1))
tau = cp.Variable((1,1))
lambda1 = cp.Variable()
eps = cp.Variable((1,1))
gamma = cp.Variable((ny,1))
Gamma = cp.Variable((ny,ny), symmetric=True)
mu_hat = cp.Parameter(ny)
Sigma_hat = cp.Parameter(ny+1)
y = cp.Parameter(ny)
mu_hat1 = cp.Parameter(1)
Sigma_hat1 = cp.Parameter(ny+1)
y1 = cp.Parameter(1)

Sigma = cp.Expression()
Sigma = cp.bmat([[Sigma_hat[0], Sigma_hat[1]],[Sigma_hat[1], Sigma_hat[2]]])
Sigma1 = cp.Expression()
Sigma1 = cp.bmat([[Sigma_hat1[0], Sigma_hat1[1]],[Sigma_hat1[1], Sigma_hat1[2]]])

constraints = [
    cp.bmat([[lambda1 * np.eye(ny) - Gamma, gamma + cp.vstack(lambda1 * mu_hat)],
             [(gamma + cp.vstack(lambda1 * mu_hat)).T, eps]
            ]) >> 0,
    cp.bmat([[lambda1 * np.eye(ny) - Gamma, lambda1 * Sigma],
             [(lambda1 * Sigma).T, Z]
            ]) >> 0,    
    cp.bmat([[np.eye(ny) + Gamma, gamma - cp.vstack(y)],
             [(gamma - cp.vstack(y)).T, tau + z]
            ]) >> 0, 
    cp.bmat([[Gamma, gamma],
             [gamma.T, tau]
            ]) >> 0, 
    eps >= 0, lambda1 >= 0
]
obj = cp.Minimize(- y1 + r * r + z + 1/(1 - alpha) * (tau + eps + cp.trace(Z) + lambda1 * (theta * theta - mu_hat1 - cp.trace(Sigma1))) )
prob = cp.Problem(obj, constraints)

In = np.array([7.09364830858073, 5.36952559622012, 0.305480348185421, 0.015403254279958, 0.639418852045523, 8.54820909414561, 6.36110970560502])
mu_hat.value = In[5:7]
Sigma_hat.value = In[2:5]
y.value = In[0:2]
mu_hat1.value = np.array([In[5:7].T @ In[5:7]])
Sigma_hat1.value = np.array([In[2]*In[2]+In[3]*In[3], In[2]*In[3]+In[3]*In[4], In[3]*In[3]+In[4]*In[4]])
y1.value = np.array([In[0:2].T @ In[0:2]])
prob.solve(solver = cp.SCS, verbose = False)
print("Optimal Value (SCS): ", prob.value, "solver time: ", prob.solver_stats.solve_time)
prob.solve(solver = cp.MOSEK, verbose = False)
print("Optimal Value (MOSEK): ", prob.value, "solver time: ", prob.solver_stats.solve_time)

**Comment by SteveDiamond** [comment]
SCS solves to lower precision than MOSEK etc. You can increase the precision by setting
```
prob.solve(solver = cp.SCS, verbose = True, eps=1e-6, max_iters=20000)
```
but that doesn't fix the problem here. Really you need to take this to the SCS repo https://github.com/cvxgrp/scs
