### ISSUE TITLE
Cvxpy fails for "mosek.iparam.infeas_report_level=inf" solver option

### ISSUE THREAD

**Issue by pqrz** [cvxgrp/cvxpy#1249]
Great Library!

**Desciption**
We were using the mosek (commercial) solver via cvxpy.
We want to set mosek's infeasibility report level [[link]](https://docs.mosek.com/9.2/toolbox/parameters.html#mosek.iparam.infeas_report_level) to `inf`, but cvxpy fails to accept it.

**To Reproduce**
Below is the code snippet that fails:
```
.
.
mosek_params = {mosek.iparam.infeas_report_auto: True, 
                mosek.iparam.infeas_report_level: 'inf'}                    # also tried np.inf 
model.solve(solver=cp.MOSEK, mosek_params=mosek_params)
.
.
```

Kindly suggest a resolution.

**Comment by aszekMosek** [comment]
Inf is never a suitable value for any Mosek data input, parameter value, or anything. 

Use 10 or 100 for this kind of parameter.

Understanding the Mosek infeasibility report when the problem had been transformed by CVXPY, without names, can be hard

**Comment by pqrz** [comment]
> Inf is never a suitable value for any Mosek data input, parameter value, or anything.

But the [mosek documentation](https://docs.mosek.com/9.2/toolbox/parameters.html#mosek.iparam.infeas_report_level) clearly states that it accepts values from **[0; +inf]** and with ends inclusive (from the square brackets)


> Use 10 or 100 for this kind of parameter.

In case it doesn't support, how should one specify to mosek to make as much verbose as possible? 
Specify 10 or 100 is still not a maximum report level, isn't it?


> Understanding the Mosek infeasibility report when the problem had been transformed by CVXPY, without names, can be hard

We are able to understand the infeasibility report and don't have any issue with this.

**Comment by aszekMosek** [comment]
Sorry, that is a notational inconsistency. It should be an open interval in this case to be super precise. Please specify 1000 and it will be the maximum output you can get.

**Comment by pqrz** [comment]
Helpful, Thanks :)
