### ISSUE TITLE
Implementation of a more memory efficient kl_div or entr atoms

### ISSUE THREAD

**Issue by KerimovEmil** [cvxgrp/cvxpy#1256]
**Problem Description**
I am trying to run the following convex optimization problem, however I am running into memory issues when I try to scale the number of scenarios. I originally tried this in cvxpy 0.4 and was able to get to `N~10,000` before running into memory issues at `N~50,000`. When I upgraded to cvxpy 1.1.10 , even `N~1000` runs into memory issues when instantiating the problem. 

```
minimize_{p} kl_div(p,q)
s.t.       sum(p) = 1
           convex_function(p, y) = some_value
```
In particular `q` and `y` are fully known before this optimization problem.

Here is a sample of my code to replicate the issue (removing any constraint on y):
```
import cvxpy
import numpy as np

N = 10

p = cvxpy.Variable(N, pos=True)
q = 1/N

obj = cvxpy.Minimize(sum(cvxpy.kl_div(p, q)))
c1 = sum(p) == 1

problem = cvxpy.Problem(obj, [c1])
problem.solve('ECOS', verbose=True)
print(p.value)
```

Ideally I'm interested in being able to make `N~500,000`. 

With cvxpy 4.0 I was able to run `N~10,000` quite fast but around `N~50,000` the cvxpy problem generation ran into memory issues on my computer. I tried to switch to the latest version of cvxpy but it became worse, now `N~1000` runs into memory issues when setting up the problem. 

I can reformulate/simplify the problem using the `entr` atom instead, but this still runs into memory issues when going up to `N~5000`. However `N=1000` takes quite a long time to solve (~373 seconds before reaching maximum iterations), compared to the almost instantaneous solving time in cvxpy 0.4. 

```
import cvxpy

N = 1000
x = cvxpy.Variable(N, pos=True)
obj = cvxpy.Maximize(sum(cvxpy.entr(x)))

c1 = sum(x) == N

problem = cvxpy.Problem(obj, [c1])
problem.solve('ECOS', verbose=True)
print(x.value/N)
```

**To replicate my exact environment setup**
I created a new python environment 
```
conda create --name cvxpy_kldiv_test python=3.7
activate cvxpy_kldiv_test
pip install cvxpy==1.1.10
```

An example of the memory issue I am seeing:
```
numpy.core._exceptions.MemoryError: Unable to allocate 95.4 MiB for an array with shape (25005002,) and data type int32
```

**Describe the solution you'd like**
If possible, to re-look at the implementation of the `kl_div` atom or the `entr` atom to be less memory intensive. This would hopefully enable me to increase the number of scenarios `(N)` without seeing memory issues or much of a performance hit when solving.

**Comment by SteveDiamond** [comment]
The problem is you are using the built-in Python ``sum`` instead of cvxpy's ``sum``. The following code only takes a few seconds on my machine:
```
import cvxpy
N = 100000
x = cvxpy.Variable(N, pos=True)
obj = cvxpy.Maximize(cvxpy.sum(cvxpy.entr(x)))

c1 = cvxpy.sum(x) == N

problem = cvxpy.Problem(obj, [c1])
problem.solve('ECOS', verbose=True)
print(x.value/N)
```

**Comment by SteveDiamond** [comment]
Maybe we should throw some kind of warning if the built-in some is used where cvxpy sum could be used. @akshayka @rileyjmurray what do you think?

**Comment by KerimovEmil** [comment]
Thank you that solved my issue!
