### ISSUE TITLE
list of lists casts to wrong shape in Constant 

### ISSUE THREAD

**Issue by RobertArbon** [cvxgrp/cvxpy#1262]
If pass a `cp.Constant` a list of lists, the final shape is the transpose of what you would expect. 

```
x = [[1, 2, 3], [4, 5, 6]]
print(np.array(x))
print(cp.Constant(x).value)
print(cp.Constant(np.array(x)).value)
```
output:
```
array([[1, 2, 3],
       [4, 5, 6]])
array([[1., 4.],
       [2., 5.],
       [3., 6.]])
array([[1., 2., 3.],
       [4., 5., 6.]])
```

I would expect `cp.Constant` to have the same behaviour as numpy. 

I'm on MacOS 11.1 (Big Sur)
cvxpy 1.1.7
python 3.7

Not the biggest problem, but I thought you should be aware. 

thanks!

**Comment by SteveDiamond** [comment]
Ok thanks for sharing! Right now inputting lists into ``Constant`` is not part of the public API.
