### ISSUE TITLE
Cvxpy to LP format convertor

### ISSUE THREAD

**Issue by pqrz** [cvxgrp/cvxpy#1266]
**What**
Can we add support to a auto-translate problem statement from Modelling Language 1 (Cvxpy) to Modelling Language 2 (LP format)?
LP format is quite standard format for representing optimization problem programmatically, this would be really helpful.

**Why**
Although I am aware that we can achieve this via CPLEX solver, i.e. `prob.solve(solver=cp.CPLEX, cplex_filename='model.lp')` but that has following cons:

1. **[Main problem]** Requires CPLEX to also solve the problem (is time-intensive in case of large problem size)

2. **[Utopia]** Generally speaking, if all modelling language can read and write in LP format - then we can achieve communication between modelling languages.

**Comment by pqrz** [comment]
Moderators: @SteveDiamond @akshayka 
Please feel free to close/delete the request, if you find it unreasonable.

**Comment by SteveDiamond** [comment]
@pqrz could you set the CPLEX solve time to be very small as well? That would address the drawbacks you mentioned. More broadly we don't really have bandwidth for a feature like this.

**Comment by pqrz** [comment]
Reducing the solve time would definitely help. Thanks a lot!

BTW - I intended to add this feature in a more longish way (~10 years).
