### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#1292]
**Describe the bug**
I try to compile the code with assertions enabled and compilation fails.

**To Reproduce**
Unclear: this is deep in a proprietary compilation stack, but the problem is evident on reading the code: `get_shape()` is going to return something multi-dimensional and `arg_idx` is a scalar - that's certainly problematic.

**Expected behavior**
Successful compilation.

**Output**
```
stderr: cvxpy/1.1.11/cvxpy/cvxcore/src/LinOpOperations.cpp:393:36: error: no member named 'get_shape' in 'std::vector<const LinOp *, std::allocator<const LinOp *> >'
  assert(arg_idx <= lin.get_args().get_shape());
```
The bug refers to [this](https://github.com/cvxgrp/cvxpy/blob/181e8ee694a30f095462a7c2acbfda2f3d6fa145/cvxpy/cvxcore/src/LinOpOperations.cpp#L393) line of code.

**Version**
 - OS: Any
 - CVXPY Version: 1.1.11

**Additional context**
A CI test with assertions enabled would rule out this class of errors.

**Comment by SteveDiamond** [comment]
Good catch! We'll be revamping our CI at some point due to Travis ending free accounts, so that would be a good time to start testing assertions.
