### ISSUE TITLE
Bug in element-wise power

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#1301]
On [this line](https://github.com/cvxgrp/cvxpy/blob/c88f09215252c932c101c842dd684a60c16ea4cf/cvxpy/atoms/elementwise/power.py#L331) of `power.py`, the variable `p` does not appear to be defined. The surrounding code is

```
        if self.p_rational is not None:
            p = self.p_rational
        elif p.value is not None:    # <-- This check looks problematic and is flagged as such by my linter
            p = self.p.value
        else:
            raise ValueError("Cannot compute grad of parametrized power when "
                             "parameter value is unspecified.")
```

**Version**
 - OS: Any
 - CVXPY Version: master

**Additional context**

**Comment by SteveDiamond** [comment]
Fixed on master. Thanks for pointing this out! What is your linter?
