### ISSUE TITLE
Incorrect use of `n` vs `m` in logistic regression example?

### ISSUE THREAD

**Issue by HanGuo97** [cvxgrp/cvxpy#1304]
**Describe the bug**
In the [logistic regression example](https://www.cvxpy.org/examples/machine_learning/logistic_regression.html), 

```python
problem = cp.Problem(cp.Maximize(log_likelihood/n - lambd * cp.norm(beta, 1)))
```

is the `n` (dimension) here supposed to be `m` (number of examples) instead? This does not affect the result since `n == m` here, but just curious.

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

**Expected behavior**

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: 
 - CVXPY Version:

**Additional context**

**Comment by SteveDiamond** [comment]
Thanks for catching this!
