### ISSUE TITLE
Solver 'GUROBI' failed. Try another solver.

### ISSUE THREAD

**Issue by Alkhaddour** [cvxgrp/cvxpy#1305]
<p>
===============================================================================<br>
                                     CVXPY                     <br>                
                                    v1.1.11                      <br>              
===============================================================================<br>
(CVXPY) Mar 22 10:55:00 AM: Your problem has 1594 variables, 21 constraints, and 0 parameters.<br>
(CVXPY) Mar 22 10:55:00 AM: It is compliant with the following grammars: DCP, DQCP<br>
(CVXPY) Mar 22 10:55:00 AM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)<br>
(CVXPY) Mar 22 10:55:00 AM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.<br>
-------------------------------------------------------------------------------<br>
                                  Compilation                                  <br>
-------------------------------------------------------------------------------<br>
(CVXPY) Mar 22 10:55:00 AM: Compiling problem (target solver=GUROBI).<br>
(CVXPY) Mar 22 10:55:00 AM: Reduction chain: CvxAttr2Constr -> Qp2SymbolicQp -> QpMatrixStuffing -> GUROBI<br>
(CVXPY) Mar 22 10:55:00 AM: Applying reduction CvxAttr2Constr<br>
(CVXPY) Mar 22 10:55:00 AM: Applying reduction Qp2SymbolicQp<br>
(CVXPY) Mar 22 10:55:00 AM: Applying reduction QpMatrixStuffing<br>
(CVXPY) Mar 22 10:55:00 AM: Applying reduction GUROBI<br>
(CVXPY) Mar 22 10:55:00 AM: Finished problem compilation (took 1.596e-01 seconds).<br>
(CVXPY) Mar 22 10:55:00 AM: (Subsequent compilations of this problem, using the same arguments, should take less time.)<br>
-------------------------------------------------------------------------------<br>
                                Numerical solver                               <br>
-------------------------------------------------------------------------------<br>
(CVXPY) Mar 22 10:55:00 AM: Invoking solver GUROBI to obtain a solution.<br>
Parameter OutputFlag unchanged<br>
   Value: 1  Min: 0  Max: 1  Default: 1<br>
Changed value of parameter QCPDual to 1<br>
   Prev: 0  Min: 0  Max: 1  Default: 0<br>
Gurobi Optimizer version 9.1.1 build v9.1.1rc0 (win64)<br>
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads<br>
---------------------------------------------------------------------------<br>
SolverError                               Traceback (most recent call last)<br>
</p>

`<ipython-input-57-46849ba99fc2> in <module>
      7         c = np.eye(10)[y[0].item()] - np.eye(10)[y_targ]
      8         prob, _ = form_lp(model_dnn_4, c, initial_bound, bounds)
----> 9         print("Targeted attack {} objective: {}".format(y_targ, prob.solve(solver=cp.GUROBI,verbose=True)))

~\anaconda3\envs\babylon37\lib\site-packages\cvxpy\problems\problem.py in solve(self, *args, **kwargs)
    434         else:
    435             solve_func = Problem._solve
--> 436         return solve_func(self, *args, **kwargs)
    437 
    438     @classmethod

~\anaconda3\envs\babylon37\lib\site-packages\cvxpy\problems\problem.py in _solve(self, solver, warm_start, verbose, gp, qcp, requires_grad, enforce_dpp, **kwargs)
    929         end = time.time()
    930         self._solve_time = end - start
--> 931         self.unpack_results(solution, solving_chain, inverse_data)
    932         if verbose:
    933             print(_FOOTER)

~\anaconda3\envs\babylon37\lib\site-packages\cvxpy\problems\problem.py in unpack_results(self, solution, chain, inverse_data)
   1251             raise error.SolverError(
   1252                     "Solver '%s' failed. " % chain.solver.name() +
-> 1253                     "Try another solver, or solve with verbose=True for more "
   1254                     "information.")
   1255 

SolverError: Solver 'GUROBI' failed. Try another solver, or solve with verbose=True for more information.`

**Comment by rileyjmurray** [comment]
Hi @Alkhaddour. Unfortunately, we can't provide support with such limited information. Please refer to our documentation on cvxpy.org.
