### ISSUE TITLE
`_update_problem_state(results_dict, sym_data, solver)` doesn't exist

### ISSUE THREAD

**Issue by r-barnes** [cvxgrp/cvxpy#1315]
**Describe the bug**
In `xpress_problem.py` I see:
```
    def _update_problem_state(self, results_dict, sym_data, solver):
        # ....
        super(XpressProblem, self)._update_problem_state(results_dict, sym_data, solver)
```
But I don't think there's a `_update_problem_state` anywhere in the superclass hierarchy.

**Version**
 - OS: Any
 - CVXPY Version: master

**Additional context**

**Comment by SteveDiamond** [comment]
I deleted the function. It seems like a relic of an earlier build.
