### ISSUE TITLE
cp.Variable does not follow constraints??

### ISSUE THREAD

**Issue by siyuanpurdue** [cvxgrp/cvxpy#1320]
Here is a function that sums a bunch of optimization result. Note that agg_load_trace is cp.Variable to be optimized in the parent optimization 
```
def deno_opt(agg_load_trace, t1, t2):
     denominator = 0
    
     for i in range(t1, t2+1):
        denominator += peak_estimation(np.array(list(agg_load_trace[0:i])))
```
Here is the parent optimization:
```
def calculate_eta_general(t1, t2):
    agg_load_trace = cp.Variable(time_slot)
    
    prob1 = cp.Problem(cp.Maximize((sum(agg_load_trace[t1-1:t2])-2*agg[0])/\
                        deno_opt(agg_load_trace,t1,t2)),constraints= \
                        [lower_agg_prediction()<= agg_load_trace, \
                        agg_load_trace <= upper_agg_prediction()])
    prob1.solve(solver=cp.SCS, max_iters= 10000)
```
I set break point in the deno_opt, but found agg_load_trace is allowed to violate the constraints ([lower_agg_prediction()<= agg_load_trace,  agg_load_trace <= upper_agg_prediction()]). So I wonder what is going on? Is this a bug? Or just a way of writing the code? What's the right to fix it?

**Comment by SteveDiamond** [comment]
Is the violation greater than 1e-3? Solver have numerical limitations. If you want the highest accuracy use a commercial solver like MOSEK.

**Comment by siyuanpurdue** [comment]
Yes, violation is way greater than 1e-3. It totally neglects the constraints. Violation is like x[1]>70, it returns a x[1] with 0. That makes me wonder if nested optimization is allowed. Because here $peak_estimation$ is itself a value from another optimization

**Comment by akshayka** [comment]
No, nested optimization is not supported.
