### ISSUE TITLE
does not support nested optimization? Or bug in nested constraints? Or way of writing

### ISSUE THREAD

**Issue by siyuanpurdue** [cvxgrp/cvxpy#1321]
To follow up the previous post, I wrote a simple program to verify how nested optimization works:
```
def cal_a(input_v):
    
    dec_var = cp.Variable(2)
    
    prob = cp.Problem(cp.Maximize(dec_var[0] + dec_var[1] + input_v), constraints=[3<=dec_var[0],\
                     dec_var[0]<=5, 4<=dec_var[1], dec_var[1]<=6] )
    prob.solve(verbose=True)
    print("dec_var!!!!!!",dec_var.value)
    if (prob.status != "optimal"):
        sys.exit("a Aborted! not optimal")
    return prob.value

def cal_b():
    tmp = cp.Variable()
    
    prob = cp.Problem(cp.Maximize(cal_a(tmp)), constraints = [1<=tmp, tmp<=3])
    prob.solve()
    if (prob.status != "optimal"):
        sys.exit("b Aborted! not optimal")
    
    print(tmp.value)
    return prob.value

if __name__ =="__main__":
    print(cal_b())
```
I get an unbounded result, which is obviously not correct.
This is the info I get when the verbose is true:
```
(CVXPY) Mar 30 09:46:55 AM: Invoking solver ECOS to obtain a solution.
ECOS 2.0.7 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS
It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  -9.000e+00  -1.500e+01  +6e+00  1e-03  2e-01  1e+00  1e+00    ---    ---    1  1  - |  -  - 
 1  -1.946e+02  -1.737e+02  +2e-01  1e-03  2e-01  3e+01  5e-02  0.9792  2e-02   0  0  0 |  0  0
 2  -1.750e+04  -1.499e+04  +2e-03  1e-03  2e-01  3e+03  6e-04  0.9890  1e-04   0  0  0 |  0  0
 3  -1.578e+06  -1.351e+06  +3e-05  1e-03  2e-01  2e+05  6e-06  0.9890  1e-04   1  0  0 |  0  0
 4  -1.423e+08  -1.219e+08  +3e-07  1e-03  2e-01  2e+07  7e-08  0.9890  1e-04   1  0  0 |  0  0
 5  -1.283e+10  -1.098e+10  +3e-09  1e-03  2e-01  2e+09  8e-10  0.9890  1e-04   1  0  0 |  0  0

UNBOUNDED (within feastol=7.2e-10).
Runtime: 0.000385 seconds.
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Mar 30 09:46:55 AM: Problem status: unbounded
(CVXPY) Mar 30 09:46:55 AM: Optimal value: inf
(CVXPY) Mar 30 09:46:55 AM: Compilation took 1.197e-02 seconds
(CVXPY) Mar 30 09:46:55 AM: Solver (including time spent in interface) took 0.000e+00 seconds
dec_var!!!!!! None
An exception has occurred, use %tb to see the full traceback.

SystemExit: a Aborted! not optimal
```
Obviously, it seems like the solver has totally thrown away the constraints we put on tmp/input_v, which is between 1 and 3.

Two question: 
1) Does cvxpy support nested optimization?
2) If yes, how to do that, say in my example? I know we can merge the two optimizations into one in this case, but I have some problems that requires nested optimization.

**Comment by akshayka** [comment]
By nested optimization, do you mean something like the objective function is the solution mapping of another optimization problem? (As in here? https://en.wikipedia.org/wiki/Bilevel_optimization)

If that's what you mean, then no, CVXPY does not support that.

**Comment by siyuanpurdue** [comment]
I am not pretty sure. Do you know the reason why my problem formulation cannot get the right output? Which is 5+6+3? The example shown above is a simple toy example I make up to show the scenario I want to resolve.

**Comment by siyuanpurdue** [comment]
Can cvxpy solve a min max problem, with different constraints for each layer? Also, if not, is there a way to solve it using some other method, as you may realize? Thanks!

**Comment by akshayka** [comment]
I think we are referring to the same thing with respect to nested optimization. CVXPY does not support nested optimization.

By the way, your problem in `cal_a` is unbounded, which is why the solve fails. `input_v` can be made arbitrarily negative. It knows nothing about `cal_b`.

Why not just use the following code?

```python3
tmp = cp.Variable()
dec_var = cp.Variable(2)
    
prob = cp.Problem(
    cp.Maximize(dec_var[0] + dec_var[1] + tmp),
    constraints = [1<=tmp, tmp<=3, 3<=dec_var[0], dec_var[0]<=5, 4<=dec_var[1], dec_var[1]<=6])
prob.solve()
    
print(tmp.value)
print(dec_var.value)
print(prob.value)
print(prob.status)
```

which yields

```
3.0
[5. 6.]
14.0
optimal
```

**Comment by akshayka** [comment]
> Can cvxpy solve a min max problem, with different constraints for each layer? Also, if not, is there a way to solve it using some other method, as you may realize? Thanks!

No, CVXPY cannot do this. If you wanted to solve this kind of problem, you could try using CVXPY Layers (https://github.com/cvxgrp/cvxpylayers), which lets you get the gradient of the solution of the inner problem with respect to the inputs. But you'd need to implement your own routine for solving the outer problem, using the gradients for the inner problem.

There may be better software packages out there for nested/bilevel optimization. Like I mentioned CVXPY does not support it.

**Comment by siyuanpurdue** [comment]
> think we are referring to the same thing with respect to nested optimization. CVXPY does not support nested optimization.
> 
> By the way, your problem in `cal_a` is unbounded,

Yes, I agree. I showed what kind of problem I want to achieve. You mean cal_b constraints on tmp passed to input_v is invisible to cal_a, right?

**Comment by siyuanpurdue** [comment]
> > Can cvxpy solve a min max problem, with different constraints for each layer? Also, if not, is there a way to solve it using some other method, as you may realize? Thanks!
> 
> No, CVXPY cannot do this. If you wanted to solve this kind of problem, you could try using CVXPY Layers (https://github.com/cvxgrp/cvxpylayers), which lets you get the gradient of the solution of the inner problem with respect to the inputs. But you'd need to implement your own routine for solving the outer problem, using the gradients for the inner problem.
> 
> There may be better software packages out there for nested/bilevel optimization. CVXPY does not support it.

Is there some tutorial or more examples available to follow to use CVXPY Layers, which get the gradient of the solution of the inner problem with respect to the inputs and also implement  routine for solving the outer problem, using the gradients for the inner problem? Any help to get started on this would be appreciated

**Comment by akshayka** [comment]
> You mean cal_b constraints on tmp passed to input_v is invisible to cal_a, right?
Yes, that's what I mean.

Unfortunately CVXPY doesn't support nested optimization, and we have no plans to add support for it. I would encourage you to look into other software packages for nested optimization, or try to reformulate your problem in such a way that nested optimization is not necessary. If the number of variables in the outer problem is small, you might consider doing a grid search over them.

**Comment by akshayka** [comment]
> Is there some tutorial or more examples available to follow to use CVXPY Layers, which get the gradient of the solution of the inner problem with respect to the inputs and also implement routine for solving the outer problem, using the gradients for the inner problem? Any help to get started on this would be appreciated

You could consult this paper and the linked-to code examples: https://web.stanford.edu/~boyd/papers/learning_copt_models.html

But getting up to speed might be considerable work. Why not try another software package that supports bilevel optimization out-of-the box? For example, it looks like Pyomo supports this: https://www.osti.gov/servlets/purl/1526125

**Comment by siyuanpurdue** [comment]
> > Is there some tutorial or more examples available to follow to use CVXPY Layers, which get the gradient of the solution of the inner problem with respect to the inputs and also implement routine for solving the outer problem, using the gradients for the inner problem? Any help to get started on this would be appreciated
> 
> You could consult this paper and the linked-to code examples: https://web.stanford.edu/~boyd/papers/learning_copt_models.html
> 
> But getting up to speed might be considerable work. Why not try another software package that supports bilevel optimization out-of-the box? For example, it looks like Pyomo supports this: https://www.osti.gov/servlets/purl/1526125

I see! Thank you very much for quick response and giving some guide!

**Comment by akshayka** [comment]
You're welcome! I hope you're able to solve your problem!
