### ISSUE TITLE
solver_stats are empty when using ECOS_BB

### ISSUE THREAD

**Issue by ashamraeva** [cvxgrp/cvxpy#1322]
**Describe the bug**
When using ECOS_BB with cvxpy, the `solver_stats` attribute of `problem` is empty, while for other solvers it usually contains some useful solver-specific optimization details.

**To Reproduce**
Just solve any problem with ECOS_BB and look at `problem.solver_stats`.

**Expected behavior**
To see some solver-specific info in `problem.solver_stats`, similar to other solvers.

**Version**
 - OS: ubuntu 20.04
 - CVXPY Version: 1.1.11

**Additional context**
I believe the only change needed here is to pass `attr` explicitly at lines 104-106 in [ecos_bb_conif.py](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/ecos_bb_conif.py) instead of an empty dict (when a solution is present) or instead of None (when there is no solution):

```
        attr = {}
        attr[s.SOLVE_TIME] = solution["info"]["timing"]["tsolve"]
        attr[s.SETUP_TIME] = solution["info"]["timing"]["tsetup"]
        attr[s.NUM_ITERS] = solution["info"]["iter"]
        attr[s.EXTRA_STATS] = solution

        if status in s.SOLUTION_PRESENT:
            ...
            return Solution(status, opt_val, primal_vars, dual_vars, {})
        else:
            return failure_solution(status)
```

Let me know if my suggestion is fine and I will submit a PR.

**Comment by SteveDiamond** [comment]
@ashamraeva your analysis is right. A PR would be welcome!
