### ISSUE TITLE
How to constraint the number of occupied CPUs 

### ISSUE THREAD

**Issue by xyyjcyd** [cvxgrp/cvxpy#1331]
**Is your feature request related to a problem? Please describe.**
I've found that when running CVXPY with solver MOSEK or some others, the process will occupies almost all CPUs in my computer. For example, I ran the same program in both computers with Intel I9  12 cores 4.6GHz and  I5 2 cores 3.4GHz. The process occupied 24 and 4 CPUs respectively.  But the run time of I9 is 0.05 while the I5 is 0.1, which means the calculating  speed is just double but sex-tuple. Maybe this is a sort of waste of computation resource.  So I want to  to constraint the number of occupied CPUs.

**Describe the solution you'd like**
I want to constraint the number of occupied CPUs when solving a problem. For example, I can determine that 4 is the maximum number of occupied number of CPUs when solving CVXPY problem. 

**Describe alternatives you've considered**
I guess that maybe CVXPY use Multiprocessing package for multiprocessing which may open the same number of processes as the number of all CPUs. Therefore, may I change the maximum number of opened process? What changes should I do to make it?

**Additional context**

**Comment by phschiele** [comment]
@xyyjcyd This should already be possible using [solver options](https://www.cvxpy.org/tutorial/advanced/index.html#setting-solver-options). I had a similar problem when running optimizations in a program that was already parallelized itself, leading to a complete freeze. I am mostly using CPLEX, and I was able to solve the problem by passing `"threads": 1` in the solver parameter dictionary. I think [similar parameters exist for MOSEK](https://docs.mosek.com/9.2/pythonfusion/parameters.html#mosek.iparam.num_threads).

**Comment by xyyjcyd** [comment]
> @xyyjcyd This should already be possible using [solver options](https://www.cvxpy.org/tutorial/advanced/index.html#setting-solver-options). I had a similar problem when running optimizations in a program that was already parallelized itself, leading to a complete freeze. I am mostly using CPLEX, and I was able to solve the problem by passing `"threads": 1` in the solver parameter dictionary. I think [similar parameters exist for MOSEK](https://docs.mosek.com/9.2/pythonfusion/parameters.html#mosek.iparam.num_threads).

Thank you! I have tested suggestion right now. But I find it doesn't make any difference. Here is my code:
`params={ 'MSK_IPAR_NUM_THREADS': 1 , 'MSK_IPAR_INTPNT_MULTI_THREAD':False }`
`prob.solve( solver=cp.MOSEK, mosek_params=params )`

I find that the optimizer occupied only one thread. But the there is still 4 process during running among which there is one process need more computation. Here is the result:
![Screenshot from 2021-04-13 19-24-06](https://user-images.githubusercontent.com/46839369/114545326-680e7880-9c8e-11eb-8380-f844bfc4ccd4.png)


===============================================================================
                                     CVXPY                                     
                                    v1.1.12                                    
===============================================================================
(CVXPY) Apr 13 07:10:33 PM: Your problem has 41 variables, 6 constraints, and 0 parameters.
(CVXPY) Apr 13 07:10:33 PM: It is compliant with the following grammars: DCP, DQCP
(CVXPY) Apr 13 07:10:33 PM: (If you need to solve this problem multiple times, but with different data, consider using parameters.)
(CVXPY) Apr 13 07:10:33 PM: CVXPY will first compile your problem; then, it will invoke a numerical solver to obtain a solution.
-------------------------------------------------------------------------------
                                  Compilation                                  
-------------------------------------------------------------------------------
(CVXPY) Apr 13 07:10:33 PM: Compiling problem (target solver=MOSEK).
(CVXPY) Apr 13 07:10:33 PM: Reduction chain: Dcp2Cone -> CvxAttr2Constr -> ConeMatrixStuffing -> MOSEK
(CVXPY) Apr 13 07:10:33 PM: Applying reduction Dcp2Cone
(CVXPY) Apr 13 07:10:33 PM: Applying reduction CvxAttr2Constr
(CVXPY) Apr 13 07:10:33 PM: Applying reduction ConeMatrixStuffing
(CVXPY) Apr 13 07:10:33 PM: Applying reduction MOSEK
(CVXPY) Apr 13 07:10:33 PM: Finished problem compilation (took 6.644e-02 seconds).
-------------------------------------------------------------------------------
                                Numerical solver                               
-------------------------------------------------------------------------------
(CVXPY) Apr 13 07:10:33 PM: Invoking solver MOSEK  to obtain a solution.


Problem
  Name                   :                 
  Objective sense        : max             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 123             
  Cones                  : 82              
  Scalar variables       : 330             
  Matrix variables       : 0               
  Integer variables      : 0               

Optimizer started.
Problem
  Name                   :                 
  Objective sense        : max             
  Type                   : CONIC (conic optimization problem)
  Constraints            : 123             
  Cones                  : 82              
  Scalar variables       : 330             
  Matrix variables       : 0               
  Integer variables      : 0               

Optimizer  - threads                : 1               
Optimizer  - solved problem         : the primal      
Optimizer  - Constraints            : 123
Optimizer  - Cones                  : 83
Optimizer  - Scalar variables       : 330               conic                  : 288             
Optimizer  - Semi-definite variables: 0                 scalarized             : 0               
Factor     - setup time             : 0.00              dense det. time        : 0.00            
Factor     - ML order time          : 0.00              GP order time          : 0.00            
Factor     - nonzeros before factor : 1444              after factor           : 1686            
Factor     - dense dim.             : 0                 flops                  : 1.25e+05        
ITE PFEAS    DFEAS    GFEAS    PRSTATUS   POBJ              DOBJ              MU       TIME  
0   9.8e+01  4.0e+00  8.2e+01  0.00e+00   -8.100000000e+01  0.000000000e+00   1.0e+00  0.01  
1   5.0e+01  2.0e+00  5.1e+01  -9.16e-01  -1.864405228e+02  -1.175660878e+02  5.1e-01  0.01  
2   4.0e+01  1.6e+00  3.2e+01  -2.32e-01  -7.555420902e+01  -2.360747081e+01  4.0e-01  0.01  
3   8.8e+00  3.6e-01  5.7e+00  -3.81e-02  -1.331023259e+02  -1.148124650e+02  9.0e-02  0.01  
4   2.0e+00  8.0e-02  6.5e-01  6.64e-01   -1.567216522e+02  -1.520045625e+02  2.0e-02  0.01  
5   4.8e-01  1.9e-02  7.8e-02  9.37e-01   -1.567680061e+02  -1.555970362e+02  4.9e-03  0.01  
6   5.6e-02  2.3e-03  2.9e-03  9.85e-01   -1.567964041e+02  -1.566590937e+02  5.7e-04  0.01  
7   1.4e-03  5.8e-05  1.2e-05  9.98e-01   -1.568113252e+02  -1.568077925e+02  1.5e-05  0.01  
8   5.8e-06  2.3e-07  3.0e-09  1.00e+00   -1.568117695e+02  -1.568117552e+02  5.8e-08  0.01  
9   6.4e-08  2.6e-09  3.5e-12  1.00e+00   -1.568117735e+02  -1.568117734e+02  6.5e-10  0.01  
Optimizer terminated. Time: 0.01    


Interior-point solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : OPTIMAL
  Primal.  obj: -1.5681177353e+02   nrm: 1e+02    Viol.  con: 2e-07    var: 2e-10    cones: 0e+00  
  Dual.    obj: -1.5681177337e+02   nrm: 8e+00    Viol.  con: 0e+00    var: 2e-09    cones: 0e+00  
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) Apr 13 07:10:33 PM: Problem status: optimal
(CVXPY) Apr 13 07:10:33 PM: Optimal value: -1.568e+02
(CVXPY) Apr 13 07:10:33 PM: Compilation took 6.644e-02 seconds
(CVXPY) Apr 13 07:10:33 PM: Solver (including time spent in interface) took 3.724e-02 seconds
 running time is 0.126434

**Comment by phschiele** [comment]
It always helps to see the code you are working with, so if possible, can you provide an MWE?

Using the following example script I can clearly see that only one CPU is being used when passing the CPLEX parameter:

```python
import time

import cvxpy as cp
import numpy

# Problem data.
m = 199
n = 800
n_solves = 100 
numpy.random.seed(1)
A = numpy.random.randn(m, n)
parameter_values = numpy.random.randn(m,100)


# # w/o parametrization
solver_time = 0
start=time.time()
for i in range(n_solves):
    x = cp.Variable(n)
    b = parameter_values[:,i]
    prob = cp.Problem(cp.Minimize(cp.sum_squares(A @ x - b)),
                       [x >= 0])
    prob.solve(solver=cp.CPLEX, cplex_params={"threads":1})
    solver_time += prob.solver_stats.solve_time
end = time.time()
print(f'total_time {end-start}, solver_time: {solver_time}, solver share: {solver_time/(end-start)}')
```
With thread limit:
![image](https://user-images.githubusercontent.com/44360364/114554428-01299900-9c67-11eb-9114-8276dafd1846.png)

Without thread limit:
![image](https://user-images.githubusercontent.com/44360364/114554601-33d39180-9c67-11eb-9021-88f565d03a7d.png)

You mentioned that the performance did not scale linearly with CPU cores, which is a common observation for most applications.

**Comment by xyyjcyd** [comment]
@phschiele I am agree with you, as the performance did not scale linearly with CPU cores. I suppose that, when solving a problem, if we constraint the number of thread, it will only constraint the  number of threads when calling optimizer such as mosek and cplex but cannot constraint the number of processes established by CVXPY. 
For example, when solving a much larger dimension problem, the CPU running as following:
![Screenshot from 2021-04-14 09-57-40](https://user-images.githubusercontent.com/46839369/114643671-b8c2b780-9d08-11eb-973a-eb922b2f6303.png)
There is one CPU  be occupied 100% but at the end, there are still some other processes which need other CPUs. 
Here is my code related to CVXPY:
`haha
haha 
xixi `

**Comment by xyyjcyd** [comment]
@phschiele I am agree with you, as the performance did not scale linearly with CPU cores. I suppose that, when solving a problem, if we constraint the number of thread, it will only constraint the number of threads when calling optimizer such as mosek and cplex but cannot constraint the number of processes established by CVXPY.
For example, when solving a much larger dimension problem, the CPU running as following:
![Screenshot from 2021-04-14 09-57-40](https://user-images.githubusercontent.com/46839369/114646106-3983b280-9d0d-11eb-88c8-e2df62038991.png)
Here is my code related to CVXPY:
```
# define the variables
U = cp.Variable(D* K)
E = cp.Variable(cons_C.shape[1])

# objective function
objective = cp.Minimize( cp.quad_form(U, Q ) + p.T @ U + rho @ cp.inv_pos(E)  )

# get constraint
constraints = [  Gamma @ U**2 <=  Umax**2]

constraints += [  Gamma @ ( Xi @ ( VA @ X_t +   VB @ U))**2 <=  Vmax**2 ]

constraints += [cons_b + cons_C @ E <= cons_A @  Phi @ ( VA @ X_t+ VB @ U)] 
constraints += [ E >= 0 ]
constraints += [ epsilon >= E ]

constraints += [  Xi_K @ ( VA @ X_t+ VB @ U) == np.zeros( D) ]

# formulate the problem
prob = cp.Problem(objective, constraints)


params={ 'MSK_IPAR_NUM_THREADS': 1 , 'MSK_IPAR_INTPNT_MULTI_THREAD':False }
start =datetime.datetime.now()
prob.solve( solver=cp.MOSEK, mosek_params=params,verbose=True )
end = datetime.datetime.now()
print(" running time is %s"%(end-start))
```

**Comment by SteveDiamond** [comment]
@akshayka is this related to the multi-core compiling possibly?

**Comment by akshayka** [comment]
> @akshayka is this related to the multi-core compiling possibly?

No, I don't think so. It's disabled by default, you have to compile from source and pass flags for OpenMP to the compiler and linker. So unless they are building from source & manually passing these flags, cvxcore will use just one thread.

**Comment by xyyjcyd** [comment]
> > @akshayka is this related to the multi-core compiling possibly?
> 
> No, I don't think so. It's disabled by default, you have to compile from source and pass flags for OpenMP to the compiler and linker. So unless they are building from source & manually passing these flags, cvxcore will use just one thread.
> 
> EDIT: if you want to be extra careful, you can use cvxpy.set_num_threads(1) to force cvxcore to use 1 thread. But this won't have an effect unless the user already opted in to multi threaded compilation.

I have done this: `cvxpy.set_num_threads(1)`. It doesn't make sense. 
And I have tested this on another computer: Intel core I9 4.6GHz. It has the similar phenomenon.
![print screen](https://user-images.githubusercontent.com/46839369/114801616-a14e0200-9dce-11eb-9dee-997350bc6672.png)
It is clearly that it occupied all the CPUs no matter the number of cores. Besides, I ran the solver many times in each interval wait for 10 seconds and here is the result:
 
![Screenshot from 2021-04-15 11-03-02](https://user-images.githubusercontent.com/46839369/114808729-6900f080-9ddb-11eb-9d0f-618cdf11f8cc.png)

**Comment by akshayka** [comment]
> I have done this: cvxpy.set_num_threads(1). It doesn't make sense.

Yes, like I said, that setting won't make a difference.

Have you tried isolating whether CVXPY or the solver is using multiple threads? You can do this by calling problem.get_problem_data(), which does not invoke the solver but does compile the problem.

If it's CVXPY, it would most likely be due to numpy/eigen. We never explicitly launch multiple processes/threads.

**Comment by xyyjcyd** [comment]
> If it's CVXPY, it would most likely be due to numpy/eigen.
I am agree with you. I find some guys mentioned that numpy will automatically running in multiprocessing and I have found this phenomenon in some programs beyond CVXPY. So that someone suggest that when running numpy they prefer multi-thread instead of multi-process. Refer to:  [Stackoverflow: Use threading instead of multiprocessing](https://stackoverflow.com/questions/38666078/fast-queue-of-read-only-numpy-arrays/38775513#38775513?newreg=7414b9ea2097488b94c7bf9930fdfe98). And maybe this is the reason.
