### ISSUE TITLE
Some result is completely wrong, even though optimality reported

### ISSUE THREAD

**Issue by siyuanpurdue** [cvxgrp/cvxpy#1335]
The problem is stated as follow:
```
def max_peak(power_signal,overall_ld):
    '''calculate peak if we use the power_signal profile  '''
    max_value = overall_ld[0] + power_signal[0]
    for i in range(1,time_slot):
        max_value= cp.maximum(max_value,\
                              overall_ld[i]+power_signal[i])
    return max_value
```
Basically, we return the peak of elementwise sum.
Here is the function call this part:
```
def peak_estimation(Z_t):
    '''
    Parameters
    ----------
    Z_t : numpy.array (variable length)
        The aggregate trace up to time t.
    Returns
    -------
    peak estimation of Z_t.
    '''
    t = Z_t.size # current time t
    remain_trace = cp.Variable(time_slot-t) # [Z_{t+1}, Z_T]
    power_signal = cp.Variable(time_slot)

    tmp = cp.Variable() # temporary variable
    
    prob = cp.Problem(cp.Minimize(tmp), constraints = [tmp>=max_peak(power_signal,\
           np.array(Z_t.tolist() + list(remain_trace))), \
           #power singal/battery constraints 
           gen_LB(agg)<= gen_A()@power_signal,\
           gen_A()@power_signal<=gen_UB(agg),\
           # prediction set constraints, i.e., lower/upper limit of prediction 
           lower_agg_prediction()[t:]<=remain_trace, \
           remain_trace<= upper_agg_prediction()[t:]]) 
        
    prob.solve(solver=cp.SCS, max_iters = 100000, eps=1e-8)

    return prob.value
```
Basically, the power_signal use the minimum allowed. The remain trace should always hit $lower_agg_prediction()[t:]$.

Reality is input of Z_t indeed get the exact optimal solution, while others have a substantial improvement space.
```
Zt=[ 84  84 101 101  84]
cumulative =  -40.0016137364416
power_singal =[ -0.3168788   -0.31684458 -17.31377696 -17.30950422  -0.30412928
  -0.2984144   -0.29059612  -0.2819718   -0.27275451  -0.26317459
  -0.25347457  -0.24390386  -0.23471344  -0.22615053  -0.21845351
  -0.21184718  -0.20653845  -0.20271263  -0.20053045  -0.20012583
  -0.20160456  -0.20504393  -0.21049338  -0.21797617]
 trace = [ 84.          84.         101.         101.          84.
  84.00018692  84.00000402  83.99979994  83.99957923  83.99934671
  83.99910742  83.99886645  83.99862883  83.99839941  83.99818268
  83.9979827   83.99780296  83.99764628  83.9975147   83.99740941
  83.99733066  83.99727773  83.99724891  83.99724139]
83.76777093543816
Zt=[101 101 101]
cumulative =  -39.592890096171935
power_singal =[-13.33399182 -13.33540032 -13.33704864   1.74861555   2.14752478
   3.03856096   2.45688448   2.02921268   2.54329345   0.64653744
   0.0631043   -2.47891124  -2.11587074   0.31417689   0.70740759
  -1.47373456  -4.34441679  -2.76958702  -1.69536949  -0.32654787
  -0.23999674   0.01766599   0.21377891  -0.06877791]
 trace = [101.         101.         101.          85.24978892  84.90422409
  84.23112206  84.54481147  84.90160855  84.36161117  84.93695698
  85.06165629  86.37050846  86.24397556  85.51490917  85.13856578
  86.03198182  87.41980173  86.84072578  85.85570531  85.36429766
  85.42021095  85.11234396  85.14970796  84.76394854]
87.65946928536609
 ```
The first input is correct for the element after 5th is all around 84 (i.e.lower_agg_prediction), while the second is suboptimal because by making the remain trace smaller, the objective could be minimized more.

I don't think that's anything to do with eps, max_iter because they are tuned.

**Comment by rileyjmurray** [comment]
Hi @siyuanpurdue. Unfortunately, we can't help you unless you provide a minimal example. One specific problem here is that ``gen_LB``, ``gen_UB``, and ``gen_A`` are all undefined.

Please post this question to StackOverflow with a CVXPY  tag (or the CVXPY Google Group) with that minimal information. We encourage you to come back and report an issue here if you believe that you have isolated a bug.

**Comment by siyuanpurdue** [comment]
Result of genA:
```
[[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [1 1 1 ... 1 0 0]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 1]]
```
Result of genLB
```
[-80. -80. -80. -80. -80. -80. -80. -80. -80. -80. -80. -80. -80. -80.
 -80. -80. -80. -80. -80. -80. -80. -80. -80. -80. -40. -40. -40. -40.
 -40. -40. -40. -40. -40. -40. -40. -40. -40. -40. -40. -40. -40. -40.
 -40. -40. -40. -40. -40. -40.]
```
Result of genUB
```
[80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80. 80.
 80. 80. 80. 80. 80. 80. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40.
 40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40. 40.]
```
Plz help! Thanks!

**Comment by SteveDiamond** [comment]
What do you mean by "completely wrong"? Do you have proof? Did you solve the problem with different solvers and get different results? Did the objective value differ across solvers or only the optimal value of the variables?

**Comment by siyuanpurdue** [comment]
I have tried SCS, and CVXOPT. It seems like SCS is more accurate in solving my problem. As I said in the first post, for input Zt = [ 84  84 101 101  84], it gives "accurate" answer, i.e., the trace is 84 since 5th element. But for Zt=[101 101 101], it outputs a wrong answer. At least it's kind of far from optimal. The optimal is clearly: [101.         101.         101.          84........84], but the result given by solver is 85.24978892  84.90422409 ... 84.76394854. Which is far away from optimal. It is obviously, it should use exact bound of lower_agg_prediction

**Comment by SteveDiamond** [comment]
Have you tried MOSEK?

**Comment by siyuanpurdue** [comment]
> Have you tried MOSEK?

Yes, if you mean by simply adding "solver = MOSEK". But it seems like they have their own way of syntax, and defining problem. But I suppose it has the same effect, by adding that option in the cvxpy?

**Comment by siyuanpurdue** [comment]
Is simply setting mosek.dparam.basis_tol_x: 1e-8 enough?
