### ISSUE TITLE
Important speed issue (in comparison with former cvxpy and picos)

### ISSUE THREAD

**Issue by callegar** [cvxgrp/cvxpy#154]
Hi,

I have a project that is based to the older cvxpy by Tomas Tinoco de Rubira. Since that project is now superseded by the current cvxpy, I am now trying to migrate my project to the newer cvxpy.

Everything seems to work, but the speed difference is huge. I have a test case that used to take approximately 1 sec with the former cvxpy and now takes approximately 30 sec.

Maybe the way in which I have reformulated the problem causes some overhead.

My problem uses cvxopt as its solver and includes a quadratic merit factor and semidefiniteness constraints as follows.

b - Vector of variables
X - symmetric matrix of variables

objective: minimize bQb.T where Q is a positive definite matrix

constraints

- X positive definite

- M big matrix built taking pieces that are all linear in X and b negative definite.

So far, I have ported the previous code with minimal changes. The only things that need to be different are the way in which the symmetry of X is expressed (in the former cvxpy this was done without adding a constraint, but by defining a variable with a 'structure'), and the way in which the negative definiteness of M is expressed (in the former cvxpy I had a statement, now it looks like I have to define a new matrix of variables with Semidef and impose the constraint that it is equal to M).

Any idea?

**Comment by callegar** [comment]
I have now tested also with picos.

Picos appears to be faster than the former cvxpy.

With the Examples/TCAS1-2013/demo_bp.py test case, all the modeling frameworks using cvxopt as the solver and the same cvxopt parameters, I get

Picos: 17 sec
Old cvxpy: 69 sec
New cvxpy: 281 sec

**Comment by SteveDiamond** [comment]
I changed the internals of Semidef. Now the new cvxpy takes 37 seconds on Examples/TCAS1-2013/demo_bp.py. Hopefully this is fast enough for you to use cvxpy over picos :)

**Comment by callegar** [comment]
Just tested: it is very much improved!

Now, on my machine I get
Picos: 17 sec
Old cvxpy: 69 sec
New cvxpy: 50 sec

So, it is definitely better than the old cvxpy!  Now, I'll look at the quality of the solutions for some cases that were critical with the older cvxpy.

Incidentally, as long as there are no critical cases, I really would like to use cvxpy since the help and assistance I am getting here is really great!  Thanks!

**Comment by callegar** [comment]
Unfortunately, just as in your forecast, I am now running into problems with redundant constraints generated by problem formulation when using the 'chol' solver.

Specifically, I now have a variant of the problem that I have illustrated so far, where selecting the 'chol' sover causes CVXOPT to abort, while the default solver is fine.

Possibly, the cause of the problem lays in the fact that I have a constraint implying that a complex Hermitian matrix is negative definite.

Following "Convex Optimization", I am recasting this problem into

```
[  Re M        Im M ]
[                   ]                     < 0
[  -Im M       Re M ]
```

Do you have any suggestion on how to deal with this?

The issue is that:

- With the default kkt solver, cvxpy can deal with all the problems that I need to consider, but when the problems grow large, the solving time rapidly increases so much that the problems at hand cannot be practically tackled (even with the recent change in the internals of Semidef).
- With the "chol" kkt solver, cvxpy is generally fast enough for practical use with the problem sizes that I need to consider, but not for this latter specific problem.
- The older cvxpy and picos can deal with this specific problem in acceptable time at the required sizes.
- I would like to support "cvxpy" that seems very actively maintained rather than having to rely on the older cvxpy for a specific case.

Any chance you can help me in removing constraint redundancy in my problem or (even better) making cvxpy at least as fast as the older cvxpy without limitations in how constraints are formulated?

**Comment by SteveDiamond** [comment]
Did you try using the "lower_tri" function in the negative semi definite
constraint, like I did in the code I wrote for you?

I suspect that picos and the old CVXPY are preprocessing the matrix to
remove rows that are obviously redundant. I'll add something like this when
I have time.

**Comment by SteveDiamond** [comment]
Did using "lower_tri" (actually I think it was upper_tri) fix the problem? If not please let me know and I'll add the preprocessing I talked about.

**Comment by sergiocallegari** [comment]
Hi!

Sorry for answering so late, but I restarted working on my project `pydsm` with `cvxpy` only recently.
For a few months I had to stay with the former `cvxpy` codebase, because I need my project to be multiplatform and the dependencies of `cvxpy` (`scs` in fact) appear to be causing issues with my users who are on Windows.  Now I am trying again to check the viability of the newer `cvxpy`.

And yes, I tried to use "lower/upper_tri" and it does the trick. However, with it, the speed is still significantly worse than that of the former `cvxpy` and of `picos` unless I also use the `chol` kkt solver.  Unfortunately, there are cases, in which I do not know how to use it (merely trying it causes errors, probably due to redundant constraints).

So, having the preprocessing would definitely help.

**Comment by SteveDiamond** [comment]
Can you install scs on windows now?

I committed a simple preprocessing step to remove redundant rows before
cvxopt runs with the 'chol' kktsolver. Could you try installing cvxpy from
source and checking if your code works now?

**Comment by SteveDiamond** [comment]
I made a much fancier preprocessor that's near the limit of what's possible in terms of eliminating redundant constraints. Now the chol kktsolver almost always works and is a lot faster than the current kktsolver, so I've made it the default.

Unfortunately it fails on test_NTFdesign_minmax.py. I'm not sure why it fails, but I have some ideas for creating fewer variables that should make this particular problem work. I'll let you know once that's implemented.

**Comment by SteveDiamond** [comment]
I made a pull request to PyDSM that gets cvxpy working with the cvxopt solver. It uses new features I added to cvxpy, namely symmetric variables and positive definite constraints like in PICOS (e.g., X >> 0).

I need to document all these features and do a bit more debugging, but it looks like the main issues are solved.
