### ISSUE TITLE
importing cvxpy changes the return value of non-cvxpy functions (patch available)

### ISSUE THREAD

**Issue by callegar** [cvxgrp/cvxpy#160]
I have a weird issue. Consider the following code snippet

```
import scipy.signal as sig
import numpy as np
# import cvxpy

# Signal specification
fsig = 1000.
B = 400.
OSR = 64
fphi = B*OSR*2
w0 = 2*fsig/fphi
B0 = 2*B/fphi
w1 = (np.sqrt(B0**2+4*w0**2)-B0)/2
w2 = (np.sqrt(B0**2+4*w0**2)+B0)/2
hz = sig.butter(4, [w1, w2], 'bandpass', output='zpk')
hz_ab = sig.zpk2tf(*hz)

print type(hz_ab[0][1])
```

It returns ``<type 'numpy.float64'>``.

However, if I uncomment the ``import cvxpy`` it returns ``<type 'numpy.cplx128'>``.  Now, why should the import of ``cvxpy`` have this weird side effect?

**Comment by callegar** [comment]
I think that I am close to the issue.

The problem is that cvxpy overloads the numpy == function in such a way that two empty numpy arrays [] and [] appear not to be equal.

This causes some non-cvxpy functions to break

**Comment by callegar** [comment]
Consider the simpler example

```
import numpy as np
# import cvxpy

a = np.asarray([])
b = np.asarray([])

print a == b
```

This returns ``[]`` without ``cvxpy`` and ``False`` with it. Consequently, ``np.all(a==b)`` returns ``True`` without ``cvxpy`` and ``False`` with ``cvxpy``.

**Comment by callegar** [comment]
I propose patching ``override(name)`` in ``interface/numpy_wrapper.py`` as follows

```
    if name == "equal":
        def ufunc(x, y):
            if isinstance(y, np.ndarray) and y.ndim > 0 and y.size > 0 \
               and y[0] is s.NP_EQUAL_STR:
                    raise Exception("Prevent Numpy equal ufunc.")
            return getattr(np, name)(x, y)
        return ufunc
    else:
        def ufunc(x, y):
            if isinstance(y, exp.Expression):
                return NotImplemented
            return getattr(np, name)(x, y)
        return ufunc
```

namey, I think that one should check that the size of ``y`` is not zero before reading ``y[0]``.

**Comment by SteveDiamond** [comment]
I played around with ``interface/numpy_wrapper.py``, and it turns out operator overloading with numpy now works without any overriding! The issue before was that the ufuncs for <=, ==, and >= didn't respect the special operator overloading flag you can set. I deleted ``interface/numpy_wrapper.py``, so there should no longer be any issues.

**Comment by echu** [comment]
Woohoo!

**Comment by callegar** [comment]
Good news to hear that a better fix than my patch is available!
Just a little clarification: was the overloading a workaround for an issue with numpy, then? If so, which version of numpy had the issue?

**Comment by SteveDiamond** [comment]
Yes, it was a workaround for a numpy issue. I'm not sure what version, but
probably 1.7. The workaround is unnecessary with 1.8 and higher.
