### ISSUE TITLE
some cvxpy tests need a newer (unreleased?) version of ecos

### ISSUE THREAD

**Issue by argriffing** [cvxgrp/cvxpy#161]
https://travis-ci.org/cvxgrp/cvxpy/builds/43582068

If cvxpy were using the `numpy.testing` framework I'd suggest adding
`@numpy.testing.decorators.knownfailureif(<old cvxpy version>)`
at the top of these tests.

**Comment by argriffing** [comment]
Nevermind, I see that cvxpy now requires a version of ecos that was released two days ago, and indicates this requirement in its setup.py.

**Comment by echu** [comment]
:-)
