### ISSUE TITLE
TravisCI seems to not actually test Python3.

### ISSUE THREAD

**Issue by argriffing** [cvxgrp/cvxpy#163]
This can be seen by inspecting the TravisCI reports for recent PRs.  For example https://travis-ci.org/cvxgrp/cvxpy/builds/45109491 has two travis configurations, one of which appears to request Python3.4 but actually gets Python2.7.3.

**Comment by SteveDiamond** [comment]
It is testing python 3. What happens is that the travis script installs miniconda, which automatically comes with python 2.7 and prints that line. Then the script creates and loads a Python 3 conda environment. Right before it installs cvxpy the output of ``python --version`` is ``Python 3.4.2 :: Continuum Analytics, Inc.`` See this line:

https://travis-ci.org/cvxgrp/cvxpy/jobs/46002057#L391

**Comment by argriffing** [comment]
OK!
