### ISSUE TITLE
Feature request: sdpt3 and/or sedumi interface

### ISSUE THREAD

**Issue by ncroc** [cvxgrp/cvxpy#165]
Most of the problems I need to solve are log det SDPs with some additional convex terms. Due to the limitations of cvxopt, I had to move to cvx and matlab inorder to be able to use sdpt3 and/or sedumi. However cvxpy has very nice features which as far as I know cvx do not. For instance, It is possible to extend optimization models with cvxpy since the variable, constraint, etc declaration and the optimization problem creation can be separated. This allows me to form various versions of the main optimization problem which might have additonal variables, constraints, objective terms very easily. I cannot do this in cvx.

Are you planning on writing an interface for sdpt3 and/or sedumi ? Is it even possible or feasible ?

**Comment by SteveDiamond** [comment]
sdpt3 and sedumi are both in matlab, so I can't call them from python. I
can add a mosek interface to cvxpy. Would that work for you?

**Comment by ncroc** [comment]
I will reinstall cvx with academic license, test the codes with Mosek and tell you the results. Thanks.

**Comment by ianozsvald** [comment]
Hello. A colleague has noted that using Matlab+SDPT3 he gets good results but using Python and a default solver (since SDPT3 isn't available) he gets poor results. I'm wondering - is it likely that SDPT3 makes it over to Python?
Am I right thinking that SDPT3 has a GPL license but is written in Matlab (https://github.com/sqlp/sdpt3), such that it wouldn't be easy to port?
Cheers, Ian.

**Comment by SteveDiamond** [comment]
I'm not sure how hard it would be to port. Looking through the code now, it seems like a port would be possible.

Was your colleague solving an SDP? I usually suggest using MOSEK for SDPs. It's really unfortunate that the better open source SDP solvers like SDTP3 are in MATLAB.

**Comment by discardthree** [comment]
Hello all,

To chime in, I use CVXPY to construct/manage/analyze my problems but I often need to do my 'good' tests with SDPT3 because CVXOPT often isn't robust enough or fast enough.  To connect the two, I have written some Python code that gets the CVXPY problem data and writes the appropriate problem to a .mat format, then triggers Matlab to load in that problem and solve it with SDPT3.  Then I read the result back into Python so I can do all my usual Python things to it (storing it, analysis, making graphs).  The code that does this is part of a bigger package that I can't make public just yet, but if there's interest I could isolate the bits relevant to this and make them available.

Note that this only helps if you have Matlab and SDPT3 installed, though if you could get SDPT3 working with Octave you should be able to get my method to work by just changing a word or two.

**Comment by SteveDiamond** [comment]
If you could make the glue code available, that would be really helpful! I think SDPT3 works in Octave.

**Comment by sschnug** [comment]
Maybe the [SDPA](http://sdpa.sourceforge.net/)-solver could be an alternative too.
[Picos](http://picos.zib.de/) now supports it (by calling the executable).

**Comment by ianozsvald** [comment]
Hi @SteveDiamond, thanks for the reply. My colleague is now testing MOSEK and GUROBI (as the 2 that can be run in both Matlab and Python) on his problem, we spent the day fighting a few MacOS install problems but the solvers are in place now. Hopefully he'll come back here on Monday and post an update. Cheers! Ian.

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12930704/c1a1c298-cf71-11e5-8cf2-b733873f776d.png)

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12930738/fef5f8b2-cf71-11e5-97c0-649aaec7fde2.png)

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12930759/18e67922-cf72-11e5-9cc1-3efa8050cef6.png)

**Comment by SteveDiamond** [comment]
Could you run the solvers with ``verbose=True`` and post the output? As in
``
prob.solve(solver=XXX, verbose=True)
```
The cvxopt error looks like a bad installation. The ecos and mosek errors are probably from numerical issues, but it's hard to tell without seeing the verbose output.

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12947056/bab95fca-cff0-11e5-8142-cdf6b228df4e.png)

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12947068/d9d9e320-cff0-11e5-99aa-6fcc4dcf0a00.png)

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12947089/0492a53e-cff1-11e5-9286-8a096d1c021f.png)

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12947110/1aa735f6-cff1-11e5-871d-c1632ffa776e.png)

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12947146/5fd6846a-cff1-11e5-8d9f-8667bfc0addf.png)

**Comment by ajm0250** [comment]
![image](https://cloud.githubusercontent.com/assets/5636813/12947180/7b66a61a-cff1-11e5-9936-ef109645103c.png)

**Comment by SteveDiamond** [comment]
From the MOSEK output, it looks like the numbers in your problem are very large. This will cause problems for all the solvers, as you observed. Try rescaling your problem so the numbers are more reasonable. For example, you could normalize your feature matrices.

Were you using exactly the same data for cvx and cvxpy? It's possible cvx does some rescaling before it gives the problem to the solver, which would address the issue of large numerical values. cvxpy doesn't do this.

**Comment by ajm0250** [comment]
Yes, the same data was used on cvx and cvxpy. I will try to normalise the data.
Thank you very much for the help.

**Comment by natschil** [comment]
@discardthree :  Could you share your CVXPY -> matlab code?

**Comment by discardthree** [comment]
@natschil Sorry it's taken so long, I've been working on this in my spare time.  It's almost ready, I just need to do a little more testing and then I'll post here with a link.

**Comment by discardthree** [comment]
Okay guys, here's where I'm at: https://github.com/discardthree/py-sdpt3-glue.  See the readme there for a description of what it should do.  **_Be warned it does not work for ANY problems right now!_**, but I'm posting here now in case anyone wants to take a crack at helping me fix it. Issue https://github.com/discardthree/py-sdpt3-glue/issues/4 is what's preventing it from working, if we get past that it should be a short road to a working product.  I've had exactly this functionality working in a previous project, so I know it's possible.

**Comment by discardthree** [comment]
PS. In addition to Matlab and (untested beta) Octave support, it has an interface to use SDPT3 the NEOS server, so you can try it out even if you don't have Matlab or Octave installed (but you'll need the python package selenium).  I'll add some example code to try out on the readme.

**Comment by discardthree** [comment]
Update: pysdpt3glue is now pip installable under the name sdpt3glue!

Github: https://github.com/discardthree/pysdpt3glue
PyPI: https://pypi.python.org/pypi/sdpt3glue/ 
Docs: http://pythonhosted.org/sdpt3glue/

We support four ways of getting access to SDPT3:

1. An installed copy of Matlab
2. An installed copy of Octave
3. Using Docker (which gets and uses [this image of Octave + SDPT3](https://hub.docker.com/r/jkawamoto/octave-sdpt3/), prepared by @jkawamoto)
4. By submitting your problem to the NEOS server
See the readme [here](https://github.com/discardthree/pysdpt3glue) for examples of running all the above.

We're at version 0.9.0, meaning we're pretty comfortable with how it's working but you should make an issue if something doesn't work as expected.
