### ISSUE TITLE
Feature request: Gurobi interface

### ISSUE THREAD

**Issue by macklin** [cvxgrp/cvxpy#168]
Would it be possible to add a Gurobi interface?  The problems that I work with (variations on flux balance analysis) can't be solved by most convex solvers due to (what I think are) numerical issues--the numerical values in real-life problems span 7-8 orders of magnitude and I always get "optimal inaccurate" solutions.  If I use Gurobi, though, I do get optimal solutions.  I would, however, like to be able to call Gurobi using cvxpy's interface if possible.  How feasible would it be to implement this?

**Comment by SteveDiamond** [comment]
Is your problem an LP or a QP? cvxpy can't target QP solvers right now. It converts QPs to SOCPs.

Adding Gurobi as an LP solver would not be very hard. Adding closed source solvers creates a few complications though. One is testing. cvxpy heavily uses continuous integration with Travis CI. You can't test closed source solvers on Travis though. Does anyone have suggestions for testing closed source solvers?

If you have time, it would be great if you could add Gurobi to cvxpy yourself. All you need to do is create a "gurobi_intf.py" file in the style of 

https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/solvers/ecos_intf.py

Even if you just make an attempt it would be helpful, and I can finish it up. Basically you just need code to take an LP or MILP stored as

min c^Tx
subject to Ax = b
                 Gx <= h

and export it to Gurobi.

**Comment by macklin** [comment]
Right now my problem is an LP (minimizing an L1 norm subject to constraints).  All of the solvers that cvxpy currently targets failed to give an optimal accurate solution.

I'll start with a GLPK interface (through CVXOPT) since that should be a fairly easy modification from the current CVXOPT interface.  Then I'll try a Gurobi interface.

It'd be nice to be able to target a QP solver at some point--I will eventually play with using an L2 rather than L1 norm, and it's be great to do that within cvxpy if possible.  How hard would this be to incorporate?  Significantly more difficult than just another interface?

**Comment by SteveDiamond** [comment]
The problem is that you can't convert an arbitrary SOCP into a QP or QCQP.
cvxpy would need to recognize problems that are QPs or QCQPs but not SOCPs.
This wouldn't be super hard, but I would prefer to avoid the complexity and
just add a mixed integer SOCP solver like MOSEK. Such a solver could handle
all mixed integer QPs or QCQPs.

**Comment by SteveDiamond** [comment]
Ignore my previous answer. For some reason I thought you wanted to solve mixed-integer programs. Even so, I expect the MOSEK SOCP solver would be robust enough to handle any QPs you want to solve.
