### ISSUE TITLE
Problem while solving two constants for Kernel orthogonal Matching pursuit

### ISSUE THREAD

**Issue by gunju** [cvxgrp/cvxpy#169]
Hi,
I am writing code for Kernel Matching pursuit.For that, I have to solve optimization problem in which unknown(or Variable) has to multipled with a matrix and again with transpose with unknown.
This is can be interprted as follows:
X*K_tr*x'

But,it is giving error as:cannot multiply  two constatnts.

Please help me to solve this problem.

**Comment by SteveDiamond** [comment]
What are the dimensions of all the terms in ``XK_trx'``? If the whole thing evaluates to a scalar you could use quad_form.
