### ISSUE TITLE
sum(x) for x = cvxpy.Variable(1)

### ISSUE THREAD

**Issue by ajfriend** [cvxgrp/cvxpy#175]
I know this is a weird edge case, but

```
x = cvxpy.Variable(2)
sum(x)
```
forms the correct expression, summing the elements of `x`, while if I write

```
x = cvxpy.Variable(1)
sum(x)
```
my interpreter hangs indefinitely.

**Comment by SteveDiamond** [comment]
You're supposed to use the CVXPY function sum_entries to sum all the entries in a CVXPY expression.
You should only use the built-in sum to add together a list of CVXPY expressions.

Anyway, I fixed this issue.

**Comment by ajfriend** [comment]
Just because I'd like to better understand: what's wrong with using `sum`?

**Comment by SteveDiamond** [comment]
``sum_entries`` is basically a vectorized version of ``sum``. It's much more efficient to parse ``sum_entries(x)`` than to parse

```
total = 0
for i in range(n):
   total += x[i]
``

which is what ``sum`` is doing. When ``x`` is a large matrix the difference in parse time is orders of magnitude. I thought I had made it so ``sum`` wouldn't work on cvxpy expressions, but evidently not.
