### ISSUE TITLE
Mac OSX install docs confusion

### ISSUE THREAD

**Issue by scottsievert** [cvxgrp/cvxpy#181]
The [MacOSX install docs] say that a special conda env needs to be created with `python=2`. However, it seems that cvxpy supports Python 3 ([mailing list announcement]) and my test passed (see below).

Why are these docs indicate python=2? It appears that it's only necessary to run `pip install cvxpy` regardless of Python 2 or Python 3.

```shell
> conda create -n cvxpy_env python=3 scipy numpy pip nose
Fetching package metadata: ....
Solving package specifications: .............
Package plan for installation in environment /Users/scott/anaconda/envs/cvxpy_env:

The following packages will be downloaded:
   ...
> source activate cvxpy_env
> pip install cvxpy
> nosetests cvxpy
Ran 1397 tests in 19.418s

OK
```

[MacOSX install docs]:http://www.cvxpy.org/en/latest/install/index.html#mac-os-x
[mailing list announcement]:https://groups.google.com/forum/#!searchin/cvxpy/python$203/cvxpy/Yi95Id11YfE/V1EErxvjWjMJ

**Comment by SteveDiamond** [comment]
Good catch. I've updated the OS X and Ubuntu install docs to make it clear you can use python 3.

**Comment by scottsievert** [comment]
Got, I saw the update. My question clarified: why is creating a virtualenv necessary?

**Comment by SteveDiamond** [comment]
It used to be really hard to install scipy on a mac. It's much easier now, so the Anaconda install isn't necessary. I changed the instructions so they just use pip.

**Comment by scottsievert** [comment]
+1
