### ISSUE TITLE
eqn rendering at http://nbviewer.ipython.org/github/cvxgrp/cvxpy/blob/master/examples/notebooks/WWW/sparse_covariance_est.ipynb

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#187]
Another problem:

A good heuristic for estimating R is to solve the problem \begin{array}{ll} \mbox{minimize} & \log \det(S) - \mbox{tr}(SY) \ \mbox{subject to} & \sum{i=1}^n \sum{j=1}^n |S_{ij}| \le \alpha \ & S \succeq 0, \end{array}

**Comment by SteveDiamond** [comment]
Fixed.
