### ISSUE TITLE
Incompatibilities with scs 1.1.0?

### ISSUE THREAD

**Issue by sergiocallegari** [cvxgrp/cvxpy#188]
Hi,

I have a problem that cvxpy used to solve just fine using the scs solver and scs 1.0.7.
With scs 1.1.0 there is a failure.

I do not know if this is significant, because scs 1.1.0 is not on pypi. Hence users relying on pip to install will get 1.0.7 anyway.

However, it can be an issue for users on Windows who try to use scs from Christoph Gohlke's repository, because only 1.1.0 is there.

**Comment by bodono** [comment]
The problem is that cvxpy has not been updated to use the latest SDP input format, v1.0.7 is the latest version with the old input format.

**Comment by SteveDiamond** [comment]
I had forgotten that this was an issue. I've updated cvxpy so that it requires scs 1.0.7. I'll work on making cvxpy scs 1.1.0 compatible. In the meantime you can update scs on pip. It would be really great if you could make a wheel for windows as well.
