### ISSUE TITLE
Minimize cvxpy dependencies

### ISSUE THREAD

**Issue by sergiocallegari** [cvxgrp/cvxpy#189]
Hi,

currently cvxpy depends on three different low level solvers (cvxopt, scs, ecos), so that installation fails if the installation of either of these solvers fails.

I suggest reducing the dependency to only one or none of these solvers hand having errors be thrown at runtime if one selects a solver that is not installed.

This should make deployment much easier on platforms where installation of some of the low level solvers fail.

For instance `pip install scs` fails on windows with current winpython.

**Comment by SteveDiamond** [comment]
cvxpy works without scs or ecos (and maybe without cvxopt). You can just
remove them from the setup.py dependencies and reinstall.

If I take them out of setup.py, it will make installation more complicated
for people on standard platforms.

If you use python(x,y), cvxpy comes preinstalled with scs and all the other
dependencies.

**Comment by sergiocallegari** [comment]
Yes, I have tried and cvxpy works without ecos or scs. This was the reason of my suggestion.

As a matter of fact, only python(x,y) currently provides a nice experience with cvxpy on windows.

With all other Python distributions (winpython, anaconda, etc), that do not come with scs, the situation is rather bad.

1) people do `pip install <some package>` where `<some package>`
2) pip sees that `<some package>` depends on `cvxpy` and tries to pull it in
3) pip sees that `cvxpy` depends on `cvxopt`, `ecos` and `scs`.  Most python distributions provide cvxopt, so that is typically not a problem.
4) pip downloads `scs` from Pypi and tries to compile it. Compilation fails unless one has some development version of `blas` and `lapack` installed
5) the user tries to find a pre-compiled version of `scs` for windows. One is found in Gohlke's repository.
6) the user downloads Gohlke's scs python wheel. Unfortunately, this is at version 1.1.0 of scs
7) the user retries `pip install cvxpy`. This now seems to work. However `cvxpy` experience with `scs` is anyway broken, because `scs` is too new.
8) people complain loudly at the authors of `<some package>`.

This is problematic because there are now may people who like to use 'portable' Python distributions like `winpython`.

**Comment by SteveDiamond** [comment]
Doesn't pip download a wheel first, if one exists? 

I'm in the process of updating cvxpy to handle scs 1.1. I hadn't realized they weren't compatible. Once that's done (and if I'm right about wheels), @bodono could make a windows scs wheel. Then everything should work out, right?

**Comment by sergiocallegari** [comment]
Yes, pip gets the wheel first if it is available. Unfortunately, there is no scs wheel currently. I have just asked @bodono to make one if possible and I hope he will be able to help.

**Comment by bodono** [comment]
I'll investigate making a wheel this weekend.

**Comment by SteveDiamond** [comment]
cvxpy now supports the latest SCS (1.1.3).
