### ISSUE TITLE
Extracting certain elements of a Variable

### ISSUE THREAD

**Issue by quantdaddy** [cvxgrp/cvxpy#193]
temp = Variable(5,5)
I'm interested in extracting certain elements of the expression matrix. 
temp[[1,3],[2,4]] gives an error
IndexError: Index/slice out of bounds.

**Comment by SteveDiamond** [comment]
It should be ``temp.value[1:3, 2:4]`` or ``temp[1:3, 2:4].value``.

See http://www.cvxpy.org/en/latest/tutorial/intro/index.html

**Comment by quantdaddy** [comment]
Thanks for your reply. I want to extract certain elements of the matrix. For example, I wanted to extract (1,2) and (3,4) elements of the matrix i.e. the (1st row, 2nd column) element and (3rd row, 4th column) element. If I had a np.array matrix, I can extract it using temp[[1,3],[2,4]], but it doesn't work for cvx Variable matrix.

**Comment by SteveDiamond** [comment]
Oh, ok. You can't do that directly. If you want a vector of these elements, you can do this:
```
vstack(*[temp[i,j] for i,j in [(1,3), (2,4)]])
```

**Comment by quantdaddy** [comment]
That works! But here is another problem I'm facing. I have a large matrix of expression, XX
>>> XX
Expression(AFFINE, UNKNOWN, (200000, 200000))
>>> I
(array([     0,      0,      0, ..., 199999, 199999, 199999], dtype=int32), array([199527, 191456, 191318, ...,   6428,   4967,   4646], dtype=int32))
>>> I[0].shape
(75830978,)
>>> I[1].shape
(75830978,)
>>> temp = vstack(*[XX[i,j] for i,j in [I[0], I[1]]])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack

Is there a way to make it work for a large matrix? Am I getting the error because of memore problem?  Thanks a ton!

**Comment by quantdaddy** [comment]
In fact, it does not work while extracting about 200K indices. So, I guess it's not a memory problem.

**Comment by SteveDiamond** [comment]
The error ``ValueError: too many values to unpack`` means your ``[XX[i,j] for i,j in [I[0], I[1]]]`` is incorrect.  The ``for i,j in  [I[0], I[1]]`` expects that ``[I[0], I[1]]`` is a list of tuples. If it's not a list of tuples, then you'll get the error. It has nothing to do with the size of the array. Probably you should write ``for i,j in  zip(I[0], I[1])``.

But if you really have such a large expression ``expr`` and you want cvxpy to run as fast as possible you should instead make a sparse matrix ``A`` such that ``A*vec(expr)`` gives the values of ``expr`` you want. Make ``A`` using scipy sparse matrices, then wrap it like this ``Constant(A)`` so cvxpy can handle it.

**Comment by quantdaddy** [comment]
I get the same error with the code below. However, I don't get any error if I use very small length of I[0] (about 50) no matter I use tuple or array. Larger length of I[0] gives the same error. 

index1 = tuple(I[0])
index2 = tuple(I[1])
XX = vstack(*[XX[i,j] for i,j in [index1, index2]])

**Comment by SteveDiamond** [comment]
Your code is wrong. I meant tuples of two elements, because you unpack them into two elements in the for loop. This code should work:
```
temp = vstack(*[XX[i,j] for i,j in zip(I[0], I[1])])
``
But you should look at the array ``[(i,j) for i,j in zip(I[0], I[1])]`` and make sure it is giving you indices into the matrix.

**Comment by quantdaddy** [comment]
works. Thank you so much!!
