### ISSUE TITLE
Defining a block diagonal matrix in terms of the block matrix variables. 

### ISSUE THREAD

**Issue by quantdaddy** [cvxgrp/cvxpy#194]
I want to define a block diagonal covariance matrix in terms of the block matrix variables. I use kronecker product to do that, but it seems like it does not work for cvx variables. For example, in the code below, I was expecting covar to be a 10 by 10 matrix. The reason I want it to be 10 by 10 is that I want to multiply covar with a constant matrix A whose dimension is N  by 10. A.dot(covar) gives an error (dimension mismatch)
Any help is very much appreciated.  

>>> dmat1 = np.eye(5)
>>> dmat2 = np.eye(5)
>>> diagcov1 = Variable(2,2);
>>> diagcov2 = Variable(2,2);
>>> covar = np.kron(dmat1, diagcov1)+np.kron(dmat2, diagcov2)
>>> covar.shape
(5, 5)

**Comment by SteveDiamond** [comment]
You can't use numpy functions on cvxpy objects. You'll have to use the cvxpy functions hstack and vstack. I'll add a cvxpy kron function when I have time.

**Comment by quantdaddy** [comment]
Can I stack cvx variables and zeros together (since the covar matrix is a block diagonal)? I don't want to define covar as a new cvx variable, that will increase the dimension of the problem. I need to define covar matrix just to calculate the objective function easily.

**Comment by quantdaddy** [comment]
Looks like i can. never mind. thanks!
