### ISSUE TITLE
MemoryError: std::bad_alloc

### ISSUE THREAD

**Issue by quantdaddy** [cvxgrp/cvxpy#195]
Running the code below gives error: MemoryError: std::bad_alloc
XX expression matrix is a function of the Variables defined below and some fixed matrices. I've defined all the fixed matrices as Constant while calculating XX expression. Also, XX is eventually calculated as A*vec(Y) where Y is another expression. 
Is there a way to deal with such a big expression? I eventually want to run the algorithm for an expression of length about 100 million. It works in matlab when I use cvx. 

>>> S = Constant(S)
evar = Variable(1); ecovRp = Semidef(2,2); ecovLp = Semidef(2); ecovRb = Semidef(2); ecovLb = Semidef(2); 
constraint = [0 <= evar , ecovRp == ecovRp.T, ecovLp == ecovLp.T, ecovLb == ecovLb.T, ecovRb == ecovRb.T];
XX = pickle.load(pkl_file)
XX
Expression(AFFINE, UNKNOWN, (254034, 1))
obj = Minimize(norm(XX - S, 2))
prob = Problem(obj, constraint)
result = prob.solve(solver=SCS,verbose=True)

**Comment by SteveDiamond** [comment]
I don't think the memory error is related to the size. It's far more likely due to pickling and unpickling XX. Does it work if you define XX in the same script?

**Comment by quantdaddy** [comment]
I get the same error with XX defined in the same script.

**Comment by quantdaddy** [comment]
Calculating XX involves calculating a 5000 by 5000 sparse expression matrix and then extracting the nonzero elements of that. It doesn't take time to calculate XX though.

**Comment by SteveDiamond** [comment]
Well I've never seen this error before. Can you post the entire script so I can run it myself?

**Comment by quantdaddy** [comment]
​Attached!​

On Thu, Jun 11, 2015 at 2:19 PM, Steven Diamond <notifications@github.com>
wrote:

> Well I've never seen this error before. Can you post the entire script so
> I can run it myself?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cvxgrp/cvxpy/issues/195#issuecomment-111280013>.
>

from cvxpy import *
import numpy as np
import cvxpy as cvx
from scipy.sparse import lil_matrix
from scipy.sparse import csr_matrix
import scipy.sparse as sp
import cvxopt as cvxopt
import pickle
import time

# Running the code on artificialy generated data
FILENAME_DATA = 'data.p'
FILENAME_RESULT = 'result.pkl'
NUMITER = 1;
np.random.seed(1)


## load the data
data = pickle.load(open(FILENAME_DATA, "rb"))
X = data['X']; Y = data['Y']; Z = data['Z']; nolp = data['nolp'];  nolb = data['nolb']; norp = data['norp']; norb = data['norb'];
X = X[:,2:] 


N = X.shape[0]
nop = norp+nolp; nob = norb+nolb;
totp = nop+nob;
indRp = np.zeros((nob+nop,nob+nop)); temp = 0*np.arange(nop); temp[0:norp] = 1; indRp[range(nop),range(nop)] = temp
indLp = np.zeros((nob+nop,nob+nop)); temp = 0*np.arange(nop); temp[norp:nop] = 1; indLp[range(nop),range(nop)] = temp
indRb = np.zeros((nob+nop,nob+nop)); temp = 0*np.arange(nob); temp[0:norb] = 1; indRb[range(nop,(nop+nob)),range(nop,(nop+nob))] = temp
indLb = np.zeros((nob+nop,nob+nop)); temp = 0*np.arange(nob); temp[norb:nob] = 1; indLb[range(nop,(nop+nob)),range(nop,(nop+nob))] = temp
covar_st = (csr_matrix((np.kron(indRp,np.ones((2,2)))+np.kron(indLp,np.ones((2,2)))+np.kron(indRb,np.ones((2,2)))+np.kron(indLb,np.ones((2,2))))))
I = (((Z.dot(covar_st)).dot(Z.transpose())).nonzero())
indices = I[0]+I[1]*N
A = lil_matrix((indices.shape[0],N*N))
A[np.arange(indices.shape[0]), indices] = 1
A = Constant(A)
###################################

####### Optimization part
Z = Z.tocsr();
XtX = (X.transpose()).dot(X);
ZtX = (Z.transpose()).dot(X);
ZtY = (Z.transpose()).dot(Y);
XtZ = ZtX.transpose();
XtY = (X.transpose()).dot(Y);

ZtZ = ((Z.transpose()).tocsr()).dot(Z);

# parameter initialization
evar = 1; ecovRp = np.identity(2); ecovLp = np.identity(2); ecovRb = np.identity(2); ecovLb= np.identity(2);
ecov = csr_matrix((np.kron(indRp,ecovRp)+np.kron(indLp,ecovLp)+np.kron(indRb,ecovRb)+np.kron(indLb,ecovLb)));
##########################################################################  Optimization loop                                                                                     
for iters in range(NUMITER):
	print iters
	# Learn beta_mle given covariance estimates
	ecovinv = sp.csr_matrix((np.kron(indRp,np.linalg.inv(ecovRp))+np.kron(indLp,np.linalg.inv(ecovLp))+np.kron(indRb,np.linalg.inv(ecovRb))+np.kron(indLb,np.linalg.inv(ecovLb))));
	inner_cov = (ecovinv+ZtZ/evar).toarray();
	temp1 = XtX/evar - ((1/evar)*XtZ).dot((np.linalg.inv(inner_cov)).dot(ZtX));
	temp2 = XtY/evar - ((1/evar)*XtZ).dot((np.linalg.inv(inner_cov)).dot(ZtY));
	beta_mle = np.linalg.solve(temp1,temp2);
	res = Y - X.dot(beta_mle);

	# calculate sample covariance matrix elements
	S = np.zeros((I[0].shape[0],));

	for i in range(I[0].shape[0]):
		S[i] = res[I[0][i]]*res[I[1][i]]

	S = Constant(S)

	# using cvxpy
	evar = Variable(1); ecovRp = Semidef(2,2); ecovLp = Semidef(2); ecovRb = Semidef(2); ecovLb = Semidef(2); 
	constraint = [0 <= evar , ecovRp == ecovRp.T, ecovLp == ecovLp.T, ecovLb == ecovLb.T, ecovRb == ecovRb.T];
	########################################### Calculate XX ####################################
	covar_columnlist = [vstack(*[ecovRp, np.zeros((2*(totp-1), 2))])]
	for ii in range(1,norp):
		iii = ii+0;
		covar_columnlist.append(vstack(*[np.zeros((2*iii,2)), ecovRp, np.zeros((2*(totp-iii-1), 2))]))

	for ii in range(nolp):
		iii = ii+norp;
		covar_columnlist.append(vstack(*[np.zeros((2*iii,2)), ecovLp, np.zeros((2*(totp-iii-1), 2))]))

	for ii in range(norb):
		iii = ii+nop;
		covar_columnlist.append(vstack(*[np.zeros((2*iii,2)), ecovRb, np.zeros((2*(totp-iii-1), 2))]))

	for ii in range(nolb-1):
		iii = ii+nop+norb;
		covar_columnlist.append(vstack(*[np.zeros((2*iii,2)), ecovLb, np.zeros((2*(totp-iii-1), 2))]))
	covar_columnlist.append(vstack(*[np.zeros((2*(totp-1),2)), ecovLb]))
	covar_final = hstack(*covar_columnlist)
	print covar_final.size

	Zcov = Z.dot(covar_final);
	ZcovZeye = (Z.dot(Zcov.T)).T+evar*sp.eye(N)
	XX = A*vec(ZcovZeye)
	#############################################################################
	print type(XX)
	obj = Minimize(norm(XX - S, 2))
	prob = Problem(obj, constraint)
	print 'started solving the problem'

	start_time = time.time()
	result = prob.solve(solver=SCS,verbose=True)
	print("--- %s seconds ---" % (time.time() - start_time))
	pkl_file.close()

**Comment by quantdaddy** [comment]
I need to email you the data file. Can I have your email address?

**Comment by SteveDiamond** [comment]
Go to the cvxpy google group and you'll see my email address:

https://groups.google.com/forum/#!forum/cvxpy

**Comment by quantdaddy** [comment]
Unfortunately, google groups are blocked in my office network.

**Comment by SteveDiamond** [comment]
Ok, it's on my personal site: 

http://web.stanford.edu/~stevend2/

**Comment by quantdaddy** [comment]
email sent!

**Comment by mynameisfiber** [comment]
Was there ever a solution to this?

**Comment by SteveDiamond** [comment]
If the problem works in CVX it should work in CVXPY. I searched and couldn't find any record of an email. Maybe I closed the thread because I never got an email. @quantdaddy did I ever get back to you on this thread?

**Comment by quantdaddy** [comment]
I don't exactly remember. I don't see any further conversation about this
in my email.

**Comment by lemon234071** [comment]
Same problem and I have 3T memory on Linux.
  
    m = 2000
    n = 2000
    np.random.seed(1)
    A = cp.Parameter((m, n))
    b = cp.Parameter(m)
    A.value = np.random.randn(m, n)
    b.value = np.random.randn(m)
    # A = np.random.randn(m, n)
    # b = np.random.randn(m)
    
    # Construct the problem.
    x = cp.Variable(n)
    objective = cp.Minimize(cp.sum_squares(A @ x - b))
    constraints = [0 <= x, x <= 1]
    prob = cp.Problem(objective, constraints)
    
    # The optimal objective value is returned by `prob.solve()`.
    result = prob.solve(verbose=True)
    # The optimal value for x is stored in `x.value`.
    print(x.value)
    # The optimal Lagrange multiplier for a constraint is stored in
    # `constraint.dual_value`.
    print(constraints[0].dual_value)

**Comment by SteveDiamond** [comment]
Does it work if A and b aren't parameters? There are issues now with large parameters. We will very soon add functionality to help, but for the moment just try making A and b constants.
