### ISSUE TITLE
Is it possible to solve mixed integer SDP by cvxpy?

### ISSUE THREAD

**Issue by cheneave** [cvxgrp/cvxpy#204]
Is it possible to solve mixed integer SDP by cvxpy?

**Comment by SteveDiamond** [comment]
No, this isn't supported. I'm not aware of any solvers that support mixed integer SDPs.

You could implement a branch and bound method on top of cvxpy's SDP solvers. That's what YALMIP does.

**Comment by cheneave** [comment]
Thank you. I'll try it.
