### ISSUE TITLE
Trouble on Windows with Python 2.7.x 64 bit due to 'shape' being 'long' in this platform 

### ISSUE THREAD

**Issue by sergiocallegari** [cvxgrp/cvxpy#207]
Hi,

I am encountering some issues with cvxpy that are restricted to a single platform (python 2.7.x 64 bit on Windows, e.g. Winpython 2.7.10.1 64 bit).

In this platform, differently from any other, the shape of an ndarray is given by a tuple of `long` integers, rather than 'int' integers. This should be just an implementation detail, but it creates issues with cvxpy. 

Specifically, when you create expressions, the shapes easily start getting mixed `int` and `long` types. Eventually, cvxopt tries using long indexes in expressions and this seems to fail.

I think that some `int` casts are required in the cvxpy codebase.

As an example, try running the test suite of pydsm (you know this piece of code already... and I still need to thank you for the help and the code you prepared for a pull on my side!).

**Comment by SteveDiamond** [comment]
Sorry for taking so long to respond to this. I don't use windows and don't have a good setup for testing things on windows. Do you have any suggestions for ways to easily test on windows? I know about appveyor and have been meaning to set up appveyor tests for a while (@echo could you help with this?).

I hopefully fixed the issue in the latest patch to master, but I wasn't able to test the fix fully. Would you mind testing it on your machine?

**Comment by sergiocallegari** [comment]
Don't be sorry for taking long, as I need time to do to things on Windows as well...

In any case, I managed testing right now and the issue seems to be still there.
`bbc3e96811ca9ac91905ca6cb53f8ec8cb43cf1d` does not seem to be enough.

I'll try to see if I can create a self-contained test program (e.g. to add to a testsuite).

**Comment by rekcahpassyla** [comment]
(Is this the same issue as https://github.com/cvxgrp/cvxpy/issues/127 ?)
