### ISSUE TITLE
ECOS very inaccurate for logistic regression

### ISSUE THREAD

**Issue by bodono** [cvxgrp/cvxpy#208]
I was tinkering around with an l1 regularized logistic regression example, and I noticed that ECOS seems to do very poorly for this problem, see example here:

https://github.com/bodono/apgpy/blob/master/notebooks/L1LogisticRegression.ipynb

The optimal objective function is around 0.69057735228
ECOS gets 0.69093800419
which is even worse than SCS, which gets 0.690683452688

That might not seem like much, but if you look at the figure at the bottom, the true answer in green and SCS solution in blue are almost indistinguishable, and the solution from ECOS in red is very poor.

Since ECOS claims to solve the problem to very high accuracy the issue might be in the translation in cvxpy.

**Comment by argriffing** [comment]
I notice that the cvxpy [implementation](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/atoms/log_sum_exp.py#L35) of `log_sum_exp` does not use the usual numerical tricks to avoid overflow/underflow, but I guess this does not explain a difference between ECOS vs. SCS.

**Comment by SteveDiamond** [comment]
I'm not sure why the ecos solution is so inaccurate. Probably small errors in the problem generated by cvxpy translate to large errors in the original objective due to the fact that there are log and exp transformations going on. @tiagoakle do you have any ideas?

@argriffing how would you recommend implementing the function to evaluate ``log_sum_exp``?

**Comment by tiagoakle** [comment]
Can we look at the norm of the solution? What are the sizes of the primals and duals?

**Comment by argriffing** [comment]
@SteveDiamond I think my comment was not relevant for this issue and that the cvxpy log_sum_exp numerical evaluation wasn't even called before the solvers had already given their inaccurate results. But just for reference the idea is like
```python
>>> x = np.array([500, 1000, 10])
>>> np.log(np.sum(np.exp(x)))
__main__:1: RuntimeWarning: overflow encountered in exp
inf
>>> from scipy.misc import logsumexp
>>> logsumexp(x)
1000.0
```
which can be important for applications like dealing with log likelihoods.

**Comment by SteveDiamond** [comment]
The numerical evaluation wouldn't affect the problem that ecos and scs solve, but it would be called when evaluating the problem objective. In any case using the ``logsumexp`` function is a good improvement to make.

**Comment by tiagoakle** [comment]
This is an issue within ECOS but the origin is still not clear. However, disabling the
scaling that ECOS uses internally seems to resolve the issue.
