### ISSUE TITLE
using mul_elemwise for cvx variable

### ISSUE THREAD

**Issue by sinhamridu** [cvxgrp/cvxpy#210]
I have the following code snippet for cvxpy:

delta=1e-3
loglambda = rvec*theta #rvec: TxJ regressor matrix, theta: (Jx1) cvx variable 
a= mul_elemwise(dy[0:T],loglambda) # size(Tx1)
b1=cvx.exp(loglambda) 
b2=mul_elemwise(delta,b1) 
cost= -a + b1             
#cost= -a + b2  #size (Tx1)
prob = Problem(Minimize(sum_entries(cost)))
prob.solve(solver=SCS)

The code runs fine as it is with cost = - a + b1. However, if I try to multiply b1 with a scalar using mul_elemwise and try to run it with cost = - a + b2 , it gives me an error - UnboundLocalError: Local variable 'coeff' referenced before assignment.

**Comment by SteveDiamond** [comment]
Good catch! This is fixed on the latest master. You don't need to use ``mul_elemwise`` to multiply by a scalar though. If you write ``delta*b1`` it will automatically do the right thing.

**Comment by sinhamridu** [comment]
Thank you!

On Tue, Aug 4, 2015 at 4:26 PM, Steven Diamond <notifications@github.com>
wrote:

> Good catch! This is fixed on the latest master. You don't need to use
> mul_elemwise to multiply by a scalar though. If you write delta*b1 it
> will automatically do the right thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cvxgrp/cvxpy/issues/210#issuecomment-127794644>.
>



-- 
Graduate Student
Bioengineering | UCSD
