### ISSUE TITLE
ECOS infeasible for small LP

### ISSUE THREAD

**Issue by ajfriend** [cvxgrp/cvxpy#216]
I made a small diet problem feasibility LP for a class, and ECOS seems to fail, while SCS and CVXOPT handle it fine.

The data:
```
from cvxpy import *
import numpy as np
h = np.array([.8, .4, .5])
c = np.array([0, .3, 2.0])
r = np.array([1, 2.1, 1.7])
p = np.array([1, .25])
```

The minimization version
```
x = Variable(2)
obj = Minimize(x.T*p)
constr = [
          h*x[0] + c*x[1] >= 50*r,
          x >= 0]

prob = Problem(obj, constr)
prob.solve(solver='ECOS')
print prob.value
```
gives an optimal value of 129.166666672. If I write a feasibility version of the problem:
```
x = Variable(2)
obj = Minimize(0)
constr = [x.T*p <= 130,
          h*x[0] + c*x[1] >= 50*r,
          x >= 0]

prob = Problem(obj, constr)
prob.solve(solver='ECOS')
print prob.value
```
ECOS incorrectly determines the problem to be infeasible, which is weird, since it just solved the minimization version of the problem without any trouble. SCS and CVXOPT don't have any trouble with either version.

Any idea what's going on?

**Comment by SteveDiamond** [comment]
This is weird. It still returns infeasible for me if I loosen the ``x.T*p <= 130`` constraint up to ``x.T*p <= 350``, so it's not a numerical tolerance issue.

Could you post this as an issue on the ECOS repo?
