### ISSUE TITLE
Failing test - test_solver_errors

### ISSUE THREAD

**Issue by lukeyeager** [cvxgrp/cvxpy#217]
This test fails - no exception is raised:
```
======================================================================
FAIL: Tests that solver errors throw an exception.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/code/optimization/venv/local/lib/python2.7/site-packages/cvxpy/tests/test_solvers.py", line 27, in test_solver_errors
    prob.solve(solver=CVXOPT)
AssertionError: Exception not raised

----------------------------------------------------------------------
Ran 2350 tests in 21.073s
```
https://github.com/cvxgrp/cvxpy/blob/v0.2.25/cvxpy/tests/test_solvers.py#L19-L29
```
$ pip list | grep cvx
cvxopt (1.1.7)
cvxpy (0.2.25)
```
I followed these instructions to install everything:
http://cvxpy.readthedocs.org/en/latest/install/#ubuntu-14-04

**Comment by SteveDiamond** [comment]
That's weird. I just tested it on exactly the same set up and the test passed. You're using Ubuntu 14.04, right?

**Comment by lukeyeager** [comment]
> You're using Ubuntu 14.04, right?

Yes.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```
I'm on an EC2  t2.micro instance. I've installed cvxpy in a virtualenv.

Any other information I can give you? This is obviously not a problem for me, I just wanted to give you a heads up.

**Comment by SteveDiamond** [comment]
I appreciate the heads up. It's good news that CVXOPT is working on this problem now. I'll just need to figure out a new way to test solver failure.

**Comment by SteveDiamond** [comment]
I removed the test.
