### ISSUE TITLE
Best practices for inspecting problem transformation

### ISSUE THREAD

**Issue by mattwescott** [cvxgrp/cvxpy#222]
I'm interested in inspecting how cvxpy transforms a problem before sending it to a solver. Is a debugger the best choice for this? 

Thanks for your efforts on this interesting and useful project!

**Comment by SteveDiamond** [comment]
I would use pdb. Every expression has an argument list ``args`` that you can use to walk the expression tree. Unfortunately the print output for expressions is not great, but you can always print the expression type at least.
