### ISSUE TITLE
ECOS incorrectly solves simple EXP

### ISSUE THREAD

**Issue by ajfriend** [cvxgrp/cvxpy#225]
I was getting wrong answers in a model, and I think the issue boils down to what's happening in the following exponential cone program.

```
import cvxpy as cvx
import numpy as np

a = .3
x = cvx.Variable()
cvx.Problem(cvx.Minimize(cvx.exp(a*x)-x)).solve(solver='ECOS')
true_x = -np.log(a)/a

print x.value, true_x
```

ECOS gets the wrong answer here, but SCS gets it right.

ECOS get the right answer when `a=1.0`, but incorrect results when `a` is not `1.0`.

Perhaps related to #208?

**Comment by SteveDiamond** [comment]
Is this resolved? It looks like ECOS was fixed.

**Comment by ajfriend** [comment]
Yeah. It works now! Thanks!
