### ISSUE TITLE
Conda install with Python3

### ISSUE THREAD

**Issue by cmale** [cvxgrp/cvxpy#227]
On cvxpy.org Install guide it states:

Mac OS X
The following instructions assume you already have Python installed. CVXPY supports both Python 2 and Python 3. 

The instructions are for pip but I am using conda. 

conda install -c https://conda.binstar.org/cvxgrp cvxpy

Results:
Fetching package metadata: ......
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
[      COMPLETE      ]|################################################################################| 100%

Hint: the following packages conflict with each other:
  - cvxpy
  - python 3.4*

Does the cvxpy binstar package not work with python3?

**Comment by SteveDiamond** [comment]
The cvxpy conda package isn't finished. I'm not sure it even works with Python 2. You need to use pip.
