### ISSUE TITLE
entr() and kl_div() do not resolve to scalars

### ISSUE THREAD

**Issue by psiminelakis** [cvxgrp/cvxpy#231]
I was trying to use the ```entr``` built in scalar function and I get the following error:
```
Exception: The 'maximize' objective must resolve to a scalar.
```
The code I was trying to run was this:
```
import cvxpy as cvx
from  numpy import *

M = cvx.Symmetric(n)
cvx.constraint = [M >= 0, M* ones(n, 1) == ones(n, 1)]
obj = cvx.Maximize(cvx.entr(M))
```

**Comment by mwytock** [comment]
I think you need to do

cvx.sum_entries(cvx.entr(M))

as it looks like entr() just applies the entropy function on an elementwise basis. It also looks like this page

http://cvxpy.readthedocs.org/en/latest/tutorial/functions/

which says entr() includes the sum may be out of date...

**Comment by SteveDiamond** [comment]
Oops, the docs are wrong. Do you think summing the elements as part of
the entr atom would be better though?

**Comment by psiminelakis** [comment]
I solved it by doing ``` sum([cvx.entr(M[i,j]) for i in range(n) for j in range(n)]) ```. I guess that is equivalent to using ```sum_entries```. 

I think that perhaps ```entr``` as well as ```kl_div``` atom should indeed sum the elements. I can't think of many reasons (weighted entropy, composition of entropy with other functions)  why not to? 

Pertaining to the last point, perhaps you could add a new elementwise function corresponding to [f-divergences](https://en.wikipedia.org/wiki/F-divergence).

**Comment by bodono** [comment]
It makes sense to me for them to apply element-wise, since it's easy for the user to do the sum.

**Comment by argriffing** [comment]
I like that they are element-wise.

**Comment by SteveDiamond** [comment]
I'm keeping them elementwise and updating the docs.
