### ISSUE TITLE
Warm start

### ISSUE THREAD

**Issue by AlexeyG** [cvxgrp/cvxpy#234]
Hi,

This is more of a question, and possibly a feature request, rather than a bug report.

I am trying to use cvxpy to solve a LASSO-like problem with L1 regularisation and I'd like to do that for a number of different regularisation parameter (alpha) values. I know that packages like glmnet allow for solving the problem for a number of alpha's with one function call. My understanding is that it uses the warm start strategy where the solution for a particular value of alpha is refined into a solution for a similar value of alpha. I imagine that something like this would also be useful for my problem and allow cvxpy to solve the problems faster, but I couldn't find this option.

Is there a possibility of using warm starts with cvxpy, and if not, would it be possible to hack it into the module, could you point me towards where I should look?

**Comment by AlexeyG** [comment]
I found the cvxpy/performance_tests/test_warmstart.py file right after creating the issue.
I think the example in that file answers my questions :)

**Comment by SteveDiamond** [comment]
I added a few lines about warm start to the docs. It only works for SCS right now.
