### ISSUE TITLE
Failure with solving SDPs

### ISSUE THREAD

**Issue by govinda-kamath** [cvxgrp/cvxpy#237]
Hi, 

I had the following optimisation code, which seems to be throwing unexpected errors.

import cvxpy as cvx

Y = cvx.Semidef(n)

obj=cvx.Maximize(cvx.trace(A*Y))
constraint = (cvx.diag(Y)==1)
prob=cvx.Problem(obj,constraint)
prob.solve()

The trace I seem to be getting is the following (even though the problem is convex):

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-163-8ea2cdbce94c> in <module>()
      6 constraint = (cvx.diag(Y)==1)
      7 prob=cvx.Problem(obj,constraint)
----> 8 prob.solve()

/media/data/anaconda/lib/python2.7/site-packages/cvxpy/problems/problem.pyc in solve(self, *args, **kwargs)
    154             return func(self, *args, **kwargs)
    155         else:
--> 156             return self._solve(*args, **kwargs)
    157 
    158     @classmethod

/media/data/anaconda/lib/python2.7/site-packages/cvxpy/problems/problem.pyc in _solve(self, solver, ignore_dcp, warm_start, verbose, **kwargs)
    217             why the problem could not be solved.
    218         """
--> 219         if not self.is_dcp():
    220             if ignore_dcp:
    221                 print ("Problem does not follow DCP rules. "

/media/data/anaconda/lib/python2.7/site-packages/cvxpy/problems/problem.pyc in is_dcp(self)
     89         """Does the problem satisfy DCP rules?
     90         """
---> 91         return all(exp.is_dcp() for exp in self.constraints + [self.objective])
     92 
     93     def canonicalize(self):

TypeError: unsupported operand type(s) for +: 'EqConstraint' and 'list'

**Comment by SteveDiamond** [comment]
The second argument to ``cvx.Problem(objective, constraints)`` has to be a list of constraints, not a single constraint:
```
import cvxpy as cvx

Y = cvx.Semidef(n)

obj=cvx.Maximize(cvx.trace(A*Y))
constraint = [cvx.diag(Y)==1]
prob=cvx.Problem(obj,constraint)
prob.solve()
```

**Comment by govinda-kamath** [comment]
Thanks. That works
