### ISSUE TITLE
N variables constraint

### ISSUE THREAD

**Issue by gerosalesc** [cvxgrp/cvxpy#242]
Trying to figure out a way to write a constraint with N variable to use on CVXPY that fit this:

var1 + var2 + ... + varN = K # K is a constant
All variables objects are instantiated and are stored in a list.

DETAILS:

http://stackoverflow.com/questions/33223473/cvxpy-constraint-with-n-variables

**Comment by SteveDiamond** [comment]
I answered on stackoverflow. Just write
```
constraint = sum([var1,var2,...]) == K
```

**Comment by gerosalesc** [comment]
And I accepted your answer, that work flawlessly, thank you very much
