### ISSUE TITLE
Vague solver failure on initial install

### ISSUE THREAD

**Issue by redraven984** [cvxgrp/cvxpy#243]
Im trying to install cvxpy on an x64, py27, windows system. After trying to add the package to anaconda I switched to python(x,y) and was able to get cvxopt and cvxpy installed. The package is recognized in python and will even run defined problems. However the solvers just dont iterate. I then ran "nosetests cvxpy" at the command prompt to see if the solvers are correctly installed. I got the following error:

PS H:\> nosetests cvxpy
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
....................................................................................................................
...........................................................F....
======================================================================
FAIL: test_solver_errors (cvxpy.tests.test_solvers.TestSolvers)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cvxpy\tests\test_solvers.py", line 27, in test_solver_errors
    prob.solve(solver=CVXOPT)
AssertionError: Exception not raised

----------------------------------------------------------------------
Ran 2344 tests in 11.453s 

What does this mean? What is the problem? How can I finish installing the solvers?

**Comment by SteveDiamond** [comment]
There's nothing wrong. It's a test case for solver failure that relied on CVXOPT not being able to solve a certain problem. But CVXOPT improved and can now solve that problem. The test isn't in the latest CVXPY on PyPi, but the Python(x,y) version is older.

**Comment by redraven984** [comment]
Thanks steve. So do i have the newest version of the solver? If not, how do i get it?

**Comment by SteveDiamond** [comment]
You have a slightly older version of cvxpy. I wouldn't worry about it. You
would need to install it with pip to get a later version.

**Comment by redraven984** [comment]
Thanks again for you help! 

I ran into an issue friday upgrading ecos via pip because im running x64. It kept trying to upgrade numpy to x32 in the process. Would o have a similar issue with cvxpy?

**Comment by SteveDiamond** [comment]
I don't know. I've never heard of that happening before. I would just try
and upgrade and see what happens.
