### ISSUE TITLE
Failure using SCS solver

### ISSUE THREAD

**Issue by iskandr** [cvxgrp/cvxpy#244]
I installed cvxpy via `pip` but when I try to use it I get the following error:

```
----------------------------------------------------------------------------
        SCS v1.1.7 - Splitting Conic Solver
        (c) Brendan O'Donoghue, Stanford University, 2012-2015
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 65496833
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 43056376, constraints m = 44160356
Cones:  primal zero / dual free vars: 21524924
        linear vars: 662388
        soc vars: 662388, soc blks: 220796
        sd vars: 21310656, sd blks: 1
FATAL: Cannot solve SDPs with > 2x2 matrices without linked blas+lapack libraries
Edit scs.mk to point to blas+lapack libray locations
*** Error in `python': free(): invalid pointer: 0x00000000077c3620 ***
Aborted (core dumped)
```

**Comment by SteveDiamond** [comment]
How did you install SCS? What OS are you using?

**Comment by iskandr** [comment]
I was previously getting this error on Mac OS X. Now I'm seeing something similar on a Travis instance running Linux:

```
Using worker: worker-linux-docker-98f7791c.prod.travis-ci.org:travis-linux-3
system_info
Build system information
Build language: python
Build group: stable
Build dist: precise
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
...
================
ERROR: test_nuclear_norm_minimization.test_rank1_symmetric_convex_solver
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/hammerlab/fancyimpute/test/test_nuclear_norm_minimization.py", line 42, in test_rank1_symmetric_convex_solver
    completed = solver.complete(XYXY_missing_rank1)
  File "/home/travis/build/hammerlab/fancyimpute/fancyimpute/solver.py", line 207, in complete
    imputations = self.multiple_imputations(X)
  File "/home/travis/build/hammerlab/fancyimpute/fancyimpute/solver.py", line 199, in multiple_imputations
    return [self.single_imputation(X) for _ in range(self.n_imputations)]
  File "/home/travis/build/hammerlab/fancyimpute/fancyimpute/solver.py", line 184, in single_imputation
    X_result = self.solve(X_filled, missing_mask)
  File "/home/travis/build/hammerlab/fancyimpute/fancyimpute/nuclear_norm_minimization.py", line 122, in solve
    solver=cvxpy.SCS if self.fast_but_approximate else None)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 173, in solve
    return self._solve(*args, **kwargs)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 284, in _solve
    self._update_problem_state(results_dict, sym_data, solver)
  File "/home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 396, in _update_problem_state
    "Solver '%s' failed. Try another solver." % solver.name())
SolverError: Solver 'SCS' failed. Try another solver.
-------------------- >> begin captured stdout << ---------------------
----------------------------------------------------------------------------
	SCS v1.2.2 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 363
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 150, constraints m = 225
Cones:	primal zero / dual free vars: 95
	linear vars: 75
	sd vars: 55, sd blks: 1
FATAL: Cannot solve SDPs with > 2x2 matrices without linked blas+lapack libraries
Install blas+lapack and re-compile SCS with blas+lapack libray locations
```

**Comment by SteveDiamond** [comment]
My guess is you didn't install SCS with correct lapack support. Try exporting the location of ATLAS like this
```
export ATLAS="/usr/lib/atlas-base/libatlas.so # adapt to your installation
``` 
and then installing SCS.

**Comment by HarjBasra** [comment]
I am having a very similar problem in Windows 10, when cvxpy was installed with Anaconda.

======================================================================
ERROR: Test sigma_max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Harjit Basra\Anaconda2\lib\site-packages\cvxpy\tests\test_scs.py", line 79, in test_sigma_max
    result = prob.solve(solver=SCS)
  File "C:\Users\Harjit Basra\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 195, in solve
    return self._solve(*args, **kwargs)
  File "C:\Users\Harjit Basra\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 325, in _solve
    self._update_problem_state(results_dict, sym_data, solver)
  File "C:\Users\Harjit Basra\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 437, in _update_problem_state
    "Solver '%s' failed. Try another solver." % solver.name())
SolverError: Solver 'SCS' failed. Try another solver.
-------------------- >> begin captured stdout << ---------------------
FATAL: Cannot solve SDPs with > 2x2 matrices without linked blas+lapack libraries
Install blas+lapack and re-compile SCS with blas+lapack libray locations
ERROR: initCone failure
Failure:could not initialize work

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 1681 tests in 14.098s

FAILED (errors=21)

**Comment by SteveDiamond** [comment]
Installing SCS with Anaconda is broken right now. We are working on fixing this.

**Comment by iskandr** [comment]
Any progress on this?

**Comment by SteveDiamond** [comment]
When you install SCS, it has to link against BLAS/LAPACK. Otherwise it
can't solve SDPs. You should look into the SCS installation instructions.
The Anaconda packages for Mac and Linux take care of the linking, but in
Windows you have to take care of it yourself.

**Comment by iskandr** [comment]
Which conda package handles this correctly on Linux? I'm still getting Travis test failures due to SCS not linking with BLAS/LAPACK.

**Comment by SteveDiamond** [comment]
You installed the SCS from the cvxgrp channel? That should work.

**Comment by iskandr** [comment]
Trying that one now, I'll let you know how it goes!

**Comment by davidrey123** [comment]
Hi, I am trying to use cvxpy on a Windows 7 machine with Python 3.4 and Anaconda 4 but I got the same error message that HarjBasra got, i.e.:

FATAL: Cannot solve SDPs with > 2x2 matrices without linked blas+lapack libraries
Install blas+lapack and re-compile SCS with blas+lapack libray locations
ERROR: initCone failure
Failure:could not initialize work

In my package list, I have mkl, scs and cvxpy installed. I tried uninstalling and re-installing scs but that doesn't help. If I understood correctly mkl contains the BLAS and LAPACK librairies but for some reason it's not working. Is there any workaround?

**Comment by tachim** [comment]
@SteveDiamond I'm seeing this failure as well, with the `cvxgrp` SCS packages:

```
root@0d4f88423a95:~# conda list | grep cvxgrp
cvxcanon                  0.1.0                    py27_0    cvxgrp
cvxpy                     0.4.8                    py27_0    cvxgrp
ecos                      2.0.4                    py27_0    cvxgrp
multiprocess              0.70.4                   py27_0    cvxgrp
scs                       1.2.6                    py27_0    cvxgrp
root@0d4f88423a95:~# dpkg -l | grep lapack
ii  liblapack3                             3.5.0-2ubuntu1                   amd64        Library of linear algebra routines 3 - shared version
root@0d4f88423a95:~# dpkg -l | grep blas
ii  cuda-cublas-7-5                        7.5-18                           amd64        CUBLAS native runtime libraries
ii  cuda-cublas-dev-7-5                    7.5-18                           amd64        CUBLAS native dev links, headers
ii  libblas-dev                            1.2.20110419-7                   amd64        Basic Linear Algebra Subroutines 3, static library
ii  libblas3                               1.2.20110419-7                   amd64        Basic Linear Algebra Reference implementations, shared library
```

The specific error is:

```
----------------------------------------------------------------------------
	SCS v1.2.6 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012-2016
----------------------------------------------------------------------------
Lin-sys: sparse-indirect, nnz in A = 17734846, CG tol ~ 1/iter^(2.00)
eps = 1.00e-03, alpha = 1.50, max_iters = 2500, normalize = 1, scale = 1.00
Variables n = 9651600, constraints m = 10832400
Cones:	primal zero / dual free vars: 4234050
	linear vars: 2952000
	sd vars: 3646350, sd blks: 1
FATAL: Cannot solve SDPs with > 2x2 matrices without linked blas+lapack libraries
Install blas+lapack and re-compile SCS with blas+lapack libray locations
ERROR: initCone failure
Setup time: 4.44e-01s
Failure:could not initialize work
```

**Comment by SteveDiamond** [comment]
@bodono any idea what's going on here? I suspect something important has changed in Anaconda.

**Comment by bodono** [comment]
That error is only printed if SCS was compiled without lapack support. I'm not overly familiar with conda, but I wonder if the recipe is incorrectly setting the LAPACK_LIB_FOUND variable to false during compilation.

**Comment by calys** [comment]
Are there any updates on this issue? I am having the same problem on Windows with the latest version of Anaconda (starting from scratch, with the newest installer).

**Comment by SteveDiamond** [comment]
@calys for Windows you need to install SCS without using Anaconda. Make sure the install actually links to LAPACK.

**Comment by GrainLive** [comment]
I come across the same problem. Windows 10 64bit, Python 3.6, using anaconda. So what should I do to 're-compile SCS with blas+lapack libray locations'?

**Comment by przemyslslaw** [comment]
Same problem here. Installed cvxpy on Anaconda Anaconda 2.3.0. Then installed gccp via pip, but it gave "RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa". Then installed gccp from source and I'm having this problem. Any tips?

**Comment by ekellbuch** [comment]
pip install numpy --upgrade

**Comment by qinfeng** [comment]
I encountered the same issue in Ubuntu 16.04 with Python 3, even with libblas.so/liblapack.so installed.

The silly mistake there is scs or cvxpy is installed via pip **before** blas/lapack been installed. So the unlinked scs wheel is cached.

So after blas/lapack installed, ```pip install -I scs``` will still get the wheel from the pip cache folder.
Disable the pip cache will solve the issue by ```pip install --no-cache-dir -I scs```, since it will build scs from source to link with blas/lapack.

Wish it will help any of you who may encounter the same issue.

**Comment by wkschwartz** [comment]
For anyone who gets here from Google with the same issue on Travis as https://github.com/cvxgrp/cvxpy/issues/244#issuecomment-193470798 you can work around this problem by adding the following to your .travis.yml:

```yaml
before_install:
    - sudo apt-get install libblas-dev liblapack-dev  # Needed for pip install cvxpy or pip install scs
```
