### ISSUE TITLE
Help in framing a problem for cvxpy

### ISSUE THREAD

**Issue by vipulbhandari82** [cvxgrp/cvxpy#248]
Here X is the variable, everything else is constant.
alpha is a vector of constants. x[0] = 0

u(x1, . . . , xT ) = Sum of i from 0 to T(X[i] * alpha[i] - k/2*sigma^2 - cost_func(x[i] - x[i-1])

here cost function is defined as

def cost_func(delta_trading_dollars):
    first_term =  (lambdda*vol/2.0)*(delta_trading_dollars/(P*V))*((Theta/V)**(0.25))
    x = nu * vol * (abs(delta_trading_dollars/(P*V))**beta)
    second_term = sign(delta_trading_dollars)*x
    cost = delta_trading_dollars * (first_term + second_term)
    return cost

#Numbers of days
T =30
#Return decay
alpha = lambda t : 50 * 0.0001 * (2**(-t/5.0))
#Price
P = 40
#Daily Volume
V = 2 * (10**6)
#Total number of shares outstanding 
Theta = 2 * (10**8)
#Volatility
vol = 0.02
#Constants
lambdda = 0.314
nu = 0.142
beta = 0.60
kappa = 10e-7

**Comment by sschnug** [comment]
This looks like a modelling problem and should not qualify for opening an issue here (there may be some exceptions regarding complex models where some missing library function may replaced with existing ones when it's not that obvious)!

I'm pretty sure this issue-tracker is for posting bugs and discussing future-directions of this library.

(Furthermore you are not really describing "what's" your problem)

- Sascha

**Comment by SteveDiamond** [comment]
@sschnug is right about the purpose of the issue-tracker. You should use the mailing list (https://groups.google.com/forum/#!forum/cvxpy) for questions about how to use cvxpy.

I'm going to close this issue. You're welcome to post the issue again on the mailing list, but I would suggest reading through the tutorial first (http://www.cvxpy.org/en/latest/tutorial/index.html). That should help you formulate your problem.

**Comment by vipulbhandari82** [comment]
Thank you.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Sun, Dec 20, 2015 at 1:01 PM -0800, "Steven Diamond" <notifications@github.com<mailto:notifications@github.com>> wrote:


@sschnug<https://github.com/sschnug> is right about the purpose of the issue-tracker. You should use the mailing list (https://groups.google.com/forum/#!forum/cvxpy) for questions about how to use cvxpy.

I'm going to close this issue. You're welcome to post the issue again on the mailing list, but I would suggest reading through the tutorial first (http://www.cvxpy.org/en/latest/tutorial/index.html). That should help you formulate your problem.

-
