### ISSUE TITLE
Anaconda Mac (red herring) missing libgfortran.3.dylib and "AttributeError: 'module' object has no attribute 'utilities'" errors and a solution

### ISSUE THREAD

**Issue by ianozsvald** [cvxgrp/cvxpy#253]
This is a sort-of bug post, it shows the probable red-herring that's exposed on a Mac (Yosemite) with Anaconda installing `cvxopt` and `cvxpy` and shows an Anaconda solution. I was using Python 2.7, IPython 4.0 and fresh environments created today.

I'm noting this as information for others, I don't think there's any direct actions to take.

First - the bugs. If using a recent Anaconda installation you can install `cvxpy` from a channel (https://anaconda.org/omnia/cvxpy) that looks good and installs without error:
```
  (research)...$ conda info
Current conda install:
             platform : osx-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.0

(research) $ conda install -c https://conda.anaconda.org/omnia cvxpy
```

After installing, you get two sorts of errors:
```
In [7]: import cvxpy
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-e37c0baa4c4c> in <module>()
----> 1 import cvxpy

[...]/site-packages/cvxpy/__init__.py in <module>()
     19 
     20 __version__ = "0.3.1"
---> 21 from cvxpy.atoms import *
     22 from cvxpy.expressions.variables import Variable, Semidef, Symmetric, Bool, Int
     23 from cvxpy.expressions.constants import Parameter, CallbackParam, Constant

[...]/site-packages/cvxpy/atoms/__init__.py in <module>()
     18 """
     19 
---> 20 from cvxpy.atoms.geo_mean import geo_mean
     21 from cvxpy.atoms.harmonic_mean import harmonic_mean
     22 from cvxpy.atoms.kl_div import kl_div

[...]/site-packages/cvxpy/atoms/geo_mean.py in <module>()
     19 
     20 
---> 21 import cvxpy.utilities as u
     22 from cvxpy.atoms.atom import Atom
     23 from cvxpy.atoms.affine.index import index

AttributeError: 'module' object has no attribute 'utilities'
```

The above error looks a bit like https://github.com/cvxgrp/cvxpy/issues/115.

With `cvxopt` you get:
```
In [2]: import cvxopt
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-14abf1b564a4> in <module>()
----> 1 import cvxopt

[...]/python2.7/site-packages/cvxopt/__init__.py in <module>()
     30 # You should have received a copy of the GNU General Public License
     31 
---> 32 import cvxopt.base
     33 
     34 def normal(nrows, ncols=1, mean=0.0, std=1.0):

[...]/python2.7/site-packages/cvxopt/base.so, 2): Library not loaded: @rpath/./libgfortran.3.dylib
  Referenced from:[...]/python2.7/site-packages/cvxopt/base.so
  Reason: image not found
```

I went in circles trying to soft-link related libraries (both `libgfortran` and `libopenblas` as needed) but couldn't get them to work.

I then removed these installations and installed from source in a fresh Anaconda environment:
```
conda create -n research2 anaconda python=2.7
source activate research2
cd /tmp
mv ~/Downloads/cvxopt-1.1.8.tar.gz .
gunzip cvxopt-1.1.8.tar.gz 
tar -xvf cvxopt-1.1.8.tar 
cd cvxopt-1.1.8
python setup.py install  # using "cd .." and then ipython and "import cvxopt" works without errors
mv ~/Downloads/cvxpy-master.zip .  # downloaded master copy of cvxpy (2016-01-08)
unzip cvxpy-master.zip 
cd cvxpy-master
python setup.py install
# called up ipython, ran the demo for cvxpy off of the homepage
```

From here `cvxpy` worked just fine. I don't know what's up with the Conda channel version but after several hours I'm fairly confident that it is broken. The *same* channel works perfectly fine on my Ubuntu 14.04 Anaconda system on the first try.

**Comment by SteveDiamond** [comment]
Thanks for documenting this! Is there any way to get whoever owns the channel to correct the cvxpy package?

**Comment by Atanahel** [comment]
Just had the same issue, thanks a lot @ianozsvald for your catch :-)

Just reporting with the python 3.5 config :
````
             platform : osx-64
        conda version : 3.19.0
  conda-build version : 1.18.1
       python version : 3.5.1.final.0
     requests version : 2.9.0
```

**Comment by shagru** [comment]
I had the same issues on Mac (Yosemite) with Python 3.4

**Comment by JohnRobson** [comment]
Same Problem:

File "/usr/lib/python3.5/site-packages/cvxpy/constraints/bool_constr.py", line 23, in <module>
    import cvxpy.utilities.performance_utils as pu

AttributeError: module 'cvxpy.utilities' has no attribute 'performance_utils'

**Comment by SteveDiamond** [comment]
Ok, how did you install cvxpy? You should install it using Anaconda on the cvxgrp channel.

**Comment by JohnRobson** [comment]
Hi, I fixed it, I remove it and installed directly from pypi. Now worked, thank you!!!
