### ISSUE TITLE
my misunderstanding or feature request

### ISSUE THREAD

**Issue by enzobusseti** [cvxgrp/cvxpy#255]
Steven,

suppose i have
x = Variable()
y = Variable()

i want to take their sum (or any other function that applies to vectors)

these fail:
sum_entries(x,y)
sum_entries([x,y])

the simplest way i found that works is
sum_entries(hstack(x,y))

could we implement the notation 
sum_entries([x,y]) 
so that is works as sum_entries(hstack(x,y))?

(i.e., recognize that the argument is an iterable and check that every element is an Expression, etc.)

**Comment by enzobusseti** [comment]
(of course this is a bad example because we can do sum([x,y]) and it works. specifically, I'm trying to do log_sum_exp([x,y]) )

**Comment by SteveDiamond** [comment]
Is using vstack or hstack so bad? The semantics of all these single argument functions could get complicated if we allow lists/iterables. I could add a flatten/ravel function that takes a list and turns it into a giant vector as best it can.

**Comment by enzobusseti** [comment]
yeah don't worry. i think (aesthetically) the notation 
```python
log_sum_exp([x,y])
```
is better than
```python
log_sum_exp(hstack(x,y))
```
but if it takes significant work forget about it..
