### ISSUE TITLE
cvxpy install error

### ISSUE THREAD

**Issue by yizhu2016** [cvxgrp/cvxpy#257]
Hi,
  Today I followed the instructions for installing cvxpy for windows (Windows 7) using Anaconda (64 bits)(http://www.cvxpy.org/en/latest/install/). When I use  "pip install cvxpy" (the last step), I got the error as follows: 
  ... \cvxopt\src\c\cvxopt.h(31) : fatal error C1083: Cannot open include file: 'complex.h': No such file or directory
   error: command 'C:\\Users\\zhyi\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2

 I have googled a lot but still I'm unable to find a  solution. Do you know how to fix this? 
  Thanks,
  Yi Zhu

**Comment by sschnug** [comment]
I just tried this way of installing cvxpy in Win 7 using Anaconda (64-bits) for Python 2.7 and Python 3.4. No problems there while installing.
Are you sure, that you installed the pre-built cvxopt binaries from https://conda.anaconda.org/omnia cvxopt? I might be wrong here, but the error above looks like your system wants to compile it (which should not happen). Again: i might be wrong about this! 

Another thing: while the two installs above worked, the nosetests crash python! So i think there are also problems within the cvxopt binaries or maybe somewhere else! Just a warning!

Maybe it's not possible for you, but i can tell you that *omnia* has working cvxopt/scs/cvxpy builts for Win-32.

- Sascha

**Comment by yizhu2016** [comment]
Thanks Sascha! I switched to 32 bits and used the open sesame: 
 conda install -c https://conda.anaconda.org/omnia cvxpy, 
and the door opened!
Thanks again Sascha!
