### ISSUE TITLE
problems with scales of constants

### ISSUE THREAD

**Issue by bison123** [cvxgrp/cvxpy#261]
The below example is using cvxpy version 0.3.4. 

Cvxpy seems to have issues with the scale of inputs. The code below is a simple portfolio construction example (adapted from cvxpy's own portfolio construction example here: http://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb) where we know the closed form solution. Although we can can compute the closed form solution and verify that cvxpy also correctly computes this solution when the "scale" setting at the top of this code is <= 1e2, when we set the scale to >= 1e3, cvxpy fails. (Having a large scale for mu and Sigma is very realistic when casting the optimization problem in terms of dollar returns rather than percentage returns.)

Thank you very much in advance for any fixes you can provide.

-Jesse Davis
Blackrock

# Scaling issues with cvxpy
scale = 1e3  # works for scale <= 1e2, fails for scale >= 1e3

# Generate data for long/short portfolio optimization.
import numpy as np
np.random.seed(1)
n = 10
mu = scale * np.abs(np.random.randn(n, 1))
Sigma = np.random.randn(n, n)
Sigma = (scale ** 2.) * Sigma.T.dot(Sigma)

# Long/short portfolio optimization.
from cvxpy import *
w = Variable(n)
gamma = 1.
ret = mu.T*w
risk = quad_form(w, Sigma)
prob = Problem(Maximize(ret - gamma/2.*risk))

# In this simple case, we know the result in closed form:
expected_result = 1./gamma * np.dot(np.linalg.inv(Sigma), mu)

# Call cvxpy to solve the problem
prob.solve()

# Print the results
print(w.value)
print(expected_result - w.value)

**Comment by bodono** [comment]
You can try a different solver, e.g.,
```
prob.solve(solver=SCS)
```
works for me.

**Comment by SteveDiamond** [comment]
Unfortunately the default solver, ECOS, runs into numerical issues sometimes. I've created an issue on the ECOS github page describing the numerical problems you ran into, so hopefully the authors will look into it. As Brendan suggests you can always try the other solvers, like SCS. You may want to use CVXPY with a commercial solver like GUROBI or MOSEK for maximum reliability.

**Comment by bison123** [comment]
Thank you for the advice, I did find that different solvers perform with scale of inputs quite differently with CVXOPT being able to solve problems at a slightly larger scale than ECOS, and we'll work on getting SCS up and running. Interestingly, if I cast my problem directly to CVXOPT, I could solve problems at about 1.5 orders of magnitude larger scale than going via CVXPY which is what spurred me to think it may have been an issue with CVXPY itself. 

I’ve also considered going down a path of pre-conditioning to remove the scaling issue, does cvxpy have any methods that can be exposed to help with that? I’ve attempted to use a formulation such as x = cvxpy.mul_elemwise(scale, Variable(n)) after computing a scale manually, but is there a more preferred mechanism to consider?

**Comment by SteveDiamond** [comment]
The reason you're getting different behavior calling CVXOPT directly is that CVXPY does some preprocessing before calling CVXOPT. It doesn't do this preprocessing for the other solvers. So the issue is with the solvers, not CVXPY.

I would definitely recommend preconditioning the problem. There isn't really a preferred way of doing this. I would rescale the problem data rather than scaling the variable though.

**Comment by bison123** [comment]
Thank you for the recommendation Steve, very much appreciated.
