### ISSUE TITLE
SCS solver doesn't return a Semidefinite Matrix

### ISSUE THREAD

**Issue by mesejo** [cvxgrp/cvxpy#262]
`import numpy as np
import cvxpy as cvx

n = 4
D = np.array([[1., 0., 0., 0.25], [0., 1., 0., 0.75], [0., 0., 1., 0.75], [0.25, 0.75, 0.75, 1.]])

alpha = cvx.Variable()
X = cvx.Semidef(n)

constraints = [D <= X, X <= alpha * D]

obj = cvx.Minimize(alpha)
prob = cvx.Problem(obj, constraints)
prob.solve(solver=cvx.SCS, max_iters=5000)

print prob.status
print np.linalg.eigvals(X.value) >= 0`

I have this script using the SCS solver, in this case it returns a matrix X and the status of problem is optimal, but when I find the eigenvalues of the matrix not all of them are non negatives. I cannot use the CVXOPT solver, some weird error with matrix shape. My version of cvxpy is 0.3.7, I have Anaconda 2.5.0 (64-bit) installed. Can anyone help??

**Comment by bodono** [comment]
This is because SCS has only 1e-3 tolerance by default, since it's designed to be a fast but low accuracy solver. I changed the call to:
```
prob.solve(solver=cvx.SCS, eps=1e-5)
```
and got (in 100 iterations) eigenvalues
```
[  1.27631350e-05   1.08974900e+00   2.17946467e+00   1.08974294e+00]
```
Lower values of eps will increase accuracy at the expense of more time required to get that accuracy.

**Comment by mesejo** [comment]
Thanks!! This solved the problem!!
