### ISSUE TITLE
Problems using CVXOPT solver

### ISSUE THREAD

**Issue by mesejo** [cvxgrp/cvxpy#263]
`import numpy as np
import cvxpy as cvx

n = 4
D = np.array([[1., 0., 0., 0.25], [0., 1., 0., 0.75], [0., 0., 1., 0.75], [0.25, 0.75, 0.75, 1.]])

alpha = cvx.Variable()
X = cvx.Semidef(n)

constraints = [D <= X, X <= alpha * D]

obj = cvx.Minimize(alpha)

prob = cvx.Problem(obj, constraints)
prob.solve(solver=cvx.CVXOPT)`

When trying to solve this throws the following:

Traceback (most recent call last):
  File "C:/python-projects/sdp-embedding/quick-test.py", line 18, in <module>
    prob.solve(solver=cvx.CVXOPT)
  File "C:\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 173, in solve
    return self._solve(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\cvxpy\problems\problem.py", line 279, in _solve
    kwargs)
  File "C:\Anaconda2\lib\site-packages\cvxpy\problems\solvers\cvxopt_intf.py", line 129, in solve
    if self.remove_redundant_rows(data) == s.INFEASIBLE:
  File "C:\Anaconda2\lib\site-packages\cvxpy\problems\solvers\cvxopt_intf.py", line 303, in remove_redundant_rows
    convert_scalars=True)
  File "C:\Anaconda2\lib\site-packages\cvxpy\interface\base_matrix_interface.py", line 52, in new_converter
    return converter(self, value)
  File "C:\Anaconda2\lib\site-packages\cvxpy\interface\cvxopt_interface\sparse_matrix_interface.py", line 53, in const_to_matrix
    return cvxopt.spmatrix(V, I, J, value.shape, tc='d')
TypeError: invalid array type

My version of cvxpy is 0.3.7, I have Anaconda 2.5.0 (64-bit) installed in Windows 7 (64-bit). Any ideas??

**Comment by SteveDiamond** [comment]
What version of cvxopt are you using? Can you do ``conda list`` and post the full output? Also show the output of executing ``cvxopt.__version__`` in Python.

**Comment by mesejo** [comment]
The version is 1.1.8. This is the result of conda list

# packages in environment at C:\Anaconda2:
#
alabaster                 0.7.7                    py27_0    <unknown>
anaconda                  2.5.0               np110py27_0    <unknown>
anaconda-client           1.2.2                    py27_0    <unknown>
argcomplete               1.0.0                    py27_1    <unknown>
astropy                   1.1.1               np110py27_0    <unknown>
babel                     2.2.0                    py27_0    <unknown>
backports-abc             0.4                       <pip>
backports.ssl-match-hostname 3.4.0.2                   <pip>
backports_abc             0.4                      py27_0    <unknown>
beautifulsoup4            4.4.1                    py27_0    <unknown>
bitarray                  0.8.1                    py27_1    <unknown>
blaze                     0.9.0                     <pip>
blaze-core                0.9.0                    py27_0    <unknown>
bokeh                     0.11.0                   py27_0    <unknown>
boto                      2.39.0                   py27_0    <unknown>
bottleneck                1.0.0               np110py27_0    <unknown>
bzip2                     1.0.6                     vc9_2  [vc9]  <unknown>
cdecimal                  2.3                      py27_1    <unknown>
cffi                      1.2.1                    py27_0    <unknown>
clyent                    1.2.0                    py27_0    <unknown>
colorama                  0.3.6                    py27_0    <unknown>
comtypes                  1.1.2                    py27_0    <unknown>
conda                     3.19.3                   py27_0    defaults
conda-build               1.19.0                   py27_0    <unknown>
conda-env                 2.4.5                    py27_0    defaults
configobj                 5.0.6                    py27_0    <unknown>
console_shortcut          0.1.1                    py27_1    <unknown>
cryptography              1.0.2                    py27_0    <unknown>
curl                      7.45.0                    vc9_1  [vc9]  <unknown>
cvxcanon                  0.0.23.3                  <pip>
cvxopt                    1.1.8                    py27_0    omnia
cvxpy                     0.3.7                     <pip>
cycler                    0.9.0                    py27_0    <unknown>
cython                    0.23.4                   py27_0    <unknown>
cytoolz                   0.7.5                    py27_0    <unknown>
datashape                 0.5.0                    py27_0    <unknown>
decorator                 4.0.6                    py27_0    <unknown>
dill                      0.2.5                     <pip>
docutils                  0.12                     py27_1    <unknown>
ecos                      2.0.4                     <pip>
enum34                    1.1.2                    py27_0    <unknown>
et-xmlfile                1.0.1                     <pip>
et_xmlfile                1.0.1                    py27_0    <unknown>
fastcache                 1.0.2                    py27_0    <unknown>
flask                     0.10.1                   py27_1    <unknown>
freetype                  2.5.5                     vc9_0  [vc9]  <unknown>
funcsigs                  0.4                      py27_0    <unknown>
futures                   3.0.3                    py27_0    <unknown>
gevent                    1.0.2                    py27_0    <unknown>
gevent-websocket          0.9.5                    py27_0    <unknown>
greenlet                  0.4.9                    py27_0    <unknown>
grin                      1.2.1                    py27_2    <unknown>
h5py                      2.5.0               np110py27_4    <unknown>
hdf5                      1.8.15.1                  vc9_4  [vc9]  <unknown>
idna                      2.0                      py27_0    <unknown>
ipaddress                 1.0.14                   py27_0    <unknown>
ipykernel                 4.2.2                    py27_0    <unknown>
ipython                   4.0.3                    py27_0    <unknown>
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_3    <unknown>
ipython-qtconsole         4.0.1                    py27_4    <unknown>
ipython_genutils          0.1.0                    py27_0    <unknown>
ipywidgets                4.1.1                    py27_0    <unknown>
itsdangerous              0.24                     py27_0    <unknown>
jdcal                     1.2                      py27_0    <unknown>
jedi                      0.9.0                    py27_0    <unknown>
jinja2                    2.8                      py27_0    <unknown>
jpeg                      8d                        vc9_0  [vc9]  <unknown>
jsonschema                2.4.0                    py27_0    <unknown>
jupyter                   1.0.0                    py27_1    <unknown>
jupyter-client            4.1.1                     <pip>
jupyter-console           4.1.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0    <unknown>
jupyter_console           4.1.0                    py27_0    <unknown>
jupyter_core              4.0.6                    py27_0    <unknown>
launcher                  1.0.0                         4    <unknown>
libpng                    1.6.17                    vc9_1  [vc9]  <unknown>
libsodium                 1.0.3                         0    <unknown>
libtiff                   4.0.6                     vc9_1  [vc9]  <unknown>
llvmlite                  0.8.0                    py27_0    <unknown>
lxml                      3.5.0                    py27_0    <unknown>
markupsafe                0.23                     py27_0    <unknown>
matplotlib                1.5.1               np110py27_0    <unknown>
menuinst                  1.3.2                    py27_0    defaults
mistune                   0.7.1                    py27_0    <unknown>
mkl                       11.3.1                        0    <unknown>
mkl-service               1.1.2                    py27_0    <unknown>
msvc_runtime              1.0.1                     vc9_0  [vc9]  defaults
multipledispatch          0.4.8                    py27_0    <unknown>
multiprocess              0.70.4                    <pip>
nbconvert                 4.1.0                    py27_0    <unknown>
nbformat                  4.0.1                    py27_0    <unknown>
networkx                  1.11                     py27_0    <unknown>
nltk                      3.1                      py27_0    <unknown>
node-webkit               0.10.1                        0    <unknown>
nose                      1.3.7                    py27_0    <unknown>
notebook                  4.1.0                    py27_0    <unknown>
numba                     0.23.1              np110py27_0    <unknown>
numexpr                   2.4.6               np110py27_1    <unknown>
numpy                     1.10.4                   py27_0    <unknown>
odo                       0.4.0                    py27_0    <unknown>
openpyxl                  2.3.2                    py27_0    <unknown>
pandas                    0.17.1              np110py27_0    <unknown>
path.py                   8.1.2                    py27_1    <unknown>
patsy                     0.4.0               np110py27_0    <unknown>
pep8                      1.7.0                    py27_0    <unknown>
pickleshare               0.5                      py27_0    <unknown>
pillow                    3.1.0                    py27_0    <unknown>
pip                       8.0.2                    py27_0    <unknown>
ply                       3.8                      py27_0    <unknown>
psutil                    3.4.2                    py27_0    <unknown>
py                        1.4.31                   py27_0    <unknown>
pyasn1                    0.1.9                    py27_0    <unknown>
pycosat                   0.6.1                    py27_0    defaults
pycparser                 2.14                     py27_0    <unknown>
pycrypto                  2.6.1                    py27_3    defaults
pyflakes                  1.0.0                    py27_0    <unknown>
pygments                  2.1                      py27_0    <unknown>
pyopenssl                 0.15.1                   py27_1    <unknown>
pyparsing                 2.0.3                    py27_0    <unknown>
pyqt                      4.11.4                   py27_4    <unknown>
pyreadline                2.1                      py27_0    <unknown>
pytables                  3.2.2               np110py27_1    <unknown>
pytest                    2.8.5                    py27_0    <unknown>
python                    2.7.11                        2    <unknown>
python-dateutil           2.4.2                    py27_0    <unknown>
pytz                      2015.7                   py27_0    <unknown>
pywin32                   219                      py27_2    <unknown>
pyyaml                    3.11                     py27_2    defaults
pyzmq                     15.2.0                   py27_0    <unknown>
qt                        4.8.7                     vc9_5  [vc9]  <unknown>
qtconsole                 4.1.1                    py27_0    <unknown>
requests                  2.9.1                    py27_0    defaults
rope                      0.9.4                    py27_1    <unknown>
scikit-image              0.11.3              np110py27_0    <unknown>
scikit-learn              0.17                np110py27_2    <unknown>
scipy                     0.17.0              np110py27_0    <unknown>
scs                       1.1.7               np110py27_1    omnia
setuptools                20.1.1                   py27_0    defaults
simplegeneric             0.8.1                    py27_0    <unknown>
singledispatch            3.4.0.3                  py27_0    <unknown>
sip                       4.16.9                   py27_2    <unknown>
six                       1.10.0                   py27_0    <unknown>
snowballstemmer           1.2.1                    py27_0    <unknown>
sockjs-tornado            1.0.1                    py27_0    <unknown>
sphinx                    1.3.5                    py27_0    <unknown>
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.9                    py27_0    <unknown>
spyder                    2.3.8                    py27_0    <unknown>
spyder-app                2.3.8                    py27_0    <unknown>
sqlalchemy                1.0.11                   py27_0    <unknown>
ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
statsmodels               0.6.1               np110py27_0    <unknown>
sympy                     0.7.6.1                  py27_0    <unknown>
tables                    3.2.2                     <pip>
tk                        8.5.18                    vc9_0  [vc9]  <unknown>
toolz                     0.7.4                    py27_0    <unknown>
tornado                   4.3                      py27_0    <unknown>
traitlets                 4.1.0                    py27_0    <unknown>
unicodecsv                0.14.1                   py27_0    <unknown>
werkzeug                  0.11.3                   py27_0    <unknown>
wheel                     0.29.0                   py27_0    defaults
xlrd                      0.9.4                    py27_0    <unknown>
xlsxwriter                0.8.4                    py27_0    <unknown>
xlwings                   0.6.4                    py27_1    <unknown>
xlwt                      1.0.0                    py27_0    <unknown>
zlib                      1.2.8                     vc9_2  [vc9]  <unknown>

cvxop.__version__ outputs:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'

Thanks in advance!!

**Comment by SteveDiamond** [comment]
Ok, it's actually
```
from cvxopt import info
print info.version
```
Also do 
```
import cvxpy
cvxpy.__version__
```
This is to verify you're actually using the version of Python you think you are. You would be surprised how often that's the problem.

**Comment by mesejo** [comment]
Ok, this is the output:

>>> from cvxopt import info
>>> info.version
'1.1.8'
>>> import cvxpy
>>> cvxpy.__version__
'0.3.7'

**Comment by SteveDiamond** [comment]
I fixed this issue and pushed a fixed version to pypi. I got appveyor CI working to test builds on windows, so hopefully there will be fewer windows issues in the future. I couldn't get Python 3 builds working on windows because there's no python 3 multiprocess conda package. If someone wanted to build a package that would be super helpful.
