### ISSUE TITLE
inexplicable behavior with sum_largest/sum_smallest

### ISSUE THREAD

**Issue by bison123** [cvxgrp/cvxpy#270]
i am trying to use sum_smallest in an application, but have found some odd behavior that i can't explain, and haven't found any examples of usage in the cvxpy examples. i start with some toy examples below which demonstrate the odd behavior i am seeing, and then show a more realistic example at the bottom demonstrating the issue i'm finding with reaching my real goal - portfolio optimization where we replace the variance term with a "shortfall" type term. is there something wrong with the way i'm using these functions?

thank you,

-Jesse

import numpy as np
import cvxpy

# generate some data, seed the random number generator for repeatability
np.random.seed(1)
t = 20
n = 2
rets = np.random.normal(0., 1., (t, n))
cov = np.cov(rets.T)

# set a matrix equal to the first row of rets and a bunch of zeros
alpha = rets[0, :]
alpha = np.vstack((alpha, 1e-6 * np.ones((t-1, len(alpha)))))

# compose variables and terms for the problem
x = cvxpy.Variable(n)
ret0 = alpha[0, :] * x
ret1 = cvxpy.sum_largest(alpha * x, 1)
ret2 = cvxpy.sum_largest(alpha * x, 2)
risk = cvxpy.quad_form(x, cov)

# start with a simple problem that we expect has an expected solution
objective = cvxpy.Maximize(0)
objective += cvxpy.Maximize(ret0)
objective += cvxpy.Maximize(-risk)
prob = cvxpy.Problem(objective)
prob.solve()

print('verify that ret0, ret1, and ret2 are all about the same value')
print('x: %s' % str(np.array(x.value).flatten()))
print('risk: %s' % str(risk.value))
print('ret0: %s' % str(ret0.value))
print('ret1: %s' % str(ret1.value))
print('ret2: %s' % str(ret2.value))

# if we add and subtract terms which are close, we can still solve the problem
objective = cvxpy.Maximize(0)
objective += cvxpy.Maximize(ret0)
objective += cvxpy.Maximize(-ret1)
prob = cvxpy.Problem(objective)
prob.solve()

print('can still find a solution when terms of objective function are close')
print('x: %s' % str(np.array(x.value).flatten()))
print('risk: %s' % str(risk.value))
print('ret0: %s' % str(ret0.value))
print('ret1: %s' % str(ret1.value))
print('ret2: %s' % str(ret2.value))

# but if we use the sum of the 2 largest, it fails
objective = cvxpy.Maximize(0)
objective += cvxpy.Maximize(ret0)
objective += cvxpy.Maximize(-ret2)
prob = cvxpy.Problem(objective)
prob.solve()

print('but when we use another term which should be close, solve fails as unbounded')
print('x: %s' % str(np.array(x.value).flatten()))
print('risk: %s' % str(risk.value))
print('ret0: %s' % str(ret0.value))
print('ret1: %s' % str(ret1.value))
print('ret2: %s' % str(ret2.value))

# and we can't replace ret0 with ret1 (or ret2) even though we know it should give about the same value
print('and when we replace the first term of objective with something that should give same result as first problem, we fail entirely')
objective = cvxpy.Maximize(0)
objective += cvxpy.Maximize(ret1)
objective += cvxpy.Maximize(-risk)
prob = cvxpy.Problem(objective)
try:
    prob.solve()
except:
    print('\tfails due to not following DCP rules?')

# and finally my real goal
import scipy.stats as stats
confidence_level = 0.75
scale = 1. / (1. - confidence_level) * stats.norm.pdf(stats.norm.ppf(1. - confidence_level))
terms = (1. - confidence_level) * t
risk1 = -cvxpy.sum_smallest(rets * x, 5) / terms / scale

objective = cvxpy.Maximize(0)
objective += cvxpy.Maximize(ret0)
objective += cvxpy.Maximize(-risk1)
prob = cvxpy.Problem(objective)
prob.solve()

print('my real goal fails as unbounded')
print('x: %s' % str(np.array(x.value).flatten()))
print('risk: %s' % str(risk.value))
print('risk1: %s' % str(risk1.value))
print('ret0: %s' % str(ret0.value))
print('ret1: %s' % str(ret1.value))
print('ret2: %s' % str(ret2.value))

# but we can verify that the size of term i'm trying to use is indeed about the same as the more conventional risk term
objective = cvxpy.Maximize(0)
objective += cvxpy.Maximize(ret0)
objective += cvxpy.Maximize(-risk)
prob = cvxpy.Problem(objective)
prob.solve()

print('but we can verify that the size of term i''m trying to use is indeed about the same as the more conventional risk term')
print('x: %s' % str(np.array(x.value).flatten()))
print('risk: %s' % str(risk.value))
print('risk1: %s' % str(risk1.value))
print('ret0: %s' % str(ret0.value))
print('ret1: %s' % str(ret1.value))
print('ret2: %s' % str(ret2.value))

**Comment by SteveDiamond** [comment]
Sorry for the slow response.  I'm in China right now so internet usage is a bit difficult.

If I understand correctly, you're trying to maximize objectives like
```
mu.T*x + sum_smallest(mu.T*x, k)
```
or 
```
mu.T*x + sum_largest(mu.T*x, k)
```
Wouldn't you just want ``x`` as large as possible? That's why the problem is unbounded. Maybe you mean 
```
mu.T*x - sum_largest(mu.T*x, k)
```
This isn't convex, but you can solve it with difference of convex programming as discussed here:
http://stanford.edu/~boyd/papers/cvx_ccv.html

**Comment by bison123** [comment]
Thank you for the response, yes, the problems I am trying to maximize are things like:
mu.T*x – sum_largest(R*x, k)
where mu is an nx1 vector and R is a txn matrix.

I took a look at the CCP algorithm in the paper you referenced, but I do not see how it helps as it doesn’t seem to change the convexity status of my objective. All algorithms in the paper http://stanford.edu/~boyd/papers/pdf/cvx_ccv.pdf start with a “convexification”. If I cast as a minimization and take g_0(x) = mu.T*x and f_0(x) = sum_largest(R*x, k), I believe the “convexification” of g_0 becomes g_hat(x,x_k) = g_0(x_k) + grad(g_0(x_k)).T * (x – x_k) = mu.T*x_k + mu.T*(x – x_k) = mu.T*x, and I’m right back where I started. I.e. it seems that “convexification” is just a linearization, but since I’m already using a linear function, I don’t see how applying this step changes the convexity status of my full objective? Further, I don’t know how to “convexify” sum_largest, so don’t know how I could cast using g = sum_largest, and so don’t see how to proceed from there.



Jesse Davis
Portfolio Manager
BLACKROCK
400 Howard Street
San Francisco, CA 94105
Jesse.Davis@Blackrock.com<mailto:Jesse.Davis@Blackrock.com>

**Comment by SteveDiamond** [comment]
I see. There's nothing wrong with maximizing
```
mu.T*x – sum_largest(R*x, k)
```
since that's concave. I think you just chose an R such that the objective was unbounded.

For the convex concave procedure, I meant that if you're maximizing the convex function
```
mu.T*x – sum_smallest(R*x, k)
```
then you should linearize ``sum_smallest(R*x, k)`` by taking the subgradient. But it sounds like that's not necessary.
