### ISSUE TITLE
Make a product along axis?

### ISSUE THREAD

**Issue by yarmenti** [cvxgrp/cvxpy#272]
Hello,

I would like to compute the solution of the following convex optimization problem:

\begin{equation}
\inf_{m \in \mathbb{R}^d} \left\{ <m, 1> | \mathbb{E} ( f(X-m) ) \leq c \right\}
\end{equation}

for some $c \in \mathbb{R}$, some function $f : \mathbb{R}^d \mapsto \mathbb{R}$ increasing convex.

The simplest way I found to use cvxpy is to compute my constraints by Monte-Carlo methods. The problem I found is that it is impossible for me to make some convex dependence of my random variables.

Indeed, the case where $f(x) = \sum_{1 \leq j <k \leq d} x_j^+ \times x_k^+$ seems to be non DCP. As product of monotonic and positive functions of my variable, I should expect it would work, am I wrong?

As I couldn't find a function which make a product along axis, I used the following snippet of code but couldn't make it work.

```
N = 2
Mu = numpy.zeros(N)
Sigma = numpy.array([[1., 0.], [0., 1.]])
alpha = 1.

rv = scipy.stats.multivariate_normal(mean=Mu, cov=Sigma)
X = rv.rvs(size=M)

m = cvx.Variable(N)

expr_x_minus_m = [X[:, i] - m[i] for i in range(N)]

correl_expr = []
for k in range(N):
    for j in range(k):
        expr_xk_minus_m_pos = cvx.pos(expr_x_minus_m[k])
        expr_xj_minus_m_pos = cvx.pos(expr_x_minus_m[j])

        # No "mult. along axis" operator
        expr_prod_vec = cvx.log(expr_xk_minus_m_pos) + cvx.log(expr_xj_minus_m_pos)
        expr_prod_vec = cvx.sum_entries(expr_prod_vec, axis=1)
        expr_prod_vec = cvx.exp(expr_prod_vec)

        expr_h_jk = cvx.sum_entries(expr_prod_vec) / M

        correl_expr.append(alpha * expr_h_jk)

expr = sum(correl_expr)
```

When solving, it says me that it is non DCP. How can I make it work?

Thanks,

**Comment by SteveDiamond** [comment]
Your function is not convex. You can see that $0 = 1/2 f(1,0) +1/2  f(0,1) < f(1/2,1/2) = 1/4$, which violates the definition of convexity. If you assume $x_1,..,x_n > 0$, your problem would be convex with the change of variables $y_i = \log x_i$. Then $f(x_1,...,x_n) = e^{y_1 + ... + y_n}$.

**Comment by yarmenti** [comment]
Good point... Thank you.
