### ISSUE TITLE
Using kl_dev as an elementwise function

### ISSUE THREAD

**Issue by scalizzi1** [cvxgrp/cvxpy#273]
Hi,
I am having problems using kl_dev on two length n variables. I want it to return an array of length n i.e.

import numpy as np
from cvxpy import *

n=5

X=Variable(n)
Y=Variable(n)
R=kl_dev(X,Y)

so that R is an array of length n, containing the elementwise operation of kl_dev on X,Y. When I do this python returns an error saying arguments of kl_dev must resolve to a scalar, however it is listed as an elementwise function on the cvxpy website. (We did the same thing with log and it worked fine)

Any help is much appreciated!

**Comment by SteveDiamond** [comment]
I listed kl_div as elementwise, but it actually wasn't implemented elementwise. I've changed it now in a new release on pypi so that your code should work.
