### ISSUE TITLE
where can I get the parsed form of original problem?

### ISSUE THREAD

**Issue by wangdingkang** [cvxgrp/cvxpy#275]
Hi, 
I'm trying to use scs directly in c++, but I got stuck in parsing a dual problem into primal form. 

My SDP problem is like having a 2 * 2 positive semidefinite matrix X, I have some linear constraints on the entries, e.g., X[0, 0] >= 2. I used cvxpy in python, it's pretty convenient, I know it can parse my problem into a primal form for scs solver, so can I get the parsed form and how?

Thanks.

**Comment by SteveDiamond** [comment]
Is this what you mean?
http://www.cvxpy.org/en/latest/tutorial/advanced/index.html#getting-the-standard-form

**Comment by mwytock** [comment]
Checkout https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/problem.py#L188

e.g.

prob = Problem(...)
prob_data = prob.get_problem_data()

**Comment by mwytock** [comment]
oh fancy - documentation! :)

**Comment by wangdingkang** [comment]
Oh..yeah, that's what I'm looking for. I should've read the tutorial more carefully, thank you all.
