### ISSUE TITLE
infeasibility certificate

### ISSUE THREAD

**Issue by ProgVal** [cvxgrp/cvxpy#276]
At least SCS returns a certificate of infeasibility, which one can see with `problem.solve(verbose='True', solver='SCS'). Unfortunately, it is impossible (or at least hard) to use it, as it is only for the problem transformed by CVXPY.
It would help a lot if CVXPY could convert the certificate so it uses variables of the original problem.

**Comment by SteveDiamond** [comment]
What would you do with the certificate? I'm hesitant to attach values to variables when the problem wasn't solved, since people will assume it was.

**Comment by ProgVal** [comment]
I would use it to debug my problem, because it is not supposed to be unbounded.

I don't think assigning values to variables would be a solution anyway, because certificates are not instantiations of variables.
For instance with linear programs, a certificate is a half-line.

**Comment by SteveDiamond** [comment]
I see. I'll think about ways to return a direction of unboundedness.

**Comment by ProgVal** [comment]
thanks!

**Comment by ProgVal** [comment]
Actually, I mixed up two things here: infeasability and unboundedness.
I am mostly interested in infeasability certificates, but I guess unboundedness one could be useful to someone else too

**Comment by KerimovEmil** [comment]
One of the ways someone would use this to help diagnose the problem can be found in this paper: 
"How to use Farkas’ lemma to say something important about infeasible linear problems."
Author: Erling D. Andersen, MOSEK ApS
link: http://docs.mosek.com/whitepapers/infeas.pdf
