### ISSUE TITLE
Functions for Matrix Exp,Log and Quantum Relative Entropy Divergence

### ISSUE THREAD

**Issue by bschreck** [cvxgrp/cvxpy#278]
I'm wondering if it would be possible to implement these. There are elementwise versions of exp, log, and kl-div, and some problems in machine learning (specifically online matrix factorization) require the matrix generalizations of them. For instance, see: http://arxiv.org/pdf/1204.0136.pdf

The exp and log are available in scipy.linalg. QRED is tr(XlogX - XlogA - X + A), where in these problems A is fixed from the previous step, and the gradient with respect to X is logX - logA.

I can try to do it- I'm not quite sure what the graph_implementation method is doing for Atoms though.

**Comment by SteveDiamond** [comment]
This sounds reasonable. The graph_implementation method rewrites the atom as partial optimization over a cone program (see this paper for examples https://stanford.edu/~boyd/papers/pdf/graph_dcp.pdf). All atoms in CVXPY need this method implemented.

**Comment by bschreck** [comment]
Okay cool I'll check back in if I get it working or can't figure out the graph_implementation

**Comment by bschreck** [comment]
Steve - in that paper it says that these types of functions can't be represented by SQLP. Is it still true that cvxpy only uses SQLP underneath or are there smooth solvers as well? Quoting:

"Key omissions include logarithms, exponentials, and entropy; such functions simply cannot be exactly represented in an SQLP solver"

**Comment by SteveDiamond** [comment]
There's also an exponential cone, supported by ECOS and SCS:
https://github.com/embotech/ecos
You can use it to represent logarithms, exponentials, entropy, etc.

**Comment by SteveDiamond** [comment]
Sorry, what exactly does ``Xlog(X)`` mean? Is this the same as ``-entr(X)`` in cvxpy?

**Comment by bschreck** [comment]
No logX as in the matrix logarithm, so U*log(Sigma)*V^T. Log of the singular values. And then matrix multiply X*logX. It's the matrix generalization of entropy

**Comment by SteveDiamond** [comment]
Ok, you might want to write an atom for tr(X*log(X)) because I expect f(X) = X*logX is convex with respect to the PSD cone, i.e., ``f(theta*X + (1-theta)*Y) << theta*f(X) + (1-theta)*f(Y)``. This can't really be expressed in cvxpy right now. Check out the log_det atom for inspiration.

**Comment by bschreck** [comment]
Yeah I'm pretty sure it's convex. I'll check out log_det

**Comment by SteveDiamond** [comment]
I'm closing this. Feel free to reopen it when you make more progress on adding the functions.

**Comment by aarongrisez** [comment]
@SteveDiamond, I have a very similar situation to @bschreck (looking at entropic quantities in Quantum Mechanics) and I was wondering if anyone knows about implementations of this sort of thing. Specifically looking for matrix logarithm and matrix square root.

**Comment by rileyjmurray** [comment]
@aarongrisez Fawzi, Saunderson, and Parillo have a paper on semidefinite approximations of the matrix logarithm (https://arxiv.org/abs/1705.00812). I believe there is some kind of prototype implementation for this method which connects to CVX in MATLAB. Unfortunately such features are a long way off from being integrated into cvxpy (or any Python-based optimization platform, for that matter).
