### ISSUE TITLE
Matlab CVX vs. CVXPY

### ISSUE THREAD

**Issue by shawnwen** [cvxgrp/cvxpy#279]
Is there any tools to translate the convex optimization code into the pythonic (coded in CVXPY)?

**Comment by SteveDiamond** [comment]
No, you need to do this by hand. If you understand NumPy and only use CVXPY functions on CVXPY objects (http://www.cvxpy.org/en/latest/faq/index.html#can-i-use-numpy-functions-on-cvxpy-objects) it should be easy.
