### ISSUE TITLE
What is ECOS_BB?

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#281]
At www.cvxpy.org/en/latest/tutorial/advanced/index.html, the links for ECOS and ECOS_BB are the same: https://www.embotech.com/ECOS, but I don't see anything about  ECOS_BB at that website.

**Comment by sschnug** [comment]
ECOS_BB is the branch-and-bound variant of ECOS which can solve models containing integers.
See [here](https://github.com/embotech/ecos#mixed-integer-socps-ecos_bb)!

It is a very simple implementation and will not be very fast for huge models.

**Comment by SteveDiamond** [comment]
Good point, I changed the link for ECOS_BB so it's clearer what it is.
