### ISSUE TITLE
functoolz memoize leaking memory in python3

### ISSUE THREAD

**Issue by mwytock** [cvxgrp/cvxpy#283]
See https://github.com/cvxgrp/CVXcanon/issues/23 for context - removing the memoize annotations in atom.py fixes the issue.

Perhaps use functools.lru_cache in python3? 

Also, we should probably add some tests to catch memory leaks as it seems to come up from time to time...

**Comment by SteveDiamond** [comment]
Are we sure the memory leak isn't in Python 2 as well? Maybe I should just remove the memoize annotations.

**Comment by mwytock** [comment]
would be good to have a second look, but it didnt seem to effect python2

in theory if you memoize a member function, i would think the cache should
be deleted when the object goes out of scope. that doesnt seem to be
happening in python3 for some reason and looking at the memoize code it
seems rather complex

**Comment by SteveDiamond** [comment]
I switched from toolz.memoize to fastcache.cru_cache, which works in python 2.7 and python 3. @ihwang try installing cvxpy from source now and see if the memory leak is still there.

**Comment by ihwang** [comment]
Thanks for your attention to this matter! Sorry for the basic question, but how precisely do I install from source? I just tried cloning from git@github.com:cvxgrp/cvxpy.git, but got the following:
`Permission denied (publickey).
fatal: Could not read from remote repository.`

**Comment by mwytock** [comment]
git clone https://github.com/cvxgrp/cvxpy

**Comment by ihwang** [comment]
Thanks! Okay, now when I attempt to run the test script with the heap profiler, it's having trouble finding some modules:
```
Starting tracking the heap
Traceback (most recent call last):
  File "scripts/test.py", line 3, in <module>
    from cvxpy import *
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/__init__.py", line 21, in <module>
    from cvxpy.atoms import *
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/atoms/__init__.py", line 20, in <module>
    from cvxpy.atoms.affine_prod import affine_prod
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/atoms/affine_prod.py", line 20, in <module>
    from cvxpy.atoms.atom import Atom
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/atoms/atom.py", line 30, in <module>
    from fastcache import clru_cache
ImportError: No module named 'fastcache'
Dumping heap profile to /tmp/.0001.heap (Exiting)
```

**Comment by SteveDiamond** [comment]
Yes, you have to install fastcache. That's a dependency now.

**Comment by ihwang** [comment]
With fastcache, everything looks good--memory usage hovers around 9 MB with no memory leaks. Thanks guys!

**Comment by mwytock** [comment]
awesome!
