### ISSUE TITLE
Optimal yet slightly infeasible solutions

### ISSUE THREAD

**Issue by nkoep** [cvxgrp/cvxpy#286]
This is in reference to pull request https://github.com/cvxgrp/cvxpy/pull/285. I'm currently trying to solve problem (1.3) from the paper "One-bit compressed sensing by linear programming" by Yaniv Plan and Roman Vershynin (https://arxiv.org/abs/1109.4299), but I'm (almost) always getting slightly infeasible solutions.

In short, I'm taking a linear transform of a vector, record the signs and then solve a program to minimize the l1-norm of the signal vector subject to a sign consistency constraint that forces the solution to exhibit the same sign pattern as my original vector if transformed by the same matrix and projected on the boolean cube.

Here's a reference implementation of the experiment as well as an example log: https://gist.github.com/nkoep/6b4992df69b336ff237f4bcfb9eb4f3b. The constraint in question is on line 17. Line 53 prints a feasibility check of the constraint. As you can see from the log, there's a bunch of negative entries in the left-hand side of the constraint. This seems to be a tolerance/precision issue though since all entries in question are rather small (on the order of 1e-12 to 1e-13).

With https://github.com/cvxgrp/cvxpy/pull/285 in place I played around with some of MOSEK's internal parameters (see http://docs.mosek.com/7.0/toolbox/Parameters.html), but so far nothing I tried seemed to make any difference, and quite frankly, I got a bit lost in the sea of different parameters. I've solved the same problem with ECOS before but wanted to switch to MOSEK for a large-scale simulation. However, while ECOS generally returns actually feasible solutions more often, that's also not always the case. Could anyone point me to the correct parameter(s) I need to tune to avoid this issue?

**Comment by SteveDiamond** [comment]
This is feasible within numerical tolerance. You can't expect higher precision than 1e-12, no matter what parameters you choose.

If the tiny negative values due to inherent numerical imprecision are an issue, I'd suggest setting the constraint to ``odot >= EPS``. Here EPS is the smallest value such that ``odot >= 0`` holds exactly.
