### ISSUE TITLE
ImportWarning when using Elemental v0.85

### ISSUE THREAD

**Issue by shadowleaves** [cvxgrp/cvxpy#288]
CVXPY ver 0.4.2, Elemental v0.85, mpich-3.2, on CentOS 7, and tested "import El" with no warnings or errors.
however when solving linear prog using cvxpy.ELEMENTAL I got the following:

"Not importing directory '/home/hyan/miniconda2/envs/algo/lib/python2.7/site-packages/El/core/environment': missing __init__.py"

warning will be gone if silencing ImportWarning. after that, I got an error when solving:
'module' object has no attribute 'WorldSize'

it seems that the problem is the following code in cvxpy/cvxpy/problems/solvers/elemental_intf.py:
line 165:       worldSize = El.mpi.WorldSize()

and looks like dir(El.mpi) does not contain the "WorldSize" function, only "WorldRank" and "Size". but I do see a WorldSize() function defined in Elemental's bleeding-edge code. Is this a version issue?

**Comment by SteveDiamond** [comment]
That's right, you need Elemental v0.86. v0.85 doesn't have an interior point solver, so the cvxpy interface wouldn't do anything even if all the APIs matched up.

**Comment by poulson** [comment]
Sorry. I have been selfishly adding features instead of packaging up releases. There is growing dissent for this reason (here)[https://gitter.im/elemental/chat#utm_source=notification&utm_medium=email&utm_campaign=unread-notifications] if you want to add your voice.
