### ISSUE TITLE
Is it possible to count non-zero entries in a vector?

### ISSUE THREAD

**Issue by davidia** [cvxgrp/cvxpy#289]
Hello, Is there any way to do something like

    sum_entries( sign(  abs(x) ) )  <= N

Apologies if this is an obvious question

Thanks!

**Comment by sschnug** [comment]
Hi,

non-expert here:

I think this is quite hard to do in a convex setting, as outlined [here](http://web.stanford.edu/class/ee364b/lectures/l1_slides.pdf). 

There is also a [card-formulation](https://github.com/cvxgrp/cvxpy/blob/master/examples/extensions/mixed_integer/card.py) in some of cvxpy's extensions (it might be available in more extensions, depending on the methods used to solve it; MIP, non-convex heuristics...)

Sascha

**Comment by davidia** [comment]
I suspected as much. Thank you very much for the help and the links.
