### ISSUE TITLE
wish: remove "multiprocess" from cvxpy requirements 

### ISSUE THREAD

**Issue by stonebig** [cvxgrp/cvxpy#296]
Because of multiprocess, cvxpy depends on pyreadline, which is a problem on Windows.

Would it be possible to change that (like Jupyter project did) ?

 ````
No matching distribution found for pyreadline>=1.7.1 (from dill>=0.2.5->multiprocess->cvxpy)
````

**Comment by SteveDiamond** [comment]
Can you install multiprocess on Windows via "conda install -c cvxgrp multiprocess"?

**Comment by stonebig** [comment]
I'm not using conda. "pyreadline-2.1.win-amd64.exe" would be the workaround, that I wish to avoid.

**Comment by SteveDiamond** [comment]
The only officially supported installation methods for windows are Anaconda and Python(x,y). You could install from source and manually remove the multiprocess dependency. It's not really important.

**Comment by stonebig** [comment]
I see. Wouldn't "joblib" be a possible replacement ? joblib is not a problem on  windows

**Comment by SteveDiamond** [comment]
Unfortunately joblib won't work because I need to pickle functions, which only multiprocess can do. The whole dependency on multiprocess is a bit annoying. For cvxpy 1.0 I'll try and switch to joblib.

**Comment by RoyiAvital** [comment]
@SteveDiamond ,
Could you reconsider?
@stonebig is running very popular Python Distribution for Windows ([WinPython](https://github.com/winpython/winpython)) and this is a blocker for having CVXPY inside it.

Thank You.

**Comment by SteveDiamond** [comment]
I could make multiprocess optional, with features disabled if it's not
installed. I'm not opposed to that. That's how all the solvers work now.
