### ISSUE TITLE
An unhandled exception when calling gurobi solver

### ISSUE THREAD

**Issue by maxwellmao** [cvxgrp/cvxpy#297]
Hi,

I am solving my convex optimization problem with cvxpy via calling gurobi solver. However, I come across the following exception. I do not name the variable as "y". Does anyone know where results_dict["y"] comes from? Or, how to fix it?

In addition, I also received a warning about the failure of inaccurate barrier solution. Does anybody have any suggestion for improving it?

Thanks.

Here are outputs I got after called prob.solve(solver='GUROBI', verbose=True):

> Barrier solved model in 22 iterations and 0.09 seconds
> Optimal objective 4.18131886e+02

> Warning: failed to compute QCP dual solution due to inaccurate barrier solution
         Try decreasing BarQCPConvTol for more accuracy

Traceback (most recent call last):
  File "label_infer.py", line 187, in <module>
    main(args)
  File "label_infer.py", line 184, in main
    g.learning_via_opt(args.norm, args.out)
  File "label_infer.py", line 143, in weight_learing_via_opt
    prob.solve(solver='GUROBI', verbose=True)
  File "/usr/local/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 195, in solve
    return self._solve(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 321, in _solve
    kwargs)
  File "/usr/local/lib/python2.7/site-packages/cvxpy/problems/solvers/gurobi_intf.py", line 295, in solve
    return self.format_results(results_dict, data, cached_data)
  File "/usr/local/lib/python2.7/site-packages/cvxpy/problems/solvers/gurobi_intf.py", line 443, in format_results
    new_results[s.EQ_DUAL] = results_dict["y"][0:dims[s.EQ_DIM]]
KeyError: 'y'

**Comment by SteveDiamond** [comment]
Can you post a minimal working example that triggers this error?

**Comment by maxwellmao** [comment]
I think this error is input dependent.

My problem is simple, Minimize(sum_squares(L-Y*W)+a*norm(W, 2.0)). When I randomly generate "L", "Y", and "a", it works. However, it raises the above exception when solving the problem on my dataset.

**Comment by SteveDiamond** [comment]
Ok, can you run this under the debugger and print out "results_dict" and also "model.status" in the solve method?

**Comment by maxwellmao** [comment]
I ran it under the debugger, and find some error in /usr/local/lib/python2.7/site-packages/cvxpy/problems/solvers/gurobi_intf.py. 

There is no key of 'y' in results_dict. The reason is, it raises GurobiError: GurobiError() when it tries to access lc.QCPi at line 280, which is before the assignment statement for results_dict['y']. Currently, there is no handler for this exception. However, results_dict["status"] is 'optimal' at line 293. Do you have any idea about the exception when accessing lc.QCPi at line 280?

> 267         try:
> 268             model.optimize()
> 269             results_dict["primal objective"] = model.ObjVal
> 270             results_dict["x"] = np.array([v.X for v in variables])
> 271 
> 272             # Only add duals if not a MIP.
> 273             # Not sure why we need to negate the following,
> 274             # but need to in order to be consistent with other solvers.
> 275             if not self.is_mip(data):
> 276                 vals = []
> 277                 for lc in gur_constrs:
> 278                     if lc is not None:
> 279                         if isinstance(lc, gurobipy.QConstr):
> 280                             vals.append(lc.QCPi)
> 281                         else:
> 282                             vals.append(lc.Pi)
> 283                     else:
> 284                         vals.append(0)
> 285                 results_dict["y"] = -np.array(vals)
> 286         except:
> 287             pass
> 289         results_dict["model"] = model
> 290         results_dict["variables"] = variables
> 291         results_dict["gur_constrs"] = gur_constrs
> 292         results_dict["status"] = self.STATUS_MAP.get(model.Status,
> 293                                                      s.SOLVER_ERROR)

**Comment by SteveDiamond** [comment]
I need to see the output of ``model.Status``. ``results_dict["status"]`` stores the output of ``self.STATUS_MAP.get(model.Status, s.SOLVER_ERROR)``, but I need to know the input.

**Comment by maxwellmao** [comment]
The output of model.Status is 2. I have two inputs, where Y is a matrix with the size of 1000*12, and L is a matrix with the size of 1000*1. Shall I send them to you via email?

**Comment by SteveDiamond** [comment]
Try running it with the latest code on master. If that doesn't work, you should email me the matrix data.

**Comment by maxwellmao** [comment]
I update it to 0.4.5. It returns "solver_error" now. 

BTW, do you have any idea about the warning:
```
Warning: failed to compute QCP dual solution due to inaccurate barrier solution
         Try decreasing BarQCPConvTol for more accuracy
```

**Comment by SteveDiamond** [comment]
Try decreasing BarQCPConvTol :)? The warning means that Gurobi had trouble computing the dual values. You probably don't need dual values so just set BarQCPConvTol or whatever to a very high value.

**Comment by maxwellmao** [comment]
Got it. Thanks!

**Comment by Santos2393** [comment]
> I update it to 0.4.5. It returns "solver_error" now.
> 
> BTW, do you have any idea about the warning:
> 
> ```
> Warning: failed to compute QCP dual solution due to inaccurate barrier solution
>          Try decreasing BarQCPConvTol for more accuracy
> ```

I am getting the same error, how to fix this? I need dual variables.
