### ISSUE TITLE
Error with semidefinite programming: TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by Zlinki** [cvxgrp/cvxpy#299]
Hello. I am trying to implement the semidefinite convex program in the paper
"Robust Support Vector Machine Training via Convex Outlier Ablation". 

I try to implement the convex problem with cvxpy.  My implementation is the following:

#toy example
n_samples=4
X= numpy.matrix([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
Y=numpy.matrix((1,1,-1,-1),None).T
e=numpy.matrix(numpy.ones(4),None).T
M=cvx.Variable(n_samples,n_samples)
n=cvx.Parameter(n_samples)
a=e
v=cvx.Variable(n_samples)
z=cvx.Variable(n_samples)
w=cvx.Variable(n_samples)
G = hardprod(X.T*X,Y*Y.T)
A = cvx.mul_elemwise(G,n*n.T)
B = (n+v-w)
delta = n.T*(a-e)-0.5*a.T*A*a
C= 2*(delta-w.T*e+n.T*e)
S1 = cvx.hstack(A,B)
S2 = cvx.hstack(B.T,C)
S= cvx.vstack(S1,S2)
constraints = [n >= 0, n <= 1 , v >= 0, w >= 0, M-n*n.T>>0, S>>0]            
obj = cvx.Minimize(delta)
prob = cvx.Problem(obj, constraints)        
prob.solve()

However , i get the following error::
 46         """Applies the binary operator to the values.
     47         """
---> 48         return reduce(self.OP_FUNC, values)
     49 
     50     def sign_from_args(self):

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float' 

Any suggestions?

note: hardprod is a function i define to multiply two matrices component by component. Notice i dont use it con cvxpy objects. Just on numpy objects.

**Comment by SteveDiamond** [comment]
I don't see you ever assigning a value to ``n``. That would cause an error of some kind.

**Comment by Zlinki** [comment]
Hello! thanks for replying. I noticed im making a lot of mistakes. Among those is that n should be a Variable and not a parametter. Gonna keep working. Thank you!

**Comment by Zlinki** [comment]
Hello again. I've been able to fix all the mistakes. However, there is a constraint i haven't been able to use.

Suppose M is a positive definite matrix: M = cvxpy.Semidef(n). and b= Variable(n) with b>=0 .

I want to add the constraint M>>b*b.T, where T is the transpose  operation.  b. b*T should be a n times n semipositive definite matrix since  b>=0 . Therefore, the constraint M>>b*b.T should be convex, 
and (M>>b*b.T).is_dcp() should be true. It is false, however. I undestand that cvxpy doesnt like multiplication of two non constant terms since it is non convex. However it is in this case. Is there a way to tell cvxpy to ignore the dcp rule for this constraint?

Thanks for your time!!!

**Comment by SteveDiamond** [comment]
You can use the Schur complement to make an equivalent (but DCP) constraint: ``cvxpy.bmat([[M, b], [b.T, 1]]) >> 0``
