### ISSUE TITLE
ECOS crashes where cvxopt succeeds

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#301]
Can anyone tell me what's happening here?

import numpy as np
import cvxpy as cvx

if __name__=='__main__':
  K,N=2,3
  p=cvx.Variable(K,N)
  g=cvx.Parameter(K,N,sign='positive')
  g.value=2*np.ones((K,N))
  objective=cvx.Maximize(cvx.sum_entries(cvx.log1p(cvx.mul_elemwise(g,p))))
  constraints=[p>=0.0,p<=1.0]
  problem=cvx.Problem(objective,constraints)
  opt_value=problem.solve(solver=cvx.CVXOPT)
  print('status:',problem.status)
  print('optimal value=%g'%problem.value)
  print('optimal p=\n',p.value)
  opt_value=problem.solve(solver=cvx.ECOS)
  print('status:',problem.status)
  print('optimal value=%g'%problem.value)
  print('optimal p=\n',p.value)

status: optimal
optimal value=6.59167
optimal p=
 [[ 1.  1.  1.]
 [ 1.  1.  1.]]
Traceback (most recent call last):
  File "./try_Anas_vectoring_00.py", line 19, in <module>
    opt_value=problem.solve(solver=cvx.ECOS)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 173, in solve
    return self._solve(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 279, in _solve
    kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/solvers/ecos_intf.py", line 124, in solve
    **solver_opts)
  File "/usr/local/lib/python3.4/dist-packages/ecos.py", line 62, in solve
    return _ecos.csolve((m,n1,p), c, data, indices, colptr, h, dims, A.data, A.indices, A.indptr, b, **kwargs)
ValueError: Number of rows of G does not match dims.l+sum(dims.q)

**Comment by SteveDiamond** [comment]
What version of ecos and cvxpy do you have? Try reinstalling both.

**Comment by keithbriggs** [comment]
Thanks - the upgrade fixed it.

Another thing:
      constraints.append(cvx.log1p(gp[k,i])<=M) 

gives me a "cvxpy.error.DCPError: Problem does not follow DCP rules", whereas

      constraints.append(1.0+gp[k,i]<=cvx.exp(M))

which should be equivalent, works perfectly.

**Comment by SteveDiamond** [comment]
Yes,  see my answer in #302
