### ISSUE TITLE
equivalent constraints - nonequivalent behaviour

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#302]
import cvxpy as cvx

x=cvx.Variable()
objective=cvx.Maximize(x)
constraints=[x>=0.0,1.0+x<=cvx.exp(1.0),]
problem=cvx.Problem(objective,constraints)
problem.solve(solver=cvx.CVXOPT)
print('status:',problem.status)
print('optimal value=%g'%problem.value)

x=cvx.Variable()
objective=cvx.Maximize(x)
constraints=[x>=0.0,cvx.log1p(x)<=1.0,]
problem=cvx.Problem(objective,constraints)
problem.solve(solver=cvx.CVXOPT)
print('status:',problem.status)
print('optimal value=%g'%problem.value)

status: optimal
optimal value=1.71828

Traceback (most recent call last):
  File "./cvxpy_log_bug.py", line 18, in <module>
    problem.solve(solver=cvx.CVXOPT)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 173, in solve
    return self._solve(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/cvxpy/problems/problem.py", line 247, in _solve
    raise DCPError("Problem does not follow DCP rules.")
cvxpy.error.DCPError: Problem does not follow DCP rules.

**Comment by SteveDiamond** [comment]
This is an interesting example! The answer is that ``x <= e`` is DCP, but ``log1p(x)<=1.0`` is not DCP (dcp.stanford.edu). DCP depends on how functions/constraints are described, so you can have mathematically equivalent constraints such that one is DCP and the other is not.

**Comment by keithbriggs** [comment]
This creates a problem in my application - exp(x) can overflow, while log1p(x) is moderately sized.  Can this be fixed by changing the convexity rules for log1p?

**Comment by sschnug** [comment]
Until Steven might give you a proper response:

This is probably non-trivial.
Always remember, that:
 - The DCP ruleset is a set of sufficient, but not necessary, conditions for convexity
 - The general problem of recognizing convexity of some general expression is NP-hard

While there might be some possible additions (hardcoded rules) to the library which will work for your case, there will always be other cases.

DCP helps a lot, but does not adopt all of the user's responsibility in regards to clever formulations.

Regarding your problem:
It's unclear to me where or how exactly the possiblilty of some overflow is a problem. If it's only connected to the decision-variables then it's probably a problem only relevant for the solver and it might be hard to recognize which formulation will have what kind of effects using solver X.

These kind of questions howewer are more suited for [cvxpy's google-group](https://groups.google.com/forum/#!forum/cvxpy) (keeping the issue-box for obvious bugs/problems).

**Comment by SteveDiamond** [comment]
I agree with everything @sschnug said. Perhaps you could do a change of variables and frame the problem in terms of ``y = log1p(x)``? You could also keep your non-DCP formulation and use the DCCP package to solve it.
