### ISSUE TITLE
Set the object as a self-defined function

### ISSUE THREAD

**Issue by RockTower** [cvxgrp/cvxpy#306]
I want to optimize over a piecewise convex function so it will contain if statement in my function, is it possible to set it as object?
BTW, how to include exponential function as part of the object? cvx.exp seems doesn't work.
Thanks!

**Comment by sschnug** [comment]
This is a type of question which is more suitable for the [google-group](https://groups.google.com/forum/#!forum/cvxpy) as it's not about a bug/issue with library directly.

Some remarks:

- You can't use some arbitrary python-object for building constraints/objectives (opposed to e.g. scipy.optimize). Everything needs to be build from the core-functions within cvxpy as some hardcoded facts are needed to reason about convexity and co
- Of course you can build your own piecewise-convex-function as cvxpy supports binary/integer-variables
 - But you have to do this yourself (no built-in support)
 - Consider reading some basic MIP-formulation texts on how to do this
 - It might be a bit cumbersome without SOS-constraints which are not supported as well (i think)
- I'm not sure what you are asking about ```cvx.exp```
 - Of course, ```cvx.exp``` can only be used on cvxpy's expressions (same arguments as above)

**Comment by SteveDiamond** [comment]
@sschnug is exactly right. You can't define your own functions in cvxpy.

**Comment by RockTower** [comment]
@sschnug I know MIP could form a piecewise linear function, but for general piecewise convex function, for example a quadratic function connected with a linear function, I'm not sure how to do it by MIP (don't really want to use linear approximation). If that's the case, do you mean scipy.optimize is my only choice? Thanks!

**Comment by SteveDiamond** [comment]
@RockTower the approach for a general piecewise convex is essentially the same as for piecewise linear. For example, suppose we have the constraint x in [0,100] and the objective 
```
          {b_0 + f_0(x)  for 0 <= x < 10,
g(x) = {b_0 + f_0(10) + f_1(x)  for 10 <= x <= 100
          {\infty for x not in [0,100].
```
where f_0 and f_1 are convex. Then we write the problem
```
minimize b_0 + f_0(z_0) + f_1(z_1)
subject to   10y_1 <= z_0 <= 10y_0
                    0 <= z_1 <= 90y_1
                    x = z_0 + z_1
                    y_0, y_1 \in {0,1}
```

**Comment by RockTower** [comment]
Thanks!
