### ISSUE TITLE
Return solution on extreme point of LP

### ISSUE THREAD

**Issue by RockTower** [cvxgrp/cvxpy#307]
When solution is not unique, I'm wondering is it possible to return the extreme solution of an LP? Any one is fine for me. Thanks! 
(technically I can construct another LP based on the solution and solve it again over a random direction to do that, but kind of lazy...)

**Comment by SteveDiamond** [comment]
This is an interesting suggestion. I wouldn't make this the default, but it could be a solver option. If you use a pure LP/MILP solver like Cbc, GLPK, GUROBI, etc., you'll get an extreme point even with the current set up.
