### ISSUE TITLE
I want to make my constraints flexible by passing extreme values

### ISSUE THREAD

**Issue by HereticSK** [cvxgrp/cvxpy#309]
I am doing a portfolio optimization problem, which is based on a factor model involving tens of constraints. The problem involves both equality and inequality constraints. It can be trivial to write  constraints one by one. So I want a unified way to express all my constraints. 

The solution I came up with is to write all my constraints like `lb <= x <=ub`. When I want `x` to be unbounded above, I set `ub` to an extremely large value. When I don't want `x` to be bounded, I set both `lb` and `ub` to an extreme value.

Is this idea feasible? Can this setting be in conflict with any internal mechanism with cvxpy? Is there any better way to do this? Not only the parameters but also the inequality signs are needed to be generalized. 

I experimented this on my data, and solved with ECOS and CVXOPT respectively. It turned out that ECOS raised `SolverError: Solver 'ECOS' failed. Try another solver`; and CVXOPT reported infeasible. When I write the constraints one by one in the usual way, both solvers worked properly.

I am sorry that my original code is a bit messed up with other parts, I don't have time to separate the optimization part to post here. But I think I have made my point above. Below I rewrite a demo in [cvxpy tutorial](http://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb), which should make my point.

```
import numpy as np
from cvxpy import *

# Generate data for factor model.
n = 3000
m = 50
np.random.seed(1)
mu = np.abs(np.random.randn(n, 1))
Sigma_tilde = np.random.randn(m, m)
Sigma_tilde = Sigma_tilde.T.dot(Sigma_tilde)
D = np.diag(np.random.uniform(0, 0.9, size=n))
F = np.random.randn(n, m)


# Factor model portfolio optimization.
w = Variable(n)
f = F.T*w
gamma = Parameter(sign='positive')
Lmax = Parameter()
ret = mu.T*w 
risk = quad_form(f, Sigma_tilde) + quad_form(w, D)

# I want to make my constraints flexible by passing different values to bound
# for example, the first pair of upper bound and lower bound are set to extreme values, 
# so that the corresponding constraint is effectively relaxed.

bound = {'upper': np.matrix([1e9, 1]).T, 'lower': np.matrix([-1e9, -1]).T}
obj = Maximize(ret - gamma*risk)
const = [sum_entries(w) == 1, norm(w, 1) <= Lmax, 
         f[0:2] >= bound['lower'],
         f[0:2] <= bound['upper'],
        ]
prob = Problem(obj, const)

# Solve the factor model problem.
Lmax.value = 2
gamma.value = 0.1
prob.solve(verbose=True)
```

**Comment by SteveDiamond** [comment]
As you discovered, massive upper bounds/tiny lower bounds will break the solvers. I would strongly recommend that you only create the constraints you actually want. This should be quite straightforward. Just construct a boolean array ``bounded_below`` and a boolean array ``bounded_above`` that identify the entries of ``f`` that are bounded below and above respectively. Then write

```
[ 
    f[bounded_below] >= bound['lower'][bounded_below],
    f[bounded_above] <= bound['upper'][bounded_above]
]
```
