### ISSUE TITLE
if I don't want to install Anaconda, what should I do? 

### ISSUE THREAD

**Issue by pzz2011** [cvxgrp/cvxpy#310]
Like the title said and For me, Anaconda is too big, I don't like it.

**Comment by mwytock** [comment]
Its relatively straightforward to install CVXPY dependencies without anaconda, but requires a few steps of installing native libraries for your platform as not everything is pip installable.

Here is a dockerfile which gets a set of sufficient libraries for ubuntu / debian platform. 

https://github.com/cvxgrp/CVXcanon/blob/solvers/tools/dockerfile/cvxcanon/Dockerfile

Mac is similarly straightforward using homebrew rather than apt-get

Hope that helps!

**Comment by mwytock** [comment]
Even simpler: once you install numpy / scipy on your platform

```pip install cvxpy```

should just work, I believe

**Comment by sschnug** [comment]
The ```pip install cvxpy``` is the way to go then.
But depending on the current state of the package and your OS-config you *might* run into problems.

One of the candidates for this is the *ecos*-dependency. When i installed cvxpy maybe 6 weeks ago on some Windows 7 machine using Python 3.5, i needed to remove ecos from the dependent-libraries (setup.py modified). But of course that means, that you got some other solvers available replacing ecos for your problem types (and in general: these are the commercial ones).

**Comment by pzz2011** [comment]
@mwytock @sschnug  I just installed it with setup.sh under cvxpy and has passed the example took from the README.    

and the following is my numpy config:
```
>>> np.__config__.show()
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    define_macros = [('HAVE_CBLAS', None)]
    language = c
blas_mkl_info:
  NOT AVAILABLE
```

**Comment by sschnug** [comment]
That's ok. MKL is intel's optimized BLAS version. You might lose some speed but i would not worry much.
Instead of testing one example you should search the repository for the test-cases though which is a much more complete check!

(Anaconda, wich you don't like, brings MKL out of the box!)

**Comment by SteveDiamond** [comment]
A lot of good suggestions here. I'm glad pip install worked for you. There's also miniconda if you want the benefits of Anaconda without the bloat from all the default packages.

**Comment by joseortiz3** [comment]
@sschnug 
(and FYI to any Windows people)

`ecos` works fine on Windows 10 (probably 7 also) if you follow my ecos install post (not sure if you were running into the `_TWO_DIGIT_EXPONENT` problem). After installing ecos, `pip install cvxpy` works like it should.
