### ISSUE TITLE
DCPError: Can only divide by a scalar constant.

### ISSUE THREAD

**Issue by hs7965** [cvxgrp/cvxpy#311]
Hi...I am a very recent user of cvxpy (just installed today) and I hope you can answer my question. I am trying to fit a model with four optimized parameters by training with a known data, but in the process I am getting an error (**_DCPError: Can only divide by a scalar constant_**) that relates to division inside an exponent term.
```
x11 = x1/mt
wpt = np.exp(-(dt)/(x11))
```
In the above expression, **x1** is the first variable in the **Variable(4)** term, or in cvxpy terms it is **_Expression(AFFINE, UNKNOWN, (1, 1))_**. The above exponential term occurs inside a function **fn2()**, where elaborate explanation about this is provided below in the problem description.

# Problem Description
My objective is to fit a model (that I believe is a convex function) with four optimized parameters by training it with a data **(referred to as data_known).** This is what I did:
```
x_guess = Variable(4)
objective = min_fun_obj(x_guess)
constraints = [0 <= x_guess[0], 0 <= x_guess[1], 0 <= (1 - np.sum(x_guess[1])) if np.size(x_guess[1]) > 1 else 0 <= (1 - x_guess[1])]
prob = Problem(objective, constraints)
prob.solve(solver=ECOS)
```
In the above code, the **min_fun_obj** function tries to minimize the squared difference between **data_estimated** and **data_known**...where, **data_estimated** is the output from **fn_model()** function (that calls 4 other functions) and **data_known** is the known time series data. 
```
#=============== minimization of objective function
def min_fun_obj(x_guess, *args):
    data_estimated = fn_model(x_guess)
    temp = 0
    for i_t in xrange(np.size(data_estimated, axis=0)): # columns: axis=1
        temp = temp + np.sum([(d_o - d_e)**2 for d_o, d_e in zip(data_known[i_t, :], data_estimated[i_t, :])])
    fun_obj = Minimize(temp)
    return fun_obj
```
The function **fn_model()** above, which calls 4 other functions, is defined below:
```
#==============================================================================
# Main model function
#==============================================================================
def fn_model(x_guess):
    x1, x2, x3, x4 = x_guess[0]*np.ones((1)), x_guess[1]*np.ones((1, 1)), \
    x_guess[2]*np.ones((1)), x_guess[3]*np.ones((1))
    s1t = [[i] for i in x3] 
    s12 = x3*np.ones((n_t, n_p)
    for i_p in xrange(n_p):
        for i_t in xrange(n_t-1):
            dt = t[i_t + 1] - t[i_t] # frequency of rate/pressure data (generally 30 days)
            #=============== call fn1
            k1, k2 = fn1(s12[i_t, i_p])
            mt = (k2/m2) + (k1/m1)
            #=============== call fn2
            data_est[i_t + 1, i_p] = fn2(x1[i_p], mt, dt, data_est[i_t, i_p], x2[:, i_p], data3[:, i_t])
            #=============== call fn3
            data1_est[i_t + 1, i_p], data2_est[i_t + 1, i_p], f2_x1 = fn3(data_est[i_t + 1, i_p], data3[:, i_t], k1, k2)
            #=============== call fn4
            s1current, s12current = fn4(x3[i_p], s1t[i_p][:], dt, x4[i_p], data1_est, x2[:, i_p], \
            data3[:, :], data_est[:, i_p], f2_x1)
            s1t[i_p].append(s1current[0])
            s12[i_t + 1, i_p] = s12current
    return data_est
```
The 4 functions (fn1, fn2, fn3, fn4) are defined as following:
```
#=============== fn1
def fn1(s12):
    k1 = k10*((s12 - s1r)/(1 - s1r - s2r))**n1
    k2 = k20*((1 - s12 - s1r)/(1 - s1r - s2r))**n2
    return k1, k2
#=============== fn2 
def fn2(x1, mt, dt, data_est_ti, x2, data3):
    x11 = x1/mt
    wpt = np.exp(-(dt)/(x11))
    cumgi = np.sum([f_i*I_i for f_i, I_i in zip(x2[:], data3[:])])
    rd = data_est_ti*wt_at_prior_t
    ip = cumgi*(1 - wpt)
    data_est_t = rd + ip
    return data_est_t
#=============== fn3
def fn3(data_est, data3, k1, k2): 
    tempi = np.sum(data3[:]) 
    a = constant/(m1*tempi)
    f2 = ((k2/m2)*(1 + a*k1))/((k1/m1) + (k2/m2))
    data2_est = data_est*f2
    data1_est = data_est - data2_est
    f2_x1 = 1 - (data1_est/data_est)
    return data1_est, data2_est, f2_x1
#=============== fn4
def fn4(x3, s1t, dt, x4, data1_est, x2, data3, data_est, f2_x1):
    temp, s1temp = 0, 0
    c3 = c0 + c1*s1t[-1] + c2*(1 - s1t[-1]) 
    for i_ttemp in xrange(np.size(s1t)): # columns: axis=1
        temp = temp + np.sum([f_i*I_i for f_i, I_i in zip(x2[:], data3[:, i_ttemp + 1])]) 
        s1temp = s1temp + (((s1t[i_ttemp]*(c0 + c1))/c3)*(temp - data_est[i_ttemp + 1]) + data1_est[i_ttemp + 1])
    s1tpresent = x3 - (dt/x4)*s1temp
    wpi = temp/x4 
    s1t2 = s1tpresent + wpi*(1 - f2_x1) 
    return s1tpresent, s1t2
```

**Comment by sschnug** [comment]
That's how it looks to me:

- mt -> depends on k2,m2,k1,m1 (fn_model)
- k1/k2 -> depends on s12 (fn1)
- s12 > depends on x3 = Variable (fn_model)
- => mt depends on Variable x3

x1 itself is a variable so: x11 = x1/mt is a division of two variables which is in general non-convex!

cvxpy only support convex optimization problems (the solvers can't solve anything else) and also tries to prove that convexity internally. This is failing here in the most obvious case there is -> variable / variable.

I don't know if your model (i did not analyze it) can be formulated as convex program, but the above won't work as it's formulated now.

**Comment by hs7965** [comment]
I tried python's scipy.optimize.minimize with method='SLQP' (and other methods), but it does not seem to be working.

**Comment by sschnug** [comment]
```It does not seem to be working```` is not a useful error-description. It's also the wrong place here to discuss the scipy.optimize approach. (Even your opening question is less suited for the issue-tracker as it's not really an issue with cvxpy, but some question about the usage. There is a google-group for that.)

Start at the beginning and reason about the kind of optimization-problem you have and what solvers are available for this specific problem. If it's a non-convex-optimization problem, cvxpy is the wrong tool.

**Comment by hs7965** [comment]
Thanks for your comment.

**Comment by SteveDiamond** [comment]
@hs7965 unfortunately there's no one size fits all tool for optimization. Using cvxpy requires that your problem have a certain structure (http://dcp.stanford.edu/). Black box optimizers like scipy.optimize are more flexible but less reliable.
