### ISSUE TITLE
Passing parameters to mosek

### ISSUE THREAD

**Issue by aszek** [cvxgrp/cvxpy#314]
I'm having a hard time getting CVXPY notice the solver parameters I want to pass to MOSEK, for example:

from cvxpy import *
import mosek

x = Variable()
prob = Problem(Minimize(x), [x==1])
prob.solve(solver=MOSEK, 
	mosek_params={mosek.iparam.presolve_use:mosek.presolvemode.off}, 
	verbose=True)

and you can see from the MOSEK output that it was ignored, presolve is still running. Am I doing something wrong? I am using the latest cvxpy and mosek available in anaconda.

**Comment by SteveDiamond** [comment]
Sorry for the slow reply. The presolve does not run in your example. It's true it appears in the mosek output, but it runs for 0 seconds. Try running
```
from cvxpy import *
import mosek

x = Variable()
y = Variable()
prob = Problem(Minimize(x), [x==y , y==1])
prob.solve(solver=MOSEK,
mosek_params={mosek.iparam.presolve_use:mosek.presolvemode.off},
verbose=True)
```
with and without the mosek_params. You'll see the presolve is does something when it's on but not when you pass in the mosek_params.
