### ISSUE TITLE
<class 'cvxopt.base.matrix'> is not a valid type for a Constant value

### ISSUE THREAD

**Issue by scubamut** [cvxgrp/cvxpy#315]
Environment: windows 10 64 bit. CVXPY latest master.
# packages in environment at c:\anaconda3\envs\cvxpy34:
#
cvxcanon                  0.0.23.3                 py34_0  
cvxopt                    1.1.9+1.gd8bd930           <pip>
cvxpy                     0.4.8                     <pip>
dill                      0.2.5                     <pip>
fastcache                 1.0.2                    py34_1  
mkl                       11.3.3                        1  
multiprocess              0.70.4                    <pip>
numpy                     1.11.2                   py34_0  
pip                       9.0.1                    py34_1  
pyreadline                2.1                       <pip>
python                    3.4.5                         0  
scipy                     0.18.1              np111py34_0  
setuptools                27.2.0                   py34_1  
six                       1.10.0                   py34_0  
toolz                     0.8.2                    py34_0  
vs2010_runtime            10.00.40219.1                 2  
vs2015_runtime            14.0.25123                    0  
wheel                     0.29.0                   py34_0 

running example ex_4_3.py results in

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-7bd5fe758cb8> in <module>()
     36 
     37 x = Variable(n)
---> 38 objective = Minimize(  0.5 * quad_form(x, P)  + q.T * x + r )
     39 constraints = [ x >= -1, x <= 1]
     40 

c:\Anaconda3\envs\cvxpy34\lib\site-packages\cvxpy-0.4.8-py3.4.egg\cvxpy\atoms\quad_form.py in quad_form(x, P)
     92 
     93     """
---> 94     x, P = list(map(Expression.cast_to_const, (x, P)))
     95     # Check dimensions.
     96     n = P.size[0]

c:\Anaconda3\envs\cvxpy34\lib\site-packages\cvxpy-0.4.8-py3.4.egg\cvxpy\expressions\expression.py in cast_to_const(expr)
    242         """Converts a non-Expression to a Constant.
    243         """
--> 244         return expr if isinstance(expr, Expression) else cvxtypes.constant()(expr)
    245 
    246     @_cast_other

c:\Anaconda3\envs\cvxpy34\lib\site-packages\cvxpy-0.4.8-py3.4.egg\cvxpy\expressions\constants\constant.py in __init__(self, value)
     40             if isinstance(value, np.ndarray) and len(value.shape) == 1:
     41                 self.is_1D_array = True
---> 42             self._value = intf.DEFAULT_INTF.const_to_matrix(value)
     43             self._sparse = False
     44         # Set DCP attributes.

c:\Anaconda3\envs\cvxpy34\lib\site-packages\cvxpy-0.4.8-py3.4.egg\cvxpy\interface\base_matrix_interface.py in new_converter(self, value, convert_scalars)
     45     def scalar_const(converter):
     46         def new_converter(self, value, convert_scalars=False):
---> 47             if not convert_scalars and cvxpy.interface.matrix_utilities.is_scalar(value):
     48                 return cvxpy.interface.matrix_utilities.scalar_value(value)
     49             else:

c:\Anaconda3\envs\cvxpy34\lib\site-packages\cvxpy-0.4.8-py3.4.egg\cvxpy\interface\matrix_utilities.py in is_scalar(constant)
    148 
    149 def is_scalar(constant):
--> 150     return size(constant) == (1, 1)
    151 
    152 

c:\Anaconda3\envs\cvxpy34\lib\site-packages\cvxpy-0.4.8-py3.4.egg\cvxpy\interface\matrix_utilities.py in size(constant)
    136         return INTERFACES[sp.csc_matrix].size(constant)
    137     else:
--> 138         raise TypeError("%s is not a valid type for a Constant value." % type(constant))
    139 
    140 # Is the constant a column vector?

TypeError: <class 'cvxopt.base.matrix'> is not a valid type for a Constant value.`

Any help would be appreciated

**Comment by SteveDiamond** [comment]
Is P or q a cvxopt matrix? Support for cvxopt matrices as constants has more or less been dropped. You should make them numpy ndarrays or matrices.

**Comment by scubamut** [comment]
got it. thks. 

the examples need updating....
