### ISSUE TITLE
orthogonality constraints in cvxpy

### ISSUE THREAD

**Issue by YipengUva** [cvxgrp/cvxpy#316]
How can I define an orthogonality constraints of a matrix variable, X \in R^m*n? X'X = I.
I tried quad_form(X, P), however, it only works for vector rather than matrix.

regards

**Comment by SteveDiamond** [comment]
Orthogonality constraints are not convex, so they are not handled by cvxpy. You could try using the dccp package and bounding the largest and smallest singular value of X.
