### ISSUE TITLE
Consensus Example not working

### ISSUE THREAD

**Issue by diego898** [cvxgrp/cvxpy#318]
the consensus example in the documentation is not working for me on python 3. It seems like a lot of things are missing like the definition of `MAX_ITER`, `run_process` vs `run_worker`, `Process(n, np.zeroes(n))` returning a `Name 'n' is not defined` error, etc. I think its fine to sketch out pseudo-code, but it might help to make the clear on that page.

**Comment by anselme333** [comment]
> the consensus example in the documentation is not working for me on python 3. It seems like a lot of things are missing like the definition of `MAX_ITER`, `run_process` vs `run_worker`, `Process(n, np.zeroes(n))` returning a `Name 'n' is not defined` error, etc. I think its fine to sketch out pseudo-code, but it might help to make the clear on that page.

I have the same issue. I would appreciate it if we can get a working example of consensus optimization. Thank you!
