### ISSUE TITLE
How to represent quadratic form of a diagonal matrix

### ISSUE THREAD

**Issue by szs8** [cvxgrp/cvxpy#319]
Given a Diagonal matrix with `d` as the diagonal vector and another vector `v`, what is the difference between the following 2 expressions?

1. `cvx.sum_entries(d * cvx.square(v))`
        
2. `cvx.sum_entries(cvx.square(cvx.sqrt(d) * v))`

(1) follows from http://mathworld.wolfram.com/DiagonalQuadraticForm.html, but (2) seems equivalent to me. However they both give different results.

**Comment by SteveDiamond** [comment]
Do you mean that if you evaluate (1) and (2) on constant values, they give different results, or that they have different behavior inside cvxpy? I would be very surprised by the former, but (1) and (2) have different DCP properties if ``d`` is a variable so the latter is possible.

**Comment by SteveDiamond** [comment]
I'm closing this due to a lack of a clarifying response.
