### ISSUE TITLE
Error import cv2

### ISSUE THREAD

**Issue by Cienlim612** [cvxgrp/cvxpy#326]
>>> import cv2
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
Can anyone tell me what is the problem?

**Comment by sschnug** [comment]
This has nothing to do with cvxpy (and this is one of the sparsest issuedescriptions i saw here).

Start debugging your opencv-install.

**Comment by Cienlim612** [comment]
haha sorry, I should describe more about it, my bad. 
First, I import numpy and then it shows working perfectly after I type "print numpy.__version__"
But, I cannot import  cv2 as shown as above

Here is the code:

Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> print numpy.__version__
1.7.1
>>> import cv2
RuntimeError: module compiled against API version 0xa but this version of numpy is 0x7
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: numpy.core.multiarray failed to import
>>>

I already re-extract the openCV and follow the instructions and steps of the documentation on [](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_setup/py_setup_in_windows/py_setup_in_windows.html)

**Comment by SteveDiamond** [comment]
@Cienlim612 this repository is for cvxpy, not opencv. I expect the developers of opencv will be more use to you.
