### ISSUE TITLE
Using simplex method in mosek raises exception

### ISSUE THREAD

**Issue by goriri** [cvxgrp/cvxpy#327]
Format result raises an exception when using

`prob.solve(solver=MOSEK,mosek_params={mosek.iparam.optimizer: mosek.optimizertype.free_simplex},verbose=True)`
I guess the problem is with the line `task.getprosta(mosek.soltype.itr)` in mosek_intf.py line 279 where only mosek.soltype.bas is defined.
Using cvxpy version 0.4.8

**Comment by SteveDiamond** [comment]
You seem to have a much better knowledge of the MOSEK interface and features than I do. Why don't you make a pull request to fix this? Remember to include a test in ``test_solvers.py``.

**Comment by RhysU** [comment]
Has this been resolved?  Seems like the fallback in https://github.com/cvxgrp/cvxpy/blob/4bf33893a5d3eeaf1ae9bd0346f76f04c60d913e/cvxpy/problems/solvers/mosek_intf.py#L246 may have it covered.
