### ISSUE TITLE
cvxpy.max_elemwise requires 2 args while min_elemwise permits 1?

### ISSUE THREAD

**Issue by RhysU** [cvxgrp/cvxpy#330]
The asymmetry in the documented 2 vs 1 argument requirement for `max_elemwise` vs `min_elemwise` is weird.  Especially since the latter is implemented in terms of the former.  Can you sidestep this by making `max_elemwise` a free function that returns either the current class (2 + arguments) or just the argument (1 argument)?

**Comment by SteveDiamond** [comment]
I'm not sure what you mean. Both require 2+ arguments (though I'm modifying them to work with a single list also). Where do you see a difference?

**Comment by RhysU** [comment]
I observed the following method signature differences:
```
In [6]: cvxpy.__version__
Out[6]: '0.4.8'

In [7]: cvxpy.max_elemwise?
Init signature: cvxpy.max_elemwise(arg1, arg2, *args)
Docstring:      Elementwise maximum. 
Init docstring:
Requires at least 2 arguments.
        
File:           ~/anaconda3/envs/cvxpy-dev/lib/python3.5/site-packages/cvxpy/atoms/elementwise/max_elemwise.py
Type:           ABCMeta

In [8]: cvxpy.min_elemwise?
Signature: cvxpy.min_elemwise(*args)
Docstring: <no docstring>
File:      ~/anaconda3/envs/cvxpy-dev/lib/python3.5/site-packages/cvxpy/atoms/elementwise/min_elemwise.py
Type:      function
```

I'd expect both to look like the first or both to look like the second.  The mixture is what prompted filing this ticket.

**Comment by SteveDiamond** [comment]
This is fixed now in the current master.
