### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by arokem** [cvxgrp/cvxpy#331]
What is `LS` (the last link) supposed to be pointing to on this line? 

https://github.com/cvxgrp/cvxpy/blame/master/doc/source/tutorial/advanced/index.rst#L242

**Comment by SteveDiamond** [comment]
This is a mistake. There shouldn't be any link.

**Comment by arokem** [comment]
So what is used for quadratic programs?

I am trying to move from CVXOPT to using cvxpy, to take advantage of your
recent relicensing (thanks!!), but I need to solve a quadratic program.

Thanks for making this great package and thanks for providing it under a
license we can use!

**Comment by SteveDiamond** [comment]
QPs are converted to SOCPs and solved by ECOS. There's ongoing work on a dedicated QP solver, but it's not integrated yet.
