### ISSUE TITLE
Unexpected constants coming back from float * Variable?

### ISSUE THREAD

**Issue by RhysU** [cvxgrp/cvxpy#333]
Apologies for the lousy ticket, but I'm at a loss for how to describe this in words...
```
In [1]: import cvxpy

In [2]: foo = 4.9e-6

In [3]: bar = cvxpy.Variable()

In [4]: bar.value = 406293

In [5]: bar.value
Out[5]: 406293

In [6]: baz = -1 * bar

In [7]: baz.value
Out[7]: -406293

In [8]: foo * baz  #Huh?
Out[8]: Expression(CONSTANT, ZERO, (1, 1))

In [9]: (foo * baz).value  #???
Out[9]: 0.0

In [10]: foo * baz.value  # As expected
Out[10]: -1.9908356999999999

In [11]: cvxpy.__version__
Out[11]: '0.4.8'

In [12]: foo * bar # ???
Out[12]: Expression(CONSTANT, ZERO, (1, 1))

In [13]: (foo * bar).value #???
Out[13]: 0.0
```

This, in a new IPython session, behaves as I expect:
```
In [1]: import cvxpy

In [2]: foo = 123

In [3]: bar = cvxpy.Variable()

In [4]: bar.value = 456

In [5]: baz = foo * bar

In [6]: baz
Out[6]: Expression(AFFINE, UNKNOWN, (1, 1))

In [7]: baz.value
Out[7]: 56088
```

Isolated/distilled from a larger example where products like "float * f(Variable)" where mysteriously uniformly zero.  In that case, I was not using `bar.value` but had the values computed as part of an objective during a solve operation.

**Comment by SteveDiamond** [comment]
This is because ``foo`` is so small in the first example. Right now if constants are very small cvxpy assigns them sign ``zero``. I honestly can't remember why I do this (there was a good reason at some point). It might be better to not do this rounding. Certainly in this example it's a mistake.

**Comment by RhysU** [comment]
Can I circumvent the behavior by using a cvxpy.Parameter or in some other manor? In my use case small * large becomes non-negligible.

**Comment by SteveDiamond** [comment]
I removed the rounding of small values on master.

**Comment by RhysU** [comment]
Thank you for your quick responses.

**Comment by RhysU** [comment]
For anyone who comes after and is working on version 0.4.8, it seems foo = cvxpy.Parameter(value=4.9e-6) permits the initial sample to work as I expected.

**Comment by RhysU** [comment]
For anyone who comes after, I have confirmed the above recreate works as expected starting with tag 0.4.9.
