### ISSUE TITLE
mosek.soltype.itr -> unknown but mosek.soltype.bas giving optimal

### ISSUE THREAD

**Issue by RhysU** [cvxgrp/cvxpy#335]
I've a case where, for `verbose=True`, Mosek 8.0 completes with
```
Interior-point solution summary
  Problem status  : UNKNOWN
  Solution status : UNKNOWN
  Primal.  obj: 5.0643588790e+05    nrm: 2e+08    Viol.  con: 3e-01    var: 0e+00  
  Dual.    obj: 5.0415624857e+05    nrm: 2e+05    Viol.  con: 5e-02    var: 4e-04  

Basic solution summary
  Problem status  : PRIMAL_AND_DUAL_FEASIBLE
  Solution status : OPTIMAL
  Primal.  obj: 4.9845334246e+05    nrm: 2e+08    Viol.  con: 2e-07    var: 0e+00  
  Dual.    obj: 4.9845334246e+05    nrm: 8e-01    Viol.  con: 3e-05    var: 6e-17  
```

Per [the Mosek interface](https://github.com/cvxgrp/cvxpy/blob/be172685c1e7198e14ded8361f0ac99c85b18a52/cvxpy/problems/solvers/mosek_intf.py#L277) this causes `task.getprosta(mosek.soltype.itr)` to return `unknown` while `task.getsolsta(mosek.soltype.bas)` reports `optimal`.  I see that [Mosek 7 has the same `soltype` enum](http://docs.mosek.com/7.0/pythonapi/Solution_types.html)-- I've not confirmed this outcome is version 8-specific but I doubt it given that documentation.

Is `mosek.soltype.bas` irrelevant or is not interrogating `soltype.bas` a shortcoming of the cvxpy interface?  Monkeying around a bit in the Python debugger suggests that I can walk through much of the remainder of that interface logic using `bas`.  That said, a simple `s/itr/bas/g` in `mosek_intf.py` does not permit running the front-page example at http://www.cvxpy.org/en/latest/.

Gross hackery in mosek_intf.py like...
```        # Retrieve basic solution if possible, otherwise fallback to interior
        try:
            task.getprosta(mosek.soltype.bas)  # unused
            solsta = task.getsolsta(mosek.soltype.bas)
            soltype = mosek.soltype.bas
        except:
            task.getprosta(mosek.soltype.itr)  # unused
            solsta = task.getsolsta(mosek.soltype.itr)
            soltype = mosek.soltype.itr
```
...along with `s/mosek.soltype.itr/soltype/g` in the remainder of the file permits both the front page example as well as my problem to run.  That try/except causes Mosek to spit out [MOSEK error 1265: The solution with code 1 is not defined.](http://docs.mosek.com/7.0/capi/Response_codes.html) which is fair.  I've not deduced how to pre-query which solution types are defined.

Recommendations for how to proceed much appreciated.

**Comment by enzobusseti** [comment]
Thanks for pointing out this! Did you find any definite instruction on how to extract the solution type, in the python-mosek documentation? (I believe lack of that information is the reason why we didn't dig further.)

**Comment by RhysU** [comment]
Something like
```
(Pdb) task.solutiondef(mosek.soltype.bas)
1
(Pdb) task.solutiondef(mosek.soltype.itr)
1
(Pdb) task.solutiondef(mosek.soltype.itg)
0
```
informs [whether or not a solution has been attempted with a given type](http://docs.mosek.com/7.0/pythonapi/Task_solutiondef_.html).  Using that would be more sensible than the `try/except` as with `solve(..., verbose=True)` Mosek logs a scary looking 1265 warning.

Mosek support indicated that the interior-point optimizer provides both by default, with most folks preferring the interior-point variant.  I'm unsure of the right pattern for falling back to the basic solution for cvxpy's purposes, or of how to make cvxpy specify which solution is desired.

**Comment by RhysU** [comment]
I suspect, but have not confirmed, that looks like monkeying wit hhttp://docs.mosek.com/7.0/capi/MSK_IPAR_BI_CLEAN_OPTIMIZER.html.

**Comment by aszekMosek** [comment]
An easy option would be, as @RhysU says, to check which solutions are available with ``solutiondef`` and then pick the one with higher status (prefer optimal over unknown etc.)

For example imagine the scenario when the user passes a MOSEK parameter like ``mosek.iparam.optimizer: mosek.optimizertype.primal_simplex`` explitcitly asking only for the basic solution. Now this crashes cvxpy.

**Comment by SteveDiamond** [comment]
@aszekMosek's solution seems reasonable. I'm happy to merge such a PR.

**Comment by RhysU** [comment]
Closing per the merge.  Please re-open if you disagree.
