### ISSUE TITLE
What's the meaning/use of primal_value in Variable

### ISSUE THREAD

**Issue by jerryfuyu0104** [cvxgrp/cvxpy#338]
Could I set value of Variable as an initial solution/guess to iterate to solve the problem, which may faster the solving? If yes, since the cost function abs(w-w0) will expand the size of problem from  N to 2*N, when I set the primal_value for the Variable sized of N, then how cvxpy will set the initial solution of sized of 2*N?
Problem are like below, eta may be setted with zero or one as a scalar.
w = Variable(N)
w.primal_value = w0
constraints = []
constraints.append(w>=0)
constraints.append(sum_entries(w) == 1)
objective = Maximize(ret.T * w - 0.5 * quad_form(w, covMat) - eta*sum_entries(abs(w-w0)))
problem =Problem(objective, constraints)
problem.solve(solver='CVXOPT', verbose=True, kktsolver=ROBUST_KKTSOLVER)

**Comment by SteveDiamond** [comment]
You can set the initial value of a variable using ``var.value = ...``. ``primal_value`` is not supposed to be public. Unfortunately setting an initial value doesn't do anything in normal cvxpy (it does something for extensions like DCCP and NCVX).

**Comment by jerryfuyu0104** [comment]
I think an iterative method could always set an initial guess, will this be added?
