### ISSUE TITLE
Problem with the solution returned by MOSEK 

### ISSUE THREAD

**Issue by ignrub** [cvxgrp/cvxpy#339]
I'm having problem with the solution returned by MOSEK, apparently the solver solves the problem but then CVXPY cannot recover the solution, here is a simple example:
https://ctrlv.it/python/18814/2945027113
that gives the following error:
  File "$HOME/miniconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 0 into shape (2,2)
Thank you in advance

**Comment by SteveDiamond** [comment]
The ``>>`` operator doesn't work with MOSEK. Obviously this is something I'd like to fix, but I didn't write the MOSEK interface and it's fairly complicated.

**Comment by ignrub** [comment]
I managed to use MOSEK using the functions 'lambda_min' and  'lambda_max':
X>>0 replaced by lambda_min(X)>0 and 
X<<0 replaced by lambda_max(X)<0
Is it correct to use this functions? Does it increase the algorithmic complexity?

**Comment by SteveDiamond** [comment]
That's a fine solution. It doesn't increase the complexity much.
