### ISSUE TITLE
Constraints about the DCP rules

### ISSUE THREAD

**Issue by jerryfuyu0104** [cvxgrp/cvxpy#341]
convex <= concave satisfies the DCP rules, 
but convex == affine does not, why?

    x = Variable(n)
    y = Variable(n)
    z = a.T * x + quad_form(x, A) + sum_entries(y)
    objective = Minimize(z)
    constraints = [x >= 0, y >=0, sum_entries(x) == 1, square(y) == x]

**Comment by SteveDiamond** [comment]
``convex == affine`` is not a convex constraint, and of course the point of DCP is to guarantee convexity. I suggest your read more about convex optimization: http://stanford.edu/~boyd/cvxbook/
