### ISSUE TITLE
Fixing values of cvx.Variables

### ISSUE THREAD

**Issue by nipunbatra** [cvxgrp/cvxpy#342]
Hi, 
I was wondering if we can specify `some` portion of the values of a cvx.Variable that we already know? The context comes from the example on [non-negative matrix factorization](http://nbviewer.jupyter.org/github/cvxgrp/cvxpy/blob/master/examples/notebooks/WWW/nonneg_matrix_fact.ipynb).

Here, say, X is `cvx.Variable(3,4)`.

Here, suppose I already know X[0, 1] and X[2, 3] and they should remain fixed throughout the optimisation. How should we encode this information?

**Comment by SteveDiamond** [comment]
Either encode it as constraints or construct X as follows: ``vec_x = Variable(12); X = reshape(A*vec_x, 3, 4) + B`` where ``A`` is a 12x12 sparse matrix with all zero rows for fixed entries of X.
