### ISSUE TITLE
Array Indexing Issue Translating Problem Solution from CVXOPT

### ISSUE THREAD

**Issue by ssanderson** [cvxgrp/cvxpy#343]
I'm seeing failures reconstructing outputs from CVXOPT when the constraints are expressed as inequalities against a matrix times a set of weights.

Minimal Repro:

```python
import numpy as np
import cvxpy as cvx

w = cvx.Variable(2)

M = np.matrix([[1., 0.1],
               [0., 0.],
               [0., 0.8],
               [0., 0.1]])
Mw = M * w

lower_bound = (Mw >= np.array([-0.5, -0.5, -0.5, -0.5]))
upper_bound = (Mw <= np.array([0.5, 0.5, 0.5, 0.5]))

objective = cvx.Minimize(cvx.norm2(w - np.array([0.4, 1.2])))

problem = cvx.Problem(objective, [lower_bound, upper_bound])

problem.solve(solver='CVXOPT')

print w.value
```

Running the above produces the following traceback for me:

```bash
$ python repro.py
Traceback (most recent call last):
  File "repro.py", line 19, in <module>
    problem.solve(solver='CVXOPT')
  File "/home/ssanderson/.virtualenvs/zipline/local/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "/home/ssanderson/.virtualenvs/zipline/local/lib/python2.7/site-packages/cvxpy/problems/problem.py", line 331, in _solve
    kwargs)
  File "/home/ssanderson/.virtualenvs/zipline/local/lib/python2.7/site-packages/cvxpy/problems/solvers/cvxopt_intf.py", line 186, in solve
    return self.format_results(results_dict, data, cached_data)
  File "/home/ssanderson/.virtualenvs/zipline/local/lib/python2.7/site-packages/cvxpy/problems/solvers/cvxopt_intf.py", line 408, in format_results
    new_dual[:P_rows] = data["P_leq"].T*z
TypeError: incompatible dimensions
```

Switching to a different solver (or to passing `kktsolver='robust'`) produces the expected result of [0.4, 6.25].

```
$ pip freeze | grep -e cvxpy -e cvxopt
cvxopt==1.1.9
cvxpy==0.4.9
```

@SteveDiamond I'm going to try to dig more into this later today, but I figured I'd post it in case you have any immediate insight as to where the mismatch is happening here.

**Comment by ssanderson** [comment]
Additional data point: the error goes away (and I get the expected result) if I comment out the block starting with `if dims[s.LEQ_DIM] > 0:` from `CVXOPT.remove_redundant_rows`.  So my suspicion here is that the compression that happens in `remove_redundant_rows` is not being respected by the code that's unpacking results on the other end.

**Comment by ssanderson** [comment]
I haven't been able to glean much more insight in to the right fix for this issue.  The only interesting new observation I have is that, in all the cases where I've seen this fail, `data["P_leq"].T*z` is mismatched, but just `data["P_leq"] * z` succeeds.

**Comment by SteveDiamond** [comment]
I believe this is fixed now on master.

**Comment by ssanderson** [comment]
@SteveDiamond much appreciated!
