### ISSUE TITLE
Indexing with all false lead to ValueError

### ISSUE THREAD

**Issue by goriri** [cvxgrp/cvxpy#344]
Add the following test in test_constaints.py, it will produce ValueError: zero-size array to reduction operation.

def test_constraint_slice(self):
        #self.A = Variable(2, 2, name='A')
        condition = np.matrix('1 1; 1 1')
        constraint = [self.A[condition == 0] == 0]

**Comment by SteveDiamond** [comment]
The error message is not the best here, but this seems like it should produce an error. You think this should work?

**Comment by goriri** [comment]
The condition might be dynamic (calculated), so it cannot be pre known whether it’s all false or not. I think no matter whether it’s all false or not, it should always work the same way.

**Comment by rileyjmurray** [comment]
@goriri , can you try to articulate the general behavior of indexing by all-False? Perhaps: cvxpy Expressions of size zero are automatically cast to the scalar 0?
