### ISSUE TITLE
CVXPY is unable to find CVXOPT

### ISSUE THREAD

**Issue by MRehanMS** [cvxgrp/cvxpy#346]
I have CVXOPT installed on my machine (win64), and I'm trying to call the CVXOPT solver from CVXPY, however, I get an error that the solver is not installed.  Printing the list of available solvers also does not show this solver - How do I resolve this?

packages in environment at C:\Program Files\Anaconda3:
_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
alabaster                 0.7.9                    py35_0
anaconda                  custom                   py35_0
anaconda-clean            1.0.0                    py35_0
anaconda-client           1.5.1                    py35_0
anaconda-navigator        1.3.1                    py35_0
appdirs                   1.4.3                     <pip>
APScheduler               3.3.0                     <pip>
argcomplete               1.0.0                    py35_1
astroid                   1.4.7                    py35_0
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
blpapi                    3.9.0                    py35_0    dsm
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.7.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
cmake                     0.5.0                     <pip>
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.14                   py35_1
conda-build               2.0.2                    py35_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.5                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
CVXcanon                  0.1.1                     <pip>
cvxopt                    1.1.9                     <pip>
cvxpy                     0.4.9                     <pip>
cycler                    0.10.0                   py35_0
cython                    0.25.1                   py35_0
Cython                    0.25.2                    <pip>
cytoolz                   0.8.0                    py35_0
dask                      0.11.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
dill                      0.2.6                     <pip>
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
ecos                      2.0.4                     <pip>
empyrical                 0.2.1                     <pip>
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
funcsigs                  1.0.2                     <pip>
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.2                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
ibm-db                    2.0.7                     <pip>
IbPy2                     0.8.0                     <pip>
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
inflection                0.3.1                     <pip>
inflection                0.3.1                    py35_0
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
lazy-object-proxy         1.2.1                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.27                   vc14_0  [vc14]
libpython                 2.0                      py35_0
libtiff                   4.0.6                    vc14_3  [vc14]
line_profiler             2.0                      py35_0    conda-forge
llvmlite                  0.13.0                   py35_0
locket                    0.2.0                    py35_1
Logbook                   1.0.0                     <pip>
lxml                      3.6.4                    py35_0
m2w64-binutils            2.25.1                        4
m2w64-bzip2               1.0.6                         5
m2w64-crt-git             5.0.0.4636.2595836               1
m2w64-gcc                 5.3.0                         5
m2w64-gcc-ada             5.3.0                         5
m2w64-gcc-fortran         5.3.0                         5
m2w64-gcc-libgfortran     5.3.0                         5
m2w64-gcc-libs            5.3.0                         6
m2w64-gcc-objc            5.3.0                         5
m2w64-gmp                 6.1.0                         1
m2w64-headers-git         5.0.0.4636.c0ad18a               1
m2w64-isl                 0.16.1                        1
m2w64-libiconv            1.14                          5
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               1
m2w64-libwinpthread-git   5.0.0.4634.697f757               1
m2w64-make                4.1.2351.a80a8b8               1
m2w64-mpc                 1.0.3                         2
m2w64-mpfr                3.1.4                         3
m2w64-pkg-config          0.29.1                        1
m2w64-toolchain           5.3.0                         6
m2w64-tools-git           5.0.0.4592.90b8472               1
m2w64-windows-default-manifest 6.4                           2
m2w64-winpthreads-git     5.0.0.4634.697f757               1
m2w64-zlib                1.2.8                         9
markupsafe                0.23                     py35_2
matplotlib                1.5.3               np111py35_1
menuinst                  1.4.1                    py35_0
mingw                     4.7                           1
mistune                   0.7.3                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mock                      2.0.0                     <pip>
more-itertools            2.2                      py35_0
more-itertools            2.3                       <pip>
mpmath                    0.19                     py35_1
msys2-conda-epoch         20160418                      0
multipledispatch          0.4.8                    py35_0
multiprocess              0.70.5                    <pip>
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
ndg-httpsclient           0.4.2                     <pip>
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.28.1              np111py35_0
numexpr                   2.6.1               np111py35_0
numpy                     1.11.2                   py35_0
oandapy                   0.1                       <pip>
odo                       0.5.0                    py35_1
olefile                   0.44                     py35_0
openpyxl                  2.4.0                    py35_0
openssl                   1.0.2j                   vc14_0  [vc14]
packaging                 16.8                      <pip>
pandas                    0.19.2              np111py35_1
pandas                    0.17.1                    <pip>
pandas-datareader         0.2.1                     <pip>
pandas-datareader         0.2.1                    py35_0
partd                     0.3.6                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pbr                       1.10.0                    <pip>
pefile                    2016.3.28                 <pip>
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    4.0.0                    py35_1
pip                       8.1.2                    py35_0
pip                       9.0.1                     <pip>
pkginfo                   1.3.2                    py35_0
plotly                    1.12.9                    <pip>
ply                       3.9                      py35_0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
py                        1.4.31                   py35_0
PyAlgoTrade               0.18                      <pip>
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.3.0                    py35_0
pyfolio                   0.6.0                     <pip>
pygments                  2.1.3                    py35_0
PyInstaller               3.2                       <pip>
pylint                    1.5.4                    py35_1
pyodbc                    3.0.10                   py35_1
pyopenssl                 16.2.0                   py35_0
pyparsing                 2.2.0                     <pip>
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_2
PyQt5                     5.7                       <pip>
pyreadline                2.1                       <pip>
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.6.1                 py35_0
pywin32                   220                      py35_1
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.1.2                    py35_0
quandl                    3.0.1                    py35_0
requests                  2.12.4                   py35_0
requests-file             1.4.1                    py35_0
requests-file             1.4.1                     <pip>
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.18.1              np111py35_0
scs                       1.2.6                     <pip>
seaborn                   0.7.1                     <pip>
setuptools                27.2.0                   py35_1
setuptools                34.3.3                    <pip>
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
sip                       4.18.1                    <pip>
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.6                    py35_0
spyder                    3.0.0                    py35_0
sqlalchemy                1.1.4                    py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
theano                    0.8.2                    py35_0
Theano                    0.8.2                     <pip>
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.4.1                    py35_0
traitlets                 4.3.0                    py35_0
tzlocal                   1.3                       <pip>
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.6                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by MRehanMS** [comment]
_Output of conda list_

packages in environment at C:\Program Files\Anaconda3:
_license                  1.1                      py35_1
_nb_ext_conf              0.3.0                    py35_0
alabaster                 0.7.9                    py35_0
anaconda                  custom                   py35_0
anaconda-clean            1.0.0                    py35_0
anaconda-client           1.5.1                    py35_0
anaconda-navigator        1.3.1                    py35_0
appdirs                   1.4.3                     <pip>
APScheduler               3.3.0                     <pip>
argcomplete               1.0.0                    py35_1
astroid                   1.4.7                    py35_0
astropy                   1.2.1               np111py35_0
babel                     2.3.4                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.5.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
blpapi                    3.9.0                    py35_0    dsm
bokeh                     0.12.2                   py35_0
boto                      2.42.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.7.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
cmake                     0.5.0                     <pip>
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.3.14                   py35_1
conda-build               2.0.2                    py35_0
conda-env                 2.6.0                         0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.5                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
CVXcanon                  0.1.1                     <pip>
cvxopt                    1.1.9                     <pip>
cvxpy                     0.4.9                     <pip>
cycler                    0.10.0                   py35_0
cython                    0.25.1                   py35_0
Cython                    0.25.2                    <pip>
cytoolz                   0.8.0                    py35_0
dask                      0.11.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
dill                      0.2.6                     <pip>
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
ecos                      2.0.4                     <pip>
empyrical                 0.2.1                     <pip>
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
filelock                  2.0.6                    py35_0
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
funcsigs                  1.0.2                     <pip>
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.2                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_2
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
ibm-db                    2.0.7                     <pip>
IbPy2                     0.8.0                     <pip>
icu                       57.1                     vc14_0  [vc14]
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
inflection                0.3.1                     <pip>
inflection                0.3.1                    py35_0
ipykernel                 4.5.0                    py35_0
ipython                   5.1.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                5.2.2                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.4.0                    py35_0
jupyter_console           5.0.0                    py35_0
jupyter_core              4.2.0                    py35_0
lazy-object-proxy         1.2.1                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.27                   vc14_0  [vc14]
libpython                 2.0                      py35_0
libtiff                   4.0.6                    vc14_3  [vc14]
line_profiler             2.0                      py35_0    conda-forge
llvmlite                  0.13.0                   py35_0
locket                    0.2.0                    py35_1
Logbook                   1.0.0                     <pip>
lxml                      3.6.4                    py35_0
m2w64-binutils            2.25.1                        4
m2w64-bzip2               1.0.6                         5
m2w64-crt-git             5.0.0.4636.2595836               1
m2w64-gcc                 5.3.0                         5
m2w64-gcc-ada             5.3.0                         5
m2w64-gcc-fortran         5.3.0                         5
m2w64-gcc-libgfortran     5.3.0                         5
m2w64-gcc-libs            5.3.0                         6
m2w64-gcc-objc            5.3.0                         5
m2w64-gmp                 6.1.0                         1
m2w64-headers-git         5.0.0.4636.c0ad18a               1
m2w64-isl                 0.16.1                        1
m2w64-libiconv            1.14                          5
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               1
m2w64-libwinpthread-git   5.0.0.4634.697f757               1
m2w64-make                4.1.2351.a80a8b8               1
m2w64-mpc                 1.0.3                         2
m2w64-mpfr                3.1.4                         3
m2w64-pkg-config          0.29.1                        1
m2w64-toolchain           5.3.0                         6
m2w64-tools-git           5.0.0.4592.90b8472               1
m2w64-windows-default-manifest 6.4                           2
m2w64-winpthreads-git     5.0.0.4634.697f757               1
m2w64-zlib                1.2.8                         9
markupsafe                0.23                     py35_2
matplotlib                1.5.3               np111py35_1
menuinst                  1.4.1                    py35_0
mingw                     4.7                           1
mistune                   0.7.3                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mock                      2.0.0                     <pip>
more-itertools            2.2                      py35_0
more-itertools            2.3                       <pip>
mpmath                    0.19                     py35_1
msys2-conda-epoch         20160418                      0
multipledispatch          0.4.8                    py35_0
multiprocess              0.70.5                    <pip>
nb_anacondacloud          1.2.0                    py35_0
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.1.0                    py35_0
nbpresent                 3.0.2                    py35_0
ndg-httpsclient           0.4.2                     <pip>
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.3                    py35_0
numba                     0.28.1              np111py35_0
numexpr                   2.6.1               np111py35_0
numpy                     1.11.2                   py35_0
oandapy                   0.1                       <pip>
odo                       0.5.0                    py35_1
olefile                   0.44                     py35_0
openpyxl                  2.4.0                    py35_0
openssl                   1.0.2j                   vc14_0  [vc14]
packaging                 16.8                      <pip>
pandas                    0.19.2              np111py35_1
pandas                    0.17.1                    <pip>
pandas-datareader         0.2.1                     <pip>
pandas-datareader         0.2.1                    py35_0
partd                     0.3.6                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pbr                       1.10.0                    <pip>
pefile                    2016.3.28                 <pip>
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pillow                    4.0.0                    py35_1
pip                       8.1.2                    py35_0
pip                       9.0.1                     <pip>
pkginfo                   1.3.2                    py35_0
plotly                    1.12.9                    <pip>
ply                       3.9                      py35_0
prompt_toolkit            1.0.3                    py35_0
psutil                    4.3.1                    py35_0
py                        1.4.31                   py35_0
PyAlgoTrade               0.18                      <pip>
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.3.0                    py35_0
pyfolio                   0.6.0                     <pip>
pygments                  2.1.3                    py35_0
PyInstaller               3.2                       <pip>
pylint                    1.5.4                    py35_1
pyodbc                    3.0.10                   py35_1
pyopenssl                 16.2.0                   py35_0
pyparsing                 2.2.0                     <pip>
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_2
PyQt5                     5.7                       <pip>
pyreadline                2.1                       <pip>
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.6.1                 py35_0
pywin32                   220                      py35_1
pyyaml                    3.12                     py35_0
pyzmq                     15.4.0                   py35_0
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.3.3                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.1.2                    py35_0
quandl                    3.0.1                    py35_0
requests                  2.12.4                   py35_0
requests-file             1.4.1                    py35_0
requests-file             1.4.1                     <pip>
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.14                  py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.18.1              np111py35_0
scs                       1.2.6                     <pip>
seaborn                   0.7.1                     <pip>
setuptools                27.2.0                   py35_1
setuptools                34.3.3                    <pip>
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.18                     py35_0
sip                       4.18.1                    <pip>
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.6                    py35_0
spyder                    3.0.0                    py35_0
sqlalchemy                1.1.4                    py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
theano                    0.8.2                    py35_0
Theano                    0.8.2                     <pip>
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.4.1                    py35_0
traitlets                 4.3.0                    py35_0
tzlocal                   1.3                       <pip>
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
werkzeug                  0.11.11                  py35_0
wheel                     0.29.0                   py35_0
widgetsnbextension        1.2.6                    py35_0
win_unicode_console       0.5                      py35_0
wrapt                     1.10.6                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.3                    py35_0
xlwings                   0.10.0                   py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by ssanderson** [comment]
@MRehanMS what happens if you open a Python shell and run `import cvxopt`?  CVXPY isn't doing anything special around finding CVXOPT as far as I know, so failure to import CVXOPT likely isn't an issue specific to cvxpy.

**Comment by SteveDiamond** [comment]
This question is really about how to install CVXOPT. It has nothing to do with CVXPY. I suggest you ask in the CVXOPT github repo.

**Comment by MRehanMS** [comment]
The CVXOPT works perfectly fine standalone - SO no, it isn't about CVXOPT.
I have used it standalone in my code, and it is fine - just that CVXPY is
unable to find it

Regards

Mohamed Rehan M S
+91 89 468 222 55

**Comment by SteveDiamond** [comment]
I see. That's very strange though. CVXOPT will appear in ``installed_solvers`` in CVXPY so long as``import cvxopt`` executes without error. So if CVXOPT is not listed as a solver, that means CVXOPT can't be imported. That's why I think it's an issue with installing CVXOPT. Can you show me the output of the following script:
```
import cvxpy
import cvxopt
print(cvxpy.installed_solvers())
```

**Comment by Iakl** [comment]
> 



> I see. That's very strange though. CVXOPT will appear in `installed_solvers` in CVXPY so long as`import cvxopt` executes without error. So if CVXOPT is not listed as a solver, that means CVXOPT can't be imported. That's why I think it's an issue with installing CVXOPT. Can you show me the output of the following script:
> 
> ```
> import cvxpy
> import cvxopt
> print(cvxpy.installed_solvers())
> ```

Im having this issue now. When i ran this code, the output tells me that CVXOPT is installed:
`['CVXOPT', 'ECOS', 'ECOS_BB', 'GLOP', 'GLPK', 'GLPK_MI', 'GUROBI', 'OSQP', 'PDLP', 'SCIPY', 'SCS']`    
However, when i try to solve with CVXOPT as the solver, the not installed error pops up
