### ISSUE TITLE
cvxpy doesn't fill in values for solved SDP

### ISSUE THREAD

**Issue by vlad17** [cvxgrp/cvxpy#349]
When I run the following code (which attempts to recover points in Euclidean space given pairwise distances), SCS exits successfully, but does not fill in the optimal values.

    import scipy.spatial.distance as dist
    import numpy as np
    import cvxpy

    np.random.seed(1234)
    dim = 2
    X=np.random.randn(3,dim)
    D = dist.squareform(dist.pdist(X))
    m = len(D)
    xs = cvxpy.Variable(m, dim)
    zs = cvxpy.Variable(m, m)
    Bs = [cvxpy.bmat([
        [zs[i, j] * np.identity(dim), (xs[i, :] - xs[j, :]).T],
        [xs[i, :] - xs[j, :], zs[i, j]]])
            for i in range(m) for j in range(i + 1, m)]

    objective = cvxpy.Minimize(cvxpy.sum_entries(zs))
    constraints = [cvxpy.lambda_min(B) >= 0 for B in Bs]
    constraints.append(D <= zs)
    constraints.append(xs[0, :] == 0)
    for i in range(m):
        constraints.append(cvxpy.norm(xs[i, :]) <= 2 * D.sum())
    prob = cvxpy.Problem(objective, constraints)

    print('optimal', prob.solve(solver=cvxpy.SCS, eps=1e-10), 'actual', D.sum())
    print('frobenius norm of error in recovered distances', np.linalg.norm(zs.value - D))
    print(zs.value)
    print(xs.value)

This is a bounded SDP, so the optimum should be achieved. In particular, this results in the following output:

	optimal 36.526621411992686 actual 36.5266213204
	frobenius norm of error in recovered distances 2.05506548556e-08
	[[  2.66458914e-09   1.30211220e+00   2.39574230e+00   6.76816215e-01
	    1.14620689e+00]
	 [  1.30211220e+00   2.66458914e-09   2.46500264e+00   6.58299103e-01
	    2.39435725e+00]
	 [  2.39574230e+00   2.46500264e+00   2.66458914e-09   2.19512647e+00
	    3.21528593e+00]
	 [  6.76816209e-01   6.58299096e-01   2.19512647e+00   2.66458914e-09
	    1.81436170e+00]
	 [  1.14620688e+00   2.39435725e+00   3.21528593e+00   1.81436170e+00
	    2.66458914e-09]]
	[[ 0.  0.]
	 [ 0.  0.]
	 [ 0.  0.]
	 [ 0.  0.]
	 [ 0.  0.]]

This is on Anaconda Python 3.6, cvxpy '0.4.9'

**Comment by SteveDiamond** [comment]
I tried the code. Everything looks fine to me on the cvxpy end. Are you certain your problem formulation is correct? The solution it gives you is optimal for the problem you specified.

**Comment by vlad17** [comment]
Oh you're right - I dropped some constraints. Sorry!
