### ISSUE TITLE
SolverStats not reported for GLPK

### ISSUE THREAD

**Issue by RhysU** [cvxgrp/cvxpy#350]
I noticed that GLPK isn't returning `num_iters`, ec. within SolverStats:
```
In [1]: import cvxpy

In [2]: cvxpy.__version__
Out[2]: '0.4.9'

In [3]: x = cvxpy.Variable(2)

In [4]: p = cvxpy.Problem(cvxpy.Minimize(cvxpy.norm1(x)), [x > 1])

In [5]: p.solve(cvxpy.GLPK)
GLPK Simplex Optimizer, v4.61
6 rows, 4 columns, 10 non-zeros
      0: obj =   0.000000000e+00 inf =   2.000e+00 (2)
      4: obj =   2.000000000e+00 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Out[5]: 2.0

In [6]: p.solver_stats
Out[6]: <cvxpy.problems.problem.SolverStats at 0x2ad6ed7332e8>

In [7]: p.solver_stats.__dict__
Out[7]: 
{'num_iters': None,
 'setup_time': None,
 'solve_time': None,
 'solver_name': 'GLPK'}
```

**Comment by SteveDiamond** [comment]
I have no idea how to get solver stats information from GLPK. It's not contained in the solver output. Why don't you figure it out and do a PR with a new version of the glpk_mi_intf.py that populates solver stats? Look at how ecos_intf.py etc handle solver stats info.

**Comment by RhysU** [comment]
https://github.com/cvxopt/cvxopt/blob/master/src/python/coneprog.py doesn't look encouraging in terms of obtaining timing.  The only thing that somes to mind is to hack it by having CVXPY time the GLPK solve.  Maybe setup = None and assume all time is in the solve.
