### ISSUE TITLE
Verbosity is ignored for GLPK

### ISSUE THREAD

**Issue by RhysU** [cvxgrp/cvxpy#351]
Reading through http://cvxopt.org/userguide/coneprog.html#optional-solvers suggests the verbosity logic at https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/solvers/glpk_intf.py#L72 is broken:
```
In [1]: import cvxpy

In [2]: cvxpy.__version__
Out[2]: '0.4.9'

In [3]: x = cvxpy.Variable(2)

In [4]: p = cvxpy.Problem(cvxpy.Minimize(cvxpy.norm1(x)), [x > 1])

In [5]: p.solve(cvxpy.GLPK, verbose=True)
GLPK Simplex Optimizer, v4.61
6 rows, 4 columns, 10 non-zeros
      0: obj =   0.000000000e+00 inf =   2.000e+00 (2)
      4: obj =   2.000000000e+00 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Out[5]: 2.0

In [6]: p.solve(cvxpy.GLPK, verbose=False)
GLPK Simplex Optimizer, v4.61
6 rows, 4 columns, 10 non-zeros
      0: obj =   0.000000000e+00 inf =   2.000e+00 (2)
      4: obj =   2.000000000e+00 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
Out[6]: 2.0
```

Other reading at that link suggests other options may be broken as `solvers.options['glpk']` appears nowhere in the code if I'm reading it correctly.  Unless the intent is for a user to supply 'gplk' as an option with a dictionary of parameters.

**Comment by RhysU** [comment]
I'm unclear what should work absent documentation at http://www.cvxpy.org/en/latest/tutorial/advanced/index.html

**Comment by RhysU** [comment]
Confirmed that
```
In [7]: p.solve(cvxpy.GLPK, glpk={'msg_lev': 'GLP_MSG_OFF'})
Out[7]: 2.0
```
works as a way to turn off verbosity.

**Comment by RhysU** [comment]
Possibly related to #251

**Comment by RhysU** [comment]
Have confirmed that other options like
```
'glpk': {
            # Use two-phase dual simplex; switch to primal should dual fail
            'meth': 'GLP_DUALP',
            # Enable using the LP presolver
            'presolve': 'GLP_ON'
        }
```
appear to take effect.

**Comment by RhysU** [comment]
As a final comment, getting that 'presolve' option documented would help a lot of folks.  The presolve makes a big difference, and it is surprising (to me) that it is off by default.

**Comment by SteveDiamond** [comment]
I fixed the verbosity issue on master and also made the presolve on by default. I'm also surprised that the GLPK/CVXOPT default is presolve off. Also, now you can pass in solver options as described in the CVXPY documentation, eg,
```
prob.solve(solver=GLPK, meth='GLP_DUALP')
```
