### ISSUE TITLE
CVXPY crashes, Python 3.6 (works on Python 2.7)

### ISSUE THREAD

**Issue by SteliosStefanatos** [cvxgrp/cvxpy#352]
Consider the following optimization problem setup

```
import numpy as np
import cvxpy

S = np.array([[0.04, 0.006, -0.004, 0],[0.006, 0.01, 0., 0.],[-0.004, 0., 0.0025, 0.],[0., 0., 0., 0.]])
p = np.array([0.12, 0.1, 0.07, 0.03])
mu = 0.1
vx = cvxpy.Variable(4)
cons = [cvxpy.sum_entries(vx) == 1, vx>=0]
```
When I attempt to define the objective as 

`obj = cvxpy.Minimize(-p*vx + mu*cvxpy.quad_form(vx,S))`

it crashes the kernel (Python 3.6.1 on Linux). On Python 2.7.13 it works fine (and I can proceed in obtaining the optimal solution).

(Version information: CVXPY 0.4.9, Numpy 1.12.1)

**Comment by SteveDiamond** [comment]
I need a proper crash report. Try running it under gdb so you can see where in the code the crash happens.

**Comment by SteliosStefanatos** [comment]
@SteveDiamond Thank you for your response.

Unfortunately, this debugging task is beyond my skills... I was wondering if someone else could reproduce the error. The only error message I managed to get is 

`Intel MKL FATAL ERROR: Cannot load libmkl_avx.so or libmkl_def.so.`

Again, this error happens only when `cvxpy.Minimize` is invoked and only on Python 3.6 (BTW, I am working on Anaconda).

**Comment by jwkvam** [comment]
Seems like you have some issue with your mkl libs and your py3 env. You could try installing nomkl and reinstalling scipy numpy and the like to remove that dependency.

**Comment by SteliosStefanatos** [comment]
So I guess the issue is on me. I will give this try, thanks for your help!

**Comment by SteliosStefanatos** [comment]
Indeed, this was apparently issue with my python 3.6 environment. I created another minimal env. and everything works fine. Again, thank you all for your help!
