### ISSUE TITLE
cvxpy (Frobenius) inner product 

### ISSUE THREAD

**Issue by jtebert** [cvxgrp/cvxpy#355]
I want to find the matrix M that maximizes the elementwise inner product of A and M ([Frobenius inner product](https://en.wikipedia.org/wiki/Frobenius_inner_product). However, from reading the documentation and from googling, I couldn't find any way to do this (or to linearize and compute the regular inner product). When I asked on StackOverflow, they suggested I turn here.

**Comment by SteveDiamond** [comment]
You can write ``cvxpy.trace(A.T*B)`` or ``cvxpy.sum_entries(cvxpy.mul_elemwise(A,B))``.
