### ISSUE TITLE
ECOS fails for a problem where some variables are constrained to be constants

### ISSUE THREAD

**Issue by jwkvam** [cvxgrp/cvxpy#356]
I have a problem where I have 5 variables and I'm doing some custom branch and bound stuff. For this instance 2 of the variables are constrained to be zero exactly and ECOS fails to solve it. CVXOPT works though. In addition, I tried removing the completely constrained variables and then ECOS is able to solve it.

I didn't try tuning the ECOS parameters at all. I did increase the max_iters but it stops after 200 or so. The script and data follow. Not sure if this is worth reporting upstream. I am able to work around this so it's not a big deal.

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import pickle

import numpy as np
import cvxpy
from cvxpy import Variable, Minimize, Problem, norm, Parameter, sum_entries

data = pickle.load(open('data.pkl', 'rb'))

lower = np.zeros(5)
upper = np.ones(5)
upper[[0, 3]] = 0

# Problem 1 (removed variables which are constrained to constants)
devs = Variable(5)
obj = norm(data['used_weights'].T * devs - data['wave'] - np.zeros(128))
penalty = sum_entries(devs)
objective = Minimize(obj)
constraints = [lower <= devs, devs <= upper]
problem = Problem(objective, constraints)

# Problem 2 (removed variables which are constrained to constants)
devs2 = Variable(3)
filt = [1, 2, 4]
obj = norm(data['used_weights'][filt].T * devs2 - data['wave'])
penalty = sum_entries(devs2)
objective = Minimize(obj)
constraints = [np.zeros(3) <= devs2, devs2 <= np.ones(3)]
problem2 = Problem(objective, constraints)

problem2.solve('ECOS')
problem.solve('ECOS')
```
[data.pkl.zip](https://github.com/cvxgrp/cvxpy/files/948458/data.pkl.zip)

**Comment by SteveDiamond** [comment]
Unfortunately ECOS fails sometimes on unexpected problems. You should report this as an ECOS issue: https://github.com/embotech/ecos
