### ISSUE TITLE
Nosetest errors with conda installation PY36 (Linux)

### ISSUE THREAD

**Issue by Surfer46** [cvxgrp/cvxpy#357]
Hi all,

I have installed anaconda with python 3.6 in linux and then created a new environment where I have installed cvxpy with:
conda install -c cvxgrp cvxpy

Then I also installed nose and have obtained 25 errors. Most of them saying that "the solver SCS is not installed" but I have checked that there is an installed SCS (version=1.2.6). 

Here the complete output:
[nosetest.txt](https://github.com/cvxgrp/cvxpy/files/968397/nosetest.txt)

Thanks,

**Comment by SteveDiamond** [comment]
I'm not convinced you installed cvxpy correctly. Can you import cvxpy, print "cvxpy.__file__" and do the same with SCS? I suspect you installed them in different versions of Python.

**Comment by Surfer46** [comment]
Doing exactly the same except for "conda create -n cvxpy27 python=2.7" instead of "conda create -n CVXenv" I got everything working fine (0 errors in the nose tests, scs imported without errors, etc). With respecto to what you say: I can import cvxpy, but not SCS. I don't understand the -print "cvxpy.file"- thing. When I run print(cvxpy.file) it says that cvxpy has no attribute 'file'. Of course it won't work for scs neither.

The error that I get when I run "import scs"  is the following: 

ImportError                               Traceback (most recent call last)
<ipython-input-2-6c0240a18355> in <module>()
----> 1 import scs

/home/sergio/anaconda3/envs/CVXenv/lib/python3.6/site-packages/scs.py in <module>()
      2 from warnings import warn
      3 from scipy import sparse
----> 4 import _scs_indirect
      5 
      6 __version__ = _scs_indirect.version()

ImportError: liblapack.so.3: cannot open shared object file: No such file or directory

**Comment by SteveDiamond** [comment]
Sorry, somehow my response got autocorrected. It's ``cvxpy.__file__`` not ``cvxpy.file``. I test with Anaconda 2, not Anaconda 3, so maybe that's why I've never seen this error before. I would try installing lapack and blas through Anaconda.

**Comment by Surfer46** [comment]
I tried today from scratch and still getting the same errors.

**Comment by SteliosStefanatos** [comment]
Had the same issue as @Surfer46 (new conda env with python 3.6). I first did `conda install blas -c conda-forge` with no success. However, with

`conda install lapack -c conda-forge` 

I was able to import SCS properly as well as call it from CVXPY.

**Comment by rwong01** [comment]
I had the same issue installing w python 3.6 on linux. @SteliosStefanatos 's comment worked successfully for me; nosetest completed with no errors.
