### ISSUE TITLE
MIP problem

### ISSUE THREAD

**Issue by wade2018** [cvxgrp/cvxpy#361]
Hey, can you give a example about Mixed Integer Programming,thank you, very much.

**Comment by sschnug** [comment]
There is one in ```examples/tsp_mip.py```.

Keep in mind, that you should provide a good MIP-solver (and the default one ECOS_BB is not).

**Comment by wade2018** [comment]
Thanks

**Comment by sbarratt** [comment]
@sschnug What is an example of a good MIP-solver that I can plug in with cvxpy?

**Comment by sschnug** [comment]
@sbarratt Commercials (Gurobi, Mosek, Fico) > Coin-OR Cbc > GLPK. (Cplex=Commercial has no support yet).

The commercial ones (above available for free in academics) are the most advanced and should be quite tunable through their parameters. Cbc is very competitive, but the interface within cvxpy is somewhat limited (branch 1.0 has much better defaults).

(It's possible, that there is a huge difference in the availability of interfaces between cvxpy 0.4.11 and the 1.0 branch; Cbc-interface changed and i think there was a lot of work on Gurobi, Mosek and Fico interfaces)

**Comment by SteveDiamond** [comment]
To chime in here, the only development going forward will be on the 1.0 branch so I recommend trying it. I will only patch 0.4 if someone finds a horrible bug.
