### ISSUE TITLE
Enhancement Request - 2nd smallest eigenvalue of the Laplacian

### ISSUE THREAD

**Issue by jwgwalton** [cvxgrp/cvxpy#363]
Hello @SteveDiamond,

Is it possible to get an implementation of a function which returns the 2nd smallest eigenvalues/ eigenvalues of the Laplacian of a matrix.

I've started to try and implement an atom myself, from some investigative work I couldn't put a restraint on it without creating an atom. My knowledge of convex optimisation isn't that great and wondered if this might be relatively easy for you to implement. 

Cheers

Joseph Walton

**Comment by enzobusseti** [comment]
you could do this using lambda_sum_smallest(L, 2), the sum of the 2
smallest eigenvalues. it is a concave function, so constraints of the
form  lambda_sum_smallest(L,
2) >= a are valid. the other sense of the inequality (and thus the
equality) are not valid. if L is a laplacian matrix then the smallest
eigenvalue is 0, thus by summing the 2 smallest eigenvalues you are in fact
selecting only the second smallest.

**Comment by jwgwalton** [comment]
Thank you very much, just got it working. Can this be closed? Cheers
