### ISSUE TITLE
Problem running a matrix completion algorithm using convex optimization

### ISSUE THREAD

**Issue by ytang928** [cvxgrp/cvxpy#366]
I tried to use cvxpy to run a matrix completion algorithm

<img width="570" alt="screen shot 2017-06-28 at 7 01 21 pm" src="https://user-images.githubusercontent.com/29212318/27668188-6ff5bdf4-5c34-11e7-9bd2-d26817d41c72.png">

The code goes like this
<img width="780" alt="screen shot 2017-06-28 at 7 04 32 pm" src="https://user-images.githubusercontent.com/29212318/27668226-ad32978c-5c34-11e7-841a-7024838ea57a.png">

The code doesn't run, getting a warning that 'UserWarning: Forming a nonconvex expression (affine)*(affine).", and throwing an exception that 'Cannot evaluate the truth value of a constraint or chain constraints, e.g., 1 >= x >= 0.'

Anyone could help me figure out where the problem is?
Is that my way for passing the constraints goes wrong, or my specification or multiplying two cyxpy-typed variables(matrices)?

It seem that this way of writing constraints dynamically does not work, then what can I do?

**Comment by ytang928** [comment]
I tried a faked instance to pass the constraints and it seems not work.

<img width="422" alt="screen shot 2017-06-28 at 7 17 15 pm" src="https://user-images.githubusercontent.com/29212318/27668515-6f9b4eda-5c36-11e7-84e8-fae87c12dfd2.png">

Could anyone help me figure out how to dynamically arrange the constraints (i.e., according to the inputs)

**Comment by SteveDiamond** [comment]
If you multiply two variables together, that's not a convex problem. You could use the DMCP package, but CVXPY alone won't work. You'll be better off constructing a boolean matrix B that is 1 wherever A is not nan. Then add the constraint ``X[B] == A[B]``.
