### ISSUE TITLE
How can I use constain to get a positive Variable?

### ISSUE THREAD

**Issue by cloga** [cvxgrp/cvxpy#367]
I use follow code want to get positive weight to build portfolio.
n = len(data.columns)
w0 = cvx.Variable(n)
return_vec0 = data.values.T
mu0 = np.asmatrix(data.mean()).T
ret0 = mu0.T * w0
C0 = np.asmatrix(np.cov(return_vec0))
risk0 = cvx.quad_form(w0, C0)
prob0 = cvx.Problem(cvx.Minimize(risk0), 
               [cvx.sum_entries(w0) == 1, 
                w0 >= 0,
                ])
but I get some weight < 0.

and I find the sample code in tutorial, also get negative value after using constrain.

![image](https://user-images.githubusercontent.com/1320343/27911296-23b2fabc-628b-11e7-951b-9bdf1a97385c.png)

as you can see, the sample code use constrain to limit x between 0 and 1 , but the result get negative value

**Comment by SteveDiamond** [comment]
The solutions cvxpy returns are always correct up to numerical tolerance, meaning every entry is within around 1e-5 of the true optimal value. So the negative values you see are 0 within numerical tolerance.
