### ISSUE TITLE
Include name of variables in the repr.

### ISSUE THREAD

**Issue by musically-ut** [cvxgrp/cvxpy#368]
Currently, the `__repr__` implementation for `Variable`, `Bool`, `Int` classes, etc. only show the variable sizes and not the names:

```python
>> CVX.Variable(rows=2, cols=3, name='A')
Variable(2, 3)
```

Personally, I would like to see the `name` of the variable (if provided) as well. I would find that more informative and it can be very handy during debugging sessions.

This will also be compatible with the current documentation of `repr` string and I expect this not to be a breaking change.

I can work on a PR if this sounds like an enhancement `cvxpy` would be open to.

**Comment by SteveDiamond** [comment]
I would be fine with adding the name to the repr for Variable. Feel free to make a PR.

**Comment by musically-ut** [comment]
Was closed by #371.
