### ISSUE TITLE
repeated semidefinite constraint?

### ISSUE THREAD

**Issue by edwintye** [cvxgrp/cvxpy#372]
When using a (positive) semidefinite constraint, it would appear the translated problem has generate such a constraint twice.  Maybe I do not have the correct understanding of how cvxopt (or scs) arranges the constraints Gx <= h but I have checked both matrices G, h and the top k rows is the same as the bottom k rows.  

A minimal example would be:

```python
import cvxpy
import numpy as np
N = 5
magic_square = np.zeros((N,N), dtype=int)

n = 1
i, j = 0, N//2

while n <= N**2:
    magic_square[i, j] = n
    n += 1
    newi, newj = (i-1) % N, (j+1)% N
    if magic_square[newi, newj]:
        i += 1
    else:
        i, j = newi, newj

X = cvxpy.Semidef(N)
obj = cvxpy.Minimize(cvxpy.trace(X*magic_square))
## constraint the diagonal to ensure the problem is bounded
constraints = [X >> 0, cvxpy.diag(X) == 1]
prob = cvxpy.Problem(obj, constraints)
cvxopt_data = prob.get_problem_data(cvxpy.CVXOPT)
print(cvxopt_data['dims'])
```

**Comment by SteveDiamond** [comment]
Remove the ``X >> 0`` constraint. It's implied by ``X = cvxpy.Semidef(N)``.
