### ISSUE TITLE
suitesparse error Mac Sierra

### ISSUE THREAD

**Issue by jacob-roth** [cvxgrp/cvxpy#378]
System details:
- macOS Sierra 10.12.5
- python 2.7

I'm trying to install `cvxpy` through Anaconda with prebuilt `cvxopt` packages for OpenBLAS with the following:
1. `conda install -c conda-forge cvxopt`
2. `conda install -c cvxgrp cvxpy`
3. `conda install nose`
4. `nosetests cvxpy`

I can install `cvxopt` and `cvxpy` with the first two commands, but running the nosetests, I receive many errors as the tests are running:
`....EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE......EEEEEE...`
and receive the following failure message:
```

======================================================================
FAIL: Test the list of installed solvers.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jakeroth/anaconda/lib/python2.7/site-packages/cvxpy/tests/test_solvers.py", line 540, in test_installed_solvers
    self.assertEqual(str(cm), "The solver LS cannot solve the problem.")
AssertionError: 'dlopen(/Users/jakeroth/anaconda/lib/python2.7/site-packages/cvxopt/cholmod.so, 2): Library not loaded: @rpath/libsuitesparseconfig.4.5.3.dylib\n  Referenced from: /Users/jakeroth/anaconda/lib/python2.7/site-packages/cvxopt/cholmod.so\n  Reason: image not found' != 'The solver LS cannot solve the problem.'

----------------------------------------------------------------------
Ran 3226 tests in 13.515s

FAILED (errors=1489, failures=1)

Reason: image not found
```
Can you please advise? Thanks

**Comment by SteveDiamond** [comment]
You should install everything through cvxgrp.
