### ISSUE TITLE
Support CPLEX too

### ISSUE THREAD

**Issue by AlexFleischer** [cvxgrp/cvxpy#379]

**Comment by AlexFleischer** [comment]
Could help
Thanks

**Comment by SteveDiamond** [comment]
Someone from CPLEX said they were working on an interface. I haven't heard from them in a long time, but I'm not going to do it myself when someone is willing to contribute.

**Comment by rayvadams** [comment]
I contacted the CPLEX development team.  They do not intend to support cvxpy unless they receive "more requests".  Instead, they point those who inquire to their proprietary APIs.

**Comment by shenker** [comment]
Any news?

**Comment by rkersh** [comment]
I've created a pull request here: #506.

**Comment by bstellato** [comment]
A simple QP interface should already be working inside CVXPY. I wrote it a while ago and it was working. Check out [this file]( https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/qp_solvers/cplex_qpif.py).

**Comment by rkersh** [comment]
Now that pull request #506 has been merged, should this issue be closed?
