### ISSUE TITLE
Slice constraints with negative indices

### ISSUE THREAD

**Issue by calebsander** [cvxgrp/cvxpy#381]
Here is a simple problem:
````python
import cvxpy as cvx

x = cvx.Variable(2)
objective = cvx.Minimize(x[0] + x[1])
constraints = [x >= 1]
problem = cvx.Problem(objective, constraints)
problem.solve()
````
The solution is pretty clearly `x = [1, 1]`. I can express the constraints as `[x[:2] >= 1]` or `[x[-2] >= 1, x[-1] >= 1]` instead and it works fine. But if I use `[x[-2:] >= 1]`, it considers the problem infeasible despite being exactly the same problem. This contradicts the documentation, which says "Non-scalar expressions can also be sliced into using the standard Python slicing syntax".

**Comment by SteveDiamond** [comment]
This is at a minimum fixed in 1.0. I've lost track a bit.
