### ISSUE TITLE
Working with Pyomo

### ISSUE THREAD

**Issue by JohnRobson** [cvxgrp/cvxpy#385]
I know that CVXPy works with several Solvers, I wonder if it also can work with Pyomo (http://www.pyomo.org/) as another solver.

There is some plan to integrate CVXPy and Pyomo?

**Comment by sschnug** [comment]
Technically Pyomo is not a solver, but a modelling-framework (providing wrappers for other solvers).

I (non cvxpy-dev) don't see any gain in supporting it as cvxpy is already a (powerful) modelling-tool and you won't gain anything using a second one, except for maybe some solver unsupported in cvxpy yet.

In my opinion, the only particularly special thing about Pyomo is support for non-convex optimization (Bonmin, Couenne and co), but this is not that compatible to cvxpy anyway (conceptually).

**Comment by SteveDiamond** [comment]
Agreed, integration with Pyomo doesn't make much sense. Integration with nonlinear solvers is something I'm considering adding after the cvxpy 1.0 rewrite (which is now 95% complete!).

**Comment by denfromufa** [comment]
Related: https://groups.google.com/forum/#!searchin/pyomo-forum/cvx%7Csort:relevance/pyomo-forum/__LHannajCM/d8i_598UCgAJ
