### ISSUE TITLE
Possible outdated documentation for cvxopt setup

### ISSUE THREAD

**Issue by felipegb94** [cvxgrp/cvxpy#388]
Hi Cvxpy devs,

I encountered the following issue in the documentation.

**Problem**

In the install guide under "Install with CVXOPT support", it says that when installing everything to Anaconda that you should install nomkl first (`conda install nomkl`) and then install cvxopt. However, installing nomkl will overwrite the numpy and scipy installations which breaks some parts of cvxpy because of the following error:

``` 
nosetests cvxpy
.......................................................Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

**Solution**

I removed nomkl which reverted my numpy and scipy installations to what was installed when I ran `conda install -c cvxgrp cvxpy`. After removing nomkl I was able to use cvxopt without any problems.

**Comment by SteveDiamond** [comment]
Ok thanks. I dropped the instructions to install nomkl.
