### ISSUE TITLE
MemoryError when optimizing large matrix 

### ISSUE THREAD

**Issue by tobyclh** [cvxgrp/cvxpy#389]
Hello, I am trying to work on the equation
min |Ax - B|
subject to sum(x) = 1
and min(x) >= 0
A is of shape (2400256, 256) and x is just a vector.
And I ran out of memory a while after starting.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

`    k = cvx.Variable(len(w0))  

    constraints = [0 <= k, k <= 1, cvx.sum_entries(k) == 1]  

    _image_gram = image_gram * len(w0)  

    c = np.abs(np.dot(database_gram, w0) - _image_gram) 

    objective = cvx.Minimize(cvx.sum_entries(  
        cvx.square(database_gram * k - _image_gram)))  

    prob = cvx.Problem(objective, constraints)`

Is this expected behaviour?

**Comment by SteveDiamond** [comment]
It will crash if you have a massive matrix. Regardless you should be reducing your problem by multiplying out ``A^TA``. (So the objective is ``quad_form(x, A.T.dot(A)) + A.T.dot(B)``.)

**Comment by wendy7707** [comment]
@tobyclh Hello, I saw you have used CNTK in unity, I have one more questions, I  have installed the CNTK and Eval Nuget package in Unity,and change the target platform to X64, but when I write"using Microsoft.MSR.CNTK....", then it always shows the error missing MSR......, would you please tell me how to solve it? Thank you so much!
