### ISSUE TITLE
conda installation requires libgcc

### ISSUE THREAD

**Issue by nbren12** [cvxgrp/cvxpy#391]
I just tried to install cvxpy using `conda install -c cvxgrp cvxpy`, but I get the following error when running the sample program:

    ImportError: <long path>/libstdc++.so.6: version `GLIBCXX_3.4.21' not found 

I was able to fix this by installing the `libgcc` anaconda package. Maybe this should be added to this project's `meta.yaml` file.

**Comment by SteveDiamond** [comment]
Which OS are you installing on? Which version of cvxpy? I'm fairly certain libgcc is listed as a dependency in conda.

**Comment by ThomasA** [comment]
Isn't this issue fixed by the current install instructions: http://www.cvxpy.org/en/latest/install/index.html#mac-os-x-and-linux?
