### ISSUE TITLE
cvxpy vs cvx dual problem issue

### ISSUE THREAD

**Issue by harrisReservoir** [cvxgrp/cvxpy#393]
I'm switching over from cvx in matlab to cvxpy in python, and I'm having issues reproducing the exact output of the matlab code. Here is a simple example:

In matlab:
```
cvx_solver scs
cvx_begin
    variable x(10)
    maximize ( sum(log(x)) )
subject to
    ones(1, 10) * x == 10
cvx_end
```
In python:
```
x = cvxpy.Variable(10)
obj = cvxpy.Maximize(cvxpy.sum_entries(cvxpy.log(x)))
cons = [cvxpy.sum_entries(x) == 10]
prob = cvxpy.Problem(obj, cons)
solver_settings = {'normalize': True, 'scale':1.00,
                   'eps': 1.49e-08, 'alpha': 1.5, 'use_indirect': True}
prob.solve(solver = cvxpy.SCS, verbose = True, **solver_settings)
```

The matlab output:

> Calling SCS 1.2.7: 30 variables, 11 equality constraints
> 
> 	SCS v1.2.7 - Splitting Conic Solver
> 	(c) Brendan O'Donoghue, Stanford University, 2012-2016
> Lin-sys: sparse-indirect, nnz in A = 20, CG tol ~ 1/iter^(2.00)
> eps = 1.49e-08, alpha = 1.50, max_iters = 10000, normalize = 1, scale = 1.00
> Variables n = 11, constraints m = 30
> **Cones:	exp vars: 0, dual exp vars: 30**
> Setup time: 9.80e-03s
>  Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
>      0| 1.#Je+00  1.#Je+00 -1.#Je+00 -1.#Je+00  1.#Je+00  1.#Je+00  2.71e-03 
>     60| 5.88e-11  1.17e-10  2.60e-09 -2.20e-10 -2.82e-09  1.92e-15  1.45e-02 
> Status: Solved
> Timing: Solve time: 1.51e-02s
> 	Lin-sys: avg # CG iterations: 1.00, avg solve time: 6.00e-006s
> 	Cones: avg projection time: 1.75e-004s
> Error metrics:
> dist(s, K) = 0.0000e+00, dist(y, K*) = 0.0000e+00, s'y/|s||y| = 2.1960e-10
> |Ax + s - b|_2 / (1 + |b|_2) = 5.8809e-11
> |A'y + c|_2 / (1 + |c|_2) = 1.1658e-10
> |c'x + b'y| / (1 + |c'x| + |b'y|) = 2.6034e-09
> c'x = -0.0000, -b'y = -0.0000
> Status: Solved
> Optimal value (cvx_optval): -2.82339e-09

And the python output:

> 	SCS v1.2.7 - Splitting Conic Solver
> 	(c) Brendan O'Donoghue, Stanford University, 2012-2016
> Lin-sys: sparse-indirect, nnz in A = 30, CG tol ~ 1/iter^(2.00)
> eps = 1.49e-08, alpha = 1.50, max_iters = 10000, normalize = 1, scale = 1.00
> Variables n = 20, constraints m = 31
> Cones:	primal zero / dual free vars: 1
> **exp vars: 30, dual exp vars: 0**
> Setup time: 3.05e-04s
>  Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
>      0|      inf       inf      -nan      -inf       inf       inf  3.48e-03 
>     60| 3.36e-10  1.45e-09  3.88e-09 -2.55e-09  1.33e-09  1.11e-15  1.25e-02 
> Status: Solved
> Timing: Solve time: 1.25e-02s
> 	Lin-sys: avg # CG iterations: 1.15, avg solve time: 6.38e-05s
> 	Cones: avg projection time: 1.36e-04s
> Error metrics:
> dist(s, K) = 1.0960e-15, dist(y, K*) = 0.0000e+00, s'y/|s||y| = 6.6107e-11
> |Ax + s - b|_2 / (1 + |b|_2) = 3.3580e-10
> |A'y + c|_2 / (1 + |c|_2) = 1.4518e-09
> |c'x + b'y| / (1 + |c'x| + |b'y|) = 3.8831e-09
> c'x = -0.0000, -b'y = 0.0000
> Out[86]: 2.553093059785613e-09

While the solution is pretty close, the "exp vars" and "dual exp vars" are swapped. I see that cvx sometimes auto-dualizes, and apparently cvxpy does not (http://ask.cvxr.com/t/why-is-cvx-2-0-not-solving-the-dual-problem/264 and http://web.stanford.edu/~stevend2/cvx_core.pdf.) Is this the reason for the difference, and is this a potential cause for other optimal differences with larger problems? Is there a way to force dualization in cvxpy?

**Comment by SteveDiamond** [comment]
The solutions are identical within numerical tolerance. That's all a solver can promise. Dualizing would not change this fundamental limitation.
