### ISSUE TITLE
Constraint on part of a variable

### ISSUE THREAD

**Issue by hkalexling** [cvxgrp/cvxpy#397]
Thanks for the great package!

I wonder if it's possible to express the following constraint with `cvxpy`?

![screen shot 2017-09-23 at 6 50 11 pm](https://user-images.githubusercontent.com/7845831/30772789-8d6b5772-a095-11e7-8243-508ebeafca10.png)

I've tried something like this

```python
# n = 20
# x = Variable(n)
constraints = [0 <= x, x <= 1]
for t in range(1, n + 1):
	xSum = 0
	for i in range(1, t + 1):
		xSum += x[i - 1]
	c = 0 <= a * exp(xSum) + xSum - t
	constraints.append(c)
```

but got the not following DCP rules error:

> cvxpy.error.DCPError: Problem does not follow DCP rules.

**Comment by SteveDiamond** [comment]
It's not a convex constraint. You can try DCCP: https://github.com/cvxgrp/dccp
