### ISSUE TITLE
No option to limit the number of threads

### ISSUE THREAD

**Issue by dburkhardt** [cvxgrp/cvxpy#399]
I'm using CVXPY on a shared computer, and it looks like there's no option to limit the number of threads the CVXPY uses. This is especially annoying because CVXPY doesn't recognize that `multiprocessing.cpu_count()` looks at the number of threads, not the number of CPU cores and so actually uses a pool size twice as large as is appropriate on CPUs that support hyperthreading.

I think the offending line is here:
https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/problem.py#L384

It would be really nice if I could pass in a value for the number of threads I want so that my jobs will play nicely on this shared resource.

I would be happy to help implement this, but I'm not the most experienced with CVXPY. I would be happy to help test though!

**Comment by SteveDiamond** [comment]
Why don't you try fixing it? Just add another keyword argument for _solve and pass it to the parallel_solve method.

**Comment by sarahwie** [comment]
I had trouble with this as well- even after removing this line. It seems that the processes are being spawned by the solver being imported, e.g. by SCS in my case.

**Comment by sschnug** [comment]
@sarahwie In this case this has not much to do with cvxpy (imho). A lot of software (even numpy) will just use all what's available for all it's BLAS/LAPACK-based core-functions. The same applies to SCS.

Start [here](https://github.com/cvxgrp/scs/issues/82) for something related.

**Comment by sarahwie** [comment]
@sschnug Thanks. That got me where I needed to be.
