### ISSUE TITLE
support for MIP for mosek

### ISSUE THREAD

**Issue by pixiez** [cvxgrp/cvxpy#400]
I think Mosek does support MIP, is it possible for cvxpy to support this for the MOSEK intf as well? thanks

**Comment by SteveDiamond** [comment]
The Mosek MIQP solver is supported in cvxpy 1.0.

**Comment by rileyjmurray** [comment]
The current version of mosek_intf.py (which should be part of 1.0?) does not have MIP support. 

https://github.com/cvxgrp/cvxpy/commit/cde8afbaccdb561621491905ceac75796792df5d

On line 33, MIP_CAPABLE = False.

**Comment by rileyjmurray** [comment]
This has been added to the latest version of cvxpy 1.0. @SteveDiamond , can you close this issue as resolved?
