### ISSUE TITLE
CVXPY fails under Anaconda 4.4

### ISSUE THREAD

**Issue by ThomasA** [cvxgrp/cvxpy#401]
I have installed and tested CVXPY in a "vanilla" Anaconda 4.4.0 environment created and installed as follows:
```bash
$ conda create -n anaconda4 anaconda=4
$ source activate anaconda4
$ conda install -c cvxgrp cvxpy libgcc
$ nosetests cvxpy
```
The tests fail with an endless series of:

> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa

and then:

> ImportError: numpy.core.multiarray failed to import

Strangely, CVXPY still seems to work - at least in the sense that it can solve the example problem I show in #402.

My platform is Linux (up-to-date Ubuntu 16.04).

**Comment by SteveDiamond** [comment]
Please verify this failure with 1.0 to reopen.
