### ISSUE TITLE
CVXPY fails under Anaconda 5.0

### ISSUE THREAD

**Issue by ThomasA** [cvxgrp/cvxpy#402]
I have installed and tested CVXPY in a "vanilla" Anaconda 5.0.0 environment created and installed as follows:
```bash
$ conda create -n anaconda5 anaconda=5
$ source activate anaconda5
$ conda install -c cvxgrp cvxpy libgcc
$ nosetests cvxpy
```
The tests succeed, but when I try to run the following script:
```python
import cvxpy as cvx
import numpy as np

E = np.random.randn(2,2)

# CVXPY set-up
X = cvx.Variable(2,2)
mu = cvx.Parameter(sign='positive', value=.1)
objective = cvx.Minimize(cvx.norm(E - X, 'fro')**2 + mu * cvx.norm(X, 'nuc'))
problem = cvx.Problem(objective)
# CVXPY solve
problem.solve()
```
Python dies on me with the following error message:
> Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.

However, this example actually works under the set-up I described in #401 despite the fact that CVXPY's tests fail in that environment.

My platform is Linux (up-to-date Ubuntu 16.04).

**Comment by SteveDiamond** [comment]
I'm sorry, all these versions of anaconda are too much for me to deal with. Can someone help me set up automated building/testing for conda packages?

**Comment by ThomasA** [comment]
Yes, I think I should be able to. I have some experience with this.

**Comment by SteveDiamond** [comment]
Thanks so much! It's something I've struggled to set up and would really appreciate help with.

**Comment by ThomasA** [comment]
I should be able to help out next week. Please remind me if I forget.

**Comment by SteveDiamond** [comment]
@ThomasA do you still have time to look at this?

**Comment by ThomasA** [comment]
Yes, tomorrow afternoon should be good.

**Comment by ThomasA** [comment]
I can see that you have testing set up on Travis. I have struggled a bit with this too for another project. Could you try and have a look at our set-up here: https://github.com/SIP-AAU/Magni/blob/master/.travis.yml. One of the key details is to set `language: generic` instead of `language: python` in order to avoid Travis' standard Python set-up messing with the Anaconda that we install using the miniconda installer (see the `before_install` section).

Ask away if you are in doubt about something and I will get some much needed exercise of my memory on this matter :-)

**Comment by SteveDiamond** [comment]
I see, you run it on many conda versions. Is there any reason to support older versions though?

**Comment by ThomasA** [comment]
Sorry, I forgot to answer this. The reason we support older versions is that we would like to provide some stability. So if we do not strictly need to break compatibility with earlier versions, we prefer to check that we don't do so by accident.

**Comment by jdechalendar** [comment]
I am having the same issue as the one described here and in #401  - is there a previous version of anaconda for which cvxpy can be considered stable until this is fixed?

**Comment by SteveDiamond** [comment]
Please verify this failure with the current version to reopen. It is probably fixed.
