### ISSUE TITLE
Nonnegative constraints gives solution with negative entries

### ISSUE THREAD

**Issue by luissv7** [cvxgrp/cvxpy#406]
Hi, 
Below, I attach code to recreate a cvxpy problem with the constraint `x >= 0` that gives a solution with negative entries. The constraint matrix is appended as a txt file with only nonnegative entries. `x.value` gives a vector with some negative entries. I am running this code using Python 3.6.1, OSX High Sierra,numpy 1.12.1, cvxpy 0.4.10

[constraints.txt](https://github.com/cvxgrp/cvxpy/files/1425125/constraints.txt)

```python
import cvxpy,numpy

CONSTRAINTS = numpy.loadtxt('constraints.txt', delimiter = ',')

x = cvxpy.Variable(26)
list_of_constraints = [x >= 0]

obj = cvxpy.Minimize(cvxpy.pnorm(x, 1))

for i in range(len(CONSTRAINTS)):
    list_of_constraints.append(1 <= numpy.transpose(CONSTRAINTS[i]) * x)

prob = cvxpy.Problem(obj, list_of_constraints)   
y = prob.solve()
print(x.value)
```

**Comment by sschnug** [comment]
This is perfectly fine behaviour! Look at the magnitudes of your negative values: -3.23045926e-11 ~ 0!

As floating-point math and iterative-algorithms are used, there will always be small errors. This is the case here!

The default-solver also is an interior-point method, which only approximate the solution (as precise as as wanted in theory; limits in practice). Commercial solvers sometimes use an additional Simplex-method-step to *clean* results.
