### ISSUE TITLE
CVXPY 1.0 parameters confer no performance benefit

### ISSUE THREAD

**Issue by farrellm** [cvxgrp/cvxpy#410]
In 0.4.11, using parameters and resolving a problem for different parameter values gives a significant performance improvement. Equivalent code with 1.0 runs in the same time whether only parameter values are change or if the whole problem is recreated from scratch.

test code:

```python
import time
import random
import statistics

import cvxpy as cvx
import numpy as np


def problem():
    x = cvx.Variable(shape=(8,))
    mu = cvx.Parameter(shape=(8,))

    u = mu.T * x - cvx.sum_squares(x) - 0.1 * cvx.sum(cvx.abs(x) ** (3/2))
    c = [-0.2 <= x, x <= 0.2]

    return {"problem": cvx.Problem(cvx.Maximize(u), c),
            "variable": x,
            "forecast": mu}

def with_compile():
    p = problem()
    p["forecast"].value = np.random.normal(size=8)
    p["problem"].solve()
    return p


p0 = problem()
def without_compile():
    p0["forecast"].value = np.random.normal(size=8)
    p0["problem"].solve()
    return p0


functions = with_compile, without_compile
times = {f.__name__: [] for f in functions}

for i in range(100):  # adjust accordingly so whole thing takes a few sec
    func = random.choice(functions)
    t0 = time.time()
    func()
    t1 = time.time()
    times[func.__name__].append((t1 - t0) * 1000)

for name, numbers in times.items():
    print('FUNCTION:', name, 'Used', len(numbers), 'times')
    print('\tMEDIAN', statistics.median(numbers))
    print('\tMEAN  ', statistics.mean(numbers))
    print('\tSTDEV ', statistics.stdev(numbers))
```

**Comment by wkschwartz** [comment]
I can confirm this report. Here's my output from the script in the ticket. Ran this on Python 3.7, macOS 10.13.5, Core i7 1.7GHz. cvxpy version 1.0.6.

```
FUNCTION: with_compile Used 59 times
	MEDIAN 27.675867080688477
	MEAN   30.742257328356725
	STDEV  7.337865665104942
FUNCTION: without_compile Used 41 times
	MEDIAN 29.330015182495117
	MEAN   31.004120663898746
	STDEV  7.93215427430337
```

I also ran the script replacing `p0["problem"].solve()` with `p0["problem"].solve(warm_start=True)` in the `without_compile` function, and I got the same result.

I then ran the script at the [docs for `warm_start`](https://www.cvxpy.org/tutorial/advanced/index.html#warm-start), which I had to modify by replacing `prob.solve_time` with `prob.solver_stats.solve_time`. This was the output:

```
First solve time: 21.465058394000003
Second solve time: 1.385668273
```

Maybe `warm_start=True` only helps with certain subclasses of problems, and this should be documented?

Personally, I'm particularly anxious that it work with MILPs. Does it?

**Comment by frk2** [comment]
Same here - using Parameters in my problem has no benefit and is the same as recreating the problem from scratch. I could paste my problem if the issue is problem specific. cvxpy 1.0.6 on Ubuntu 18.04

**Comment by frk2** [comment]
@SteveDiamond to clarify does this mean that using Parameters has no performance benefit in 1.x but does in 0.4.x?

**Comment by wkschwartz** [comment]
It looks like [ECOSBB](https://www.rdocumentation.org/packages/CVXR/versions/0.99/topics/ECOS_BB-class) and [CBC](https://www.coin-or.org/Doxygen/Cbc/classCoinWarmStartBasis.html) might support warm starting as well. Even without baked-in warm-start support, maybe it would help to be able to pass in a known-feasible initial start point for the solvers. If I understand LP and MILP correctly, this can help speed things up substantially when using simplex or branch and bound, respectively. Perhaps `warm_start=True` could pass along a known-feasible initial point to solvers that don't directly support warm starting?

**Comment by SteveDiamond** [comment]
@frk2 they do different things in the two versions. I was talking about the benefits n 1.x. @wkschwartz I agree providing initial points would be a good feature, but it's a fair amount of work.

**Comment by rileyjmurray** [comment]
@SteveDiamond to clarify: did you ever intend for (or do you think it reasonable to strive for) Parameter objects to confer compile-time benefits?

If not, it might be helpful to specify the benefits / use-cases of Parameter objects in the documentation. See #553 for what I mean by a "non compile-time" benefit of Parameter objects.

**Comment by SteveDiamond** [comment]
This should be improved since #664
