### ISSUE TITLE
cvxgrp on conda lacking behind

### ISSUE THREAD

**Issue by tschm** [cvxgrp/cvxpy#413]
Hello, the current version on conda's cvxgrp is 0.4.9 for Linux users. Can you please provide updates for 0.4.11 and 1.0? Many thanks

**Comment by h-vetinari** [comment]
1.0 on conda would be cool... :)

**Comment by iyer** [comment]
Pip install of cvxpy reveals
cvxpy.__version__ = 0.4.11
scs.__version__ = 2.0.2

Conda install of cvxpy reveals
cvxpy.__version__ = 0.4.9
scs.__version__ = 1.2.6

Can we bring cvxpy on conda to the same level as pip?

**Comment by SteveDiamond** [comment]
1.0 is released now on pip, conda, etc.
