### ISSUE TITLE
time cost of the prob.solve()

### ISSUE THREAD

**Issue by dagelailege** [cvxgrp/cvxpy#416]
I run pro.solve() in a for cycle，as follows:
 for i in rang(700):
         #produce some expressions
         #produce some constrains
         objective = Minimize(sum(expressions))
         prob = Problem(objective, constrains)
         result = prob.solve()
the cost time of one cycle will increase with cycles . what i mean, with the same expressions and constrains, the cost time of the solver is not the same when i is not the same

**Comment by sschnug** [comment]
Please:

- Present a **valid** code-example; in the best-case: something we can run too (synthetic-data?)
- Include your at least *semi-scientific* benchmarks (how are you measuring this? what variance is observed)
- Tell us which version of python, cvxpy and other used components (solver?) you are using

**Comment by dagelailege** [comment]
my code is like this:
for slot in range(721):
    inflow_path = "./car_flow_np_20160903/{}_in_flow.npy".format(slot)
    ninflow_path = "./car_nflow_np_20160903/{}_out_nflow.npy".format(slot)
    data_array, _= get_data_size(inflow_path = inflow_path,map_array = map_array)    #this method return a array
    constrains_array = get_constrains(ninflow_path = ninflow_path,map_array = map_array)  #this method return a array
    # Construct the problem.
    x = Variable(region_acc,region_acc*8)
    expressions = []
    constrains = []
    for i in range(region_acc):
        for j in range(region_acc):
            fcont1 = data_array[i][j]              
            fout = x[i,j*8+0] + x[i,j*8+1] +x[i,j*8+2] +x[i,j*8+3] +x[i,j*8+4] +x[i,j*8+5] +x[i,j*8+6] +x[i,j*8+7]
            fin =  (x[i,(j+1)*8+0] if j<(region_acc-1) else 0) \
                + (x[i+1,(j+1)*8+4] if j<(region_acc-1) and i<(region_acc-1) else 0)\
                + (x[i+1,j*8+1] if i<(region_acc-1) else 0)\
                + (x[i+1,(j-1)*8+6] if i<(region_acc-1) and j>0 else 0)\
                + (x[i,(j-1)*8+2] if j>0 else 0)\
                + (x[i-1,(j-1)*8+7] if i>0 and j>0 else 0)\
                + (x[i-1,j*8+3] if i>0 else 0)\
                + (x[i-1,(j+1)*8+5] if i>0 and j<(region_acc-1) else 0)
            fcont2 = cont1                      
            f = pos(fcont1 +fin - fout - fcont2)          
            expressions += [f]
    for i in range(region_acc):
        for j in range(region_acc*8):
            constrains += [0 <= x[i,j],x[i,j] <= constrains_array[i][int(j/8)][j%8]]

    objective = Minimize(sum(expressions))
    prob = Problem(objective, constrains)

    # The optimal objective is returned by prob.solve().
    time1 = time.time()
    result = prob.solve()
    time2 = time.time()
    spend_time = time2 - time1
    # The optimal value for x is stored in x.value.

    x_array = np.array(x.value)
    np.save("./optimize_20160903/{}_optimize_solution.npy".format(slot),x_array)
    print ("fininshed {}".format(slot))
my problem is that when the slot is increasing, the spend_time is increasing too, from 50s to 300s after 100-200 cycles. It is amusing that if I start with slot = 200 , the spend_time will be 50s, but if I start with slot = 0, when cycle until slot = 200， the spend_time will be about 100-200s.
My python is 2.7,cvxpy is 0.4.11, and the slover is ecos-2.0.5

**Comment by sschnug** [comment]
Did you check memory-consumption? Is it gradually increasing? Is it hitting your memory-bound?

**Comment by dagelailege** [comment]
yes, i have checked my memory-consumption, it just increases a little about 20% and just less than 10% usage of my total memory.

**Comment by SteveDiamond** [comment]
I'm sorry, but as @sschnug points out we can't diagnose this without being able to reproduce it ourselves. Your example includes files we don't have. I'll reopen if you have a reproducable example.
