### ISSUE TITLE
Problem with ecos and numpy multiarray

### ISSUE THREAD

**Issue by tschm** [cvxgrp/cvxpy#418]
I am using cvxpy in a rather large docker container and can not modify the numpy version. 
I have installed cvxpy using anaconda and run into the import multiarray numpy problem, as in

![image](https://user-images.githubusercontent.com/2046079/33857027-5dbfd2be-deca-11e7-9352-005f24c6e3eb.png)

This is very urgent, I am very sorry

**Comment by SteveDiamond** [comment]
Install cvxpy from source if you're having problems.

**Comment by SteveDiamond** [comment]
These installation issues are hard for me to debug, so I apologize that I haven't fixed it yet.

**Comment by tschm** [comment]
ok, I overwrote the existing numpy installation in the container. Works for tomorrow :-) :+1:

**Comment by tschm** [comment]
@SteveDiamond :+1: Thank you for acting so quickly. I am not sure I should open the can of installing from source :-)
