### ISSUE TITLE
Broken links under Example at webpage

### ISSUE THREAD

**Issue by TobiasRitschel** [cvxgrp/cvxpy#419]
The links under Examples at the website (at http://www.cvxpy.org/en/latest/examples/index.html) appear to be broken. I didn't try all of them, but all the ones I tried gave me this error message

```
Error 503 No healthy backends
No healthy backends
Guru Mediation:
Details: cache-bma7025-BMA 1513241309 119240031
Varnish cache server
```

The code under "Details" varies. I've tried with the following browsers (all on Windows 7 64-bit)

- Opera 49.0 (49.0.2725.47)
- Internet Explorer 11 (11.0.9600.18837, update version: 11.0.48 (KB4047206))
- Firefox Quantum (57.0.2 (32-bit))
- Google Chrome (63.0.3239.84 (Official Build) (64-bit))

Best regards
Tobias

**Comment by sschnug** [comment]
As these are rendered (external service) notebooks, this probably was due to [nbwiever](https://twitter.com/XuBramble/status/941180866650292229) being down.

Most of these examples (some not found) work now again.

**Comment by TobiasRitschel** [comment]
Ah okay, sorry for the inconvenience. They work for me too.
