### ISSUE TITLE
Gurobi MIP solver in v1.0

### ISSUE THREAD

**Issue by befelix** [cvxgrp/cvxpy#421]
In cvxpy 1.0 there seems to be an issue with the Gurobi solver interface. In particular, it doesn't seem to respect boolean and integer flags for variables.

```
var = cvxpy.Variable(1, boolean=True)
objective = cvxpy.Maximize(var)
constraints = []
prob = cvxpy.Problem(objective, constraints)
prob.solve(solver='GUROBI', verbose=True)
```

fails with an `Unbounded model` error.

If I change the constraint to `[var <= 1.5]`, I get the non-integer solution `var=1.5`.

Thanks,
Felix

**Comment by SteveDiamond** [comment]
This should be fixed now for QPs on the latest commit. I'm still working on making it work for all problems that GUROBI can solve.

**Comment by SteveDiamond** [comment]
Ok this is fixed now for all GUROBI interfaces.
