### ISSUE TITLE
Accessings value of feastol, abstol, and reltol

### ISSUE THREAD

**Issue by jackalack** [cvxgrp/cvxpy#423]
there is a verbose flag for `.solve` which enables you to log values of feastol, abstol, and reltol; however, I do not see the ability to access these variables.  There is the attribute `._solver_stats` which includes 'solver_name', 'solve_time', 'setup_time', 'num_iters', but no information regarding the tolerances.  Is there a way to access the values of these tolerances without parsing the logs?

**Comment by SteveDiamond** [comment]
You can set the tolerances yourself and record them separately:
http://www.cvxpy.org/en/latest/tutorial/advanced/index.html#solve-method-options

**Comment by jackalack** [comment]
Sorry my question was not clear.  I am not interested in the tolerances that I set, but rather the tolerances realized.  Specifically, I am interested in the tolerances achieved when it fails to solve.  These tolerances are logged, but I cannot find a way to access them beyond parsing the logs.

<img width="605" alt="screen shot 2018-01-08 at 5 43 14 pm" src="https://user-images.githubusercontent.com/7672771/34785813-19e8cf76-f5e7-11e7-96e2-dc0f0cfbd285.png">

**Comment by SteveDiamond** [comment]
I've decided this feature will not be added any time soon, unless somebody wants to take it on. It's unfortunately quite a large project.
