### ISSUE TITLE
Documentation on CVXPY website incorrect

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#424]
In the CVXPY docs (http://www.cvxpy.org/en/latest/tutorial/advanced/) it's stated that CVXOPT supports the exponential cone. 

A paper describing the mathematics of CVXOPT (http://www.seas.ucla.edu/~vandenbe/publications/coneprog.pdf) makes no reference to the exponential cone. 

As a matter of practice, I have not been able to get CVXOPT to solve even toy examples of relative entropy programs (which ECOS handles very well). Perhaps CVXOPT supports the negative logarithm, but not the negative entropy and/or perspective functions?

As a side note: ECOS was initially based on CVXOPT, but was extended to support the exponential cone around 2015 (see Serrano's thesis: https://web.stanford.edu/group/SOL/dissertations/ThesisAkleAdobe-augmented.pdf). I can't find any references indicating that CVXOPT was extended in a similar way.

**Comment by SteveDiamond** [comment]
CVXPY uses CVXOPT to solve exponential cone problems using the general convex solver: http://cvxopt.org/userguide/solvers.html
You're quite right that this is not a particularly robust approach, but it is valid.

**Comment by rileyjmurray** [comment]
Gotcha. Thank you for the lightning fast reply!

Although, in the same way that the documentation mentions that 'SCS may be faster, but less accurate', perhaps include a remark of the type 'CVXOPT uses a general convex solver, and is less robust than ECOS and SCS for exponential cone problems.'
