### ISSUE TITLE
Cannot install /feature/dccp branch

### ISSUE THREAD

**Issue by dkobak** [cvxgrp/cvxpy#425]
I am trying to install feature/dccp branch, based on the instructions in https://github.com/cvxgrp/dmcp. Unfortunately, I get lots of errors.

After successfully running `python setup.py install`, I try to `import cvxpy as cvx` and get 
```
File "/home/localadmin/tmp/cvxpy/cvxpy/utilities/__init__.py", line 21, in <module>
    import grad
```
I looked into the master branch, and it has `from . import grad` in the same file, so I edited this line and the next few. Now when importing I get a different error: 
```
File "/home/localadmin/tmp/cvxpy/cvxpy/expressions/constants/constant.py", line 22, in <module>
    import cvxpy.settings as s
AttributeError: module 'cvxpy' has no attribute 'settings'
```
(In the master branch this line is missing...)

Am I doing something wrong?

**Comment by SteveDiamond** [comment]
Eventually dccp will be made compatible with cvxpy 1.0. For the moment people need to use the dccp branch. @dkobak try uninstalling and reinstalling everything. This looks like a bad install issue.
