### ISSUE TITLE
CVXPY 1.0: Support 0-element vectors

### ISSUE THREAD

**Issue by farrellm** [cvxgrp/cvxpy#426]
A nice-to-have feature to simplify some problems.
Support of 0-element vectors for Variables, Parameters and functions of numpy arrays (eg, hstack).

This comes up because I have an optimization problem that is parameterized by a natural number, and sometimes the argument is 0. This results in constructions like:

```python
import cvxpy
import numpy

n = 0

cvxpy.Variable((n,))
cvxpy.Parameter((n,))

x = cvxpy.Variable((1,))
a = numpy.zeros((n,))
cvxpy.hstack([x, a])
```

**Comment by SteveDiamond** [comment]
This is similar to #344 If it is addressed it will be in 1.0, after the full 1.0 release.
