### ISSUE TITLE
Issues with installation and portfolio optimization examples

### ISSUE THREAD

**Issue by glim1971** [cvxgrp/cvxpy#427]
I installed CVXPY 0.4.11 in Windows 7 + Anaconda 5 + Python 3.6 (64-bit) by the following steps:

1. Download and install Microsoft Visual C++ Build Tools 2015.

2. Open Anaconda Prompt as administrator and run the following commands:
      `conda install cvxcanon ecos`
      `pip install scs cvxpy multiprocess`

### Installation Issue
When I tested the installation by running the command `nosetests cvxpy`, I got 1769 tests ran with 1 failure. The failure is in the test of the optimal inaccurate status (see the screen shot attached below). **Should I be concerned about this failure?**

![image](https://user-images.githubusercontent.com/33199825/35077776-cc1602b4-fbcc-11e7-901f-9f2d7d77b96a.png)

### Issues with Portfolio Optimization Examples
When I ran all the examples in the link below, I found two issues. 
[http://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb](url)

**Issue 1:**
Cell [30] gave the error message below. 

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-5-05614bf6eea0> in <module>()
>      16 for idx, L_val in enumerate(L_vals):
>      17      plt.bar(np.arange(1,n+1) + 0.25*idx - 0.375, w_vals[idx][indices], color=colors[idx], 
> ---> 18              label=r"$L^{\max}$ = %d" % L_val, width = 0.25)
>      19 plt.ylabel(r"$w_i$", fontsize=16)
>      20 plt.xlabel(r"$i$", fontsize=16)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py in bar(*args, **kwargs)
>    2646                       mplDeprecation)
>    2647     try:
> -> 2648         ret = ax.bar(*args, **kwargs)
>    2649     finally:
>    2650         ax._hold = washold
> 
> C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py in inner(ax, *args, **kwargs)
>    1715                     warnings.warn(msg % (label_namer, func.__name__),
>    1716                                   RuntimeWarning, stacklevel=2)
> -> 1717             return func(ax, *args, **kwargs)
>    1718         pre_doc = inner.__doc__
>    1719         if pre_doc is None:
> 
> C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in bar(self, *args, **kwargs)
>    2085                 edgecolor=e,
>    2086                 linewidth=lw,
> -> 2087                 label='_nolegend_',
>    2088                 )
>    2089             r.update(kwargs)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\patches.py in __init__(self, xy, width, height, angle, **kwargs)
>     657         """
>     658 
> --> 659         Patch.__init__(self, **kwargs)
>     660 
>     661         self._x = xy[0]
> 
> C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\patches.py in __init__(self, edgecolor, facecolor, color, linewidth, linestyle, antialiased, hatch, fill, capstyle, joinstyle, **kwargs)
>     101         self.set_fill(fill)
>     102         self.set_linestyle(linestyle)
> --> 103         self.set_linewidth(linewidth)
>     104         self.set_antialiased(antialiased)
>     105         self.set_hatch(hatch)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\patches.py in set_linewidth(self, w)
>     349                 w = mpl.rcParams['axes.linewidth']
>     350 
> --> 351         self._linewidth = float(w)
>     352         # scale the dash pattern by the linewidth
>     353         offset, ls = self._us_dashes
> 
> TypeError: only length-1 arrays can be converted to Python scalars
> 

**Issue 2:**
The output of cell [32] in the example is 2.5 (using ECOS 1.1.1 as the default solver); however, I got 4.6 (using ECOS 2.0.4 as the default solver). See my detailed output below. **Why is the difference so large?**

> ECOS 2.0.4 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS
> 
> It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
>  0  -7.950e-01  -5.980e+00  +2e+04  1e+00  1e-01  1e+00  3e+00    ---    ---    2  1  - |  -  - 
>  1  -1.109e+01  -1.151e+01  +2e+03  9e-01  2e-02  5e-01  4e-01  0.9890  1e-01   1  1  1 |  0  0
>  2  -1.026e+01  -1.033e+01  +2e+02  3e-01  2e-03  5e-03  3e-02  0.9042  7e-04   1  1  1 |  0  0
>  3  -6.679e+00  -6.713e+00  +2e+02  2e-01  6e-04  7e-03  3e-02  0.2597  4e-01   1  2  2 |  0  0
>  4  -6.405e+00  -6.426e+00  +1e+02  9e-02  4e-04  1e-02  2e-02  0.6494  7e-01   2  2  2 |  0  0
>  5  -5.931e+00  -5.944e+00  +1e+02  6e-02  3e-04  8e-03  2e-02  0.3532  4e-01   2  2  2 |  0  0
>  6  -6.372e+00  -6.386e+00  +1e+02  6e-02  3e-04  1e-02  2e-02  0.1742  9e-01   2  2  2 |  0  0
>  7  -5.548e+00  -5.554e+00  +7e+01  4e-02  2e-04  7e-03  1e-02  0.6668  5e-01   2  2  2 |  0  0
>  8  -5.615e+00  -5.621e+00  +7e+01  3e-02  2e-04  7e-03  1e-02  0.2541  9e-01   2  2  2 |  0  0
>  9  -5.035e+00  -5.038e+00  +4e+01  2e-02  7e-05  3e-03  7e-03  0.5214  1e-01   2  2  2 |  0  0
> 10  -4.917e+00  -4.920e+00  +3e+01  1e-02  5e-05  2e-03  5e-03  0.4483  6e-01   2  2  2 |  0  0
> 11  -4.728e+00  -4.730e+00  +1e+01  5e-03  2e-05  8e-04  2e-03  0.7257  3e-01   2  2  2 |  0  0
> 12  -4.657e+00  -4.658e+00  +8e+00  2e-03  1e-05  4e-04  1e-03  0.6407  3e-01   2  2  2 |  0  0
> 13  -4.636e+00  -4.637e+00  +6e+00  2e-03  9e-06  2e-04  1e-03  0.6347  7e-01   2  2  2 |  0  0
> 14  -4.617e+00  -4.617e+00  +3e+00  1e-03  4e-06  1e-04  6e-04  0.5208  1e-01   2  2  3 |  0  0
> 15  -4.608e+00  -4.608e+00  +2e+00  5e-04  2e-06  5e-05  3e-04  0.7115  3e-01   2  3  3 |  0  0
> 16  -4.604e+00  -4.604e+00  +7e-01  2e-04  9e-07  2e-05  1e-04  0.7158  2e-01   2  2  2 |  0  0
> 17  -4.602e+00  -4.602e+00  +1e-01  4e-05  2e-07  4e-06  2e-05  0.8303  6e-02   2  2  2 |  0  0
> 18  -4.602e+00  -4.602e+00  +2e-02  4e-06  2e-08  4e-07  3e-06  0.9137  2e-02   2  2  2 |  0  0
> 19  -4.601e+00  -4.601e+00  +4e-03  1e-06  5e-09  9e-08  6e-07  0.8251  8e-02   2  2  2 |  0  0
> 20  -4.601e+00  -4.601e+00  +9e-04  2e-07  1e-09  2e-08  1e-07  0.8232  7e-02   2  2  2 |  0  0
> 21  -4.601e+00  -4.601e+00  +6e-04  2e-07  7e-10  1e-08  9e-08  0.5486  4e-01   2  2  2 |  0  0
> 22  -4.601e+00  -4.601e+00  +3e-05  1e-08  4e-11  8e-10  6e-09  0.9407  3e-03   2  1  1 |  0  0
> 23  -4.601e+00  -4.601e+00  +3e-06  9e-10  4e-12  7e-11  5e-10  0.9867  7e-02   2  2  2 |  0  0
> 24  -4.601e+00  -4.601e+00  +2e-07  6e-11  3e-13  5e-12  4e-11  0.9250  8e-04   2  1  1 |  0  0
> 25  -4.601e+00  -4.601e+00  +2e-08  9e-12  2e-14  4e-13  3e-12  0.9849  7e-02   2  1  1 |  0  0
> 
> OPTIMAL (within feastol=9.5e-12, reltol=3.9e-09, abstol=1.8e-08).
> Runtime: 0.521075 seconds.
> 
> 4.601466742642543

**Comment by sschnug** [comment]
Just some superficial remarks:

- i would not be scared about this one failed test (but the developers should be probably)
- issue 1 seems to be a matplotlib-problem only
  - it's hard to tell what's the origin (and i'm too lazy to debug this): changes in matplotlib or the big changes in cvxpy (cvxopt vs. nump/scipy mats); the error itself is typically calling something which works on a scalar with a numpy-argument which has > 1 elements
  - it's possible, that some of the examples are not working anymore!
- it's unclear to me how you did check those 2 different solvers (if setup was done correctly; if cvxpy is able to work with such an old ECOS-version); first i thought of some bugs repaired (as equilibration) but 1.1.1 should already incorporated that
  - in general i would trust the more recent version, but that's just guessing
  - solve it with cvxopt / SCS or any commercial one if available and compare the results!
