### ISSUE TITLE
Confusion about license

### ISSUE THREAD

**Issue by jotterbach** [cvxgrp/cvxpy#428]
Hello,

I have a question about the licensing of this package as I intend to use it for some projects. I see that you removed the CVXopt dependency and changed the license from GPLv3 to Apache v2.0. However, the [ECOS](https://github.com/embotech/ecos) package that is listed in the install requirements of the setup.py file is licensed under GPLv3 (as it depends on CVXopt). Hence I wondered if the Apache license is applicable if I depend on this package?

It would be great if you could help me understand the licensing in this case.

**Comment by SteveDiamond** [comment]
ECOS is not really a dependency. CVXPY works fine without it. The Apache v2.0 license is definitely only valid if you use CVXPY without ECOS. You can contact the authors of ECOS (https://www.embotech.com/) if you want to use it with a different license. I would prefer if everything were Apache v2.0, but I don't have control over the solvers.
