### ISSUE TITLE
Library not loaded: /usr/local/lib/libgfortran.2.dylib

### ISSUE THREAD

**Issue by chakpongchung** [cvxgrp/cvxpy#429]
`python linsep.py
`
Traceback (most recent call last):
  File "linsep.py", line 5, in <module>
    from cvxopt import solvers, matrix, spmatrix, spdiag, log, exp, div
  File "/anaconda2/lib/python2.7/site-packages/cvxopt/__init__.py", line 32, in <module>
    import cvxopt.base
ImportError: dlopen(/anaconda2/lib/python2.7/site-packages/cvxopt/base.so, 2): Library not loaded: /usr/local/lib/libgfortran.2.dylib
  Referenced from: /anaconda2/lib/libopenblasp-r0.2.14.dylib
  Reason: image not found

Tried upgrade brew reinstall gcc. Use conda to install libgfortran

I am using MAC.

**Comment by SteveDiamond** [comment]
This is a CVXOPT problem. You should post there: http://cvxopt.org/
