### ISSUE TITLE
PSD matrices rejected by the value check in expressions/leaf.py

### ISSUE THREAD

**Issue by akisato-** [cvxgrp/cvxpy#442]
(This problem is closely related to https://github.com/cvxgrp/cvxpy/issues/415)

An attempt to store a positive semi-definite (PSD) matrix into cvxpy.Parameter((n,m), PSD=True) can be rejected, due to the value check in [expressions/leaf.py:344](https://github.com/cvxgrp/cvxpy/blob/1.0/cvxpy/expressions/leaf.py#L344).

```
344:            elif np.sum(self.project(val) != val):
```

Since self.project contains eigenvalue decomposition (see [expressions/leaf.py:290](https://github.com/cvxgrp/cvxpy/blob/1.0/cvxpy/expressions/leaf.py#L290)), the result might include small computation errors.

```
290:       elif any([self.attributes[key] for
291:                  key in ['symmetric', 'PSD', 'NSD']]):
292:            val = (val + val.T)/2
293:            if self.attributes['symmetric']:
294:                return val
295:            w, V = LA.eig(val)
296:            if self.attributes['PSD']:
297:                w = np.maximum(w, 0)
298:            else:  # NSD
299:                w = np.minimum(w, 0)
300:            return V.dot(np.diag(w)).dot(V.T)
```

I think that expressions/leaf.py:344 should be
```
elif np.sum(not np.allclose(self.project(val), val, rtol=rtol)):
```
after defining an appropriate `rtol` value.

You can reproduce this problem by the following test code.

```
import cvxpy as cvx
import numpy as np
np.random.seed(2)

a = np.random.normal(size=(100,100))
a2 = a.dot(a.T)    # This must be a PSD matrix.

b = (a2 + a2.T) / 2    # fixed
w, V = np.linalg.eig(b)
c = V.dot(np.diag(w)).dot(V.T)    # simulating self.project function
# You will see that np.max(c-a2) != 0 (1.22e-12 in this case)

d = cvx.Parameter((100,100), PSD=True)
d.value = a2
```

--> ValueError: Parameter value must be positive semidefinite.

**Comment by rileyjmurray** [comment]
For the test code you provided, I think "b" should be "b = (a2 + a2.T) / 2". Perhaps I'm misunderstanding?

Also (although not terribly important), the "np.max(c-a2)" calculation should probably be replaced by "np.max(np.abs(c-a2))".

**Comment by akisato-** [comment]
@rileyjmurray Thanks for the comments. 2. is what I meant exactly.

**Comment by rileyjmurray** [comment]
I've made the changes necessary to resolve this issue. It will be included in my next pull request.

**Comment by rileyjmurray** [comment]
This can be marked as resolved.
