### ISSUE TITLE
Constraint on matrix elements not working

### ISSUE THREAD

**Issue by prateeky2806** [cvxgrp/cvxpy#450]
Hello, I am trying to implement Lovasz Theta function, which is the solution of a sdp. 
max \sum_{i,j} Z 
subject to Z psd, Z(i,j)=0 if (i,j) \in E(G) where G is a Graph, trace(Z)=1
The second constraint which is Z(i,j)=0 if (i,j) \in E(G) where G is a Graph is the part not working. I am getting an error "NoneType' object is not subscriptable"
This is due to the fact that values of Z are none but I don't know any other way to put in this constraint.

This is the code:
```
import networkx as nx
import cvxpy as cvx

G = nx.random_regular_graph(2,5)
nv = G.number_of_nodes()

Z = cvx.Variable(nv,nv)
constraints = [Z>>0, cvx.trace(Z)==1, Z.value[tuple(np.array(G.edges()).T)] == 0]
obj = cvx.Maximize(cvx.sum_entries(Z))
prob = cvx.Problem(obj, constraints)
prob.solve()
```
Can someone please, tell me if this is even possible because all the constrains on matrix entries which I have seen in the examples are done using preimplemented functions, like, diag(Z)==0.

**Comment by sschnug** [comment]
Yes, that ```.value``` call looks troublesome! 

Look up the docs for the available functions, and if there is none to find:
-  what's wrong with an elementwise-multiplication (using ```multiply```)  ```cvx.multiply(aux, Z)``` where aux is describing the relation ```(i,j) in G``` (which you build a-priori with np.where or whatever networks is providing). 

(Maybe you want to consider using the mailing-list or gitter-chat for *non-issue* questions like these)

**Comment by prateeky2806** [comment]
@sschnug Writing the constraint as Z[tuple(np.array(G.edges()).T)] == 0 work but then then solvers are failing, I have tried all which support SDP, SCS MOSEK, CVXOPT. but failing in all cases. I think there is some issue with cvx. 
(I'll keep gitter-chat in mind for next time, )
