### ISSUE TITLE
Cannot evaluate the truth value ......

### ISSUE THREAD

**Issue by amztc34283** [cvxgrp/cvxpy#455]
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-115-e9c66f3e4487> in <module>()
      2 #    return [p[i]*x[i] if x[i] - q[i] <= 0 else p[i]*q[i] + p_disc[i]*(x[i] - q[i]) for i in range(5)]
      3 sum_of_r = one.T*r
----> 4 constraints = [c <= c_max, (r == p*x and 1 == 1)]
      5 obj = Maximize(sum_of_r)
      6 prob = Problem(obj, constraints)

/usr/local/lib/python2.7/dist-packages/cvxpy/constraints/leq_constraint.pyc in __nonzero__(self)
     64         Raising an error here prevents writing chained constraints.
     65         """
---> 66         return self._chain_constraints()
     67 
     68     def _chain_constraints(self):

/usr/local/lib/python2.7/dist-packages/cvxpy/constraints/leq_constraint.pyc in _chain_constraints(self)
     70         """
     71         raise Exception(
---> 72             ("Cannot evaluate the truth value of a constraint or "
     73              "chain constraints, e.g., 1 >= x >= 0.")
     74         )

Exception: Cannot evaluate the truth value of a constraint or chain constraints, e.g., 1 >= x >= 0.

My cvxpy version is 0.4.11. I have no idea what is causing this issue because I think the boolean expression is valid.

**Comment by SteveDiamond** [comment]
You can't use an "and" in your constraints. Only a list of equality and inequality constraints is allowed.
