### ISSUE TITLE
Any idea how to solve this non-convex problem?

### ISSUE THREAD

**Issue by ninoarsov** [cvxgrp/cvxpy#462]
Hi, 
I've been exploring cvxpy and its extensions in the last few days, so I am posting this here as a last resort before moving on with a different approach to solve my problem. 

I may not be aware of extensions other than qcqp, dccp, and dmcp.

I want to minimize a function that essentially looks like this:
[https://ibb.co/cEx5gc](url) (please copy and paste the link, github brings up a 404)

It represents two nested polynomial kernels of degree 2. The variable is x, while all the vectors and matrices that multiply x may contain entries of arbitrary sign.

I know this violates DCP, DCCP, and DMCP rules. However, it is not quadratic and is therefore inappropriate for QCQP, as well.

Are there some other extensions that this would make use of? I'm trying to plug this into a network lasso model, which is built on top of cvxpy.

P.S. I'm not an optimization guru whatsoever, so I believe some of you might be able to give me some clues.
Any suggestions would be much appreciated! 
Thank you,

**Comment by ninoarsov** [comment]
Thanks for your answer, Steven! 
Will be closing the issue since it really isn't one. 

DCMP says the "problem is not DCMP". I am thinking of debugging it for a while because DCMP now looks appropriate after taking a second look. 

Will be posting all related further questions on the gitter.
Thanks!

**Comment by uthsavc** [comment]
@ninoarsov did you ever debug the issue? I am running into a similar issue.

**Comment by ninoarsov** [comment]
Hi! Sorry for my late response.
No, I never managed to solve the issue, and later I realized that I do not need cvxpy at all.



________________________________

**Comment by SteveDiamond** [comment]
Out of curiosity where did this problem come from? It's an unusual objective function.
