### ISSUE TITLE
Warm start for SOCP (using SCS)

### ISSUE THREAD

**Issue by guillean** [cvxgrp/cvxpy#464]
This is more of a question than any issue in general, but, having seen #234 referencing a warm start for the SCS solver (using the last instance as the new solution), I was wondering if it was possible to directly specify all (primal/dual) variables in the SOCP as an initial starting point?

This is (at least personally!) useful since I have a closed-form solution for the optimization problem as one of the parameters becomes large (which is a starting point, say, for cross-validation), but constructing this initial solution numerically is an ill-conditioned problem—taking tens of thousands of iterations to converge to a useful estimate for reasonably-sized cases.

Thanks!

**Comment by rileyjmurray** [comment]
In the issue you linked, the poster mentioned "cvxpy/performance_tests/test_warmstart.py". That file contains a basic example. You can generalize that example by just assigning `my_var.value = some_numpy_array` where `my_var` is your desired CVXPY Variable object. I believe you can extend this to dual variables by calling `my_constr.dual_value = some_numpy_array` where `my_constr` is a CVXPY Constraint object.

Give that a shot.

As a side-note, questions like this are probably better suited to cvxpy's gitter channel. https://gitter.im/cvxgrp/cvxpy

**Comment by guillean** [comment]
Ah brilliant, thank you! For some reason I did totally skip over the `test_warmstart.py` file presented there. I'll give it a shot.

Thanks!
