### ISSUE TITLE
CVXPY expression become constant zero unexpectedly

### ISSUE THREAD

**Issue by XuanSomerville** [cvxgrp/cvxpy#468]
I am using CVXPY (version 1.0). I do not understand what causes the difference between a ZERO expression and a NONNEGATIVE expression as demonstrated by the following code:

```
import cvxpy as cv
a = cv.Variable(1)
b = cv.Variable(1)
print((cv.square(a-b)*1/(1e-6)).__repr__()) 
# Expression(CONSTANT, ZERO, (1,))
print((cv.square(a-b)*float(1/1e-6)).__repr__()) 
# Expression(CONVEX, NONNEGATIVE, (1,))
```

**Comment by rileyjmurray** [comment]
I think it boils down to strange behavior in CVXPY Constant objects (scalars are implicitly cast to this type during multiply operations like the ones you're doing).

```
from cvxpy.expressions.constants import Constant
print(Constant(value=1e-5).sign)  # zero
print(Constant(value=1e-4).sign)  # nonnegative
```

The `.sign` attribute of a Constant is determined by `cvxpy.interface.matrix_utilities.sign( ... )`. Right now that function has a tolerance of `1e-5`. I don't think we need a `tol` parameter here (let alone one so big). I just changed `tol=0` on my machine's local copy of cvxpy and reinstalled. After this change all nosetests pass, and your issue goes away.

@SteveDiamond  can you approve these changes?
