### ISSUE TITLE
svec equivalent in cvxpy

### ISSUE THREAD

**Issue by meijieru** [cvxgrp/cvxpy#470]
I want to implement following `cvx` code in `cvxpy`, but I could not find any equivalent for `svec` function.

```matlab
    Sk = randn(2*size(AA,2),size(AA,1));
    Skdd = Sk*dd; 
    SkAA = Sk*AA; %#ok<*NASGU>

    % Solve the SDLS problem
    cvx_begin sdp
        cvx_quiet(true)
        cvx_precision best
        variable Z(r,r) symmetric
        minimize norm(SkAA*svec(Z) - Skdd)
        Z >= 0 %#ok<NOPRT>
    cvx_end
```

Are there other ways to do that?

**Comment by rileyjmurray** [comment]
At present there is no dedicated svec function in cvxpy (at least, not one in the public-facing API). That said, the functionality is easy to implement in this specific context.

```
import cvxpy
import numpy as np
Z = cvxpy.Variable(shape=(n,n), symmetric=True)
upper_tri_blocks = [Z[i, np.arange(i,n)] for i in range(n)]
Z_as_vec = cvxpy.hstack(upper_tri)
```
To ensure correct behavior in the matrix-vector product `SkAA * svec(Z)`, you may need to reshape `Z_as_vec` by calling `Z_as_vec = cvxpy.reshape(Z_as_vec, shape=(Z_as_vec.shape[0], 1))`.

**Comment by meijieru** [comment]
Thanks very much!

**Comment by meijieru** [comment]
thanks
