### ISSUE TITLE
I got a error when I import cvxpy 1.0

### ISSUE THREAD

**Issue by hopesAccount** [cvxgrp/cvxpy#472]
`import cvxpy as cvx`

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-92b7f12ac8cd> in <module>()
      1 import numpy as np
      2 import matplotlib.pyplot as plt
----> 3 import cvxpy as cvx
      4 from numpy import pi, exp, sin, deg2rad, rad2deg
      5 from numpy.linalg import svd, norm

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/__init__.py in <module>()
     19 
     20 __version__ = "1.0.0"
---> 21 from cvxpy.atoms import *
     22 from cvxpy.constraints import NonPos, Zero, SOC, PSD
     23 from cvxpy.expressions.variable import Variable

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/atoms/__init__.py in <module>()
     18 """
     19 
---> 20 from cvxpy.atoms.geo_mean import geo_mean
     21 from cvxpy.atoms.harmonic_mean import harmonic_mean
     22 from cvxpy.atoms.lambda_max import lambda_max

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/atoms/geo_mean.py in <module>()
     21 import numpy as np
     22 import scipy.sparse as sp
---> 23 from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
     24                                          over_bound, prettydict)
     25 

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/utilities/power_tools.py in <module>()
     19 
     20 from fractions import Fraction
---> 21 from cvxpy.atoms.affine.reshape import reshape
     22 from cvxpy.atoms.affine.vstack import vstack
     23 from cvxpy.constraints.second_order import SOC

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/atoms/affine/reshape.py in <module>()
     18 """
     19 
---> 20 from cvxpy.atoms.affine.affine_atom import AffAtom
     21 import cvxpy.lin_ops.lin_utils as lu
     22 import numpy as np

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/atoms/affine/affine_atom.py in <module>()
     23 from cvxpy.atoms.atom import Atom
     24 from cvxpy.expressions.constants import Constant
---> 25 from cvxpy.CVXcanon.python import canonInterface
     26 from fastcache import clru_cache
     27 import scipy.sparse as sp

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/CVXcanon/python/canonInterface.py in <module>()
     30 
     31 from cvxpy.lin_ops import lin_op as lo
---> 32 import cvxpy.CVXcanon.python.CVXcanon as CVXcanon
     33 import numbers
     34 import numpy as np

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/CVXcanon/python/CVXcanon.py in <module>()
    227 _CVXcanon.KRON_swigconstant(_CVXcanon)
    228 KRON = _CVXcanon.KRON
--> 229 class LinOp(_object):
    230     __swig_setmethods__ = {}
    231     __setattr__ = lambda self, name, value: _swig_setattr(self, LinOp, name, value)

~/.conda/envs/py36/lib/python3.6/site-packages/cvxpy-1.0.0-py3.6-linux-x86_64.egg/cvxpy/CVXcanon/python/CVXcanon.py in LinOp()
    245     if _newclass:
    246         args = _swig_property(_CVXcanon.LinOp_args_get, _CVXcanon.LinOp_args_set)
--> 247     __swig_setmethods__["data_ndim"] = _CVXcanon.LinOp_data_ndim_set
    248     __swig_getmethods__["data_ndim"] = _CVXcanon.LinOp_data_ndim_get
    249     if _newclass:

AttributeError: module '_CVXcanon' has no attribute 'LinOp_data_ndim_set' `

**Comment by rileyjmurray** [comment]
Did you have a prior installation of cvxpy (either in a virtual environment, or globally)?

**Comment by hopesAccount** [comment]
yes, I have cvxpy 0.4.9 on my global environment

**Comment by akshayka** [comment]
Marking as closed; d139dbabb58627b5397180060f0942fdcb87e7aa renamed CVXCanon to cvxcore, so having a prior installation of CVXPY will no longer result in this error.
