### ISSUE TITLE
OSQP doesn't recognize a trivial QP problem.

### ISSUE THREAD

**Issue by XuanSomerville** [cvxgrp/cvxpy#473]
I am using cvxpy version 1.0.

I don't understand why solving the following trivial problem returns "Problem could not be reduced to a QP, and no conic solvers exist among candidate solvers (['OSQP'])".

```
import cvxpy as cv
u = cv.Variable(2)
constr = []
constr += [cv.abs(u[1]-u[0])<=100]
prob = cv.Problem(cv.Minimize(cv.sum_squares(u)), constr)
print("The problem is QP: ", prob.is_qp())
prob.solve(solver=cv.OSQP, verbose=1)
```
 
I notice this works:

```
import cvxpy as cv
u = cv.Variable(2)
constr = []
constr += [u[1]-u[0]<=100]
constr += [u[1]-u[0]>=-100]
prob = cv.Problem(cv.Minimize(cv.sum_squares(u)), constr)
print("The problem is QP: ", prob.is_qp())
prob.solve(solver=cv.OSQP, verbose=1)
```

But these two are equivalent.

**Comment by bstellato** [comment]
Looks strange. I suspect it is a problem of how the `abs` atom is parsed by the CVXPY QP canonicalization. The OSQP side should be fine.

**Comment by SteveDiamond** [comment]
This is fixed.

**Comment by bstellato** [comment]
Version 1.0.6 does not include the latest fixes. Have you tried the master branch?

**Comment by wkschwartz** [comment]
Downloaded the master branch just now and tried it. Same result.

**Comment by wkschwartz** [comment]
Is there any relationship between this bug and #535?

**Comment by rileyjmurray** [comment]
@wkschwartz  Things are getting a little confusing between OP's examples and the cases you are describing. I will open a new issue for the example you just gave.

**Comment by rileyjmurray** [comment]
@wkschwartz I've opened a separate issue for what you brought up.

@XuanSomerville from my tests with cvxpy 1.0.8, the issue you posted about is indeed resolved. I am closing this issue again.

**Comment by cangokalp** [comment]
@wkschwartz I have a norm in my objective and I'm experiencing the same thing " SolverError: Problem could not be reduced to a QP, and no conic solvers exist among candidate solvers (['CPLEX']). ". How did you go about resolving this issue? quad_form is not the same with norm.

**Comment by wkschwartz** [comment]
@cangokalp If your norm is the Euclidean or Frobenius norm $\sqrt{x'x}$ then you could try replacing it with sum of squares $x'x$. The two functions have the same set of maximizers over any set of vectors $x$. In my code I use `quad_form` to compute $x'Px$ where $P$ is diagonal and non-negative, unless I know that $P$ is the identity matrix, in which case I use [`sum_squares`](https://www.cvxpy.org/api_reference/cvxpy.atoms.other_atoms.html#sum-squares).

If your norm is not the Euclidean norm but some other $p$-norm then you might try `pow` to get rid of the $p$th root.

**Comment by sandeepparameshwara** [comment]
@wkschwartz I have a similar issue. I am trying to include the below term in the objective function
` term = (|| X - Y ||_2 - D )^2 ` where 

```
import cvxpy as cp
import numpy as np
X = cp.Variable(3) 
Y = np.array([1, 2, 3])
D = 1

```
After reading the discussion above, I tried

`cost = cp.sum_squares(X - Y) - D`

even though this seems to be not a correct simplification of the term I want to add. Well, this runs correctly but doesn't give me the result I am expecting. Hence I wanted to ask if there is a more suitable formulation of the term possible. I am new to this domain and I am not sure if the term I am trying to add is convex. It is convex according to the research paper I am referring to.
To give you a more complete idea, I have a constraint in my QP:

`|| X-Y||_2 >= D`

Then they convert this constraint to its equivalent cost term as given above in the beginning, so they can still solve QP.

Any help is appreciated
Thanks
