### ISSUE TITLE
Create pre-release, dev packages for CVXPY on PyPi

### ISSUE THREAD

**Issue by echu** [cvxgrp/cvxpy#474]
Following the convention from PEP-440, [pre-releases](https://www.python.org/dev/peps/pep-0440/#pre-releases) and [development releases](https://www.python.org/dev/peps/pep-0440/#developmental-releases) are supported on PyPi.

It would probably make installing CVXPY 1.0 easier for folks if it was released on PyPi as either a pre-release or a development release.

I've a [bash script](https://gist.github.com/echu/8a2bde80d5c8ba221ea428d1e4219d4a) that can construct these from git sha's hashes but with no guarantees it will work with the current tagging convention.

**Comment by SteveDiamond** [comment]
We released 1.0. @echu encourage people to try the new ECOS and get feedback that way. You could update it on pip but you may get too much feedback :)
