### ISSUE TITLE
get_problem_data produces wrong format for OSQP

### ISSUE THREAD

**Issue by goulart-paul** [cvxgrp/cvxpy#477]
Calling get_problem_data for OSQP formatted data produces data in the wrong format (presumably for a different solver).   It appears to produce data for constraints in the form 

``A x = b, Fx <= g``

or something on those lines.  OSQP expects instead

``l <= Ax <= u``

for the constraints.

```
import cvxpy as cvx

# only 2 natural variables
x = cvx.Variable([2, 1]);

# construct linear and quadratic cost terms
linCost = x[0] + x[1];
quadCost = cvx.sum_squares(x);

# box constraints
C = [];
C += [0<= x[0]] + [x[0] <= 1]
C += [0<= x[1]] + [x[1] <= 1]

# this objective produces 2 variables
# and 4 constraints in OSQP
# nnz(P) + nnz(A) = 6
f = cvx.Minimize(linCost);
prob = cvx.Problem(f, C)

# get the data in OSQP format
dataOSQP = prob.get_problem_data(cvx.OSQP)

# dataOSQP has problem data (P,q,A,b,F,g), but
# this is not the problem format for OSQP.  
```

**Comment by akshayka** [comment]
As the [documentation states](https://cvxgrp.github.io/cvxpy/api_reference/cvxpy.problems.html#cvxpy.problems.problem.Problem.get_problem_data), `get_problem_data` doesn't necessarily return the data in a form that's acceptable to the solver. It returns an intermediate form, though perhaps this particular intermediate form could be improved.

The below logic is how our osqp interface massages the data dictionary into OSQP's problem data:

```
        P = data['P']
        q = data['q']
        A = sp.vstack([data['A'], data['F']]).tocsc()
        data['full_A'] = A
        uA = np.concatenate((data['b'], data['g']]))
        lA = np.concatenate([data['b'], -np.inf*np.ones(data['g'].shape)])
```

Does this logic suffice for you?

**Comment by goulart-paul** [comment]
It does, and I understand that I'm free to reformulate the problem to fit whatever format I need.   I think the point in this case is that it seems counterintuitive for CvxPy to return problem data in some intermediate format for its default QP solver.

**Comment by SteveDiamond** [comment]
@goulart-paul I agree with you. Originally get_problem_data was supposed to give you literally the input to the solver. This became unworkable for some of the complex solver interfaces like Gurobi, but we should strive for it whenever possible. We'll fix this.

**Comment by TechSurfer1** [comment]
Hi, I am wondering if someone can offer further insight into how I can take a problem formulated in cvxpy and put it in osqp format using the get_problem_data() function.

Below is a test case, using random data with a seed for a portfolio optimization problem.

```
np.random.seed(123)
A = np.random.normal(loc=0.12, scale=0.1, size=10)
B = np.random.normal(loc=0.02, scale=0.09, size=10)
C = np.random.normal(loc=0.1, scale=0.12, size=10)
D = np.random.normal(loc=-0.05, scale=0.1, size=10)
r = np.array([np.mean(A), np.mean(B), np.mean(C), np.mean(D)])
cov = np.cov(np.stack((A, B, C, D), axis=0))

x = cvxpy.Variable(4)
prob = cvxpy.Problem(cvxpy.Minimize(-r.T@x + L*cvxpy.quad_form(x, cov)))
data, chain, meta_data = prob.get_problem_data(solver="OSQP")
```

When I then look at ```data['P'].todense()``` it produces different output to ```cov```. Why is this?
