### ISSUE TITLE
a float is required

### ISSUE THREAD

**Issue by jainSamkit** [cvxgrp/cvxpy#483]
Inside NonlinearModel,I am getting "a float is required" error when cos is trying to operate the argument.The arguments are cvxpy variables and None type.Basically the initial states have not been set.How do I fix this issue? The NonlinearModel is being called from CalcInput function. Thanks!

import cvxpy
import numpy as np
from cvxpy import *
from math import *
import time

def NonlinearModel(self,x,u,coeffs):

             
                x[0] = x[0] + x[2] * cos(x[3] + u[1]) * self.dt
                x[1] = x[1] + x[2] * sin(x[3] + u[1]) * self.dt
                x[2] = x[2] + u[0] * self.dt
                x[3] = x[3] + x[2] / self.lr * sin(u[1]) * selff.dt

                return x

def CalcInput(self,x, u,T,coeffs):
        
                x_0 = x[:]
                x = Variable(x.shape[0],T+1)
                u = Variable(u.shape[0],T)
                
                

                states=[]
                for t in range(T):

                        constr = [x[:,t+1] == self.NonlinearModel(x[:,t],u[:,t],coeffs)]
                        constr = [x[2, t + 1] <= self.max_s]
                        constr += [x[2, t + 1] >= self.min_s]
                        constr += [u[0 ,t ] <=1]
                        constr += [u[0 ,t ] >=0]
                        constr += [u[1 ,t ] >=-0.436332]
                        constr += [u[1 ,t ] <= 0.436332]
        
                        cost = 1500*x[4,t] **2 
                        cost += 1500*x[5,t]**2
                        cost += (x[2,t]-self.ref_vel)**2

                        states.append(Problem(Minimize(cost), constr))

                prob = sum(states)
                prob.constraints += [x[:, 0] == x_0]
                result = prob.solve()
                print(prob.value)
                print(u.value)
                return u,x,prob.value

**Comment by rileyjmurray** [comment]
cvxpy does not support nonlinear programs with variable arguments to cosines or sines. Such problems are not convex by construction, and so there is no plan to support them in the future. 

I recommend you look into general nonlinear optimizers and modeling languages; see [this page](https://scicomp.stackexchange.com/questions/83/is-there-a-high-quality-nonlinear-programming-solver-for-python) for detailed discussion.

I'm marking this issued as closed, but please comment again if I'm misunderstanding.
