### ISSUE TITLE
solution can't meet constraints 

### ISSUE THREAD

**Issue by SoulMateK** [cvxgrp/cvxpy#484]
i use the code from official website, version 0.4.11. but i add pos func in objective as below
```
from cvxpy import *
import numpy
import mosek

m = 30
n = 20
numpy.random.seed(1)
A = numpy.random.randn(m, n)
b = numpy.random.randn(m)

x = Variable(n)
objective = Minimize(sum_squares(pos(A*x - b)))
constraints = [0 <= x, x <= 1]
prob = Problem(objective, constraints)

result = prob.solve(solver=MOSEK)
```

the result contain negative value. values are below.
> x.value
matrix([[ 3.19875090e-01],
        [ 3.03800807e-01],
        [ 6.99977418e-01],
        [-1.98557866e-09],
        [-3.18765344e-10],
        [ 2.26223754e-09],
        [ 1.06073732e-08],
        [ 3.83202591e-09],
        [ 1.69901284e-01],
        [ 3.86004785e-01],
        [-3.45735797e-09],
        [ 4.24791799e-03],
        [-7.50910846e-10],
        [ 1.16471516e-07],
        [-8.95639871e-10],
        [ 4.36239064e-01],
        [ 1.27716532e-09],
        [ 1.61988607e-09],
        [ 5.39277131e-03],
        [-1.12994884e-09]])

i want to know what causes this?

**Comment by rileyjmurray** [comment]
There are two things going on here.

First, just about any solver (mosek, ECOS, SCS, gurobi, etc..) has feasibility tolerances. If a solution's violation is within some very small tolerance (e.g. 1e-9), then those constraint violations are effectively ignored. In principle you can prevent this, by setting the feasibility tolerance of your solver to zero (different solvers do this in different ways).

However, even setting your feasibility tolerance to zero may not save you here. The main purpose of CVXPY is to manage a large number of problem transformations behind-the-scenes, so as to pass your problem to a high performance solver with rigid input requirements. These transformations are valid in exact arithmetic, but they may introduce issues when working with floating point numbers. The errors introduced should always be small (say, no larger than 1e-10), but they can be meaningful.

There has been some discussion around post-solver checks for feasibility (see #434 ) but it's not clear how far out those might be from a cvxpy release (if it's incorporated at all).

For now, users should verify or perform projections of a returned solution when feasibility is critical. In your case, that's as simple as `x.value = np.max( x.value, 0 )`.

@akshayka , can you mention this on the landing page of the new documentation? @SteveDiamond  perhaps this is something the undergrad can help with (RE: examples)?

**Comment by akshayka** [comment]
@rileyjmurray Sure, I can work it into the documentation.
