### ISSUE TITLE
tree_mat() function does not support "rmul" operation in cvxpy. "Unknown linear operator." exception.

### ISSUE THREAD

**Issue by JasontheMonster** [cvxgrp/cvxpy#486]
As I created a numpy matrix A and a cvxpy variable P, I want to call the tree_mat() function on the constraint include a form of "P*A". But it triggers the exception "Unknown linear operator." exception.

**Comment by rileyjmurray** [comment]
What version of cvxpy is this? What's the `tree_mat` function?

**Comment by JasontheMonster** [comment]
Sorry for the confusion. It is the **op_mul()** function inside **tree_mat.py** inside the **lin_ops** package. https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/lin_ops/tree_mat.py

**Comment by JasontheMonster** [comment]
Thank you for responding! That works for me right now. 
But also, as I have more than one constraints in the constraints list, this problem happens again. In my constraint, there is not such form as "P*A" as I mentioned before, but when i print the constriants, I still have a "rmul" term.

**Comment by rileyjmurray** [comment]
Hmm. It's strange the right-multiplying decision variables by constants is creating a problem. I would think that something like this would have come up shortly after cvxpy 0.4 was released.

If you are able, I think it would be good to switch to cvxpy 1.0 before getting deep into workarounds for cvxpy 0.4. Are you running Windows, Mac, or Linux? The install on Mac and Linux is pretty straightforward, but for Windows you need to have an appropriate C++ compiler installed. See https://wiki.python.org/moin/WindowsCompilers for an appropriate list of compilers.

**Comment by JasontheMonster** [comment]
The code of op_mul() in cvxpy 1.0 version is something like this:
def op_mul(lin_op, args):
    """Applies the linear operator to the arguments.
    Parameters
    ----------
    lin_op : LinOp
        A linear operator.
    args : list
        The arguments to the operator.
    Returns
    -------
    NumPy matrix or SciPy sparse matrix.
        The result of applying the linear operator.
    """
    # Constants convert directly to their value.
    if lin_op.type in [lo.SCALAR_CONST, lo.DENSE_CONST, lo.SPARSE_CONST]:
        result = lin_op.data
    # No-op is not evaluated.
    elif lin_op.type is lo.NO_OP:
        return None
    # For non-leaves, recurse on args.
    elif lin_op.type is lo.SUM:
        result = sum(args)
    elif lin_op.type is lo.NEG:
        result = -args[0]
    elif lin_op.type is lo.MUL:
        coeff = mul(lin_op.data, {})
        result = coeff*args[0]
    elif lin_op.type is lo.DIV:
        divisor = mul(lin_op.data, {})
        result = args[0]/divisor
    elif lin_op.type is lo.SUM_ENTRIES:
        result = np.sum(args[0])
    elif lin_op.type is lo.INDEX:
        row_slc, col_slc = lin_op.data
        result = args[0][row_slc, col_slc]
    elif lin_op.type is lo.TRANSPOSE:
        result = args[0].T
    elif lin_op.type is lo.CONV:
        result = conv_mul(lin_op, args[0])
    elif lin_op.type is lo.PROMOTE:
        result = np.ones(lin_op.size)*args[0]
    elif lin_op.type is lo.DIAG_VEC:
        val = intf.from_2D_to_1D(args[0])
        result = np.diag(val)
    else:
        raise Exception("Unknown linear operator.")
    return result

Is possible that since the if statements do not check the cases where **lin_op.type** is lo.RMUL, which will lead to the exception ("Unknown linear operator") ? 

Thanks for the reply!

**Comment by SteveDiamond** [comment]
tree_mat is not really supported. That's not public facing, not part of the API. It was something I built for a project/paper.

**Comment by SteveDiamond** [comment]
Point well taken! I've updated all the files that will be deprecated to say so and added some language to the Developer Guide section (perviously Contributors).

**Comment by rileyjmurray** [comment]
The file (https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/lin_ops/tree_mat.py) is now marked as deprecated. @JasontheMonster , can you provide a minimax example demonstrating the issue with cvxpy 1.0? I ran the code below without any problem

```
import cvxpy
import numpy as np
A = np.random.randn(5,5)
X = cvxpy.Variable(shape=(5,5))
expr1 = X * A
expr2 = A * X
```

**Comment by SteveDiamond** [comment]
I'm closing this because it's about a deprecated feature. You can open it on the cvxflow repo.
