### ISSUE TITLE
Is there any c++ version of CVXPY?

### ISSUE THREAD

**Issue by lianglia-apollo** [cvxgrp/cvxpy#487]
we are working on autonomous driving systems and require real-time calculations. The problem we are acing usually has 30 - 100 variables and several hundreds of boundary conditions. The calculation efficiency is very important. Is there a c++ version of CVXPY, or if someone could provide some suggestions?

**Comment by SteveDiamond** [comment]
Look into CVXGEN: https://cvxgen.com/docs/index.html
It's only for QPs but you're probably solving QPs or should be :)

**Comment by lianglia-apollo** [comment]
Thank you! @ SteveDiamond
