### ISSUE TITLE
Gurobi Parameters are ignored 

### ISSUE THREAD

**Issue by pindash** [cvxgrp/cvxpy#489]
passing solver_opts arguments in gurobi are ignored, I looked at the gurobi_inf code and it looks like they are being passed to the model:
for key, value in solver_opts.items():
            model.setParam(key, value)
Perhaps the model is being created earlier, for some reason, the arguments are ignored. 
Gurobi also has an alternate config system, where you place a gurobi.env file in the working directory, this works but requires you to restart the kernel/interpreter for each setting change.

Here is a toy example with the code and the env file

```
import cvxpy
def simOptCVX(n,sumValue,maxValue,num,sol,solopts):
    x = cvxpy.Variable(n)
    d = cvxpy.Bool(n)
    
    objective = cvxpy.Minimize(cvxpy.norm( x,2))
    constraints = [x >= 0,
                   x <= maxValue,
                   x + (1 - d) >= maxValue,
                   cvxpy.sum_entries(x) == sumValue,
                   cvxpy.sum_entries(d) == num
                  ]
    
    prob = cvxpy.Problem(objective, constraints)
    
    prob.solve(solver=sol, verbose=True)
    return x.value


opts={'MIQCPMethod':0,'PreMIQCPForm':0}
simOptCVX(100, 1.0, 0.4,1,cvxpy.GUROBI,opts)

```

gurobi.env:
```
MIQCPMethod 0
PreMIQCPForm 0

```
The difference in timings for this problem are an order of magnitude so it is easy to spot that the parameters are having no effect.

**Comment by sjschneider** [comment]
@pindash In your example, you don't pass solopts to the solve method.  I would expect:

`prob.solve(solver=sol, verbose=True, **solopts)`
