### ISSUE TITLE
"No Module Named Canon-Interface" Error Windows Jupyter

### ISSUE THREAD

**Issue by rohithdesikan** [cvxgrp/cvxpy#490]
I keep getting this error. I used the code copied from an easy example on the CVXPY website. 
![image](https://user-images.githubusercontent.com/31898229/40145503-f82856fc-5916-11e8-8482-931a9bcf3c12.png)

I have Anaconda on my windows and I installed it just like the website said:
```
conda install -c https://conda.anaconda.org/omnia scs
pip install cvxpy
```
Note, I don't know whether or not this is important, but I have Julia, R and Python on my laptop. 

So, I am not sure how to solve this problem. Please help!!

**Comment by rileyjmurray** [comment]
The syntax you're using in the variable declaration suggests that you are using CVXPY 0.4. We are about  to make an official switch to 1.0. Can you try installing 1.0 from source? We are happy to help with installation issues in 1.0.

**Comment by rohithdesikan** [comment]
So, I ran `conda install -c cvxgrp cvxpy` from the CVXPY 1.0 website. First, it says, 'All requested packages are already installed.' but when I run nosetests, it says this:
![image](https://user-images.githubusercontent.com/31898229/40150851-fcda756c-5930-11e8-9d43-213ca3819cea.png)

I don't know why the packages seem to be inside 'Julia' when they should be inside Python. Not sure if that is the problem.

**Comment by SteveDiamond** [comment]
Your nose is installed inside Julia, which is bad. Conda is inside Julia, which is also bad. You need to fix your environment before we can say more.

**Comment by rohithdesikan** [comment]
So, I uninstalled Conda and reinstalled it in my C:\Users\username\Anaconda3. I installed CVX1.0 version. Now, I ran the 2nd Control example from the Examples page and I am getting the optimal solution. But nosetests gives me 21 errors. Is this ok?
![image](https://user-images.githubusercontent.com/31898229/40196634-f7a30e98-59c5-11e8-99ed-a0b249c41f67.png)

**Comment by SteveDiamond** [comment]
Is this with Python 2 or Python 3?

**Comment by rileyjmurray** [comment]
@SteveDiamond , can you create a Git Issue explaining the difficulty with Anaconda + Python 3 + Windows? Maybe this is something I can help with.

@rohithdesikan, you can try installing cvxpy from source, or via pip.
