### ISSUE TITLE
Array elements product

### ISSUE THREAD

**Issue by giorgioporzio** [cvxgrp/cvxpy#496]
Hello everybody,
is there a CVXPY function that multiplies the elements of an array?

**Comment by rileyjmurray** [comment]
`cvxpy.multiply(expr1, expr2)` returns an expression that is the element-wise multiplication of entries in expr1 by entries in expr2.

http://www.cvxpy.org/tutorial/functions/index.html#elementwise-functions

Although perhaps you mean a function which takes in a single array and returns a scalar (the product of all entries in that array). Yes, there are such functions (`geo_mean`), but their usage must conform to the ruleset of Disciplined Convex Programming. 

http://www.cvxpy.org/tutorial/functions/index.html#scalar-functions

Does that answer your question?

**Comment by giorgioporzio** [comment]
Yes, it does answer my question perfectly.
Thank you for your detailed response

**Comment by giorgioporzio** [comment]
Yes it does answer my question. Thank you for the detailed response
