### ISSUE TITLE
Certificate of infeasibility for unconstrained convex problems 

### ISSUE THREAD

**Issue by sunilshah** [cvxgrp/cvxpy#498]
For what appears to be a modest dynamic range in an l-1 regularized least-squares problem, cvxpy declares the convex unconstrained problem to be infeasible. It does so, for multiple solvers. In this case, it can be resolved by simple scaling.  However, it is not clear either from the documentation or from the messages that the user needs to do so.  Of course, it would be friendlier if cvxpy reduction process took care of the scaling for the user to maintain feasibility.  At the very least, it should not declare an unconstrained convex problem infeasible.  

For version 0.4.11, attached file testSolvers4.11.html,  shows the problem.  
For version 1.0.3, attached file testSolvers1.0.html, shows the problem.  

For version 1.0.3 there is an additional problem with CVXOPT solver as seen in the notebook cell output.  
[testSolvers4.11.html.zip](https://github.com/cvxgrp/cvxpy/files/2029553/testSolvers4.11.html.zip)
[testSolvers1.0.html.zip](https://github.com/cvxgrp/cvxpy/files/2029554/testSolvers1.0.html.zip)

**Comment by sunilshah** [comment]
Hi Akshay,

Any thoughts on looking at automatic scaling of variables or tolerances to preserve properties like feasibility through the reductions?  To me, the main attraction of convex optimization is to get some guarantee on the results. 

Should I file a separate issue for problem with CVXOPT solver in version 1.0.3 that did not exist in version 0.4.11?

Thanks!

**Comment by bstellato** [comment]
Did you try it with OSQP as well? It should not report infeasibility.

**Comment by sunilshah** [comment]
Hi @bstellato 

Yes!  It does not report infeasibility and it is chosen by cvxpy 1.0.3 automatically for the problem.

**Comment by SteveDiamond** [comment]
@sunilshah sadly the problem of automatic scaling is deep and not something we can solve easily. If you have issues with particular solvers, you should post issues for those solvers. You should not say "cvxpy cannot solve the problem". It is fair to say that the solution of rescaling the problem is not featured prominently. I've changed the solver error message to mention rescaling.

**Comment by sunilshah** [comment]
@SteveDiamond 

Yes, I agree it is deeper- future research.  

The second issue in the original post needs a bit more elaboration.   

For the scaled problem in cvx 1.0.3, 

>> resCVX=prob2.solve(solver='CVXOPT',verbose=True)
 
results python traceback:

            TypeError: incompatible dimensions

         at line 417    cvxpy/problems/solvers/cvxopt_intf.py in format_results(self, results_dict, data, cached_data)

This occurs after CVXOPT message: "Optimal solution found"

This traceback does not occur in 0.4.11 for the same problem.  See the attachments in the OP. 

Do you think this is a problem with CVXOPT solver to be posted on cvxopt/cvxopt ?

Thanks!
