### ISSUE TITLE
cumsum doesn't work

### ISSUE THREAD

**Issue by mirage007** [cvxgrp/cvxpy#511]
I'm trying to make a simple problem with cvxpy but it doesn't seem like it is formatting a valid optimization, please see below example.

````python
import sys
print('python version', sys.version)
import cvxpy as cvx
print('cvxpy verson', cvx.__version__)
tt = cvx.Variable(5)
cvx.Problem(cvx.Minimize(cvx.sum(tt)), [cvx.cumsum(tt, 0) >=-0.0001]).solve()
````

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-168-5568ba0fffdf> in <module>()
      4 print('cvxpy verson', cvx.__version__)
      5 tt = cvx.Variable(5)
----> 6 cvx.Problem(cvx.Minimize(cvx.sum(tt)), [cvx.cumsum(tt, 0) >=-0.0001]).solve()

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    244         else:
    245             solve_func = Problem._solve
--> 246         return solve_func(self, *args, **kwargs)
    247 
    248     @classmethod

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/problems/problem.py in _solve(self, solver, ignore_dcp, warm_start, verbose, parallel, **kwargs)
    356                 raise e
    357 
--> 358         data, inverse_data = self._solving_chain.apply(self)
    359         solution = self._solving_chain.solve_via_data(self, data, warm_start, verbose,
    360                                                       kwargs)

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/chain.py in apply(self, problem)
     56         inverse_data = []
     57         for r in self.reductions:
---> 58             problem, inv = r.apply(problem)
     59             inverse_data.append(inv)
     60         return problem, inverse_data

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/dcp2cone/dcp2cone.py in apply(self, problem)
     41         if not self.accepts(problem):
     42             raise ValueError("Cannot reduce problem to cone program")
---> 43         return Canonicalization(cone_canon_methods).apply(problem)

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/canonicalization.py in apply(self, problem)
     47             # constraint
     48             canon_constr, aux_constr = self.canonicalize_tree(
---> 49                 constraint)
     50             canon_constraints += aux_constr + [canon_constr]
     51             inverse_data.cons_id_map.update({constraint.id:

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/canonicalization.py in canonicalize_tree(self, expr)
     76             constrs = []
     77             for arg in expr.args:
---> 78                 canon_arg, c = self.canonicalize_tree(arg)
     79                 canon_args += [canon_arg]
     80                 constrs += c

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/canonicalization.py in canonicalize_tree(self, expr)
     76             constrs = []
     77             for arg in expr.args:
---> 78                 canon_arg, c = self.canonicalize_tree(arg)
     79                 canon_args += [canon_arg]
     80                 constrs += c

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/canonicalization.py in canonicalize_tree(self, expr)
     76             constrs = []
     77             for arg in expr.args:
---> 78                 canon_arg, c = self.canonicalize_tree(arg)
     79                 canon_args += [canon_arg]
     80                 constrs += c

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/canonicalization.py in canonicalize_tree(self, expr)
     79                 canon_args += [canon_arg]
     80                 constrs += c
---> 81             canon_expr, c = self.canonicalize_expr(expr, canon_args)
     82             constrs += c
     83         return canon_expr, constrs

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/canonicalization.py in canonicalize_expr(self, expr, args)
     95                 return Constant(expr.value), []
     96         elif type(expr) in self.canon_methods:
---> 97             return self.canon_methods[type(expr)](expr, args)
     98         else:
     99             return expr.copy(args), []

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/reductions/dcp2cone/atom_canonicalizers/cumsum_canon.py in cumsum_canon(expr, args)
     31     Y = Variable(expr.shape)
     32     if axis == 0:
---> 33         constr = [X[1:, :] == Y[1:, :] - Y[:-1, :], Y[0, :] == X[0, :]]
     34     else:
     35         constr = [X[:, 1:] == Y[:, 1:] - Y[:, :-1], Y[:, 0] == X[:, 0]]

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/expressions/expression.py in __getitem__(self, key)
    311             return cvxtypes.index().get_special_slice(self, key)
    312         else:
--> 313             return cvxtypes.index()(self, key)
    314 
    315     @property

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/atoms/affine/index.py in __init__(self, expr, key, orig_key)
     46         if orig_key is None:
     47             self._orig_key = key
---> 48             self.key = ku.validate_key(key, expr.shape)
     49         else:
     50             self._orig_key = orig_key

~/miniconda3/envs/test/lib/python3.6/site-packages/cvxpy/utilities/key_utils.py in validate_key(key, shape)
     47     slices = len(key) - none_count
     48     if slices > len(shape):
---> 49         raise IndexError("Too many indices for expression.")
     50     elif slices < len(shape):
     51         # Add : to the right.

IndexError: Too many indices for expression.

**Comment by SteveDiamond** [comment]
This is fixed.
