### ISSUE TITLE
Incorrect objective value

### ISSUE THREAD

**Issue by KwangmooKoh** [cvxgrp/cvxpy#513]
Sometimes, the evaluated objective value is incorrect although the solution is correct.

Example:
```python
import cvxpy
x = cvxpy.Variable((2, 1))
A = np.array([[1.0]])
B = np.array([[1.0, 1.0]]).T
obj0 = -B.T * x
obj1 = cvxpy.quad_form(B.T * x, A)
prob = cvxpy.Problem(cvxpy.Minimize(obj0 + obj1))
prob.solve()

print(prob.value, prob.objective.value)
```
Result:
```
-0.25, -0.50
```
`prob.value` is not the same with `prob.objective.value`.

If we look further,

```python
print(obj1.value, (B.T @ x.value).T @ A @ (B.T @ x.value)))
```

Result:
```
0.0, [[0.25]]
```
`obj1.value` should be 0.25, but it is set to 0.0.

**Comment by GrayThomas** [comment]
I got the same answer, and changing to ```obj1 = cvxpy.quad_form(x, B.dot(A).dot(B.T))``` seems to give a different (correct) answer. The matrix in the quad_form is 1x1 when it fails, and 2x2 when it works, so I wonder if this is because of the special case.

**Comment by SteveDiamond** [comment]
This is fixed now. @GrayThomas thanks for your help! It turned out to be a subtle bug with determining positive/negative semidefiniteness.
