### ISSUE TITLE
Problem solvable with 0.4.11 not solvable with 1.0.6

### ISSUE THREAD

**Issue by wrossmorrow** [cvxgrp/cvxpy#516]
I have a convex program, basically logistic regression with a certain L1 penalty, that is solvable with the previous generation `cvxpy` (using ECOS for the exponential cone problem), but is _not_ solvable with the newer 1.0.6 version of `cvxpy`. The newer version hangs before terminating with a `killed` print to the terminal. The last time I tried (in a clean `virtualenv` install of `cvxpy 1.0.6`) I got a bunch of "application out of memory" warnings from other programs running at the same time. No such issues with the older `cvxpy`. 

Any advice would be helpful. I can certainly provide more information to help debug what might be happening.

**Comment by SteveDiamond** [comment]
Is your problem vectorized? In other words, how many distinct variable objects are there? Also, how many distinct constraints are there? Both these numbers should be small.

**Comment by wrossmorrow** [comment]
Depending on definitions, there is a single Variable, Parameter, and Constraint object. Here is the basic problem, in almost a one-liner: 

```
p , L = cp.Variable( Nvars ) , cp.Parameter( nonneg=True )
cp.Problem( cp.Minimize( sum( cp.logistic( Z * p ) ) + L * cp.norm( p[A:] , 1 ) , [ S * p == b ] )
```
This isn't substantially different from the actual code, in fact. 

Here `Z` and `S` are `scipy.sparse` obejcts. The problem isn't "small", though: in one case (that `0.4.11` can solve, trusting the solve status, and `1.0.6` can't) `p` is 2346 with `Z` being 4565 x 2346 and `S` being 125 x 2346.

**Comment by SteveDiamond** [comment]
You need to use ``cp.sum``, not the built in sum. I need to figure out how to make that trigger a warning.

**Comment by wrossmorrow** [comment]
Awesome. That indeed appears to be working in `1.0.6`
