### ISSUE TITLE
Complex promotion unimplemented?

### ISSUE THREAD

**Issue by harrisReservoir** [cvxgrp/cvxpy#517]
If I run

```
import cvxpy as cvx
import numpy as np
v = cvx.Variable(complex = True)
obj = cvx.Maximize(cvx.real(4 *	v))
con = [cvx.norm(v) <= 1]
prob = cvx.Problem(obj, con)
```
I get 3.999999999911048.

Shouldn't the following problem be the same?

```
import cvxpy as cvx
import numpy as np
v = cvx.Variable(complex = True)
obj = cvx.Maximize(cvx.real(cvx.sum(v * np.ones((2,2)))))
con = [cvx.norm(v) <= 1]
prob = cvx.Problem(obj, con)
prob.solve()
```
I get the following error:

> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> <ipython-input-141-3498ea861007> in <module>()
> ----> 1 prob.solve()
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
>     244         else:
>     245             solve_func = Problem._solve
> --> 246         return solve_func(self, *args, **kwargs)
>     247 
>     248     @classmethod
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py in _solve(self, solver, ignore_dcp, warm_start, verbose, parallel, **kwargs)
>     356                 raise e
>     357 
> --> 358         data, inverse_data = self._solving_chain.apply(self)
>     359         solution = self._solving_chain.solve_via_data(self, data, warm_start, verbose,
>     360                                                       kwargs)
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/chain.py in apply(self, problem)
>      56         inverse_data = []
>      57         for r in self.reductions:
> ---> 58             problem, inv = r.apply(problem)
>      59             inverse_data.append(inv)
>      60         return problem, inverse_data
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py in apply(self, problem)
>      41         leaf_map = {}
>      42         real_obj, imag_obj = self.canonicalize_tree(
> ---> 43             problem.objective, inverse_data.real2imag, leaf_map)
>      44         assert imag_obj is None
>      45 
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py in canonicalize_tree(self, expr, real2imag, leaf_map)
>      97             imag_args = []
>      98             for arg in expr.args:
> ---> 99                 real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
>     100                 real_args.append(real_arg)
>     101                 imag_args.append(imag_arg)
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py in canonicalize_tree(self, expr, real2imag, leaf_map)
>      97             imag_args = []
>      98             for arg in expr.args:
> ---> 99                 real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
>     100                 real_args.append(real_arg)
>     101                 imag_args.append(imag_arg)
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py in canonicalize_tree(self, expr, real2imag, leaf_map)
>      97             imag_args = []
>      98             for arg in expr.args:
> ---> 99                 real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
>     100                 real_args.append(real_arg)
>     101                 imag_args.append(imag_arg)
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py in canonicalize_tree(self, expr, real2imag, leaf_map)
>      97             imag_args = []
>      98             for arg in expr.args:
> ---> 99                 real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
>     100                 real_args.append(real_arg)
>     101                 imag_args.append(imag_arg)
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py in canonicalize_tree(self, expr, real2imag, leaf_map)
>     102             real_out, imag_out = self.canonicalize_expr(expr, real_args,
>     103                                                         imag_args, real2imag,
> --> 104                                                         leaf_map)
>     105         return real_out, imag_out
>     106 
> 
> ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py in canonicalize_expr(self, expr, real_args, imag_args, real2imag, leaf_map)
>     124             return result
>     125         else:
> --> 126             assert all(v is None for v in imag_args)
>     127             return expr.copy(real_args), None
> 
> AssertionError: 
> 

I think this may be because there is no method in https://github.com/cvxgrp/cvxpy/blob/5a0cc1286526c129524bf431b8d4f62f26cb7503/cvxpy/reductions/complex2real/atom_canonicalizers/__init__.py to handle atoms of type <class 'cvxpy.atoms.affine.promote.Promote'>.

Thank you

**Comment by SteveDiamond** [comment]
This is fixed.

**Comment by lucienwerner** [comment]
I have been running into what seems like a similar issue; however updating the above-mentioned `__init__.py` file did not seem to address it. Below is the problem I am trying to solve along with the errors:
```
import cvxpy as cvx

b = [1.366324420-4.20143265j,
     12.82603065-2.99276024j,
      1.10476590-4.26269995j,
     12.99995934-2.86050107j,
      6.63051295-3.50754316j,
      3.97323449-4.00951606j,
      0.76069049-4.35432646j,
      8.03253272-3.48512879j,
      6.67770330-3.54464451j,
      5.68580795-3.79364239j]

A = [1.00069575+0.20552237j,
     1.01873727+2.86999910j,
     1.00802324+0.14383855j,
     0.99283509+2.91337912j,
     0.97711951+1.43306890j, 
     1.02388092+0.80950735j,
     1.02019707+0.06240993j,
     1.00815544+1.75581200j,  
     0.98686287+1.44295499j,
     1.01847807+1.20860459j]

N = 1
x = cvx.Variable((N,),complex=True)
obj = cvx.Minimize(cvx.norm(x, 1))
const = [A*x == b]
prob = cvx.Problem(obj, const)
prob.solve(solver=cvx.ECOS,verbose=False)
```

> Traceback (most recent call last):
> 
>   File "<ipython-input-10-2a6c2e2b5b05>", line 29, in <module>
>     prob.solve(solver=cvx.ECOS,verbose=False)
> 
>   File "~/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 246, in solve
>     return solve_func(self, *args, **kwargs)
> 
>   File "~/anaconda3/lib/python3.6/site-packages/cvxpy/problems/problem.py", line 358, in _solve
>     data, inverse_data = self._solving_chain.apply(self)
> 
>   File ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/chain.py", line 58, in apply
>     problem, inv = r.apply(problem)
> 
>   File ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 50, in apply
>     constraint, inverse_data.real2imag, leaf_map)
> 
>   File ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 108, in canonicalize_tree
>     real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
> 
>   File "~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 108, in canonicalize_tree
>     real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
> 
>   File ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 108, in canonicalize_tree
>     real_arg, imag_arg = self.canonicalize_tree(arg, real2imag, leaf_map)
> 
>   File "~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 113, in canonicalize_tree
>     leaf_map)
> 
>   File ~/anaconda3/lib/python3.6/site-packages/cvxpy/reductions/complex2real/complex2real.py", line 135, in canonicalize_expr
>     assert all(v is None for v in imag_args)
> 
> AssertionError

If A and b are real-valued the error does not come up. I am also only getting the error in this degenerate case where A and b are both vectors and x is a scalar. Any ideas what may be going on here?
