### ISSUE TITLE
Do you still need cvxcanon in the conda recipe?

### ISSUE THREAD

**Issue by mcg1969** [cvxgrp/cvxpy#519]
Don't you vendor it now?
https://github.com/cvxgrp/cvxpy/blob/68aa9648a7b256dc08b18aff9958d504ea15afd6/conda-recipe/meta.yaml#L17

**Comment by SteveDiamond** [comment]
Yes, it should be removed. I've removed it now.

**Comment by mcg1969** [comment]
Great! I'm actually working on cleaning up that conda recipe further—using the new Anaconda 5.0 compilers, conda build 3.0 constructs, etc. I'll submit a PR

**Comment by SteveDiamond** [comment]
Thanks so much! We've done our best to use conda, but we could really use help from an expert!
