### ISSUE TITLE
Nonnegative scalar times PSD should be PSD

### ISSUE THREAD

**Issue by dougalsutherland** [cvxgrp/cvxpy#522]
```
>>> A = cvx.Parameter(shape=(5, 5), PSD=True)
>>> A.is_psd()
True
>>> (2 * A).is_psd()
False
```
Obviously if I were just doing this I'd just pull the scalar out of whatever I was doing to it, but it's part of a more complicated structure, where `2` is a different `Parameter`, etc. And since there's no way AFAIK to annotate some intermediate `Expression` as being PSD, this means I need to do a nontrivial amount of moving stuff around.

I guess this is because `2 * A` is implemented with a `Promote` of `2`, and of course if you "forget" that a matrix is a constant, then you can't be confident that it ends up PSD. So presumably there should be some new kind of operation that handles that case.

**Comment by SteveDiamond** [comment]
Thanks for pointing this out! Looking now, I see PSD isn't tracked through very many operations. For example, in the case you found it's assumed that multiplication loses PSD. I will work on adding more tracking of PSD for linear operators.

**Comment by SteveDiamond** [comment]
Fixed in master.
