### ISSUE TITLE
Anaconda - Can't upgrade from 0.4 to 1.x

### ISSUE THREAD

**Issue by JulienNic0las** [cvxgrp/cvxpy#523]
Hi,

I found nothing relating either here in github or in stackoverflow so I open a new ticket (I may have not search well enough, feel free to redirect me if necessary).

I am using Anaconda `4.1.1` with Python 3.5. I installed a couple of weeks ago cvxpy following the instruction found in the tutorial: `conda install -c cvxgrp cvxpy`. I am surprised that the version installed is the `0.4.2`. I tried everything I know to upgrade (excepting pip as I need a compiled version, indeed I lack of visual c++ to build a wheel myself). Each time conda says that **all requested packages already installed**.

Does it means that the version on `cvxgrp` is still the 0.4.2? Or versions >=1.0 are incompatibles with Python 3.5? The documentation says nothing about that. 

Thanks in advance.

J

**Comment by SteveDiamond** [comment]
We do not currently have a conda version for Python 3 on Windows. You need to install with pip if you want to use Python 3 on Windows.

**Comment by SteveDiamond** [comment]
#492

**Comment by JulienNic0las** [comment]
Thanks for the feedback. I fear I cannot be of any help on that matter.

Maybe a note about that issue in the documentation could be added. 

Thanks.
