### ISSUE TITLE
Interface to see if OSQP polish worked.

### ISSUE THREAD

**Issue by rhaskett** [cvxgrp/cvxpy#525]
When I run prob.solve(verbose=True) over my parameter space, it seems to solve the problem everytime, but occasionally the solution polish will fail.  The solutions where the polish fails are, on inspection, clearly inferior.

> -----------------------------------------------------------------
>            OSQP v0.3.1  -  Operator Splitting QP Solver
>               (c) Bartolomeo Stellato,  Goran Banjac
>         University of Oxford  -  Stanford University 2018
> -----------------------------------------------------------------
> problem:  variables n = 56, constraints m = 99
>           nnz(P) + nnz(A) = 434
> settings: linear system solver = suitesparse ldl,
>           eps_abs = 1.0e-04, eps_rel = 1.0e-04,
>           eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
>           rho = 1.00e-01 (adaptive),
>           sigma = 1.00e-06, alpha = 1.60, max_iter = 4000
>           check_termination: on (interval 25),
>           scaling: on, scaled_termination: off
>           warm start: on, polish: on
> 
> iter  objective    pri res    dua res    rho        time
>    1  -8.7678e-03   1.68e+00   8.81e-01   1.00e-01   1.15e-04s
>  100  -3.9076e-03   2.99e-05   6.10e-08   5.79e-01   3.78e-04s
> 
> status:               solved
> solution polish:      unsuccessful
> number of iterations: 100
> optimal objective:    -0.0039
> run time:             4.72e-04s
> optimal rho estimate: 1.07e+00

Deep in the prob._solver_cache object, I can see that status_polish has failed (status_polish = -1), but I'm not sure how to consistently get at this variable as _solver_cache has some weird "bound method" in it.  Should this be in prob.solver_stats?

**Comment by bstellato** [comment]
This is a small typo in the cache definition. After this pull request is merged, you should be able to access the results information with:

```python
_, _, results = problem._solver_cache['OSQP']
print(results.info.status_polish)
```

I wonder if we should implement a function to retrieve the raw results structure given by the solver or at least explain how to do it in the docs. @rileyjmurray @SteveDiamond.
