### ISSUE TITLE
CVXPY Missing sum_entries

### ISSUE THREAD

**Issue by malardy** [cvxgrp/cvxpy#527]
Hi,

I'm having an annoying issue with cvxpy in that the sum_entries function appears to be missing.  I installed cvxpy with pip, without any issue.  The machine I am on is a clean install.  Here is the commands I'm using to find the issue:

>>> import cvxpy
>>> from cvxpy import sum_entries
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'sum_entries'

When I try to use it in code I get the following:
AttributeError: module 'cvxpy' has no attribute 'sum_entries'

I'm at a loss.  Everything else I've tried to use in cvxpy is there and working.  Is this function deprecated?  

Thanks in advance!
Matt

**Comment by rileyjmurray** [comment]
“sum_entries” has been replaced by “sum” in cvxpy 1.0. A number of other changes (particularly declaration of variables) have also been made between 0.4 and 1.0. Please refer to the 1.0 documentation at cvxpy.org.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
