### ISSUE TITLE
Issue : Installation of cvxpy on Python 3.6 with pip on Windows 10

### ISSUE THREAD

**Issue by marine33** [cvxgrp/cvxpy#533]
I have tried to install the module cvxpy on Python 3.6 with pip on Windows 10. I have tested the command :  "pip install cvxpy " on anaconda prompt but that doesn't work.
I have also tried to install cvxpy from source. But I have this message : "Microsoft Visual C++ 14.0 is required". But when I see on computer's programs, Microsoft Visual C++ 14.0 is already installed. 
So, I don't know what to do anymore. Can I have help to install cvxpy on Python 3.6 with Windows 10 please ?

**Comment by stevenwong** [comment]
From memory you'd also need to have Windows 10 SDK installed or something, but it's easier if you just use precompiled wheels published at here

https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by marine33** [comment]
It works ! Thank you very much !
