### ISSUE TITLE
the procedure entry point could not be located

### ISSUE THREAD

**Issue by Cerebrock** [cvxgrp/cvxpy#538]
...  in the dynamic link library mkl_sparse_s_bsr__g_n_sypr_i4

:\ 

code: 
`%%time

c_p_0 = Q.groupby(['Canal', 'Prod.']).sum() 
c_p_1 = cp.Variable(shape = c_p_0.shape[0], nonneg = True)

c_p_1.value = c_p_0.values

constrains = []
for p in c_p_0.index.get_level_values(1).unique():
    mask = c_p_0.index.get_level_values(1) == p
    constrains.append(cp.sum(c_p_1[np.where(mask)[0]]) == p_pres[p])

porc = 0.45
q_max = porc * p_pres.sum()
canal = '01'
mask = c_p_0.index.get_level_values(0) == canal
constrains.append(cp.sum(c_p_1[np.where(mask)]) <= q_max)    
    
obj = cp.Minimize(cp.sum(cp.kl_div(c_p_1, c_p_0)))

prob = cp.Problem(obj, constrains)
t0 = time.time()
sol = prob.solve('SCS', warm_start = True, verbose = True, gpu = True)
t1 = time.time()
print(t1-t0, prob.status)
`

c_p_0 shape is ~900

**Comment by rileyjmurray** [comment]
The code you posted cannot be executed. (What is ``Q``?)

Regardless, that kind of error message indicates a problem with how you setup your development environment.

If you are still experiencing issues, please provide 
1. a minimal example for generating the error.
2. information on your development environment (as much as possible).

**Comment by rileyjmurray** [comment]
Closing due to lack of response.
