### ISSUE TITLE
The error in the "control" example

### ISSUE THREAD

**Issue by maxydroll** [cvxgrp/cvxpy#540]
I tried to run the code of the "Control" example on CVXPY 1.0.6 from this [link](http://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/intro/control.ipynb). 

```
# Generate data for control problem.
import numpy as np
np.random.seed(1)
n = 8
m = 2
T = 50
alpha = 0.2
beta = 5
A = np.eye(n) + alpha*np.random.randn(n,n)
B = np.random.randn(n,m)
x_0 = beta*np.random.randn(n,1)
```

```
# Form and solve control problem.
from cvxpy import *
x = Variable((n, T+1))
u = Variable((m, T))

states = []
for t in range(T):
    cost = sum_squares(x[:,t+1]) + sum_squares(u[:,t])
    constr = [x[:,t+1] == A*x[:,t] + B*u[:,t],
              norm(u[:,t], 'inf') <= 1]
    states.append( Problem(Minimize(cost), constr) )
# sums problem objectives and concatenates constraints.
prob = sum(states)
prob.constraints += [x[:,T] == 0, x[:,0] == x_0.flatten()]
prob.solve()
```

But I got an error in the line with additional constraints:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-12-62c434796c14> in <module>()
>      12 # sums problem objectives and concatenates constraints.
>      13 prob = sum(states)
> ---> 14 prob.constraints += [x[:,T] == 0, x[:,0] == x_0.flatten()]
>      15 prob.solve()
> 
> AttributeError: can't set attribute

In CVXPY v0.4.10 the code works well. 
What could be a problem in CVXPY 1.0.6?
Maybe there is another way to add constraints?

**Comment by drazenb** [comment]
I encountered the same issue. As mentioned [in the tutorial](http://www.cvxpy.org/tutorial/intro/index.html#changing-the-problem), problems cannot be changed after they are created. The solution is to create a new problem with expanded constraints:
```
# sums problem objectives and concatenates constraints.
prob0 = sum(states)
# add constraints and create new problem
cnst = prob0.constraints + [x[:,T] == 0, x[:,0] == x_0]
prob = Problem(prob0.objective, cnst)
prob.solve()
```

In the same example there is also a small issue in the plotting of results. All the `.value.A.flatten()` parts should be changed to just `.value`.

**Comment by SteveDiamond** [comment]
@drazenb is right. I'll fix the example.

**Comment by rileyjmurray** [comment]
@SteveDiamond do you have the fix on your local machine's copy of cvxpy?

**Comment by nzhou** [comment]
After this fix, the problem still failed with the OSDP solver, but it worked with the ECOS solver for me.
