### ISSUE TITLE
[Performance]cvxpy 1.0 re-parse the problem on each call of `problem._solve`

### ISSUE THREAD

**Issue by kongscn** [cvxgrp/cvxpy#541]
I'm trying the [Portfolio optimization with factor covariance model](http://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb#Portfolio-optimization-with-factor-covariance-model) example, and find that subsequent calls on `problem.solve()` with different parameter values take significantly longer in 1.0 than 0.4, while the solve time reported by ecos is roughly the same.

I dig a little deeper and find that, whenever `problem.solve()` is called, the problem is re-parsed from scratch(if I didnt missing any important details, L358 below):

https://github.com/cvxgrp/cvxpy/blob/43270fcc8af8fc4742f1b3519800b0074f2e6693/cvxpy/problems/problem.py#L358-L359

but the `quad_form` canonicalization is very expensive in this example: in `cvxpy.atoms.decomp_quad`, we need to call `np.linalg.eigh` with a `50 * 3000` matrix.
https://github.com/cvxgrp/cvxpy/blob/43270fcc8af8fc4742f1b3519800b0074f2e6693/cvxpy/atoms/quad_form.py#L183

This single step taks 3s+ while the ecos opt process only taks ~500ms. I have to switch to 0.4 for now.

Though when the matrix is smaller(e.g. 50 * 1500 takes much less time ~500ms), I think problems better be parsed and prepared once when initialize, and avoid possible works if they are not necessary, especially when some might be very time consuming.

This re-parse might explain why `without_compile`  and `wih_complie` take similar time with 1.0, while in 0.4 `without` take much less time, in  #409 

I'm using cvxpy 1.0.6 and 0.4.11

**Comment by frk2** [comment]
@kongscn I am experiencing the same - but am a noob to cvxpy. It makes no difference whether I setup the entire model from scratch each time or compile the problem once and use parameters.

**Comment by pnystrup** [comment]
@SteveDiamond I am experiencing the same problem. Version 1.0.x is too slow to use in cases, such as backtesting, where you want to solve the same (small) problem a large number of times with different parameter values. It's too bad, because I like the syntax of version 1.0 better.

**Comment by bstellato** [comment]
Are there any updates on this? I am experiencing a very similar problem. It looks like using parameters does not help in reducing the parse time for the 1.0 version.

**Comment by akshayka** [comment]
@bstellato You're right, we never got around to optimizing the parse time in the presence of parameters. It's an important TODO for us.

**Comment by bstellato** [comment]
Can we consider this fixed in #664?

**Comment by akshayka** [comment]
Yes, thanks @bstellato !!
