### ISSUE TITLE
root.args[0] and the expr passed to quad_form are the either convex or concave

### ISSUE THREAD

**Issue by Isaac1989** [cvxgrp/cvxpy#542]
So  I figure `root` variable is suppose to be some form of affine expression but there is something smelly with that line of code:
 **root = LinOp(NO_OP, expr.shape, [expr], [])**
in the method `quad_form`. In fact the  `expr` and `root.arg[0]` are the same expression, which doesn't make sense to me at this point. This is raising `ValueError` in the method *`affine`* of class `CoeffExtractor`.

Please any idea on how to fix this?
A newbie here so please take it easy on this submission.Thank you

**Comment by rileyjmurray** [comment]
In what context did you run into this issue? Are you running cvxpy 1.0?

The only invocation of ``CoeffExtractor.quad_form`` is in ``CoeffExtractor.get_coeffs``.  I can't find a single invocation of ``CoeffExtractor.get_coeffs`` in the remaining cvxpy source. In fact, I can't find an reference to ``CoeffExtractor`` anywhere outside of ``coeff_extractor.py``. 

I suspect the file should be removed from cvxpy.

@SteveDiamond, can you confirm that we can remove this file?

**Comment by rileyjmurray** [comment]
Update on ``coeff_extractor.py``

I was wrong about where ``CoeffExtractor`` is used in the project files. Of the five methods implemented by instances of this class, three are used elsewhere in project files:
* ``get_coeffs( ... )`` is used in ``matrix_suffing.py``, ``cone_matrix_stuffing.py``, and ``ls_conif.py``.
* ``affine(...)`` is used in  ``mosek_conif.py`` and ``scs_conif.py``
* ``quad_form(...)`` is in fact used in ``qp_matrix_stuffing.py``

and two are used as helper functions (only called within ``coeff_extractor.py``)

* ``constant( ... )`` is used in ``get_coeffs(...)``.
* ``extract_quadratic_coeffs(...)`` is used in ``quad_form(...)``

I'm not sure where that leaves us. @Isaac1989 , can you provide information on when you encountered this error?

**Comment by rileyjmurray** [comment]
Closing due to lack of response.
