### ISSUE TITLE
two CONVEX Positive problems minus

### ISSUE THREAD

**Issue by Messiwang1014** [cvxgrp/cvxpy#545]
I have a covarianc martix  P to be used in portfolio optimization ,**P = I-X*inverse(X'X)*X'**,  P is singular , I is a N*N identity matrix, X is a N*K matrix ,N is about 3000, K is about 40. i wanna minimize the variance = wPw', although the problem is solvable but it cost much time , so i want to use the form  like Portfolio optimization in cvxpy document examples,i.e. the form **ww'-f*inverse(X'X)f', f = wX**, these two problem minus could cost less time ,but the sign of this problem is UNKNOW,so it doesn't follow the DCP rules.

**Comment by rileyjmurray** [comment]
This question doesn't seem to be about any possible bug in cvxpy, and so it isn't really appropriate for a github issue. Please post it to stackexchange with the "cvxpy" tag.
