### ISSUE TITLE
ECOS_BB returns None

### ISSUE THREAD

**Issue by cyivy1992** [cvxgrp/cvxpy#546]
I'm using ECOS_BB for solving MIP (linear with binary variables). The solver occasionally returns 'none'. 
For example I'm solving a minimization problem:
with a constraint: aTx >= 0.9  it returns none,
however, it gives an solution when I change to a more restrictive constraint: e.g. aTx >= 1.0

**Comment by rileyjmurray** [comment]
This issue should likely be posted at https://github.com/embotech/ecos, rather than with CVXPY.

**Comment by cyivy1992** [comment]
Thanks! Just asked there.
