### ISSUE TITLE
cvppy on RHEL6 with python 2.7.14?

### ISSUE THREAD

**Issue by jGaboardi** [cvxgrp/cvxpy#548]
I learned about `cvxpy` at SciPy last week and I am very impressed with it. However, I do research in an extremely secure environment with relatively archaic software (the "powers that be" finally upgraded from `RHEL5` to `RHEL6` recently and were gracious enough to provide an `Anaconda` install of `python 3.6.3`).

I do not have a copy of `RHEL6` to do any testing on, but I do have `RHEL5` (with `python 3.6.2`), which I was unsuccessful in getting a working install of `cvxpy` into, [maybe due to an older version of the `C` library](https://stackoverflow.com/questions/7647818/glibc-elf-file-os-abi-invalid). The error message (with 2 `Exceptions`) when trying to `cvxpy` is below.

Issue #81 specifically referenced a Red Hat build that was successful (at least with installation), but I was not even able to get that far. Before asking the IT department to attempt the install I wanted to reach out to see if it is even possible to install `cvxpy` on `RHEL6`?

* OS: `RHEL6` with `gcc v4.4.7` and `gfortran `
* python: `3.6.3` with `2.7.14` environment (we have to use 2.7 due to other legacy code)

Thanks for any help/suggestions!
James

-------------------------------------------------
```
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cvxpy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py in swig_import_helper()
     17         try:
---> 18             fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
     19         except ImportError:

~/miniconda3/envs/py362/lib/python3.6/imp.py in find_module(name, path)
    295     else:
--> 296         raise ImportError(_ERR_MSG.format(name), name=name)
    297 

ImportError: No module named '_cvxcore'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-e37c0baa4c4c> in <module>()
----> 1 import cvxpy

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/__init__.py in <module>()
     19 
     20 __version__ = "1.0.6"
---> 21 from cvxpy.atoms import *
     22 from cvxpy.constraints import NonPos, Zero, SOC, PSD
     23 from cvxpy.expressions.variable import Variable

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/atoms/__init__.py in <module>()
     18 """
     19 
---> 20 from cvxpy.atoms.geo_mean import geo_mean
     21 from cvxpy.atoms.harmonic_mean import harmonic_mean
     22 from cvxpy.atoms.lambda_max import lambda_max

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/atoms/geo_mean.py in <module>()
     21 import numpy as np
     22 import scipy.sparse as sp
---> 23 from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
     24                                          over_bound, prettydict)
     25 

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/utilities/power_tools.py in <module>()
     19 
     20 from fractions import Fraction
---> 21 from cvxpy.atoms.affine.reshape import reshape
     22 from cvxpy.atoms.affine.vstack import vstack
     23 from cvxpy.constraints.second_order import SOC

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/atoms/affine/reshape.py in <module>()
     18 """
     19 
---> 20 from cvxpy.atoms.affine.affine_atom import AffAtom
     21 import cvxpy.lin_ops.lin_utils as lu
     22 import numpy as np

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/atoms/affine/affine_atom.py in <module>()
     23 from cvxpy.atoms.atom import Atom
     24 from cvxpy.expressions.constants import Constant
---> 25 from cvxpy.cvxcore.python import canonInterface
     26 from fastcache import clru_cache
     27 import scipy.sparse as sp

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/cvxcore/python/canonInterface.py in <module>()
     30 
     31 from cvxpy.lin_ops import lin_op as lo
---> 32 import cvxpy.cvxcore.python.cvxcore as cvxcore
     33 import numbers
     34 import numpy as np

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py in <module>()
     26                 fp.close()
     27             return _mod
---> 28     _cvxcore = swig_import_helper()
     29     del swig_import_helper
     30 else:

~/miniconda3/envs/py362/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py in swig_import_helper()
     18             fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
     19         except ImportError:
---> 20             import _cvxcore
     21             return _cvxcore
     22         if fp is not None:

ImportError: /home/$USER/miniconda3/envs/py362/lib/python3.6/site-packages/_cvxcore.cpython-36m-x86_64-linux-gnu.so: ELF file OS ABI invalid
```

**Comment by rileyjmurray** [comment]
We do not know of any reasons why you would be unable to install cvxpy on RHEL 6. Asking for help from your IT department is a good idea, but I'll provide some comments to help get you started.

Although there are two import errors, the second one seems more informative. 
> ImportError: /home/$USER/miniconda3/envs/py362/lib/python3.6/site-packages/_cvxcore.cpython-36m-x86_64-linux-gnu.so: ELF file OS ABI invalid

I'm no expert here, but I believe that the error message "ELF file OS ABI invalid" means that your operating system's default C program loader is reading some metadata from the specified file, and rejecting that file because it doesn't recognize the value for an important field.

You can find the metadata it's referring to by running this command:
```
readelf -h  /home/$USER/miniconda3/envs/py362/lib/python3.6/site-packages/_cvxcore.cpython-36m-x86_64-linux-gnu.so
```
On my machine the output of the analogous command was
```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x1ac10
  Start of program headers:          64 (bytes into file)
  Start of section headers:          5873488 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         6
  Size of section headers:           64 (bytes)
  Number of section headers:         37
  Section header string table index: 34
```

The piece of metadata you're looking for is the "OS/ABI" field. On my system it says "UNIX - GNU"; it should be the same on your system because we installed cvxpy from the same place (the cvxgrp channel on conda). Now, "UNIX - GNU" is a perfectly valid value for "OS/ABI". However, a more common value for "OS/ABI" is "UNIX - System V". If your C program loader is out of date, it might be rejecting the file because it says "UNIX - GNU" instead of "UNIX - System V".

So, if I was in your shoes, I would try to update my system's C program loader. (Mind you- I have no idea how to do that, but that's what I would be trying to figure out with the help of Google.)

**Comment by jGaboardi** [comment]
@rileyjmurray Thanks so much for the suggestions. Once I get it figured out I'll let you know so that other might benefit. In the meantime I am also trying to get an RHEL6 install of my own for testing.
