### ISSUE TITLE
AttributeError: module 'cvxpy' has no attribute 'GLPK_MI'

### ISSUE THREAD

**Issue by jiterika** [cvxgrp/cvxpy#551]
Hi, when i try to use GLPK_MI solver, i get the below error message.
AttributeError: module 'cvxpy' has no attribute 'GLPK_MI'
 I have cvxpy 1.06 and i see GLPK_MI in conic_solvers.  Can you help me resolve the issue @SteveDiamond @stephenpboyd 

Thank You

**Comment by rileyjmurray** [comment]
I suspect this has something to do with how cvxpy is installed on your machine. When you import cvxpy, that loads __init__.py, which definitely contains the definition for GLPK_MI.

Are other solvers working on your end? Please provide a minimal example showing when one solver works, but another (GLPK_MI) fails.

As a side note: please be judicious in when you tag specific people in a GitHub issue. There is no reason to tag Steven Diamond or Stephen Boyd here.

**Comment by jiterika** [comment]
Hi @rileyjmurray 

Thank you for the reply. Apologies for tagging them. This is my second post on GitHub, so was not sure if anyone will look into my question. I found their names in the guide and found Steven answering in most of the blogs, hence tagged them. 

Here is the example code. I am learning optimization and this is my first attempt. Please spare any foolish attempts

import cvxpy
import numpy as np

A=np.array([20,10,30,50,40])
B=np.array([15,0,50,25,0])
C=np.array([7.5,25,50,0,40])

Ac=np.array([5,3,2,6,4])
Bc=np.array([5,0,10,3,0])
Cc=np.array([3,5,7.5,0,15])

sa=cvxpy.Variable(len(A),True)
sb=cvxpy.Variable(len(B),True)
sc=cvxpy.Variable(len(C),True)

selection_constraint=sa+sb+sc==1
U_constraint=sa*Ac+sb*Bc+sc*Cc<=5
L_constraint=sa*Ac+sb*Bc+sc*Cc>=0

constraints=[selection_constraint,U_constraint,L_constraint]
obj=sa*A+sb*B+sc*C
opt_problem=cvxpy.Problem(cvxpy.Maximize(obj),constraints)
opt_problem.solve(solver=cvxpy.ECOS_BB)

when i use ECOS_BB, it returned 'inf', it didn't give any error though, but when i used GLPK_MI, it threw following error.

SolverError: The solver GLPK_MI is not installed.

when i tried installing GLPK_MI from Jupyter using the following command
!pip install GLPK_MI

it threw the below error
Collecting GLPK_MI
  Could not find a version that satisfies the requirement GLPK_MI (from versions: )
No matching distribution found for GLPK_MI

Also can you help me understand if i am doing something wrong while using ECOS_BB, because it's returning 'inf'. I suspect constraints are not being applied properly.

Thank You

**Comment by rileyjmurray** [comment]
No worries! Although from your more detailed information, I can say that this is a post better suited to StackExchange, with the tag ``cvxpy``.

I will say this, however: your variable declaration does not make sense. Writing ``sa=cvxpy.Variable(len(A),True)`` will result in undefined behavior, due to the second argument ``True`` not having an associated keyword. Since you are trying to use a mixed integer programming solver, I'm guessing that you want ``sa=cvxpy.Variable(len(A),integer=True)``.

**Comment by jiterika** [comment]
Hi @rileyjmurray ,

I am still not able to install GLPK_MI. Do you have any comments about that.
I wanted sa,sb,sc to be boolena variables. i will specify Bool=True, but can you help me with GLPK_MI 

Thank You

**Comment by rileyjmurray** [comment]
If you specify ``Bool=True`` cvxpy will give you an error. Please refer to the cvxpy documentation, specifically:
http://www.cvxpy.org/tutorial/advanced/index.html#mixed-integer-programs
There you will find that the proper keyword is ``boolean`` a lowercase "b".

Help with installation of additional solvers is beyond the scope of what we address in GitHub issues (unless it's a solver we've just started to support, and we're working out kinks in the interface). I do not use pip personally, and so I cannot make recommendations for how to install GLPK_MI via pip. Please direct that specific question to StackExchange with any tags you might think relevant.
