### ISSUE TITLE
is_psd() and is_nsd() depending on eigvals

### ISSUE THREAD

**Issue by milandotlic** [cvxgrp/cvxpy#553]
In the file expressions/constants.py functions psd() and is_nsd() should be changed

if one of the eigenvalues is mathematically zero, numerically it doesn't have to be. For example if the largest eigenvalue is 10^3, eigenvalue that is mathematically zero can be anything in range (-10^-13,10-13). 

Therefore lines 
197 return all(self._eigvals.real >= 0)
and 
218 return all(self._eigvals.real <= 0)

should be changed to something like 
(>=) - 10^-(16-exponent_of(np.max(self._eigvals.real)))
(<=)

**Comment by rileyjmurray** [comment]
Constant objects are used to cast numeric types (including numpy n-d arrays) to cvxpy Expressions. They are meant to have rigid tests for properties like sign, and PSD/NSD-ness.

If you have a term in your model that is PSD in exact arithmetic, you can use more generous tests for PSD-ness by declaring ``P = cvxpy.Parameter(P_array, PSD=True) ``.  When you declare ``P`` in this way, the constructor checks if the problem data ``P_array`` has sufficiently small projection onto the PSD cone after an eigen-decomposition (this happens in ``_validate_value`` of ``Leaf.py``, which in turn relies on ``project`` in ``Leaf.py``). We have verified that this allows for PSD matrices with nontrivial kernel.
