### ISSUE TITLE
inconsistent behavior with sparse objective function

### ISSUE THREAD

**Issue by jdark-tremor** [cvxgrp/cvxpy#557]
Here is a minimal (non-) working example:
```python
from cvxpy import *
import numpy as np
import scipy.sparse as sparse

# Here are our QP factors
A = Constant(sparse.eye(4))
c = np.matrix(np.ones(4)).reshape((1,4))

# Here is our optimization variable
x = Variable(4)

# And the QP problem setup
function = quad_form(x, A) - c @ x
objective = Minimize(function)
problem = Problem(objective)

problem.solve()
print(function.value)  # this output is the weirdness under consideration
```

The expected output is either a scalar or 1x1 matrix with the value of -1. Running the code, I get a 4x4 matrix with -1 along the diagonal and -2 elsewhere. Were I to have instead set ``A = np.ones(4)``, the problem does not occur. Leaving ``A = Constant(sparse.eye(4))`` alone, I can also get the desired output by setting ``function = quad_form(x, A)[0,0] - c @ x``. However, while this works when OSQP is the solver, it will segfault when any other solver is used (tested against ECOS, SCS, and CVXOPT).

System info: Python 3.6.6, numpy 1.14.5, scipy 1.1.0, and cvxpy 1.0.6.

**Comment by SteveDiamond** [comment]
Fixed on master.
