### ISSUE TITLE
SuperSCS support!

### ISSUE THREAD

**Issue by Cerebrock** [cvxgrp/cvxpy#562]
To my understanding cvxpy should support superscs ( https://kul-forbes.github.io/scs/page_doc.html#seccvxpython ), but after installing in a conda env and being able to import, it doesn't appear in installed_solvers()

**Comment by SteveDiamond** [comment]
Sorry, we must have lost the interface in the upgrade to 1.0. We'll take a look and put it back!

**Comment by Cerebrock** [comment]
Please ping this thread then!

**Comment by rileyjmurray** [comment]
PR #565 addresses this.
