### ISSUE TITLE
indicator test error

### ISSUE THREAD

**Issue by dsp6414** [cvxgrp/cvxpy#570]
import cvxpy as cvx   #version 1.0.8
from cvxpy.transforms.indicator import *
x = cvx.Variable()
constraints = [0 <= x, x <= 1]
expr = indicator(constraints)
x.value = .5
print("expr.value = ", expr.value)
x.value = 2
print("expr.value = ", expr.value)

result : 
expr.value =  0
expr.value =  0

**Comment by gbanjac** [comment]
This is fixed in the current master branch. I get the following output:
```
expr.value =  0
expr.value =  inf
```
I vote for closing this issue.
