### ISSUE TITLE
MOSEK solver TypeError

### ISSUE THREAD

**Issue by czrcbl** [cvxgrp/cvxpy#571]
Hi,
When using MOSEK solver (version 8.1.60) with cvxpy (version 1.0.8 ) I get the following error `TypeError: keyword arguments must be strings` on the expression:
```
STATUS_MAP = dict(STATUS_MAP, **STATUS_MAP_INACCURATE)
```
On the `../.cvxpy/reductions/solvers/conic_solvers/mosek_conif.py` file, line 448. It seems like a bug.
I solved it by changing the the line to 
```
STATUS_MAP.update(STATUS_MAP_INACCURATE)
```
But I don't know if it is a suitable solution.

**Comment by rileyjmurray** [comment]
Your solution is valid, although I'm surprised that you're seeing this error. @aszekMosek wrote and tested the status map updates just recently.

**Comment by aszekMosek** [comment]
That is a good solution. I'll have a look at the bug

**Comment by aszekMosek** [comment]
Yes, I see. Probably Python3 doesn't like it. @czrcbl do you want to make the PR?

**Comment by czrcbl** [comment]
OK, I will do it
