### ISSUE TITLE
Trend filtering example doesn't work

### ISSUE THREAD

**Issue by dave31415** [cvxgrp/cvxpy#576]
https://www.cvxpy.org/examples/applications/l1_trend_filter.html?highlight=trend
ValueError: Cannot broadcast dimensions  (1999,) (1999, 1)

**Comment by bstellato** [comment]
Yes, it needs to be updated. Check [this issue](https://stackoverflow.com/questions/50114387/l1-trend-program-not-working-cvxopt-cvxpy/50282557#50282557).

**Comment by akshayka** [comment]
https://github.com/cvxgrp/cvxpy/pull/634 updated the example library, including the trend filtering example.
