### ISSUE TITLE
Remove old solver interfaces

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/cvxpy#581]
After `1.0` it seems many interfaces are now duplicated.

- old interfaces: `cvxpy/problems/solvers`
- new interfaces: `cvxpy/reductions/solvers` divided by LP, QP and Conic solvers.

Is there any reason why we are keeping the old interfaces? I believe this would help a lot to keep the code clean.

**Comment by rileyjmurray** [comment]
Many of the current "1.0" interfaces are wrappers around old 0.4-style interfaces.

**Comment by bstellato** [comment]
That's exactly my point. The current structure makes it harder to locate where the solvers interfaces are and to maintain them. I believe it would be much better to keep them in the same location, i.e., `cvxpy/reductions/solvers` with no wrappers around older versions.

**Comment by rileyjmurray** [comment]
Oh absolutely. It's just a matter of developer effort to fix that. I'll update this with a "help wanted".

**Comment by SteveDiamond** [comment]
I got rid of the old ECOS interface, which wasn't doing anything. I guess we move them one by one. Unfortunately I had to accept some contributions into the old interfaces that people started before the switch to 1.0, like Xpress.

**Comment by SteveDiamond** [comment]
Done!
