### ISSUE TITLE
mosek interface

### ISSUE THREAD

**Issue by wiehern** [cvxgrp/cvxpy#583]
Sorry I cannot delete this. Right after writing it, I saw it is fixed in master. 

The problem is https://stackoverflow.com/questions/52056655/mosek-solver-on-cvxpy-typeerror.

**Comment by aszekMosek** [comment]
I think you should try master. As far as I see version 1.0.9 should have been tagged but wasn't.

**Comment by rileyjmurray** [comment]
I'll leave this open until @SteveDiamond pushes 1.0.9.

**Comment by SteveDiamond** [comment]
Ok I pushed it.
