### ISSUE TITLE
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by alvaromc317** [cvxgrp/cvxpy#584]
Hello, I am trying to install cvxpy module on a linux-based OS (CentOS).  I followed the steps from the website https://www.cvxpy.org/install/index.html and it appeared to be correctly installed. However, when I open python and try to import the cvxpy module I get the following error message:

![image](https://user-images.githubusercontent.com/32359999/45963142-c9b05e00-c022-11e8-90a5-d5b9df170c2b.png)

Surfing on internet I found some suggestions on how to fix it, mainly installing "conda install libgcc" but this didnt work.  I am working with Python 2.7 installed using miniconda.

**Comment by wiehern** [comment]
It seems cannot find the correct version of libgcc. Add the miniconda lib path to LD_LIBRARY_PATH *might* fix this. 
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/miniconda2/lib `

**Comment by SteveDiamond** [comment]
As part of a general issue purge, I'm closing this until/if it comes up again. The installation process has changed so much it may have gone away.
