### ISSUE TITLE
Feature request: CBC time limit for MIP solver

### ISSUE THREAD

**Issue by wkschwartz** [cvxgrp/cvxpy#585]
CyCBC [supports](https://github.com/coin-or/CyLP/blob/master/cylp/cy/CyCbcModel.pyx#L232) CBCModel's [setMaximumSeconds](https://www.coin-or.org/Cbc/cbcuserguide.html#setsandgets) method. This could be set as a `solver_option` named `MaximumSeconds` (or, I think better, `time_limit`) and applied [here](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/problems/solvers/cbc_intf.py#L171).

**Comment by SteveDiamond** [comment]
Wow the CBC interface is much worse than I remembered. You can't specify options at all! The standard way we handle this is to pass in generic keyword arguments which are unpacked in the solver. We should just get rid of the old CBC interface and move it to ``cbc_conif.py`` and handle options correctly.

**Comment by SteveDiamond** [comment]
This is fixed on master. Sorry for the super long delay, I'm trying to clean up cvxpy now that I have more time.

**Comment by SteveDiamond** [comment]
For reference, solver options are specified via the CyCBC name (here ``maximumSeconds``) passed as a solve option (eg ``prob.solve(maximumSeconds=100)``.
