### ISSUE TITLE
Specify conda channel for dependencies (osqp and lapack)

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/cvxpy#587]
It would be useful to automatically install 

- `lapack` from the `conda-forge` channel
- `osqp` from the `oxfordcontrol` anaconda channel 

when we execute the [install command](http://www.cvxpy.org/install/index.html#install):

`conda install -c cvxgrp cvxpy`

I am not sure if the users already do it automatically or if they have to add channels separately. It seems that for the `lapack` package they have to run a separate command.

@mcg1969 is there a way to specify the dependencies' channels from the conda recipe?

This is related to https://github.com/conda/conda/issues/988.

**Comment by mcg1969** [comment]
No, the channels cannot be specified within the conda recipe (meta.yaml) itself. You could add the channels to the CI scripts though.

However, there needs to be another solution here. It is not good practice to depend on a particular channel's package like this. That is to say, you really don't want to force someone to add `conda-forge` to their channel list just to use your package. You need to find a way to get `lapack` more universally. Perhaps from scipy?

**Comment by rileyjmurray** [comment]
In CI scripts we can add the oxfordcontrol channel. However for everyday users, they should be able to run ``conda install -c cvxgrp cvxpy`` and *not* get an outdated or unsupported version of one of cvxpy's dependencies (OSQP being the one I'm worried about).

@bstellato if the conda-forge version of OSQP will no longer be updated, then we can simply update cvxpy's minimum version of OSQP to something higher than can be found on conda-forge. It looks like setting ``osqp >= 0.4.1`` would do the trick. That specification would need to be made in the conda recipe (https://github.com/cvxgrp/cvxpy/blob/master/conda-recipe/meta.yaml#L31), and setup.py (https://github.com/cvxgrp/cvxpy/blob/master/setup.py#L39).

**Comment by bstellato** [comment]
The conda recipe will be updated at some point but we are not supporting it ourselves. We are supporting our version https://github.com/oxfordcontrol/osqp-recipes for which @mcg1969 helped a lot to simplify the build and deploy scripts.

**Comment by rileyjmurray** [comment]
I see.

@SteveDiamond @akshayka what do we need the lapack dependency for?

**Comment by bstellato** [comment]
Lapack is used in SCS conic projections I think

**Comment by SteveDiamond** [comment]
The Anaconda installation instructions now say to add the ``oxfordcontrol`` channel.
