### ISSUE TITLE
travis reports a 1.0.9 build, but master is 1.0.8.

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#589]
Here's the "tag" (not a "branch"?) with cvxpy 1.0.9:
https://github.com/cvxgrp/cvxpy/tree/v1.0.9

Here's the master branch (currently sitting at 1.0.8):
https://github.com/cvxgrp/cvxpy/tree/master

I found the 1.0.9 "tag" after checking TravisCI's build status: https://travis-ci.org/cvxgrp/cvxpy/builds.

**Comment by SteveDiamond** [comment]
Fixed. Not sure what happened.
