### ISSUE TITLE
OSQP solver errors in tests

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#590]
OSQP was recently updated, and now two cvxpy tests for the OSQP interface fail.

See https://travis-ci.org/rileyjmurray/cvxpy/jobs/435773573#L2195 and https://travis-ci.org/rileyjmurray/cvxpy/jobs/435773573#L2213 for the TravisCI logs where the failure occurs.

@bstellato 

Edit: I just realized that the above links are for my fork of cvxpy, but my repo only differs from the official repo in terms of documentation. You can verify that builds for this repo also fail on Travis.

**Comment by bstellato** [comment]
@gbanjac could you please have a look into this? It should be related to this commit https://github.com/oxfordcontrol/osqp-python/commit/43bdecc02c22f715f285f16716ba5524b87ebd3a

I believe it can be fixed in a couple of line changes to the `osqp_qpif.py` file.

**Comment by SteveDiamond** [comment]
Thanks for catching this! It's always fun when the CI fails because of other packages...

**Comment by bstellato** [comment]
Sorry for the confusion guys. I made a PR.
