### ISSUE TITLE
Sample code doesn't match documenting output in doc/source/tutorial/intro/index.rst

### ISSUE THREAD

**Issue by renewang** [cvxgrp/cvxpy#593]
In the second example, **Changing the problem**:

```
# Replace the objective.
prob2 = cvx.Problem(cvx.Maximize(x + y), prob.constraints)
print("optimal value", prob2.solve())

# Replace the constraint (x + y == 1).
constraints = [x + y <= 3] + prob.constraints[1:]
prob2 = cvx.Problem(prob.objective, constraints)
print("optimal value", prob2.solve())
```

Execute this piece of code following the first example, would output as the following:

optimal value 0.9996939016105745
optimal value 1.0

This output is inconsistent with the document:

optimal value 1.0
optimal value 3.00000000006

One should change the line in code above
prob2 = cvx.Problem(**prob**.objective, constraints)  
into   
prob2 = cvx.Problem(**prob2**.objective, constraints)

to make more sense output (like the following in my python console, cvxpy version == '1.0.8')

optimal value 0.9996939016105745
optimal value 3.0009677118090208

How does everyone think here?  Is it a mistake in documentation?

**Comment by akshayka** [comment]
Thanks, I fixed the bug in the documentation. @SteveDiamond , can you push the update to the website?

**Comment by bstellato** [comment]
The website deployment could be automated using travis. 

For osqp [we generate the docs using doxygen + sphinx and push them to the website repository](https://github.com/oxfordcontrol/osqp/blob/master/ci/travis/docs.sh). It could be done for cvxpy `gh-pages` branch as well.

**Comment by SteveDiamond** [comment]
Thanks! For now our approach to generating the web site is fine. I've been burned with an automated approach.
