### ISSUE TITLE
1.0.9 fails setup.py when installing over pip (__NUMPY_SETUP__ attribute)

### ISSUE THREAD

**Issue by lpfann** [cvxgrp/cvxpy#594]
The newest built could not be installed correctly over pip.
The new numpy header injection method seems problematic.(?)

`AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'`
Detailed log on travis at the installation step can be found [here](https://travis-ci.org/lpfann/fri/jobs/437299138).

**Comment by akshayka** [comment]
@SteveDiamond , @shariat --- any idea what's going on here?

**Comment by shariat** [comment]
Wkk take a look

**Comment by shariat** [comment]
> CPython implementation detail: Users should not touch __builtins__; it is strictly an implementation detail. Users wanting to override values in the builtins namespace should import the __builtin__ (no ‘s’) module and modify its attributes appropriately.

see https://docs.python.org/2/reference/executionmodel.html
