### ISSUE TITLE
GLPK installation

### ISSUE THREAD

**Issue by wkschwartz** [cvxgrp/cvxpy#599]
CVXOPT now [bundles GLPK](http://cvxopt.org/install/index.html#installing-a-pre-built-package) as part of its standard Wheel distribution binaries for Linux, Windows, and macOS on PyPI. Thus all that's needed to make GLPK work out of the box with cvxpy on all but the strangest setups is `pip install cvxopt`. Rather than just updating the [now out-of-date instructions](http://www.cvxpy.org/install/index.html#install-with-glpk-support) in the documentation, cvxpy could simply add `"cvxopt >= 1.2.1"` as one of the `install_requires` items in `setup.py`. Then GLPK would become a first-class pre-bundled solver, just like SCS, ECOS, and OSQP (meaning updating those docs too).

If you don't want CVXOPT to be installed by default, you can always put it in `setup.py`'s `extra_requires` so that people can install GLPK support with `pip install cvxpy [glpk]`.

**Comment by akshayka** [comment]
That's a good suggestion! Do you want to create a pull request that implements the "extra_requires" option?

**Comment by wkschwartz** [comment]
@r-barnes That commit (845cf2e) is part of PR #619, which is awaiting review. Merging the PR will close this issue.

**Comment by SteveDiamond** [comment]
I merged in PR #619
