### ISSUE TITLE
Partial optimize is not callable

### ISSUE THREAD

**Issue by minkkkk** [cvxgrp/cvxpy#606]
Partial optimize is not callable
How can I figure it out?

  File "C:/Users/soyeon/Desktop/2018 Fall/test1017.py", line 55, in TestAtoms
    g = cvxpy.partial_optimize(p2, [y], [x])

TypeError: 'module' object is not callable

**Comment by rileyjmurray** [comment]
This sort of error message suggests that your python environment is not configured properly. Please post this on StackExchange with a ``cvxpy`` and ``windows`` tag. When you make your post- be sure to provide much more information than you gave above.
