### ISSUE TITLE
Methods in feature/dccp branch

### ISSUE THREAD

**Issue by miggy2129** [cvxgrp/cvxpy#609]
I'm trying to get DMCP to work on CVXPY 1.0.9. It says on the repository that I have to install the feature/dccp branch from this repository. However, when I checked, feature/dccp branch is still implemented in CVXPY 0.4. Hence, why I'm having difficulty working with methods such as **is_atom_multiconvex()**.

I'm trying to figure out which functions, methods, and classes are unique to the feature/dccp branch, so I can reimplement them on the DMCP implementation instead. Can I get any help on this? 

Also, would it be better if these dependencies be implemented instead on this repository rather than reimplementing them on the DMCP repository? In this case, I can also work on updating the feature/dccp branch, and hopefully integrating it to the main branch.

**Comment by SteveDiamond** [comment]
DMCP should work with CVXPY 1.0. Could you just switch to 1.0 and see what's missing? So many things have changed I'm not quite sure what's in there and what's not.

Whether the features should be in cvxpy or in dmcp depends on how general they are.
