### ISSUE TITLE
Repeat the constraints in 2D-array

### ISSUE THREAD

**Issue by sheekhey** [cvxgrp/cvxpy#622]
Can the constraints repeat for 2 same things in a 2D-array?
`
totalTime=50
duration = 4
totalCourse=2
startHour= cvx.Variable( (totalCourse, totalTime), boolean=True)
nextHour= cvx.Variable( (totalCourse, totalTime), boolean=True)
for c in range(totalCourse): 
  constraints.append(cvx.vec(startHour[c])+ cvx.vec(nextHour[c]) <=1) 
  constraints.append(cvx.vec(startHour[c]) + cvx.vec(nextHour[c]) == duration
# Form objective.
obj = cvx.Minimize(1)

# Form and solve problem.
prob= cvx.Problem(obj, constraints)
prob.solve() # Returns the optimal value.
`
Because it does not work for me. If I separate do, then it work for me.

**Comment by sheekhey** [comment]
cvx.vec(startHour[c]) : I write this because I want to vectorize the two 2D-array and add together so that they less that one. This mean that startHour[0][0]+nextHour[0][0]<=1, startHour[0][1]<=nextHour[0][1]....

Sorry, I have paste wrong constraint ady. Below are the correct code:
`
constraints.append(cvx.vec(startHour)+ cvx.vec(nextHour) <=1) #to make sure the classes wont overlap for one course
constraints.append(cvx.sum(startHour) + cvx.sum(nextHour) == duration)#ensure have 4hrs class
`

**Comment by arlenk** [comment]
honestly, I think this is more of a modeling question than an issue with cvxpy.  cvxpy can handle the constraints you specified and is able to solve the problem with those constraints, but I don't think your model is solving the problem you want to solve.

You will probably have better luck asking here:
https://groups.google.com/forum/#!forum/cvxpy

**Comment by SteveDiamond** [comment]
Agreed. I'm not really sure what you're asking, better to discuss it on the forum or stackoverflow.
