### ISSUE TITLE
have AppVeyor deploy Windows builds to conda and pypi

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#627]
### Problem (and current "solution")
Right now cvxpy's documentation recommends that people use conda to get the latest version of cvxpy. This is fine advice for linux and mac users, but it doesn't work well for Windows users. The only way for a Windows user to get the latest version of cvxpy is to install from a source distribution hosted on [pypi](https://pypi.org/project/cvxpy/).

If a Windows user doesn't already use conda, then they simply install cvxpy by running ``pip install cvxpy`` in the command line. However, if a Windows users needs the most up-to-date version of cvxpy in a conda virtual environment, the installation process is more complicated. Specifically, if their desired conda virtual environment is named "myEnv", then they should run two pairs of commands:
```
activate myEnv
conda install pip
```
and
```
activate myEnv
pip install cvxpy
```
The first line in the second block of commands isn't really necessary, but it helps make the procedure fool-proof (in the event that the commands are not executed in the same command line window).

### Proposed changes

Although the above approach should get the job done, it is unnecessarily complicated. Our AppVeyor scripts should be updated so that Windows binaries are uploaded to the ``cvxgrp'' conda channel whenever AppVeyor builds succeed. 

On a related note, @bstellato suggests in https://github.com/cvxgrp/cvxpy/issues/615#issuecomment-434050947 that we upload *binaries* (in addition to source distributions) to pypi. Pypi allows Windows and OSX binaries natively, and also allows a certain type of Linux build ("[manylinux](https://www.python.org/dev/peps/pep-0513/#pypi-support)"). A full resolution of this issue should include pushing Windows binaries to pypi upon successful AppVeyor builds.

The main obstacle in making these changes is that I don't know how AppVeyor handles censoring sensitive environment variables (like conda usernames and passwords) that we will need for the upload process. (Right now our AppVeyor continuous integration scripts do not upload any distribution of cvxpy upon a successful build; the source distribution which Windows users currently rely on is in fact uploaded after successful TravisCI builds.)

**Comment by bstellato** [comment]
Appveyor can encrypt variables just as travis. Check out the [secure variables](https://www.appveyor.com/docs/build-configuration/#secure-variables) section of their docs. That's what we have for the [osqp recipes](https://github.com/oxfordcontrol/osqp-recipes/blob/master/appveyor.yml).

The only issue I see with binary wheels is that **pypi do not allow deleting a file**. They are way less flexible than anaconda. Pypi requires you to create a new version number to upload a different file. One can use the `test.pypi` server for uploads but in order to have the final files on pip you need to use the main server. That's why we upload the osqp wheels to a [separate space](https://bintray.com/bstellato/generic/osqp-wheels), [download them](https://github.com/oxfordcontrol/osqp-wheels/blob/master/download_wheels.py) before the upload using twine.

Not sure this is the ideal way but that's the compromise we found for now with osqp. I believe it would help having binary wheels for cvxpy and the solvers (the scs compilation seems problematic when lapack cannot be found).

Making these things work is a huge pain and takes time but it is a good long-term investment.

**Comment by rileyjmurray** [comment]
Paging @SteveDiamond and @akshayka .

What was the reason for requiring libgcc as a build and run requirement in [cvxpy's conda recipe](https://github.com/cvxgrp/cvxpy/blob/master/conda-recipe/meta.yaml)? I ask because libgcc is [not available for Windows](https://anaconda.org/anaconda/libgcc), which means I'm currently blocked from making Windows conda builds by this requirement.

I'm under the impression that some C++ compiler is needed for cvxpy builds, since cvxcore is written in C++. With that in mind, libgcc works for linux and mac just fine, but it doesn't work for Windows. In the case of Windows, the standard Visual Studio C++ compiler is what does all the work. Do either of you know how to specify a compiler requirement in a less-platform-specific way?

**Comment by SteveDiamond** [comment]
@rileyjmurray I don't remember the details, but adding libgcc arose from issues people posted. I'm not certain if it's really necessary, but it did make a difference at one point. I found this with some googling: https://conda.io/projects/conda-build/en/latest/source/resources/define-metadata.html#preprocessing-selectors

**Comment by rileyjmurray** [comment]
Okay I have Windows builds succeeding. But for some reason uploading those builds to my conda channel isn't working.

**Comment by rileyjmurray** [comment]
Got it working! (Windows builds on conda, that is.)

**Comment by rileyjmurray** [comment]
Okay, here's where we stand. I tried to get everything to work with 3.5, 3.6, and 3.7. Turns out several cvxpy dependencies aren't ready for python 3.7 (at least on Windows), so we can only really hope for 3.5 and 3.6 support.

- Windows binaries (3.5 and 3.6) successfully build with conda. The result isn't perfect, in that cvxpy gets packaged with a version of SCS that doesn't link with MKL properly (the version of SCS on the cvxgrp channel), but cvxpy still installs fine on Windows machines via conda - no compiler needed. If someone wants full SCS support, then they will need a compiler to pip-install SCS version 2.x.
- Python 3.6 wheels build successfully. There is a [very obscure error](https://ci.appveyor.com/project/rileyjmurray/cvxpy/build/job/vq6mlgmhgbsvp4r2) when attempting to build Python 3.5 wheels. For 3.6 I tried installing cvxpy with a "pip install" pointing to test-pypi. Before doing this I had to manually install all of cvxpy's dependencies. It is easy enough to get osqp, ecos, multiprocess, fastcache, six, numpy, scipy, lapack, mkl via pip. But if you don't have a compiler then the *only* SCS option is version 1.2.6 on the cvxgrp conda channel  (there is no pip option which satisfies cvxpy's version requirements on SCS). Once the dependencies were in place, a "pip install cvxpy" went off without a hitch.

Overall I think that the conda distribution is in a reasonable state.

Wheels for Windows is another story. The problem is that even with pre-built wheels for cvxpy, there is no way to install SCS on Windows without either conda (in which case you can get version 1.2.6 off the cvxgrp channel) or a compiler (in which case you can get version 2.x from pypi). As long as SCS is a hard requirement for cvxpy, these distribution requirements (needing either a compiler, or conda) directly carry over to requirements for cvxpy. This seems to largely defeat the purpose of having wheels at all.

I am inclined to drop the idea of cvxpy wheels for Windows. It should be doable for me to add osx and manylinux wheels to Travis builds, but that won't be part of resolving this (GitHub) issue.

@SteveDiamond @akshayka @bstellato your input is welcome.

**Comment by SteveDiamond** [comment]
@rileyjmurray conda is good enough in my view. If people run pip, everything will compile, so I don't see why we need wheels. Does cvxpy pass the nosetests with the version of SCS you mentioned?

**Comment by rileyjmurray** [comment]
Tests are a delicate issue because of SCS.

For CI *testing* we use a properly linked instance of SCS 2.x. We get this instance as a source distribution from pypi. Since the AppVeyor Windows VM has several compilers, we are able to install from the source distribution without any trouble. The full suite of cvxpy tests passes with this version of SCS. Once the tests succeed, we need to build the conda package.

When building a conda package, the build process is blind to any compilers which are not declared as a dependency in the conda recipe. Right now there is no compiler requirement for Windows machines in the conda recipe, so although the AppVeyor VM has compilers, the current conda-build needs access to a no-compiler-needed version of SCS. 

The only no-compiler-needed version of SCS (for Windows!) is a particular instance (v 1.2.6) on the cvxgrp channel. So I add the cvxgrp conda channel to build dependencies, and the build process succeeds. Note that the conda-build process does not run the full suite of cvxpy tests; it only runs import tests. If you tried to run the full suite of cvxpy tests on the built package, then they would fail because the associated version of SCS cannot solve SDPs with matrix variables of order > 2.

**Comment by SteveDiamond** [comment]
Ok that's not ideal. People will complain endlessly about the tests failing. Can you require a compiler for the Windows builds?

**Comment by rileyjmurray** [comment]
I've looked into the possibility of adding a suitable Windows C/C++ compiler requirement to the [Windows] conda recipe. Rather than ``libgcc``, conda-forge has access to ``mingwpy``. MinGWPy nominally provides access to the compilers that would be needed for a source install of SCS, but ``pip install scs`` will download a source distribution with a ``setup.py`` file that is unable to take advantage of these compilers.

It may be possible to modify scs-python's [setup.py file](https://github.com/bodono/scs-python/blob/master/setup.py) to check for MinGWPy compilers. Currently that file tries to use the MSVC compiler that comes with distutils. From what I understand, that compiler only goes up to version 9, which isn't enough to compile C extensions for Python > 3.2. The scs-python project has [AppVeyor tests](https://github.com/bodono/scs-python/blob/master/.appveyor.yml), so it does work on Windows. But those AppVeyor tests are on machines which contain all the necessary compilers (Visual C++ 10 / 14) to compile C extensions for any modern version of Python.

So at the moment, there is no indication to me that it is possible to properly install SCS on a Windows machine without first requiring the user to install Visual C++ 14. There is no mechanism in the conda framework for requiring that kind of dependency.  If my assessment here is correct, that would mean there is no way to have both (1) SCS as a cvxpy dependency, and (2) a fully-functional cvxpy conda package for Windows users.

@bodono does my assessment sound plausible to you?

**Comment by rileyjmurray** [comment]
There's also the ``m2w64`` compiler toolchain on conda-forge. That package is more actively maintained than ``mingwpy``. Even with both ``m2w64`` and ``mingwpy`` installed in a conda environment, running ``pip install scs`` (within the conda environment) fails unless Visual C++ 10/14 is installed.

**Comment by SteveDiamond** [comment]
An update here, I've switched the installation instructions to recommend pip. So we should be good for windows, right? Having conda too would be desirable if we can swing it of course.

**Comment by rileyjmurray** [comment]
By switching the recommended install to pip (and stating a C++ compiler requirement), the install behavior on Windows should be fine (i.e. there won't be an issue with an improperly linked version of SCS).

Although I feel like now we need to play a bit of catch-up. It doesn't make sense for all of our CI testing to use conda to manage dependencies for us, if users have to figure out those dependencies some other way.

@akshayka this is going to sound ridiculous, but how does pip manage dependencies? When I tried "pip install cvxpy" without first manually installing dependencies, the install process failed.

**Comment by akshayka** [comment]
Typically the setup.py file lists requirements, which if missing are
automatically installed by pip before the package is installed.

The behavior in our case is a little weirder because we build a C++
extension (cvxcore), which requires numpy. The extension might be built
before pip installs numpy ... does that seem related to the error you see?

**Comment by bstellato** [comment]
This might be OT (and sound weird) but what do you think about having cvxcore written in cython? This installation problems with the C++ extension might become easier. Also, it might make it easier to maintain the code and to include slow parts of cvxpy in it. Just a thought..

**Comment by rileyjmurray** [comment]
This was resolved (and should have been closed) several months ago.
