### ISSUE TITLE
* is matrix multiplication rather than elementwise multiplication

### ISSUE THREAD

**Issue by zhou13** [cvxgrp/cvxpy#628]
I understand that it might be too late to change this for compatibility reason.  I feel awkward when mixing `*` operator with numpy because they have different meaning.  But this behavior is not emphasized enough in the tutorial since this is inconsistent with numpy and and pep465.  We need to use `multiply` to do the element-wise multiplication.

In numpy, `@` is reserved for matrix multiplication and `*` is reserved for element-wise multiplication.

**Comment by SteveDiamond** [comment]
Yes, this is a difference with numpy that will not change for compatibility and other reasons. The main reason was that I need a reasonable matrix multiplication symbol in Python 2.7, and it would be confusing to have * mean one thing in Python 2.7 and another in Python 3. I could see emphasizing this more in the tutorial certainly

**Comment by akshayka** [comment]
I've updated the documentation to emphasize this. It'll be reflected on the website within the next week or so.
