### ISSUE TITLE
ECOS infeasible inaccurate for MIP problem 

### ISSUE THREAD

**Issue by andrewibbetson** [cvxgrp/cvxpy#631]
I am trying to solve a mixed integer problem, where I need to ensure that there are enough household (HH) slots available for allocation of individuals.

The data (simplified), includes (1) a matrix of household slots where rows represent households and columns represent a specific characteristic and (2) the total number of individuals who need to be allocated to households by characteristic:

```
HH_slots = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])
Individuals = [8, 8, 8, 8]
```

I need to minimise changes to the household composition:

```
change_HH_slots = cp.Variable(shape=(len(HH_slots), len(HH_slots[0)), integer=True)
obj = cp.Minimize(cp.sum_squares(change_HH_slots))
```

with constraints, (1) a HH slot cannot be negative, (2) the sum of household slots by characteristic is equal to the sum of individuals by characteristic - so that all individuals have a HH slot to be allocated to:

```
constraints = []
for HH in HH_slots:
    for characteristic in len(HH_slots[0)):
        constraints += [HH_slots[HH][characteristic] + change_HH_slots[HH][characteristic] >= 0]

constraints += [sum(HH_slots) + sum(change_HH_slots) == Individuals]
```

the problem:

```
prob = cp.Problem(obj, constraints)
prob.solve()
```

The ECOS solver is called and prob.status returns 'inaccurate_infeasible' and prob.value returns 'None'

It is not obvious to me why this problem is infeasible. Perhaps my programming of it is wrong.

But it seems to struggle when there are a large number of households eg. If I remove one HH (row) from HH_slots it provides a solution. 

The real version of this problem (not simplified) involves ~ 600 households and 14 characteristics (a 600x14 matrix). 

Thanks,
Andrew

**Comment by SteveDiamond** [comment]
The limitations of ECOS for mixed integer problems is a recurring issue. We may even remove support for the ECOS mixed integer solver because it fails so frequently. Unlike convex problems, mixed integer programs are not guaranteed to be solved. Try using another solver, like Cbc or GLPK.

**Comment by wkschwartz** [comment]
Removing support for ECOS_BB may be easier now that GLPK is easier to install via Pip: see #599. In #619 I had made CVXOPT/GLPK an optional feature. Perhaps it would be better to make GLPK install by default?

**Comment by wkschwartz** [comment]
Is this related to #578?

**Comment by rostyboost** [comment]
I also vote for dropping ECOS_BB or at least defaulting to GLPK for MIP. GLPK performs much better than ECOS_BB. The later one drops the towel for most non-trivial MIP problems you throw at it.

**Comment by rileyjmurray** [comment]
ECOS_BB has been dropped for cvxpy 1.1, as of #973. The recommended open-source MILP solver is now GLPK. In order to use GLPK, one needs to install the cvxopt python package.

Ideally we would include GLPK with cvxpy. We cannot do this, because the current license systems are incompatible: cvxpy uses the Apache License, and GLPK is an official GNU project released under the GNU General Public License.
