### ISSUE TITLE
dcp analyzer

### ISSUE THREAD

**Issue by ezrawinston** [cvxgrp/cvxpy#636]
I'd like to use the dcp analyzer but the dcp.stanford.edu website appears to be down. Will the site be back up or is there another way to access the source for the analyzer? Thanks!

**Comment by SteveDiamond** [comment]
This is sad news! I'll look into it.

**Comment by guillean** [comment]
Bumping this as well! Was trying to use it for a demonstration, but I get no response.

`(base) guille-mbp:~ guille$ ping dcp.stanford.edu
PING dcp.stanford.edu (172.24.90.102): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
^C
--- dcp.stanford.edu ping statistics ---
5 packets transmitted, 0 packets received, 100.0% packet loss
(base) guille-mbp:~ guille$ `

**Comment by SteveDiamond** [comment]
It should be up now. Try it!

**Comment by guillean** [comment]
Sounds great! Wanted to also bump, just in case :)

**Comment by SteveDiamond** [comment]
I spoke too soon. There's some kind of weird permissions error (example http://dcp.stanford.edu/analyzer?expr=1%2B1). I'm truly baffled about why this is happening. If anyone is familiar with django I'd appreciate help. Basically it's hosted using Apache and mod_wsgi, when you call the analyzer the parse view needs to write to a file. The file is writeable by all users, but somehow it throws an error to open it with write permissions.

**Comment by guillean** [comment]
Perhaps @sredmond can help?

**Comment by sredmond** [comment]
Unfortunately I don't have any Django knowledge to drop here. The situation of a globally-writeable fail failing to be opened for writing is strange - there might be something weird if the file is writeable by all users but not readable (although who sets permissions like that), in which case some hidden library call that might be relying on reading file data could be crashing. Can you include the error that is generated when trying to open the file with write permissions?

**Comment by SteveDiamond** [comment]
Ok I switched to gunicorn and now it works!
