### ISSUE TITLE
PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra

### ISSUE THREAD

**Issue by pranav08** [cvxgrp/cvxpy#644]
We are facing this issue after upgrading our complete dependencies:

/root/.local/share/virtualenvs/build-3vGKWv3F/lib/python3.6/site-packages/cvxpy/cvxcore/python/canonInterface.py:92: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
    return np.asfortranarray(np.matrix(matrix))

Is the issue being considered in the new version of cvxpy?

**Comment by akshayka** [comment]
https://github.com/cvxgrp/cvxpy/pull/638 was just merged, and it addresses this issue.

**Comment by pranav08** [comment]
@akshayka I am using cvxpy version 1.0.15 but still this issue is showing up. My python version is 3.6.7.

**Comment by SteveDiamond** [comment]
Is it exactly the error you posted at the top of the thread? That would be strange because the matrix class is not used in canonInterface.py anymore.

**Comment by pranav08** [comment]
@SteveDiamond Let me do a double check from my end, and get back to you. Thanks
