### ISSUE TITLE
Cannot import cvxpy on Python 3.6

### ISSUE THREAD

**Issue by LijieTu** [cvxgrp/cvxpy#646]
It seems I have problems importing cvxpy. I have tried uninstalling and installing again but no luck.

> Python 3.6.7 |Anaconda custom (64-bit)| (default, Oct 23 2018, 14:01:38) 
> [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cvxpy
> 
> Traceback (most recent call last):
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 18, in swig_import_helper
>     fp, pathname, description = imp.find_module('_cvxcore', [dirname(__file__)])
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/imp.py", line 297, in find_module
>     raise ImportError(_ERR_MSG.format(name), name=name)
> ImportError: No module named '_cvxcore'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/__init__.py", line 18, in <module>
>     from cvxpy.atoms import *
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/atoms/__init__.py", line 18, in <module>
>     from cvxpy.atoms.geo_mean import geo_mean
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/atoms/geo_mean.py", line 20, in <module>
>     from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/utilities/power_tools.py", line 18, in <module>
>     from cvxpy.atoms.affine.reshape import reshape
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/atoms/affine/reshape.py", line 17, in <module>
>     from cvxpy.atoms.affine.affine_atom import AffAtom
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/atoms/affine/affine_atom.py", line 22, in <module>
>     from cvxpy.cvxcore.python import canonInterface
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/cvxcore/python/canonInterface.py", line 17, in <module>
>     import cvxpy.cvxcore.python.cvxcore as cvxcore
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 28, in <module>
>     _cvxcore = swig_import_helper()
>   File "/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/cvxpy/cvxcore/python/cvxcore.py", line 20, in swig_import_helper
>     import _cvxcore
> ImportError: dlopen(/Users/Lijie/courses/python/anaconda/envs/py36/lib/python3.6/site-packages/_cvxcore.cpython-36m-darwin.so, 2): Symbol not found: ___emutls_get_address
>   Referenced from: /Users/Lijie/courses/python/anaconda/envs/py36/lib/libstdc++.6.dylib
>   Expected in: /usr/lib/libSystem.B.dylib
>  in /Users/Lijie/courses/python/anaconda/envs/py36/lib/libstdc++.6.dylib

**Comment by akshayka** [comment]
@LijieTu, were you able to resolve this?

**Comment by LijieTu** [comment]
@akshayka Yes, I reinstalled all py36 packages and it seems that is the only way that works.
