### ISSUE TITLE
How to break out the loop of solving when returns a GUROBI SolverError?

### ISSUE THREAD

**Issue by geeeekDing** [cvxgrp/cvxpy#651]
Dear developers:

I want to solve linear programming using GUROBI in python 3.7(cvxpy 1.0)  in the "for" loop, but when "SolverError"  occurs,  the program **terminates** and cannot continue solving, and I can't obtain the Problem_status. 
"SolverError: Solver 'GUROBI' failed. Try another solver or solve with verbose=True for more information. Try recentering the problem data around 0 and rescaling to reduce the dynamic range."

How to break out the loop to continue the next cycle?

- Another  strange question I found. When I give an infeasible problem and an unbounded problem to test GUROBI solver, something strange happened.
If I use the default solver to solve two problems 

1.  import cvxpy as cvx
2.  x = cvx.Variable()
3.  
4. prob = cvx.Problem(cvx.Minimize(x), [x >= 1, x <= 0])
5.  prob.solve()
6. print("status:", prob.status)
7.  print("optimal value", prob.value)
8. 
9.  prob = cvx.Problem(cvx.Minimize(x))
10. prob.solve()
11. print("status:", prob.status)
12.  print("optimal value", prob.value)

It returns 
status: infeasible
optimal value inf
status: unbounded
optimal value -inf

- when I change the GUROBI solver for two problems, it returns "SolverError: Solver 'GUROBI' failed. Try another solver or solve with verbose=True for more information. Try recentering the problem data around 0 and rescaling to reduce the dynamic range."
when I change the GUROBI solver for the first problem, all going well. such that 
1. import cvxpy as cvx
2. x = cvx.Variable()
3. prob = cvx.Problem(cvx.Minimize(x), [x >= 1, x <= 0])
4. prob.solve()
5. print("status:", prob.status)
6. print("optimal value", prob.value)
7. 
8. prob = cvx.Problem(cvx.Minimize(x))
9. prob.solve(solver=cvx.GUROBI)
10. print("status:", prob.status)
11. print("optimal value", prob.value)

It returns 

status: infeasible
optimal value inf
status: unbounded
optimal value -inf

- when I only change the GUROBI solver for the second problem, it also returns "SolverError: Solver 'GUROBI' failed. Try another solver or solve with verbose=True for more information. Try recentering the problem data around 0 and rescaling to reduce the dynamic range."

**Comment by SteveDiamond** [comment]
As it says, try using a different solver or improving the numerical properties of your data.

**Comment by rileyjmurray** [comment]
I think @geeeekDing was asking how to programmatically handle solver errors. For this purpose, use a try-catch, i.e.
```
for i in range(num_probs):
    prob = generate_your_problem(i)
    try:
        prob.solve(solver='GUROBI')
        # handle success
    except cvxpy.SolverError:
        # handle failure
```

**Comment by geeeekDing** [comment]
> As it says, try using a different solver or improving the numerical properties of your data.

Sorry, dear developers,  perhaps I didn't describe the problem clearly.  As I tested, I found that the GUROBI solver may return "SolverError“  rather than "infeasible" status when it solves an infeasible problem. 

> I think @geeeekDing was asking how to programmatically handle solver errors. For this purpose, use a try-catch, i.e.
> 
> ```
> for i in range(num_probs):
>     prob = generate_your_problem(i)
>     try:
>         prob.solve(solver='GUROBI')
>         # handle success
>     except cvxpy.SolverError:
>         # handle failure
> ```

Thanks a lot @rileyjmurray !! I will try your suggestions

**Comment by SteveDiamond** [comment]
The solvers behave differently because they are different.
