### ISSUE TITLE
When does cvxpy perform dcp anaylsis?

### ISSUE THREAD

**Issue by suraj2596** [cvxgrp/cvxpy#652]
Does it happen at the end of executing this line : `Problem(objective, constraints)` in code? 
Or does it start with performing the analysis when `prob.solve` is called?

**Comment by SteveDiamond** [comment]
Yes.

**Comment by suraj2596** [comment]
Thank you @SteveDiamond. But wouldn't it be an undesired overhead when one wants to optimize continuously in a loop? Especially in a scenario where the problem definition would remain the same and only parameters would be varying.

Or is there a way to bypass the dcp analysis? I understand the risks but time is an expensive factor in my case.

**Comment by SteveDiamond** [comment]
cvxpy is not currently optimized for solving the same problem many times, even with parameters. There are many improvements that can be made for this case, which I hope to make.

**Comment by suraj2596** [comment]
I see. And it would be a helpful feature, especially for path-planning problems where looping is inevitable. Thank you.

**Comment by suraj2596** [comment]
Posting a related issue, just for future reference: #409
