### ISSUE TITLE
Python RuntimeWarning: overflow encountered in long_scalars   if self.max_big_small_squared < big*small**2:

### ISSUE THREAD

**Issue by MiliKovja** [cvxgrp/cvxpy#654]
Hi guys!

I am trying to solve a pretty large optimization problem using Python 3.6.5, CVXPY 1.0  and the solver is MOSEK. I'm running it on Windows 7. When I run the code I get this warning:

C:\Users\User\Anaconda3\lib\site-packages\cvxpy\problems\problem.py:614: RuntimeWarning: overflow encountered in long_scalars   if self.max_big_small_squared < big*small**2:
C:\Users\User\Anaconda3\lib\site-packages\cvxpy\problems\problem.py:615: RuntimeWarning: overflow encountered in long_scalars  self.max_big_small_squared = big*small**2

Does anyone know where could be the problem? If any other information on my code are needed, let me know.

**Comment by akshayka** [comment]
Please move this question to [StackOverflow](https://stackoverflow.com/questions/tagged/cvxpy), and tag it with the CVXPY tag. Also, make sure to include a complete code example that reproduces this behavior.

**Comment by wkschwartz** [comment]
I've run into this. `big_small` is a NumPy `int32` (or maybe it's a NumPy `int` and I was on a 32 bit platform, I forget), and `big_small**2` is larger than 2^31. The fix is to ensure that `big_small` is either a Python `int` or at least a NumPy `int64`.
