### ISSUE TITLE
Some confusing results

### ISSUE THREAD

**Issue by Reesing** [cvxgrp/cvxpy#657]
I did a quite simple quadratic optimization with cvxpy and run into some confusing problems.

### PROBLEM 1

`score` is a 1400 * 1 numpy array fiiled with all positive floats.
I run the following codes:

```
# Different N affects the result.
import numpy as np
import cvxpy as cp
w = cp.Variable(N,1))
objective = cp.Maximize(score[:N].T*w)
constraints = [w>=0,sum(w)==1]
prob = cp.Problem(objective,constraints)
prob.solve()
```
    

When `N` is a relative small integer like 300, w.value is vector `[0,...,1,...,0]` where 1 is in the position of the max number of  `score[:N]`. Apparently, this is what I expeted.
    However if `N` is greater than about 500, `w.value` is vector of `[1/N,1/N,...,1/N]`. I was totally confused by the result.

 **Why did the dimension of parameters affect the optimization?**

### PROBLEM 2

We still use parameters from PROBLEM 1.
Additionally, `cov_mat` is a 10 * 10 numpy matrix. It is a symmetric matrix with no nan values.
`fac` is 1400 * 10 numpy matrix.
Define:

```
sigma = fac.dot(cov_mat).dot(fac.T)
risk = cp.quad_form(w,sigma)
```
   

 The interpreter told me that risk is `Expression(UNKNOWN, UNKNOWN, (1, 1))`, rather than `Expression(CONVEX, UNKNOWN, (1, 1))` which I expected. As a result, the following codes gave a warning `*** cvxpy.error.DCPError: Problem does not follow DCP rules`.

```
N = len(score)
import numpy as np
import cvxpy as cp
w = cp.Variable(N,1))
sigma = fac.dot(cov_mat).dot(fac.T)
risk = cp.quad_form(w,sigma)
objective = cp.Maximize(score[:N].T*w-risk)
constraints = [w>=0,sum(w)==1]
prob = cp.Problem(objective,constraints)
prob.solve()
```

**How is `quad_form(w,sigma)` a not-convec expression? Is there any bugs in my code?**

### PROBLEM 3
We still use parameters from PROBLEM 2.
I tried to replace
`risk = cp.quad_form(w,sigma)`
    with
`risk = cp.quad_form(w,cp.Parameter(value=sigma,PSD=True,shape=sigma.shape))`
    in the code block from PROBLEM 2. Finally, the problem was solved with `prob.status = 'optimal'`.
    However, w.value contained about 700 negative numbers while I specifically required `w>=0` in the constraints.
    **How is this possible that optimal results defy my constaints?**

**Comment by akshayka** [comment]
@Reesing , since this question is about how to properly use CVXPY, can you move this question to [StackOverflow](https://stackoverflow.com/questions/tagged/cvxpy) and label it with the cvxpy tag? You're likely to get a quicker response if you post it there.

**Comment by rileyjmurray** [comment]
@akshayka the first of the three issues from OP is a matter of correctness, and should probably be investigated.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
