### ISSUE TITLE
is_dcp for cvx.log(x)

### ISSUE THREAD

**Issue by miggy2129** [cvxgrp/cvxpy#662]
**Describe the bug**
I'm working with the sample code:

```
x = cvx.Variable()
param = cvx.Parameter()
expr = param*cvx.log(x)
print(expr.is_dcp())

```

I believe this should return a true because CVXPY ought to treat the parameter as a constant. I'm currently receiving 'False' while operating on this. 

I believe that parameters ought to be treated as constants by CVXPY. I tested the following script

```
x = cvx.Variable()
expr = 2*cvx.log(x)
expr2 = -2*cvx.log(x)
print(expr.is_dcp(), expr2.is_dcp())
```

and it returns 'True' for both cases. Is the former code snippet a bug or did I have a misinterpretation of the definition of parameter?

I'm currently working on Python3 on a Mac OS X Sierra.

**Comment by SteveDiamond** [comment]
You need to make the parameter positive or negative, eg, ``Param(nonneg=True)`` or ``Param(nonpos=True)``. It's not DCP without a sign, since the curvature is unknown.
