### ISSUE TITLE
geometric programming ValueError

### ISSUE THREAD

**Issue by stephanietsuei** [cvxgrp/cvxpy#668]
Hi,

I get the message: `ValueError: Cannot reduce problem to symbolic QP` when running [the example in the geometric programming](https://www.cvxpy.org/tutorial/dgp/index.html?highlight=geometric%20programming) tutorial. The full trace is below:
```
Traceback (most recent call last):
  File "testgp.py", line 12, in <module>
    problem.solve(gp=True)
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/problems/problem.py", line 268, in solve
    return solve_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/problems/problem.py", line 381, in _solve
    data, inverse_data = self._solving_chain.apply(self)
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/reductions/chain.py", line 65, in apply
    problem, inv = r.apply(problem)
  File "/usr/local/lib/python3.5/dist-packages/cvxpy/reductions/qp2quad_form/qp2symbolic_qp.py", line 59, in apply
    raise ValueError("Cannot reduce problem to symbolic QP")
ValueError: Cannot reduce problem to symbolic QP
```

I am using Ubuntu 16.04, Python 3.5.2, and cvxpy 1.0.14. I installed cvxpy using pip. I also tried downgrading to cvxpy 1.0.13 and 1.0.11 and the same error happened.

Please let me know if you need any more information. 

Thanks!

**Comment by akshayka** [comment]
@stephanietsuei Thanks for reporting this; I'll look into it.

**Comment by akshayka** [comment]
I was able to reproduce this bug at 1.0.14 by installing Gurobi (@stephanietsuei, do you have Gurobi installed?). 

I think this problem has been solved at master. @SteveDiamond , can you publish a new release soon?

**Comment by akshayka** [comment]
@stephanietsuei : in the meantime, you can get around this bug by solving problems with SCS.

For example:

```
import cvxpy as cp

# form your DGP problem ...
problem.solve(gp=True, solver=cp.SCS)
```

**Comment by stephanietsuei** [comment]
Yes, I do have Gurobi installed. Using SCS did the trick. Thanks!
