### ISSUE TITLE
Sparse expression to involve SSE (sum square error) in objective function

### ISSUE THREAD

**Issue by chen371502** [cvxgrp/cvxpy#670]
I'm now working on a problem with the SSE of linear regression in the objective function. To describe it briefly, I want to include the convex term  y.T * (I - X * ((X.T * X)**(-1)) * X.T) * y in the objective function，where X is a matrix of shape (n, 2), I is an identity matrix of shape (n, n), y is a vector of shape (n, ), and it is the variable to be optimized.
the code below gives a simple example with n=4:
```
import numpy as np
import cvxpy as cvx
X = np.array([[1,2],[2,3],[3,2.5],[4,4]])
y = cvx.Variable((4,))
I = np.identity(4)
```
Then I can write the second order term of SSE of linear regression
```
sse_term = cvx.quad_form(y,I-np.dot(X,np.dot(np.linalg.inv(np.dot(X.T,X)),X.T)))
sse_term.is_convex()
```
the output is True, cvxpy can identify this term is convex, however, the real problem I'm working on is with much more data compared with this sample problem, if I use solvers like ECOS, the expression above cannot harness the sparsity expression of matrix, and the solving time is intolerable, so I try to express sse_term in a sparsity form
```
sse_term = cvx.quad_form(y,I)-cvx.quad_form(X.T*y,np.linalg.inv(np.dot(X.T,X)))
sse_term.is_convex()
```
the output is False, this term can no longer be identified as a convex function.
The question is that if there is a way in cvxpy to write this SSE term using sparse expression, thus to speed up the calculation when using solvers like ECOS and SCS?

**Comment by SteveDiamond** [comment]
What's wrong with ``sum_squares``?

**Comment by chen371502** [comment]
I represented the sse term using sum_squares in the simplified 4 variable example:
```
import numpy as np
import cvxpy as cvx
X = np.array([[1,2],[2,3],[3,2.5],[4,4]])
y = cvx.Variable((4,))
I = np.identity(4)

sse_term = cvx.sum_squares(y-np.dot(X,np.linalg.inv(np.dot(X.T,X)))*(X.T*y))
```
sse_term can be identified convex, however the calculation using ECOS is still slow, it seems that  ECOS doesn't harness the sparse representation when I use sum_squares under this circumstance. It takes about 140 seconds to solve my problem (with 1200 variables). But when I use structured matrix input in other problems (such as structured asset covariance in mean-variance problem), ECOS usually gives the solution within 1 second.

btw, the cvxpy version is 1.0.8, and ecos version is 2.0.4

**Comment by SteveDiamond** [comment]
I see. Add a variable ``z = X.T*y``

**Comment by chen371502** [comment]
I tried `z = X.T*y`, the simplified 4-variable example is as follows:
```
import numpy as np
import cvxpy as cvx
X = np.array([[1,2],[2,3],[3,2.5],[4,4]])
y = cvx.Variable((4,))
I = np.identity(4)

z = X.T*y
sse_term = cvx.sum_squares(y-np.dot(X,np.linalg.inv(np.dot(X.T,X)))*z)
```
however, this revise seems can not help to improve calculation efficiency using ECOS.
In my problem, X is a matrix of shape (1200,38), y is a vector of shape (1200,), the calculation time is still above 140 seconds.

**Comment by SteveDiamond** [comment]
I meant declare a variable z (``z = Variable(n)`` and add the constraint ``z == X.T*y``. Literally writing ``z = X.T*y`` is the same as before.

**Comment by chen371502** [comment]
That works for me. after declaring variable z, problem can be solved within 1 second. Thanks very much.
