### ISSUE TITLE
'QuadForm' object has no attribute 'P' with cvxpy 1.0.15

### ISSUE THREAD

**Issue by skoudoro** [cvxgrp/cvxpy#672]
Hi Cvxpy devs!

**Describe the bug**

Since the last release (1.0.15), our project (DIPY) is failing due to the following error : 
`'QuadForm' object has no attribute 'P'`.  How can I solve this problem?

Thank you for your feedback!

**To Reproduce**

```
import cvxpy
import numpy as np

data_norm = np.random.random(203)
M = np.random.random(203*50).reshape((203, 50))
c = cvxpy.Variable(M.shape[1])
lopt = 0
laplacian_matrix = np.ones((50, 50))

design_matrix = cvxpy.Constant(M)
objective = cvxpy.Minimize(
    cvxpy.sum_squares(design_matrix * c - data_norm) +
    lopt * cvxpy.quad_form(c, laplacian_matrix)
)
constraints = [(M[0] * c) == 1] # (K * c) >= -0.1]
prob = cvxpy.Problem(objective, constraints)
prob.solve()
```

**Version**
 - OS: Tested on Linux ,windows, mac
 - CVXPY Version: 1.0.15

**Comment by SteveDiamond** [comment]
It appears to work if ``lopt`` is not zero. A strange bug.

**Comment by skoudoro** [comment]
Indeed, really strange... 

But Thanks for this information, a workaround is easy to implement until your fix and the new cvxpy release.

**Comment by SteveDiamond** [comment]
This is fixed in master.

**Comment by skoudoro** [comment]
Thank you @SteveDiamond!

By curiosity, which PR fixed it and what was the problem?

**Comment by SteveDiamond** [comment]
I fixed it directly in master. Basically if an expression was known to be zero, it was treated as constant. This is reasonable, but interacted badly with other aspects of the code base.

**Comment by skoudoro** [comment]
ok, great! Thank you for this information and the fast fix!
