### ISSUE TITLE
Gurobi interface (still) incorrectly returns SolverError for infeasible model

### ISSUE THREAD

**Issue by dmalyuta** [cvxgrp/cvxpy#673]
SolverError continues to get returned when using Gurobi on some infeasible problems, despite #521 being solved. Consider the following minimal code, based on #512:
```
import numpy as np
import numpy.random as nprand
import cvxpy as cvx

z = cvx.Variable(integer=True)

nprand.seed(0)

Q = nprand.randn(2,2) # np.array([[ 1.01092346, -1.246334  ], [-1.246334  , 11.24925237]])
q = np.array([-0.79305302, -0.67245977])
C = np.array([[ 1.74951088, -0.86604018],
       [ 1.83903552,  0.28968686],
       [ 1.85200233,  1.34964664],
       [-0.62858037,  0.15304167]])
c = np.array([ 0.58550308,  0.96431765,  0.40713688, -0.79539809])
w = np.array([ 1.71458648, -1.54797607])

x = cvx.Variable(2)
# obj = cvx.quad_form(x, Q.T @ Q) / 2 + q.T*x + cvx.norm(x-z,2)**2 / 20
obj = cvx.norm(Q*x,2)**2 / 2 + q.T*x + cvx.norm(x-w,2)**2 / 20
constr = [C*x <= z, z>=1, z<=-1]
prob = cvx.Problem(cvx.Minimize(obj), constr)

prob.solve(solver=cvx.GUROBI, verbose=True)
```
which returns `SolverError` (the problem is infeasible due to the two constraints `z>=1, z<=-1`). The issue is on [L270](https://github.com/cvxgrp/cvxpy/blob/cd0302266e50010cd598ad718e0477f114bbb971/cvxpy/problems/solvers/gurobi_intf.py#L270) because `model.ObjVal` does not exist, so an exception gets triggered. However, `model.status=4` so actually the correct `results_dict["status"]` value should be `INFEASIBLE_INACCURATE`.

I suggest a fix by changing (L291)[https://github.com/cvxgrp/cvxpy/blob/cd0302266e50010cd598ad718e0477f114bbb971/cvxpy/problems/solvers/gurobi_intf.py#L291] to the same as (L288)[https://github.com/cvxgrp/cvxpy/blob/cd0302266e50010cd598ad718e0477f114bbb971/cvxpy/problems/solvers/gurobi_intf.py#L288]:
```
results_dict["status"] = self.STATUS_MAP.get(model.Status, s.SOLVER_ERROR)
```
or better yet, to avoid that line being written twice:
![image](https://user-images.githubusercontent.com/12475811/52806640-627d5f80-303e-11e9-8ae9-fa5a53054055.png)

**Version**
 - OS: Ubuntu 18.04 x86_64
 - CVXPY Version: 1.0.14
- Gurobi Version: 8.1.0 build v8.1.0rc1 (linux64)

**Comment by SteveDiamond** [comment]
I made your suggested change. Could you try master? I don't have gurobi installed right now.

**Comment by dmalyuta** [comment]
Hmm, I'm not sure how to install cvxpy from just the source code here (I used pip for 1.0.14). But it works for me making the above change to 1.0.14.

**Comment by SteveDiamond** [comment]
Ok, good enough.
