### ISSUE TITLE
PSD constraint for non-symetric matricies

### ISSUE THREAD

**Issue by johnldean** [cvxgrp/cvxpy#674]
**Describe the bug**
PSD constraints for non-symmetric matrices appear to not function properly. For the cvxpy `>>` operator, the documentation states

>The second way is to create a positive semidefinite cone constraint using the >> or << operator. If X and Y are n by n variables, the constraint X >> Y means that zT(X−Y)z≥0, for all z∈Rn. In other words, X+XT is positive semidefinite. The constraint does not require that X and Y be symmetric. Both sides of a postive semidefinite cone constraint must be square matrices and affine.

However, in the example below, adding a `>>` constraint to a non-symmetric matrix appears to have no effect.

I have tried this with SCS and CVXOPT, and both produce the same bug, so it does not appear to be a solver issue.

Side note: I think the documentation also not quite right. I think it should state: "in otherwords, (X-Y) + (X-Y)^T is positive semidefinite"

**To Reproduce**

Note here that the min with 10 in the objective is simply to keep the problem from being unbounded, since the `>>` constraint is not functioning properly.
```
import numpy as np
import cvxpy as cp

s = cp.Variable((2, 2))
obj= cp.Maximize(cp.minimum(s[0,1],10))

const = [s>>0,cp.diag(s)==np.ones(2)]

prob = cp.Problem(obj, const)
r = prob.solve()
s = s.value
s = (s+s.T)/2
print("value", r)
print("s", s)
print("eigs",np.linalg.eig(s)[0])
```

**Expected behavior**
The resulting matrix should be PSD to within numerical precision. To get the expected output, I add `PSD=True` when declaring `s`. However, this should not be required.
```
value 1.0000137273806762
s [[1.00000233 1.00001495]
 [1.00001495 1.00000233]]
eigs [ 2.00001728e+00 -1.26168319e-05]
[Finished in 0.5s]
```

**Output**

```
value 9.999999999973621
s [[1.         5.02056715]
 [5.02056715 1.        ]]
eigs [ 6.02056715 -4.02056715]
[Finished in 0.4s]
```

**Version**
 - OS: Ubuntu 18.04.1
 - CVXPY Version: 1.0.15

**Comment by SteveDiamond** [comment]
This is fixed on master.
