### ISSUE TITLE
Impossible to fix certain values in matrix variables

### ISSUE THREAD

**Issue by cyrilgarcia009** [cvxgrp/cvxpy#675]
<img width="830" alt="screenshot 2019-02-25 at 23 16 44" src="https://user-images.githubusercontent.com/20226693/53387471-1642f100-3955-11e9-9642-b00d92374434.png">
I looked at different websites and requests but I couldn't find how to code such a constraint where some elements of the matrix are kept constant (see photo attached). Thank you for your help!

**Comment by akshayka** [comment]
```
import cvxpy as cp

X = cp.Variable((3, 3), PSD=True)
x = cp.Variable()
constraints = [cp.diag(X) == [1, 1, 1], X[1, 2] == 0.5, x >= 0, x <= 1]
problem = cp.Problem(cp.Minimize(1.0), constraints)
problem.solve(solver=cp.SCS)
print(X.value)
print(x.value)
```

prints

```
array([[1. , 0. , 0. ],
       [0. , 1. , 0.5],
       [0. , 0.5, 1. ]])
array(0.49988009)
```

i.e., x1 and x2 are found to be 0 and x3 is 0.5.

The tutorial has more information on PSD constraints: https://www.cvxpy.org/tutorial/advanced/index.html#semidefinite-matrices.
