### ISSUE TITLE
Boolean/Integer memory usage

### ISSUE THREAD

**Issue by Priwinn** [cvxgrp/cvxpy#684]
**Describe the bug**
I am trying to solve quite a big problem of integer programming (with 80000x80000 boolean variables). I am not exactly sure about the limits of cvxpy but my problem here is that I can't even create 5000x5000 boolean variable because it uses up too much memory. I think it is because it stores all indices for which the variable is boolean instead of just saying that all variables are boolean.

**To Reproduce**
Simply create a big integer or boolean variable say:

x=cvxpy.Variable((50000,50000),boolean=True)

In my case 5000x5000 is enough to cause MemoryError

**Output**
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2018.3.5\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2018.3.5\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/ruizh/OneDrive/hashcode/Online/exactb.py", line 11, in <module>
    x = cp.Variable(shape=(size, size),integer=True)
  File "C:\Users\ruizh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cvxpy\expressions\variable.py", line 78, in __init__
    super(Variable, self).__init__(shape, **kwargs)
  File "C:\Users\ruizh\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cvxpy\expressions\leaf.py", line 121, in __init__
    np.ndindex(max(shape, (1,))))
MemoryError

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.0

**Comment by SteveDiamond** [comment]
You're right about the source of the issue. An index is stored for each boolean entry. But I'm honestly not sure cvxpy is a good fit for solving such large boolean problems.

**Comment by Priwinn** [comment]
Ok, I absolutely misread some benchmarks abouth the biggest integer programming problems solved and I thought cvxpy could totally solve it. I guess solving a problem with 6400 million variables is too much for anyone. Thank you for your fast response.

**Comment by rileyjmurray** [comment]
Just to follow-up: globally solving an unstructured boolean optimization problem with even 100,000 variables is essentially impossible. You can find local solutions just fine, but proving optimality is out of the question (unless your problem has very special structure).

**Comment by Priwinn** [comment]
That is good to know since I only have knowledge about the theoretical aspects. I figured the number couldn't get infinitely high but I was not sure of the approximate limit.
