### ISSUE TITLE
Incoherency in "Sparse covariance estimation for Gaussian variables" example

### ISSUE THREAD

**Issue by bertrandhaut** [cvxgrp/cvxpy#685]
According to the example Sparse covariance estimation for Gaussian variables (https://www.cvxpy.org/examples/applications/sparse_covariance_est.html) the problem of estimating R is to solve a minimization problem.

 But the code below solve a maximization problem.

If one takes back the original reference "Section 7.1.1, Boyd & Vandenberghe “Convex Optimization”, the associated equation (7.4) is stating that it is a maximization issue. 

The text description should be updated " minimize --> maximize"

**Comment by SteveDiamond** [comment]
Thanks for pointing this out! @akshayka could you fix this? I don't know how to generate the html files for the notebooks.
