### ISSUE TITLE
CVXPY fails for large, sparse quadratic programs

### ISSUE THREAD

**Issue by moehle** [cvxgrp/cvxpy#689]
For a large, sparse quadratic programs CVXPY performs a (dense, full) eigenvalue decomposition, which is obviously prohibitively expensive.  These problems can presumably be handled by OSQP, and in theory, could be handled by CVXPY as well.  Previously, "ignore_dcp" could be used to turn off this check, but this is no longer an option, as per #534.  

It is possible (using scipy.linalg.eigsh) to compute the smallest eigenvalue of a sparse symmetric matrix, without conversion to a dense array.  Maybe this should be used?

This has come up independently in a few different applications I'm working on, so I suspect it could be a common issue for large problems.   

import cvxpy
import scipy.sparse as sprs

x = cvxpy.Variable(1000000)
prob = cvxpy.Problem(cvxpy.Minimize(cvxpy.sum_squares(x)))
prob.solve()

**Comment by SteveDiamond** [comment]
One option would be to use the new ``psd_wrap`` in ``cvxpy.atoms.affine.wraps``. You write ``psd_wrap(expr)`` and it asserts that the expression is PSD without checking. We added this for a different issue recently.
