### ISSUE TITLE
Trying to run cvxpy on cluster of centos6 machines getting some errors

### ISSUE THREAD

**Issue by rjgithub1** [cvxgrp/cvxpy#690]
**Describe the bug**
Getting 2 errors trying to run cvxpy on cluster of centos6 machines.  I know these questions aren't that hard, but I don't have access to fix this stuff, I have to tell the sysadmin what I want so I don't want to tell him to try stuff that won't work.

**1. no module named _cvxcore**
    -saw some stuff related to this that said you need numpy 1.13 or higher, doesn't seem to be an issue 
       since we have numpy 1.15.4

**2. glib version 2.14 not found**
    -I know what's going on here, we can't upgrade it b/c some other stuff needs 2.12 which we are 
        running.  What I would like to know is if we can just change the depedency to 2.12 or will that mess
        stuff up.  If not I could probably get access to a different cluster that has 2.17 running but this  
       would require navigating  a bit of red tape that I would prefer to avoid.

<img width="936" alt="Screen Shot 2019-02-18 at 3 21 05 PM" src="https://user-images.githubusercontent.com/18296759/54327970-69f64100-45c9-11e9-90eb-33e0ef61229a.png">

**Version**
 - OS: centos6
 - CVXPY Version: 1.06

**Comment by SteveDiamond** [comment]
The no ``_cvxcore`` error has been happening with Anaconda installs. Because of it, we've switched to recommending installation with pip.

**Comment by rjgithub1** [comment]
Thanks Steve, any tips on the glib issue?  Can it be manually  changed or is it the case the glib version is tied with the cvxpy version?

**Comment by SteveDiamond** [comment]
You can try changing it.
