### ISSUE TITLE
Unplausible setup_time/solve_time return values in solver_stats for ECOS_BB

### ISSUE THREAD

**Issue by lumbric** [cvxgrp/cvxpy#691]
**Describe the bug**
`solver_stats.setup_time` and `solver_stats.solve_time` report 3-10ms and `solver.num_iters = 8`, but the duration of `Problem.solve()` is ~39 seconds.

If this is just a misunderstanding from my side, I'd be happy to contribute to the documentation with a pull request.

**To Reproduce**

This example runs in ~39 seconds on my computer, but `solver_stats` contain much lower values:

```Python
import time
import numpy as np
import cvxpy as cp
from  scipy.spatial.distance import pdist
from  scipy.spatial.distance import squareform

N = 100

locations = np.random.random((N, 2))
value = np.random.random(N)

pairwise_distances = squareform(pdist(locations))

x = cp.Variable(N, boolean=True)

constraints = [(x.T + x - 1) * pairwise_distances <= 0.5]

obj = cp.Maximize(value @ x)

problem = cp.Problem(obj, constraints)

t0 =  time.time()
problem.solve()
duration = time.time() - t0

print("solver_name:", problem.solver_stats.solver_name)
print("solve_time:", problem.solver_stats.solve_time)
print("setup_time:", problem.solver_stats.setup_time)
print("num_iters:", problem.solver_stats.num_iters)
print("duration:", duration)
```

This prints:
```
solver_name: ECOS_BB
solve_time: 0.008032949
setup_time: 0.002911595
num_iters: 8
duration: 39.710853815078735
```

I haven't managed to find a smaller example. This chooses 100 random locations on a 2D-plane, assigns a random value to each and tries to choose locations with maximum total value such that the distance between two chosen locations is less than 0.5. Note that this is *not* efficient. N^2 constraints are created here, but not needed in general.

**Expected behavior**
I'd expect that I could estimate the overall run time using `solve_time`, `setup_time` (and maybe `num_iters`). Ideally it should be clear from the documentation if I have to expect additional overhead and if the time is given per iteration or in total.

**Version**
 - OS: Ubuntu 18.10 (Cosmic Cuttlefish)
 - CVXPY Version: 1.0.21

**Comment by SteveDiamond** [comment]
ECOS BB doesn't seem to return any useful timing information. I removed the solve_time and setup_time fields for the ECOS BB solver.
