### ISSUE TITLE
Broadcasting error

### ISSUE THREAD

**Issue by mjag1898** [cvxgrp/cvxpy#700]
I am encountering the following error for a very simple broadcast. Python 3.6.8, cvx 1.0.21, numpy 1.15.4.

I have seen #588 and #587 but don't have a conda installation and haven't been able to find a fix here.

Transposing X also gives an error as it should, while matrix multiplication works.

```
import numpy as np
import cvxpy as cvx

X = np.random.uniform(size=(10, 2))
x = cvx.Variable(2)

diff = X - x
```
```
File "/Users/milindjagota/Library/Python/3.6/lib/python/site-packages/cvxpy/utilities/shape.py", line 49, in sum_shapes
    len(shapes)*" %s" % tuple(shapes))
ValueError: Cannot broadcast dimensions  (10, 2) (2,)
```

**Comment by mjag1898** [comment]
Giving x the shape (1,2) also does not work.

**Comment by SteveDiamond** [comment]
You are not allowed to do broadcasting like this in cvxpy.
