### ISSUE TITLE
Documentation of "Advanced Features" is partly out of date.

### ISSUE THREAD

**Issue by JoergVanAken** [cvxgrp/cvxpy#702]
**Describe the bug**
Solving the problem described in https://gist.github.com/freddyalfonsoboulton/b3d7a17b913e928a349e04acb6b0a740
is no problem. 

**To Reproduce**
Getting the standard form does not work with:

`rawdata = problem.get_problem_data(cvxpy.GLPK_MI)`

But `rawdata` is still an internal representation. Two further steps a necessary:

`glpk = GLPK_MI();
data = glpk.get_problem_data(rawdata['objective'], rawdata['constraints'], {glpk.name(): ProblemData()})`

One step later unpacking the solution isn't possible with

`prob.unpack_results(cvx.GLPK_MI, solver_output)`

**Expected behavior**
Things should work as described in the documentation.

**Version**
 - OS: Windows
 - CVXPY Version: 1.0.21

**Comment by akshayka** [comment]
Thanks for reporting this. The documentation is indeed out-of-date compared to the current semantics of `get_problem_data` (the [docstring](https://www.cvxpy.org/api_reference/cvxpy.problems.html#cvxpy.problems.problem.Problem.get_problem_data) is accurate). I'll look into fixing this.

**Comment by akshayka** [comment]
I've updated the docs (the website should be updated within a couple days). The semantics of `get_problem_data` were changed in 1.0, and they're not ideal. We're currently working on a major update to CVXPY. We'll try to better semantics for `get_problem_data` in this update; perhaps we'll just match the pre 1.0 behavior.

**Comment by JoergVanAken** [comment]
Thanks for updating the documentation and I am looking forward to the new version :-)
