### ISSUE TITLE
Provide an API to retrieve the solution path and historical objective function values

### ISSUE THREAD

**Issue by Rothdyt** [cvxgrp/cvxpy#712]
**Is your feature request related to a problem? Please describe.**

For research purpose, it would be nice to be able to plot the objective function value against each iteration.  Currently, if you use `problem.solve(Verbose = True)` the historical primal-dual objective function values are printed out on the screen. It would be nice to store them into a `np.arrary`.

**Describe the solution you'd like**

I would image something like

```python
results = problem.solve(keep_solution_path = True, keep_historical_function_value= True)
solution_path = results.sol_path
function_vals = results.fvals
```

**Comment by akshayka** [comment]
That’s an interesting idea, but I don’t think it’d be feasible to implement. CVXPY wraps numerical solvers, which are separate Python packages; it’s not a solver itself (the verbose output is printed by solvers, not CVXPY). Most solvers (as far as I know) don’t have APIs for returning per-iteration residuals.
