### ISSUE TITLE
Question/Feature request about Linear Programs in Normal Form

### ISSUE THREAD

**Issue by jparsert** [cvxgrp/cvxpy#714]
I know cvxpy prides itself with only having the need for intuitive constraints etc. However, I would like to have the ability to simply give a matrix A and vectors b and c such that I get an assignment of variables x  such that A*x <= b and c*x is maximized.  That Is i would like to give a linear program in standard form and get a solution.

I guess this is possible but I am not sure how

**Comment by angeris** [comment]
Heya, have you looked at the [cvxpy main page](https://www.cvxpy.org)? It has an example that could help answer your question. You can replace the constraints
```python
constraints = [0 <= x, x <= 1]
```
with the one you want,
```python
constraints = [A @ x <= b]
```
and similarly for the objective
```python
objective = cp.Minimize(cp.sum_squares(A*x - b))
```
versus
```python
objective = cp.Maximize(c.T @ x)
```

Similarly, looking at the [cvxpy tutorial](https://www.cvxpy.org/tutorial/intro/index.html) might help, too :)

**Comment by jparsert** [comment]
Thank you very much. I would have been surprised if this wasn't possible. Nevertheless, the reason I wrote this question here is that I was not aware of the possibility of using "@".

**Comment by angeris** [comment]
@jparsert No worries! Yes, it is also okay to use `*` (as in the example objective), but `@` is often considered more pythonic (and has less issues with sometimes being elementwise multiplication, etc).

**Comment by jparsert** [comment]
@angeris I have another question. Is there a way of transforming an arbitrary linear program to a linear program in matrix form I.E a triple (A, b, c)?

**Comment by angeris** [comment]
Yes, but this conversion is outside of the scope of CVXPY (also, you can just input the linear program directly into CVXPY without converting it to standard form, this is the goal of CVXPY :).

If you do need to convert general LPs to standard form, [MIT OCW has a good course](https://ocw.mit.edu/courses/sloan-school-of-management/15-053-optimization-methods-in-management-science-spring-2013/tutorials/MIT15_053S13_tut06.pdf) on it (complete with... cartoon characters? Not so sure about that part...)

**Comment by jparsert** [comment]
I guess I should have formulated my question better: I am aware that it can be done. I was wondering if cvxpy offers this functionality (as I am lazy and do not want to implement it myself). The second question would be if cvxpy does not offer it, do you know of a program that does?

**Comment by akshayka** [comment]
CVXPY offers this for cone programs and QPs, via the get_problem_data() function (see the documentation on our website). It should be easy to convert the cone data to LP data. For the future, usage questions like the ones in this thread are better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/cvxpy).
