### ISSUE TITLE
ECOS solver returns unsual results when used to train a soft-margin SVM

### ISSUE THREAD

**Issue by prabathabey** [cvxgrp/cvxpy#718]
CVXPY version: v1.0

Just thought of seeking some feedback on a bit of an unusual observation that I encountered while training a soft-margin SVM using the ECOS solver via Cvxpy framework. The implementation of the aforementioned soft-margin SVM goes below. The dataset I've used is a real-world dataset slightly modified to be able to train a binary SVM on it. 

```
n = 50
C = Parameter(sign="positive")
C.value = 0.75
beta = cp.Variable(n, name="x")  # x in our terminology
v = cp.Variable(name="v")  # b in our terminology
Epsilon = cp.Variable(len(X_train), 1, name="Epsilon")  # punishing factor

objective = Minimize(sum_entries(square(beta)) + C * norm(Epsilon, 1))
g = C * cp.norm(Epsilon, 1)
for i in range(n):
  g = g + 0.5 * cp.square(beta[i])

constraints = [Epsilon >= 0]
for j in range(len(X_train)):
   constraints = constraints + [y_train[j] * (cp.sum_entries(cp.mul_elemwise(np.asmatrix(X_train[j]).T, beta)) + v) >= 1 - Epsilon[j]]
prob = Problem(Minimize(50*g), constraints)
try:
	prob.solve(solver=ECOS)
except SolverError as e:
	print(e)
```

I understand that different solvers use different ways of solving a given problem thereby returning different results. However, the results returned by the aforementioned implementation ranges around 98% for the given dataset, which is unusually high compared to the results returned by other implementations such as libsvm, etc, which were about 50%. Therefore, wondering if I might be missing something obvious. 

Appreciate any input on this.

**Comment by rileyjmurray** [comment]
Not sure if this is the source of your error, but
```
Epsilon = cp.Variable(len(X_train), 1, name="Epsilon")  # punishing factor
```
is cvxpy 0.4.x syntax. The current syntax is
```
Epsilon = cp.Variable(shape=(len(X_train), 1), name="Epsilon")  # punishing factor
```

**Comment by prabathabey** [comment]
@rileyjmurray Apprecaite the prompt response!

My apologies, I seem to have copied the code snippet used in 0.4.x version here. However, the above behaviout was seen in both versions of cvxpy.

I've certainly already tried pretty much most other applicable solvers, as well. As it turned out, OSQP and SCS couldn't build a model on top of the given dataset (they throw SolverErrors and recommend to use other solvers, and sometimes even return "inf" as proble value) at all, and only ECOS and ECOS_BB could successfully train a model and return the parameters of those respective models. It's actually the result of the two aforementioned models that returned superior accuracies. The results are accuracies after all, and there maybe nothing that I should worry about. However, the difference in accuracies (50% returned by libsvm and others vs 98% returned by ECOS, ECOS_BB) made me double check this with the community and ensure I wasn't making any obvious mistakes.

**Comment by SteveDiamond** [comment]
The only idea I have is that libsvm might be solving a slightly different problem than you're imagining. Otherwise there's no obvious issue. (BTW, you should vectorize problems whenever possible in cvxpy.)
