### ISSUE TITLE
Evaluate Objective function at user provided solution

### ISSUE THREAD

**Issue by Rothdyt** [cvxgrp/cvxpy#725]
**Problem - A minimal example**
I am trying to solve the following convex problem.

![image](https://user-images.githubusercontent.com/19240875/57241633-0b60a880-6ff7-11e9-9ad7-5f35e463122f.png)

I want to compare the performance of my own algorithm with solver provided by `CVXPY`. I tried two different way of expressing the objective, where I set w_{ij} = 1 for the sake of simplicity,

```
u = cp.Variable((n,d))
1. objective = cp.Minimize((0.5 * cp.sum_squares(data - u))+ penalty * cp.norm(u[t1] - u[t2], 1) )
2. objective = cp.Minimize((0.5 * cp.norm(data - u, "fro") ** 2)+ penalty * cp.norm(u[t1] - u[t2], 1) )
```
These two formulations gave me nearly the same solution, but when I plugged the `u.value` back to my objective function, which was written as 

```
a = 0.5 * np.sum(np.linalg.norm(data - u.value, 2, axis=1) ** 2.0)
b = penalty * np.sum(np.linalg.norm(u.value[t1] - u.value[t2], ord=1,axis=1))
a + b
```
 it produced totally different results.

The value provided by `CVXPY` is `2943.0156660023194`, while the expression `a+b` yields `5488.4470645803785`.

I have no idea how to debug.

**Describe the solution you'd like**

It would be convenient for users to evaluate the objective specified in `CVXPY` at their provided solution, such that they can know at least whether they are using correct objective functions. 

I would expect something like

```
problem._evaluate_objective(user-provided-solution)
```

**Appendix**
The complete code for CVXPY solving the problem is attached below.

```{python}
np.random.seed(521)
group1 = np.random.multivariate_normal(mean = [10,10], cov=np.eye(d), size=n)
group2 = np.random.multivariate_normal(mean = [-10,10], cov=np.eye(d), size=n)
group3 = np.random.multivariate_normal(mean = [-10,-10], cov=np.eye(d), size=n)
group4 = np.random.multivariate_normal(mean = [10,-10], cov=np.eye(d), size=n)
data = np.vstack((group1, group2, group3, group4))
n,d = data.shape
penalty = 0.1
w = np.array([])
for i in range(n-1):
    for j in range(i+1, n):
        w = np.append(w, [i, j, 1])
w = w.reshape(-1, 3)
t1, t2, w_t = w[:, 0].astype("int"), w[:, 1].astype("int"), w[:, 2]
u = cp.Variable((n,d))
#objective = cp.Minimize((0.5 * cp.sum_squares(data - u))+ penalty * cp.norm(u[t1] - u[t2], 1) )
objective = cp.Minimize((0.5 * cp.norm(data - u, "fro") ** 2)+ penalty * cp.norm(u[t1] - u[t2], 1) )
prob = cp.Problem(objective)
prob.solve(solver="ECOS", verbose=True)
```

**Comment by SteveDiamond** [comment]
You can set the variable value fields yourself, then evaluate any expression involving them. In your case, ``u.value = ...; print(objective.value)``. Perhaps this functionality should be better documented. I'm not sure why you're getting something different with numpy. Probably some subtle difference in the two expressions.

**Comment by Rothdyt** [comment]
> You can set the variable value fields yourself, then evaluate any expression involving them. In your case, `u.value = ...; print(objective.value)`. Perhaps this functionality should be better documented. I'm not sure why you're getting something different with numpy. Probably some subtle difference in the two expressions.

I know I can retrieve the objective value by objective.value. But what I really what to do is to evaluate the objective function value at my solution (derived from another algorithm ) not the solution provided by the `cvxpy`.

**Comment by rileyjmurray** [comment]
I believe the following code does what you are asking for.
```
x = cp.Variable(shape=(3,))
x.value = np.array([1,2,3])
expr = cp.sum_squares(x)
print(expr.value)
```
I.e. you can manually assign a Variable a value, and that value is propagated through calculation of subsequent expressions.

**Comment by Rothdyt** [comment]
> I believe the following code does what you are asking for.
> 
> ```
> x = cp.Variable(shape=(3,))
> x.value = np.array([1,2,3])
> expr = cp.sum_squares(x)
> print(expr.value)
> ```
> 
> I.e. you can manually assign a Variable a value, and that value is propagated through calculation of subsequent expressions.

Thanks. It indeed works, but the rounding error seems to be a little bit large. See figure below.

![image](https://user-images.githubusercontent.com/19240875/57251585-cd23b300-700f-11e9-91b3-4f3ca40fe3b4.png)


**May  I ask one more question?**

Why the following two expressions are different?

```
# the way I express the objective function using numpy
0.5 * np.sum(np.linalg.norm(data - u.value, 2, axis=1) ** 2.0) + penalty * np.sum(np.linalg.norm(u.value[t1] - u.value[t2], ord=1,axis=1))

# the way I express the objective function using CVXPY
(0.5 * cp.sum_squares(data - u))+ penalty * cp.norm(u[t1] - u[t2], 1)

# t1, t2 here are vectorized indices for summation.
```

I think essentially they are both equivalent to
![image](https://user-images.githubusercontent.com/19240875/57251435-6900ef00-700f-11e9-84fa-3ec77e4048be.png)

where w_{ij}=1.

If not, what is the correct way to specify the objective in the CVXPY?

**Comment by SteveDiamond** [comment]
It looks fine to me. Maybe try writing both expressions using ``abs`` instead of the L1-norm.
