### ISSUE TITLE
Does cvxpy support cplex12.9 or mosek 9?

### ISSUE THREAD

**Issue by ChengweiLou** [cvxgrp/cvxpy#726]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen, and how your solution would solve the problem.

**Describe alternatives you've considered**

**Additional context**
Add any other context.

**Comment by rileyjmurray** [comment]
Please follow our guidelines when posting questions. Off the top of my head, the answer to your second question is "yes."
