### ISSUE TITLE
GLPK_MI result status "undefined" or "feasible" results in KeyError

### ISSUE THREAD

**Issue by mbotkinl** [cvxgrp/cvxpy#728]
**Describe the bug**
When constraining GLPK_MI solver using `mip_gap` or `tm_lim` the `cvxopt.glpk.ilp` function sometimes returns `undefined` or `feasible` which results in a `KeyError` when trying to map to `CVXOPT.STATUS_MAP`

**To Reproduce**
```
import numpy as np
import cvxpy as cp
N = 10000
w = np.random.rand(N)
x = cp.Variable(N, nonneg=True)
i = cp.Variable(N, boolean=True)
obj = cp.Minimize(sum(w*x) + cp.tv(i))
constraints = []
constraints += [x <= 10 * i]
constraints += [sum(i) == 5]
prob = cp.Problem(obj, constraints)
prob.solve(verbose=True, solver=cp.GLPK_MI, mip_gap=0.5, tm_lim=10000)
print("status:", prob.status)
```
**Expected behavior**
GLPK status should be mapped to CVXOPT STATUS_MAP

**Output**
![Screenshot from 2019-05-17 11-26-55](https://user-images.githubusercontent.com/32102213/57948534-c2caaa00-7896-11e9-9f07-28869dbddbd8.png)

**Version**
 - OS: Linux
 - CVXPY Version: 1.0.22
 - CVXOPT Version: 1.2.3

**Comment by SteveDiamond** [comment]
This is fixed on master.

**Comment by mbotkinl** [comment]
Thanks that fixes the error. @SteveDiamond My knowledge of GLPK_MI solver is limited but wouldn't we want to map `feasible` to `s.OPTIMAL_INACCURATE` as this means it found a solution but it may not be the optimal one? In reference to this commit: https://github.com/cvxgrp/cvxpy/commit/329b9a7061fd7b8a0738e5bc7f723ed2301fd5ed

**Comment by SteveDiamond** [comment]
I tried to find documentation for the GLPK solver codes, but it looks like CVXOPT maps raw codes to strings. Are you sure that's what feasible means?

**Comment by mbotkinl** [comment]
My reference is the GLPK documentation: [glpk.pdf](https://github.com/cvxgrp/cvxpy/files/3199032/glpk.pdf). I was assuming CVXOPT was using the code that glp_intopt returns to map to the strings. On page 58 it says the successful code only means the solver has completed the solution process but not necessarily found the optimal solution. Couldn't find the source code to support it.

**Comment by SteveDiamond** [comment]
Ok, thanks! I changed it.
