### ISSUE TITLE
how do I speed up (parallelize) cvxpy solver

### ISSUE THREAD

**Issue by mstambou** [cvxgrp/cvxpy#729]
I have written some code that uses the cvxpy library to solve an integer programming problem the code is as follows:

    mat_f = sys.argv[1]
    matIdx2genome_dic_f = sys.argv[2]
    genomes_f = sys.argv[3]
    
    with open(matIdx2genome_dic_f, 'r') as in_f:
        matIdx2genome_dic = json.load(in_f)
    
    M = np.load(mat_f)   
    
    selection = cp.Variable(M.shape[1], boolean = True)
    ones_vec = np.ones(M.shape[1])
    
    constraints = []
    for i in range(len(M)):
        constraints.append(M[i] * selection >= 1)
    
    total_genomes = ones_vec * selection
    
    problem = cp.Problem(cp.Minimize(total_genomes), constraints)
    print('solving the integer programing problem: ')
    time = time.time()
    problem.solve(parallel = True)
    print('problem solved in: '+ str(time.time() - time))
    
    solution = selection.value
    solution = list(map(round, solution))
    solution = np.array(solution)
    
    which_genomes = np.where(solution == 1.0)[0]
    
    with open(genomes_f, 'w') as out_f:
        for idx in which_genomes:
            out_f.write(matIdx2genome_dic[idx]+'\n')

The first command line argument is what's important here, it's a numpy binary matrix that is of shape (1569, 3071).
The problem here is to minimize the number of columns of the matrix needed such that each and every row has at least a 1 in it's rows.

My question is how can I write this script so that it can run faster? is there a way to parallelize it? I have set the parallel parameter to True in the solve method by I don't think it's doing much since I'm monitoring the cpu utilization and it's only 100%, so I don't think that parallel option is doing much? 
Or is there another way (solver that I should call maybe) that would solve this faster?

also another side question, here in this case I have defined the variable to be solved for as : 

     selection = cp.Variable(M.shape[1], boolean = True)

However on another computer when I installed this package today it gives an error when I set boolean = True in the Variable object. I have installed cvxpy on both places similarly using conda environment, did the package change it's objects? 
I had to define this variable as 

     selection = cp.Bool(M.shape[1])

to get the code working. I'm confused as which way is the correct way for future use. Thanks for your time.

**Comment by SteveDiamond** [comment]
You have an old version of cvxpy on the second machine. Out of curiosity, does pip install not work for you? We're trying to make pip install work for everyone. You can pip install even if you're using Anaconda.

**Comment by mstambou** [comment]
> You have an old version of cvxpy on the second machine. Out of curiosity, does pip install not work for you? We're trying to make pip install work for everyone. You can pip install even if you're using Anaconda.

shall I try using pip on the other machine? would it overwrite the previous installation?

Also what advice would you have concerning speeding up the processing time of my code? It's still running.

**Comment by akshayka** [comment]
@mstambou : There are two things that might account for slowness: either CVXPY is taking a long time to "compile" your problem, or the solver is taking a long time to solve the problem (or both).

Is the length of `M` very large? If so, you should vectorize the constraints `M[i] * selection >= 1`, instead of using a for loop (e.g., `cp.matmul(M, selection) >= 1`, if I'm understanding the code correctly). That will speed up the time to "compile" the problem, which might help. 

You can use `verbose=True` to see how much time is being spent in the solver itself. 

Does using `parallel=True` speed things up? That feature is old and not well-tested, and we're considering deprecating it (unless we can find an owner for it).
