### ISSUE TITLE
how to install and use external solvers?

### ISSUE THREAD

**Issue by mstambou** [cvxgrp/cvxpy#730]
I am trying to use an external solver and call it through the cvxpy library. In particular I want to use GLPK_MI solver. When I run the following code in python:

    >>> cp.installed_solvers()
    ['ECOS', 'ECOS_BB', 'SCS', 'OSQP']

it shows the only four solvers callable through the library. However I tried installing the GLPK solver through conda by issuing the following:
    conda install -c conda-forge glpk

I could not later call glpk from cvxpy when I specify the solver as glpk. Is there another way to install these external solvers?

**Comment by SteveDiamond** [comment]
cvxpy interfaces to glpk through cvxopt (http://cvxopt.org/install/index.html#installing-a-pre-built-package). When you install glpk as you did it may not have python bindings.

**Comment by rileyjmurray** [comment]
@SteveDiamond does cvxopt automatically ship with GLPK, or is there some extra installation / configuration step there as well?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SteveDiamond** [comment]
If CVXOPT is installed as a wheel or anything prebuilt, it will include GLPK.

**Comment by ashis-w** [comment]
Building CVXOPT from source as per the steps given in the official website is not able to find the GLPK solver. I tried following steps:
git clone https://github.com/cvxopt/cvxopt.git
cd cvxopt
git checkout `git describe --abbrev=0 --tags`

export CVXOPT_BUILD_GLPK=1    

python setup.py install

installation is successful. But the binding is not done.

Could you please help?
