### ISSUE TITLE
Is there a way to do a rotated second order cone?

### ISSUE THREAD

**Issue by hroskes** [cvxgrp/cvxpy#737]
**Is your feature request related to a problem? Please describe.**
Mosek allows rotated second order cone constraints, as described [here](https://docs.mosek.com/9.0/toolbox/tutorial-cqo-shared.html).  I'd like to be able to pass them to it via cvxpy, but don't see any way to do it in the current implementation.

**Describe the solution you'd like**
I'd like a class for rotated quadratic cone constraints, similar to SOC.

**Describe alternatives you've considered**
I tried to implement this myself, but the issue comes when passing the constraint to [mosek](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py).  I'm way out of my depth there.

**Additional context**

**Comment by rileyjmurray** [comment]
I wrote the Mosek interface, so I should be able to add this functionality. However I will need a “rotated cone” constraint in cvxpy (implementing new types of constraints is something I don’t have experience with).

If this is very time sensitive, you might just want to implement a “rotated cone” primitive of your own in high-level cvxpy syntax (eg using the sum_squares atom, and applying a rotation matrix to the input of this atom). Such an approach will have slow compile-times, and may create ill-conditioned problems, but it should work for prototyping.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hroskes** [comment]
Hi Riley, thanks a lot for your very fast response!

I actually tried to implement something like this, because I originally thought all the logic for the constraint was contained in the constraint class itself.  You can find it [here](https://github.com/hroskes/TemplateBuilder/blob/20d21b5eb99d3eb0739d9a9ba20bb8cd3bb43447/python/rotatedconicconstraint.py), if that's helpful.

I see mentions of SOC throughout the cvxpy code, and I don't know how many of those are critical for transferring data from the initialization to mosek and back to the output, so take my code with a huge dose of salt.

If someone who has expertise in the core of the cvxpy code could comment, that would be amazing.  In the meantime I'll try to use your suggestion.

**Comment by SteveDiamond** [comment]
@hroskes the class is a good start. Knowing the whole pipeline, adding rotated second order cones would add a fair amount of complexity. I feel Riley's proposal of implementing the constraints using higher level atoms is actually best, unless the argument for rotated SOC becomes overwhelming.

**Comment by hroskes** [comment]
@SteveDiamond @rileyjmurray ok, thank you both.

I might be missing something, but I don't see how to get the left side of the rotated cone equation from `sum_squares` with rotated axes.  I can rotate 2xy by pi/4 to end up with x^2-y^2, but that's a difference of squares, not a sum.

**Comment by rileyjmurray** [comment]
The simplest way to implement a rotated SOC constraint is to actually use 2-by-2 linear matrix inequalities (note, there is a generic way to cast a 2x2 LMI as an ordinary SOC constraint). See https://en.wikipedia.org/wiki/Sylvester%27s_criterion for the mathematics involved.

The simplest case of this reduction is for R^3. A vector ``[x,y,z]`` satisfies ``x y >= z^2`` iff the matrix ``[[x, z], [z, y]]`` is positive semidefinite. You can scale this to higher-order rotated SOCs by adding an auxiliary variable. I believe the code below should work.
```
import cvxpy
n = 5
xyz = cvxpy.Variable(shape=(n,))  # first two coordinates are "x" and "y"
t = cvxpy.Variable(shape=(,))
aux_constraint = t >= cvxpy.norm(xyz[2:])
lmi_ constraint = cvxpy.bmat([[xyz[0], t],[t, xyz[1]]]) >> 0
equivalent_rotated_soc = [aux_constraint, lmi_constraint]
```

The reduction to 2-by-2 LMIs is not appropriate for all solvers. For example, ECOS would need to reformulate the LMI as an ordinary SOC constraint. However SCS and MOSEK will handle the LMIs correctly.

@aszekMosek is there a real / substantial benefit to passing 2x2 LMIs to MOSEK via equivalent rotated SOC constraints?

**Comment by rileyjmurray** [comment]
Pinging @aszekMosek and @hroskes once more before closing. The linear matrix inequality approach I described above feels like an adequate resolution of this issue. Do either of you have objections to this solution?

**Comment by aszekMosek** [comment]
@rileyjmurray I think the solution with a 2x2 semidefinite matrix is good, although it may be a bit of a hack from cvxpy modeling perspective? I can add that the latest Mosek internally converts 2x2 LMIs into rotated quadratic cones before solving.

@hroskes On a related note, modeling (rotated quadratic cone) with a (rotated (quadratic cone)) is described in https://docs.mosek.com/modeling-cookbook/cqo.html#rotated-quadratic-cones. There is a difference of squares involved as you wrote, but then you move the negative square to the other side of the inequality.

**Comment by hroskes** [comment]
Oh, I understand now!  I found another way around the issue so I'm ok to close this.

**Comment by hroskes** [comment]
Thanks!

**Comment by rileyjmurray** [comment]
@aszekMosek thanks for the reply.

I have since realized a conceptually simpler way to specify a rotated second order cone constraint in cvxpy: use the ``quad_over_lin`` atom.
```
import cvxpy
n = 5
x = cvxpy.Variable(shape=(n,))
y = cvxpy.Variable(shape=(1,))
z = cvxpy.Variable(shape=(1,))
constraint = [cvxpy.quad_over_lin(x, y) <= z]
# the above enforces  \sum_i x_i^2 <= y * z, and y >= 0.
```
