### ISSUE TITLE
Cannot find function diff_pos()

### ISSUE THREAD

**Issue by RieCo432** [cvxgrp/cvxpy#745]
The documentation lists an atom called diff_pos https://www.cvxpy.org/api_reference/cvxpy.atoms.other_atoms.html#diff-pos It can also be found under elementwise functions on https://www.cvxpy.org/tutorial/dgp/index.html However I cannot find the the actual function in the package and thus cannot use it.

**Comment by akshayka** [comment]
Are you using an older version of CVXPY? I can access it by just typing `cp.diff_pos` using version 1.0.24.

**Comment by RieCo432** [comment]
> Are you using an older version of CVXPY? I can access it by just typing `cp.diff_pos` using version 1.0.24.

Oh right thanks, I found it now. I was looking in cvxpy.atoms and its subfolders, where all the other atoms are found, so I assumed this one to be in there as well. Neihertheless it should have a class name in the online documentation.
