### ISSUE TITLE
'Problem' object has no attribute '_compute_once_is_mixed_integer'

### ISSUE THREAD

**Issue by WillysMa** [cvxgrp/cvxpy#749]
import numpy as np
import scipy.io as sio
import cvxpy as cp
filename = 'channel'
var_name = 'H'
data = sio.loadmat(file_name=filename+'.mat')
H = data[var_name]
antennas, UE, Bs = np.shape(H)

H_ = np.zeros([antennas * Bs, UE], dtype='D')
for i in range(UE):
    H_[:, i] = np.reshape(H[:, i, :], antennas * Bs, order='F').T
print(H_)

sigma = 1
gamma = 10
Pc =100
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)
constr = []
for m in range(UE):
    e = np.eye(UE, UE)
    e[m, m] = 0
    constr += [cp.SOC(np.real(H_[:, m].T @ w[:, m]) / np.sqrt(gamma), np.hstack((H_[:, m].T @ w @ e, sigma))),
               np.imag(H_[:, m].T @ w[:, m]) == 0]
for q in range(Bs):
    constr += [cp.norm(w[(q-1)*antennas+1:q*antennas, :], 'fro') <= Pw[q], Pw[q] <= np.sqrt(Pc)]

prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
prob.solve()
print('Optimal value:', prob.value)

Here I want solve a SOCP problem in communication field. However the Interpreter keep rising the error:'''Problem' object has no attribute '_compute_once_is_mixed_integer' '' and '''numpy.ndarray' object has no attribute 'variables' ''. I don't know what the error means. Have anyone ever went through this? How to fix the problem?

**Comment by SteveDiamond** [comment]
Could you post a code snippet that we can run?

**Comment by WillysMa** [comment]
import numpy as np
import scipy.io as sio
import cvxpy as cp
antennas, UE, Bs = 2, 3, 2
H_= [[0.05221169+0.02236014j, 0.11507819+0.23286528j, 0.04240248+0.05163106j],
 [0.0647228 +0.12858326j, 0.27416864+0.36640208j, 0.01989594+0.07813894j],
 [0.62388787+0.62330062j, 0.02298837+0.03943087j, 0.03940723+0.01719871j],
 [0.63787985+0.2536698j,  0.16819581+0.2366397j,  0.15092605+0.1541783j]]

sigma = 1.
gamma = 1.
Pc =100.
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)
constr = []
for m in range(UE):
    e = np.eye(UE, UE)
    e[m, m] = 0
    constr += [cp.SOC(np.real(H_[:, m].T @ w[:, m]) / np.sqrt(gamma), np.hstack((H_[:, m].T @ w @ e, sigma))),
                    np.imag(H_[:, m].T @ w[:, m]) == 0]

for q in range(Bs):
    constr += [cp.norm(w[q*antennas:(q+1)*antennas, :], 'fro') <= Pw[q], Pw[q] <= np.sqrt(Pc)]

print(constr)
prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
print(prob)
print(prob.is_dcp())
prob.solve()
print('Optimal value:', prob.value)

It's so weird! I put array 'H_' explicitly in the snippet then the Interpreter returned a different type error. Why does that happen？I'm completely confuesd.

**Comment by WillysMa** [comment]
> Could you post a code snippet that we can run?
import numpy as np
import scipy.io as sio
import cvxpy as cp
antennas, UE, Bs = 2, 3, 2
H_= np.mat([[0.05221169+0.02236014j, 0.11507819+0.23286528j, 0.04240248+0.05163106j],
 [0.0647228 +0.12858326j, 0.27416864+0.36640208j, 0.01989594+0.07813894j],
 [0.62388787+0.62330062j, 0.02298837+0.03943087j, 0.03940723+0.01719871j],
 [0.63787985+0.2536698j,  0.16819581+0.2366397j,  0.15092605+0.1541783j]])

sigma = 1.
gamma = 1.
Pc =100.
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)
constr = []
for m in range(UE):
    e = np.mat(np.eye(UE, UE))
    e[m, m] = 0
    t = H_[:, m].T @ w[:, m]
    x = np.hstack((H_[:, m].T @ w @ e, sigma))
    constr += [cp.SOC(t / np.sqrt(gamma), x), np.imag(H_[:, m].T @ w[:, m]) == 0]

for q in range(Bs):
    constr += [cp.norm(w[q*antennas:(q+1)*antennas, :], 'fro') <= Pw[q], Pw[q] <= np.sqrt(Pc)]

print(constr)
prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
print(prob)
print(prob.is_dcp())
prob.solve()
print('Optimal value:', prob.value)

**Comment by WillysMa** [comment]
> Could you post a code snippet that we can run?

import numpy as np
import scipy.io as sio
import cvxpy as cp
antennas, UE, Bs = 2, 3, 2
H_= np.mat([[0.05221169+0.02236014j, 0.11507819+0.23286528j, 0.04240248+0.05163106j],
 [0.0647228 +0.12858326j, 0.27416864+0.36640208j, 0.01989594+0.07813894j],
 [0.62388787+0.62330062j, 0.02298837+0.03943087j, 0.03940723+0.01719871j],
 [0.63787985+0.2536698j,  0.16819581+0.2366397j,  0.15092605+0.1541783j]])

sigma = 1.
gamma = 1.
Pc =100.
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)

constr = []
for m in range(UE):
    e = np.mat(np.eye(UE, UE))
    e[m, m] = 0
    t =np.real(H_[:, m].T @ w[:, m])
    x = np.hstack((H_[:, m].T @ w @ e, sigma))
    constr += [cp.SOC(t / cp.sqrt(gamma), x), np.imag(H_[:, m].T @ w[:, m]) == 0]

for q in range(Bs):
    constr += [cp.norm(w[q*antennas:(q+1)*antennas, :], 'fro') <= Pw[q], Pw[q] <= np.sqrt(Pc)]

print(constr)
prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
print(prob)
print(prob.is_dcp())
prob.solve()
print('Optimal value:', prob.value)

I think the problem is that I try to abstract the real part and imaginary part of the intermidiate result using np.real() and np.imag. But how can I realize that operation using only cvx atomic functions？I’ve read the cvxpy tutorial and failed to find such a function. Is there any other way?

**Comment by WillysMa** [comment]
> Could you post a code snippet that we can run?

import numpy as np
import scipy.io as sio
import cvxpy as cp
antennas, UE, Bs = 2, 3, 2
H_ = np.mat([[0.05221169+0.02236014j, 0.11507819+0.23286528j, 0.04240248+0.05163106j],
 [0.0647228 +0.12858326j, 0.27416864+0.36640208j, 0.01989594+0.07813894j],
 [0.62388787+0.62330062j, 0.02298837+0.03943087j, 0.03940723+0.01719871j],
 [0.63787985+0.2536698j,  0.16819581+0.2366397j,  0.15092605+0.1541783j]])

sigma = [[1.]]
gamma = 1.
Pc =100.
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)

constr = []
for m in range(UE):
    e = np.mat(np.eye(UE, UE))
    e[m, m] = 0
    t = cp.real(H_[:, m].H @ w[:, m])
    x = cp.hstack((H_[:, m].H @ w @ e, sigma))
    constr += [cp.SOC(t / cp.sqrt(gamma), x), cp.imag(H_[:, m].H @ w[:, m]) == 0]

for q in range(Bs):
    constr += [cp.norm(w[q*antennas:(q+1)*antennas, :], 'fro') <= Pw[q], Pw[q] <= cp.sqrt(Pc)]

print(constr)
prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
print(prob)
print(prob.is_dcp())
prob.solve()
print('Optimal value:', prob.value)



> Could you post a code snippet that we can run?

import numpy as np
import scipy.io as sio
import cvxpy as cp
antennas, UE, Bs = 2, 3, 2
H_ = np.mat([[0.05221169+0.02236014j, 0.11507819+0.23286528j, 0.04240248+0.05163106j],
 [0.0647228 +0.12858326j, 0.27416864+0.36640208j, 0.01989594+0.07813894j],
 [0.62388787+0.62330062j, 0.02298837+0.03943087j, 0.03940723+0.01719871j],
 [0.63787985+0.2536698j,  0.16819581+0.2366397j,  0.15092605+0.1541783j]])

sigma = [[1.]]
gamma = 1.
Pc =100.
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)

constr = []
for m in range(UE):
    e = np.mat(np.eye(UE, UE))
    e[m, m] = 0
    t = cp.real(H_[:, m].H @ w[:, m])
    x = cp.hstack((H_[:, m].H @ w @ e, sigma))
    constr += [cp.SOC(t / cp.sqrt(gamma), x), cp.imag(H_[:, m].H @ w[:, m]) == 0]

for q in range(Bs):
    constr += [cp.norm(w[q*antennas:(q+1)*antennas, :], 'fro') <= Pw[q], Pw[q] <= cp.sqrt(Pc)]

print(constr)
prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
print(prob)
print(prob.is_dcp())
prob.solve()
print('Optimal value:', prob.value)

It satisfies the DCP rule but AssertionError arises. I don't know what's that mean. What kinds of factors can lead to such error ? And how can I dug it?

**Comment by WillysMa** [comment]
> Could you post a code snippet that we can run?
import numpy as np
import scipy.io as sio
import cvxpy as cp
antennas, UE, Bs = 2, 3, 2
H_ = np.mat([[0.05221169+0.02236014j, 0.11507819+0.23286528j, 0.04240248+0.05163106j],
 [0.0647228 +0.12858326j, 0.27416864+0.36640208j, 0.01989594+0.07813894j],
 [0.62388787+0.62330062j, 0.02298837+0.03943087j, 0.03940723+0.01719871j],
 [0.63787985+0.2536698j,  0.16819581+0.2366397j,  0.15092605+0.1541783j]])

sigma = [[1.]]
gamma = 1.
Pc =100.
w = cp.Variable((antennas * Bs, UE), complex=True)
Pw = cp.Variable(Bs)

constr = []
for m in range(UE):
    e = np.mat(np.eye(UE, UE))
    e[m, m] = 0
    t = cp.real(H_[:, m].H @ w[:, m])
    x = cp.hstack((H_[:, m].H @ w @ e, sigma))
    constr += [cp.SOC(t / cp.sqrt(gamma), x), cp.imag(H_[:, m].H @ w[:, m]) == 0]

for q in range(Bs):
    constr += [cp.norm(w[q*antennas:(q+1)*antennas, :], 'fro') <= Pw[q], Pw[q] <= cp.sqrt(Pc)]

print(constr)
prob = cp.Problem(cp.Minimize(cp.sum(Pw)), constr)
print(prob)
print(prob.is_dcp())
prob.solve()
print('Optimal value:', prob.value)

It satisfies the DCP rule but AssertionError arises. I don't know what's that mean. What kinds of factors can lead to such error ? And how can I dug it?

**Comment by WillysMa** [comment]
I need to extract the real part and imaginary part of the intermediate result. But cp.real and cp.imag seems not to work the way I thought. Is there other way to achieve this operation?
