### ISSUE TITLE
Problem with Hermitian matrices

### ISSUE THREAD

**Issue by Navascues1980** [cvxgrp/cvxpy#751]
I try to optimize 0 over a Hermitian matrix Z with unit trace, and I get an error. If, however, the matrix is real and symmetric OR I add the constraint Z>>0, I get the right result, i.e., 0. Why? I am running CVXPY 1.0.23 under Windows.

Here is a minimalistic code:

import numpy as np
import cvxpy as cp
from cvxpy import Variable
from cvxpy.atoms.affine.trace import trace

def problem2():
    Z=Variable((2,2),hermitian=True)
    constraints=[trace(cp.real(Z))==1]
    obj=cp.Minimize(0)
    prob=cp.Problem(obj,constraints)
    prob.solve()
    return prob.value

When I run problem2(), I obtain the (very long) error message:

KeyError                                  Traceback (most recent call last)
<ipython-input-49-0d7845e41109> in <module>
----> 1 problem2()

D:\Documents\pythonProg\connectors\testComplexOpt.py in problem2()
     50     obj=cp.Minimize(0)
     51     prob=cp.Problem(obj,constraints)
---> 52     prob.solve()
     53     return prob.value

D:\Users\Miguel\Anaconda3\lib\site-packages\cvxpy\problems\problem.py in solve(self, *args, **kwargs)
    287         else:
    288             solve_func = Problem._solve
--> 289         return solve_func(self, *args, **kwargs)
    290
    291     @classmethod

D:\Users\Miguel\Anaconda3\lib\site-packages\cvxpy\problems\problem.py in _solve(self, solver, warm_start, verbose, parallel, gp, qcp, **kwargs)
    572         full_chain = self._solving_chain.prepend(self._intermediate_chain)
    573         inverse_data = self._intermediate_inverse_data + solving_inverse_data
--> 574         self.unpack_results(solution, full_chain, inverse_data)
    575         return self.value
    576

D:\Users\Miguel\Anaconda3\lib\site-packages\cvxpy\problems\problem.py in unpack_results(self, solution, chain, inverse_data)
    711         """
    712
--> 713         solution = chain.invert(solution, inverse_data)
    714         if solution.status in s.ERROR:
    715             raise error.SolverError(

D:\Users\Miguel\Anaconda3\lib\site-packages\cvxpy\reductions\chain.py in invert(self, solution, inverse_data)
     71         """
     72         for r, inv in reversed(list(zip(self.reductions, inverse_data))):
---> 73             solution = r.invert(solution, inv)
     74         return solution

D:\Users\Miguel\Anaconda3\lib\site-packages\cvxpy\reductions\complex2real\complex2real.py in invert(self, solution, inverse_data)
     72                 elif var.is_complex() and var.is_hermitian():
     73                     imag_id = inverse_data.real2imag[vid]
---> 74                     imag_val = solution.primal_vars[imag_id]
     75                     pvars[vid] = solution.primal_vars[vid] + \
     76                         1j*(imag_val - imag_val.T)/2

KeyError: 1167

**Comment by SteveDiamond** [comment]
This issue is fixed in master.
