### ISSUE TITLE
is_sparse in cvxpy.interface does not work with cvxopt spmatrix

### ISSUE THREAD

**Issue by milkiss** [cvxgrp/cvxpy#752]
**Describe the bug**
is_sparse in cvxpy.interface does not work with cvxopt a-matrix.
this prevents users to do <cvxopt.spmatrix> * <CVXPY.Variable>

**To Reproduce**
import cvxopt
s=cvxopt.sparse([])
import cvxpy.interface as intf
intf.is_sparse(s) # False

v = cvxpy.Variable(1)
s*v # TypeError: float() argument must be a string or a number, not 'cvxopt.base.spmatrix'

**Expected behavior**
is_sparse(s) should be True

**Version**
 - OS: osx 10.14.5
 - CVXPY Version: 1.0.24
 - CVXOPT Version: 1.2.3

**Comment by rileyjmurray** [comment]
Is there any reason why you aren’t using a scipy sparse matrix? I’m not familiar with every last bit of cvxpy’s intended compatibility features, but using something from cvxopt instead of scipy seems strange.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by milkiss** [comment]
> Is there any reason why you aren’t using a scipy sparse matrix? I’m not familiar with every last bit of cvxpy’s intended compatibility features, but using something from cvxopt instead of scipy seems strange.
> 
> Sent with [GitHawk](http://githawk.com)

No reason. Is it recommended to use SciPy matrices than cvxopt matrices?
I just used it as I used to use cvxopt.

**Comment by rileyjmurray** [comment]
You should absolutely use scipy sparse matrices rather than cvxopt sparse matrices. Scipy is the de-facto standard for sparse linear algebra (along with a hundred other things) in the python programming language.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by milkiss** [comment]
Got it! thanks for kind help :)
