### ISSUE TITLE
l1-norm constraint is violated in the portfolio optimization example

### ISSUE THREAD

**Issue by jjgraveline** [cvxgrp/cvxpy#753]
As the subject suggests, the l1-norm constrain is violated in the [portfolio optimization](https://colab.research.google.com/github/cvxgrp/cvx_short_course/blob/master/applications/portfolio_optimization.ipynb) example.

Here is code to replicate the issue.

`import numpy as np`
`import cvxpy as cp`

`# Generate data for factor model.`
`n = 3000`
`m = 50`
`np.random.seed(1)`
`mu = np.abs(np.random.randn(n, 1))`
`Sigma_tilde = np.random.randn(m, m)`
`Sigma_tilde = Sigma_tilde.T.dot(Sigma_tilde)`
`D = np.diag(np.random.uniform(0, 0.9, size=n))`
`F = np.random.randn(n, m)`

`# Factor model portfolio optimization.`
`w = cp.Variable(n)`
`f = F.T*w`
`gamma = cp.Parameter(nonneg=True)`
`Lmax = cp.Parameter()`
`ret = mu.T*w`
`risk = cp.quad_form(f, Sigma_tilde) + cp.quad_form(w, D)`
`prob_factor = cp.Problem(cp.Maximize(ret - gamma*risk), `
`                     [cp.sum(w) == 1, `
`                      cp.norm(w, 1) <= Lmax])`

`# Solve the factor model problem.`
`Lmax.value = 1.2  # changed from original value of 2.`
`gamma.value = 0.1`
`prob_factor.solve(verbose=True)`

At the solution, it should be the case that
`cp.norm(w, 1).value <= Lmax.value`

but this is False.

The example notebook on colab is running version 1.0.15 and it fails.  I've also tested in it OS X, Windows, and Linux using version 1.0.24 and it fails as well.

**Comment by SteveDiamond** [comment]
Thanks for letting us know! If you solve it with ECOS, the constraint is well satisfied. In CVXPY 1.0 we made OSQP the default solver for QPs (which this is). I'll let the OSQP devs know about your example.

**Comment by bstellato** [comment]
@jjgraveline please follow the discussion here https://github.com/oxfordcontrol/osqp/issues/158
