### ISSUE TITLE
Excessive (rouge?) solver output -- making CI builds unreadable

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#756]
Our TravisCI builds are failing because of flake8 issues. However, we cannot see this from the usual logs in Travis, because the log is exceeding TravisCI's limit of 10k lines.

Refer to https://travis-ci.org/cvxgrp/cvxpy/jobs/548832775#L2438, where a solver is writing to an output stream that it shouldn't be, and dumps about 20k lines into the log.

The raw log can be found here: https://api.travis-ci.org/v3/job/548832775/log.txt. If you CTRF+F for "flake8", you should get 7 results, and the 7th result shows the errors.

We should identify the solver that is responsible for writing these lines, and find out how to suppress the output. There is a chance that we are just calling ``prob.solve(verbose=True)``, but that actually happens in a large number of tests, and we don't see the output of those tests in the Travis logs. This leads me to believe that the lines are being written by a solver's C code. I think I remember seeing SCS writing lines like this from time to time, but never in such abundance.

**Comment by SteveDiamond** [comment]
Thanks Riley! The output is from SCS. I found this bug earlier, where output is being printed even though verbose is False. @bodono is there a version of SCS out that has the Anderson acceleration errors silenced?

**Comment by bodono** [comment]
I have fixed it in the latest SCS, I'll cut a new pip release containing it asap.

**Comment by bodono** [comment]
Just uploaded SCS 2.1.1 to pip with the warning silenced.
