### ISSUE TITLE
CPLEX benders decomposition Set annotations parameters in cvxpy

### ISSUE THREAD

**Issue by AXE-Chen** [cvxgrp/cvxpy#757]
With CPLEX has been added with Benders Decomposition, using the Benders decomposition "USER" strategy of CPLEX to decompose my model strictly according to my annotations. What I want to know is that how to transmit the annotation parameters to cvxpy? Like the follows for "USER(1)".
`>>>` # Set CPXPARAM_Benders_Strategy (1501) to FULL (3)
... cpx_params = {"benders.strategy": 3}
`>>>` prob.solve(solver=cvx.CPLEX, verbose=True,
               cplex_params=cpx_params")

**Comment by SteveDiamond** [comment]
It should be cplex_params, not cpx_params. Otherwise you'll need to try it.

**Comment by AXE-Chen** [comment]
> It should be cplex_params, not cpx_params. Otherwise you'll need to try it.

Thanks for your answer!
