### ISSUE TITLE
cvxpy for real-time - Understanding prob.solve overhead time

### ISSUE THREAD

**Issue by greymfm** [cvxgrp/cvxpy#762]
Hello,
For some real-time model-predicted control (MPC), I'm trying to figure out if cvxpy could be used for real-time control.

Therefore, I'm constructing a cvxpy minimization problem with cvxpy variables, constraints and parameters. I only construct this problem one time. Then I update the parameter values (param.value = ...)  in my control loop **without** reconstructing the problem or any of the constraints or variables.

Using different solvers (ECOS, OSQP), I measured the time for the cvxpy.Problem.solve function call which is 100 ms:
![grafik](https://user-images.githubusercontent.com/11735886/60804675-51b0c000-a17e-11e9-9400-38d70613fc65.png)
**prob.solve 0.109   (=100 ms)**

When activating 'verbose=True' for cvxpy.Problem.solve, I can see in the terminal output that the actual solve time however is only 6 ms:
![grafik](https://user-images.githubusercontent.com/11735886/60804721-6d1bcb00-a17e-11e9-8a6a-6b9259df3a79.png)
**Runtime: 0.0062 seconds.   (=6 ms)** 

Why is there such a big difference in processing time between the cvxpy.Problem.solve function call and the actual solver function, how could I reduce the function call overhead time? I assumed that just assigning values to parameters can be fast and would not have to internally 'recompile' anything for the solver?

cvxpy version: 1.0.24
Conda: 4.5.12 (Python 3.6.6, Win64)
my code:  [mpc.zip](https://github.com/cvxgrp/cvxpy/files/3367963/mpc.zip)

Thanks,
Alexander Grau

**Comment by akshayka** [comment]
Hey Alexander. CVXPY is not yet ready for real-time applications. We’re working on a new version of CVXPY (version 1.1) that’ll be better suited for your needs — it’ll make more intelligent use of parameters, and it’ll also support code generation for embedded optimization. So stay tuned — we don’t know when exactly 1.1 will be ready, but hopefully it’ll land sometime this year.

**Comment by greymfm** [comment]
Thanks for the info :-)

**Comment by greymfm** [comment]
You can close this issue if you like. I found the solution by using the ACADO code generator to generate a Python C extension for my MPC problem that can run even faster than realtime (only a few hundred microseconds per control step). I'm quite happy with the results :). 
Maybe a future code generator for CVXPY could do the same, however I think it probably runs best when looking at specific optimization problems (MPC in my case).

![grafik](https://user-images.githubusercontent.com/11735886/61376113-c4b5e700-a8a0-11e9-953a-7490f39a2268.png)

**Comment by Danfoa** [comment]
I am still experiencing overhead time consumption. The time difference is approximately one order of magnitude greater than the optimizer reported one. 

Could I get some info on the causes of this and possible solutions? 

PS: I have version `1.1.10`

**Comment by phschiele** [comment]
Hi @Danfoa, you could try to profile the function call when solving the optimization problem.
For that, you can use something like [tuna](https://github.com/nschloe/tuna) (kudos to @akshayka, from whom I copied using the tool).
Is your optimization problem related to the one discussed in the issue above (which dates back to before the release of version `1.1`)?

**Comment by Danfoa** [comment]
Hi, @phschiele thanks for the quick answer. I did profile my program, here is the [.prog](https://drive.google.com/file/d/1I_q4f4dKzHiAFnnyso_5lNWcUTfP1cXU/view?usp=sharing) file. Search for the `flight_stance_cycle_opt` function call, this is where I am solving a `QP` with `OSQP`. 

The profile seems to suggest that there is a lot of heap time in reductions and expressions transforms, I guess this part of `cvxpy` is done in python and that's why it consumes so much? Could it be related to the details of my implementation?

I can really use some insight into how to reduce the overall time.

In the image, you can see the order of magnitude increase elapsed time from the solver reported time:
![Capture](https://user-images.githubusercontent.com/8356912/108818104-3136b300-75b9-11eb-81d2-374c3c918776.PNG)

**Comment by SteveDiamond** [comment]
@Danfoa are you using parameters? I assume you're solving the same problem form multiple times.

**Comment by Danfoa** [comment]
Yes I am using `warm start`, `time limit`, `refine=False`, `max_iter`, and I believe some other minor adjustments. However although the solver works extremely fast the overhead keeps constant.


As a matter of fact I am solving the same QP Form (Quadratic cost is computed as the sum of quadratic error of a polynomial (whose coefficients are the program variables) and some reference trajectory), while constraints are final and initial trajectory constraints.

I am solving the same QP but the reference trajectory varies from iteration to iteration, only the reference in que quadratic error costs, everything else is kept constant through iterations.

**Comment by phschiele** [comment]
I think the question was referring to the usage of [cvxpy Parameters](https://www.cvxpy.org/api_reference/cvxpy.expressions.html#parameter). 

As you mention, reconstructing the problem indeed can create overhead.
Consider this simple example (slight adaption of [Docs](https://www.cvxpy.org/tutorial/advanced/index.html#warm-start)) to see how using a `Parameter` can speed up the optimizations:

```python
import time
import cvxpy as cp
import numpy

# Problem data.
m = 1000
n = 1000
n_solves = 10
numpy.random.seed(1)
A = numpy.random.randn(m, n)
parameter_values = numpy.random.randn(m,100)

# w/o parametrization
solver_time = 0
start=time.time()
for i in range(n_solves):
    x = cp.Variable(n)
    b = parameter_values[:,i]
    prob = cp.Problem(cp.Minimize(cp.sum_squares(A @ x - b)),
                       [x >= 0])
    prob.solve()
    solver_time += prob.solver_stats.solve_time
end = time.time()
print(f'total_time {end-start}, solver_time: {solver_time}, solver share: {solver_time/(end-start)}')

# w/ parametrization
solver_time = 0
start = time.time()
x = cp.Variable(n)
b = cp.Parameter(m)
prob = cp.Problem(cp.Minimize(cp.sum_squares(A @ x - b)),
                   [x >= 0])
for i in range(n_solves):
    b.value = parameter_values[:,i]
    prob.solve(warm_start=True)
    solver_time += prob.solver_stats.solve_time
end = time.time()

print(f'total_time {end-start}, solver_time: {solver_time}, solver share: {solver_time/(end-start)}')
```

```python
total_time 69.73, solver_time: 61.42, solver share: 0.88
total_time 27.06, solver_time: 25.73, solver share: 0.95
```
Not only is the computation much faster overall, but the fraction of time spent in the solver also increases.
Relevant to when such improvements are achievable, check out the [DPP ruleset](https://www.cvxpy.org/tutorial/advanced/index.html#what-is-dpp).

**Comment by Danfoa** [comment]
@phschiele @SteveDiamond, sorry for the confusion with the Parameters.

I followed your example and the documentation on DPP, and effectively the overhead time was increasingly reduced, although it's still considerable on top of the solver reported one. However, I was able to achieve almost real-time performance, which is more than fine for now. Absolute Thanks!.

Also, although I read a lot of the documentation while implementing the QP for the first time (this was my first use of cvxpy) I was never able to find the concepts of the DPP and the tricks for optimal performance. Maybe it would be helpful to make it more accessible in the documentation.

**Comment by SteveDiamond** [comment]
@Danfoa I'm glad things are working for you now! For sure, I'll mention to the other devs that we should make DPP more prominent. We've added a lot of features over the last year or so and the docs may not highlight them all as clearly as they should

**Comment by whenwherewhy** [comment]
Hi! I want to use CVXPY to slove a quadratic problem with changing cost and constrains for path tracking. As the example Repeatedly solving a DPP problem shows in the tutorial , the cost and constrains of the problem are not changing with the value. I try to constructing the problem once at the beginning, and solve the problem at each iteration with different cost and constrains. Unfortunately, it doesn't seem to work well. But the total time was increasingly reduced. I think this method is feasible, maybe somewhere has gone wrong.  Could you please give me some suggestions on  repeatedly solving a DPP problem with changing cost and constrains?

**Comment by SteveDiamond** [comment]
@whenwherewhy it's a bit tricky if you have a changing set of constraints. DPP is designed for problems where the dimensions and functional form don't change, for example a quadratic program
```
min x^TPx + q^Tx
subject to Ax = b
                  Gx <= h
```
where P, q, A, b, G, and h are parameters with fixed dimensions. Does your application fit into that setting?
