### ISSUE TITLE
how to get coefficients for logistic regression? 

### ISSUE THREAD

**Issue by Sandy4321** [cvxgrp/cvxpy#763]
as per this example
https://www.cvxpy.org/examples/machine_learning/logistic_regression.html
how to get coefficients for logistic regression? 

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen, and how your solution would solve the problem.

**Describe alternatives you've considered**

**Additional context**
Add any other context.

**Comment by rileyjmurray** [comment]
Please post these kinds of questions to Stack Exchange, with a “cvxpy” tag.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
