### ISSUE TITLE
how to find solution for unbalanced data: class_weight  needed

### ISSUE THREAD

**Issue by Sandy4321** [cvxgrp/cvxpy#764]
how to use
https://www.cvxpy.org/examples/machine_learning/logistic_regression.html
with class_weight  parameter?

scikit versoin has parameter class_weight 
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html
class_weight : dict or ‘balanced’, optional (default=None)
Weights associated with classes in the form {class_label: weight}. If not given, all classes are supposed to have weight one.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**
A clear and concise description of what you want to happen, and how your solution would solve the problem.

**Describe alternatives you've considered**

**Additional context**
Add any other context.

**Comment by rileyjmurray** [comment]
That file is merely an example. It is expected that you understand what logistic regression is trying to accomplish.

Please post these kinds of questions to Stack Exchange, with a “cvxpy” tag.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
