### ISSUE TITLE
1 norm of matrix does not match web documentation 

### ISSUE THREAD

**Issue by sunilshah** [cvxgrp/cvxpy#766]
On the CVXPY web documentation (dated on July 9, 2019), the table of Atomic Functions in Tutorial section defines 

norm(X,1) = sum over i,j  (abs(X(i,j))) 

under scalar function of a m x n real matrix X. 

However, the source code and the documentation in the code states clearly that norm(X,1) will be the standard definition of 1 norm of X, i.e., max of column sum of absolute values.  

     

It is easy to see the behavior for a real matrix variable  by evaluating 

```
X=cvx.Variable((2,2))
X.value=np.random.randn(2,2)
print(X.value)
print(cvx.norm(X,1).value,cvx.norm(cvx.vec(X),1).value,cvx.norm1(X).value)
```

**Comment by SteveDiamond** [comment]
Thanks for pointing this out! I've updated the documentation.

**Comment by rileyjmurray** [comment]
There is now a failing test related to this issue.

Do a CTRL+F for "FAIL: Test that norm1 and normInf match definition for matrices."

https://api.travis-ci.org/v3/job/558363565/log.txt

**Comment by SteveDiamond** [comment]
Oops, I left in an assert False! It's fixed now.
