### ISSUE TITLE
logistic regression example   is not working at all

### ISSUE THREAD

**Issue by Sandy4321** [cvxgrp/cvxpy#767]
**Describe the bug**

logistic regression example 
https://www.cvxpy.org/examples/machine_learning/logistic_regression.html
is not working at all
Probability of error is 50% on your figure
plt.plot(lambda_vals, train_error, label="Train error")
plt.plot(lambda_vals, test_error, label="Test error")
plt.xscale('log')
plt.legend(loc='upper left')
plt.xlabel(r"$\lambda$", fontsize=16)
plt.show()
and 
beta Reconstruction is bad
**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

**Expected behavior**
probability of error should be low and beta should be some Reconstructed, lets say with 10% for each beta element  

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: Windows
 - CVXPY Version: latest

**Additional context**

**Comment by SteveDiamond** [comment]
I've updated the logistic regression example to have more compelling numerical results.

**Comment by Sandy4321** [comment]
great thanks, will test it, what change was?
But mostly important , can you add demonstration of beta_true reconstruction
it is so easy for you to do: just show plot of beta_true and reconstructed beta

thanks in advance
