### ISSUE TITLE
Infix operator * is not affine when one expression is constant

### ISSUE THREAD

**Issue by dtch1997** [cvxgrp/cvxpy#772]
In the documentation, it says: 

> expr1*expr2 is DCP only when one of the expressions is constant

However, this seems to not be the case:

`import cvxpy as cp`
`a = cp.Parameter([2])`
`b = cp.Variable([2])`
`print(a.curvature) # CONSTANT`
`print(cp.log(b).curvature) # CONCAVE`
`print((a * cp.log(b)).curvature) # UNKNOWN`

Is this a bug, or did I misunderstand the DCP rules? 

EDIT: If it helps, I am on cp version 1.0.24

**Comment by SteveDiamond** [comment]
Thanks for bringing up this point of confusion! One of the expressions being constant is a necessary but not sufficient condition for the ``expr1*expr2`` being DCP compliant. I've rewritten the documentation to be more clear.
