### ISSUE TITLE
in logistic_regression example data is created with mistake

### ISSUE THREAD

**Issue by Sandy4321** [cvxgrp/cvxpy#774]
**Describe the bug**
in
https://www.cvxpy.org/examples/machine_learning/logistic_regression.html
line 
Y_test = X_test @ beta_true + np.random.normal(0, sigma, size=(m,1))
should be changed to 
Y_test = X_test @ beta_true + np.random.normal(0, sigma, size=(m))

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.

**Expected behavior**

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: 
 - CVXPY Version:

**Additional context**

**Comment by jinglejiang** [comment]
This is not really an issue... Essentially, (X_test @ beta_true) returns a 1D vector of shape (m,), and when you add it with 

1. 1D vector of shape (m,) as produced by np.random.normal(size=(m))
2. 2D vector of shape (m,1) as produced by np.random.normal(size=(m,1)) 

results are the same thanks to numpy [broadcasting](https://stackoverflow.com/questions/5954603/transposing-a-numpy-array)

and it's common among python data science practitioner to interchange these two data structure.

**Comment by Sandy4321** [comment]
in any case coefficients should be reconstructed
did you tried answer to this
https://stackoverflow.com/questions/57244206/interior-point-m-cvxpy-logistic-regression-does-not-reconstruct-regression-coeff

**Comment by SteveDiamond** [comment]
@Sandy4321 I apologize for not taking your concerns seriously. I have fixed the example. There was a second bug in it. Let me know if you are satisfied.

**Comment by Sandy4321** [comment]
thanks let me try 
but did you tested with this test example
https://github.com/vene/pyowl
https://github.com/vene/pyowl/blob/master/test_pyowl.py
![image](https://user-images.githubusercontent.com/11426119/63950809-acfa8280-ca4a-11e9-92d3-86d30148a254.png)

**Comment by SteveDiamond** [comment]
Fixed.
