### ISSUE TITLE
The Mixed Conda/Pip Installation in Windows Causes Conda Instabilities

### ISSUE THREAD

**Issue by rhaskett** [cvxgrp/cvxpy#778]
**Describe the bug**
We have Anaconda and CVXPY installed on a number of machines.  With a fresh Conda install and following the [directions](https://www.cvxpy.org/install/#anaconda-installation) CVXPY works.  However, after a few months if we need to update numpy/pandas "conda update --all" will break the conda environment but only on machines with CVXPY installed through pip.

**To Reproduce**
1) Install with an old version of Anaconda "Anaconda3-5.2.0-Windows-x86_64"
2) Install cvxpy using pip
3) run conda update --all
4) import numpy

**Output**
>     from pandas.core.frame import DataFrame
>   File "C:\anaconda3\lib\site-packages\pandas\__init__.py", line 17, in <module>
>     "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
> ImportError: Unable to import required dependencies:
> numpy: DLL load failed: The specified module could not be found.

**Version**
 - OS: Windows 64-bit
-  Conda: 2019.07
 - CVXPY Version: 1.0.24

**Comment by rhaskett** [comment]
This may have been a reproduction error on my part.  I will close and explore further.

**Comment by SteveDiamond** [comment]
So there wasn't actually an issue?
