### ISSUE TITLE
Incorrect solution to simple DGP problem

### ISSUE THREAD

**Issue by narain** [cvxgrp/cvxpy#782]
Consider the following nearly trivial problem:

```
import cvxpy as cp
import numpy as np

w = cp.Variable(pos=True)
h = cp.Variable(pos=True)
problem = cp.Problem(cp.Minimize(h), [w*h >= 10, w <= 5])
problem.solve(gp=True)
print(problem.value)
```

CVXPY correctly finds that the optimal value of h is (approximately) 2. However, if you replace the constraint w <= 5 with cp.sum(w) <= 5, the optimal value changes to approximately 2.5. This occurs with both ECOS and SCS solvers on CVXPY 1.0.24.

**Comment by akshayka** [comment]
Thanks for reporting, we’ll fix this.

**Comment by narain** [comment]
I'm afraid the fix is probably not quite so simple. I only posted a one-dimensional problem for simplicity, but I guess that was misleading. Here is a two-dimensional (separable) version showing the same problem:

```
import cvxpy as cp
import numpy as np

w = cp.Variable(2, pos=True)
h = cp.Variable(2, pos=True)
goodProblem = cp.Problem(cp.Minimize(h[0]+h[1]), [cp.multiply(w,h) >= 10, w[0]+w[1] <= 10])
goodProblem.solve(gp=True)
print(goodProblem.value)
# 3.9999999939163136
print(w.value)
# [5. 5.]
print(h.value)
# [2. 2.]
badProblem = cp.Problem(cp.Minimize(cp.sum(h)), [cp.multiply(w,h) >= 10, cp.sum(w) <= 10])
badProblem.solve(gp=True)
print(badProblem.value)
# 5.444444445995609
print(w.value)
# [4.5 4.5]
print(h.value)
# [2.22222222 2.22222222]
```

It appears that cp.sum() is just off by one when DGP is on.

**Comment by akshayka** [comment]
@narain, thanks a ton for the detailed bug report. I've pushed a fix. The Python builtin sum() uses `0` as its initial argument, which due to the nature of DGP canonicalization led to the off-by-one error.

**Comment by akshayka** [comment]
Reopining because an import error is breaking the build, will fix later today. The logic of the fix is correct, though, thanks again.
