### ISSUE TITLE
mosek cvxpy interface works slower when using Dask task schedular

### ISSUE THREAD

**Issue by RuiXu55** [cvxgrp/cvxpy#783]
mosek cvxpy interface works slower when using Dask task schedular compared to run it with local jupyter notebook (both set the number of threads to be 1). The performance is much worse when multi-threading is enabled.

**Comment by SteveDiamond** [comment]
mosek is probably multi-threaded itself, so that may be a factor.

**Comment by RuiXu55** [comment]
it's slower even when setting the number of threads to be one in both cases.

**Comment by rileyjmurray** [comment]
Can you compare this to other interface files? For example, could you try using SCS and Dask?

SCS runtimes and solution quality will likely be worse than with Mosek, but I’m just curious about SCS-notebook vs SCS-Dask.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RuiXu55** [comment]
I think I found the solution. it seems mosek can take advantage of multiple-CPUs, that's why it's slower when you only use one cpu for the computation.

**Comment by rileyjmurray** [comment]
Closing because OP's last response indicated a non-issue, and OP did not follow-up with my last question.
