### ISSUE TITLE
CPLEX fail to solve MIP feasible problem

### ISSUE THREAD

**Issue by Eitan99** [cvxgrp/cvxpy#785]
My MIP problem is feasible, as all constrains have slack variable and I can also solve for optimal solution when I use another solver (namely CBC). Moreover, when I look at CPLEX progress (verbose=True), I see it has found a solution.

However, CPLEX claims Error 1217 (CPLEX Error  1217: No solution exists). In some cases, the cvxpy returns the solution (even though the error message). I understood this is just 'wrong error message'.
 
My problem is that cvxpy stops and write "Cannot unpack invalid solution".

Thanks. 

![image](https://user-images.githubusercontent.com/54119040/63049616-c398c980-bee1-11e9-9e8e-4701c02f1968.png)

**Comment by SteveDiamond** [comment]
Can you provide an example we can run? @sschnug could you perhaps take a look when you have time? It might be an issue with the CPLEX interface.

**Comment by Eitan99** [comment]
Thanks. 
[problem.zip](https://github.com/cvxgrp/cvxpy/files/3504870/problem.zip)
See attachment. Unfortunately I could not re-produce the issue on a smaller problem.

**Comment by rkersh** [comment]
@Eitan99: Using your attachment and the following code, I was not able to reproduce the issue:
```
import cvxpy
import pickle


with open("problem.pickle", "rb") as f:
    prob = pickle.load(f)
    print(prob)

prob.solve(solver=cvxpy.CPLEX, verbose=True, cplex_filename="testpickle.sav")
print("status:", prob.status)
print("objective:", prob.value)
```

**Comment by Eitan99** [comment]
@rkersh Thank you for trying to help. I checked again, with your straight forward code - same error. I'm using Windows, Anaconda and Jupiter. Could that be the reason? 
Anyway, in the meantime I've found a way around- I call CPLEX from cvxpy and write problem.mps file. It fails, but then I solve it with cplex.Cplex("problem.mps"), and luckily my variable structure is simple to extract.

**Comment by rkersh** [comment]
@Eitan99: What versions of cvxpy and CPLEX are you using?

**Comment by Eitan99** [comment]
@rkersh cvxpy 1.0.21, cplex 12.9.0.1

**Comment by rkersh** [comment]
@Eitan99: I can reproduce the "CPLEX Error 1217: No solution exists" error message with cvxpy 1.0.21. This jogged my memory; that issue was fixed with https://github.com/cvxgrp/cvxpy/issues/747. If you update your version of cvxpy you shouldn't see that message any more. However, as I think you were pointing out, this may not have anything to do with your "Cannot unpack invalid solution" error. Just to be sure, can you try with cvxpy 1.0.25?

**Comment by Eitan99** [comment]
@rkersh 1.0.25 solves the issue! thanks.
