### ISSUE TITLE
appveyor builds are failing

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#788]
It seems that they've been failing for almost a month. Here is the earliest failure in the sequence of builds I'm referring to:

https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/26199963/job/x7ayjweqxyi8ob2p

That build has a failure because of a unittest. The more common failure mode is that something goes wrong with conda. See the next commit (albeit on a different branch):

https://ci.appveyor.com/project/StevenDiamond/cvxpy/builds/26390089

Something must have changed with how conda installs on Windows machines. I think I've seen this error before.

I don't have an estimate for when I can try and fix this, but I wanted to create an issue since I noticed the build failure.

**Comment by EQt** [comment]
Is there any reason to download MiniConda and not use one of the [pre-installed versions provided by AppVeyor](https://www.appveyor.com/docs/windows-images-software/#miniconda)?

**Comment by EQt** [comment]
I tried it (see [fix_appveyor](https://github.com/EQt/cvxpy/tree/fix_appveyor) branch). At least the conda setup worked. However it can't find the `_cvxcore` module any more:

https://ci.appveyor.com/project/EQt/cvxpy/builds/27199482

**Comment by akshayka** [comment]
Now, builds are failing because SCS can't find lapack+blas:

https://ci.appveyor.com/project/StevenDiamond/cvxpy/build/job/604u7t1ts1cs162s

**Comment by akshayka** [comment]
https://github.com/bodono/scs-python/issues/5 might be relevant

**Comment by akshayka** [comment]
Fixed by #844
