### ISSUE TITLE
code generation similar to CVXGEN?

### ISSUE THREAD

**Issue by PandaZejiang** [cvxgrp/cvxpy#795]
Hello.
I am using cvxpy 1.0.24 with Python 3.7.3 in Jupyter notebook under Windows 10.
My project is about controlling a RC car.
So, I formulate an MPC problem and then solve it in PC side and then send the optimal control to the RC car. This process is repeated again and again.
MPC formulation is always QP. OSQP solves the problem (very small scale: 2 states, 1 inputs) within 0.001s. However, the overall time (problem formulation + Compilation + Solve) exceeds more than 0.03s.
I am wondering how to speed up a little bit. For instance, CVXGEN does code generation. Can CVXPY do something similar?

Thanks.

**Comment by gbanjac** [comment]
OSQP has a code generation capability. Please see [here](https://osqp.org/docs/codegen/index.html) for more details.

Also, note that you can update the problem data without performing the `setup` function each time.

**Comment by bstellato** [comment]
As @gbanjac said, if you plan to put the solver on an embedded platform you can use the [OSQP codegen](https://osqp.org/docs/codegen/index.html) which creates a library-free binary with no dynamic memory allocation.

To speed things up for you at the moment, you need to write the QP matrices yourself in numpy. Check [this OSQP example](https://osqp.org/docs/examples/mpc.html).  I believe CVXPY 1.1 will support code generation making your life much easier in this regard.

**Comment by PandaZejiang** [comment]
Thanks for the info. @gbanjac  and @bstellato  
I'll have a try.

**Comment by PandaZejiang** [comment]
@gbanjac @bstellato 
Sorry to bother you guys again.

I do follow the OSQP python code generation example on OSQP website:

import osqp
import scipy.sparse as sparse
import numpy as np

P = sparse.csc_matrix([[4, 1], [1, 2]])
q = np.array([1, 1])
A = sparse.csc_matrix([[1, 1], [1, 0], [0, 1]])
l = np.array([1, 0, 0])
u = np.array([1, 0.7, 0.7])

prob = osqp.OSQP()

prob.setup(P, q, A, l, u, alpha=1.0)

But when I do code generation:
prob.codegen('code', parameters='matrices', python_ext_name='emosqp')

ERROR OCCURS:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-d00015ce467a> in <module>
     17 
     18 
---> 19 prob.codegen('code', parameters='matrices', python_ext_name='emosqp')

~\AppData\Local\Continuum\anaconda3\lib\site-packages\osqp\interface.py in codegen(self, folder, project_type, parameters, python_ext_name, force_rewrite, loop_unrolling)
    368         # Generate code with codegen module
    369         cg.codegen(work, folder, python_ext_name, project_type,
--> 370                    embedded, force_rewrite, loop_unrolling)
    371 
    372     def _linsys_solver_str_to_int(self, settings):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\osqp\codegen\code_generator.py in codegen(work, target_dir, python_ext_name, project_type, embedded, force_rewrite, loop_unrolling)
    175     module_name = glob('%s*' % python_ext_name + module_ext)
    176     if not any(module_name):
--> 177         raise ValueError('No python module generated! ' +
    178                          'Some errors have occurred.')
    179     module_name = module_name[0]

It seems like the 'module_ext' name was undefined?

Did you encounter the same issue before? 
Thanks!

**Comment by gbanjac** [comment]
I see that you opened an issue in the OSQP repository (https://github.com/oxfordcontrol/osqp/issues/177). Let's move the discussion there since this is not related to CVXPY.

**Comment by PandaZejiang** [comment]
Make sense @gbanjac 
Sorry about that.
