### ISSUE TITLE
cvxpy is unable to return (unpack) the solution when OSQP is the solver

### ISSUE THREAD

**Issue by semercim** [cvxgrp/cvxpy#798]
When I try to solve the same convex problem with CVXOPT, the result is returned. But if I use OSQP, the cvxpy is unable to return a solution and crashes.

Below I provide a small example

------------

import cvxpy as cvx
import numpy as np
Y = np.random.rand(28,1)
A = np.random.rand(28,30)
w = cvx.Variable((30, 1))
objective = cvx.Minimize(cvx.norm(A * w - Y, 1)  + 4 * cvx.norm(w[2:], 1))
constraints = []
prob = cvx.Problem(objective, constraints)
optimal_value = prob.solve(solver=cvx.CVXOPT, verbose=True) # work fine
optimal_value = prob.solve(solver=cvx.OSQP, verbose=True) . ##!! Crashes!!

----------------

I expect to see the result for both solvers. Since the verbose info messages show that OSQP does not crash, but the result is not returned by cvxpy.

**Output**
```
     pcost       dcost       gap    pres   dres   k/t
 0:  0.0000e+00  4.8580e-18  2e+02  3e+00  4e-15  1e+00
 1:  1.8767e+00  1.8812e+00  3e+01  5e-01  3e-15  2e-01
 2:  5.4813e+00  5.4862e+00  1e+01  2e-01  2e-15  6e-02
 3:  6.6654e+00  6.6685e+00  4e+00  6e-02  2e-15  2e-02
 4:  6.8620e+00  6.8658e+00  2e+00  3e-02  3e-15  1e-02
 5:  7.1436e+00  7.1445e+00  4e-01  6e-03  2e-15  3e-03
 6:  7.2005e+00  7.2009e+00  1e-01  2e-03  2e-15  1e-03
 7:  7.2249e+00  7.2250e+00  4e-02  6e-04  2e-15  3e-04
 8:  7.2331e+00  7.2332e+00  3e-03  5e-05  2e-15  3e-05
 9:  7.2339e+00  7.2339e+00  3e-05  5e-07  3e-15  3e-07
10:  7.2339e+00  7.2339e+00  3e-07  5e-09  3e-15  3e-09
Optimal solution found.

-----------------------------------------------------------------
           OSQP v0.5.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2018
-----------------------------------------------------------------
problem:  variables n = 88, constraints m = 114
          nnz(P) + nnz(A) = 1906
settings: linear system solver = qdldl,
          eps_abs = 1.0e-05, eps_rel = 1.0e-05,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on
iter   objective    pri res    dua res    rho        time
   1  -1.0198e+03   1.60e+01   8.22e+00   1.00e-01   3.85e-04s
 200   7.2301e+00   1.53e-03   9.22e-03   1.00e-01   2.38e-03s
 400   7.2442e+00   1.43e-03   1.13e-03   1.00e-01   4.25e-03s
 600   7.2355e+00   2.00e-04   1.17e-03   1.00e-01   6.13e-03s
 800   7.2330e+00   4.98e-04   5.31e-04   1.00e-01   7.99e-03s
1000   7.2374e+00   2.34e-04   3.73e-04   1.00e-01   9.97e-03s
1200   7.2354e+00   9.81e-05   8.69e-04   1.00e-01   1.19e-02s
1400   7.2313e+00   1.66e-04   5.74e-04   1.00e-01   1.38e-02s
1600   7.2310e+00   1.88e-04   2.54e-04   1.00e-01   1.59e-02s
1800   7.2334e+00   3.55e-05   6.59e-04   1.00e-01   1.77e-02s
2000   7.2408e+00   4.72e-04   2.55e-03   1.18e-01   1.52e-03s
2200   7.2133e+00   2.42e-03   1.07e-03   1.44e-02   6.57e-04s
2400   7.2410e+00   3.21e-04   4.51e-03   8.94e-02   1.57e-03s
2600   7.2489e+00   7.23e-04   2.11e-04   8.94e-02   3.37e-03s
2800   7.2363e+00   2.82e-04   1.89e-03   8.94e-02   5.20e-03s
3000   7.2290e+00   2.67e-04   1.20e-03   8.94e-02   7.00e-03s
3200   7.2282e+00   4.13e-04   1.01e-04   8.94e-02   8.85e-03s
3400   7.2312e+00   1.98e-04   1.05e-03   8.94e-02   1.08e-02s
3600   7.2389e+00   1.10e-03   2.73e-03   9.43e-02   1.11e-03s
3800   7.2269e+00   6.03e-04   2.33e-03   9.43e-02   2.89e-03s
4000   7.2262e+00   5.48e-04   9.08e-04   9.43e-02   4.88e-03s
4200   7.2278e+00   5.24e-04   9.28e-04   9.43e-02   6.67e-03s
4400   7.2333e+00   3.80e-05   1.79e-03   9.43e-02   8.39e-03s
4600   7.2397e+00   4.15e-04   9.73e-04   9.43e-02   1.01e-02s
4800   7.2400e+00   4.16e-04   6.98e-04   9.43e-02   1.19e-02s
5000   7.2344e+00   3.26e-05   1.48e-03   9.43e-02   1.36e-02s
5200   7.2292e+00   3.21e-04   7.83e-04   9.43e-02   1.54e-02s
5400   7.2510e+00   1.09e-03   2.25e-04   1.42e-02   1.03e-03s
5600   7.2425e+00   6.55e-04   1.01e-03   7.44e-02   8.28e-04s
5800   7.2349e+00   3.08e-04   1.60e-03   7.44e-02   2.54e-03s
6000   7.2288e+00   3.79e-04   1.13e-03   7.44e-02   4.48e-03s
6200   7.2264e+00   5.29e-04   2.31e-04   7.44e-02   6.17e-03s
6400   7.2311e+00   1.80e-04   1.28e-03   7.44e-02   7.89e-03s
6600   7.2380e+00   2.89e-04   1.00e-03   7.44e-02   9.55e-03s
6800   7.2169e+00   2.14e-03   4.23e-04   7.42e-03   6.23e-04s
7000   7.2455e+00   5.97e-04   3.04e-03   6.83e-02   1.42e-03s
7200   7.2490e+00   7.92e-04   4.56e-04   6.83e-02   3.12e-03s
7400   7.2357e+00   3.32e-04   1.67e-03   6.83e-02   4.70e-03s
7600   7.2280e+00   3.59e-04   1.04e-03   6.83e-02   6.53e-03s
7800   7.1961e+00   2.75e-03   2.04e-04   1.25e-02   6.23e-04s
8000   7.2378e+00   1.06e-03   6.17e-04   7.27e-02   2.04e-03s
8200   7.2384e+00   3.25e-04   1.04e-03   7.27e-02   3.62e-03s
8400   7.2323e+00   3.03e-04   1.30e-03   7.27e-02   5.15e-03s
8600   7.2267e+00   4.87e-04   2.31e-04   7.27e-02   6.68e-03s
8800   7.2296e+00   2.78e-04   9.73e-04   7.27e-02   8.21e-03s
9000   7.2288e+00   1.55e-03   3.35e-03   6.38e-02   7.85e-04s
9200   7.2253e+00   6.15e-04   8.87e-04   6.38e-02   2.26e-03s
9400   7.2276e+00   4.35e-04   2.88e-04   6.38e-02   3.74e-03s
9600   7.2311e+00   3.61e-04   6.57e-04   6.38e-02   5.15e-03s
9800   7.2349e+00   9.31e-05   8.00e-04   6.38e-02   6.54e-03s
10000   7.2384e+00   3.28e-04   2.67e-04   6.38e-02   7.93e-03s
status:               maximum iterations reached
number of iterations: 10000
run time:             7.95e-03s
optimal rho estimate: 1.09e-01
Traceback (most recent call last):
  File "/Users/semercim/.local/share/virtualenvs/semercim-_KJvTfDp/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-18-fe981c789f79>", line 1, in <module>
    optimal_value = prob.solve(solver=cvx.OSQP, verbose=True)
  File "/Users/semercim/.local/share/virtualenvs/semercim-_KJvTfDp/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 289, in solve
    return solve_func(self, *args, **kwargs)
  File "/Users/semercim/.local/share/virtualenvs/semercim-_KJvTfDp/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 574, in _solve
    self.unpack_results(solution, full_chain, inverse_data)
  File "/Users/semercim/.local/share/virtualenvs/semercim-_KJvTfDp/lib/python3.7/site-packages/cvxpy/problems/problem.py", line 717, in unpack_results
    "Try another solver, or solve with verbose=True for more "
cvxpy.error.SolverError: Solver 'OSQP' failed. Try another solver, or solve with verbose=True for more information.
```
 - OS: Macos Mojave 10.14.6 
 - CVXPY Version: 1.0.25
 - CVXOPT Version: 1.2.3
 - OSQP Version: 0.5.0

**Comment by bstellato** [comment]
Your code is not deterministic since it creates different matrices at each run. Can you try to set the seed that produces your error? I tried it with the CVXPY master and latest OSQP but I cannot reproduce the error even when OSQP reaches the maximum number of iterations.

**Comment by semercim** [comment]
Hi,

I have attached the real Y and A matrices I am using in my application. Similarly cvxopt solves but osqp crashes.

If the solver is the problem, at least I would expect cvxpy to return a warning instead of raising an error.

Best Regards

[Y.txt](https://github.com/cvxgrp/cvxpy/files/3566458/Y.txt)
[A.txt](https://github.com/cvxgrp/cvxpy/files/3566460/A.txt)


----------------------------------
import cvxpy as cvx
import numpy as np
Y = Y = np.loadtxt('Y.txt')  
Y = Y.reshape(-1,1) 
A = A = np.loadtxt('A.txt') 
w = cvx.Variable((53, 1))
objective = cvx.Minimize(cvx.norm(A * w - Y, 1) + 4 * cvx.norm(w[2:], 1))
constraints = []
prob = cvx.Problem(objective, constraints)
optimal_value = prob.solve(solver=cvx.CVXOPT, verbose=True) # work fine
optimal_value = prob.solve(solver=cvx.OSQP, verbose=True)  ##!! Crashes!!
------------------------------

**Comment by semercim** [comment]
Hi,

I have attached the real Y and A matrices I am using in my application. Similarly cvxopt solves but osqp crashes.

If the solver is the problem, at least I would expect cvxpy to return a warning instead of raising an error.

Best Regards


[A.txt](https://github.com/cvxgrp/cvxpy/files/3566468/A.txt)
[Y.txt](https://github.com/cvxgrp/cvxpy/files/3566470/Y.txt)
------------------------------------
import cvxpy as cvx
import numpy as np
Y = Y = np.loadtxt('Y.txt')
Y = Y.reshape(-1,1)
A = A = np.loadtxt('A.txt')
w = cvx.Variable((53, 1))
objective = cvx.Minimize(cvx.norm(A * w - Y, 1) + 4 * cvx.norm(w[2:], 1))
constraints = []
prob = cvx.Problem(objective, constraints)
optimal_value = prob.solve(solver=cvx.CVXOPT, verbose=True) # work fine
optimal_value = prob.solve(solver=cvx.OSQP, verbose=True) ##!! Crashes!!

**Comment by SteveDiamond** [comment]
Why would cvxpy return a warning? It raised an error because the solver couldn't solve the problem. Sometimes that happens.

**Comment by semercim** [comment]
Hmm.  It is my good wish/expectation to get the best result obtained until the max iteration, probably with some warning or status code, in case the solver does not converge to the optimum. But if the solver did not return a result at all, cvxpy should, of course, raise an error.

Additional info for any possible future reference: Experimentally, osqp solves this specific example inaccurately for some number of iterations (E.g. 60K), but fails at some other (E.g. 10K or 90K).

**Comment by SteveDiamond** [comment]
Ok, I understand what you're saying now. We try to return a solution with the ``_INACCURATE`` flag whenever the solution might be useful. But our assumption is that most people aren't necessarily checking the status, and returning a terrible solution would break their assumptions about cvxpy. I've been thinking about adding some sort of user specified tolerance, but that's hard to support with so many solvers.

Anyway, these bug reports are helpful and I appreciate your looking into this matter so thoroughly.

**Comment by SteveDiamond** [comment]
Closed due to lack of clear path to fix.
