### ISSUE TITLE
Remove dependency on six

### ISSUE THREAD

**Issue by wkschwartz** [cvxgrp/cvxpy#803]
Pip treats `six` as a requirement for cvxpy because of this line, which is the only **code** in the entire repository mentioning `six`:
https://github.com/cvxgrp/cvxpy/blob/27278d5f11957e43920f6d9ba3972f4bb25b11b4/setup.py#L72

Here are the only two lines in the **documentation** mentioning `six`:

https://github.com/cvxgrp/cvxpy/blob/bd74114a80130c432bfa63d3128bdd98b5c08ef0/doc/source/install/index.rst#L77
https://github.com/cvxgrp/cvxpy/blob/c9c7009362e6cb52e3871798cfcb2972c3e26013/README.md#L67

These are the only mentions of `six` in any **deploy scripts**.
https://github.com/cvxgrp/cvxpy/blob/8d6deba53c473017e6d47114d8d00207514cbc63/conda-recipe/meta.yaml#L15
https://github.com/cvxgrp/cvxpy/blob/8d6deba53c473017e6d47114d8d00207514cbc63/conda-recipe/meta.yaml#L33

That's it.* No real need to have pip install an extra package upon `pip install cvxpy`. Each of those mentions of `six` above can be removed to resolve this issue. (It looks like #544 attempted to remove the dependency on `six`, but missed some stuff.)

\* `git grep six` would verify this before merging a PR.

**Comment by SteveDiamond** [comment]
This is a nice catch. I tried removing six, but unfortunately we have something wrong in the build that we need to fix first.

**Comment by SteveDiamond** [comment]
Ok, everything looks good.
