### ISSUE TITLE
Installation Fails for python3 but not python2

### ISSUE THREAD

**Issue by baxelrodoverleaf** [cvxgrp/cvxpy#805]
I'm running a fairly fresh copy of ubuntu 18.04 and recently installed cxvpy but can't seem to get it to run in python 3. 

I installed cvxpy via pip and nosetests cvxpy passes (but skips 2 tests). I had to reinstall SCS after installing blas etc. via apt to get that to work. 

The following works in python 2.7.15rc1 but not python 3.6.8. 

`import cvxpy as cp`

Is this a known issue? Do you have advice on how I can fix this?

Thanks in advance!

**Comment by akshayka** [comment]
Hey, welcome to the CVXPY repo! We can't help you unless you post the complete error message you saw.

**Comment by baxelrodoverleaf** [comment]
Running it in the shell yields the following:

>>> import cvxpy as cp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cvxpy'
________________________________

**Comment by aszekMosek** [comment]
This is a long shot but have you installed cvxpy in python3? Your description only seems to mention you installing it for python2. These are separate installations to make.

**Comment by baxelrodoverleaf** [comment]
Thanks! That did it for me, what a silly error on my part.

**Comment by SteveDiamond** [comment]
It's ok. These issues are helpful for other people.
