### ISSUE TITLE
Couple of module errors when using cvxpy 0.4.10

### ISSUE THREAD

**Issue by fkan95** [cvxgrp/cvxpy#810]
Hi!
I'm trying to use cvxpy for semidefinite programming, but I got the error message  

> ImportError: cannot import name 'logsumexp'

The solution described  [here](https://github.com/cvxgrp/cvxpy/issues/640) seems to work.

But solving this error just leads me to the next error message:

> File "<ipython-input-5-24fd80cd53f1>", line 1, in <module>
>     runfile('C:/Users/flori/Simulator/ToyExample.py', wdir='C:/Users/flori/Simulator')
> 
>   File "C:\Users\flori\Anaconda3\envs\MyEnvironment\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "C:\Users\flori\Anaconda3\envs\MyEnvironment\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "C:/Users/flori/Simulator/ToyExample.py", line 2, in <module>
>     import cvxpy as cp
> 
>   File "C:\Users\flori\Anaconda3\envs\MyEnvironment\lib\site-packages\cvxpy\__init__.py", line 18, in <module>
>     from cvxpy.atoms import *
> 
>   File "C:\Users\flori\Anaconda3\envs\MyEnvironment\lib\site-packages\cvxpy\atoms\__init__.py", line 25, in <module>
>     from cvxpy.atoms.log_sum_exp import log_sum_exp
> 
>   File "C:\Users\flori\Anaconda3\envs\MyEnvironment\lib\site-packages\cvxpy\atoms\log_sum_exp.py", line 17, in <module>
>     import cvxpy.lin_ops.lin_utils as lu
> 
> AttributeError: module 'cvxpy' has no attribute 'lin_ops'

All this issus (and maybe more, after I've solved the present ones) occur, when I try to run the (easy) toy example from [here](https://www.cvxpy.org/examples/basic/sdp.html).

Since I've already used Anaconda and cvxopt for the same purpose on Win10  on another computer a few days ago, where everything worked fine (I did the installation the same way as I did it now on the new computer) there must be something wrong, but I can't find out what went wrong.

Can anybody help me?

Thank you very much in Advance!

PS: I'm using Python 3.6.9 :: Anaconda, Inc. on Windows 10

**Comment by akshayka** [comment]
What version of CVXPY are you using? Try upgrading to the latest version (1.0.25), if you're not using it already.

**Comment by fkan95** [comment]
Hi and thanks for your respond!

I am using cvxpy 0.4.10 and I've already tried to upgrade to the latest version via using

> conda update -n MyEnv -c cvxgrp cvxpy

but it still states afterwards, that cvxpy 0.4.10 is my current version. So this might be the problem...(?)

**Comment by akshayka** [comment]
Our recommended way of installing CVXPY is via pip. Please thoroughly uninstall CVXPY, and then follow the installation instructions at our website:

https://www.cvxpy.org/install/index.html#anaconda-installation

**Comment by fkan95** [comment]
Oh - good to know! I've tried it the way it already had worked a few days ago, but anyhow - now it works.

Thank you for your help!
