### ISSUE TITLE
[1.1] Performance

### ISSUE THREAD

**Issue by akshayka** [cvxgrp/cvxpy#814]
This is a tracking issue for the performance of 1.1 The objectives are

* match the performance (wall-time) of master for problems without variables;
* make the initial compilation of a problem with parameters within a factor of 5 for problems without parameters
* make subsequent compilations of a parameterized parameters substantially faster than compiling an equivalent non-parameterized problem

Key results include adding benchmarks and improving on them until the benchmarks are satisfied.

**Comment by akshayka** [comment]
Related commits:

* 95455901e9461c33548bce6d12326230c46ace93 [faster constraint formatting]
* e6a4e8a1f45d2ea0c84456b433067fb4faf914e3 [faster constraint formatting]
* 1fbe1f016674340b1b330a83875c433764bbeff4 [compilation flag]
* 899fb9bc11c5e488b06b9c32fed25fd1085ad840 [benchmark clean-up]
* bf78e484454884363b5f584acccab6342ce3f984 [add benchmarks]

**Comment by akshayka** [comment]
Failing tests (because they take too long):

```
TestBenchmarks.test_diffcp_sdp_example 

test_parameterized_cone_matrix_stuffing_with_many_constraints
```

It's important to get `TestBenchmarks.test_diffcp_sdp_example` working, because that tests a problem without parameters (so it works on master, and failing it would be a regression).

**Comment by akshayka** [comment]
@sbarratt looked into the performance of `test_diffcp_sdp_example`. On 1.1alpha, there are ~4K calls made to `LinOpOperations.cpp:sparse_reshape_to_vec` (see the attached photo). This doesn't happen on master (which is > 10x faster than master on this benchmark).

@SteveDiamond , do you know what changed? Note that this problem does not have any parameters.

![image](https://user-images.githubusercontent.com/1994308/65642490-38acf380-dfa4-11e9-8c06-28d6e1a77209.png)

**Comment by SteveDiamond** [comment]
I added a fast path for when the data in the multiplication canonicalization is a sparse or dense constant (versus an expression tree). This brought the runtime for ``test_diffcp_sdp_example`` down to ~7 seconds, which seems close enough to master to consider this issue resolved.
