### ISSUE TITLE
Possible incorrect sign on dual variable

### ISSUE THREAD

**Issue by dmicha16** [cvxgrp/cvxpy#824]
**Describe the bug**

Hey,

Earlier this year I've been working on some exercises with CVX Matlab for one of my math courses. I have tried to reproduce the same optimization problems in cvxpy, but I seem to get the wrong signs on the dual variables for corresponding equality constraints. I have good reason to belive the result I've obtained from Matlab.

**To Reproduce**
Below is an output from my juypter notebook.
```python
import numpy as np
import cvxpy as cp

x_1 = cp.Variable()
x_2 = cp.Variable()

obj = cp.Minimize(x_1**2 + x_2**2 + 5)
const = [x_1 - x_2 + 2 == 0,
         3*x_1 + 3*x_2 + 3 == 0]

prob = cp.Problem(obj, const)

prob.solve(verbose=True)

-----------------------------------------------------------------
           OSQP v0.5.0  -  Operator Splitting QP Solver
              (c) Bartolomeo Stellato,  Goran Banjac
        University of Oxford  -  Stanford University 2018
-----------------------------------------------------------------
problem:  variables n = 2, constraints m = 2
          nnz(P) + nnz(A) = 6
settings: linear system solver = qdldl,
          eps_abs = 1.0e-04, eps_rel = 1.0e-04,
          eps_prim_inf = 1.0e-04, eps_dual_inf = 1.0e-04,
          rho = 1.00e-01 (adaptive),
          sigma = 1.00e-06, alpha = 1.60, max_iter = 10000
          check_termination: on (interval 25),
          scaling: on, scaled_termination: off
          warm start: on, polish: on

iter   objective    pri res    dua res    rho        time
   1   0.0000e+00   3.00e+00   8.99e+02   1.00e-01   6.59e-05s
  50   2.5000e+00   4.31e-09   1.21e-08   1.00e-01   1.58e-04s
plsh   2.5000e+00   3.85e-16   1.15e-15   --------   2.51e-04s

status:               solved
solution polish:      successful
number of iterations: 50
optimal objective:    2.5000
run time:             2.51e-04s
optimal rho estimate: 5.89e-02

print("status:", prob.status)
print("optimal value", prob.value)
print("optimal var", x_1.value, x_2.value)
print(f"Lagrange Multipliers: {const[0].dual_value}, {const[1].dual_value}")
```

I'm hosting these problems on my github as well:
https://github.com/dmicha16/jupyter_math/blob/master/exercises_8.1c.ipynb
https://github.com/dmicha16/jupyter_math/blob/master/matrix_hw_cvxpy.ipynb

**Expected behavior**
Expected results: (From Matlab)
Minimizer with coordinates (-1.5, 0.5)
Function minima is 7.5
Lagrange multipliers lambda = (-2, -0.33333)

**Output**
status: optimal
optimal value 7.500000000000001
optimal var -1.5000000000000002 0.4999999999999999
Lagrange Multipliers: 1.9999999999999993, 0.33333333333333337

**Version**
 - OS: Ubuntu 16.04
 - CVXPY Version: 1.0.24
- Python: 3.7.3

**Additional context**
I have tried to go through all the different solvers installed by default in cvxpy, but all of them seems to give me the same result. Additionally, I have tried to look through all of the Advanced Features, where I might have made a mistake in setting up the problem, but I found no answers, and I can't seem to think that I might need anything like that, since these problems I'm using are rather simple. 

I've also looked through most of the issues posted before, and I found this one to be somewhat similar to my issue: https://github.com/cvxgrp/cvxpy/issues/591 --> "Below there is an example where the intro QP in the docs gives the wrong dual variables."

Thanks :slightly_smiling_face:, and I hope I didn't just make some small mistake somewhere..

David

**Comment by akshayka** [comment]
Hey @dmicha16 , thanks for your detailed report. The dual values look correct to me. Maybe you can double check my math?

The gradient of the Lagrangian with respect to (x_1, x_2) is

2(x_1, x_2) + nu_1(1, -1) + nu_2(3, 3).

When nu_1 = 2, nu_2 = 1/3, the above expression evaluates to 0 when x_1=-1.5 and x_2=0.5. So the returned values for the variables and dual variables are in fact optimal.

**Comment by dmicha16** [comment]
Hi @akshayka,

Thanks for your reply!

I think I might have found the culprit. Took me a day, sorry for the long reply time (I did your math too)!

**You are using this equation to test the KKT condition:**
```matlab
%% Your solution of the KKT condition:

f_gradient = [2 0; 0 2];
minimizers = [-1.5 0.5]';
A = [1 3;
    -1 3];
nu_1 = 2;
nu_2 = 1/3;


eq1 = f_gradient * minimizers + nu_1 * A(:,1) + nu_2 * A(:,end)
```

**Output**

```matlab
eq1 =
     0
     0
```

which does equal 0, just as you have said, only if you input the result from cvxpy with the positive nu_s. (2, 1/3). This equation does not equal zero if you use the matlab results (-2, -1/3). With these the output, it becomes `eq1 = -6 2`.

However, according to my book and my calculations I'm using this equation:
```matlab
%% My solution of the KKT condition based on the re:

f_gradient = [2 0; 0 2];
minimizers = [-1.5 0.5]';
A = [1 3;
    -1 3];
nu_1 = -2;
nu_2 = -1/3;

eq2 = f_gradient * minimizers + nu_1 * -A(:,1) + nu_2 * -A(:,end)
```
**Output**

```matlab
eq2 =
     0
     0
```

I'm using the book https://www.springer.com/gp/book/9780387711065 where on p286, 10.56, they specify the equation I've used.

On paper I construct this to get the results:
```matlab
gradient_f(x) - A'*nu = 0
                   Ax = b
```
In matrix form the above becomes:
```
[gradient_f(x) - A';
                 Ax]  * z = [0,0, -2 -3]'
```
where: `z =(z, nu)`
In matlab that becomes:
```matlab
C = [2 0 -1 -3;
    0 2 1 -3;
    1 -1 0 0;
    3 3 0 0]

z = [-1.5 0.5 -2 -1/3]'

C*z
```
Output:
```matlab
z =

  -1.500000000000000
   0.500000000000000
  -2.000000000000000
  -0.333333333333333
```

which also gives me the results for what I got from matlab cvx. So of course this just made me more confused? I don't have that much experience in convex optimization, so naturally this is quite confusing for me. This is what I meant from my ticket, that I don't think I would need to specify anything to compute the negative of eq1 which it seems to me what cvxpy is doing. Does this mean that both of them are correct, I'm not sure if it would make sense for the lagrangian multiplier since that would flip the direction the vector at the minimia (which is the same for matlab & cvxpy) but with the same magnitude?

Anyways, for clarity I'm also adding the matlab script I've used for my original results of (-2, -1/3) as well. I hope this helps clarify my issue a bit more.

```matlab
cvx_begin quiet
    
    variable x_1
    variable x_2
    
    f = x_1^2 + x_2^2 + 5;
    
    minimize(f)
    
    dual variable a1
    dual variable a2
    
    subject to
    a1 : x_1 - x_2 + 2 == 0
    a2 : 3*x_1 + 3*x_2 + 3 == 0
cvx_end

a1
a2
```

Output:
```matlab 
a1 = -2.000001518380772
a2 = -0.333333311290378
```

Thanks for taking the time and sorry again it took me so long to figure out what's up! :slightly_smiling_face: 

David

**Comment by akshayka** [comment]
We use the definition of the Lagrangian given in chapter 5 of https://web.stanford.edu/~boyd/cvxbook/. It seems like this definition differs from the definition in the book you're using, by the signs of the terms involving the dual variables. So if you use the definition from https://web.stanford.edu/~boyd/cvxbook/, then I believe the signs of the dual variables CVXPY returns are correct.

Does that make sense?

**Comment by dmicha16** [comment]
Yes of course. Thanks and sorry for the confusion.

Cheers!
