### ISSUE TITLE
cvcore.i SWIG interface is licensed under GPLv3

### ISSUE THREAD

**Issue by alexdyck** [cvxgrp/cvxpy#834]
Hello,

as I am really happy to use cvxpy, I was checking the commercial usability in terms of licensing. 

I found that the [SWIG interface file for cvxcore](https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/cvxcore/python/cvxcore.i) is licensed under GPLv3. 

As the corresponding __init__.py and all other files are licensed under the Apache 2.0 license, I wanted to ask whether this is on purpose or was not updated when switching cvxpy to the Apache 2.0 license.

If this file was overlooked, it would be great, to change the license paragraph of the file, so it becomes commercially usable without having to license my software under GPLv3.

Kind Regards,
Alex

**Comment by akshayka** [comment]
Interesting catch ... my guess is that it's a mistake. cvxcore is a fork of cvxcanon: https://github.com/cvxgrp/CVXcanon

@SteveDiamond , do you know whether the license is supposed to be Apache 2.0?

**Comment by SteveDiamond** [comment]
The license is supposed to be Apache 2.0. Let's change the file.
