### ISSUE TITLE
Getting False DCP error

### ISSUE THREAD

**Issue by amitpartani** [cvxgrp/cvxpy#840]
Windows OS: Python 3.6, CVXPY 1.0.24

I am trying to maximize cx - xAx with A being positive definite, but I am getting DCP error

I tried the problem using this data

A = np.array([[1595., 1098., 1133.,    0.,    0.,    0.,    0.],
       [1191., 1497., 1133.,    0.,    0.,    0.,    0.],
       [1191., 1098., 1396.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,  655.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0., 1313.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,  581.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,  536.]])

c = np.array([4673.36981266, 4727.12719741, 5939.49046907, 3867.69830799,
       6099.15146109, 5358.10885615, 4885.96523884])

x= cp.Variable(7)
prob = cp.Problem(cp.Maximize(-cp.quad_form(x,A)+c.T@x),[x>=0])
prob.solve()

I get DCP error with code above..

I then tried Minimize version which initially gave -inf as answer, but now also giving DCP error

prob = cp.Problem(cp.Minimize(cp.quad_form(x,A)-c.T@x),[x>=0])
prob.solve()

The actual optimal solution to Max (cx - xAx) is

np.array([0,0,2.134,2.903,2.359,4.6266,4.508])
with optimal value of 42586

**Comment by akshayka** [comment]
Your matrix `A` needs to be symmetric positive semidefinite, as documented here: https://www.cvxpy.org/tutorial/functions/index.html

**Comment by aadamson** [comment]
@akshayka  That matrix appears to be PSD:
```
>>> import numpy as np
>>> A = np.array([[1595., 1098., 1133., 0., 0., 0., 0.],
... [1191., 1497., 1133., 0., 0., 0., 0.],
... [1191., 1098., 1396., 0., 0., 0., 0.],
... [ 0., 0., 0., 655., 0., 0., 0.],
... [ 0., 0., 0., 0., 1313., 0., 0.],
... [ 0., 0., 0., 0., 0., 581., 0.],
... [ 0., 0., 0., 0., 0., 0., 536.]])
>>> A
array([[1595., 1098., 1133.,    0.,    0.,    0.,    0.],
       [1191., 1497., 1133.,    0.,    0.,    0.,    0.],
       [1191., 1098., 1396.,    0.,    0.,    0.,    0.],
       [   0.,    0.,    0.,  655.,    0.,    0.,    0.],
       [   0.,    0.,    0.,    0., 1313.,    0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,  581.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,  536.]])
>>> np.linalg.cholesky(A)
array([[39.9374511 ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [29.82163276, 24.65096792,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [29.82163276,  8.46499091, 20.85699279,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , 25.59296778,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , 36.23534186,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        24.10394159,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , 23.15167381]])
>>> from scipy.sparse.linalg import eigsh
>>> eigsh(A, k=A.shape[0], which='SA', return_eigenvectors=False)
array([ 300.32067852,  367.50533039,  536.        ,  581.        ,
        655.        , 1313.        , 3820.17399109])
```
