### ISSUE TITLE
Gurobi interface should set USER_LIMIT instead of SOLVER_ERROR if the solver stops due to time limit

### ISSUE THREAD

**Issue by pjssilva** [cvxgrp/cvxpy#847]
I am using Gurobi to solve a MIQP, it is a hard problem and takes long time to close the gap. But the solver finds good quality solutions soon, so I want to use the time limit to stop the optimization and retrieve the best feasible solution. Unfortunately when stopping due to time limit the Gurobi interface flags it as a SOLVER_ERROR instead of USER_LIMIT.

I believe USER_LIMIT is a better description of the result and it also closer to the behavior of the Cplex interface.

I could ignore SOLVER_ERROR in my code, but this does not seem right and may be even risky as I might not actually get a real error.

**Comment by SteveDiamond** [comment]
We don't have a user limit flag. We've discussed extending the solving statuses, and this is a good example to keep in mind.

**Comment by pjssilva** [comment]
Sorry, I don't understand what you mean by "we" in your answer. You can find USER_LIMIT defined in cvxpy.settings and this is the constant used by Cplex interface to flag this situation. Actually, the change I suggest would be minimal. I can submit a pull request if you think it is appropriate. The idea is basically change the line 39 of gurobi_qpif.py from
                  9: s.SOLVER_ERROR,
to
                  9: s.USER_LIMIT,

Something similar should be done in line 47 of gurobi_conif.py. But there code 9 is mapped to  s.OPTIMAL_INACCURATE which is odd unless you check if a feasible solution was found in the time limit. I am not sure what would be appropriate in this file.

**Comment by SteveDiamond** [comment]
The developers of cvxpy. I meant the discussion in #735 . I agree that OPTIMAL_INACCURATE is a poor choice in the abstract, but may be the best choice available. The alternative was to introduce a new solver code USER_LIMIT, or rearchitect the status codes to support more types.
