### ISSUE TITLE
logistic regression example fails using MOSEK on 1.1.0a1

### ISSUE THREAD

**Issue by sbarratt** [cvxgrp/cvxpy#848]
**Describe the bug**
The logistic regression example on the website using the MOSEK solver
fails on cvxpy 1.1alpha, but passes on cvxpy 1.0.25.

**To Reproduce**
```python
import cvxpy as cp
import numpy as np

np.random.seed(0)
n = 5
m = 50
def sigmoid(z):
    return 1/(1 + np.exp(-z))

beta_true = np.array([1, 0.5, -0.5] + [0]*(n - 3))
X = (np.random.random((m, n)) - 0.5)*10
Y = np.round(sigmoid(X @ beta_true + np.random.randn(m)*0.5))

X_test = (np.random.random((2*m, n)) - 0.5)*10
Y_test = np.round(sigmoid(X_test @ beta_true + np.random.randn(2*m)*0.5))

beta = cp.Variable(n)
log_likelihood = cp.sum(
    cp.multiply(Y, X @ beta) - cp.logistic(X @ beta)
)
problem = cp.Problem(cp.Maximize(log_likelihood/n - 0.1 * cp.sum_squares(beta)))

problem.solve(solver=cp.SCS) # works on both versions
problem.solve(solver=cp.MOSEK) # works on 1.0.25, fails on 1.1alpha
```

**Expected behavior**
I expect MOSEK to work, as it does in 1.0.25.

**Output**
```bash
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-4-c1410c742f67> in <module>
----> 1 problem.solve(solver=cp.MOSEK)

~/miniconda3/envs/cvxpy1.1alpha/lib/python3.7/site-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    300         else:
    301             solve_func = Problem._solve
--> 302         return solve_func(self, *args, **kwargs)
    303 
    304     @classmethod

~/miniconda3/envs/cvxpy1.1alpha/lib/python3.7/site-packages/cvxpy/problems/problem.py in _solve(self, solver, warm_start, verbose, gp, qcp, **kwargs)
    586         data, solving_chain, inverse_data = self.get_problem_data(solver, gp)
    587         solution = solving_chain.solve_via_data(
--> 588             self, data, warm_start, verbose, kwargs)
    589         self.unpack_results(solution, solving_chain, inverse_data)
    590 

~/miniconda3/envs/cvxpy1.1alpha/lib/python3.7/site-packages/cvxpy/reductions/solvers/solving_chain.py in solve_via_data(self, problem, data, warm_start, verbose, solver_opts)
    290         """
    291         return self.solver.solve_via_data(data, warm_start, verbose,
--> 292                                           solver_opts, problem._solver_cache)

~/miniconda3/envs/cvxpy1.1alpha/lib/python3.7/site-packages/cvxpy/reductions/solvers/conic_solvers/mosek_conif.py in solve_via_data(self, data, warm_start, verbose, solver_opts, solver_cache)
    385             rows = np.arange(i, i + total_soc_exp_slacks).tolist()
    386             cols = np.arange(j, j + total_soc_exp_slacks).tolist()
--> 387             task.putaijlist(rows, cols, [1] * total_soc_exp_slacks)
    388 
    389         # constraint index; start of LMIs.

~/miniconda3/envs/cvxpy1.1alpha/lib/python3.7/site-packages/mosek/__init__.py in putaijlist(self, _arg2_subi, _arg3_subj, _arg4_valij)
   7793       if res != 0:
   7794         result,msg = self.__getlasterror(res)
-> 7795         raise Error(rescode(res),msg)
   7796 
   7797     def putacol(self,_arg1_j,_arg3_subj,_arg4_valj): # 3

Error: (1204) The index value 156 occurring in argument 'subi' is too large.
```

**Version**
 - OS: Ubuntu 18.04 bionic
 - CVXPY Version: `1.1alpha`

**Comment by akshayka** [comment]
My guess is that it has something to do with the exponential cone. I sometimes test MOSEK locally, but my version of MOSEK doesn't support the exponential cone. We don't test MOSEK on CI.

**Comment by aszekMosek** [comment]
Looking at the input MOSEK interface gets I think the interpretation of ``dims[s.EXP_DIM]`` may have changed. In 1.0.25 it is

```
[150, 150]
```

and in 1.1.alpha:

```
100
```

I think in many places a multiplication by 3 may be necessary, and also increasing the length of ``s.H``? I have not been able to investigate the source of this.

**Comment by akshayka** [comment]
Thanks for looking into this, @aszekMosek. I ported the interface in the alpha update, and I must've done something wrong. Most of the CVXPY developers don't use MOSEK directly, so it's not simple for us to debug what's wrong. 

We'd really appreciate it if you could help us with this! If you look at the git history for `mosek_conif.py`, for example, it might be obvious to you what incorrect change was made. The latest pre-release version is [1.1.0a1](https://pypi.org/project/cvxpy/1.1.0a1/).

**Comment by aszekMosek** [comment]
@akshayka I'll do my best. It would help to know what the intended interpretation of ``dims[s.EXP_DIM]`` is before it even reaches the solver interface. Is it the number of exp cones, for instance, or their total dimension?

**Comment by rileyjmurray** [comment]
I have this fixed. It'll be in my next PR. @aszekMosek, since that PR will also contain a lot of code related to a support function implementation, it would be okay to essentially copy my changes to mosek_conif.py and make a separate PR for that. That way the MOSEK fix could be expedited.

**Comment by rileyjmurray** [comment]
This is resolved on master.
