### ISSUE TITLE
DOC: https://www.cvxpy.org/tutorial/dcp/index.html

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#850]
It is written "If the expression is written as norm(vstack(1, x), 2)...", but the following code actually uses hstack.   Ok, it makes no difference, but this could confuse some people.

Also, there is an abuse of TeX when writing $f(expr_i,...)$ etc.  You can't write a word in mathmode - the spacing is all wrong.   It should probably be something like $f(\text{\textit{expr}}_i,...)$.

**Comment by akshayka** [comment]
Thanks! We'll fix the first one ourselves.

You're definitely right about the TeX being incorrect. Want to file a pull request? (Edit doc/source/tutorial/dcp/index.rst)
