### ISSUE TITLE
OSQP solver does not accept initial variable values with warm start

### ISSUE THREAD

**Issue by edbarton1** [cvxgrp/cvxpy#854]
In some other issue responses, it has been suggested that starting values can be supplied to a solver by setting the values of variables before solving, and setting warm_start=True, for solvers that support warm start.  For the OSQP solver, warm start is supported and at the low level the solver can accept initial values, but setting variable values before calling the solver does not cause them to be used for an initial warm start.  Warm start with the OSQP interface currently works only for repeated solves with the same problem object, not for supplying an initial guess.  It appears that this could work, but is not implemented.

[no-initial-start-with-osqp.zip](https://github.com/cvxgrp/cvxpy/files/3784687/no-initial-start-with-osqp.zip)

The following is the output from the attached example, which runs OSQP on a problem that has been simplified to be a pure LP.  We can see that warm start works between runs, and that supplying a set of optimal variable values at the low level usually causes the number of iterations to be much smaller than a full solve (not on every run though), but trying to supply the suggested values through the values of the variables does not work.  (I assume that the difference in objective value is because I have not figured out how to inject the values into the normal process that would include an unpacking step.)

This is running on Ubuntu with cvxpy 1.0.25.

-- Find a solution for this simplified LP-only problem:
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
-- With freshly created problems, we may see variation but the iteration count is high:
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 28475 iterations
fresh problem: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem: optimal, objective -6752.7757895248415, 28475 iterations
-- With reusing the same problem for warm start, the iteration count is tiny as expected:
reused problem: optimal, objective -6752.775789524827, 25 iterations
reused problem: optimal, objective -6752.775789524774, 25 iterations
reused problem: optimal, objective -6752.775789524785, 25 iterations
reused problem: optimal, objective -6752.775789524899, 25 iterations
reused problem: optimal, objective -6752.775789524937, 25 iterations
reused problem: optimal, objective -6752.775789524898, 25 iterations
reused problem: optimal, objective -6752.775789524795, 25 iterations
reused problem: optimal, objective -6752.775789524822, 25 iterations
reused problem: optimal, objective -6752.775789524884, 25 iterations
reused problem: optimal, objective -6752.775789524901, 25 iterations
-- Trying to supply initial values through initial warm start is not effective:
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 28475 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
fresh problem with xsol: optimal, objective -6752.7757895248415, 14500 iterations
-- The low-level interface has similar behavior to freshly created problems:
fresh problem low-level: solved, objective -6910.584676696744, 14500 iterations
fresh problem low-level: solved, objective -6912.147878322633, 28475 iterations
fresh problem low-level: solved, objective -6910.584676696744, 14500 iterations
fresh problem low-level: solved, objective -6910.584676696744, 14500 iterations
fresh problem low-level: solved, objective -6912.147878322633, 28475 iterations
fresh problem low-level: solved, objective -6910.584676696744, 14500 iterations
fresh problem low-level: solved, objective -6912.147878322633, 28475 iterations
fresh problem low-level: solved, objective -6910.584676696744, 14500 iterations
fresh problem low-level: solved, objective -6910.584676696744, 14500 iterations
fresh problem low-level: solved, objective -6910.584676696744, 14500 iterations
-- The low-level interface accepts the initial solution and usually does fewer iterations:
fresh problem with xsol low-level: maximum iterations reached, objective -9918.64547338846, 30000 iterations
fresh problem with xsol low-level: maximum iterations reached, objective -9918.64547338846, 30000 iterations
fresh problem with xsol low-level: solved, objective -6696.279108862777, 4225 iterations
fresh problem with xsol low-level: solved, objective -6696.279108862777, 4225 iterations
fresh problem with xsol low-level: solved, objective -6696.279108862777, 4225 iterations
fresh problem with xsol low-level: solved, objective -6696.279108862777, 4225 iterations
fresh problem with xsol low-level: solved, objective -6696.279108862777, 4225 iterations
fresh problem with xsol low-level: solved, objective -6696.279108862777, 4225 iterations
fresh problem with xsol low-level: maximum iterations reached, objective -9918.64547338846, 30000 iterations
fresh problem with xsol low-level: solved, objective -6696.279108862777, 4225 iterations

**Comment by edbarton1** [comment]
When I hacked it in a way that handles my simple problem shape (don't know enough to do it correctly):

fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 7400 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 7400 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations
fresh problem with xsol hacked: optimal, objective -6752.7757895248415, 4225 iterations

**Comment by edbarton1** [comment]
Looking at the code, it appears that the values would need to be carried along in the application of the reduction steps because the inverse-mapping mechanism is designed to map back values rather than locations within the solver variable vector.  I could be wrong.

**Comment by SteveDiamond** [comment]
@edbarton1 the idea that the variable .value fields should supply a warm start for OSQP or any other solver is only something we've discussed. It's not implemented. Could you merge this with the discussion in #849?
