### ISSUE TITLE
DCP Analyzer down again

### ISSUE THREAD

**Issue by bonakdarf92** [cvxgrp/cvxpy#861]
It seems to me that the Website https://dcp.stanford.edu/analyzer is down again (https://github.com/cvxgrp/cvxpy/issues/636). I need to depict the tree for my thesis.

Tried it within 3 hours multiple times.

Suggestion for upcoming versions:
Could it be possible to ship the code which generates the tree in cvxpy as analyzes tool?

**Comment by SteveDiamond** [comment]
Ok sorry about this. I'm not sure why it keeps going down. I'll look into a long term solution. I got it up again.

**Comment by SteveDiamond** [comment]
If anyone has suggestions for how to set up
