### ISSUE TITLE
DCPError("Problem does not follow DCP rules. Specifically:\n" + append) raised when using SCS solver

### ISSUE THREAD

**Issue by jordan8409212** [cvxgrp/cvxpy#863]
Here is my code script, I'm using cvxpy and trying to solve a pseudo convex problem:
    
    def Psi(p_j, user):  # p_j is a (4, 1) vector
        # print(np.sum(betalin[:, user]))
        psi_i = alpha[user] / (1 + np.sum(beta[:, user] * p_j))
        return psi_i

    def f(p):
        w = np.ones((1, 4))
        obj = np.zeros((4, 1))
        for user in range(p.shape[0]):
            psi_i = Psi(p, user)
            obj[user] = np.log2(1 + (psi_i * p[user])) / (mu * p[user] + Pc)
            #  print(obj[user])
        obj = float(w @ obj)
        return obj

    def R(p):
        rate = np.zeros((4, 1))
        for user in range(p.shape[0]):
            psi_i = Psi(p, user)
            rate[user] = np.log2(1 + (psi_i * p[user]))
        return rate

    def mygradR(p):
        chp = h.T * p
        alphap = np.diag(chp)
        sumbetap = np.sum(chp, axis=-1) - alphap
        ln2 = np.log(2)
        term1 = 1 / ln2 * (1 + alphap / (1 + sumbetap)) ** (-1)  # (4,)
        term2 = (-1) * alphap * h / (1 + sumbetap) ** 2  # (4, 4)
        grad = (term1 * term2).T
        didx = np.diag_indices_from(grad)
        # print(np.diag_indices_from(grad))
        # print(term1 * (alphap / p) / (1 + sumbetap))
        grad[didx] = term1 * np.diag(h) / (1 + sumbetap)
        return grad

    def mygradf(p):
        gr = mygradR(p)
        den = 1 / (mu * p + Pc)
        gr = gr * den
        didx = np.diag_indices_from(gr)
        gr[didx] = gr[didx] - (mu * R(p).reshape(4, ) * den ** 2)
        gr = np.sum(gr, axis=0)
        return gr

    cnt = 0
    obj = f(pt)
    while True:
        cnt += 1
        grad = mygradR(pt)
        didx = np.diag_indices_from(grad)
        grad[didx] = 0

        chp = h.T * pt
        alphap = np.diag(chp)
        sumbetap = np.sum(chp, axis=-1) - alphap
        # Constants in EE tilde(pt is known, pvar is unknown)
        denominator = 1.0 / (mu * pt + Pc)

        c1 = np.sum(grad * denominator, axis=-1)
        c2 = -mu * np.log2(1 + alphap / (1 + sumbetap)) * denominator ** 2
        c = c1 + c2

        d = -c * pt

        # solve inner problem
        pvar = cp.Variable(4)
        obj_nl = cp.log(cp.multiply(1 + alphap / (1 + sumbetap), pvar)) / np.log(2) * denominator
        obj_l = cp.multiply(c, pvar)

        objective = cp.Maximize(cp.sum(obj_nl + obj_l + d))
        constraints = [0 <= pvar, pvar <= Pmax]
        prob = cp.Problem(objective, constraints)
        print("problem is DCP:", prob.is_dcp())
        try:
            prob.solve(solver=cp.SCS)
        # There are different solver we can use in CVXPY
        except cp.SolverError:
            print('SCS failed')
            try:
                prob.solve(solver=cp.CVXOPT, verbose=True)
            except cp.SolverError:
                print('cvxopt also failed')
                try:
                    prob.solve(solver=cp.MOSEK, verbose=True)
                except cp.SolverError:
                    print('MOSEK also failed')
                    break

        # calculate gradient step
        Bpt = pvar.value - pt
        gamma = 1

        old_obj = obj  # f(pt)
        old_pt = pt
        # @ is inner product, can use np.dot(mygradf(pt), Bpt) as well
        while f(pt + gamma * Bpt) < old_obj + parm_alpha * gamma * mygradf(pt) @ Bpt:
            gamma *= parm_beta  # reduce the magnitude of gamma

        pt += gamma * Bpt
        obj = f(pt)
        # Break when the
        # Ignore when division by zero
        with np.errstate(divide='ignore'):
            # np.linalg.norm(x, np.inf) calculate the infinite norm of x. i.e. max(sum(abs(x), axis=1)
            if abs(obj / old_obj - 1) < RelTolObj and np.linalg.norm(pt - old_pt, np.inf) / np.linalg.norm(pt,
                                                                                                           np.inf) < RelTolVal:
                break

        if cnt > MaxIter:
            print('MaxIter')
            break

    return obj, pt

It seems OK at the first few iterations, I've print out the message to see if my problem formulation follows the DCP rule.
![image](https://user-images.githubusercontent.com/43395802/68286965-e7bd0e80-00bc-11ea-8771-80963f1aa8da.png)
But after I get the following error:
![image](https://user-images.githubusercontent.com/43395802/68287063-11763580-00bd-11ea-8d80-bfc5a1d61315.png)
![image](https://user-images.githubusercontent.com/43395802/68287137-323e8b00-00bd-11ea-9f11-d1c87b71e69a.png)

**Version**
 - OS: Ubuntu 16.04 LTS
 - CVXPY Version: 1.0.25

Thanks for help!

**Comment by SteveDiamond** [comment]
You can't multiply log elementwise by a mix of positive and negative values. This has unknown curvature. You need to be multiplying by all positive numbers or all negative numbers (technically non-negative and non-positive).

**Comment by 670555467** [comment]
> You can't multiply log elementwise by a mix of positive and negative values. This has unknown curvature. You need to be multiplying by all positive numbers or all negative numbers (technically non-negative and non-positive).

How should we finally solve this problem？
