### ISSUE TITLE
Efficient MPC formulation to reduce compilation time

### ISSUE THREAD

**Issue by PandaZejiang** [cvxgrp/cvxpy#864]
**Describe the bug**
Hello. I am using CVXPY for a project. For a system with 1 state and 1 input, with prediction step Hp = 10 and Control Step Hc = 1, the formulated problem needs less than 0.001s to be solved with OSQP. However, the overall execution time is around 0.05s, which is even larger than the required simpling time of the controlled plant. 

The MPC is formulated as below:

### cvx throttle variables
    x_throttle = cp.Variable(Hp_throttle+1)                              # (1, )
    u_throttle = cp.Variable(Hp_throttle)                                # (1, )
     
    ### CVX Throttle Problem Formulation
    objective_throttle = 0
    constraints_throttle = [x_throttle[0] == vx0]
    
    for k in range(Hp_throttle):
        objective_throttle += Q_throttle*cp.sum_squares((x_throttle[k+1]-vxr_vec[k+1])) + Input_weight_throttle[k]*cp.sum_squares(u_throttle[k])
        constraints_throttle += [x_throttle[k+1] == Ak_throttle*x_throttle[k] + Bk_throttle*u_throttle[k]+dk_vx]
    
    constraints_throttle += [u_throttle[0:Hc_throttle]<=delta_throttle_max, u_throttle[0:Hc_throttle]>=delta_throttle_min, u_throttle[Hc_throttle:] == 0,
                Throttle_last+u_throttle[0]<=throttle_max, Throttle_last+u_throttle[0]>=throttle_min]
        
    QP_throttle = cp.Problem(cp.Minimize(objective_throttle), constraints_throttle)

**Expected behavior**
May I kindly ask if there is any way to reformulate the problem above to reduce the compilation time? Indeed, I did try to use vectorization above.

**Version**
 - OS:  Win10
 - CVXPY Version: 1.0.24

**Additional context**
The desktop where cvxpy runs is with Intel i5-6500 with 12G memory.

Thank you.

**Comment by SteveDiamond** [comment]
Try something like:
```
objective_throttle = Q_throttle*cp.sum_squares(x_throttle[1:]-vxr_vec[1:]) + Input_weight_throttle@cp.squares(u_throttle)
constraints_throttle = [x_throttle[1:] == Ak_throttle*x_throttle[:-1] + Bk_throttle*u_throttle[:]+dk_vx]

constraints_throttle += [u_throttle[0:Hc_throttle]<=delta_throttle_max, u_throttle[0:Hc_throttle]>=delta_throttle_min, u_throttle[Hc_throttle:] == 0,
            Throttle_last+u_throttle[0]<=throttle_max, Throttle_last+u_throttle[0]>=throttle_min]
    
QP_throttle = cp.Problem(cp.Minimize(objective_throttle), constraints_throttle)
```
This may need a little tweaking. At some point we'll also have fast parameterized problems for QPs on the alpha branch, so it won't really matter how you formulate the problem if you're solving it multiple times.

**Comment by PandaZejiang** [comment]
Hi Steve,  thank you!
Yes, we need to replace the 'cp.squares' by quad_form as cp.squares is not supported.
I achieve 5 times speed.

May I ask you again if right now 

x_throttle = cp.Variable(2, Hp_throttle+1)                              # a matrix  instead of a vector
u_throttle = cp.Variable(Hp_throttle) 

How to change the following line accoridngly? 
constraints_throttle = [x_throttle[1:] == Ak_throttle*x_throttle[:-1] + Bk_throttle*u_throttle[:]+dk_vx]

Thanks again!

**Comment by PandaZejiang** [comment]
Oh, I think it should be somehow like
x_steer[:,1:] == Ad_steer*x_steer[:,:-1] + Bd_steer*u_steer[:,:]+dk_steer

**Comment by PandaZejiang** [comment]
Ohmmm, it does not work. Please help thanks !

**Comment by SteveDiamond** [comment]
From now on I'm kicking questions like this to stackoverflow. I don't think there's much benefit from answering them here.
