### ISSUE TITLE
passing in mosek parameters

### ISSUE THREAD

**Issue by jask1** [cvxgrp/cvxpy#868]
I am trying to set "mosek_param" settings, but, am getting errors. For instance, for the following case

> MSK_IPAR_INTPNT_SOLVE_FORM
> 
> Controls whether the primal or the dual problem is solved.
> Default:
>   "FREE"
> Accepted:
>   "FREE", "PRIMAL", "DUAL"
> Example:
>   param.MSK_IPAR_INTPNT_SOLVE_FORM = 'MSK_SOLVE_FREE'
> Groups:
>   Interior-point method

from https://docs.mosek.com/9.0/toolbox/parameters.html --> I tried

> prob.solve(solver=MOSEK,
> mosek_params={mosek.iparam.intpnt_solve_form: mosek.solve.primal},   
> verbose=True)

but, run into errors. 

When I was working in Matlab --> using
`cvx_solver_settings('MSK_IPAR_INTPNT_SOLVE_FORM','MSK_SOLVE_PRIMAL')`
worked well for me. But, doesn't work in the present case. Also, I was able to set precision as follows
`cvx_precision low`
but, cannot do so now. Is there another way to do both of these in cvxpy? thank you.

**Comment by aszekMosek** [comment]
https://stackoverflow.com/questions/58846453/mosek-parameter-settings-in-cvxpy/58863821#58863821 contains an answer

**Comment by rileyjmurray** [comment]
The answer linked by @aszekMosek seems adequate for this question. There is no global way to set precision (such as ``cvx_precision low``) within cvxpy. You have to do this on a solver-by-solver basis, with keyword arguments tailored to that solver (as mentioned in the stackoverflow link).
