### ISSUE TITLE
Problem.status in None in DCCP

### ISSUE THREAD

**Issue by keithbriggs** [cvxgrp/cvxpy#873]
According to https://www.cvxpy.org/api_reference/cvxpy.problems.html, status has to be a string and one of optimal, infeasible, or unbounded.    But with solver='dccp', I'm often getting a None value (apparently when the solver has failed, since constraints are violated).   What could cause this?

Also, the same webpage still uses python2 print statements in the examples.

Also, I'm not sure what's meant by the strange punctuation in "Populates the .status’, `.value".

**Comment by keithbriggs** [comment]
In fact even the first DCCP example has this problem:

import cvxpy as cvx   
import dccp
x = cvx.Variable(2)
y = cvx.Variable(2)
myprob = cvx.Problem(cvx.Maximize(cvx.norm(x-y,2)), [0<=x, x<=1, 0<=y, y<=1])
print("problem is DCP:", myprob.is_dcp())   # false
print("problem is DCCP:", dccp.is_dccp(myprob))  # true
result = myprob.solve(method = 'dccp')
print("x =", x.value)
print("y =", y.value)
print("cost value =", result[0])
print("status =",myprob.status) # prints "None"
print("status =",myprob._status) # prints "None"

**Comment by akshayka** [comment]
DCCP is not a part of CVXP; it’s a separate package (that we don’t maintain). The DCCP repo is the appropriate place to file this issue.

**Comment by keithbriggs** [comment]
Ok, but these two points are relevant to cvxpy:


Also, the same webpage still uses python2 print statements in the examples.


Also, I'm not sure what's meant by the strange punctuation in "Populates the .status', `.value".



Keith
________________________________

**Comment by akshayka** [comment]
Thanks! We’ll fix those.
