### ISSUE TITLE
Canonicalization can enforce symmetry constraints poorly

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#877]
There are several places in cvxpy's canonicalization that enforce symmetry of a matrix expression by writing ``expr.T == expr``. This is a bad way to enforce symmetry, because the diagonal terms are always trivially satisfied, and the off-diagonal terms are duplicated. If people use a commercial solver like MOSEK, then a presolve phase should eliminate such constraints. However when using SCS there is no such presolve phase, and warnings are often printed about empty rows or columns of a sparse matrix. Problem size (and likely problem conditioning) can be improved by enforcing symmetry in a more careful way.

We should go though all SDP-representable dcp2cone canon methods, and identify when something like ``expr.T == expr`` is written. (One such place is https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/dcp2cone/atom_canonicalizers/lambda_max_canon.py.)

From there, we should make two changes. First, check if ``expr.is_symmetric() == True``; in this case, don't add any equality constraints for the symmetry. If instead ``expr.is_symmetric == False``, then we should add the *minimum* number of equality constraints (``n * (n-1) // 2``) needed to enforce symmetry.

**Comment by rileyjmurray** [comment]
Turns out I was conflating a couple different inefficient practices in canonicalization. For the specific pattern ``expr.T == expr``, this only occured in ``lambda_max_canon``. I've resolved this on my fork by writing ``upper_tri(expr) == upper_tri(expr.T)``, using the existing ``upper_tri`` affine atom.

I still think that ``sigma_max_canon``, ``log_det_canon``, and ``normNuc_canon`` canonicalize matrix expressions inefficiently. They introduce additional Variable objects (e.g. ``X = Variable(shape=(n+m, n+m), PSD=True)``) and extremely simple equality constraints on the entries of that Variable object. @SteveDiamond @akshayka, before I make a PR: would you be open to me making changes for these three methods, or would you prefer I restrict changes to ``lambda_max_canon``?

**Comment by akshayka** [comment]
Riley, we’d very much welcome a PR for all of those canonicalizers.

**Comment by rileyjmurray** [comment]
Note for this thread: also changed ``matrix_frac_canon``.

**Comment by rileyjmurray** [comment]
Closed by merged PR.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
