### ISSUE TITLE
Update NAG interface for cvxpy 1.1

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#884]
The NAG interface (created through PR #776) relies on one or more functions from the ``ConicSolver`` class which were removed from cvxpy, in the switch from version 1.0 to 1.1. In particular, ``NAG.block_format`` is broken, because ``ConicSolver.format_constr`` does not exist anymore.

From what I can tell, the NAG apply() function was modeled off the MOSEK apply() function. With that in mind, many of the necessary changes to the current NAG interface can be identified by following https://github.com/cvxgrp/cvxpy/commit/badc0a79701da0785acaaf994b9d072bafb64efb#diff-209669af1b5a91178295a651bbea34f3. (That commit wasn't perfect though; exponential cone changes were needed in https://github.com/cvxgrp/cvxpy/pull/862.)

**Comment by akshayka** [comment]
Thanks for opening this, Riley!

The NAG developers are welcome to submit a PR to update the interface. NAG is a commercial solver; we don't test it in CI.

**Comment by rileyjmurray** [comment]
Making a note before I close this issue.

Steven attempted to get NAG working on 1.1, but wasn't successful (https://github.com/cvxgrp/cvxpy/issues/913#issuecomment-582197969). The lack of readily available academic or trial licenses makes it unrealistic for us to support NAG on our own. Since no NAG users or developers stepped up to tackle this issue, we've opted to remove NAG support in the CVXPY 1.1 release (https://github.com/cvxgrp/cvxpy/issues/913#issuecomment-582222934).

We'll update https://github.com/cvxgrp/cvxpy/blob/master/CONTRIBUTING.md to provide guidance on contributing solver interfaces (commercial or otherwise) in the future.

**Comment by shuanghuabai** [comment]
Hi, now the NAG interface has been updated #967. Thanks a lot!
