### ISSUE TITLE
Parameter verification bug with `np.bool` arrays

### ISSUE THREAD

**Issue by vidakDK** [cvxgrp/cvxpy#888]
**Describe the bug**
Trying to pass a Numpy array of `bool` values to a CVXPY Parameter fails.

**To Reproduce**
```
import cvxpy as cp
import numpy as np
p = cp.Paramter(2)
val = np.array([True, False])
p.value = val  # fails here
```

**Expected behavior**
Set the value of `p` to `val`. If needed convert it to int.

**Output**
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/vidak.kazic/.virtualenvs/colours-reduce/lib/python3.7/site-packages/cvxpy/expressions/constants/parameter.py", line 63, in value
    self._value = self._validate_value(val)
  File "/Users/vidak.kazic/.virtualenvs/colours-reduce/lib/python3.7/site-packages/cvxpy/expressions/leaf.py", line 383, in _validate_value
    delta = np.abs(val - projection)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Version**
 - OS: macOS Catalina (10.15.1)
 - CVXPY Version: `1.0.24`

**Additional context**
If we do `p.value = val.astype(int)` everything works, but I feel we should fix the error. 

I would be happy to try and make a PR if you guys want, but would need to look more into how the projection is created in the verifier.

**Comment by SteveDiamond** [comment]
Pretty sure this is fixed in 1.1.
