### ISSUE TITLE
nose test no final result

### ISSUE THREAD

**Issue by lliill** [cvxgrp/cvxpy#896]
**Describe the bug**
When I use `nosetests cvxpy`, there is no final result to be produced, like (testing time, ok or not)

**To Reproduce**

![image](https://user-images.githubusercontent.com/18643795/70241849-1091fb80-1770-11ea-9a9e-69e78bc81991.png)

![image](https://user-images.githubusercontent.com/18643795/70241901-27385280-1770-11ea-83b3-06c0d76841cd.png)

It seems that there is no result for `test_partial_optimize_special_constr (cvxpy.tests.test_atoms.TestAtoms)`

**Expected behavior**
Normally, there is a ok at the end to show if the test is passed or not.
![image](https://user-images.githubusercontent.com/18643795/70241994-4df68900-1770-11ea-903d-9020ed140ae3.png)

**Version**
 - OS:  Windows 10
 - CVXPY Version: 1.0.25

**Additional context**
I just installed `cvxpy` with `pip` inside conda

**Comment by SteveDiamond** [comment]
We get so many of these questions about installation, I think they should start going to stackoverflow. Anyway, try reposting on stackoverflow.
