### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by dinesh286** [cvxgrp/cvxpy#906]
Hi,
I made a pole cart problem to learn CVXPY.  The details of the source and the code are given in the link
https://github.com/dinesh286/Cvxpy_Polecart
The problem is solved by sucessive convex programing approach. Cvxpy is used for solving problem. Hermit-simpson collocation is used for integration. The code gives optimized result better than the original code. But it takes more number of iterations (~190 iterations) to solve the problem. Also it takes more time to run the code (~20 min).

Suggestions are invited to improve the coding style to reduce number of iteration and run time in a standard PC

**Comment by SteveDiamond** [comment]
@dinesh286 you could try using Parameters with version 1.1. It may be faster.
