### ISSUE TITLE
Not able to solve convex problems with complex variables

### ISSUE THREAD

**Issue by Ali-Ai** [cvxgrp/cvxpy#907]
**CVXPY can not solve convex SDR optimization problems with complex-variables**
The error happens in running the constraints. When it tries to run the following constraint:

H = np.random.standard_normal((M, 1))
                               + 1j * np.random.standard_normal((M, 1))
R = H @ np.conjugate(H.T)

W = cp.Variable(shape=(M, M), complex=True)

constraints = []
constraints += [W >> 0]
constraints += [cp.trace(R @  W) >= 0]

where R is a Hermitian positive-semidefinite matrix as parameter of the problem; and W is a Hermitian matrix positive-semidefinite as the variableof the problem.

With Matlab CVX, the problem is solved. But with cvxpy I got the following error:

"ValueError: Inequality constraints cannot be complex." which is related to the last constraint.

**Version**
 - OS: Win 7: 
 - cvxpy 1.0.25:

**Comment by rileyjmurray** [comment]
The mostly likely cause is that cvxpy doesn't recognize that ``cp.trace(R @ W)`` is real. For now, you can get around this by writing ``cp.real(cp.trace(R @ W)) >= 0``.

**Comment by SteveDiamond** [comment]
You can also update to cvxpy 1.1. This issue is fixed there.

**Comment by akshayka** [comment]
Just one note — cvxpy 1.1 is still in alpha. We might be ready to make it stable soon.
