### ISSUE TITLE
gurobi conic interface needs tiny change for scipy 1.1

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#912]
The ``gurobi_conif.py`` file uses ``scipy.sparse.dok_matrix`` datatypes, and currently tries to access ``mat.iteritems()`` for such datatypes. The function ``iteritems()`` only applies to dok-format matrices from scipy versions < 1.0. CVXPY requires scipy version >= 1.1.

Lines 268 and 310 of ``gurobi_conif.py`` should be changed from ``for (i, j), c in mat.iteritems():`` to ``for (i, j), c in mat.items():``.

@akshayka , @SteveDiamond let me know if you want me to add this to my existing PR.

**Comment by SteveDiamond** [comment]
I made this change. Something else seems wrong with the gurobi interface though.
