### ISSUE TITLE
Getting “Cannot multiply AFFINE and CONVEX” in cvxpy 0.4.10 but not 1.0.18

### ISSUE THREAD

**Issue by jonathanng** [cvxgrp/cvxpy#914]
**Describe the bug**
I'm working on two different environments which have different versions of cvxpy.

On 1.0.18, this works as expected:
```
import cvxpy as cp

print(cp.__version__)

X = cp.Parameter(name='X', shape=(10), nonneg=True)
Y = cp.Variable(shape=(10))

print(X.T @ cp.abs(Y))

>>> Expression(CONVEX, NONNEGATIVE, ())
```

But on 0.4.10, this does not:

```
import cvxpy as cp

print(cp.__version__)

X = cp.NonNegative(name='X', rows=10)
Y = cp.Variable(rows=10)

print(X.T @ cp.abs(Y))

>>> DCPError: Cannot multiply AFFINE and CONVEX.
```

Anyone know why? Did I do something wrong?

Much appreciated! Thanks!

**Comment by rileyjmurray** [comment]
Version 0.4 is no longer supported. From what you described, version 1.0 is behaving correctly.

A “parameter” is not an optimization variable, a must be assigned a value before a call to ``prob.solve()``. My guess is that you are declaring a nonnegative *variable* in the 0.4 code. In that case, 0.4 would correctly be raising an error.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
