### ISSUE TITLE
how to solve an unequal equation???

### ISSUE THREAD

**Issue by freedomwindy** [cvxgrp/cvxpy#916]
I  has a fuction like this :
y = (2*x1 + x2)/(10*x1+9*x2+8*x3) 

constraints:  y>=0.4 and y<=0.45 and x1,x2,x3 is even number,and x1 <=x2 <=x3

how to solve upper question???

**Comment by akshayka** [comment]
Hey @freedomwindy, welcome to CVXPY. Your question is better suited to the website stackoverflow.com, where you can tell the community what you’d like to solve and what you’ve tried so far. I’m closing the issue for now, but do post your question (with additional details) on stackoverflow, and tag it with CVXPY.
