### ISSUE TITLE
Drop the "Elemental" solver from web-documentation

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#919]
[Web documentation](https://www.cvxpy.org/tutorial/advanced/index.html#solve-method-options) mentions a solver called "Elemental."

CVXPY no longer has an interface file for Elemental. The interface was probably dropped with 1.0, but in any case, [the solver is no longer maintained](https://github.com/elemental/Elemental). CVXPY's web documentation should be updated to remove reference to this solver.

**Comment by SteveDiamond** [comment]
Fixed.
