### ISSUE TITLE
CPLEX dual variable issue

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#920]
@SteveDiamond recently informed me that a trial version of CPLEX is available from pip. I ran the current suite of tests against that version of CPLEX, and some of the dual variable tests failed. Most of the failures were fixed by changing precision of the tests, however one test failed by a huge margin. Specifically,
```
StandardTestSOCPs.test_socp_1(solver='CPLEX', places=0)
```
fails (follow [this link](https://github.com/cvxgrp/cvxpy/blob/f35960c65ee9dd5687929f0c95104f901d920db8/cvxpy/tests/solver_test_helpers.py#L222) for the problem definition).

The cause of the failure is that the dual variable to the final constraint (``y <= 5``) is reported as zero, when it should be about ``2.86560``. I checked to see if the test was over-restrictive (i.e. maybe some dual-optimal solution has zero dual variable to ``y <= 5``), but this is not the case. The current CPLEX solution fails a stationary Lagrangian check, and so it is not dual-feasible.

**Comment by rkersh** [comment]
@rileyjmurray: I'm able to reproduce the issue, and I'm looking into it.

**Comment by rkersh** [comment]
Here is the test script (github doesn't accept .py files, so I zipped it up).
[test.zip](https://github.com/cvxgrp/cvxpy/files/4073548/test.zip)

**Comment by rileyjmurray** [comment]
@rkersh is there progress on this?

**Comment by rkersh** [comment]
> @rkersh is there progress on this?

@rileyjmurray: Yes, an issue has been filed with the CPLEX team. There appears to be a problem when mapping the solution to the presolved model back to the original model. Can you mark the test as skipped or ignored for the time being? I'll let you know when a solid workaround or fix is available for this.

**Comment by rileyjmurray** [comment]
I see. Thanks for the reply!

As of yesterday evening, we now have a couple new tests for SOCPs. The CPLEX interface is failing ``socp_1``, ``socp_2``, and ``socp_3`` because of dual variable issues.

Moving forward I can either disable all SOCP dual variable tests, or just the one that sparked this thread. Take a look at the new tests and let me know which you'd prefer.

**Comment by rkersh** [comment]
@rileyjmurray: I think we should skip all three for the short term. For example:
```
diff --git a/cvxpy/tests/test_conic_solvers.py b/cvxpy/tests/test_conic_solvers.py
index 01812b58..74ffba35 100644
--- a/cvxpy/tests/test_conic_solvers.py
+++ b/cvxpy/tests/test_conic_solvers.py
@@ -817,12 +817,15 @@ class TestCPLEX(BaseTest):
     def test_cplex_socp_0(self):
         StandardTestSOCPs.test_socp_0(solver='CPLEX')
 
+    @unittest.skip("GH-920")
     def test_cplex_socp_1(self):
         StandardTestSOCPs.test_socp_1(solver='CPLEX', places=2)
 
+    @unittest.skip("GH-920")
     def test_cplex_socp_2(self):
         StandardTestSOCPs.test_socp_2(solver='CPLEX')
 
+    @unittest.skip("GH-920")
     def test_cplex_socp_3(self):
         # axis 0
         StandardTestSOCPs.test_socp_3ax0(solver='CPLEX')
```

**Comment by rileyjmurray** [comment]
@rkersh can do. I'll make the change to tests before we release v1.1 (#913).

**Comment by rkersh** [comment]
@rileyjmurray: I assumed that the failures for `test_cplex_socp_(2|3)` were related to the failure for `test_cplex_socp_1`, but it turns out they were not. With the commit above from my rkersh/GH-920 branch, the test_cplex_socp_(2|3) tests should be fixed. I'll create a pull request for this.

**Comment by rileyjmurray** [comment]
@rkersh thanks for following up!

**Comment by rkersh** [comment]
When pull request #956 is merged, the `test_cplex_socp_2` and `test_cplex_socp_3` tests should not need to be marked as skipped.

With regards to `test_cplex_socp_1` a fix will be included with the next CPLEX release, so it can be skipped for now. In the meantime, the following parameters can be set to workaround the problem:
```
result = model.solve(solver=cvxpy.CPLEX,
                                 cplex_params={
                                     "preprocessing.presolve": 0,
                                     "preprocessing.reduce": 2
                                 })
```
These parameters correspond to the [presolve switch](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cplex.help/CPLEX/Parameters/topics/PreInd.html) and [primal and dual reduction type](https://www.ibm.com/support/knowledgecenter/SSSA5P_12.10.0/ilog.odms.cplex.help/CPLEX/Parameters/topics/Reduce.html).

**Comment by rileyjmurray** [comment]
@rkersh let us know which version of CPLEX contains the fix for this issue. For now we've changed the problematic CPLEX unittest to use solver keyword arguments as you suggest, so users should be able to run unittests and see everything pass.
