### ISSUE TITLE
CPLEX status "unbounded" being parsed to "infeasible".

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#921]
Consider the problem
```
x = cp.Variable(5)
cons = [x <= 1]
objective = cp.Minimize(cp.sum(x))
prob = cp.Problem(objective, cons)
```
If you run ``prob.solve(solver='CPLEX', verbose=True)``, you'll get
```
Version identifier: 12.10.0.0 | 2019-11-27 | 843d4de
CPXPARAM_Read_DataCheck                          1
Dual infeasible due to empty column 'x1'.
Presolve time = 0.00 sec. (0.00 ticks)
CPLEX Error  1217: No solution exists.
```
The CPLEX solution (dual infeasibility, a.k.a. primal unboundedness) is correct, however, cvxpy isn't correctly processing this result. Specifically, cvxpy returns ``prob.value == np.inf`` and ``prob.status == 'infeasible'``, when the correct values are ``-np.inf`` and ``prob.status == 'unbounded'``. 

Edit: this test case is ``lp_3`` in ``cvxpy/tests/solver_test_helpers.py``.

**Comment by SteveDiamond** [comment]
Fixed.

**Comment by rileyjmurray** [comment]
@SteveDiamond @rluce this is almost the same error we're now seeing with GUROBI (#1065).
