### ISSUE TITLE
Get XPRESS interface working again

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#923]
The XPRESS interface has been minimally maintained since migrating to cvxpy 1.0. I don't think anyone has tested changes from cvxpy's 1.0 -> 1.1 upgrade.

Per a comment on #382 , a community license (suitable for running unittests with cvxpy) can be installed with ``pip install xpress``. I installed XPRESS in this way, and ran the full suite of unittests. Upon doing this, all tests fail.

The **initial** cause of this failure is that the function ``XPRESS.apply`` in ``xpress_conif.py`` doesn't return anything. A correct implementation of ``XPRESS.apply`` would return the tuple ``(data, inv_data)`` already defined in that function.

Pinging @merraksh , since you mentioned volunteering to get this working again.

**Comment by merraksh** [comment]
Working on it these days, hopefully by end of next week I'll be done.

**Comment by rileyjmurray** [comment]
@merraksh has this moved at all? Let me know if you need help. We can discuss here, or perhaps over the phone / skype if you'd like.

**Comment by merraksh** [comment]
@rileyjmurray this moved a bit. There are substantial changes to both the quadratic solver and some changes to the conic one. I'm working on the branch [https://github.com/fico-xpress/cvxpy/tree/update-xpress](https://github.com/fico-xpress/cvxpy/tree/update-xpress) and currently failing a few tests due to wrong solution translation (CVXPY is expecting a different value of the solution/objective value than reported).

**Comment by merraksh** [comment]
@rileyjmurray we can discuss it here or on the phone (ping me at pietrobelotti at fico dot com); work laptop doesn't do skype (but can use Zoom). Either way I think I need to figure out how apply/invert methods work as I think those are currently incorrect in the Xpress interface.

**Comment by merraksh** [comment]
@rileyjmurray the current fork master fails test_dqcp.py with ECOS even though I haven't touched that part of the code. Also, for some reason minimization problems with <= constraints are checked against positive dual values while the result obviously has nonpositive dual values.

**Comment by rileyjmurray** [comment]
@merraksh thanks for the replies! I only have experience with the conic interfaces, so I'll speak to those first.

Generally speaking, the objective value and the primal variables should be easy to map back to CVXPY. If you're encountering issues with this step, it likely means the constraints in the XPRESS problem are not being specified in a way consistent with what CVXPY intends. For LP interfaces there is usually no confusion here. To see if you are stuck at this phase or somewhere else, see my notes on testing at the end of this comment.

Dual variables are often a sticking point in solver interfaces. I'll go into those in more detail below.

Give the ideas in this comment a try. If you still encounter trouble, we can schedule a zoom call.

Dual variable signs
-------------------------
Often one needs to flip the sign on a solver's dual variable; this happens because of how CVXPY considers the relationship between primal and dual problems.
* CVXPY begins by working with a primal-dual pair as described in Chapter 5 of https://web.stanford.edu/~boyd/cvxbook/.
  * Linear inequality constraints are always rewritten to a form ``con = (expr <= 0)`` for an appropriate expression ``expr``. From there we associate a nonnegative dual variable to ``con``. 
  * Linear equality constraints of the form ``con = (expr_left == expr_right)`` are translated to ``con = (expr_left - expr_right == 0)``.
* CVXPY takes the opposite convention when it comes to general cone constraints. If you have a constraint of the form ``expr in K`` for ``K`` as either SOC, ExpCone, or PSD, we introduce a dual variable ``dv`` and augment the Lagrangian by ``- cp.scalar_product(dv, expr)``.

These policies imply that for all constraints other than ``expr1 == expr2``, CVXPY's dual variable will be "nonnegative" in the appropriate sense (i.e. literally nonnegative for inequality constraints, nonnegative eigenvalues for PSD constraints, etc...).

Conic dual variable assumptions
-------------------------------------------
For LP models, there isn't much to dual variables other than getting the signs right. However for general conic models (SOC, ExpCone, PSD) there can be other issues. CVXPY makes assumptions about how primal cones are represented, and that ends up affecting how a dual cone needs to be represented. A common example here is a second order cone constraint. CVXPY assumes 
```
SOC(n) = { (t, x) in R^{n+1} : ||x||_2 <= t },
```
which is of course different from
```
OtherSOC(n) = { (x,t) in R^{n+1} : ||x||_2 <= t}.
```
These forms are related to each other by simple transformations. If your solver interface works with ``OtherSOC`` rather than ``SOC``, you need to account for the different convention for both primal and dual variables.

Testing advice
-------------------

Pass all relevant LP tests before trying to pass tests with SOC, ExpCone, or PSD constraints.

When you're in the prototyping phase, it can be helpful to create custom tests which only check for certain functionality. For example- a test which only cares about the optimal objective and primal values. The ingredients for such a test are found in ``tests/solver_test_helpers.py``; you can put your intermediate tests under the heading for XPRESS in ``tests/test_conic_solvers.py``. Here is an example of a test for a second order cone program, which does not check dual variables
```
from solver_test_helpers import socp_1

def test_socp_1_primal(places=4):
    sth = socp_1()
    sth.solve(solver='XPRESS')
    sth.verify_objective(places)
    sth.verify_primal_values(places)
    pass
```
It's possible that you couldn't run the above test, if you encountered a runtime error in ``sth.solve()``. Such runtime errors could happen if you tried to save a dual variable of an incorrect shape. If you really are only trying to test primal functionality, you could temporarily modify ``cvxpy/constraints/second_order.SOC.save_dual_value`` with a try-catch block. Of course, such a try-catch block would need to be removed before a PR, but that's easy.

**Comment by rileyjmurray** [comment]
@merraksh I noticed your CVXPY fork hasn't had activitiy since our last exchange of comments. Would you like to setup a call this week, so I can help in areas where you might be stuck?

**Comment by merraksh** [comment]
@rileyjmurray I'm quite busy at the moment, but we can set up a call in a couple of weeks. I'll follow up with an invite. Thanks!

**Comment by merraksh** [comment]
@rileyjmurray I'm available now. Sorry for the long silence. Let me know if you want to set up a call tomorrow (Friday) or next week.

**Comment by rileyjmurray** [comment]
@merraksh no worries. Your timing is actually quite good, since I'm just now wrapping up a fix of an incorrect (and very confusing!) naming convention in the solver interfaces. I'll probably create the PR today or tomorrow. Once that PR is merged we can setup a call.

**Comment by merraksh** [comment]
Sounds good!

**Comment by rileyjmurray** [comment]
@merraksh #1020 is the PR I mentioned above.

**Comment by merraksh** [comment]
Hi,

 

I can see that PR is merged. We can chat about Xpress next week if you're available.

 

Thanks,

Pietro

 
 

Sent: Saturday, May 09, 2020 at 3:07 AM

**Comment by rileyjmurray** [comment]
Next week works; I'll send you an email.

**Comment by rodfloripa** [comment]
The XPRESS parameter MAXTIME is not working.

**Comment by merraksh** [comment]
@rodfloripa Can you elaborate? Please note that, as per [https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/MAXTIME.html](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/MAXTIME.html), when a feasible solution is not found, the solver stops after |MAXTIME| seconds if MAXTIME is negative. If MAXTIME is positive, the solver goes on after MAXTIME seconds until a solution is found.

**Comment by rodfloripa** [comment]
I think that the cvxpy interface is not working,I have the latest cvxpy version from source(github).
That's what I tried: result = prob.solve(cp.XPRESS,verbose = True,MAXTIME=-60).  The solver didn't
stop after 60 seconds.

**Comment by rodfloripa** [comment]
Is it working @rileyjmurray ?

**Comment by phschiele** [comment]
@rodfloripa 

You can check the implementation of the interface in `xpress_conif.py`. 

There you can find a comment about the solver options:
```
       # Set options
        #
        # The parameter solver_opts is a dictionary that contains only
        # one key, 'solver_opt', and its value is a dictionary
        # {'control': value}, matching perfectly the format used by
        # the Xpress Python interface.
```

**Comment by rodfloripa** [comment]
I only have two parameters,'festol' and 'bargaptarget'
Can I include 'maxtime'?

 # the Xpress Python interface.

        self.prob_.setControl({i: solver_opts[i] for i in solver_opts
                               if i in xp.controls.__dict__})

        if 'bargaptarget' not in solver_opts:
            self.prob_.controls.bargaptarget = 1e-30

        if 'feastol' not in solver_opts:
            self.prob_.controls.feastol = 1e-9

**Comment by rodfloripa** [comment]
Ok, hard coding xpress_conif.py it worked
