### ISSUE TITLE
Inconsistent check for definiteness of a matrix

### ISSUE THREAD

**Issue by aadamson** [cvxgrp/cvxpy#929]
The checks for definiteness used for decomposing a quadratic form (https://github.com/cvxgrp/cvxpy/blob/badc0a79701da0785acaaf994b9d072bafb64efb/cvxpy/atoms/quad_form.py#L203) and checking the definiteness of a matrix (https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/expressions/constants/constant.py#L205) are not consistent, and the latter has given me incorrect results for ill-conditioned matrices generated from the inner-product of a PSD matrix with itself (should be PSD).

Would there be interest in a PR that would make the matrix PSD check account for the conditioning of the matrix and data type?

**Comment by SteveDiamond** [comment]
Yes, a more sophisticated approach to checking definiteness of constants would be valuable.

**Comment by aadamson** [comment]
Reading through the [scipy docs ](https://docs.scipy.org/doc/scipy/reference/tutorial/arpack.html#shift-invert-mode) a bit more, it looks like they recommend using a transformation called "shift-invert mode" when you're trying to find small eigenvalues: "Note that ARPACK is generally better at finding extremal eigenvalues, that is, eigenvalues with large magnitudes. In particular, using which = 'SM' may lead to slow execution time and/or anomalous results. A better approach is to use shift-invert mode."

I confirmed that for my particular issue, setting `sigma=0.` as they recommend solves the problem (all of the eigenvalues are > 0, as expected, and it converges faster). I'll create a PR with that change later today if that would be valuable.

I couldn't find any clear documentation in ARPACK or scipy on errors, so I don't know what to do about the tolerances.
