### ISSUE TITLE
Conda and pypi deployment issues

### ISSUE THREAD

**Issue by rileyjmurray** [cvxgrp/cvxpy#937]
There are a couple problems with deploying to conda and pypi following successful CI tests. Conda uploads don't seem to be working at all, and pypi uploads aren't happening for python 3.5.

Non-exhaustive list of issues with conda:
* The conda recipe had some bad syntax from my changes in #926. 

Non-exhaustive list of Issues with pypi:
* Uploading to pypi requires ``readme_renderer``. We're trying to install ``readme_renderer`` with conda, but this is failing in 3.5 because conda channels seem to not have a 3.5 compatible version of ``readme_renderer``. The fix here is simply to get ``readme_renderer`` from pip (since the package itself certainly supports python 3.5).

**Comment by rileyjmurray** [comment]
This has largely been resolved by the above PR. The only possible issue that remains is Windows builds with Conda. Currently deciding how the handle those.

**Comment by h-vetinari** [comment]
See my comment [here](https://github.com/cvxgrp/cvxpy/pull/528#issuecomment-583854796). Despite publishing for a much shorter period of time (e.g. windows builds only since September), the conda-forge package has already [eclipsed](https://anaconda.org/search?q=cvxpy) the cvxgrp-channel, and also offers AArch-support.

Generally, there are several reasons why having fewer channels for conda is recommended (e.g. solver speed), and so it's a significant benefit to have cvxpy + dependencies in conda-forge now, and for all OSes too! :)

It would be awesome IMHO if the cvxpy-maintainers were to shift their packaging efforts to the conda-forge feedstock (compare for example also how the packaging of osqp is now maintained on conda-forge) - it would only be a formality to add you as additional recipe maintainers.

**Comment by rileyjmurray** [comment]
Hi @h-vetinari. Thanks for the suggestion. Are you one of the maintainers of the conda-forge feedstock?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by h-vetinari** [comment]
I'm not a maintainer of the cvxpy-feedstock itself, but I have taken care of taking care of the windows builds for [cvxpy](https://github.com/conda-forge/cvxpy-feedstock/pull/22) after taking care of the dependencies ([scs](https://github.com/conda-forge/scs-feedstock/pull/7), [osqp](https://github.com/conda-forge/osqp-feedstock/pull/10), [ecos](https://github.com/conda-forge/ecos-feedstock/pull/8), [cvxopt](https://github.com/conda-forge/cvxopt-feedstock/pull/38), etc.), and I'm maintainer of several of _those_ feedstocks now - in general, the barrier to recipe-maintainership is quite low; wanting to help is usually enough (which is how I ended up as one ;-)).

But pinging the [maintainers](https://github.com/conda-forge/cvxpy-feedstock/#feedstock-maintainers) @scopatz @mcg1969 as well.

**Comment by rileyjmurray** [comment]
Oh wow! Nice to see that someone took the Windows-SCS issue on. As you can see that has been plaguing us for a while.

I’d be happy to potentially join in on maintaining the conda-forge cvxpy feedstock. Continuing from a solid foundation there would free up some effort to really get our wheel distribution down (e.g. manylinux wheels). Let me discuss with Steven and Akshay to make sure we’re on the same page about this.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bstellato** [comment]
We also moved our anaconda osqp packaging to conda-forge as well. Every time there is a new release on the `osqp-python` repo, a new PR is automatically created from conda-forge bots.

**Comment by dougalsutherland** [comment]
Yes, you’re of course welcome to join as maintainers of the conda-forge feedstock, and we’d be perfectly happy if you move primary conda distribution over there as well.

If you care about python 3.5 specifically for some reason, though, note that conda-forge doesn’t build for that anymore. (Not sure if defaults does either.)

**Comment by scopatz** [comment]
Note that conda-forge just doesn't build Python 3.5 packages by default.  It is possible to reenable it if you really need it for your stack

**Comment by rileyjmurray** [comment]
Hi all -- sorry for not responding on this for a while. I ended up getting preoccupied with other issues. I've spoken with Steven and Akshay, and we're all in agreement that shifting cvxpy's conda efforts from "cvxgrp" to "conda-forge" is a good idea. I won't have time to work on this for the next couple weeks, but it's on the to-do list.

**Comment by h-vetinari** [comment]
Hey @rileyjmurray, no worries about the timeline, it's not a big rush. If you want, I could very easily open a PR to add you three as recipe maintainers - you will get occasional github pings, but that way, you could see how the game is played (so to speak) without having to do something yourself yet.

Why I came back to this issue now is that I was wondering if it would make sense to add `cvxopt` as a dependency within the conda-package. I ask this for example in the context of the removal of last available open-source MIP solver (#973), which is a gap that `cvxopt` could fill with `glpk`. `cvxopt` might be fiddly to install through pip, but the packaging of `cvxopt` has matured well (not least on the windows support side; plus support across 4 blas variants - `mkl`, `netlib`, `openblas`, `blis`), and I think that could be worthwhile.

What do you think?

**Comment by rileyjmurray** [comment]
@h-vetinari it would be great if you could add @SteveDiamond, @akshayka, and myself as maintainers.

The change #973 actually includes an explicit recommendation to install cvxopt, if a user tries to solve a MIP without an appropriate solver. I've found pip installation of cvxopt pretty seamless as of late.

That said, cvxopt is licensed under the GNU general public license. By contrast, cvxpy uses (and will continue to use) an Apache license. Having non-GPL software ship with GPL software is a delicate issue, and one that I have no serious experience with. From the GNU GPL [faq](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins), it seems that if cvxpy shipped with cvxopt, then the whole package would be considered a single program, and it would need to be distributed under the GPL.

In principle, someone could take cvxpy's apache license, and distribute *a version* of cvxpy under the GPL (see the [Apache docs](https://www.apache.org/licenses/GPL-compatibility.html) about this). I don't know how this would work, or how @SteveDiamond or @akshayka would feel about such an effort.

**Comment by h-vetinari** [comment]
> @rileyjmurray : @h-vetinari it would be great if you could add @SteveDiamond, @akshayka, and myself as maintainers.

Great to hear!

About the license situation: I'm no lawyer, but the libraries would still be packaged separately, under their respective licences. cvxopt would "just" be a dependency of cvxpy. I realise that this is likely too simplistic to be a completely satisfying answer, but it's (to the best of my knowledge) how pip/conda and a lot of other dependency solvers treat the question.

**Comment by akshayka** [comment]
Unfortunately, I believe Riley is right. If we included GPL software, even through a dependency, we’d have to distribute CVXPY under GPL as well.

**Comment by dougalsutherland** [comment]
On conda-forge, cvxpy is currently split into `cvxpy-base` and `cvxpy`, where the latter is simply a metapackage requiring `cvxpy-base` and some solvers. I believe, but I am not a lawyer and am not 100% confident, that it’s fine to have `cvxpy-base` continue to be Apache but `cvxpy` be GPL.

That said, I’m not sure whether conda-forge supports different licenses for split output packages right now.

**Comment by SteveDiamond** [comment]
We already have this situation with ECOS, which is GPL. My view has been that since CVXPY does not strictly require these dependencies, and can and is used without them, it's fine to have CVXPY as Apache. The move to Apache was actually prompted by user requests, and those users have been satisfied with the situation.

**Comment by SteveDiamond** [comment]
@h-vetinari we actually used to have CVXOPT as a dependency, but dropped it because it had become a nightmare to install. I'm glad to hear the installation situation has improved. I'd be open to adding it as one of the auto-installed solvers, if we're really confident this isn't going to open a can of worms.

**Comment by h-vetinari** [comment]
@SteveDiamond 
Glad to hear your thoughts on this.

> I'd be open to adding it as one of the auto-installed solvers, if we're really confident this isn't going to open a can of worms.

 Which can of worms are we talking about? Legal? Installation issues? Both?

I can't make definitive statements on the legal situation, but I'm quite-to-very confident that the installation issues would be a thing of the past.

**Comment by rileyjmurray** [comment]
@h-vetinari I think the can-of-worms in question is more about respecting the wishes of other developers. @SteveDiamond mentioned that we already ship with GPL software via ECOS, but in that case we have clear communications with ECOS developers that cvxpy's ECOS dependency is fine. I imagine the CVXOPT developers would similarly be okay with cvxpy adopting CVXOPT as a dependency. However, we need to consider the CVXOPT is bundled with GLPK, and GLPK developers might have their own views here.

GLPK isn't any ordinary piece of GPL software. It's part of the official GNU Project, and as such the GLPK maintainers almost certainly take a strict stance on the GPL. I don't think we could really make a case that cvxpy could ship with GLPK and retain the Apache license. Reason being, it's extremely common for people to conflate cvxpy with a solver (tons of optimization-based academic papers contain phrases like "we used the CVX solver in Matlab" or "we used the CVXPY solver in python").  So many people wouldn't even think to check if cvxpy automatically included official GNU Project software in the form of GLPK; they would just see the Apache license, and feel that they were in the clear.

@dougalsutherland suggested distributing cvxpy under GPL, and some distinct "cvxpy-base" under Apache. I don't think that approach is viable if the distinction is purely one of an Anaconda recipe. However if there was a *truly distinct* Apache-licensed "cvxpybase" python package, then the main cvxpy package could be made GPL, and include "cvxpybase" as a dependency. I can think of some simple rules by which a functional "cvxpybase" package can be considered distinct from a larger "cvxpy", but that's outside the scope of this conversion. I'm open to exploring this split-package approach if @SteveDiamond and @akshayka are, but right now we probably don't have the bandwidth to plan and carry out such a project.

**Comment by h-vetinari** [comment]
Looping in @martinandersen (cvxopt developer) for possible thoughts/input on making `cvxopt` a dependency of `cvxpy` (at least within conda; discussion starting [here](https://github.com/cvxgrp/cvxpy/issues/937#issuecomment-606268768)), in particular from the POV of licensing, which currently looks like an insurmountable blocker.

**Comment by martinandersen** [comment]
I'm no expert in licensing. It is basically the extension modules (including GLPK) that force us to use the GPL license. We are currently discussing different options that would allow us to switch to a different license in a future release.

**Comment by rileyjmurray** [comment]
This thread has pretty far exceeded its intended scope. Since there is no immediately actionable information or task here, I'm going to close it.

To summarize the various discussions:
 * The issues which motivated this thread have largely been fixed. I say *largely* because there are still bugs with AppVeyor and conda. Those issues now occur across cvxpy 1.0.x and 1.1. I'm going to open another ticket for those issues.
 * Thanks to @h-vetinari - Steven, Akshay and I have been added as maintainers for a conda-forge distribution of cvxpy. The plan is for us to shift conda efforts to that channel. (I might even use that as justification to close the ticket I'm about to open regarding pending AppVeyor issues, but I want to lay those issues out first.)
 * There has been discussion on shipping cvxpy with cvxopt, motivated by the fact that cvxopt comes with GLPK. Our of respect for the GLPK developers I believe it would be necessary to receive explicit approval before doing that, so long as cvxpy has an Apache license. I would like to provide one last remark on this topic. @martinandersen -- cvxopt is currently the only way that cvxpy interfaces with GLPK. If you plan on changing licenses or otherwise dropping the GLPK bundle, please let us know as soon as possible, so that we here at cvxpy can plan accordingly.
