### ISSUE TITLE
Print CVXPY information when verbose=True

### ISSUE THREAD

**Issue by sbarratt** [cvxgrp/cvxpy#940]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
When the argument `verbose=True` is passed to the `Problem.solve` method, print some status information about the CVXPY canonicalization, like canonicalization started, expression tree parsed, generating affine maps, sending to solver, etc...

**Comment by rileyjmurray** [comment]
I think this is a good idea.

I'm not sure about having ``verbose=True`` triggering cvxpy logging, but I definitely support the larger idea. As a possible alternative,``Problem.solve`` could accept a keyword argument like ``canon_log``. If someone called ``prob.solve(canon_log=True)`` then the behavior would log to ``sys.stdout``. If someone called ``prob.solve(canon_log=my_stream)`` for some datastream ``my_stream``, then ``sys.stdout`` would be untouched.

For an implementation, it would be most natural to have ``Reduction`` objects decide how to handle logging during their ``apply`` and ``invert`` phases. It would be easy to identify performance bottlenecks by having ``apply`` functions record ``time.time()`` when starting and finishing each reduction. There is a question of at what level these logs should be made, though.

Those are just some quick thoughts I have on the topic.

**Comment by akshayka** [comment]
I also think this is a good idea! I’m hesitant to add new arguments unless absolutely required, though, since they make the interface more complicated. Using the verbose argument to trigger CVXPY logging seems natural.

**Comment by andrea83ny** [comment]
love this thread ! Any sort of verbose would be incredibly useful.

**Comment by juancaoviedo** [comment]
Hi, 

I think the idea of printing info on screen when "verbose = True" as actually implemented is good. However, low-level logging when "verbose = log" could be very useful. Think about deploying cvxpy in docker containers or in raspberry pi, then the logging option I think is a must-have. 

If there are some advances in the implementation of the logging option I will love to be noticed! Currently, I'm needing it! 

Regards

**Comment by QCmonk** [comment]
I would also support such a feature, would be very useful for checkiing progress on large problems with many constraints.

**Comment by sbarratt** [comment]
Addressed in https://github.com/cvxgrp/cvxpy/pull/1251
