### ISSUE TITLE
Issue when plotting using Matplotlib

### ISSUE THREAD

**Issue by taufique1929** [cvxgrp/cvxpy#943]
I have started reading the documentation of cvxpy and working through the examples. The examples work fine, except the plotting part. Whenever I try to plot, error is encountered (attached).  
[cvxpy_matplotlib_issue.docx](https://github.com/cvxgrp/cvxpy/files/4196608/cvxpy_matplotlib_issue.docx)

**Comment by rileyjmurray** [comment]
Please post your error in something other than a Microsoft word document. Ideally the error should be posted directly to this GitHub issue. Failing that- use a Google Doc if necessary.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by taufique1929** [comment]
Thanks for your response. I have taken care of the issue.
