### ISSUE TITLE
CVXOPT solver failing on example quadratic program

### ISSUE THREAD

**Issue by sixpearls** [cvxgrp/cvxpy#951]
When I try to use the CVXOPT solver for a quadratic program, it fails -- even if I use the same problem data and `cvxopt.solvers.qp` directly. I believe this is because even for a QP (i.e., `problem.is_qp()` returns `True`) the `cvxopt.solvers.conelp` function is called. I can trace this to [these lines](https://github.com/cvxgrp/cvxpy/blob/fc2d20658384e66824ccc4cc22357c687aa338ea/cvxpy/reductions/solvers/conic_solvers/cvxopt_conif.py#L201-L207).

To reproduce, use the example QP with the CVXOPT solver:
```python
# Import packages.
import cvxpy as cp
import numpy as np

# Generate a random non-trivial quadratic program.
m = 15
n = 10
p = 5
np.random.seed(1)
P = np.random.randn(n, n)
P = P.T @ P
q = np.random.randn(n)
G = np.random.randn(m, n)
h = G @ np.random.randn(n)
A = np.random.randn(p, n)
b = np.random.randn(p)

# Define and solve the CVXPY problem.
x = cp.Variable(n)
prob = cp.Problem(cp.Minimize((1/2)*cp.quad_form(x, P) + q.T @ x),
                 [G @ x <= h,
                  A @ x == b])
prob.solve(solver=cp.CVXOPT)

# Print result.
print("\nThe optimal value is", prob.value)
print("A solution x is")
print(x.value)
print("A dual solution corresponding to the inequality constraints is")
print(prob.constraints[0].dual_value)
```

This is with cvxpy version 1.1.0a3.

**Comment by rileyjmurray** [comment]
What's the unexpected behavior you're seeing? I ran your code and didn't see any glaring issues.

**Comment by rileyjmurray** [comment]
The ``conelp`` function is called because CVXPY compiles the problem into an equivalent second order cone program, and ``conelp`` handles LP, SOCP, and SDP.

**Comment by sixpearls** [comment]
Sorry about that, I had already realized the failure I reported was in a stale workspace and was tracing through the problem on my end to make sure it was in my user code before closing. I believe I was able to trace the problem to setting some values in the global `cvxopt.options` dict which causes a failure even though solving a sequence of similar problem data directly does not cause a problem. I'll go ahead and close this out.
