### ISSUE TITLE
Best Solution displayed in Pycharm but apparently not available with a field

### ISSUE THREAD

**Issue by andrea83ny** [cvxgrp/cvxpy#952]
**Describe the bug**
Hi, I'm extremely new to github so apologizes if there's something missing in my very first post.
I use a lot cvxpy at work and if I run it from Pycharm I can see the screen shows a "best solution" value. I would badly need to capture such value (other editors like Spyder don't even show such value) but it seems there's no field to capture it.
Notice how, as soon as the solver starts, Pycharm shows the current solution value found vs the best solution possible.
I know the "value" attribute captures the value at the end of the optimization, however if we use a timeout, it becomes hugely important to be able to compare the value found vs the optimal solution value.
Am I missing something?
Many thanks,
Andrea

**To Reproduce**
A [minimal code example](https://stackoverflow.com/help/mcve) that reproduces the bug or unexpected behavior.
Unfortunately I can't share the massive code I have here at work but it's a portfolio optimization problem mix with integer optimization.

**Expected behavior**
Offer a field that could be used to compare the optimal solution value.

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS:  Windows 7.
 - CVXPY Version: __version__ = "1.1.0a1"

**Additional context**

**Comment by SteveDiamond** [comment]
Once you solve an optimization problem, you can get the optimal value from the ``problem.value`` field and the solution from the ``variable.value`` fields. Is that the info you want?

**Comment by andrea83ny** [comment]
Hello Steve,
thanks for your answer. No, that's what I need though.
Let me try please to be a little more accurate.

I have the following code:
```
prob = cvx.Problem(objfunction, constraints_list)
prob.solve(verbose=True, solver=cvx.CBC, maximumSeconds=40)
```

Given the big dimension of my problem, the timeout of 40 seconds will often cause the optimizer to find a non optimal solution.

if you run the python code using PyCharm, you will see something like:
"Cbc0010I After 3100 nodes, 458 on tree, -2001.0231 best solution, best possible -2042.2492 (96.78 seconds)"

what I need to capture is the best possible solution value because if at this point the timeout interrupts the optimization  'problem.value' will return -2001.0231 and I need also to capture -2042.2492

Any thoughts?
Thanks again, much appreciated,
Andrea

**Comment by SteveDiamond** [comment]
You'll need to manually change the Cbc interface to get that.

**Comment by andrea83ny** [comment]
Any chance you could point me to where/how I could do that? 
I spent two days already digging into tens of cvxpy python files with no luck.
Thanks Steve,
Andrea

**Comment by SteveDiamond** [comment]
Cbc interface is here: https://github.com/cvxgrp/cvxpy/blob/master/cvxpy/reductions/solvers/conic_solvers/cbc_conif.py
