### ISSUE TITLE
Gurobi does not report any solver time with a simple LP in 1.0.28

### ISSUE THREAD

**Issue by bstellato** [cvxgrp/cvxpy#954]
**Describe the bug**
Gurobi does not report any timing when solving LPs with `cvxpy>1.0.28`. This is because cvxpy defaults to its conic interface which does not save any `SOLVER_TIME`.

**To Reproduce**
```python
import cvxpy as cp
import numpy as np

# Problem data.
m = 30
n = 20
np.random.seed(1)
A = np.random.randn(m, n)
b = np.random.randn(m)

# Construct the problem.
x = cp.Variable(n)
objective = cp.Minimize(cp.norm(A*x - b, 1))
constraints = [0 <= x, x <= 1]
prob = cp.Problem(objective, constraints)
prob.solve(solver=cp.GUROBI)
prob.solver_stats.solve_time
```

**Expected behavior**
It should print the solver time

**Version**
 - OS: Mac OSX
 - CVXPY Version: 1.0.28

**Comment by thanever** [comment]
I met the same problem. May I know if it has been solved? Thanks.

**Comment by SteveDiamond** [comment]
Fixed on master.

**Comment by thanever** [comment]
> Fixed on master.

Thanks~
