### ISSUE TITLE
ValueError: 'shape' elements cannot be negative

### ISSUE THREAD

**Issue by andrea83ny** [cvxgrp/cvxpy#958]
**Describe the bug**
Hi, I'm running cvxvpy on a big data set here at work, and all of a sudden I get the following error message:

```
Traceback (most recent call last):
  File "C:/git/RAP.Muni.Optimizer.Api/DTC_Testing.py", line 821, in DTC_MultiRunner
    prob.solve(solver=cvx.CBC, maximumNodes=12000, maximumSeconds=220)
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 362, in solve
    result = solve_func(self, *args, **kwargs)
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 787, in _solve
    data, solving_chain, inverse_data = self.get_problem_data(solver, gp)
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 512, in get_problem_data
    data, inverse_data = solving_chain.apply(self, verbose_aa = self.verbose_aa)
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\chain.py", line 99, in apply
    problem, inv = r.apply(problem)
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\dcp2cone\cone_matrix_stuffing.py", line 222, in apply
    params_to_problem_data = extractor.affine(expr_list)
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\utilities\coeff_extractor.py", line 90, in affine
    num_rows)
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py", line 246, in get_problem_matrix
    (V, (I, J)), shape=(constr_length*(var_length+1), param_size_plus_one))
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\compressed.py", line 106, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\coo.py", line 185, in __init__
    self._shape = check_shape((M, N))
  File "C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\scipy\sparse\sputils.py", line 321, in check_shape
    raise ValueError("'shape' elements cannot be negative")
ValueError: 'shape' elements cannot be negative
```

It's impossible for me to share the underlying data since it's confidential customer data.
How can we try to find the root case of the problem?

**To Reproduce**
I simply run 

```
prob = cvx.Problem(objfun, constraints=conslist)
prob.solve(solver=cvx.CBC, maximumNodes=12000, maximumSeconds=220)

```

**Expected behavior**
All I need is a solution (feasible or unfeasible) but I get a bug / error message.

**Output**
If applicable, include program output. If reporting a program crash, please include the entire stack trace.

**Version**
 - OS: Windows 7
 - CVXPY Version: __version__ = "1.1.0a1"

**Additional context**

**Comment by rileyjmurray** [comment]
Issue #826 had very similar output. Can you follow the instructions in https://github.com/cvxgrp/cvxpy/issues/826#issuecomment-536477724 and report back what you see for len(V), len(I), etc..?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andrea83ny** [comment]
sure, working on this right now

**Comment by andrea83ny** [comment]
Sorry for my simple question, but I believe the code has changed quite a bit.
It doesn't seem I can len(problemData.V).
Shall I just check for the size of "V" right after I see V = np.concatenate(V) ?

**Comment by andrea83ny** [comment]
I managed to print a few variables. This is what I see when I print the len of variables V,I,J,A at the very end of function   get_problem_matrix():

-  'len(V)'    -> 7174
- 'len(I)'    -> 7174
- 'len(J)'    -> 7174
- 'A.getnnz()'    -> 7174
- A has dimension:  84 KB

thoughts? Thank you Riley

**Comment by rileyjmurray** [comment]
Hmm. It's surprising that the data is so small. What's ``max(I)`` and ``max(J)``?

**Comment by andrea83ny** [comment]
len(V)    -> 7174
len(I)    -> 7174
len(J)    -> 7174
max(I)   =  7533.0
max(J)   =  0.0

**Comment by rileyjmurray** [comment]
Those results indicate that the matrix in question is a column vector (``max(I) + 1 == 7534`` rows, ``max(J)  + 1 == 1`` columns). I suspect that ``get_problem_matrix`` is being called more than once, and that the information you've posted so far is only for the first call. My guess is that the information here is for the objective function only, and that the data ``(V,I,J)`` for the constraint matrix is much larger.

Can you actually modify the code for ``get_problem_matrix`` to include a print statement for length ``V`` and ``max(I)``, ``max(J)``? That way we can see all calls to the function, up until you encounter this error. The thing to modify would be
```
C:\Users\aardem\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\cvxcore\python\canonInterface.py
```
in between lines 244 and 245. While you're at it, it might be good to just print out ``constr_length*(var_length+1)`` and ``param_size_plus_one`` as well.

**Comment by andrea83ny** [comment]
As you guesses, _get_problem_matrix_  is called multiple times indeed.
1st time:
len(V)    -> 7174
len(I)    -> 7174
len(J)    -> 7174
max(I)   =  7533.0
max(J)   =  0.0
constr_length*(var_length+1)  =  11717
param_size_plus_one  =  1 
A.getnnz()    -> 7174
A has dimension:  84 KB

2nd time:
len(V)    -> 259798
len(I)    -> 259798
len(J)    -> 259798
max(I)   =  2164340805.0
max(J)   =  0.0
constr_length*(var_length+1)  =  -2130626490
param_size_plus_one  =  1 

3rd time:
len(V)    -> 7174
len(I)    -> 7174
len(J)    -> 7174
max(I)   =  7533.0
max(J)   =  0.0
constr_length*(var_length+1)  =  11717
param_size_plus_one  =  1 
A.getnnz()    -> 7174
A has dimension:  84 KB

4th - last time:
len(V)    -> 259798
len(I)    -> 259798
len(J)    -> 259798
max(I)   =  2164340805.0
max(J)   =  0.0
constr_length*(var_length+1)  =  -2130626490
param_size_plus_one  =  1 

So I guess this actually means this is a real big data issue?

**Comment by andrea83ny** [comment]
What I find strange is that if a slightly reduce the problem (I remove 10 constraints out of a total of ~ 900), an optimal solution is found in about 45 seconds, but with such an incremental step, we get this issue

**Comment by rileyjmurray** [comment]
Thanks for providing the values. It looks like the integer-overflow is actually occurring with the product ``constr_length*(var_length+1) = -2130626490``. It's going to be hard for us to help more without having access to at least the overall structure of the problem.

If possible, could you provide us with scrubbed problem data? For example, the code used to generate the LP, but replace every single numeric constant with the value ``1.0`` (even if this creates an infeasible or unbounded LP).

**Comment by andrea83ny** [comment]
happy to do my best to provide the data, but I would please need more guidance in what exact data you need. Apologizes for asking but I don't understand what you mean with 
'For example, the code used to generate the LP, but replace every single numeric constant with the value 1.0 (even if this creates an infeasible or unbounded LP)."

**Comment by otukka** [comment]
I had similar problem few months ago, and I think this problem originates from numpy sparce matrices that cvxpy is using.  I don't remember the details, but somewhere we call reshape function with -1 parameter. Numpy then calls np.prod function that fails on windows machines if the integer product goes beyond 2^32.  This problem happens only in Windows OS and doesn't effect Linux systems.  I suggest that to fix this the matrix reshape dimension should be calculated beforehand, and by not using -1 parameter. If someone want's to replicate this error good way is to use inpainting example in cvxpy.org. Use image size ~512 to replicate because smaller images might not fail.

**Comment by rileyjmurray** [comment]
Thanks very much for your comment @otukka! We'll give that fix a shot, as part of the larger effort to release v1.1.

**Comment by rileyjmurray** [comment]
@andrea83ny sorry for not replying sooner. My earlier remark was really just to ask if there was any way for you to share the code used to generate your problem.

You mentioned that the problem contains confidential data, but perhaps you can simply remove that data? Presumably the confidential data is simply numeric in nature (for example, a numeric value for some kind of budget, which appears in a constraint). If that is the case, then it would still be helpful for us to see the code even if you modified it to generate nonsense optimization problems (i.e. you could make a hypothetical "budget" value equal to -1). The only thing we'd really need is that the problem we see has the same sparsity pattern as the problem you're trying to solve. For example, if you had a constraint ``A @ x == b`` where ``A`` is a SciPy sparse matrix, then it would not really help to provide us with code that replaced ``A`` by a dense numpy array.

**Comment by YongchangHu** [comment]
Already solved it.
See  https://github.com/cvxgrp/cvxpy/issues/826#issuecomment-648618636

**Comment by rileyjmurray** [comment]
Per @YongchangHu's comment, @BlankCanvasStudio's corroboration of that comment, and PR #1074, I belive this issue is fixed on CVXPY's master branch. Anyone who is still experiencing problems please let us know.
