### ISSUE TITLE
MIP Problem

### ISSUE THREAD

**Issue by wade2018** [cvxgrp/cvxpy#959]
I have a problem: For example, I create a Variable called w, then i need to set a constraint which is the num about w > 0 should bigger than a integer.  For more details:
import cvxpy as cp
x = cp.Variable(5)
alpha = np.array([0.3, 0.1, 0.4, 0.8, 0.9])
cons = [x >= 0.2, x <= 1, cvx.sum(x) == 1, cvx.sum_largest(x, 2) >= 1]
prob = cvx.Problem(cvx.Maximize(obj), cons)
prob.solve(verbose=True, qcp=True)

but cvxpy raise error。How to solve it, should i change the cons express>

**Comment by akshayka** [comment]
Can you paste the entire error message here?

**Comment by akshayka** [comment]
Additionally, can you post the entire code snippet that produces the error? (I don't see the variable `obj` being created in the code you included.)

**Comment by wade2018** [comment]
> Additionally, can you post the entire code snippet that produces the error? (I don't see the variable `obj` being created in the code you included.

Thanks, and i find my constraint is called cardinality constraint, and i find a way to solve it.Thank you for your reply.
