### ISSUE TITLE
DCPError : expr.is_dcp() returns False for expressions of the form w.T@w

### ISSUE THREAD

**Issue by sadimanna** [cvxgrp/cvxpy#961]
**Describe the bug**
Any expression of the form x.T@P@x in cvxpy gives DCPError. When checked if the expression is DCP or not, expr.is_dcp() return False.

**To Reproduce**

    import cvxpy as cp
    import numpy as np

    alphas = cp.Variable((2*NUM,1))
    Cd = cp.Parameter()
    Cd.value = 0.95

    alphas_constraint_1 = [alphas[i] >=0 for i in range(2*NUM)]
    alphas_constraint_2 = [alphas[i] <= Cd for i in range(2*NUM)]
    alpha_y_constraint = [alphas.T@y == 0]

    constraints = alphas_constraint_1 + alphas_constraint_2 + alpha_y_constraint

    K = y[:,None]*x
    K = np.dot(K,K.T)

    objective_dual = cp.Minimize(cp.sum(alphas)-alphas.T@K@alphas)

    prob_dual = cp.Problem(objective_dual,constraints)

**Expected behavior**
As shown in various examples on the cvxpy tutorials, the above problem is expected to run without failure.

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.1.0a3

**Additional context**
The problem I am trying to solve here is the dual form of SVM
Link to [question](https://stackoverflow.com/questions/60606336/getting-dcperror-when-trying-to-solve-dual-form-of-svm-using-cvxpy) posted on Stackoverflow

**Comment by SteveDiamond** [comment]
You need to use the ``quad_form`` atom, as in ``quad_form(x, P)``.

**Comment by akshayka** [comment]
@sadimanna , please read the documentation on DCP here: https://www.cvxpy.org/tutorial/dcp/index.html

DCP is a grammar for constructing convex expressions, using a simple composition rule. Once you learn this grammar (it's just one rule), you should be able to easily express essentially any convex expression in CVXPY.

**Comment by sadimanna** [comment]
> You need to use the `quad_form` atom, as in `quad_form(x, P)`.
@SteveDiamond 
I have tried using 
 `-cp.sum(alphas)+0.5*cp.quad_form(alphas,K)`
But I still get the same error
