### ISSUE TITLE
DCPError : expr.is_dcp() returns False for expressions of the cp.quad_form(w,P)

### ISSUE THREAD

**Issue by sadimanna** [cvxgrp/cvxpy#962]
**Describe the bug**
Any expression of the cp.quad_form(w,K) in cvxpy gives DCPError. When checked if the expression is DCP or not, expr.is_dcp() return False.

**To Reproduce**

    import cvxpy as cp
    import numpy as np

    DIM = 2
    NUM = 50
    #COLORS = ['red', 'blue']
    M1 = np.ones((DIM,))
    M2 = 2 * np.ones((DIM,))
    C1 = np.diag(0.3 * np.ones((DIM,)))
    C2 = np.diag(0.2 * np.ones((DIM,)))

    def generate_gaussian(m, c, num):
         return np.random.multivariate_normal(m, c, num)

    NUM = 50
    x1 = generate_gaussian(M1, C1, NUM)
    y1 = np.ones((x1.shape[0],))
    x2 = generate_gaussian(M2, C2, NUM)
    y2 = -np.ones((x2.shape[0],))
    # join
    x = np.concatenate((x1, x2), axis = 0)
    y = np.concatenate((y1, y2), axis = 0)
    print('x {} y {}'.format(x.shape, y.shape))

    alphas = cp.Variable(2*NUM)
    Cd = cp.Parameter()
    Cd.value = 0.95

    alphas_constraint_1 = [alphas[i] >=0 for i in range(2*NUM)]
    alphas_constraint_2 = [alphas[i] <= Cd for i in range(2*NUM)]
    alpha_y_constraint = [alphas.T@y == 0]

    constraints = alphas_constraint_1 + alphas_constraint_2 + alpha_y_constraint

    K = y[:,None]*x
    K = np.dot(K,K.T)

    objective_dual = cp.Minimize(-cp.sum(alphas)+cp.quad_form(alphas,K))

    prob_dual = cp.Problem(objective_dual,constraints)

    prob_dual.solve()

Posting this again as the previous issue was closed before I confirmed that my problem was solved.

**Expected behavior**
As shown in various examples on the cvxpy tutorials, the above problem is expected to run without failure.

**Version**
 - OS: Windows 10
 - CVXPY Version: 1.1.0a3

**Additional context**
The problem I am trying to solve here is the dual form of SVM
Link to [question](https://stackoverflow.com/questions/60606336/getting-dcperror-when-trying-to-solve-dual-form-of-svm-using-cvxpy) posted on Stackoverflow 

![Capture](https://user-images.githubusercontent.com/21175586/76284731-1abe1b80-62c4-11ea-9ea4-eebe483ea0f5.JPG)

**Comment by akshayka** [comment]
What is `y`? What is `x`? Please provide a complete reproducible example; we cannot help otherwise.

**Comment by sadimanna** [comment]
@akshayka I have updated the code. I also ran a example code from this [link](https://nbviewer.jupyter.org/github/cvxgrp/cvx_short_course/blob/master/applications/worst_case_analysis.ipynb), which seems to work fine, but my code doesn't work. I replaced the variables from my code into the code from the link and it seems that **K** seems to be the real problem here.

**Comment by sadimanna** [comment]
@akshayka  it will be very helpful if you can tell why the code is not working. As I mentioned, the code in the example works fine, but shows the same error once I replace "Sigma_nom" with "K" in my code.

**Comment by akshayka** [comment]
I think your matrix K is very (very) slightly indefinite, numerically. We should maybe have a better way of checking definiteness in the quad_form atom. For now, you can try deleting the line K = np.dot(K,K.T), and replacing the quad form with cp.sum_squares(K.T @ alphas).

**Comment by sadimanna** [comment]
Yes, replacing the quad form with cp.sum_squares(K.T @ alphas) worked. But the values of w and b obtained from alphas is very small, of the order of 1e-13. But it worked. Thank you.
