### ISSUE TITLE
Warm start support for solvers other than SCS

### ISSUE THREAD

**Issue by sdementen** [cvxgrp/cvxpy#963]
Hello,

After digging a bit, I found that only SCS supports today a warm start. For other solvers, calling solve a second time (even without changing any parameter), restart the solve algorithm from scratch, without benefiting from the previous solution.

Is it planned to support warm start for other solvers ? For my allocation problem, the ECOS solver is giving the best results (and so specially interested by warm start on this solver).

**Comment by SteveDiamond** [comment]
OSQP also supports warm start. The other solvers don't support warm start to my knowledge (maybe a few). ECOS doesn't unfortunately.

**Comment by rileyjmurray** [comment]
I'll follow-up and say that for conic solvers (like ECOS, MOSEK, or CVXOPT), warm-starting is delicate. The MOSEK developers have mentioned warm-start as something they might do in the future, but it's probably not happening soon.

It's reasonable to ask for warm-start with simplex LP solvers(e.g. GLPK), and mixed-integer solvers. There's a separate ticket about warm starting integer variables (#849 ).

**Comment by sdementen** [comment]
by conic solvers, should I understand they use interior point solvers (vs simple solvers) and that for interior point methods, reusing a previous solution is not that useful/doable ?

I need to solve multiple times the same LP problem where only the objective function is changed. What would be the best strategy (if any) when using conic solvers ?

**Comment by rileyjmurray** [comment]
Yes I should have said interior point solvers; those are the tough ones to warm-start.

If only your objective function is varying then you should find a simplex-based LP solver which supports warm-start. If GLPK has that feature we can try to expose that functionality through cvxpy. I do think most commercial solvers support that feature. Do you have easy access to commercial solvers (ie are you in academia)?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sdementen** [comment]
No, not in academia.
Yet interested by GLPK (I have used GLPK for a long time yet sparsely)
