### ISSUE TITLE
Transpose missing?

### ISSUE THREAD

**Issue by remzawi** [cvxgrp/cvxpy#964]
Hi! The transpose method is listed on the website https://www.cvxpy.org/api_reference/cvxpy.atoms.affine.html?highlight=transpose#cvxpy.atoms.affine.transpose.transpose but is not recognized by Python and not proposed as auto-completion on my install. I installed cvxpy with the pip install command within conda. Except that everything seems to work. Would you have any idea why? Thanks

**Comment by akshayka** [comment]
Hey, good find! Thanks for reporting. Looks like we forgot to expose it. We'll fix that.

In the meantime, you can transpose using the `.T` syntax. For example, if `expr` is a CVXPY expression, just write `expr.T`.

**Comment by remzawi** [comment]
Okay thanks!
