### ISSUE TITLE
conditional statements in constraints 

### ISSUE THREAD

**Issue by jask1** [cvxgrp/cvxpy#971]
Hi - One of my decision variable `x` (of size `n`) is constrained:

> -M <= x <= M

I needed to change the bounds of some entries of `x` (say i = 2, 5, 10) to be `B_i` and leave the bounds of other entries to be `M`. Can I add if statements within a for loop to over-ride the above bounds, e.g., 

idx = [2, 5, 10]
for i = 1:length(idx)
      -B_i <= x(i) <= B_i

Any advice on effectively doing this would be much appreciated. Thank you.

**Comment by rileyjmurray** [comment]
I assume this is about updating the values in ``M`` after already using it in some cvxpy Problem. If that's the case, you can do this by creating a Parameter object. I.e. ``M_param = cvxpy.Parameter(shape=M.shape, value=M)``. If you need to update the value of M_param, just execute ``M_param.value = updated_M``, or write ``M_param[idx] = scalar_value`` to update components one at a time.

You should specifically avoid looping over indices and creating new constraints. It takes cvxpy longer to pass your problem to a solver if you do that.

Other things of note:
1. You can't index cvxpy variables by ``()``, you need to use ``[]``. So ``x[i]`` is allowed where ``x(i)`` is not. This is standard across all of python.
2. constraints ``-B_i <= x(i) <= B_i`` aren't allowed in cvxpy. You have to specify the bounds separately, ``con1 = -B_i <= x[i]``, ``con2 = x[i] <= B_i``, ``cons = [con1, con2]``.

**Comment by jask1** [comment]
Thank you for your reply. I actually need to update `M` with `B_i` for some entries `i` in the variable `x` and leave the other entries of `x` to have bounds `M`. In this case, should I follow your advice (2) and define the bounds `con1, con2` before moving to solve the problem?
