### ISSUE TITLE
cvxpy solver error:SolverError: The solver GLPK_MI is not installed.

### ISSUE THREAD

**Issue by sahsoni** [cvxgrp/cvxpy#972]
I'm new to cvxpy. Installed cvpxy using following command
`conda install -c conda-forge lapack
conda install -c cvxgrp cvxpy
`
But while I'm trying to run the code `knapsack_problem.solve(solver=cvxpy.GLPK_MI)`, I'm getting error message `SolverError: The solver GLPK_MI is not installed.`

**Comment by rileyjmurray** [comment]
GLPK is not installed by default. You can access GLPK by installing CVXOPT first.

**Comment by h-vetinari** [comment]
We ran into the same issue, but with CVXOPT installed and importable, and `GLPK_MI` showing up in the installed solvers:
```
> print(cvxpy.installed_solvers())
['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCS']
```

With `1.0.25` (installed through conda on windows), when trying to solve a problem with the solver, we got:
```
> prob.solve(solver=cvxpy.GLPK_MI)
[...]
SolverError: The solver GLPK_MI is not installed
```

With `1.0.27`, the problem is not there anymore. Not sure if this is the exact cause, just reporting that this solved it for us.

**Comment by robertmartin8** [comment]
I was having some troubles with python 3.9.1. I created a fresh virtualenv, then ran 

```
> pip install cvxpy
> pip install cvxopt

python
>>> import cvxpy; cvxpy.installed_solvers()
['CVXOPT', 'ECOS', 'ECOS_BB', 'OSQP', 'SCS']
```

So it seems that in 3.9.1, CVXOPT is not coming with GLPK stuff by default. I was able to fix by running the following:

```
pip uninstall cvxopt
export CVXOPT_BUILD_GLPK=1
pip install cvxopt --no-binary cvxopt
```

Might be worth updating the cvxpy docs to mention this? The relevant part of cvxopt installation docs are [here](https://cvxopt.org/install/#customizing-the-setup-script).

**Comment by rileyjmurray** [comment]
@robertmartin8 The CVXOPT documentation doesn't mention support for python 3.9. From the look of things, they intend to ship their pre-built packages with GLPK (https://cvxopt.org/install/index.html#installing-a-pre-built-package).

Some other notes: CVXOPT isn't required by CVXPY. However, we do try to run continuous integration tests against CVXOPT. I recently updated our CI builds and found that we cannot use CVXOPT with python 3.9 on an OS other than Windows. I saw errors unrelated to GLPK.

There is a recent mention of a packaging error with CVXOPT: https://github.com/cvxopt/cvxopt/issues/180. My recommendation would be to post a GitHub issue in their repo, pointing out that GLPK seems to not be bundled by default.

**Comment by robertmartin8** [comment]
Cheers Riley, my bad for not checking 3.9 support when I upgraded, it's a bad habit 😬 . 

I required CVXOPT so that I could solve a mixed-integer program – hopefully a future version of CVXPY will ship with a MIP solver. 

See you at the next meetup!
Robert

**Comment by rileyjmurray** [comment]
No worries, Robert. I can say that you should be able to use ECOS_BB with cvxpy's default python 3.9 distribution. I'd just caution against that unless you warn your users. If your problems are small you could add XPRESS as a dependency -- it comes with a decent community license and is easily available via pip. For advanced users that cannot afford a commercial license, you can suggest that they install SCIP.

**Comment by GEB-cell** [comment]
Thanks so much. Problem solved!! By the way, if you follow the steps above but no reaction. Maybe you can try to restart the complier~~

**Comment by chanansh** [comment]
> Thanks so much. Problem solved!! By the way, if you follow the steps above but no reaction. Maybe you can try to restart the complier~~

how did you solve it?

**Comment by tom-shlomo** [comment]
> I was having some troubles with python 3.9.1. I created a fresh virtualenv, then ran
> 
> ```
> > pip install cvxpy
> > pip install cvxopt
> 
> > python
> Python 3.9.1 (default, Dec 10 2020, 10:36:41) 
> [Clang 11.0.0 (clang-1100.0.33.17)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import cvxpy; cvxpy.installed_solvers()
> ['CVXOPT', 'ECOS', 'ECOS_BB', 'OSQP', 'SCS']
> ```
> 
> So it seems that in 3.9.1, CVXOPT is not coming with GLPK stuff by default. I was able to fix by running the following:
> 
> ```
> pip uninstall cvxopt
> export CVXOPT_BUILD_GLPK=1
> pip install cvxopt --no-binary cvxopt
> ```
> 
> Might be worth updating the cvxpy docs to mention this? The relevant part of cvxopt installation docs are [here](https://cvxopt.org/install/#customizing-the-setup-script).

Thanks, this helped!
For anyone else encountering this: I also had to edit the paths to GLPK. For example, what worked for me is:
```
CVXOPT_BUILD_GLPK=1 CVXOPT_GLPK_LIB_DIR=/opt/homebrew/Cellar/glpk/5.0/ CVXOPT_GLPK_INC_DIR=/opt/homebrew/Cellar/glpk/5.0/include CVXOPT_SUITESPARSE_LIB_DIR=/opt/homebrew/Cellar/suite-sparse/5.13.0/lib/ CVXOPT_SUITESPARSE_INC_DIR=/opt/homebrew/Cellar/suite-sparse/5.13.0/include/ pip install cvxopt --no-binary cvxopt
```
 the `CVXOPT_SUITESPARSE_` part seems to only be required for apple silicon (got it from [here](https://github.com/cvxopt/cvxopt/issues/78#issuecomment-1149742696))
