### ISSUE TITLE
How to change the properties of variables, such as boolean

### ISSUE THREAD

**Issue by PanZhanhua** [cvxgrp/cvxpy#986]
### Description
I have a need to solve a problem **twice**. 
The **mixed integer programming** is used for the first time. 
After obtaining the calculation result, the calculation result is used as the constraint for the second time, and then the **linear programming** is used again to solve, the purpose is to obtain the **shadow price** of other variables.
After reading the documentation carefully, I did not find a solution, and now my solution is as follows
 
### My solution
```
# First
 # boolean = True
var  = Variable((3, 4),boolean=True) 
var1 = Variable() 
some_constrants = [...]
prob = cp.Problem(cp.Maximize(cp.sum(var)+cp.sum(var1)),
                           some_constrants)
prob.solve()

# And Then
# boolean = False
fixed_var = var == var.value
var.attributes['boolean']=False
var.boolean_idx=[]
prob1 = cp.Problem(prob.objective,
                  prob.constraints+[fixed_var])
prob1.solve()
```

**I know this may be a stupid method, but I did not think of other better ways.**

### The solution I hope is as follows

```
# And Then
# boolean = False
var.fixed_value(var.value)
var.boolean=False
prob1 = cp.Problem(prob.objective,
                  prob.constraints)
prob1.solve()
```

**Comment by PanZhanhua** [comment]
I found another feasible way is to customize the **solve_via_data** method：

```
# MIP 
def solve_via_data_1(data, warm_start, verbose, solver_opts, solver_cache=None):
        # some code
        for i in data[s.BOOL_IDX]:
            model.variables.set_types(var_idx[i],
                                      model.variables.type.binary)
        # some code

# LP
def solve_via_data_2(data, warm_start, verbose, solver_opts, solver_cache=None):
        # some code
        # for i in data[s.BOOL_IDX]:
        #     model.variables.set_types(var_idx[i],
        #                              model.variables.type.binary)
        model.variables.add(obj=var,
                                           lb=var.val,
                                           ub=var.val)
        # some code

data, chain, inverse_data = prob.get_problem_data(cp.CPLEX)
soln1 = solve_via_data_1(data,warm_start=False, verbose=False)

soln2 = solve_via_data_2(data,warm_start=True, verbose=False)
```

**Comment by akshayka** [comment]
@PanZhanhua , that's a good question.

CVXPY problems are meant to be immutable, by design (with one exception: you can change the problem data by changing the value of CVXPY Parameters). Immutability simplifies much of the logic in analyzing and compiling problems. This means that, as of now, there's no supported way to modify the attributes of a Variable after it's been created. Perhaps we should make that clearer in the documentation.

Instead, we would recommend creating new Variable objects and a new Problem object, from scratch. Hopefully this isn't too much effort on your part. 

The developers have had discussions about adding a way to 'relax' problems, which would drop/relax boolean and integer attributes. We might add such a feature in the future, but we don't have any concrete plans for doing so.

**Comment by PanZhanhua** [comment]
@akshayka Thank you for your patient explanation.I found a way to improve the speed, hope to help the development of this project.

**1, Getting the standard form(Takes about 60 seconds)**
`data, chain, inverse_data = problem.get_problem_data(cp.CPLEX)`

**2, solve_via_data(Takes about 60 seconds)**
`soln = solve_via_data(problem, data)`
Happily, soln['model'] return a model ,it is cplex.Cplex().

**3,Use soln['model'] for the second solution(Takes about 30 seconds)**
Take soln['model'] as input. Call the method of docplex to achieve my purpose
```
for i in data[s.BOOL_IDX]:
        model.variables.set_types(var_idx[i],model.variables.type.continuous)
for i, j in zip(data[s.BOOL_IDX], fixed_val):
        model.variables.set_lower_bounds(var_idx[i],j)
        model.variables.set_upper_bounds(var_idx[i], j)

       #other code...

model.set_problem_type(model.problem_type.LP)
model.solve()
```

**In general，The total time it takes is 60+60+30=150(s)**
If I re-model and solve it, it takes **240** seconds in total.
I saved 60 seconds for the second get_problem_data, and 30 seconds for the second solve_via_data.
In solve_via_data, it takes 30 seconds to process the data, and 30 seconds to solve using CPLEX.

**That's it**
- get_problem_data  *  1   #save 60s
- "process the data"  * 1  #save 30s
- model.solve()  * 2

Finally, the sad thing is that I think the **Warm start** in the document is very useful, but I cannot use it normally.

I found that modeling twice and using GUROBI to solve twice only took 150s(CPLEX is 240s), which is the same as the result of my painstakingly modifying the program. 😭

**Comment by SteveDiamond** [comment]
@PanZhanhua Thanks for letting us know! Changing variable properties is an interesting situation where we could definitely cache something, but it would add a lot of code complexity and so probably not something we will add.
