### ISSUE TITLE
Google Group not public

### ISSUE THREAD

**Issue by cdeil** [cvxgrp/cvxpy#994]
Can you please change the setting on https://groups.google.com/forum/#!forum/cvxpy to public?

I currently get this:

![Screenshot 2020-04-10 at 22 56 25](https://user-images.githubusercontent.com/852409/79022669-c6d27b00-7b7e-11ea-9074-1a44cddbbdbb.png)

**Comment by SteveDiamond** [comment]
Hopefully fixed. I've been kind of neglecting the google group, probably better to post here or on stackoverflow.

**Comment by cdeil** [comment]
It's fixed. Thank you!
