### ISSUE TITLE
pip is still installing multiprocess

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/cvxpy#996]
**Describe the bug**
A while ago I removed all dependency in cvxpy on the package multiprocess. But whenever I install cvxpy through pip it sill pulls in the multiprocess package. This should be fixed somehow.

**To Reproduce**
Try pip installing cvxpy.

**Expected behavior**
When we install via pip, multiprocess should *not* be installed.

**Version**
 - OS: Mac
 - CVXPY Version: 1.0.31

**Comment by akshayka** [comment]
The dependency on multiprocess was removed in 1.1 (this can be verified by looking at master). That change was never backported to 1.0.x.

This issue will be resolved once 1.1 is stable (or if it's important you could backport the dependency removal and cut a new release 1.0.32).

**Comment by SteveDiamond** [comment]
I see. That clears it up.
