### ISSUE TITLE
Flexible shape of a parameter

### ISSUE THREAD

**Issue by tschm** [cvxgrp/cvxpy#998]
I optimize over a cloud of points. Some I deal with n=10 points, sometimes with n=100 points, etc.

I wonder whether this makes any sense...
points = cvx.Parameter((_,2), name="points")

Of course, I could replace _ with n=points.shape[0] here but I try to separate the creation of the problem and injecting the parameters as much as I can.

**Comment by SteveDiamond** [comment]
This is a highly requested feature, but unfortunately not one we can add. cvxpy uses information from parameters to cache concrete, realized matrices. So we need real dimensions. One possibility would be to create multiple problems with different dimensions, and reuse the one that is closest in size to what you need.

**Comment by tschm** [comment]
thank you @SteveDiamond
