### ISSUE TITLE
Matrix power (sort of)

### ISSUE THREAD

**Issue by SteveDiamond** [cvxgrp/cvxpy#999]
I'd like to add an atom that implements the following function. Let ``x in R^n`` and ``A in R^{m x n}``. Then ``f(A,x)`` outputs an m-vector, with entries given by
```
f(A,x)_i = x_1^A_{i1}*x_2^A_{i2}*...x_n^A_{in}.
```
So it's sort of like matrix multiplication, but where you take powers instead of multiplying by coefficients and instead of summing you multiply. 

The idea comes from [this paper](https://arxiv.org/pdf/2001.03649.pdf) I wrote on log-linear dynamical systems. I haven't needed an atom yet because I do the log-transform by hand, but @moehle suggested a posynomial formulation (a sum of such functions), and in general it would be cool to see what we can compose this with.

Anyway this function is not hard to add, but I'm not sure what name to call it and am looking for suggestions.

**Comment by SteveDiamond** [comment]
After some thought, my proposal is the “geometric matrix multiplication”, ‘’gmatmul’’ in cvxpy. Mathematically, denoted A♢x 😜

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rileyjmurray** [comment]
I like this idea! And the notation is nice. Since python doesn't allow the creation of new infix operators, we'd probably have to stick with a named function like ``cp.gmatmul`` as you said.

**Comment by akshayka** [comment]
If x is elementwise positive, each entry in the expression you’ve written would be a monomial, ie log-log affine. So you could compose lots of things with it.

I agree, it’s a cool atom!
